### PR TITLE
Acta chirurgiae orthopaedica ACTA

### PR DESCRIPTION
**Pull request by gehmert**
Citation style for zotero for the journal Acta chirurgiae orthopaedica et traumatologiae Cechoslovaca

### CODE REVIEW

**Comment by libora** [comment]
There is a lot of errors in your style. See https://travis-ci.org/citation-style-language/styles/builds/202193628. If you need any help see http://docs.citationstyles.org/en/stable/specification.html or contact me by email (libor.ansorge(at)volny.cz)

**Comment by libora** [comment]
There is a lot of errors in your style. See https://travis-ci.org/citation-style-language/styles/builds/202193628 for details. You can find Specification of CSL on http://docs.citationstyles.org/en/stable/specification.html. If you need any help send me message by email (libor.ansorge(at)volny.cz)

**Comment by rmzelle** [comment]
@libora, actually, those errors were all due to the file name and the location (independent CSL styles like this one don't belong in the "dependent" subdirectory).

@gehmert, it looks like this journal publishes in Czech, Slovak, and English. Did you test it for multiple languages? Also, did you base this on another style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

**Comment by gehmert** [comment]
I did not test it for multiple languages. I used Vancouver style and
changed everything as required for this specific Journal.
​

**Comment by libora** [comment]
There so no differences in English and Czech/Slovak version of Literature part in instruction for authors on the web page of the journal. The English version of CSL style can be used for all languages.
Template link is http://www.achot.cz/pokyny.php in Czech or http://www.achot.cz/instruction.php in English

**Comment by rmzelle** [comment]
@libora, so we can just fix the style to "en-GB" (British English)?

**Comment by libora** [comment]
@rmzelle  I think yes

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
