### PR TITLE
Update multidisciplinary-digital-publishing-institute.csl

### PR DESCRIPTION
**Pull request by damnation333**
Via: http://support.mendeley.com/customer/portal/questions/17063260-molecules-style (people are 
left alone over there...)
and via: https://forums.zotero.org/discussion/65884/style-error-insects
add doi, URL, ISBN

Seems like the publisher came out with a new style. The pdf with the style guide is dated 30/05/2017.

### CODE REVIEW

**Comment by adam3smith** [comment]
@damnation333 Mendeley actually has an error report form for citation styles that goes directly to us:
http://support.mendeley.com/customer/portal/articles/1392513-i-would-like-to-report-an-incorrect-citation-style-in-mendeley-

I'm a little behind on those because they changed things around there, but catching up.

**Comment by adam3smith** [comment]
I'd say ~2/week on average and about half are "valid". The others are data issues, Mendeley issues, or people are wrong about the citation style (most people are wrong about APA most of the time ;)

**Comment by adam3smith** [comment]
Didn't it look like they wanted both doi and URL for articles?

**Comment by damnation333** [comment]
@adam3smith 
In the actual guidelines.pdf there is nothing about that. Just the examples on the website. I went with the more official document.

**Comment by adam3smith** [comment]
OK, let's take it as it is for now. Thanks!

**Pull request merged**
