### PR TITLE
Create harvard-university-of-essex.csl

### PR DESCRIPTION
**Pull request by CCCowley**

### CODE REVIEW

**Comment by rmzelle** [comment]
@CCCowley, thanks. Is the Essex Style Guide available online?

**Comment by adam3smith** [comment]
https://www.essex.ac.uk/student/academic-skills/referencing-guides suggests that the university follows Cite Them Right, which we already have

**Comment by CCCowley** [comment]
Hi Sebastian,

That is what I was using. Unfortunately the minimum number before et al was too high (it should be 2 for citations and 6 for bibliography, that’s all I’ve changed from the Cite them rite template.

Thanks,

**Comment by adam3smith** [comment]
Hmm -- where to they say that? Our Cite Them Right style follows the book afaik

**Comment by CCCowley** [comment]
Yeah, I think its the University that is being inconsistent.

Here’s what I can find:

from here:
https://www1.essex.ac.uk/csee/documents/Appendix1-Referencing.pdf

**Comment by adam3smith** [comment]
I'd inquire with the library -- those are four years old, and we frequently hear from UK libraries that they're updating their guidelines, so it might just be that these are the old ones and the current Cite Them Right, which they link to prominently, is correct.

**Comment by CCCowley** [comment]
No problem, I’ll reach out to them and let you know what they say!

**Comment by rmzelle** [comment]
@CCCowley, did you ever hear back?

**Comment by rmzelle** [comment]
Closing because of inactivity.

**Pull request closed without merging**
