### PR TITLE
Create Cardiff University - Vancouver.csl

### PR DESCRIPTION
**Pull request by YoungZoe**
This style gets used by staff and students of Cardiff University. I have tried to replicate the style that we use from the guidance as closely as possible.

### CODE REVIEW

**Comment by YoungZoe** [comment]
don't understand the failure as it passed the CSL schema.  I thought i had followed the naming convention that you had given previously for Cardiff University - Harvard, http://www.zotero.org/styles/harvard-cardiff-university.
Please help

**Comment by adam3smith** [comment]
You can click on "test report" for details -- the problem here was that you had left an unused macro in the style.

Apart from that it looks good. A couple of questions:
1) Presumably this style will only get used in English, right?
2) Which exact CSL style did you base this on? Plain Vancouver?

**Comment by YoungZoe** [comment]
Hi Sebastian,

Yes, it will only be used in English.

It was based on plain Vancouver.

Many thanks for your help
Zoe

[dark open door icon 30 percent]Book a UG lunchtime drop-in      <http://www.bit.ly/bls-drop-ins>  [dark calendar icon 30 percent]    Book a staff/PG 1-2-1<bit.ly/bls-121s>
          www.bit.ly/bls-drop-ins<http://www.bit.ly/bls-drop-ins>                                   www.bit.ly/bls-121s<http://www.bit.ly/bls-121s>

Mrs Zoe Young BSc(Hons) MSc(ECON)

Subject Librarian, School of Healthcare Sciences, Optometry and Pharmacy
Health Library
University Library Service
Cardiff University
Cochrane Building
Heath Park
Cardiff
CF14 4YU
Tel: 029 22510196
Web: www.cardiff.ac.uk<http://www.cardiff.ac.uk/>
E-mail: YoungZ@cardiff.ac.uk<mailto:YoungZ@cardiff.ac.uk>

Registered charity: no. 1136855

Winner of THE Outstanding Library Team Award 2015

Proud to hold the Customer Service Excellence Standard®

The University welcomes correspondence in Welsh or English.


Mrs Zoe Young BSc(Hons) MSc(ECON)

Llyfrgellydd Pwnc, Ysgol Gwyddorau Gofal Iechyd, Optometreg a Fferylliaeth
Llyfrgell Iechyd
Gwasanaeth Llyfrgell y Brifysgol
Prifysgol Caerdydd
Adeilad Cochrane
Parc y Mynydd Bychan
Caerdydd
CF14 4YU
Ffôn: 029 22510196
Gwefan: www.caerdydd.ac.uk<http://www.caerdydd.ac.uk/>
E-bost: YoungZ@caerdydd.ac.uk<mailto:YoungZ@caerdydd.ac.uk>

Elusen gofrestredig: rhif 1136855

Enillydd 2015 Gwobr Tîm Llyfrgell Ragorol y THE

Rydym yn falch o fod wedi ennill safon Rhagoriaeth Mewn Gwasanaethau Cwsmeriaid ®

Mae'r Brifysgol yn croesawu gohebiaeth yn Gymraeg neu'n Saesneg.

**Comment by adam3smith** [comment]
Great, thanks Zoe

**Pull request merged**
