### PR TITLE
remove name-as-sort-order="all"

### PR DESCRIPTION
**Pull request by reagle**
First Monday requires "First Last, First Last, and First Last", remove the attribute that was preventing that.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! Given what you write, you should also delete the delimiter-precedes-last="never" attribute (since there is a comma before the and).

**Comment by reagle** [comment]
I've not used the edit-and-merge on Github feature before. Are you asking me to do this? I'm not sure how.

**Comment by adam3smith** [comment]
no, you can simply update your pull request by using the pencil button here to edit the file:
https://github.com/reagle/styles/blob/patch-1/first-monday.csl 
let us know when you're done

**Comment by reagle** [comment]
Okay, done.

**Comment by adam3smith** [comment]
great, thanks!

**Pull request merged**
