### PR TITLE
[ASM] Re-generate dependent styles with short title

### PR DESCRIPTION
**Pull request by aurimasv**
citation-style-language/utilities#22

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks! Are you submitting? :)

**Comment by aurimasv** [comment]
I am indeed. :-)

**Comment by rmzelle** [comment]
Good luck!

**Comment by rmzelle** [comment]
@aurimasv, shouldn't the ASM CSL style be double-spaced? (as it happens, I'm prepping a manuscript for another ASM journal)

**Comment by aurimasv** [comment]
It's possible. The text is and since they don't explicitly mention anything about references, I guess they are too. Looking at recently accepted manuscripts to MCB, about half of them have double-spaced references and half have single-spaced, but given CSL's popularity that might not mean much (it does mean that the editors probably don't care).

**Comment by aurimasv** [comment]
Good luck, btw!

**Comment by rmzelle** [comment]
http://aem.asm.org/site/misc/journal-ita_org.xhtml#link00 says "Type every portion of the manuscript double-spaced (a minimum of 6 mm between lines), including figure legends, table footnotes, and references"

**Comment by aurimasv** [comment]
Good catch. Ooops.

**Pull request merged**
