### PR TITLE
Update the-astrophysical-journal.csl

### PR DESCRIPTION
**Pull request by libora**
https://forums.zotero.org/discussion/comment/276621

### CODE REVIEW

**Comment by adam3smith** [comment]
Yes, sorry, I reverted that.


If you can fix the citation-format of the three dependents in your branch to author-date, that'd be great:
the-astronomical-journal
the-astrophysical-journal-supplement-series
the-astrophysical-journal-letters

otherwise I'll do that tomorrow.

**Comment by libora** [comment]
OK take me few hours, now I have to do a correction an article in next 3
hours, an then I will go back to this style.

2017-05-23 8:28 GMT+02:00 Sebastian Karcher <notifications@github.com>:

**Comment by libora** [comment]
@adam3smith It is done.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
