### PR TITLE
Create iainutuban-tarbiyah.csl

### PR DESCRIPTION
**Pull request by LPPMiainutuban**
Edited in 2023

### CODE REVIEW

**Comment by LPPMiainutuban** [comment]
Please, let me know about "whats next step after this?" 
Sorry I just learn about this thing.

**Comment by LPPMiainutuban** [comment]
Thanks

**Comment by LPPMiainutuban** [comment]
Please let me know, how long this pull request merged into CSL master?

**Comment by LPPMiainutuban** [comment]
hello mr @adam3smith can you help me to merge this pull request into CSL master??

**Comment by LPPMiainutuban** [comment]
hello mr @POBrien333, can you help me to merge? Our institution need this soon for student thesis citation system. Thanks

**Comment by adam3smith** [comment]
Sorry for the delay -- I note that you want people to use Mendeley. FWIW, we've heard from various Mendeley users that they are not currently updating the available styles from this repository effectively. I haven't tested this, but I want to be clear that we have absolutely no way to influence if/when a style becomes available on Mendeley. This style will be available via github immediately and on zotero.org/styles within hours.

**Comment by LPPMiainutuban** [comment]
Thank you so much sir. For the merged our citation style and the
information.

**Pull request merged**
