### PR TITLE
Use "et al" in Romanian

### PR DESCRIPTION
**Pull request by bwiernik**

### CODE REVIEW

**Comment by bwiernik** [comment]
@adam3smith @retorquere Any idea why the CI is broken?

**Comment by retorquere** [comment]
We amended something about how yaml files were loaded (regarding a potential attack vector in YAML loading) but I honestly have no idea where we did that.

**Comment by POBrien333** [comment]
via https://forums.zotero.org/discussion/120338/romanian-apa-citation-zotero-help#latest

**Comment by retorquere** [comment]
I've reverted that fix, but this pr will have to merge master to get it.

**Pull request merged**
