### PR TITLE
Create brepols.csl

### PR DESCRIPTION
**Pull request by carljohanberglund**
New style for Brepols Publishers.

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks for the submission. 

Please don't continue to close the pull request and open new ones. If you need to make additional changes, please make them in this existing pull request

**Comment by adam3smith** [comment]
Thanks! Brepols says to just use MHRA style, which we already have available -- do we need a separate style? If so, how does this one differ from MHRA?

**Comment by adam3smith** [comment]
@carljohanberglund -- see my question about MHRA above, please

**Comment by adam3smith** [comment]
Closing for inactivity -- we're happy to re-open if you come back to this in the future; just post here.

**Pull request closed without merging**
