### PR TITLE
Create journal-of-nanoscience-and-nanotechnology.csl

### PR DESCRIPTION
**Pull request by fvmolina**
Style for the Journal of Nanoscience and Nanotechnology (American Scientific Publishers), adapted from the sister publication Journal of Neuroscience and Neuroengineering

### CODE REVIEW

**Comment by rmzelle** [comment]
The format differs?

**Comment by fvmolina** [comment]
It differs in two points (at least as the other journal style is today):


1. No title for journal articles. 

2. The year should be in plain text, not bold. 

Regards 

El 2015-06-10 21:05, Rintze M. Zelle escribió: 

> The format differs? 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/citation-style-language/styles/pull/1582#issuecomment-110951898

**Comment by rmzelle** [comment]
Okay, just making sure we need an "independent" CSL style. Thanks for contributing!

**Comment by fvmolina** [comment]
You are welcome. 

El 2015-06-10 22:12, Rintze M. Zelle escribió: 

> Okay, just making sure we need an "independent" CSL style. Thanks for contributing! 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/citation-style-language/styles/pull/1582#issuecomment-110960767

**Pull request merged**
