### PR TITLE
Update harvard-anglia-ruskin-university.csl

### PR DESCRIPTION
**Pull request by POBrien333**
add DOI

via https://github.com/citation-style-language/styles/pull/4130#issuecomment-791460222

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, did you confirm this in the style guide? The quick guide and full guide at https://library.aru.ac.uk/referencing/harvard.htm both seem to be from 2019.

**Comment by POBrien333** [comment]
Yeah, check "Articles with DOI" just show an example of an article with volume, page AND DOI.
https://library.aru.ac.uk/referencing/harvard.htm

**Comment by rmzelle** [comment]
@POBrien333, thanks!

**Comment by Harbender** [comment]
> Yeah, check "Articles with DOI" just show an example of an article with volume, page AND DOI.
> 
> https://library.aru.ac.uk/referencing/harvard.htm

Problem is with mendeley under the type(s) there is only limited selection 
Eg there's no articles with doi choice.. only journal article
Any suggestions how to overcome this issue?
And there is an error -- articles with doi 
They have the [e-journal] after the journal title name 

If possible mayb allow the old csl file available too incase someone needs the old version. Sorry im still new to this github and the codes image

**Comment by POBrien333** [comment]
In Mendeley you can add the DOI in its specific field. Under "Catalog IDs". Then it'll be able to pull it into the output.

**Pull request merged**
