### PR TITLE
Create iso690-author-date-de.csl

### PR DESCRIPTION
**Pull request by ApolloLV**
Starting translation to German

### CODE REVIEW

**Comment by ApolloLV** [comment]
I just tried this style on a thesis with Zotero, it looks fine to me.
I will create a new merge request if I stumble upon any remaining issues, so feel free to merge this already.

**Comment by adam3smith** [comment]
I thought the ISO690-de norm wanted small-caps/Kapitälchen for last names, not uppercase? Also, did you start the style from scratch, or did you base this on an existing one?

**Comment by ApolloLV** [comment]
I basically translated the existing ISO690-en.

**Comment by ApolloLV** [comment]
The ISO690-de norm wants uppercase, not small-caps, as far as I can tell:
examples_iso690

**Comment by adam3smith** [comment]
A couple of questions:
1. My reading of ISO 690 (and the German DIN ISO interpretations I've found) suggest that names should only by lastname, firstname for the first author, then firstname lastname, i.e. 

> HANCKÉ, Bob, Martin RHODES und Mark THATCHER

2. What's the deal with abstracts in ISO? I don't think they're normal part of a bibliography and people would expect them. Can we remove them?

3. I would expect editors to be included for chapters in edited volumes (MARES in the provided examples). Is that not the case?

Thanks again for your work on this!

**Comment by ApolloLV** [comment]
> A couple of questions:
> 
>     1. My reading of ISO 690 (and the German DIN ISO interpretations I've found) suggest that names should only by lastname, firstname for the first author, then firstname lastname, i.e.
> 
Yes, the first author is to be given as lastname, firstname (5.2.1).
If the current style is incorrect in this regard, we may need to fix the version in other languages
> 
> > HANCKÉ, Bob, Martin RHODES und Mark THATCHER
> 
>     2. What's the deal with abstracts in ISO? I don't think they're normal part of a bibliography and people would expect them. Can we remove them?
As far as I can see, the standard does not even mention abstracts. They also don't show up in any of the examples.
> 
>     3. I would expect editors to be included for chapters in edited volumes (MARES in the provided examples). Is that not the case?
iso690
Sorry, I didn't check. They should be included.

> 
> 
> Thanks again for your work on this!

**Comment by adam3smith** [comment]
great, thanks! Let us know if you find any issues with this.

**Pull request merged**
