### PR TITLE
Create gender-and-society.csl

### PR DESCRIPTION
**Pull request by celia-bouchet**
Citation guidelines for the Gender & Society journal

### CODE REVIEW

**Comment by celia-bouchet** [comment]
I tried to understand what the "may not have any unused macros" correspond to (the CSL style validor was fine)... From what I read [here](https://github.com/citation-style-language/styles/pull/3772), the problem might come from the fact that I rely on a Chicago style (16th edition) to construct this one, and Chicago styles have an exception to the "no unused macro" rule. Do I still need to edit it?

**Comment by adam3smith** [comment]
Not quite, no. No CSL styles should define macros that aren't used. We make an example for Chicago variants so they are easier to update at the same time, but for your style you should delete the unused macros editor and translator

**Comment by celia-bouchet** [comment]
> Not quite, no. No CSL styles should define macros that aren't used. We make an example for Chicago variants so they are easier to update at the same time, but for your style you should delete the unused macros editor and translator

Got it ! Thanks a lot.

**Comment by adam3smith** [comment]
Thanks -- this looks great

**Pull request merged**
