### PR TITLE
Update aquatic-conservation.csl

### PR DESCRIPTION
**Pull request by POBrien333**
closes https://github.com/citation-style-language/styles/issues/5377

### CODE REVIEW

**Comment by JensHegg** [comment]
Example citations are incorrect. 

Fenner example reference should abbreviate the authors with et al. starting after Rocco-Serra with et al. according to the style guide. Should look like this:

Fenner, M., Crosas, M., Grethe, J.S., Kennedy, D., Hermjakob, H., Rocca-Serra, P. et al. (2019). A data citation roadmap for scholarly data repositories. Scientific Data, 6(1), 28. https://doi.org/10.1038/s41597-019-0031-8

(Hancké et al., 2007) in-text citation above is also incorrect. It should be (Hancké, Rhodes & Thatcher, 2007)

**Comment by JensHegg** [comment]
compare to the style in the following link. I downloaded this style, edited in Mendeley after spending some time learning how the styles work, and appear to have fixed the two issues I mentioned above. Use this code if it works. 

https://csl.mendeley.com/styles/14007053/aquatic-conservation-corrected-JH-2

**Comment by POBrien333** [comment]
No need to do this.
Also, if you know CSL, you can always submit your own style fixes and styles. :)

**Comment by rmzelle** [comment]
@POBrien333, @JensHegg, thanks!

**Pull request merged**
