### PR TITLE
Create saglik-bilimleri-universitesi.csl

### PR DESCRIPTION
**Pull request by mcaslan92**
i created a new csl file for Sağlık Bilimleri Üniversitesi

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#csl-style-repository-requirements, we typically require each CSL style to include a link to the format it describes.

**Comment by mcaslan92** [comment]
Hello there,
Yes but it's turkish. If you want you can search the term in document:
"Kaynak" it means reference
Thanks.

28 Şub 2021 Paz 04:15 tarihinde Rintze M. Zelle <notifications@github.com>
şunu yazdı:

**Comment by rmzelle** [comment]
@mcaslan92, thanks. Is that document available online?

Note that you can't email attachments. You can attach documents to GitHub comments via the website.

**Comment by mcaslan92** [comment]
Yes here it is
https://www.sbu.edu.tr/FileFolder/Dosyalar/226a44f5/2017_7/tez-yazim-klavuzu-130a0155.pdf

28 Şub 2021 Paz 19:28 tarihinde Rintze M. Zelle <notifications@github.com>
şunu yazdı:

**Comment by rmzelle** [comment]
Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#8---template-link)

**Comment by mcaslan92** [comment]
Yes it was APA11 .
Thanks

2 Mar 2021 Sal 06:25 tarihinde Rintze M. Zelle <notifications@github.com>
şunu yazdı:

**Comment by rmzelle** [comment]
@mcaslan92, you mean our APA style https://github.com/citation-style-language/styles/blob/master/apa.csl?

**Comment by mcaslan92** [comment]
I downloaded APA11 style from inside of zotero style editor and changed a
few things according to our Sağlık Bilimleri Üniversitesi citation
instructions.

2 Mar 2021 Sal 07:40 tarihinde Rintze M. Zelle <notifications@github.com>
şunu yazdı:

**Comment by adam3smith** [comment]
The style looks fine, but I'm a bit puzzled how you get to the style from the instructions. I'm only seeing a single sample citation (for an internet article) in the document you posted. What am I missing?

**Comment by mcaslan92** [comment]
I'm sorry i dont understand ,which file i posted?

13 Mar 2021 Cmt 06:37 tarihinde Sebastian Karcher ***@***.***>
şunu yazdı:

**Comment by adam3smith** [comment]
Sorry for the delay here -- This does fit with everything that's available in the thesis requirement (et al, journal abbreviations, in-text citations), so taking this as is.

**Pull request merged**
