### PR TITLE
Updates to hiob ludolf style to match aethiopica guidelines

### PR DESCRIPTION
**Pull request by PietroLiuzzo**
I have fixed the thesis extra white space and the year which should go in brackets.
an entire new citation style has been added for encyclopaedia articles
webpages bibliography has been updated. For books (like encyclopaedias) with a main record including short title, this is put first

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
Dear all, I am not quite sure this contribution has gone right. I updated my fork from the upstream master before making a new branch a opening the PR. I hope it is ok, please let me know if I need to do it differently

**Comment by rmzelle** [comment]
> I updated my fork from the upstream master before making a new branch a opening the PR. I hope it is ok, please let me know if I need to do it differently

Yeah, this doesn't look very pretty.

It's usually easier to just ignore the "master" branch of your fork, and just create a new branch off of our "master" branch via the GitHub web interface, per the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style. Feel free to create a new pull request if you want to give that a try.

**Comment by PietroLiuzzo** [comment]
I had been following that, but
I cannot make changes to the file because I need to be on a branch 
but I cannot create a new branch on your master, 
that is way I tried to sync my fork to the upstream repository (this) and then make a branch with the pull request. I will try deleting my fork and forking again then sending the new pr from there

**Comment by rmzelle** [comment]
> I cannot make changes to the file because I need to be on a branch
> but I cannot create a new branch on your master,

If you click the pencil icon at e.g. https://github.com/citation-style-language/styles/blob/master/hiob-ludolf-centre-for-ethiopian-studies.csl, you get a new branch in your own fork. There should be no need to delete your fork.

**Comment by PietroLiuzzo** [comment]
I have now made a new pull request and I am closing this one
https://github.com/citation-style-language/styles/pull/3001

**Pull request closed without merging**
