### PR TITLE
Request for review and assessment of the repa.csl

### PR DESCRIPTION
**Pull request by repajp**
Dear reviewers,

After several attempts, hopefully would like to submit the new version of the repa.csl for review and validation. 
Thank you in advance for your time and for your review.
Note: The proposed style will be applied for 6-journals and also conference proceedings publications.

### CODE REVIEW

**Comment by repajp** [comment]
Many thanks for your kind support and good news :). Since three days we are working on it.

**Comment by rmzelle** [comment]
> The proposed style will be applied for 6-journals and also conference proceedings publications.

@repajp, could you point us to the "instructions to authors" webpages for these 6 journals and, if one exists, the conference proceedings?

**Comment by repajp** [comment]
Sure we will do so, now the REPA journal websites are under maintenance and shortly will be online. So, what is the best option to point the CSL? Is there any standard quotation "    " ? 
Also, still the repa citation is not accessible through Zotero.

**Comment by repajp** [comment]
Sure we will do so, now the REPA journal websites are under maintenance and shortly will be online. So, what is the best option to point the CSL? Is there any standard quotation " " ?
Also, still the repa citation is not accessible through Zotero.

**Comment by rmzelle** [comment]
> Sure we will do so, now the REPA journal websites are under maintenance and shortly will be online. So, what is the best option to point the CSL? Is there any standard quotation " " ?

Some software products like Mendeley have their own interface for accessing our repository styles, but you can always point users to your style(s) in the Zotero Style Repository (e.g. https://www.zotero.org/styles?q=id%3Aapa).

> Also, still the repa citation is not accessible through Zotero.

We haven't accepted your CSL style yet, as I was hoping you could first link to your online style guide. Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

**Comment by repajp** [comment]
I went through the style guide several times :) still, our journals' websites are public. However, please find the linked of author instructions that included and already mentioned citation use:
https://repa.jp/journals/paper-submission-instructions/

**Comment by rmzelle** [comment]
Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by rmzelle** [comment]
And if you can give us a spreadsheet of journal titles, and print/online ISSNs, we can also add 'dependent' styles for these. (see https://github.com/citation-style-language/journals/blob/master/apa/_journals.tab for an example)

**Comment by repajp** [comment]
Dear Zelle,
Thank you for your cooperation. 
This is a standalone citation style based on the unique style such as grouping the vol. no. pp. and etc. without any similarity with existing styles in the same manner

**Comment by repajp** [comment]
We already applied for the ISSN for our upcoming 6-journals, may we request your cooperation on the subject matter later after receiving the ISSNs

**Comment by rmzelle** [comment]
> This is a standalone citation style based on the unique style such as grouping the vol. no. pp. and etc. without any similarity with existing styles in the same manner

Just to make sure we understand each other correctly: I was asking whether you based the CSL style file on an existing CSL style, not whether the REPA citation format is derived from something else. Did you write this CSL style from scratch, or did you start from an existing style?

**Comment by rmzelle** [comment]
> We already applied for the ISSN for our upcoming 6-journals, may we request your cooperation on the subject matter later after receiving the ISSNs

Yes. If the ISSNs are not yet available, we can just accept the REPA CSL style by itself. You can create a new GitHub issue once you have the ISSNs and we'll generate the dependent CSL styles for the journals.

**Comment by repajp** [comment]
For better understanding, our team inspired and analyzed existing styles especially (APA, IEEE, etc.) and in light (observing the structures, establishing relations, variables, and etc.) create a new style, confidently can claim that the REPA style is unique without similarity with the available styles. We think, as per the copyright, we do not imply to acknowledge or be dependent when we had a general observation in the public domain.  
For the ISSNs, we will do as per your advice, thank you.

**Comment by rmzelle** [comment]
Thanks!

**Comment by repajp** [comment]
Dear Zelle, thank you very much for your great cooperation towards the fulfillment of the endeavor. Take care, and stay safe, bye.

**Pull request merged**
