### PR TITLE
Update bursa-uludag-universitesi-fen-bilimleri-enstitusu.csl

### PR DESCRIPTION
**Pull request by ozhansaglik**
Editing et al options. Before this edition, users did edit the bibliography manually; but now it can be done autonomously.

### CODE REVIEW

**Comment by ozhansaglik** [comment]
Hi CSL team,

As you see in inline citations we use Saglik et al. ; but in the bibliography, we should write the name of the all authors, without using "..." or "&" etc.

Can you help?

**Comment by biosainik** [comment]
> 
> 
> Hi CSL team,
> 
> As you see in inline citations we use Saglik et al. ; but in the bibliography, we should write the name of the all authors, without using "..." or "&" etc.
> 
> Can you help?

Can you please give a link to check your standard style of bibliography. Alternately, you may reply with a formatted citation (in your style) of a journal article?

**Comment by biosainik** [comment]
> 
> 
> Hi CSL team,
> 
> As you see in inline citations we use Saglik et al. ; but in the bibliography, we should write the name of the all authors, without using "..." or "&" etc.
> 
> Can you help?

@ozhansaglik  Do you use "and" instead of "&"?

**Comment by ozhansaglik** [comment]
@biosainik Goldmann, W., Hunter, N., Foster, J.D., Salbaum, J.M., Beyreuther, K., Hope, J. 1990. Alleles of a neural protein gene linked to scrapie in sheep. Proc. Natl. Acad. Sci., 87(7): 2476-2480. 

You can download the examples from here. http://www.uludag.edu.tr/fenbilimleri/default/konu/4861

We use "and" only for two authors and never use "&".

**Comment by adam3smith** [comment]
@biosainik thanks for chiming in -- getting some help with style review/fixes would be great! Maybe wait, though, for the review on the style you're submitted so you become a bit more familiar with our procedures and standards before you start helping others (which, again, we would greatly appreciate)

**Comment by biosainik** [comment]
@adam3smith thanks for the gentle advice! As you observe, I am a kind of beginner.
If I understand that right, I am expected to properly go through style fixes, by identifying/rectifying the errors in code with minimum efforts.

By the way, am I allowed to commit to issues/pull requests and edit the styles ?
Thanks!

**Comment by ozhansaglik** [comment]
@adam3smith @biosainik Dear Stephen and Pragaadeesh thank you so much for your help.

**Pull request merged**
