### PR TITLE
Add TravisBuddy Travis-CI build comments

### PR DESCRIPTION
**Pull request by rmzelle**
Test out TravisBuddy (per #3722).

### CODE REVIEW

**Comment by bluzi** [comment]
Hi @rmzelle, just wanted to add that if you guys need any kind of help with @TravisBuddy integration or if you need any special features, feel free to @mention me and I'll do my best to help :)

**Comment by adam3smith** [comment]
@rmzelle what do you think? It seems to me that, given how our tests are built, the gain in clarity is quite modest

**Comment by rmzelle** [comment]
> Hi @rmzelle, just wanted to add that if you guys need any kind of help with @TravisBuddy integration or if you need any special features

@bluzi, thanks! Actually, I'm trying set up a failure and success template (per https://github.com/bluzi/travis-buddy#custom-template), but neither file (travis-buddy-failure-template.md or travis-buddy-success-template.md) seems to have an effect in this PR. Am I doing something wrong?

**Comment by rmzelle** [comment]
> @rmzelle what do you think? It seems to me that, given how our tests are built, the gain in clarity is quite modest

With custom templates (one that doesn't require the failed tests to be expanded) and some regex for extracting just the failed test output (per https://github.com/bluzi/travis-buddy#configuration) I think it would be an improvement. (we would have to figure out how to turn off Sheldon except for the initial post, though, since Travis-CI (still) doesn't allow multiple notification settings for multiple webhook URLs)

**Comment by bluzi** [comment]
> > Hi @rmzelle, just wanted to add that if you guys need any kind of help with @TravisBuddy integration or if you need any special features
> 
> @bluzi, thanks! Actually, I'm trying set up a failure and success template (per [bluzi/travis-buddy#custom-template](https://github.com/bluzi/travis-buddy#custom-template)), but neither file (travis-buddy-failure-template.md or travis-buddy-success-template.md) seems to have an effect in this PR. Am I doing something wrong?

@rmzelle I know it's a bit inconvenient, but currently there is no easy way for us to get the base branch of a PR, so template files only take effect when they are on master. 
Once you'll merge the PR, @TravisBuddy will find those templates on master and will use them in future comments.

**Comment by rmzelle** [comment]
Superseded by our in-house upgrade of Sheldon (see e.g. https://github.com/citation-style-language/Sheldon/pull/15, and pull requests 16-19, and https://github.com/citation-style-language/styles/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Aretorquere)

**Pull request closed without merging**
