### PR TITLE
Update plos.csl (issues re. [internet/preprint])

### PR DESCRIPTION
**Pull request by POBrien333**
Fix issues regarding [internet] and [preprint] for PLoS as per: #4138 (and pointed out again here: https://github.com/citation-style-language/styles/issues/4140#issuecomment-535641750)

Please check carefully if I did this correctly. :)

@dhimmel, can you give this a test ride?

### CODE REVIEW

**Comment by dhimmel** [comment]
In https://github.com/greenelab/meta-review/pull/261, I evaluate the effect of the new PLOS style from https://github.com/citation-style-language/styles/pull/4323/commits/82df7b538c5471ab9806efadc0b2ecf131d24293 on our reference formatting. The result is available in [`manuscript-1.0.18-d0462c5.pdf`](https://github.com/citation-style-language/styles/files/3664081/manuscript-1.0.18-d0462c5.pdf).

I can confirm that `[Internet]` no longer appears for references 1, 10, 15, 25 as documented in https://github.com/citation-style-language/styles/issues/4138#issue-454851781.

`[Preprint]` does not appear for arXiv references, but also appears for references 23, 35, 45, 60, 69 which are not preprints (some are blog posts, but some are journal articles). Furthermore, preprint does not appear for bioRxiv references. Our [CSL JSON](https://github.com/greenelab/meta-review/blob/output/references.json) is located here, if that helps with debugging. I wonder if the method for detecting preprints is too imprecise? Given the current CSL JSON schema, perhaps it is best to not assume anything is a preprint (or perhaps to hardcode a list of preprint servers).

**Comment by POBrien333** [comment]
Re [Preprint]:
The conditional tests for article-journal and reports.
It then only prints [preprint] if the item does NOT have a volume and a page.

Item 23 and 35 are blog articles and should NOT be article-journals.
The others a normal papers from journals and as far as I see it does that correctly, print [Preprint] if if there is no volume and or page assigned, meaning it is in preprint.

**Comment by dhimmel** [comment]
> The others a normal papers from journals and as far as I see it does that correctly, print [Preprint] if if there is no volume and or page assigned, meaning it is in preprint.

Unfortunately the meaning of "preprint" differs from the obvious interpretation of an article prior to print publication. Instead in the life sciences, the term is [defined as such](https://asapbio.org/preprint-info/preprint-faq#qe-faq-637):

> A preprint is a complete scientific manuscript that is uploaded by the authors to a public server.  The preprint contains complete data and methodologies; it is often the same manuscript being submitted to a journal (see FAQ on submitting preprints).  After a brief quality-control inspection to ensure that the work is scientific in nature, the author’s manuscript is posted within a day or so on the Web without peer review and can be viewed without charge by anyone in the world.

The key distinctions is that preprints are posted at the author's discretion, independent of approval from peer review. They are usually hosted on preprint servers that are distinct from the journals, although some journals like _F1000 Research_ also make submitted articles available prior to peer review and acceptance and these could be called preprints (but this is a corner case).

The [PLOS guidelines](https://journals.plos.org/plosone/s/submission-guidelines) add `[Preprint]` to references under the category "Deposited articles (preprints, e-prints, or arXiv)`. 

> The conditional tests for article-journal and reports. It then only prints [preprint] if the item does NOT have a volume and a page.

I'd suggest never labeling an `article-journal` with `[Preprint]`. Labeling reports without a volume and page as a `[Preprint]` would probably be right more than not... although ultimately it's a tough workaround to CSL JSON's lack of an `article-preprint` type.

> Item 23 and 35 are blog articles and should NOT be article-journals.

Good catch. Will look into fixing my metadata.

**Comment by POBrien333** [comment]
I see. In that case that conditional doesn't make sense. I've removed it again.
I don't think there is any other way we could test for with CSL.

**Comment by adam3smith** [comment]
We have discussed using `article` for preprints and I'm still open for that, but it's obviously not in the specs. The alternative would be to just wait for CSL 1.1/1.2 and introduce a preprint item type.

**Comment by dhimmel** [comment]
I rebuilt the manuscript with the style from https://github.com/citation-style-language/styles/pull/4323/commits/dfe2507a7851304fc8d3c08e9a1824045a7d5f49: 
[manuscript-1.0.19-468ace4.pdf](https://github.com/citation-style-language/styles/files/3667997/manuscript-1.0.19-468ace4.pdf).

The PR looks good on my end! An improvement for sure. Thanks @POBrien333.

**Comment by adam3smith** [comment]
Thanks both!

**Comment by bwiernik** [comment]
@adam3smith From my perspective, the spec doesn’t really clearly define the meaning of any item type, so conventions about type usage are important to consider.

The current typical conventional for preprints is to use `article-journal` or `report`. I think we agree that doesn’t make much sense. `article` is essentially unused, and I agree with your earlier comments that it’s a good conceptual fit. In CSL 1.2/2, the name could potentially be changed to `preprint`, but it seems like a waste to not move toward a convention of using it for this purpose now. That’s the assumption being used with APA, and `article` isn’t otherwise being printed at all with this style.

**Comment by dhimmel** [comment]
> From my perspective, the spec doesn’t really clearly define the meaning of any item type, so conventions about type usage are important to consider.

Agreed although this should be fixed by updating the schema with definitions.

>  seems like a waste to not move toward a convention of using it for this purpose now.

I'm happy to use the `article` type for preprints in CSL JSON that I produce. However, users receive CSL JSON from many sources, and I don't think it's practical to expect all users of a given style will update CSL JSON they receive to use `article` for preprints. In other words, it's probably dangerous for a style to assume `article` means preprint.

**Pull request merged**
