### PR TITLE
Create departement-histoire-uqam-v12.csl

### PR DESCRIPTION
**Pull request by McKaulick**

### CODE REVIEW

**Comment by rmzelle** [comment]
Replaces #3194, #3200, #3201, and #3202. @McKaulick, per the [instructions](https://github.com/citation-style-language/styles/pull/3203#issuecomment-352632103) at the top of each pull request, you can update an existing pull request if there are changes that need to be made to it. Let's continue here with the style submission.

**Comment by rmzelle** [comment]
@McKaulick, is there an (online) description of this citation format that we can link to. We always try to include a documentation link in our styles. See https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link

Also, I assume you already made sure that your citation format is different from that of our general UQAM CSL style (https://www.zotero.org/styles?q=id%3Auniversite-du-quebec-a-montreal), which is documented at http://guides.bibliotheques.uqam.ca/themes/108-Zotero-a-l-uQAM-et-Carrefour-Zotero and http://www.guidemt.uqam.ca/citer/style-uqam ?

**Comment by McKaulick** [comment]
Hello @rmzelle, yes, there is now a link to the style guide. I added it to the file and commit the change. And yes, the style format is different than the general style at UQAM. Pointing to a different style guide. 

Please let me know if everything is good now.

Regards,

**Comment by rmzelle** [comment]
> Hello @rmzelle, yes, there is now a link to the style guide. I added it to the file and commit the change.

Is there an actual description online of what the citation format should look like? I didn't see anything like that at https://histoire.uqam.ca/style-zotero-departement/.

I also noticed you link to https://www.zotero.org/support/screencast_tutorials on your webpage, but the Zotero screencasts are very outdated (about 10 years old), so I would just link to https://www.zotero.org/support/ instead.

> Please let me know if everything is good now.

Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

I made a few changes to the style title and file name to be more in line with our styles.

**Comment by McKaulick** [comment]
Hello @rmzelle 

I changed the online description to a PDF guide from history department at UQAM that describe the citation and bibliographie format. 

Regarding changing the URL to https://www.zotero.org/support/, this will more than likely be done by the website's responsible after the Holidays. 

Lastly, I did based my style using this one https://www.zotero.org/styles/revue-dhistoire-moderne-et-contemporaine, but only for the basic structure. i.e. the XML declaration. The rest is original. 

Do I need really need to add the URL?

Let me know.

Thank you for your help and wishing you a happy holidays.

**Comment by rmzelle** [comment]
Thanks! I just merged the style.

> Do I need really need to add the URL?

No, not if you basically replaced the whole style.

**Pull request merged**
