### PR TITLE
Create revista-espanola-de-nutricion-humana-y-dietetica.csl

### PR DESCRIPTION
**Pull request by ebaladia**
Estilo Vancouver para la Revista Española de Nutrición Humana y Dietética / Vancouver style for the Spanish Journal of Human Nutrition and Dietetics

### CODE REVIEW

**Comment by adam3smith** [comment]
(documentation here: http://renhyd.org/index.php/renhyd/pages/view/norm#formatoyestilo )

**Comment by adam3smith** [comment]
Thanks! Which style did you base this on, i.e. which did you modify to create this one?

**Comment by ebaladia** [comment]
> Thanks! Which style did you base this on, i.e. which did you modify to create this one?
I don't remmember it. I searched by example, the system suggested the closest style, and then I edited it.

**Comment by ebaladia** [comment]
What's the next step?

**Comment by adam3smith** [comment]
Thanks!

**Comment by ebaladia** [comment]
> Thanks!

Thanks Sebastian (@adam3smith). Best wishes!

**Pull request merged**
