### PR TITLE
Create ecole-doctorale-de-sciences-po-note-french.csl

### PR DESCRIPTION
**Pull request by AnnaCouthuresIdrizi**

### CODE REVIEW

**Comment by AnnaCouthuresIdrizi** [comment]
Hello,
@adam3smith Please re-open this request, so i will put some corrections like you do in author-date style .
Thank you,
Anna

**Comment by adam3smith** [comment]
Sorry, had meant to open this earlier.

**Comment by AnnaCouthuresIdrizi** [comment]
Hello,
Please don't close this issue, i will review it on 19th August.
best regards,

*Anna Couthures-Idrizi*

bibliothécaire

Direction des Ressources et de l'Information Scientifique
27 rue Saint-Guillaume 75337 Paris cedex 07 France
T. +33 (0)1 45 49 50 43
anna.couthuresidrizi@sciencespo.fr
Libguide Humanités <http:///>
www.sciencespo.fr
[image: Twitter Sciences Po] <https://twitter.com/sciencespo>
<https://www.facebook.com/sciencespo>
<https://www.linkedin.com/edu/school?id=12454>
<https://www.linkedin.com/edu/school?id=12454>


Le jeu. 4 juil. 2019 à 19:31, stale[bot] <notifications@github.com> a
écrit :

**Comment by AnnaCouthuresIdrizi** [comment]
Dear all,
Did you have any idea when shall it be possible for you to review this
style in order to merged it ?
New students are coming and this would be now a great moment to promote
this style.
Thanks in advance for your comprehension.
Best regards,
Anna

*Anna Couthures-Idrizi*

bibliothécaire

Direction des Ressources et de l'Information Scientifique
27 rue Saint-Guillaume 75337 Paris cedex 07 France
T. +33 (0)1 45 49 50 43
anna.couthuresidrizi@sciencespo.fr
Libguide Humanités <http:///>
www.sciencespo.fr
[image: Twitter Sciences Po] <https://twitter.com/sciencespo>
<https://www.facebook.com/sciencespo>
<https://www.linkedin.com/edu/school?id=12454>
<https://www.linkedin.com/edu/school?id=12454>

**Comment by AnnaCouthuresIdrizi** [comment]
Hello,
Please merged this style to your official repository.
best regards,
Anna

**Pull request closed without merging**
