### PR TITLE
Create inventaire-general-author-date.csl

### PR DESCRIPTION
**Pull request by Emic37**

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks for describing these styles on your github. Could you say a bit more about who would be using these styles and for what?

**Comment by Emic37** [comment]
These styles are made priorily for researchers and documentalists of "service Patrimoine et Inventaire" of région Centre-Val de Loire (France). But they will be useful for all researchers of all heritage inventory services of country (1 per region). General inventory use bibliography norms derived from ISO-690 norms but with some modifications. 

So these style are adapted of uses of general inventory and will allow use of Zotero and ZoteroBib in services.

**Comment by Emic37** [comment]
@adam3smith Do you wish I add this on my github ?

**Comment by adam3smith** [comment]
I'm trying to ascertain whether this is a good fit for the repository. Here are our criteria:
https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles

To me, this sounds a bit like it's falling under the first category of style we do not accept (but I'm open to be convinced that I'm misunderstanding)

**Comment by Emic37** [comment]
Thanks for reply.

I understand your hesitation. I have been not clear.

The document joined in my GitHub is the style guide edited by the mission
of general heritage inventory of french culture ministry.

All inventory regional services are integrated to the regions and have to
apply directives edicted by the ministry.

Each regional inventory service have internal researcher agents and
external researcher partners or university partners.

In total, inventory services counts around 120 agents in France and much
more if counting the external partners and university partners.

So I developed these csl styles as researcher for the region Centre-Val de
Loire's inventory service. They are done primarily to facilitate the work
of the agents of the service and all of his partners but of course the
works of all others agents of all inventory regional services too. These
styles are made too for all researchers or academics partners who are
invested by regions of a culturel heritage inventory mission.

Share these styles between all agents and partners seems difficult,
especially because the general inventory is integrated into the regions.
So, for the organisation, the size, the function, the nature of the
institution, I think we are in the second accepted case.

I hope my explainations are more clear.
I named the styles because I don't want lose the provenance but maybe, it's
not a good idea. Should I rename style with more generic term?

**Comment by adam3smith** [comment]
OK, that makes sense then for us and yes, we'd absolutely want a general name that reflects this:

>  The document joined in my GitHub is the style guide edited by the mission of general heritage inventory of french culture ministry.

You can put the provenance info in the summary field if you wish. 

And just to confirm, all three styles are actually in use?

**Comment by Emic37** [comment]
Yes, I'll rename the styles. The prescriptions of ministry doesn't have any name, so I think the better way is using a title designating directly the general inventory of cultural heritage. It should be clearer and I'll use the summary field to precise the provenance of styles.

If you are agree with that, I'll correct styles in the coming days.

And in our service, 'spi note', 'spi full note' and 'spi full note with ibid' are used depending on the restitution support of our research. However, we never use the last author date style. I don't know if others researchers in the other services use it.

**Comment by adam3smith** [comment]
> The prescriptions of ministry doesn't have any name, so I think the better way is using a title designating directly the general inventory of cultural heritage.

Yes, that sounds good.

**Comment by Emic37** [comment]
So, I renamed all styles. It should be good now. Hope I didn't make any mistake.

**Comment by rmzelle** [comment]
@Emic37, sorry for the long wait. Two questions:

> And in our service, 'spi note', 'spi full note' and 'spi full note with ibid' are used depending on the restitution support of our research. However, we never use the last 'author date' style. I don't know if others researchers in the other services use it.

Does http://www2.culture.gouv.fr/culture/dp/inventaire/extranetIGPC/normes/constit_normesbiblio.pdf describe the 'author date' version? If it does, we'll take that version as well. Otherwise, we might want to start with just the 'note', 'full note' and 'full note with ibid' variants.

> General inventory use bibliography norms derived from ISO-690 norms but with some modifications.

Do you know if any non-ISO-690 derived styles are in use at General inventory? If you aren't aware of any, we can change the style title from "Inventaire général du patrimoine culturel — ISO-690" to just "Inventaire général du patrimoine culturel".

**Comment by Emic37** [comment]
@rmzelle no problem, thank for your reply. 

No, http://www2.culture.gouv.fr/culture/dp/inventaire/extranetIGPC/normes/constit_normesbiblio.pdf doesn't describe the 'author-date' version. This variant can be excluded. 

The styles of the "Inventaire général du patrimoine culturel" are only derived of ISO-690 norms, so I added this info in the title of styles to help some others people (external of general inventory like) who search a style based on ISO-690 norms but, if you think it's better to make title more simple, I w'll change title.

**Comment by rmzelle** [comment]
> No, http://www2.culture.gouv.fr/culture/dp/inventaire/extranetIGPC/normes/constit_normesbiblio.pdf doesn't describe the 'author-date' version. This variant can be excluded.

Okay, then I'll close this pull request. You can always reopen it in the future if you wish to add this variant at a later date. For now I've accepted the "note", "full-note", and "full-note-with-ibid" versions (#3696, #3698, and #3697).

> The styles of the "Inventaire général du patrimoine culturel" are only derived of ISO-690 norms, so I added this info in the title of styles to help some others people (external of general inventory like) who search a style based on ISO-690 norms but, if you think it's better to make title more simple, I w'll change title.

Let's leave it in, especially since we can't be sure every user knows to search for "Inventaire général du patrimoine culturel".

**Comment by rmzelle** [comment]
And thanks!

**Pull request closed without merging**
