### PR TITLE
Create PHBern IVP

### PR DESCRIPTION
**Pull request by arimnummocud**
PHBern IVP citation style

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

**Comment by arimnummocud** [comment]
Hello Rintze

Thank you for your message!
There is a style guide available, however, it is uploaded on an internal website : meinephbern.ch.
You’ll find the style guide in the annex. Would we have to upload the style guide on an accessable website in order for the style to be in the zotero repository ?

Best regards,
Mira

Von: Rintze M. Zelle [mailto:notifications@github.com]
Gesendet: Sonntag, 8. Dezember 2019 22:32
An: citation-style-language/styles
Cc: Ducommun, Mira; Author
Betreff: Re: [citation-style-language/styles] Create PHBern IVP (#4427)


Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

**Comment by rmzelle** [comment]
> There is a style guide available, however, it is uploaded on an internal website : meinephbern.ch. You’ll find the style guide in the annex. Would we have to upload the style guide on an accessable website in order for the style to be in the zotero repository ?

@arimnummocud, would it be possible to attach the style guide as an attachment to a GitHub comment here? Email attachments don't work on GitHub, you need to use the website.

**Comment by rmzelle** [comment]
I was also curious what "IVP" stands for.

**Comment by arimnummocud** [comment]
> > There is a style guide available, however, it is uploaded on an internal website : meinephbern.ch. You’ll find the style guide in the annex. Would we have to upload the style guide on an accessable website in order for the style to be in the zotero repository ?
> 
> @arimnummocud, would it be possible to attach the style guide as an attachment to a GitHub comment here? Email attachments don't work on GitHub, you need to use the website.

Sure. 
[180925_Formale_Richtlinien_IVP_vorHS18_def.pdf](https://github.com/citation-style-language/styles/files/4039298/180925_Formale_Richtlinien_IVP_vorHS18_def.pdf)

**Comment by arimnummocud** [comment]
> I was also curious what "IVP" stands for.

"IVP" is short for "Institut Vorschulstufe und Primarstufe" (engl.: Institute for Pre-Primary and Primary Education) based at the Bern University of Teacher Education in Bern, Switzerland.

**Comment by rmzelle** [comment]
@arimnummocud, one more question. Do you expect this style to only be used in German, or English as well?

**Comment by arimnummocud** [comment]
> @arimnummocud, one more question. Do you expect this style to only be used in German, or English as well?

The students as well as the staff of the institute will in the vast majority of cases use the style in German. I can't, however, rule out the possibility that it might be used in English in certain instances.

**Comment by rmzelle** [comment]
> The students as well as the staff of the institute will in the vast majority of cases use the style in German. I can't, however, rule out the possibility that it might be used in English in certain instances.

Okay, we'll leave the style without a fixed locale, then.

And it looks like you based this style on apa.csl. Can you confirm whether that's the case?

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
