### PR TITLE
Create hakwolfsberg.csl

### PR DESCRIPTION
**Pull request by martinhak**
Changes:
- Citate Websites only with "URL: " and not with "Online verfügbar unter: URL: ")

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks! We try to include a "documentation" link in every style (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link). Does HAK Wolfsberg have a webpage that describes your style format?

And did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by martinhak** [comment]
Hi! There is no actual documentation from our institution but there is one that we base it on. Can be found here: http://www.diplomarbeiten-bbs.at/sites/default/files/DA-Handreichung_14.4.2016.pdf  ( (page 26)
Our style is based on another one, I already added this to the code. Line shoud be:     <link href="http://www.zotero.org/styles/die-bachelorarbeit-samac-et-al-note" rel="template"/>

Nice regards!

**Comment by rmzelle** [comment]
Ah, sorry, I missed the "template" link.

**Comment by adam3smith** [comment]
Hmm - so this style seems quite different from the BBS style you link to (and the BBS style is quite thinly documented itself). So e.g. you use small caps/Kapitälchen, BBS doesn't. This style has quite specific et al settings, modelled after APA, BBS doesn't mention that. BBS also appears to use ebd. this style doesn't. 
Those sorts of things are the reasons we really want the actual document for the style. It's impossible for me to tell which of these things are done on purpose and which are just left from the Samac style.

**Comment by martinhak** [comment]
We base our style on "Die Bachelorarbeit". There are no differences except citing a website ("Die Bachelorarbeit" says "Online Verfügbar unter: URL", in our style we only use "URL:"). The style "Die Bachelorarbeit" is documented within this book: https://www.amazon.de/Bachelorarbeit-P%C3%A4dagogischen-Hochschule-wissenschaftlicher-Lehrerbildung/dp/3708901886 . As already said there is no real documentation from our institution.

**Comment by adam3smith** [comment]
OK, I guess we can do this, but it seems a bit odd to have a separate style just because of three words before the URL. Is that really needed? Couldn't we just create your style as a [dependent](http://docs.citationstyles.org/en/stable/specification.html#dependent-styles) to the Samac one, which would facilitate maintenance?

**Comment by adam3smith** [comment]
@martinhak just wondering if you saw my question above. More different styles create more work in maintenance, so if possible I'd like to avoid that, but if this distinction is crucial for you style, we'd probably take it.

**Pull request closed without merging**
