### PR TITLE
Create harvard-fh-salzburg.csl

### PR DESCRIPTION
**Pull request by mmackh**
Citation for Fachhochschule Salzburg

### CODE REVIEW

**Comment by rmzelle** [comment]
Is this style specific to Informationstechnik und Systemmanagement?

If so, in general, we would use "Harvard - Fachhochschule Salzburg - Informationstechnik und Systemmanagement" for the style title and "harvard-fachhochschule-salzburg-informationstechnik-und-systemmanagement.csl" for the file name (no abbreviations). If your university uses multiple style formats (e.g. both an author-date and a numeric style), we might want to use "Fachhochschule Salzburg - Informationstechnik und Systemmanagement (Harvard)" instead (and something similar for the file name), but that might not be the case here.

Which CSL did you base this on? Can you add a "template" link? (see point 8 at https://github.com/citation-style-language/styles/wiki/Style-Requirements )

The `<category field="medicine"/>` also needs to be updated. For a "Informationstechnik und Systemmanagement"-specific style, "communications" and "engineering" are probably reasonable choices (see http://docs.citationstyles.org/en/stable/specification.html#appendix-i-categories).

**Comment by mmackh** [comment]
Hi, thank you for writing back so quickly - sorry it took a little time - exam season. FH Salzburg does not have any departments, so the style applies universally to every assignment, even from different subjects.

**Comment by rmzelle** [comment]
Can you rename the style to ""Harvard - Fachhochschule Salzburg", then? Please use "harvard-fachhochschule-salzburg.csl" as the style file name, and update the style ID and "self" link accordingly.

"tourism" is not a valid CSL category, but maybe "science" works.

**Comment by mmackh** [comment]
Ok, I've made the changes accordingly - please let me know if anything else needs to be changed?

**Comment by rmzelle** [comment]
Looks good, thanks!

**Pull request merged**
