### PR TITLE
Update harvard-university-of-technology-sydney.csl

### PR DESCRIPTION
**Pull request by MeijunHuang**

### CODE REVIEW

**Comment by MeijunHuang** [comment]
Thanks

The style I proposed only has single quotation marks. Could you help check about this?

Cheers
Meijun

**Comment by rmzelle** [comment]
> The style I proposed only has single quotation marks. Could you help check about this?

In Zotero I get the following output with single quotes:

> Abbott, D.A., van den Brink, J., Minneboo, I.M.K., Pronk, J.T. & van Maris, A.J.A. 2009, ‘Anaerobic homolactate fermentation with Saccharomyces cerevisiae results in depletion of ATP and impaired metabolic activity!.’, FEMS Yeast Research, vol. 9, no. 3, pp. 349–57.

@adam3smith, it looks like the csl-bot examples don't localize. See e.g. https://github.com/citation-style-language/styles/pull/4221#issuecomment-514891409 (which is a Canadian French style), and the style in this PR.

(see also https://github.com/citation-style-language/styles/pull/4222/commits/7a6ab8de3a6da83bd1f51cd22f1f099d139dc645#issuecomment-514900188)

**Comment by rmzelle** [comment]
@MeijunHuang, after your report, we discovered that the sample references in the GitHub comments here ("Below are some sample citations generated based on your proposed changes:") didn't follow the style locale. This has been fixed now for all future pull requests. Thanks for alerting us of the problem.

**Comment by MeijunHuang** [comment]
Thanks for your help.

Meijun

**Pull request merged**
