### PR TITLE
Create international-biodeterioration-and-biodegradation.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/73104/question-about-style-international-biodeterioration-biodegradation

Made independent style with sorting adapted as per guidelines (via editors).

Added dependent style to skip list: https://github.com/citation-style-language/journals/pull/70

### CODE REVIEW

**Comment by adam3smith** [comment]
(you still need to delete the dependent style)

**Comment by POBrien333** [comment]
Is that not deleted automatically when the PR for addition to the skip list get's signed off?

**Comment by adam3smith** [comment]
thanks!

**Comment by POBrien333** [comment]
ah ok. Understood. Thank you :)

**Pull request merged**
