### PR TITLE
Some new updates

### PR DESCRIPTION
**Pull request by amendesd**
"yearpage" macro and "et-al" are no longer used and have been removed. Other minor changes have been made. Thanks

### CODE REVIEW

**Comment by rmzelle** [comment]
Hi. I looks like we're currently rather picky about the "license" URL. Could you change "https://creativecommons.org/licenses/by-sa/3.0/" to "http://creativecommons.org/licenses/by-sa/3.0/"? ("https" to "http")

**Comment by rmzelle** [comment]
Sorry, we need the exact `<rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>`

**Comment by rmzelle** [comment]
@amendesd, can you fix this?

**Comment by amendesd** [comment]
I'm not comfortable with the use of Github. I apologizes. I thought I had made the requested corrections. Perhaps this is not the right way, but here is the link I generated with a patch-5: https://github.com/amendesd/styles/commit/842273126779ac322271b6106971a99d5bb27084

**Comment by rmzelle** [comment]
It's easiest for us if you update the current pull request, which you can do by clicking the pencil/edit icon at https://github.com/amendesd/styles/blob/patch-4/invisu.csl.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
