### PR TITLE
Create the-journal-of-pure-and-applied-chemistry-research.csl

### PR DESCRIPTION
**Pull request by Firda09**

### CODE REVIEW

**Comment by rmzelle** [comment]
@Firda09, the documentation link needs to be updated to http://jpacr.ub.ac.id/index.php/jpacr/about/submissions#authorGuidelines. And do you remember which CSL style you started from? We'd like to have a "template" link to that style (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

**Comment by Firda09** [comment]
Please tell me, which documentation link need to be updated to  http://jpacr.ub.ac.id/index.php/jpacr/about/submissions#authorGuidelines. and how to do? 
and where can I find the repository of this CSL? has it already can be used or not?
thank you

**Comment by rmzelle** [comment]
> Please tell me, which documentation link need to be updated to http://jpacr.ub.ac.id/index.php/jpacr/about/submissions#authorGuidelines. and how to do?

`<link href="http://pubs.acs.org/doi/pdf/10.1021/bk-2006-STYG.ch014" rel="documentation"/>` needs to be changed to `<link href="http://jpacr.ub.ac.id/index.php/jpacr/about/submissions#authorGuidelines" rel="documentation"/>`. The [post above](https://github.com/citation-style-language/styles/pull/2367#issuecomment-267868411) has instructions on how to update your existing pull request.

> where can I find the repository of this CSL? has it already can be used or not?

We haven't accepted this style into the repository yet.

I was also curious whether you remember which CSL style you used to create this one. It looks like it was one of the ACS styles: https://www.zotero.org/styles?q=american%20chemical%20society. Do you recall which one you used?

**Comment by Firda09** [comment]
I have already commit change the CSL. is it already received or not?
Actually this CSL style adapted from ACS style with a little bit improvisation. can it be accepted?
thank you.

**Comment by rmzelle** [comment]
I'll accept the style now. Thanks for contributing!

(it looks like you started from http://www.zotero.org/styles/american-chemical-society, so I added a "template" link to that style)

**Comment by Firda09** [comment]
Thank you for your valuable assistance,
after that, what should I do?
Thank you.

**Comment by rmzelle** [comment]
> after that, what should I do?

That depends on what software you're using. Mendeley and Zotero both update their styles within 24 hours.

**Pull request merged**
