### PR TITLE
DEA Style

### PR DESCRIPTION
**Pull request by ankeqiang**
This is a style patterned after the Revue d'Histoire Moderne et Contemporaine (France) that we modified to produce a style that meets the requirements of the Department of Asian Studies at Aix Marseille University.

We have modified the style at the following level:
- Format of doctoral dissertation

We plan to modify it further to handle references in Asian languages. This style is to be used for all academic works (Ph. D. dissertations, M.A. thesis, etc.) produced by the faculty and students of the Department of Asian Studies.

### CODE REVIEW

**Comment by ankeqiang** [comment]
Hi,

Sorry. I can't see anything on the test report.

Christian

**Comment by adam3smith** [comment]
Start here: https://github.com/citation-style-language/styles/wiki/Style-Requirements
and take a close look at the file naming (and id/link) conventions. 
To start with, your file needs to have a .csl extension for the tests to even run on it (beyond throwing an error).

**Comment by ankeqiang** [comment]
I made corrections both for file naming and in the style itself.
CSL extension: I have a file with CSL extension (DEA_Style.csl). Did I miss a step (upload)? I upload the .txt version of my CSL file.
[DEA_Style.txt](https://github.com/citation-style-language/styles/files/531823/DEA_Style.txt)

**Comment by rmzelle** [comment]
@ankeqiang, I made some changes. Is the new name okay? See https://github.com/citation-style-language/styles/pull/2272/commits/d30156edd6c330ac08bdf8e6e1829780516b2bcb

**Comment by ankeqiang** [comment]
Many thanks. I did not have time to go back to the cal issue yesterday. I got it now. And thanks for the change of name. It makes things more explicit indeed. Have a good day.

**Comment by rmzelle** [comment]
@ankeqiang, I added the style to the repository, thanks!

**Pull request merged**
