### PR TITLE
Create ilahiyat-studies.csl

### PR DESCRIPTION
**Pull request by mtarakci**
A fullnote style for Ilahiyat Studies. 
Web page of the journal: http://ilahiyatstudies.org/index.php/journal/index
Link for style sheet: https://drive.google.com/file/d/1qNUR5UZ3QDJkxhJv0-gE39HA5-2I2n4E/view

### CODE REVIEW

**Comment by adam3smith** [comment]
(Helpful to say what you actually change if you submit a style that's 95% identical to Chicago Manual or another complex style). 

The changes to volume make sense to me, but I don't see why you're removing title case. The journal's style guide clearly applies title casing as in "History of Islamic Philosophy" etc.

**Comment by adam3smith** [comment]
right, but as we discuss in this thread and as per https://www.zotero.org/support/kb/preventing_title_casing_for_non-english_titles there's a solution for Arabic (and if need be mixed) titles that doesn't require users to incorrectly enter data in title case (incorrectly because it will format incorrectly in styles requiring sentence case). Please revert that change.

**Comment by mtarakci** [comment]
I changed titles to Title Case.

**Comment by adam3smith** [comment]
Thanks!

**Comment by mtarakci** [comment]
It's not used anymore. It would be better to delete it to avoid confusion.
See
https://www.ilahiyatstudies.org/journal/announcement/view/64)

**Pull request merged**
