### PR TITLE
Create artificial-organs.csl

### PR DESCRIPTION
**Pull request by pyrusx**
Added citation style of Artificial Organs: https://onlinelibrary.wiley.com/journal/15251594

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, @adam3smith, do you have any thoughts if we have a better independent parent than elsevier-vancouver.csl for this journal, seeing that it's published by Wiley?

Per https://onlinelibrary.wiley.com/page/journal/15251594/homepage/forauthors.html and https://onlinelibrary.wiley.com/doi/epdf/10.1111/aor.13773, it looks to be vanilla Vancouver, but vancouver-superscript-only-year.csl is too verbose.

**Comment by adam3smith** [comment]
Too verbose in anything other than the treatment of online sources?

**Comment by rmzelle** [comment]
> Too verbose in anything other than the treatment of online sources?

I was looking at the Zotero Style Repository preview, which I assume is a regular journal article:

> Hisakata R, Nishida S, Johnston A. An adaptable metric shapes perceptual space. Curr Biol [Internet]. 2016 [cited 2016 Oct 3];26:1911–5. Available from: http://www.cell.com/current-biology/abstract/S0960-9822(16)30544-9

**Comment by adam3smith** [comment]
But that's just because Zotero generates the styles with the URL flag checked. Otherwise the internet/cited/URL wouldn't show up.

**Comment by pyrusx** [comment]
Hello,

I just wanted to touch base on what the status of this request is, and if I could do anything to help. Thanks!

**Comment by pyrusx** [comment]
@rmzelle @adam3smith Sorry to tag you, but just wanted to get an update!

**Comment by pyrusx** [comment]
Hi, just wanted to touch base again. @rmzelle @adam3smith @POBrien333

**Comment by adam3smith** [comment]
Sorry for the long delay!

**Comment by pyrusx** [comment]
Thank you so much!

**Pull request merged**
