### PR TITLE
Update style for université de Lausanne - Section d'Archéologie et Science de l'antiquité

### PR DESCRIPTION
**Pull request by leonienussbaum**

### CODE REVIEW

**Comment by leonienussbaum** [comment]
Hello! I really don't understand what's wrong with my locale tag.. It didn't change at all since 5 month ago and i did not raise any issues back then... Could you please take a look at what failed here ?

**Comment by POBrien333** [comment]
So, the warning actually told you to utilise the CSL validator. If you do so you get more information on WHY there is an error.
https://validator.citationstyles.org/?url=https%3A%2F%2Fgithub.com%2Fcitation-style-language%2Fstyles%2Fraw%2F906ae102d1a0e4feb90b3a9bfd2a56534ef9d321%2Funiversite-de-lausanne-institut-d-archeologie-et-des-sciences-de-l-antiquite.csl&version=1.0.2

The error is because you have added a conditional inside the bibliography's sort section which is not allowed. You'd need to modify that.

Also, please don't open issues for an already made PR just to get our attention. You can just tag us inside the PR (if it's reasonable).

**Comment by leonienussbaum** [comment]
Thank you for your answer, i was looking at the wrong tag and got mistaken. It should pass all the tests now.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
