### PR TITLE
Update applied-spectroscopy-reviews.csl

### PR DESCRIPTION
**Pull request by gul916**
enhance report and proceeding parts, based on damnation333 file

### CODE REVIEW

**Comment by damnation333** [comment]
Continuation of https://github.com/citation-style-language/styles/pull/2649#issuecomment-297412943

**Comment by adam3smith** [comment]
@gul916 @damnation333 made some tweaks for robustness & elegance. If either of you could take this for a spin before I merge?

**Comment by gul916** [comment]
Hi @adam3smith ,
It seems fine for article, book, book chapter, proceeding, presentation, thesis, web, blog, forum, and report.

Minor corrections:
For manuscript, there are two spaces before "Available at".
For all accessed dates, is there a way to have only month and year without the day ?

**Comment by adam3smith** [comment]
OK, the two spaces are fixed. Are you sure about omitting the day? It's such an odd requirement if you're going to include access dates and I wouldn't take specifics in the often hastily written instructions for authors too literally.

**Comment by gul916** [comment]
@adam3smith 
Ok, all is fine.
If it's an odd requirement, I will follow your advice and ignore it. Let's wait what the editor will say when I will submit my article.
Many thanks for your work.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
