### PR TITLE
Create petit-chicago.csl

### PR DESCRIPTION
**Pull request by f-mb**
CSL adaptation of "Petit Chicago" (http://guides.bib.umontreal.ca/uploads/uploads/original/Petit_Chicago_Plus_Cycles_Sup_.pdf)

### CODE REVIEW

**Comment by rmzelle** [comment]
> `default-locale="fr"`

Could you set this style to either "fr-FR" or "fr-CA"? (if the latter, the title should change to "Petit Chicago (author-date, French - Canada)")

**Comment by adam3smith** [comment]
@rmzelle  -- how do you feel about the filename/id? I was thinking maybe add author-date, since there is a note version described in the guide, too, and someone might want to add it at a later point.

**Comment by rmzelle** [comment]
Oh, yeah, petit-chicago-author-date.csl would probably be better, then.

**Comment by rmzelle** [comment]
Thanks!

**Comment by f-mb** [comment]
Done.

**Comment by f-mb** [comment]
Thanks!

**Pull request merged**
