### PR TITLE
Adds APA where the citation authors are separated by 'and' instead of…

### PR DESCRIPTION
**Pull request by cpina**
… '&'.

Some places like in Spain or France use this (localized in their
languages)

### CODE REVIEW

**Comment by rmzelle** [comment]
Oh, wait, did we decide to add this to the repo anyway?

**Comment by cpina** [comment]
Oops, I understood that the style could be added to the repo after I mentioned in the email thread that there are 8 variants of apa such as apa-tr.csl or two apa-fr* and we discussed a correct name (I thought that the name proposals was for the repo, not for internal usage).

If can't be added using any name I'll give instructions to the affected users about how to use it without being in the repository; and apologies for getting over-excited creating it...

**Comment by rmzelle** [comment]
I'll let Sebastian decide, since he does most of the maintenance on the APA styles. I don't think the title/ID is very clear, though. "and-as-text" probably only makes sense to people who know CSL. How about "American Psychological Association 6th edition (no ampersand)" and "apa-no-ampersand.csl"?

**Comment by cpina** [comment]
Ok, I'll wait for @adam3smith 's input. I'm happy with either name. Thanks!

**Comment by adam3smith** [comment]
I like no ampersand -- was still kind of sleepy when I suggested the
"text".
I'm Ok with adding this, since I always feel we're underserving the
non-English populations, though with the understanding that we'll remove it
once we can deal with it in locales as we should.

On Thu, May 14, 2015 at 5:06 PM, Carles Pina Estany <
notifications@github.com> wrote:

> Ok, I'll wait for @adam3smith <https://github.com/adam3smith> 's input.
> I'm happy with either name. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1552#issuecomment-102182798>
> .
>



-- 
Sebastian Karcher, PhD
Department of Political Science
Northwestern University

**Comment by cpina** [comment]
I've renamed it.

**Comment by rmzelle** [comment]
Okay, thanks!

**Pull request merged**
