### PR TITLE
Create wirtschaftsuniversitat-wien-abteilung-fur-unternehmensrechnung…

### PR DESCRIPTION
**Pull request by georgd**
…-und-controlling.csl

### CODE REVIEW

**Comment by rmzelle** [comment]
@georgd, can you confirm that this style shouldn't be fixed to German?

I also deleted the "Abteilung für " from the title since https://www.wu.ac.at/uco/ just uses "Unternehmensrechnung und Controlling". Hope that's okay.

**Comment by adam3smith** [comment]
@georgd did you see Rintze's question above? Otherwise this should be good to go.

**Comment by georgd** [comment]
We contacted the institute and are still waiting for an answer. I'll ping
them again.

Am Mo., 10. Dez. 2018, 14:17 hat Sebastian Karcher <notifications@github.com>
geschrieben:

**Comment by rmzelle** [comment]
I just went ahead and accepted this. Please let us know here if you hear back and the style needs to be changed (or feel free to file another pull request to make the change yourself).

**Pull request merged**
