### PR TITLE
Create universitat-bremen-frankoromanistik-literaturwissenschaft.csl

### PR DESCRIPTION
**Pull request by POBrien333**
Via private client. The style has been thoroughly tested and reviewed. The person who commissioned the style asked to be listed as the author of the style so requests go to her if need be. I'm fine with that. @adam3smith I'd be grateful if you could review and merge this style when you are able to. Thanks a lot!

### CODE REVIEW

**Comment by adam3smith** [comment]
(please ping me again once you've fixed the redundant macros; I'll merge quickly as requested)

**Comment by bwiernik** [comment]
I can check again tomorrow too and merge if ready

**Comment by POBrien333** [comment]
Ah, should've checked back last night! Was literally the last thing I did.
Macros removed now. Thank you :)

**Comment by adam3smith** [comment]
Great, thanks!

**Pull request merged**
