### PR TITLE
Update gallia-prehistoire.csl

### PR DESCRIPTION
**Pull request by DMathelier**
Update of the journal's norms and standards.
Daphné Mathelier (editor of _Gallia Préhistoire_)

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- I tried to look at the new guidelines, but this: http://www.mae.parisnanterre.fr/wp-content/uploads/2015/06/GP_recommandations_auteurs-2016.pdf looks different from what you changed the style to (and' it's 4 years old). Is the new/current guide for authors online?

(Feel free to reply in French if that's easier for you).

**Comment by DMathelier** [comment]
Dear Sebastian,

Thank you for your message and for your care. Indeed, the standards on our
institution's website are not yet up to date (but the modification has been
requested).
The right standards are on the OpenEdition Journals website where the
digital editions of our journal are published.

https://journals.openedition.org/galliap/430

I am attaching the new standards as attachments to this email.

I am at your disposal for any further information,

Best regards,


*Daphné Mathelier*
Revue *Gallia Préhistoire*

MSH – 21 allée de l’Université
92 023 Nanterre cedex
01 46 69 24 34
www.mae.parisnanterre.fr
twitter.com/MAENanterre

**Comment by DMathelier** [comment]
The journal's guidelines are now updated on all platforms:
 http://www.mae.parisnanterre.fr/wp-content/uploads/2019/07/GP_Normes_2019.pdf
https://journals.openedition.org/galliap/430

**Comment by rmzelle** [comment]
@DMathelier, thanks!

**Pull request merged**
