### PR TITLE
Create apa-7-french-adaptation-uco.csl

### PR DESCRIPTION
**Pull request by Kalunna**
Hello,
Here is a French adaptation of the APA version of the year 2010, for the Catholic University of the West.
Thanks

### CODE REVIEW

**Comment by bwiernik** [comment]
A few questions to start:

1. You say that this is based on APA 6, but you used APA 6 as a template. Why is that?
2. How do the university requirements differ from standard APA 7 style?

**Comment by Kalunna** [comment]
Hello Bwiernik,
1-It's a mistake, I must delete the line N°8 (reference about the 6eme ed template)
2- It's minor requirement like but it's important for our students. 
For exemple, 
<term name="in"> must be « dans »,
for container-periodical) if no volume, the issue must be in brackets

**Comment by bwiernik** [comment]
Translation of terms is done with the standard APA style by setting the language of the document to French. If things like using "dans" instead of "in" is all that  needs to be adjusted, the standard APA style already does that

**Comment by Kalunna** [comment]
OK, I try this. Thanks you for your comments

**Comment by adam3smith** [comment]
@Kalunna  did you get a chance to check? Is this still needed?

**Comment by Kalunna** [comment]
I am completely resuming my work, I am going to delete my file and resubmit a new one. thank you for your remarks

**Comment by bwiernik** [comment]
Thanks for the update.

Based on the documentation you linked to, the documentation is just describing the standard APA style with French terms. This can be accomplished by using the regular APA CSL style and setting the language/locale to French.

**Comment by adam3smith** [comment]
Closing based on bwiernik's feedback

**Pull request closed without merging**
