### PR TITLE
[WIP] Create incontext-studies-in-translation-and-interculturalism.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/94075/request-for-new-style-incontext-studies-in-translation-and-interculturalism#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
(there are additional improvements requested on the forums, waiting until POBrien333 has those implemented)

**Comment by adam3smith** [comment]
@POBrien333 is this reasonably ready to merge now? We can always fix later

**Comment by POBrien333** [comment]
Yeah, maybe we also get more requests for fixes from other users then. Thanks :)

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
