### PR TITLE
Create zilsel.csl

### PR DESCRIPTION
**Pull request by sebastien-plutniak**
Creation of a style for the Zilsel journal.

### CODE REVIEW

**Comment by sebastien-plutniak** [comment]
I'm sorry but I don't understand why the checks failed =/ 
Someone might help?

**Comment by rmzelle** [comment]
> I'm sorry but I don't understand why the checks failed =/
> Someone might help?

@sebastien-plutniak, there was an issue on our side that caused all tests to fail. Should be fixed now.

I assume this should be a "note" type citation style, with footnotes on each page? And is this CSL style for both French and English, or just French? We're also curious if you based this on an existing CSL style, in which case we'd like to include a "template" link (see also https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

**Comment by rmzelle** [comment]
I was also wondering if the journal has an online description of the citation format (e.g. in a style guide).

**Comment by sebastien-plutniak** [comment]
Thank you, I confirm that this is a “note” type citation style. I added a template reference to the style I used as a model. Unfortunately, the journal does not have yet an online description of the style.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
