### PR TITLE
Create cell-reports-medicine.csl

### PR DESCRIPTION
**Pull request by TKPath**
A CSL for Cell Reports Medicine based on cell-numeric-superscript

### CODE REVIEW

**Comment by bwiernik** [comment]
Hi thanks! Styles for this publisher are generated automatically from https://github.com/citation-style-language/journals 

Can you instead add this journal's information to the "cell-press-research" section there?

**Comment by bwiernik** [comment]
@POBrien333 Could you add this to journals ?

**Comment by POBrien333** [comment]
That's done: https://github.com/citation-style-language/journals/pull/130

**Comment by bwiernik** [comment]
Thanks!

**Comment by TKPath** [comment]
Thanks both! I'm on leave this week but was going to try to do it myself
when back (Git, push, pull etc. is all new to me). I'll do it next time!

Cheers,

Tim

**Pull request closed without merging**
