### PR TITLE
Create harlaxton-medieval-studies.csl

### PR DESCRIPTION
**Pull request by justincolson**
Style for Harlaxton Medieval Studies edited volume series. Based on Chicago Full Note as template. http://harlaxton.org.uk/publications/

### CODE REVIEW

**Comment by rmzelle** [comment]
@justincolson, thanks! So this style format differs from regular Chicago Full Note? Do you know where the Harlaxton Medieval Studies format is described? Is there a webpage we can point to?

**Comment by justincolson** [comment]
Hi @rmzelle ! The main difference is the initialisation of names in all cases, as well as the exclusion of the names of publishers (only places). The stylesheet for the series is only circulated to invited authors as a .doc file, rather than posted online. I could supply a copy but I don't have control of their website so can't get it posted there. The link supplied before describes the conference and links to existing publications.

**Comment by adam3smith** [comment]
If you don't mind attaching the file here (simply by drag&drop to the comment window) that'd be helpful.
How many invited authors are we talking about approximately?

**Comment by adam3smith** [comment]
@justincolson just a gentle reminder that we're waiting on your input here still. Thanks!

**Comment by rmzelle** [comment]
@justincolson, we closed this pull request due to inactivity. If you can add the stylesheet here as an attachment to a GitHub comment, we'd be happy to reopen the pull request.

**Pull request closed without merging**
