### PR TITLE
Create informationspraxis.csl

### PR DESCRIPTION
**Pull request by zuphilip**
This new Open Access journal from library, archive and information community chooses an already existing citation style. They will apply for an ISSN and when this happened, the information can be added here. Any other suggestion for the category?

### CODE REVIEW

**Comment by rmzelle** [comment]
No, looks good!

**Comment by rmzelle** [comment]
I assume you'll update the "documentation" link as well once the journal has a website?

**Comment by zuphilip** [comment]
The first documentation link is fine: https://journals.ub.uni-heidelberg.de/index.php/ip/about/submissions#authorGuidelines and there the pdf from the second link is explicitely mentioned. Do you prefer any change?

There is the blog (with the open review): http://informationspraxis.de/ and there is the journal homepage https://journals.ub.uni-heidelberg.de/index.php/ip/index which collect the articles in issues etc. I see that the ISSN seems to be ready, I will update that later.

**Comment by rmzelle** [comment]
Oh, never mind, then. I missed the first link.

**Pull request merged**
