### PR TITLE
Södertörns högskola update

### PR DESCRIPTION
**Pull request by Ca7w3as3l**
updated Södertörns CSL files

### CODE REVIEW

**Comment by Ca7w3as3l** [comment]
I must not know what I am doing. I am trying to update the two CSL files in the repository with ones I have edited and uploaded to my ca7w3as3l account. Get this conflicting error.

**Comment by Ca7w3as3l** [comment]
I am trying to update the repository. I have these conflicts that I do not know what to do with.

**Comment by adam3smith** [comment]
You're trying to update from an older branch of your repository. 
Go to the most recent version of the style at https://github.com/citation-style-language/styles/blob/master/sodertorns-hogskola-harvard-ibid.csl and click the pencil icon at the top right. That will create a new branch in your fork that is up to date.

**Comment by rmzelle** [comment]
(replaced by #3032 and #3033)

**Pull request closed without merging**
