### PR TITLE
create mcgill9-en.csl, Canadian McGill legal style

### PR DESCRIPTION
**Pull request by gspanglett**
Canadian Guide to Uniform Legal Citation 9th edition (McGill Guide)

### CODE REVIEW

**Comment by rmzelle** [comment]
@gspanglett, thanks! Somebody else also recently submitted a 9th edition style (see https://github.com/citation-style-language/styles/pull/4509 and https://twitter.com/andrew_leach/status/1217321423313625088).

Do you think it's worth keeping around the 7th edition style, or are the changes minor enough that we can just replace the existing style with the 9th edition format?

**Comment by gspanglett** [comment]
Hi Rintze, and thanks for the update.

The 7th edition style is considerably out-of-date and should probably be 
removed - it is not usable by Canadian legal writers and was very basic.

And thank you for mentioning Andrew Leach's submission.  Funny enough - 
I noticed it in the open pull requests when I was putting in my own.

I was going to reach out to see if we can combine efforts or build a 
small support community.  I am also in contact with a group of students 
in Montreal who were also looking at working with Zotero.

Warmest regards,

Gareth.

ps - I can also be reached at my Ottawa U. email account: 
gspan042@uottawa.ca

**Comment by gspanglett** [comment]
Hi again Rintze,

One other thing - to answer your question:  there are quite a lot of 
changes, as I've added a lot of specific formatting for various item 
types.  So, it is quite different from both the 7th edition, and Andrew 
Leach's recent submission as well.

Thanks again,

Gareth.

ps - I have a spreadsheet that maps McGill fields to both Zotero and CSL 
fields and item types; if you need it, just let me know and I will send 
it.  I also have examples taken from the printed McGill Guide: 
https://www.zotero.org/groups/2427436/mcgill_style_guide_examples

**Comment by rmzelle** [comment]
@gspanglett, thanks! Let's just update the existing style with your version, then.

(I also noticed we have a French version of the 7th edition: https://www.zotero.org/styles?q=mcgill)

**Pull request merged**
