### PR TITLE
Create dependent style comparative oriental manuscript studies bulletin

### PR DESCRIPTION
**Pull request by eu-genia**
a dependent style to hiob ludolf centre for manuscript studies style
journal Comparative Oriental Manuscript Studies Bulletin

### CODE REVIEW

**Comment by eu-genia** [comment]
I think I need help with this style. Don't get where the error is. Thanks!

**Comment by rmzelle** [comment]
For one, the file name is incorrect. Instead of "dependent/comparative oriental manuscript studies bulletin", it should be "dependent/comparative-oriental-manuscript-studies-bulletin.csl" (see https://help.github.com/articles/renaming-a-file/ for instructions on how to rename the file)

**Comment by eu-genia** [comment]
oops thanks


Quoting "Rintze M. Zelle" <notifications@github.com>:

> For one, the file name is incorrect. Instead of  
> "dependent/comparative oriental manuscript studies bulletin", it  
> should be  
> "dependent/comparative-oriental-manuscript-studies-bulletin.csl"  
> (see https://help.github.com/articles/renaming-a-file/ for  
> instructions on how to rename the file)
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/1979#issuecomment-201365884



-- 
Eugenia Sokolinski
Project Coordinator
Hiob Ludolf Centre for Ethiopian Studies
Asien Afrika Institut
Universit�t Hamburg
Alsterterrasse 1
20354 Hamburg

eugenia.sokolinski@uni-hamburg.de

http://www1.uni-hamburg.de/ethiostudies
http://www.traces.uni-hamburg.de

**Comment by adam3smith** [comment]
don't merge please

**Comment by rmzelle** [comment]
> don't merge please

Because of all the commits?

**Comment by adam3smith** [comment]
could we actually make this and the parent style en-GB as default locale, because it clearly is (commas are always inside quotation marks in US English and single quotes are only used inside double quotes). Also, the usage of plural abbreviations without period, very much British.
I'd then also ask that the hardcoded commas in the parent style be replaced with `quotes="true"`, i.e. in https://github.com/citation-style-language/styles/blob/master/hiob-ludolf-centre-for-ethiopian-studies.csl#L139 and https://github.com/citation-style-language/styles/blob/master/hiob-ludolf-centre-for-ethiopian-studies.csl#L139 and https://github.com/citation-style-language/styles/blob/master/hiob-ludolf-centre-for-ethiopian-studies.csl#L129

**Comment by adam3smith** [comment]
no, mainly because of the request above, though yes, this is probably a bit much history for a single dependent style.

**Comment by eu-genia** [comment]
where can i define that we need single quotes?

ok for en-GB

Quoting Sebastian Karcher <notifications@github.com>:

> could we actually make this and the parent style en-GB as default  
> locale, because it clearly is (commas are always inside quotation  
> marks in US English and single quotes are only used inside double  
> quotes). Also, the usage of plural abbreviations without period,  
> very much British.
> I'd then also ask that the hardcoded commas in the parent style be  
> replaced with `quotes="true"`, i.e. in  
> https://github.com/citation-style-language/styles/blob/master/hiob-ludolf-centre-for-ethiopian-studies.csl#L139 and https://github.com/citation-style-language/styles/blob/master/hiob-ludolf-centre-for-ethiopian-studies.csl#L139 and  
> https://github.com/citation-style-language/styles/blob/master/hiob-ludolf-centre-for-ethiopian-studies.csl#L129
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/1979#issuecomment-201383674



-- 
Eugenia Sokolinski
Project Coordinator
Hiob Ludolf Centre for Ethiopian Studies
Asien Afrika Institut
Universit�t Hamburg
Alsterterrasse 1
20354 Hamburg

eugenia.sokolinski@uni-hamburg.de

http://www1.uni-hamburg.de/ethiostudies
http://www.traces.uni-hamburg.de

**Comment by eu-genia** [comment]
i have changed to en-GB

can be merged (the long history is my mistake, it is a simple dependent style)

Quoting Sebastian Karcher <notifications@github.com>:

> no, mainly because of the request above, though yes, this is  
> probably a bit much history for a single dependent style.
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/1979#issuecomment-201383893



-- 
Eugenia Sokolinski
Project Coordinator
Hiob Ludolf Centre for Ethiopian Studies
Asien Afrika Institut
Universit�t Hamburg
Alsterterrasse 1
20354 Hamburg

eugenia.sokolinski@uni-hamburg.de

http://www1.uni-hamburg.de/ethiostudies
http://www.traces.uni-hamburg.de

**Comment by eu-genia** [comment]
is the style ok now? anything else to do?

**Comment by rmzelle** [comment]
Yes, you're all set (@adam3smith added this by hand to limit the number of commits going into the repository)

**Comment by eu-genia** [comment]
thanks a lot!

**Pull request closed without merging**
