### PR TITLE
Modifications to collapse multiple citations from [1,2,3,4] to [1-4] and...

### PR DESCRIPTION
**Pull request by dmkaplan2000**
... to avoid trailing comma on doi.  Also doing nice things like adding myself as a contributor and updating update date.  But the style still deals miserably with non-journal references and position of year between journal volume and pages is unusual - both of these are from original file and have not been modified by myself.

NOTE: The version of this style that is currently on the official github repository seems to be older than what is available on the Zotero Style Repository.  Most of the differences between the two appear to be editorial.  I have modified the version that is on the Zotero Style Repository, which appears to be newer.

### CODE REVIEW

**Comment by adam3smith** [comment]
no, you're modifying an old fork, the Zotero style repository is build directly from this one, so it's never ahead. 
If you're interested in making this work, you'd need to update master from origin in your fork and then rebase to master. If that sounds Latin/G(r)eek to you, I can just implement the changes manually over the weekend.

**Comment by dmkaplan2000** [comment]
Hi,

Thanks for your patience.  I have no idea how I ended up on a random 
fork.  What you are saying to me isn't exactly Greek, more like a 
strange form of English.  Other than starting over with a clean fork 
(which isn't that hard), I can't see how to fix this.  If you have the 
magic formula, let me know...

Thanks,
David

**Comment by dmkaplan2000** [comment]
OK, I did some banging on the keyboard and I *think* I am now up to date 
with the official repository.  I added a remote for the official 
repository, fetched the changes, merged them into my local master and 
then committed and pushed everything back to my fork on github, dealing 
with the conflict between versions of the NSF file along the way.  Is 
this what you had in mind?  Do I need to generate a new pull request?

Cheers,
David

**Comment by adam3smith** [comment]
this worked swimmingly, thanks!

**Comment by rmzelle** [comment]
:fish:

**Comment by rmzelle** [comment]
> I added a remote for the official
repository, fetched the changes, merged them into my local master and
then committed and pushed everything back to my fork on github, dealing
with the conflict between versions of the NSF file along the way.  Is
this what you had in mind?

Yes, that's about the way to go. It easier if you always keep your "master" branch clean, so you can easily update it from the remote without getting merge conflicts. Then you can create a branch off of "master" and make your changes there.

**Pull request merged**
