### PR TITLE
Create depro-ufs.csl

### PR DESCRIPTION
**Pull request by isabellypsilva**
I created this based on "Universidade Federal do Rio Grande do Sul - ABNT (autoria abreviada) (Portuguese - Brazil)" style  (http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-ufrgs-initials) to fit the requirements of my institution.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this citation format?

And this is for the Departamento de Engenharia de Produção da Universidade Federal de Sergipe (DEPRO/UFS) (http://depro.ufs.br/), correct?

**Comment by isabellypsilva** [comment]
Hi.

Yes. There is an online style guide but it is still being prepared. The material can be accessed through the link: http://depro.ufs.br/pagina/22237.

This also answers your second question. The address http://depro.ufs.br/ is the address of the educational institution where the proposed style would be used.

Thanks.

**Comment by rmzelle** [comment]
Thanks! Do you think we should add "ABNT" to the style title? (we seem to use it for most ABNT-derived styles; see https://www.zotero.org/styles?q=universidade)

**Comment by isabellypsilva** [comment]
Yes, that would be great. Thank you.

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
