### PR TITLE
Update arts-university-bournemouth.csl

### PR DESCRIPTION
**Pull request by Dbelk**
We have done quite a lot of work to get the references and citations for films similar to those of other references (although this can probably be done more gracefully/with less repetition) but we have also closed the gaps between initials in references, changed our element separator to a full stop, and removed the quotes from titles.

(RZ: replacement of #2899)

### CODE REVIEW

**Comment by Dbelk** [comment]
I'm really confused by the error message. 
Is there a plain English explanation of why the way we have used the 'director' macro is wrong, and how we might fix it (it passed thought the validation at http://validator.citationstyles.org/): 

  1) arts-university-bournemouth: may not have any unused macros
     Failure/Error: expect(available_macros - used_macros).to eq([])
     
       expected: []
            got: ["director"]
     
       (compared using ==)
     Shared Example Group: "style" called from ./spec/styles_spec.rb:216
     # ./spec/styles_spec.rb:70:in `block (2 levels) in <top (required)>'
 145859/145859 |==================== 100 =====================>| Time: 00:01:55 
Finished in 1 minute 55.8 seconds (files took 1 minute 18.26 seconds to load)
145859 examples, 1 failure
Failed examples:
rspec ./spec/styles_spec.rb[166:10] # arts-university-bournemouth: may not have any unused macros

PS, sorry, i don't know how to 'make commits to the current pull request branch' (i don't really now what it means), hence the creating new pull request. Are there instructions on this?

**Comment by rmzelle** [comment]
> Is there a plain English explanation of why the way we have used the 'director' macro is wrong, and how we might fix it

For the repository, we don't allow styles to contain any macros that aren't used. Your current version has one of those, named "director". Deleting this "director" macro will clear the error.



> i don't know how to 'make commits to the current pull request branch' (i don't really now what it means), hence the creating new pull request. Are there instructions on this?

Click the pencil icon at https://github.com/citation-style-language/styles/pull/2903/files (it's on the right, at the top of the style file panel) to start editing.

**Comment by Dbelk** [comment]
Hi,

To respond to the first point below, we do use the Director macro though (in lines 23-28 of our file); when we create a reference for a film, we have to use the Director tag (see attached screenshot), and therefore we have to have a Director macro, don’t we?
The way I created our style was the only way I could see to make the Director appear with the same formatting as an Author in the citation and bibliography (so many institutions don’t do this and it just looks poorly done; we didn’t want to follow suit).
Is there another way to make a Director conform to the same formatting as an Author?

Duncan


Duncan Belk
Digital Services Librarian
+441202363394
dbelk@aub.ac.uk
aub.ac.uk

​The contents of this communication are confidential and intended solely for the use of the named recipient(s). If you have received this email in error please delete it and do not disseminate, distribute, copy or alter it. Any views or opinions expressed are those of the author and do not necessarily represent those of Arts University Bournemouth.

Although  Arts University Bournemouth has taken reasonable precautions to ensure no viruses are present in this email, the University cannot accept responsibility for any loss or damage arising from the use of this email or attachments.

**Comment by rmzelle** [comment]
@Dbelk, email attachments don't work on GitHub, but you can attach them via the GitHub website. See https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

And you define the "director" macro on lines 23-28, but then don't actually use that macro anywhere in the style. (you are substituting the "director" variable in the "author" and "author-short" macros, but that doesn't involve the "director" macro)

**Comment by rmzelle** [comment]
Your submissions also lack correct indenting. How exactly are you copying and pasting the style code into the GitHub window?

You can quickly get the correct formatting by copying and pasting your style code into our formatter at http://formatter.citationstyles.org/, and then update the pull request with the reformatted style (assuming you have figured out how to do that last bit).

**Comment by Dbelk** [comment]
Okay, i have now removed the Director macro. Sorry, i thought i needed this in order to use the substitute.
I have also put the text file i was using through your formatter. Hopefully this will meet all your needs.

**Comment by rmzelle** [comment]
Thanks! And happy to see you figured out how to edit the existing pull request :).

I made a few minor changes, so please start from the latest repository version if you would like to submit more changes in the future.

**Pull request merged**
