### PR TITLE
Create health-education-england-harvard-citation-style.csl

### PR DESCRIPTION
**Pull request by mattjholland**
This is a new style for Higher Education England for use primarily by NHS healthcare librarians.

### CODE REVIEW

**Comment by adam3smith** [comment]
@mattjholland just to make sure we're on the same page: we currently have this on hold while waiting for some sort of documentation for the style. No rush from our end, but I wanted to make sure there was no misunderstanding.

**Comment by mattjholland** [comment]
Hello,

I have made some changes and added links to documentation and tidied up a broken link.  Can this now go forward to the repository?

Best wishes

Matt

**Comment by adam3smith** [comment]
Should this be Health Education or Higher Education? The title & id/link/filename should align. The linked style is also called "higher education"

**Comment by mattjholland** [comment]
It should be Health-education- england I have tried to change the name but I am not sure it was successful. BW Matt

**Comment by adam3smith** [comment]
Thanks (you still had the id and the link set to "higher education" -- the guide currently also says "higher eduction" so maybe fix that when you get a chance.

**Pull request merged**
