### PR TITLE
Add Vegetation classification and Survey

### PR DESCRIPTION
**Pull request by adam3smith**
closes #5221

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle do you understand the error(s) here? -- I assume related to the recent Sheldon updates, but not quite sure what's going on. CC @retorquere

**Comment by rmzelle** [comment]
Did dependent styles ever render correctly?

**Comment by rmzelle** [comment]
> Your submission passed all our automated tests.

Ah, I see that despite the message above, that the build failed with `NameError: uninitialized constant YAML`. That must be related to https://github.com/citation-style-language/styles/pull/5268.

**Comment by rmzelle** [comment]
Maybe it just requires a `require 'yaml'` (https://github.com/ryanb/private_pub/issues/118#issuecomment-162261474)?

**Comment by retorquere** [comment]
Yeah, it must require YAML - I thought YAML was just always available in ruby. Sorry about this people.

**Comment by rmzelle** [comment]
(@adam3smith, did you create a PR for the journals repo as well?)

**Comment by adam3smith** [comment]
I have one ready yes, just not pushed yet.

**Pull request merged**
