### PR TITLE
Revert 3 yrg23 patch 3

### PR DESCRIPTION
**Pull request by yrg23**

### CODE REVIEW

**Comment by rmzelle** [comment]
@yrg23, what are you trying to achieve here, exactly?

If you wish to update this style, it's much better to follow the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style.

**Comment by yrg23** [comment]
i will follow the instructions next time. so sorry...

**Comment by rmzelle** [comment]
No worries, but it looks like you might not be making the changes you want to make.

Was the switch from British to US English intentional? (https://github.com/citation-style-language/styles/commit/ef19002b7667c7ab88c69ed15d7a3d7c46731b45)

**Comment by yrg23** [comment]
yes. but we can completely ignore this pull request. i have opened another including all the changes i wanted to make

**Pull request closed without merging**
