### PR TITLE
Update harvard-university-for-the-creative-arts.csl

### PR DESCRIPTION
**Pull request by ibadger**
Style has always referenced basic material - books, journals, websites well. But this update should bring improvements to other source types such as maps, artworks and online material which are increasingly popular to reference by students at UCA. I hadn't updated the style for a while as UCA had a subscription to RefME and they looked after it within their site, since they have been taken over our University is looking to recommend Zotero in the first instance so major updates are required.

### CODE REVIEW

**Comment by rmzelle** [comment]
> I hadn't updated the style for a while as UCA had a subscription to RefME and they looked after it within their site, since they have been taken over our University is looking to recommend Zotero in the first instance so major updates are required.

Did you make the changes you're proposing yourself? Or is this a version RefME made?

**Comment by rmzelle** [comment]
(I guess it doesn't really matter, since you're the original author of this style (https://github.com/citation-style-language/styles/pull/1079), and any subsequent tweaks to this style would have inherited the style's CC-BY-SA license. I'm just curious since we're in contact with Chegg/RefME, and we asked them if they would be willing to contribute any styles they created from scratch back to this repository. Still waiting on an answer.)

**Comment by ibadger** [comment]
No these are changes that I’ve made myself.

The last version that I had approved by you and the Github, last summer I think, is the one that I have updated myself here.

At that point they fiddled with it, but that version only exists within their system, which will no longer exist after 28 Feb

––––––––––––
Ian Badger
Learning & Teaching Librarian |  Library & Student Services
–
University for the Creative Arts
New Dover Road
Canterbury
Kent CT1 3AN
–
Telephone: 01227 817370
www.uca.ac.uk<http://www.uca.ac.uk>
UCA Twitter: @LibraryUCA<http://www.twitter.com/libraryuca>
Facebook: ucacanterburylibrary<http://www.facebook.com/UCALibraryCanterbury>
–
UCA is a top 40 university, this year entering the Guardian University Guide league table at position 39, with its School of Architecture placed 5th in the Subject listings. For over 150 years the University for the Creative Arts in Canterbury, Epsom, Farnham, Maidstone and Rochester has been leading the way for art and design education.

**Comment by rmzelle** [comment]
Perfect, thanks. (I just removed a few redundant group elements)

**Comment by ibadger** [comment]
I can provide a bit of background.

They used my CSL, which was already in their system. They then renamed and created new source types to match the terminology in our referencing guide.

When I exported the references (we collaborated on replicating the UCA reference style in RefME) out of RefME and put them into Zotero a lot of the source types were a little surprising, I’ve attached a RIS file of the text references from our guide. They kind of used whatever source types they felt fitted best, rather than the ones that relate to the material that is being referenced. So I would think that some of the ones they wrote from scratch wouldn’t match what you are looking for.

The guy from RefME who edited our style now works for Chegg

Thanks for your help. If you have any more questions about RefME just get in touch


––––––––––––
Ian Badger
Learning & Teaching Librarian |  Library & Student Services
–
University for the Creative Arts
New Dover Road
Canterbury
Kent CT1 3AN
–
Telephone: 01227 817370
www.uca.ac.uk<http://www.uca.ac.uk>
UCA Twitter: @LibraryUCA<http://www.twitter.com/libraryuca>
Facebook: ucacanterburylibrary<http://www.facebook.com/UCALibraryCanterbury>
–
UCA is a top 40 university, this year entering the Guardian University Guide league table at position 39, with its School of Architecture placed 5th in the Subject listings. For over 150 years the University for the Creative Arts in Canterbury, Epsom, Farnham, Maidstone and Rochester has been leading the way for art and design education.

**Comment by rmzelle** [comment]
> So I would think that some of the ones they wrote from scratch wouldn’t match what you are looking for.

Thanks for providing some background info. We'll just wait and see whether Chegg/RefME is willing to share any of their in-house developed CSL styles, and if so, if they're of sufficient quality to add them to the repository.

**Pull request merged**
