### PR TITLE
Create method-and-theory-in-the-study-of-religion.csl

### PR DESCRIPTION
**Pull request by Giovanni-Maltese**

### CODE REVIEW

**Comment by Giovanni-Maltese** [comment]
Sorry, found some corrigenda. Here is a revised CSL:

<?xml version="1.0" encoding="utf-8"?>
<style class="in-text" version="1.0" et-al-min="1" et-al-use-first="2" et-al-subsequent-min="1" et-al-subsequent-use-first="1" initialize="false" page-range-format="expanded" demote-non-dropping-particle="sort-only" default-locale="en-US" xmlns="http://purl.org/net/xbiblio/csl">
  <info>
    <title>Method &amp; Theory in the Study of Religion</title>
    <title-short>MTSR</title-short>
    <id>http://www.zotero.org/styles/method-and-theory-in-the-study-of-religion</id>
    <link href="http://www.zotero.org/styles/method-and-theory-in-the-study-of-religion" rel="self"/>
    <link href="http://www.zotero.org/styles/original-style" rel="template"/>
    <link href="http://gbfe.org/" rel="documentation"/>
    <link href="http://www.acf.de/uploads/media/GBFE_Studienbrief_5_Form_bewahren_01.pdf" rel="documentation"/>
    <author>
      <name>Giovanni Maltee</name>
      <email>Giovanni.Maltese@uni-hamburg.de</email>
    </author>
    <contributor/>
    <category citation-format="author-date"/>
    <category field="Religious Studies"/>
    <category field="Cultural Studies"/>
    <category field="Humanities"/>
    <issn>0943-3058</issn>
    <issn>1570-0682</issn>
    <updated>2020-09-25T11:51:56+00:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>
  </info>
  <locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="de-DE">
    <terms>
      <term name="page">
        <single>Seite</single>
        <multiple>Seiten</multiple>
      </term>
      <term name="page" form="short">S.</term>
      <term name="editor">Herausgeber</term>
      <term name="editor" form="short">(eds.)</term>
      <term name="edition">
        <single>Auflage</single>
        <multiple>Auflagen</multiple>
      </term>
      <term name="edition" form="short">
        <single>Auflage</single>
        <multiple>Auflagen</multiple>
      </term>
      <term name="ordinal-01">.</term>
      <term name="ordinal-02">.</term>
      <term name="ordinal-03">.</term>
      <term name="ordinal-04">.</term>
      <term name="accessed">Accessed:</term>
    </terms>
    <date form="text">
      <date-part name="month" suffix=" "/>
      <date-part name="day" suffix=", "/>
      <date-part name="year"/>
    </date>
    <date form="numeric">
      <date-part name="year"/>
      <date-part name="month" form="numeric" prefix="-" range-delimiter="/"/>
      <date-part name="day" prefix="-" range-delimiter="/"/>
    </date>
    <style-options punctuation-in-quote="true"/>
  </locale>
  <macro name="author">
    <names variable="author">
      <name and="symbol" delimiter-precedes-last="never" et-al-min="2" et-al-use-first="2" et-al-subsequent-min="2" et-al-subsequent-use-first="2" initialize="false" name-as-sort-order="first"/>
      <label form="short" text-case="capitalize-first" prefix=" (" suffix=")"/>
      <substitute>
        <names variable="editor"/>
        <text macro="anon"/>
      </substitute>
    </names>
  </macro>
  <macro name="editor">
    <names variable="editor" delimiter=",">
      <name and="symbol" et-al-min="2" et-al-use-first="1" et-al-subsequent-min="2" et-al-subsequent-use-first="2"/>
      <label form="short" text-case="lowercase" prefix=" (" suffix=")"/>
    </names>
  </macro>
  <macro name="anon">
    <text term="anonymous" form="short" text-case="capitalize-first" strip-periods="true"/>
  </macro>
  <macro name="author-short">
    <names variable="author">
      <name form="short" and="text" delimiter-precedes-et-al="never" delimiter-precedes-last="never" et-al-min="2" et-al-use-first="1" et-al-subsequent-min="2" et-al-subsequent-use-first="1" initialize-with=". "/>
      <substitute>
        <names variable="editor"/>
        <names variable="translator"/>
        <text macro="anon"/>
      </substitute>
    </names>
  </macro>
  <macro name="access">
    <choose>
      <if variable="URL">
        <text variable="URL"/>
        <group prefix=" (" suffix=")">
          <text term="accessed" text-case="lowercase" suffix=" "/>
          <date variable="accessed">
            <date-part name="year" range-delimiter="/" suffix="/"/>
            <date-part name="month" form="numeric-leading-zeros" range-delimiter="/" suffix="/"/>
            <date-part name="day" range-delimiter="/"/>
          </date>
        </group>
      </if>
    </choose>
  </macro>
  <macro name="title">
    <choose>
      <if type="bill book graphic legal_case legislation motion_picture report song thesis webpage" match="any">
        <text variable="title" text-case="title" font-style="italic" font-variant="normal" suffix="."/>
      </if>
      <else>
        <text variable="title"/>
      </else>
    </choose>
  </macro>
  <macro name="publisher">
    <group delimiter=": ">
      <text variable="publisher-place"/>
      <text variable="publisher"/>
    </group>
  </macro>
  <macro name="year-date">
    <choose>
      <if variable="issued">
        <date variable="issued">
          <date-part name="year"/>
        </date>
      </if>
      <else>
        <text term="no date" form="short"/>
      </else>
    </choose>
  </macro>
  <macro name="edition">
    <choose>
      <if is-numeric="edition">
        <group delimiter=" ">
          <number variable="edition" form="ordinal"/>
          <text term="edition" form="short"/>
        </group>
      </if>
      <else>
        <text variable="edition" suffix="."/>
      </else>
    </choose>
  </macro>
  <citation et-al-min="3" et-al-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true">
    <layout prefix="(" suffix=")" delimiter="; ">
      <group delimiter=", ">
        <group>
          <text macro="author-short" suffix=" "/>
          <text macro="year-date"/>
          <text variable="locator" prefix=": "/>
        </group>
      </group>
    </layout>
  </citation>
  <bibliography et-al-min="4" et-al-use-first="1" initialize="false" hanging-indent="true">
    <sort>
      <key macro="author" names-use-first="2"/>
      <key variable="title"/>
    </sort>
    <layout>
      <text macro="author"/>
      <date variable="issued" prefix=" (" suffix=").">
        <date-part name="year"/>
      </date>
      <choose>
        <if type="bill book graphic legal_case legislation motion_picture report song" match="any">
          <group prefix=" " delimiter=" ">
            <text macro="title" text-case="title"/>
            <text variable="volume" prefix="Bd. " suffix=", "/>
            <text variable="issue" suffix=", "/>
            <text macro="edition"/>
            <text macro="editor"/>
          </group>
          <text prefix=" " suffix="." macro="publisher"/>
        </if>
        <else-if type="chapter paper-conference" match="any">
          <text macro="title" prefix=" " suffix="."/>
          <group prefix=" " delimiter=" ">
            <text term="in" text-case="capitalize-first" suffix=":"/>
            <text macro="editor"/>
            <text variable="container-title" text-case="title" font-style="italic" suffix="."/>
            <text variable="collection-title" suffix="."/>
            <text variable="event" suffix="."/>
            <group suffix="." delimiter=", ">
              <text macro="publisher" prefix=" "/>
              <text variable="page" prefix="pp. "/>
            </group>
          </group>
        </else-if>
        <else-if type="thesis">
          <group prefix=" " suffix=".">
            <text macro="title" suffix=". "/>
            <text variable="genre" suffix=". "/>
            <text variable="publisher" suffix=", "/>
            <text variable="publisher-place"/>
          </group>
        </else-if>
        <else-if type="webpage post-weblog post" match="any">
          <group prefix=" " delimiter=" " suffix=". ">
            <text macro="title"/>
            <text variable="container-title"/>
            <text macro="edition"/>
            <text macro="editor"/>
          </group>
        </else-if>
        <else-if type="entry-encyclopedia entry-dictionary" match="any">
          <group suffix=".">
            <text macro="title" prefix=" "/>
            <text macro="editor" prefix=" "/>
          </group>
          <group prefix=" " suffix=".">
            <text variable="container-title" font-style="italic"/>
            <text variable="edition" vertical-align="sup"/>
            <group prefix=" ">
              <text variable="volume"/>
              <text variable="issue" prefix="(" suffix=")"/>
            </group>
            <group prefix=",">
              <text variable="page"/>
            </group>
          </group>
        </else-if>
        <else-if type="article-magazine article-newspaper article-journal" match="any">
          <group suffix=".">
            <text macro="title" prefix=" "/>
            <text macro="editor" prefix=" "/>
          </group>
          <group prefix=" " suffix=".">
            <text variable="container-title" font-style="italic" suffix=" "/>
            <text variable="volume" suffix=" "/>
            <text variable="issue" prefix="(" suffix="), "/>
            <text variable="page" prefix="pp. "/>
          </group>
        </else-if>
        <else>
          <group suffix=".">
            <text macro="title" text-case="title" prefix=" "/>
            <text macro="editor" prefix=" "/>
          </group>
          <group prefix=" " suffix=".">
            <text variable="container-title" font-style="italic"/>
            <group prefix=", ">
              <text variable="volume"/>
              <text variable="issue" prefix="(" suffix=")"/>
            </group>
            <group prefix=", ">
              <text variable="page"/>
            </group>
          </group>
        </else>
      </choose>
      <text prefix=" " macro="access" suffix="."/>
    </layout>
  </bibliography>
</style>

**Comment by Giovanni-Maltese** [comment]
<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" et-al-min="1" et-al-use-first="2" et-al-subsequent-min="1" et-al-subsequent-use-first="1" initialize="false" page-range-format="expanded" demote-non-dropping-particle="sort-only" default-locale="en-US">
  <info>
    <title>Method &amp; Theory in the Study of Religion</title>
    <title-short>MTSR</title-short>
    <id>http://www.zotero.org/styles/method-and-theory-in-the-study-of-religion</id>
    <link href="http://www.zotero.org/styles/method-and-theory-in-the-study-of-religion" rel="self"/>
    <link href="http://www.zotero.org/styles/apa-6th-edition" rel="template"/>
    <link href="http://gbfe.org/" rel="documentation"/>
    <link href="http://www.acf.de/uploads/media/GBFE_Studienbrief_5_Form_bewahren_01.pdf" rel="documentation"/>
    <author>
      <name>Giovanni Maltee</name>
      <email>Giovanni.Maltese@uni-hamburg.de</email>
    </author>
    <category citation-format="author-date"/>
    <category field="Religious Studies"/>
    <category field="Cultural Studies"/>
    <category field="Humanities"/>
    <issn>0943-3058</issn>
    <issn>1570-0682</issn>
    <updated>2020-09-25T14:07:05+00:00</updated>
    <rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>
  </info>
  <locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="en-AE">
    <terms>
      <term name="page">
        <single>Seite</single>
        <multiple>Seiten</multiple>
      </term>
      <term name="page" form="short">S.</term>
      <term name="editor">Herausgeber</term>
      <term name="editor" form="short">(eds.)</term>
      <term name="edition">
        <single>Auflage</single>
        <multiple>Auflagen</multiple>
      </term>
      <term name="edition" form="short">
        <single>Auflage</single>
        <multiple>Auflagen</multiple>
      </term>
      <term name="ordinal-01">.</term>
      <term name="ordinal-02">.</term>
      <term name="ordinal-03">.</term>
      <term name="ordinal-04">.</term>
      <term name="accessed">Accessed:</term>
    </terms>
    <date form="text">
      <date-part name="month" suffix=" "/>
      <date-part name="day" suffix=", "/>
      <date-part name="year"/>
    </date>
    <date form="numeric">
      <date-part name="year"/>
      <date-part name="month" form="numeric" prefix="-" range-delimiter="/"/>
      <date-part name="day" prefix="-" range-delimiter="/"/>
    </date>
    <style-options punctuation-in-quote="true"/>
  </locale>
  <macro name="author">
    <names variable="author">
      <name and="symbol" delimiter-precedes-last="never" et-al-min="3" et-al-use-first="2" et-al-subsequent-min="2" et-al-subsequent-use-first="2" initialize="false" name-as-sort-order="first"/>
      <label form="short" text-case="capitalize-first" prefix=" (" suffix=")"/>
      <substitute>
        <names variable="editor"/>
        <text macro="anon"/>
      </substitute>
    </names>
  </macro>
  <macro name="editor">
    <names variable="editor" delimiter=",">
      <name and="symbol" et-al-min="2" et-al-use-first="1" et-al-subsequent-min="2" et-al-subsequent-use-first="1"/>
      <label form="short" text-case="lowercase" prefix=" (" suffix=")"/>
    </names>
  </macro>
  <macro name="anon">
    <text term="anonymous" form="short" text-case="capitalize-first" strip-periods="true"/>
  </macro>
  <macro name="author-short">
    <names variable="author">
      <name form="short" and="text" delimiter-precedes-et-al="never" delimiter-precedes-last="never" et-al-min="2" et-al-use-first="1" et-al-subsequent-min="2" et-al-subsequent-use-first="1" initialize-with=". "/>
      <substitute>
        <names variable="editor"/>
        <names variable="translator"/>
        <text macro="anon"/>
      </substitute>
    </names>
  </macro>
  <macro name="access">
    <choose>
      <if variable="URL" type="broadcast thesis webpage entry-encyclopedia manuscript">
        <text variable="URL"/>
        <group prefix=" (" suffix=")">
          <text term="accessed" text-case="lowercase" suffix=" "/>
          <date variable="accessed">
            <date-part name="year" range-delimiter="/" suffix="/"/>
            <date-part name="month" form="numeric-leading-zeros" range-delimiter="/" suffix="/"/>
            <date-part name="day" form="numeric-leading-zeros" range-delimiter="/"/>
          </date>
        </group>
      </if>
    </choose>
  </macro>
  <macro name="title">
    <choose>
      <if type="bill book graphic legal_case legislation motion_picture report song thesis webpage" match="any">
        <text variable="title" text-case="title" font-style="italic" font-variant="normal" suffix="."/>
      </if>
      <else>
        <text variable="title"/>
      </else>
    </choose>
  </macro>
  <macro name="publisher">
    <group delimiter=": ">
      <text variable="publisher-place"/>
      <text variable="publisher"/>
    </group>
  </macro>
  <macro name="year-date">
    <choose>
      <if variable="issued">
        <date variable="issued">
          <date-part name="year"/>
        </date>
      </if>
      <else>
        <text term="no date" form="short"/>
      </else>
    </choose>
  </macro>
  <macro name="edition">
    <choose>
      <if is-numeric="edition">
        <group delimiter=" ">
          <number variable="edition" form="ordinal"/>
          <text term="edition" form="short"/>
        </group>
      </if>
      <else>
        <text variable="edition" suffix="."/>
      </else>
    </choose>
  </macro>
  <citation et-al-min="3" et-al-use-first="1" disambiguate-add-year-suffix="true" disambiguate-add-names="true" disambiguate-add-givenname="true">
    <layout prefix="(" suffix=")" delimiter="; ">
      <group delimiter=", ">
        <group>
          <text macro="author-short" suffix=" "/>
          <text macro="year-date"/>
          <text variable="locator" prefix=": "/>
        </group>
      </group>
    </layout>
  </citation>
  <bibliography et-al-min="4" et-al-use-first="1" initialize="false" hanging-indent="true">
    <sort>
      <key macro="author" names-use-first="2"/>
      <key variable="title"/>
    </sort>
    <layout>
      <text macro="author"/>
      <date variable="issued" prefix=" (" suffix=").">
        <date-part name="year"/>
      </date>
      <choose>
        <if type="bill book graphic legal_case legislation motion_picture report song" match="any">
          <group prefix=" " delimiter=" ">
            <text macro="title" text-case="title"/>
            <text variable="volume" prefix="Bd. " suffix=", "/>
            <text variable="issue" suffix=", "/>
            <text macro="edition"/>
            <text macro="editor"/>
          </group>
          <text prefix=" " suffix="." macro="publisher"/>
        </if>
        <else-if type="chapter paper-conference" match="any">
          <text macro="title" prefix=" " suffix="."/>
          <group prefix=" " delimiter=" ">
            <text term="in" text-case="capitalize-first" suffix=":"/>
            <text macro="editor"/>
            <text variable="container-title" text-case="title" font-style="italic" suffix="."/>
            <text variable="collection-title" suffix="."/>
            <text variable="event" suffix="."/>
            <group suffix="." delimiter=", ">
              <text macro="publisher" prefix=" "/>
              <text variable="page" prefix="pp. "/>
            </group>
          </group>
        </else-if>
        <else-if type="thesis">
          <group prefix=" " suffix=".">
            <text macro="title" suffix=". "/>
            <text variable="genre" suffix=". "/>
            <text variable="publisher" suffix=", "/>
            <text variable="publisher-place"/>
          </group>
        </else-if>
        <else-if type="webpage post-weblog post" match="any">
          <group prefix=" " delimiter=" " suffix=". ">
            <text macro="title"/>
            <text variable="container-title"/>
            <text macro="edition"/>
            <text macro="editor"/>
          </group>
        </else-if>
        <else-if type="entry-encyclopedia entry-dictionary" match="any">
          <group suffix=".">
            <text macro="title" prefix=" "/>
            <text macro="editor" prefix=" "/>
          </group>
          <group prefix=" " suffix=".">
            <text variable="container-title" font-style="italic"/>
            <text variable="edition" vertical-align="sup"/>
            <group prefix=" ">
              <text variable="volume"/>
              <text variable="issue" prefix="(" suffix=")"/>
            </group>
            <group prefix=",">
              <text variable="page"/>
            </group>
          </group>
        </else-if>
        <else-if type="article-magazine article-newspaper article-journal" match="any">
          <group suffix=".">
            <text macro="title" prefix=" "/>
            <text macro="editor" prefix=" "/>
          </group>
          <group prefix=" " suffix=".">
            <text variable="container-title" font-style="italic" suffix=" "/>
            <text variable="volume" suffix=" "/>
            <text variable="issue" prefix="(" suffix="), "/>
            <text variable="page" prefix="pp. "/>
          </group>
        </else-if>
        <else>
          <group suffix=".">
            <text macro="title" text-case="title" prefix=" "/>
            <text macro="editor" prefix=" "/>
          </group>
          <group prefix=" " suffix=".">
            <text variable="container-title" font-style="italic"/>
            <group prefix=", ">
              <text variable="volume"/>
              <text variable="issue" prefix="(" suffix=")"/>
            </group>
            <group prefix=", ">
              <text variable="page"/>
            </group>
          </group>
        </else>
      </choose>
      <text prefix=" " macro="access" suffix="."/>
    </layout>
  </bibliography>
</style>

**Comment by adam3smith** [comment]
There seems to be some misunderstanding here: You can't update the style by pasting code into an email/comment window. You'd need to do this either on the github website as described above or via a github tool.

**Comment by rmzelle** [comment]
@Giovanni-Maltese, thanks. As @adam3smith, it's better to update the pull request yourself (see https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#4-update-your-pull-request for instructions).

In this case, I went ahead and used the version in your latest comment. It looks like your style has been based on the "Gesellschaft für Bildung und Forschung in Europa - Harvard (German)" style, and I changed the et-al settings to match what https://brill.com/fileasset/downloads_products/Author_Instructions/MTSR.pdf dictates.

**Pull request merged**
