### PR TITLE
Officially supported by Institut Teknologi Bandung

### PR DESCRIPTION
**Pull request by ceefour**
This CSL is now officially supported by Institut Teknologi Bandung (I am currently assigned as the maintainer).

### CODE REVIEW

**Comment by adam3smith** [comment]
Could you clarify why you're renaming the style? "SP" seems a lot less clear to me than "Tesis Magister" (and we generally try to avoid acronyms in style names).

**Comment by ceefour** [comment]
@adam3smith SPs is the mother organization of all graduate programs in Institut Teknologi Bandung (everyone studying here knows it), including master and doctor. "Tesis Magister" only refer to the masters citation style, while now the styles are unified (used by both masters and doctoral).

**Comment by rmzelle** [comment]
Thanks! (I replaced the "SPs" by the full "Sekolah Pascasarjana", since we avoid abbreviations in CSL repository style titles whenever feasible)

**Comment by ceefour** [comment]
Thank you @rmzelle :)

**Pull request merged**
