### PR TITLE
Create comptes-rendus-numeric.csl

### PR DESCRIPTION
**Pull request by justinefabre**
Following a discussion with Adam Smith (https://github.com/citation-style-language/styles/pull/6626), I am creating two new independent styles : comptes-rendus-numeric and comptes-rendus-author-date. The other styles I already created can then be added as dependants from these.

### CODE REVIEW

**Comment by adam3smith** [comment]
Do you have the guides available online somewhere? If so, could you add them as a link with `rel="documentation"` please?

**Comment by justinefabre** [comment]
Not for the moment, sorry :-(

**Comment by adam3smith** [comment]
Thanks! The quickest way to get the dependent styles in would be to get us a spreadsheet that has their metadata (name, field, category, ISSN, e-ISSN, which of the two styles it applies to)

**Comment by justinefabre** [comment]
Thank you very much, here is the spreadsheet ! I am not sure about the "category" metadata, though. What is it ? Thank you in advance.
[Info_CR_styles.xlsx](https://github.com/citation-style-language/styles/files/12828136/Info_CR_styles.xlsx)

**Pull request merged**
