### PR TITLE
Update revista-fave-seccion-ciencias-agrarias.csl

### PR DESCRIPTION
**Pull request by alexo81**
I've changed the citation-format from "author-date" to "number" according to journal's guidelines.

### CODE REVIEW

**Comment by adam3smith** [comment]
a) it's `numeric` not number
b) you can't just change the description--you'd actually have to change how the style formats citations, which is author-date in the current style.

**Comment by rmzelle** [comment]
Yeah, nothing within the `<info/>` section influences the actual style format.

**Comment by alexo81** [comment]
Sorry for that. I've updated the <info/> section along with the <citation/> and <bibliography/> with commit `bdba155`. Commit `810360f` fixes accent issue in <id/> and <self/>.

**Comment by rmzelle** [comment]
Sorry, but could you create a new pull request based on the latest version of the style at https://github.com/citation-style-language/styles/blob/master/revista-fave-seccion-ciencias-agrarias.csl?

We can't merge this pull request, since we made some changes to your style after we accepted it (see https://github.com/citation-style-language/styles/commits/master/revista-fave-seccion-ciencias-agrarias.csl ).

**Comment by rmzelle** [comment]
@alexo81, I created a new pull request (#1821) to merge in your changes, along with a few additional edits.

**Pull request closed without merging**
