### PR TITLE
Update chicago-fullnote-bibliography.csl

### PR DESCRIPTION
**Pull request by flatride**
I added the Date (issued) to the abbreviated subsequent citations

### CODE REVIEW

**Comment by adam3smith** [comment]
Why? The Chicago Manual doesn't do this for short notes (with few exceptions such as letters, which would require a more elaborate fix)

**Comment by flatride** [comment]
Thanks for your swift reply. 
I do not need to adhere to a specific style for my research. I can simply have it the way I find it useful.
Since it isnt possible to simply change the citation style locally without zotero always changing back to the original style, I had to do it this way.

**Comment by adam3smith** [comment]
You can absolutely edit styles in Zotero locally and have changes remain, you just need to change style title and ID as explained here: https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step#change_the_style_title_and_id

**Comment by flatride** [comment]
I did change the Style title and the ID but it still wouldnt let me. It always switches back!

**Comment by adam3smith** [comment]
Rename the file, too, just to be sure, but I'm absolutely positive this works. Are you sure you've changed the ID?

**Comment by flatride** [comment]
Habs rausgefunden! Musste im Word file in den document preferences den Zitierstil ändern, nicht bloss in Zotero auf meinen Stil klicken (das ändert den Zitierstil im Worddokument nämlich auch, allerdings nur so lange, bis Zotero wieder neu gestartet wird.
Vielen Dank Dir und schönes Wochenende!

In case you do not speak German – it works now. thanks!

**Pull request closed without merging**
