### PR TITLE
Update metropol-verlag.csl

### PR DESCRIPTION
**Pull request by rewa1962**
version of 2018 was not the last version of the CSL.
some faults have been corrected in the version of 2019
for example "in:" instead of faulty "in,"

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks!

**Comment by rewa1962** [comment]
Here is the good one!

**Comment by rewa1962** [comment]
Hello,
This did not work out well, it is still the old style!
Could you please look at it again?
Thank you
Renée Wagener

**Comment by bwiernik** [comment]
Updated style is here https://raw.githubusercontent.com/citation-style-language/styles/master/metropol-verlag.csl

This will appear on the Zotero style repository in the next day or so

**Comment by rewa1962** [comment]
Ok, I did not know this. I will have a look in a few days then. Thank you!

**Pull request merged**
