### PR TITLE
Create institut-de-recherches-archeologiques-preventives.csl

### PR DESCRIPTION
**Pull request by Clem-F**

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

And did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by Clem-F** [comment]
Thanks for your comments.
I added the two missing lines : 
  - \<link [...] rel="template"/>
  - \<link [...] rel="documentation"/>

**Comment by adam3smith** [comment]
(The preview shown here is incorrect, so don't worry about that)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
