### PR TITLE
Create jcr-journal-of-clinical-rheumatology.csl

### PR DESCRIPTION
**Pull request by damnation333**
https://forums.zotero.org/discussion/56395/style-request-journal-of-clinical-rheumatology
AMA style with minor changes only.

### CODE REVIEW

**Comment by rmzelle** [comment]
Renamed based on https://www.ncbi.nlm.nih.gov/nlmcatalog?term=1076-1608%5BISSN%5D

**Comment by rmzelle** [comment]
Thanks!

**Comment by damnation333** [comment]
Thanks, @rmzelle 
Sorry about the documentation link. Restarted making the style with a new template and missed that one then.

**Comment by rmzelle** [comment]
No problem. It always helps to have a second pair of eyes look things over.

**Pull request merged**
