### PR TITLE
Update chicago-author-date-fr.csl

### PR DESCRIPTION
**Pull request by apinea**
Edits made to reflect changes made in the most recent edition of Chicago (17th).
Please see file attached (top of page, under "Chicago 17 Auteur-date") for overview of key changes made. Additional changes were made with the guidance of University of Montreal librarians.

[Feuille synthese des changements a faire dans le style CSL pour Zotero.docx](https://github.com/citation-style-language/styles/files/3223930/Feuille.synthese.des.changements.a.faire.dans.le.style.CSL.pour.Zotero.docx)

### CODE REVIEW

**Comment by apinea** [comment]
Do any further edits need to be made on my end for this updated style to be published? Thank you!

**Comment by apinea** [comment]
Bump

**Comment by apinea** [comment]
Bump

**Comment by apinea** [comment]
bump

**Comment by adam3smith** [comment]
@apinea sorry again this took so long. This all seems good to me with the exception of "et al." being in italics in the bibliography. That's not in line with Chicago style and I don't think the guide at U Montreal prescribes it:
> Si plus de dix auteurs sont mentionnés, on indique les sept premiers suivis de l’abréviation _et al._

just has et al in italics because all abbreviations referred to in the text are.

**Comment by apinea** [comment]
@adam3smith Recommended changes have been made to the latest version. Thank you!

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
