### PR TITLE
Update harvard-cardiff-university.csl

### PR DESCRIPTION
**Pull request by YoungZoe**
Cardiff University have changed their Harvard style so this is the old version which may still be used by some students until the end of the year. There is no longer any documentation available for it. This style also has a dependent style (Welsh version) that would need the title and id changing "Prifysgol Caerdydd - hen Harvard (Welsh)"

### CODE REVIEW

**Comment by YoungZoe** [comment]
I think the test has failed because i needed to change the name and ID of the style. Should i have submitted this as a new style rather than an edit?

**Comment by YoungZoe** [comment]
Cardiff University have changed their Harvard style so this is the old version which may still be used by some students until the end of the year. There is no longer any documentation available for it. This style also has a dependent style (Welsh version) that would need the title and id changing "Prifysgol Caerdydd - hen Harvard (Welsh)"  I was unable to change the style ID to mtach the title.

**Comment by adam3smith** [comment]
What's the new style? Are you going to make that available?
And is there any better label than "old" we could use? legacy + dater or so? Or how are folks still using this being told to look for it/call it?

**Comment by YoungZoe** [comment]
> What's the new style? Are you going to make that available?
> And is there any better label than "old" we could use? legacy + dater or so? Or how are folks still using this being told to look for it/call it?

The New style is what is currently on the system as Cardiff University BIOSI and CARBS - Harvard but the whole university has now adopted this style so it needs to be changed to Cardiff University - Harvard and i need to alter the support documentation links for it. I hadn't submitted the changes for this yet as i thought the other version would need do been done first if i was wanting to use the Cardiff University - Harvard name.  Please let me know if i should make the changes and submit the pull request for this one as well.

The old style needs to have old in the title as this is what is being used on the equivalent EndNote style and what has been told to the students and staff.

**Comment by adam3smith** [comment]
> I hadn't submitted the changes for this yet as i thought the other version would need do been done first if i was wanting to use the Cardiff University - Harvard name. Please let me know if i should make the changes and submit the pull request for this one as well

Yes, that would be great. Please do that as part of this pull request, i.e. by editing the files in the same branch (linked above)
Let me know if you need any help with that.

**Comment by adam3smith** [comment]
Ok, I think this should be all set now. Can you take a look to make sure I understood correctly what still needed to be changed?

**Comment by YoungZoe** [comment]
> Ok, I think this should be all set now. Can you take a look to make sure I understood correctly what still needed to be changed?

Yes it all looks correct. Thank you for making the changes.

**Comment by adam3smith** [comment]
Great, thanks!

**Comment by YoungZoe** [comment]
How do i ensure that this style also appears on Mendeley and any other software that uses these styles?

**Comment by adam3smith** [comment]
We'll, it's a bit complicated. The CSL styles almost everywhere come from this repository. Zotero updates their list basically immediately.
Mendeley updates the list of styles you can add and update from "More styles" quite frequently too, as far as I know.
The styles on our version of the visual CSL editor (editor.citationstyles.org) get updated much less frequently. I try for about 2-3 times a year. Mendeley's own version of the CSL editor is updated much less frequently. 
You can try nagging them about this (can't hurt). You'd ask them to update all CSL styles, not just yours (the process automatically pulls in all styles from the repository here, but involves several additional steps, which is why this doesn't happen all the time)

**Comment by YoungZoe** [comment]
Many thanks for your very helpful reply. I have now pestered Mendeley and suggested the full update to them but they wanted the direct links for the Cardiff styles as well. So it remains to be seen if they do a full update.

Thanks again
Zoe


Book a UG lunchtime drop-in        <http://www.bit.ly/bls-drop-in>              Book a staff/PG 1-2-1<http://www.bit.ly/subjectlibrarian121>
      www.bit.ly/bls-drop-in<http://www.bit.ly/bls-drop-in>                           www.bit.ly/subjectlibrarian121<http://www.bit.ly/subjectlibrarian121>

My working hours are: Monday 8-17:00, Tuesday 8-14:30, Wednesday 8-17:00, Thursday and Friday 8-14:30

Mrs Zoe Young BSc(Hons) MSc(ECON) AFHEA

Subject Librarian, Optometry and Pharmacy
Bute Library
University Library Service
Cardiff University
Bute Building
King Edward VII Avenue
Cardiff
CF10 3NB
Tel: 029 22510196
Web: www.cardiff.ac.uk<http://www.cardiff.ac.uk/>
E-mail: ***@***.******@***.***>

Registered charity: no. 1136855

Winner of THE Outstanding Library Team Award 2015

Proud to hold the Customer Service Excellence Standard®

The University welcomes correspondence in Welsh or English.

Mrs Zoe Young BSc(Hons) MSc(ECON) AFHEA

Llyfrgellydd Pwnc, Optometreg a Fferylliaeth
Llyfrgell Bute
Gwasanaeth Llyfrgell y Brifysgol
Prifysgol Caerdydd
Adeilad Bute
King Edward VII Avenue
Caerdydd
CF10 3NB
Ffôn: 029 22510196
Gwefan: www.caerdydd.ac.uk<http://www.caerdydd.ac.uk/>
E-bost: ***@***.******@***.***>

Elusen gofrestredig: rhif 1136855

Enillydd 2015 Gwobr Tîm Llyfrgell Ragorol y THE

Rydym yn falch o fod wedi ennill safon Rhagoriaeth Mewn Gwasanaethau Cwsmeriaid ®

Mae'r Brifysgol yn croesawu gohebiaeth yn Gymraeg neu'n Saesneg.

**Pull request merged**
