### PR TITLE
Create rassegna-degli-archivi-di-stato-bibliografia-generale.csl

### PR DESCRIPTION
**Pull request by Pepppino**
Style for general and reasoned bibliographies on the Rassegna degli archivi di Stato

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks (and sorry for the long wait) -- could you explain a bit more how this is different from the existing style of the same name and how it would be used?

**Comment by Pepppino** [comment]
Regarding the notes, there is no difference. This style is meant for the creation of stand-alone bibliographies, intended to be a scientific work in themselves and the _Rassegna degli Archivi di Stato_, in that case, asks for the publications to be ordered chronologically, while the bibliographies at the end of articles (covered in my other style, which has been already published) are to be ordered alphabetically by author.

**Comment by adam3smith** [comment]
(ignore the failing test)

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
