### PR TITLE
Create sodertorns-hogskola-harvard.csl

### PR DESCRIPTION
**Pull request by Ca7w3as3l**
A working draft of a Harvard citation style meeting Södertörn University's criteria.
14 Sep 2017

### CODE REVIEW

**Comment by rmzelle** [comment]
@Ca7w3as3l, will this style be used Swedish, English, or both? If the style will only be used in a single language, we'd want to fix the style to that particular locale. See also https://github.com/citation-style-language/styles/wiki/Style-Requirements#3---style-locale.

**Comment by Ca7w3as3l** [comment]
Swedish mostly but I would like to keep the option for English. Certainly not ALL languages.

**Comment by rmzelle** [comment]
> Swedish mostly but I would like to keep the option for English. Certainly not ALL languages.
> What is the next step?
> Create new pull requests with separate files for Swedish and English?

We can just accept this version, then. Reference managers such as Zotero allow you to select the desired locale (e.g. Swedish or English) to use the style with.

**Comment by Ca7w3as3l** [comment]
Super. Thanks.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
