### PR TITLE
fix MHRA author date for editors

### PR DESCRIPTION
**Pull request by adam3smith**
(plus another sheldon test, thought this one doesn't have an error.)

### CODE REVIEW

**Comment by adam3smith** [comment]
going to merge this. we can experiment on the other PR

**Comment by rmzelle** [comment]
cc @inukshuk

**Comment by inukshuk** [comment]
Hmm... it seems like something has changed either on Travis' or on GitHub's side. Shelbot received the build notification, but posting the comment did not work because the issue number was set to 0. I'll take a look at this... I may have to open a few PRs for testing, please just ignore them and I will close them myself.

**Comment by inukshuk** [comment]
I posted to the Travis CI issue tracker; the pull request number is always set to 0 for some reason so our bot does not know where to post the comments to.

https://github.com/travis-ci/travis-ci/issues/4930

**Comment by rmzelle** [comment]
Is there an easy way to see the content of the notification payloads? (just curious)

**Comment by inukshuk** [comment]
I just wrote it to the logger. You can look at it using the `heroku` CLI app.

I just disabled the output again, so as not to spam the log, but we can re-enable it if you're interested.

**Comment by rmzelle** [comment]
Okay, thanks for explaining how that works. Let's wait for the folks at Travis CI first.

**Comment by rmzelle** [comment]
(oops, I accidentally restarted the build at https://travis-ci.org/citation-style-language/styles/builds/85035796 )

**Comment by rmzelle** [comment]
@inukshuk, I tried disabling Sheldon for now via the Heroku dashboard, since the current message is a bit confusing to users.

**Comment by inukshuk** [comment]
Did it not work?

You can also just disable the notification in the repository settings here on GitHub. That's probably better (because if we disable Sheldon but leave the notifications enabled, there will be 404s).

**Comment by rmzelle** [comment]
Well, e.g. in https://github.com/citation-style-language/styles/pull/1733 the comment says "We will inform you when the test report is ready, which usually takes just a few minutes.", but because of the Travis issue you created a ticket for, we never post a followup. So we should just disable the webhook to https://shelbot.herokuapp.com/pull_request ?

**Comment by inukshuk** [comment]
Yes, exactly. If we disable the webhook, Sheldon will not post the initial comment anymore. Once we have solved the Travis issue we can re-enable it again.

**Comment by inukshuk** [comment]
Ah, and my question earlier, was whether or not disabling Sheldon on Heroku worked? Because you wrote you 'tried' to disable it.

**Comment by rmzelle** [comment]
> Ah, and my question earlier, was whether or not disabling Sheldon on Heroku worked?

I think so, but nobody created any PRs during the few minutes that I had moved the slider for the web dyno to "off".

**Pull request merged**
