### PR TITLE
Move "Harvard"/"Oxford"/"Vancouver"

### PR DESCRIPTION
**Pull request by rmzelle**
Follow-up of #2512.

### CODE REVIEW

**Comment by rmzelle** [comment]
@adam3smith, for you to merge. Just doing the titles for now should make it easy to roll things back, and minimize disruption for programs that don't use renamed-styles.json, or documentation that linked directly to styles.

**Comment by rmzelle** [comment]
There is a drawback of this, by the way, in that the focus of people who are specifically looking for a "Harvard" style will be drawn more to the remaining styles that will start with "Harvard":

Harvard Educational Review
Harvard Reference format 1 (author-date)
Harvard Reference format 7 (author-date, German)

I still think we should make the change, but it increases the importance of getting rid of the "format 1" and "format 7" titles.

**Comment by rmzelle** [comment]
> it increases the importance of getting rid of the "format 1" (...) and "format 7" (...) titles.

@adam3smith, in the xbiblio-devel discussion it seemed like the consensus was to turn the "format 1" style into a dependent, as a prelude to its eventual removal, but that hasn't happened yet. I think that would be a good change, but we might also want to change the title to indicate its deprecated status, e.g. to "(retired) Harvard Reference format 1 (replaced by "Cite Them Right 9th edition - Harvard")". Maybe we should then give Mendeley 6 months or so to prepare on their end, and remove it altogether after that point (and add it to renamed-styles.json).

Do you know if Mendeley nowadays comes with the Cite Them Right style in fresh installations? I have it in my copy of Mendeley, but I don't remember if I installed it myself at some point.

**Comment by bwiernik** [comment]
> Do you know if Mendeley nowadays comes with the Cite Them Right style in fresh installations? I have it in my copy of Mendeley, but I don't remember if I installed it myself at some point.

Yes, the default styles are:
AMA
APSA
APA
ASA
Chicago 16 (note, full note, author-date)
Harvard - Cite them Right 9
Harvard Reference format 1
IEEE
MHRA
MLA
NLM
Nature
Vancouver

**Comment by adam3smith** [comment]
Cool, thanks. As per one of the threads, I prepared a branch with Harvard1 turned into a dependent. There are currently 25 styles linking to it as a template. @rmzelle -- remind me what we do for those cases?

I also agree that we should be getting rid of it, but making it dependent on a decent style seems like a good idea anyway (and we'll need to resolve the template question either way).

**Comment by rmzelle** [comment]
> There are currently 25 styles linking to it as a template. @rmzelle -- remind me what we do for those cases?

We don't really have to enforce the current requirement that all "template" links point to existing styles, but it helps catch typos, and usually doesn't give problems. In almost all cases, I just change the "template" link to the same style you redirect the old style ID to in renamed-styles.json. Just don't think of it as purely an pointer to the originating style. It can also be a close relative that is of higher or equally high quality as the style containing the "template" link.

**Pull request merged**
