### PR TITLE
Create berghahn-books.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/70712/modifying-style-development-and-change

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle if you check here: https://www.berghahnbooks.com/authors/ they actually have a US and a UK documentation (=references) guide and both have a "Harvard" and a note option. This is the UK "Harvard" one. What do you want to do about naming?

**Comment by rmzelle** [comment]
> What do you want to do about naming?

I would use this (https://github.com/citation-style-language/styles/pull/3372/commits/86c0a519e651f54bcb384236b6378f07cc652e2d), which seems most consistent which what we've done in the past for such cases. Feel free to merge.

**Comment by POBrien333** [comment]
Are we ready to merge this one?

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
