### PR TITLE
Update university-of-tasmania-simplified-author-date.csl

### PR DESCRIPTION
**Pull request by TheLightFury**
Cleaned up the script quite a bit as the first version was very messy and obfuscated. Additionally made it a bit more useable for users outside of very academic fields. Also fixed the issue with the bibliography not sorting citations properly if the author field is blank.

### CODE REVIEW

**Comment by adam3smith** [comment]
I've started reviewing this, but there are actually a fair number of regressions in terms of CSL best practices in the style (in particular, hard-coded elements where labels, attributes, or terms should be used) -- before I go through all of them, could you walk me through the bigger picture of why this rewrite is an improvement and what you mean by "users outside of very academic fields" (presumably this is for use at an academic institution?)

**Comment by TheLightFury** [comment]
> I've started reviewing this, but there are actually a fair number of regressions in terms of CSL best practices in the style (in particular, hard-coded elements where labels, attributes, or terms should be used) -- before I go through all of them, could you walk me through the bigger picture of why this rewrite is an improvement and what you mean by "users outside of very academic fields" (presumably this is for use at an academic institution?)

Hey! This rewrite focuses a lot around the specific formatting required by my university, and trying to ensure that those requirements are met with the least amount of effort for the user. This includes specific spellings of abbreviations, certain conditional formatting depending on the kind of source being cited, etc.

And yes, this is at an academic institution, by that statement I simply meant students in courses such as fine arts which are, as far as I'm aware, a lot less focussed on academic research relative to medicine which is the field I'm in.

**Comment by adam3smith** [comment]
@TheLightFury any update on this? Would like to get it merged

**Comment by adam3smith** [comment]
I'm closing this for inactivity, but happy to reopen when you come back to it. Just post here

**Pull request closed without merging**
