### PR TITLE
Update harvard-stellenbosch-university.csl

### PR DESCRIPTION
**Pull request by Yusufras**
Change available at: to [Online], Available:

### CODE REVIEW

**Comment by Yusufras** [comment]
I edited available at: to [Online], Available:
I think something went wrong?

**Comment by rmzelle** [comment]
As specified at http://docs.citationstyles.org/en/stable/specification.html#text, `<text term="..."/>` may only use one of the predefined terms in CSL (http://docs.citationstyles.org/en/stable/specification.html#appendix-ii-terms). To print free-form text, use `<text value="..."/>`.

**Comment by rmzelle** [comment]
(you can update the current pull request via the edit icon at https://github.com/Yusufras/styles/blob/patch-8/harvard-stellenbosch-university.csl )

**Comment by rmzelle** [comment]
Actually, could you change:

```
          <group>
            <text value=" [Online], Available" suffix=": " text-case="capitalize-first"/>
            <text variable="URL"/>
          </group>
```

into

```
          <group delimiter=": ">
            <group delimiter=", ">
              <text term="online" prefix="[" suffix="]" text-case="capitalize-first"/>
              <text term="available at" text-case="capitalize-first"/>
            </group>
            <text variable="URL"/>
          </group>
```

You will need to redefine the "available at" term at the top of the style by adding `<term name="available at">available</term>` to

```
  <locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="en-GB">
    <terms>
    <term name="open-quote">“</term>
    <term name="close-quote">”</term>
    <term name="open-inner-quote">‘</term>
    <term name="close-inner-quote">’</term>
    </terms>
  </locale>
```

The benefit of all is that we try to use terms wherever possible so that our CSL styles can later be translated easily into other languages.

If you still need a space before "[Online]", it would be better to fix this wherever the "access" macro is called.

**Comment by Yusufras** [comment]
I edited the style as advised.
<group>
            <text value=" [Online], Available" suffix=": " text-case="capitalize-first"/>
            <text variable="URL"/>
          </group>
into
          <group delimiter=": ">
            <group delimiter=", ">
              <text term="online" prefix="[" suffix="]" text-case="capitalize-first"/>
              <text term="available at" text-case="capitalize-first"/>
            </group>
            <text variable="URL"/>
          </group>

I am not sure where to add the others mentioned? Do is just add it before <locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="en-GB">

You will need to redefine the "available at" term at the top of the style by adding <term name="available at">available</term> to
  <locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="en-GB">
    <terms>
    <term name="open-quote">“</term>
    <term name="close-quote">”</term>
    <term name="open-inner-quote">‘</term>
    <term name="close-inner-quote">’</term>
    </terms>
  </locale>

Also could you give more detail on the space before this[Online]. Yes i still need the space.

And also i don't want the date 10/07/2014 before the title. 
Avolio, B.J., Walumbwa, F.O. & Weber, T.J. 2009 10/07/2014. Leadership: current theories, research, and future directions. Annual review of psychology. 60:421–49. [Online], Available: http://www.ncbi.nlm.nih.gov/pubmed/18651820 [2014 , July 10].

**Comment by rmzelle** [comment]
For the translation, change

```
  <locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="en-GB">
    <terms>
    <term name="open-quote">“</term>
    <term name="close-quote">”</term>
    <term name="open-inner-quote">‘</term>
    <term name="close-inner-quote">’</term>
    </terms>
  </locale>
```

to

```
  <locale xmlns="http://purl.org/net/xbiblio/csl" xml:lang="en-GB">
    <terms>
      <term name="available at">available</term>
      <term name="open-quote">“</term>
      <term name="close-quote">”</term>
      <term name="open-inner-quote">‘</term>
      <term name="close-inner-quote">’</term>
    </terms>
  </locale>
```

As for "2009 10/07/2014", are you sure that the date in your "Date" field is correctly entered? I can't reproduce this. I also already get a space before "[Online]" as in your example above, so it looks like things are okay there. E.g. after making my change, I get:

> Henningsen, B.M., Hon, S., Covalla, S.F., Sonu, C., Argyros, D.A., Barrett, T.F., Wiswall, E., Froehlich, A.C., et al. 2015. Increasing anaerobic acetate consumption and ethanol yield in Saccharomyces cerevisiae with NADPH-specific alcohol dehydrogenase. Applied and Environmental Microbiology. 4(55):200–205. [Online], Available: http://aem.asm.org/content/early/2015/09/14/AEM.01689-15 [2015, October 20].

**Comment by rmzelle** [comment]
Great, thanks!

**Comment by Yusufras** [comment]
Thanks for all the help. Much appreciated.

Vriendelike groete / Kind regards
Yusuf Ras

Fakulteitsbibliotekaris AgriWetenskappe / Faculty Librarian AgriSciences
Biblioteek- & Inligtingsdiens / Library & Information Service
Universiteit Stellenbosch University  | map<https://www.google.co.za/maps/place/JS+Gericke+Library/@-33.932975,18.8640494,377m/data=!3m1!1e3!4m2!3m1!1s0x1dcdb25d82940c29:0x80f6dcd585958374> | Tel: +27 (021) 808 4345 | yr@sun.ac.za<mailto:yr@sun.ac.za>

**Comment by Yusufras** [comment]
I tested the style this morning, but there seemed to be no changes. Does Mendeley still need to run updates or did something go wrong?

**Comment by adam3smith** [comment]
Does it say "Update Available" next to the style? If so, I think you need to do that manually --right-click --> Update Style.

**Comment by Yusufras** [comment]
I have done that, but still no changes.

Vriendelike groete / Kind regards
Yusuf Ras

Fakulteitsbibliotekaris AgriWetenskappe / Faculty Librarian AgriSciences
Biblioteek- & Inligtingsdiens / Library & Information Service
Universiteit Stellenbosch University  | map<https://www.google.co.za/maps/place/JS+Gericke+Library/@-33.932975,18.8640494,377m/data=!3m1!1e3!4m2!3m1!1s0x1dcdb25d82940c29:0x80f6dcd585958374> | Tel: +27 (021) 808 4345 | yr@sun.ac.za<mailto:yr@sun.ac.za>

**Comment by adam3smith** [comment]
and what's the date that appears after the style now in Mendeley?

**Comment by rmzelle** [comment]
October 20th in my case.

**Comment by Yusufras** [comment]
Yes that is correct, but there still is no change

Vriendelike groete / Kind regards
Yusuf Ras

Fakulteitsbibliotekaris AgriWetenskappe / Faculty Librarian AgriSciences
Biblioteek- & Inligtingsdiens / Library & Information Service
Universiteit Stellenbosch University  | map<https://www.google.co.za/maps/place/JS+Gericke+Library/@-33.932975,18.8640494,377m/data=!3m1!1e3!4m2!3m1!1s0x1dcdb25d82940c29:0x80f6dcd585958374> | Tel: +27 (021) 808 4345 | yr@sun.ac.za<mailto:yr@sun.ac.za>

**Comment by adam3smith** [comment]
Mendeley has special settings on when to show URLs and access dates under View-->Citation Styles.

**Comment by Yusufras** [comment]
I edited a Harvard style adding this:
<macro name="access">
    <choose>
      <if variable="URL">
        <text value="[Online], Available:" suffix=" "/>
        <text variable="URL"/>
        <group prefix=" [" suffix="]">
          <text term="accessed" text-case="capitalize-first" suffix=" "/>
          <date form="text" variable="accessed">
            <date-part name="year" suffix=","/>
            <date-part name="month"/>
            <date-part name="day" form="numeric-leading-zeros"/>
          </date>
        </group>
      </if>
    </choose>
  </macro>

Which resulted in this:
(Avolio, Walumbwa & Weber, 2009)
Avolio, B.J., Walumbwa, F.O. & Weber, T.J. 2009 10/07/2014. Leadership: current theories, research, and future directions. Annual review of psychology. 60:421–49. [Online], Available: http://www.ncbi.nlm.nih.gov/pubmed/18651820 [2014 , July 10].

I don’t get this with the updated Harvard Stellenbosch we managed to edit? My settings on Mendeley is still the same.

Vriendelike groete / Kind regards
Yusuf Ras

Fakulteitsbibliotekaris AgriWetenskappe / Faculty Librarian AgriSciences
Biblioteek- & Inligtingsdiens / Library & Information Service
Universiteit Stellenbosch University  | map<https://www.google.co.za/maps/place/JS+Gericke+Library/@-33.932975,18.8640494,377m/data=!3m1!1e3!4m2!3m1!1s0x1dcdb25d82940c29:0x80f6dcd585958374> | Tel: +27 (021) 808 4345 | yr@sun.ac.za<mailto:yr@sun.ac.za>

**Pull request merged**
