### PR TITLE
Update universite-cheikh-anta-diop-faculte-de-medecine-de-pharmacie-e…

### PR DESCRIPTION
**Pull request by drgomis**
…t-dodontologie.csl

Changement about 
- "." after "vol"
- "." after "edition"
- how to write the edition number as a cardinal number as a superscript

### CODE REVIEW

**Comment by drgomis** [comment]
@adam3smith ???

**Comment by adam3smith** [comment]
We work through these fast as we can, but can easily take two weeks.

**Comment by adam3smith** [comment]
As for the question:

> how to write the edition number as a cardinal number as a superscript

You can just do something like
`<number variable="edition" form="numeric" vertical-align="sup"/>`

**Comment by drgomis** [comment]
> We work through these fast as we can, but can easily take two weeks.


Thank you. I understand.

**Comment by drgomis** [comment]
> As for the question:
> 
> 
> 
> > how to write the edition number as a cardinal number as a superscript
> 
> 
> 
> You can just do something like
> 
> `<number variable="edition" form="numeric" vertical-align="sup"/>`

It's not a question. Sorry !
I just wanted to explain that i changed the form of writing the edition number.

Sorry again. English is not my native language.

**Pull request merged**
