### PR TITLE
Create griffith-college-harvard.csl

### PR DESCRIPTION
**Pull request by deanwatters**
Changes made to films/tv broadcasts.
Changes from sentence case to title case.

### CODE REVIEW

**Comment by deanwatters** [comment]
<link href="http://www.https://www.citethemrightonline.com/" rel="documentation"/> corrected to <link href="https://www.citethemrightonline.com/" rel="documentation"/>

**Comment by adam3smith** [comment]
Could you say more about this style? -- does Griffith follow Cite Them Right? (If so, why the changes)? Does it use a slight variation of CTR? (If so, is that documented somewhere)?

**Comment by deanwatters** [comment]
Hey

Major difference is preference for title case over sentence case, which CTR
doesn't follow. Also the .csl for CTR isn't correct when citing a motion
picture: motion picture should be cited as Title (Year) Directed by...
[Film] Distribution Company. The current .csl available doesn't follow this
style. Also, there is no presence of "medium" variable in the CTR .csl. For
example, photographs do not have the medium variable present "[Photograph]".

Here's the documentation that follows the proposed .csl

all the best
Dean

**Comment by adam3smith** [comment]
>  Here's the documentation that follows the proposed .csl

That didn't make it. Note that e-mail attachments don't work.  You need to upload attachments on github.

We'd like the improvements for motion pictures and artwork for CTR as a pull request if at all possible.

**Comment by deanwatters** [comment]
Hi, sorry. 
[FinalDoc (1).pdf](https://github.com/citation-style-language/styles/files/3034674/FinalDoc.1.pdf)

Does this work?

That's not possible, the code has been patched together and I'm not sure how to make those improvements for CTR. Sorry about that.

Dean.

**Comment by deanwatters** [comment]
Hi, any updates on this?

**Comment by rmzelle** [comment]
Thanks!

**Comment by deanwatters** [comment]
Great! Thanks for your help guys.

Dean

**Pull request merged**
