### PR TITLE
Create north-pacific-anadromous-fish-commission-bulletin.csl

### PR DESCRIPTION
**Pull request by Br-Johnson**
Here is .csl file for the North Pacific Anadromous Fish Commission's bespoke citation style. 

I only have a word doc that indicates the citation style, and as far as I can tell it's not available on their website. So I will paste it here below:

References in Text
 For one author: Suzuki (1980), or (Suzuki 1980), no comma between name and year.
 For two authors: Suzuki and Yamada (1980), or (Suzuki and Yamada 1980).
 For more than two authors: Suzuki et al. (1980), or (Suzuki et al. 1980), “et al.” is used with a
period, not italicized and not underlined.
 For two or more references given together: Smith (1980, 1981), Suzuki and Yamada (1983), and
Smith (1984), or (Smith 1980, 1981; Suzuki and Yamada 1983; Smith 1984). Note: references are
listed first in order of publication date, then alphabetically by author.
 Same author(s), same date (incl. in press): add “a”, “b”, … after the date, e.g., (1999a, b, c; in
press b). Please note the space or lack thereof.
 In press: Suzuki (in press), or (Suzuki in press). The publication must be accepted for publication,
preferably at the galley stage; if this is not the case, cite as unpublished data or personal
communication.
 This volume: same format as for “In press”, e.g., Suzuki (this volume), or (Suzuki this volume).
 Unpublished data by an author: where the author(s) needs (need) to be identified; e.g., (Smith
unpublished data; Beacham et al. unpublished data).
 Unpublished information from a colleague: first initial and name of the colleague, e-mail address,
and pers. comm., all in parentheses, i.e., (J. Smith, smithj@......, pers. comm.).
 Edited book: (Gordon and Hourston 1993) no need to put “[ed.]” in the text.
 Corporate author: full spelling of the name of the company (with the acronym in parentheses) at
the first appearance and thereafter that only the acronym should be used, e.g., (American Public
Health Association (APHA), American Water Works Association, and Water Pollution Control
Federation 1975).

References in the Reference List
 References should be listed in alphabetical order according to the surname of the first author.
 References with the same first author are listed in the following order.
(1) First: papers with one author are listed in chronological order.
(2) Second: papers with two authors are listed in alphabetical order by the last name of the
second author and then in chronological order.
(3) Third: papers with three or more authors are listed in chronological order.

 The objective of consistent format is to ensure that all necessary information for retrieving a work is
provided as succinctly as possible. In a particular instance if modification of the format would
facilitate retrieval, e.g., by addition of a date, or page numbers, or other specifics, modification is
approved.
 Indent after the 1 st line of the reference by a ½ inch as demonstrated in the following examples.
 In the reference list, the first author is shown surname first, followed by their initials. The following
authors in the citation are shown with initials first, then surname (see examples below).
 Follow the spacing convention between words as illustrated in the following references: double space
after last author, year, and article title; single space after journal title and volume number. Use the
en-dash to show the range in page numbers.

### CODE REVIEW

**Comment by adam3smith** [comment]
Afaict, journal articles should be abbreviated and there should be a comma before the last author in the bibliography. Looks good otherwise.

**Comment by Br-Johnson** [comment]
Thanks for those comments and checks @adam3smith I'm happy with this now and would love if this could be merged into production. Thanks.

**Comment by adam3smith** [comment]
You're still not using form="short" on the journal title -- is that on purpose?

**Comment by Br-Johnson** [comment]
@adam3smith Thanks for that. I have changed the journal title to short. I think this should be good to go now!

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
