### PR TITLE
Create associacao-brasileira-de-normas-tecnicas-imm.csl

### PR DESCRIPTION
**Pull request by MarceloMalagutti**
ABNT-Instituto Meira Mattos-PPGCM (Post Graduation Studies in Military Sciences)
Although based on the similar associacao-brasileira-de-normas-tecnicas-eceme.csl style, there are important differences regarding author connectors and title and container bold/italic presentation. Thus, it is necessary to create a different style.

### CODE REVIEW

**Comment by rmzelle** [comment]
@MarceloMalagutti, thanks. Just so we name this correctly, is this style specific to the PPGCM, or to the entire IMM?

**Comment by MarceloMalagutti** [comment]
Hi,
It is for the entire IMM.
Thanks,
Marcelo MalaguttiDoutorando/PhD ResearcherECEME/Inst. Meira Mattos

-------- Mensagem original --------
De : "Rintze M. Zelle" <notifications@github.com> 
Data: 23/06/17  20:46  (GMT-03:00) 
Para: citation-style-language/styles <styles@noreply.github.com> 
Cc: MarceloMalagutti <marcelomalagutti@yahoo.com.br>, Mention <mention@noreply.github.com> 
Assunto: Re: [citation-style-language/styles] Create
  associacao-brasileira-de-normas-tecnicas-imm.csl (#2765) 

@MarceloMalagutti, thanks. Just so we name this correctly, is this style specific to the PPGCM, or to the entire IMM?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/citation-style-language/styles","title":"citation-style-language/styles","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/citation-style-language/styles"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rmzelle in #2765: @MarceloMalagutti, thanks. Just so we name this correctly, is this style specific to the PPGCM, or to the entire IMM?"}],"action":{"name":"View Pull Request","url":"https://github.com/citation-style-language/styles/pull/2765#issuecomment-310796186"}}}

**Comment by rmzelle** [comment]
Thanks. One more question: is there a web page that describes this citation format, or, if that doesn't exist, an official website for the IMM?

**Comment by MarceloMalagutti** [comment]
Hi Rintze,
The website of the Institute (IMM) is http://www.eceme.eb.mil.br/instituto-meira-mattos-imm.Regarding the referencing style there is the attached manual (unfortunately only in Brazilian Portuguese). I suppose I will still have to make some minor adjustments, but for now the major differences have already been corrected. 
Best regards, Marcelo MalaguttiDoutorando/Ph.D. CandidateECEME/Inst. Meira Mattos


      De: Rintze M. Zelle <notifications@github.com>
 Para: citation-style-language/styles <styles@noreply.github.com> 
Cc: MarceloMalagutti <marcelomalagutti@yahoo.com.br>; Mention <mention@noreply.github.com>
 Enviadas: Sábado, 24 de Junho de 2017 13:18
 Assunto: Re: [citation-style-language/styles] Create associacao-brasileira-de-normas-tecnicas-imm.csl (#2765)
  
Thanks. One more question: is there a web page that describes this citation format, or, if that doesn't exist, an official website for the IMM?—

**Comment by rmzelle** [comment]
Great, thanks. So, if I understand it correctly, the IMM is part of the ECEME, correct?

Also, could you attach the manual via the GitHub website, instead of as an email attachment? The latter don't work. See https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

(finally, http://www.eceme.eb.mil.br/ doesn't load for me from the US. The website works for you? http://downforeveryoneorjustme.com/http://www.eceme.eb.mil.br/ also says it's down, so it's not just me)

**Comment by MarceloMalagutti** [comment]
Hi Rintze,
Just clicking in the ECEME link below it is working. At least here in Rio de Janeiro. I can't imagine the reason why it doesn't work for you and 'downforeveryoneorjustme'. Cordialmente, Marcelo MalaguttiDoutorando/Ph.D. CandidateECEME/Inst. Meira Mattos


      De: Rintze M. Zelle <notifications@github.com>
 Para: citation-style-language/styles <styles@noreply.github.com> 
Cc: MarceloMalagutti <marcelomalagutti@yahoo.com.br>; Mention <mention@noreply.github.com>
 Enviadas: Domingo, 25 de Junho de 2017 0:30
 Assunto: Re: [citation-style-language/styles] Create associacao-brasileira-de-normas-tecnicas-imm.csl (#2765)
   
Great, thanks. So, if I understand it correctly, the IMM is part of the ECEME, correct?Also, could you attach the manual via the GitHub website, instead of as an email attachment? The latter don't work. See https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/(finally, http://www.eceme.eb.mil.br/ doesn't load for me from the US. The website works for you? http://downforeveryoneorjustme.com/http://www.eceme.eb.mil.br/ also says it's down, so it's not just me)—

**Comment by MarceloMalagutti** [comment]
Follow Instituto Meira Mattos' style manual (in Brazilian Portuguese).
[ME 21-253 - 2017.pdf](https://github.com/citation-style-language/styles/files/1100329/ME.21-253.-.2017.pdf)

**Comment by rmzelle** [comment]
Great, thanks!

**Comment by rmzelle** [comment]
(@adam3smith, if it's okay with you, I'm thinking that we might want to do the same thing for the ABNT derivates as what we did with the universities' APA and Harvard variants. I.e., rename e.g. "Associação Brasileira de Normas Técnicas - Faculdade de Medicina Veterinária e Zootecnia - USP (Portuguese - Brazil)" to "Faculdade de Medicina Veterinária e Zootecnia - USP - ABNT (Portuguese - Brazil)". See also https://www.zotero.org/styles?q=associacao-b and https://www.zotero.org/styles?q=-%20apa.

All these ABNT titles are currently extremely long, and might not display the full title in style selectors like those of Zotero/Mendeley.)

**Comment by adam3smith** [comment]
Yes, makes perfect sense to me -- we'll still have the to versions not associated with a specific department/university

**Comment by MarceloMalagutti** [comment]
Hi Rintze,
I think it is a great idea, but usingABNT-USPABNT-UFMGand so on, since the general standard is national, and specifications come from different institutions.
Best regards,
Marcelo MalaguttiDoutorando/PhD ResearcherECEME/Inst. Meira Mattos

-------- Mensagem original --------
De : "Rintze M. Zelle" <notifications@github.com> 
Data: 25/06/17  11:08  (GMT-03:00) 
Para: citation-style-language/styles <styles@noreply.github.com> 
Cc: MarceloMalagutti <marcelomalagutti@yahoo.com.br>, Mention <mention@noreply.github.com> 
Assunto: Re: [citation-style-language/styles] Create
  associacao-brasileira-de-normas-tecnicas-imm.csl (#2765) 

(@adam3smith, if it's okay with you, I'm thinking that we might want to do the same thing for the ABNT derivates as what we did with the universities' APA and Harvard variants. I.e., rename e.g. "Associação Brasileira de Normas Técnicas - Faculdade de Medicina Veterinária e Zootecnia - USP (Portuguese - Brazil)" to "Faculdade de Medicina Veterinária e Zootecnia - USP - ABNT (Portuguese - Brazil)". See also https://www.zotero.org/styles?q=associacao-b and https://www.zotero.org/styles?q=-%20apa.
All these ABNT titles are currently extremely long, and might not display the full title in style selectors like those of Zotero/Mendeley.)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/citation-style-language/styles","title":"citation-style-language/styles","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/citation-style-language/styles"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rmzelle in #2765: (@adam3smith, if it's okay with you, I'm thinking that we might want to do the same thing for the ABNT derivates as what we did with the universities' APA and Harvard variants. I.e., rename e.g. \"Associação Brasileira de Normas Técnicas - Faculdade de Medicina Veterinária e Zootecnia - USP (Portuguese - Brazil)\" to \"Faculdade de Medicina Veterinária e Zootecnia - USP - ABNT (Portuguese - Brazil)\". See also https://www.zotero.org/styles?q=associacao-b and https://www.zotero.org/styles?q=-%20apa.\r\n\r\nAll these ABNT titles are currently extremely long, and might not display the full title in style selectors like those of Zotero/Mendeley.) \r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/citation-style-language/styles/pull/2765#issuecomment-310904697"}}}

**Comment by rmzelle** [comment]
@MarceloMalagutti, there are some advantages and disadvantage to either order, but it would be most consistent for our repository to put "ABNT" last. That's especially useful when a given institution uses multiple styles (in which they show up next to each other alphabetically in the style list). And users should still be able to locate all ABNT styles by searching for "ABNT" (https://www.zotero.org/styles?q=abnt).

**Comment by rmzelle** [comment]
(we recently changed this for e.g. all the "Harvard" and "APA" variants: https://www.zotero.org/styles?q=-%20harvard and https://www.zotero.org/styles?q=-%20apa)

**Comment by MarceloMalagutti** [comment]
Dear Rintze,
Your proposal is fine for me.
Best wishes,
Marcelo MalaguttiDoutorando/PhD ResearcherECEME/Inst. Meira Mattos

-------- Mensagem original --------
De : "Rintze M. Zelle" <notifications@github.com> 
Data: 25/06/17  14:36  (GMT-03:00) 
Para: citation-style-language/styles <styles@noreply.github.com> 
Cc: MarceloMalagutti <marcelomalagutti@yahoo.com.br>, Mention <mention@noreply.github.com> 
Assunto: Re: [citation-style-language/styles] Create
  associacao-brasileira-de-normas-tecnicas-imm.csl (#2765) 

@MarceloMalagutti, there are some advantages and disadvantage to either order, but it would be most consistent for our repository to put "ABNT" last. That's especially useful when a given institution uses multiple styles (in which they show up next to each other alphabetically in the style list). And users should still be able to locate all ABNT styles by searching for "ABNT" (https://www.zotero.org/styles?q=abnt).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/citation-style-language/styles","title":"citation-style-language/styles","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/citation-style-language/styles"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rmzelle in #2765: @MarceloMalagutti, there are some advantages and disadvantage to either order, but it would be most consistent for our repository to put \"ABNT\" last. That's especially useful when a given institution uses multiple styles (in which they show up next to each other alphabetically in the style list). And users should still be able to locate all ABNT styles by searching for \"ABNT\" (https://www.zotero.org/styles?q=abnt)."}],"action":{"name":"View Pull Request","url":"https://github.com/citation-style-language/styles/pull/2765#issuecomment-310916550"}}}

**Comment by rmzelle** [comment]
Done, in https://github.com/citation-style-language/styles/commit/44808db510152943c5d9dc471a9c8982a3edfbea.

**Pull request merged**
