### PR TITLE
 APA: use "et al." in Norwegian nn and nb

### PR DESCRIPTION
**Pull request by kjtlslt**
Similar to German and Danish in #4066.

### CODE REVIEW

**Comment by adam3smith** [comment]
Is there any documentation for APA in Norwegian this is based on? We did have this for German and Danish.

**Comment by kjtlslt** [comment]
There is. We have made [an attempt to standardise a Norwegian translation/adaptation of the APA referencing style](https://www.unit.no/tjenester/norsk-apa-referansestil), as various university web sites had somewhat different interpretations, leading to confusion. This standard is backed by [Søk og Skriv](https://www.sokogskriv.no), a collaboration between the libraries of UiO, UiB and HVL, [Kildekompasset](https://www.kildekompasset.no), a collaboration of USN, UiS and UiA, [VIKO](https://www.ntnu.no/viko/) (NTNU), OsloMet, INN and UiT. (That's an awful lot of institutions, but not so many people.)

**Comment by adam3smith** [comment]
That's terrific. We'd love the CSL APA to be listed on the style's page if that's possible.

**Comment by kjtlslt** [comment]
I think we'll do that.

But is it possible to turn off the serial (Oxford) comma for one language? The serial comma doesn't work in Norwegian (and probably not in Danish either), at least not in in-text citations.

**Comment by adam3smith** [comment]
<blockquote>But is it possible to turn off the serial (Oxford) comma for one language? The serial comma doesn't work in Norwegian (and probably not in Danish either), at least not in in-text citations.</blockquote>
No, not currently. @rmzelle -- I thought we had a ticket for this (not the first time this comes up) but can only find `&` vs. `and`

**Pull request merged**
