### PR TITLE
Fixed one last missed attribute double-space in harvard-leeds-beckett-university.csl

### PR DESCRIPTION
**Pull request by joejoinerr**

### CODE REVIEW

**Comment by adam3smith** [comment]
thanks (btw. all implementations handle the update times themselves. There's no need to manually adjust that, though obviously it also doesn't hurt).

**Comment by joejoinerr** [comment]
The more you know :)

**Comment by rmzelle** [comment]
Actually, nowadays we have https://github.com/citation-style-language/styles-distribution, which mirrors this repository. It only gets updated when the Travis CI build passes, and only creates one commit per pull request (for this one, the changes are represented in https://github.com/citation-style-language/styles-distribution/commit/5fc46ffa69743b8e5d602cd68eca06090017809e ).

And when it updates, the style's time stamp is automatically updated as well!

**Comment by joejoinerr** [comment]
@rmzelle Good to know for future reference, thanks.

**Pull request merged**
