### PR TITLE
Create universite-de-geneve-departement-de-francais-moderne.csl

### PR DESCRIPTION
**Pull request by Benjamin-Paul**
Hello !

I would like to submit this new CSL style for Zotero to the repository. It matches the official citation norms used by the departement of french litterature from the University of Geneva (UNIGE), in Switzerland.  The documentation can be found here : https://www.unige.ch/lettres/framo/files/5615/8799/0756/normes_redactionnelles_FRAMO.pdf 
...and I'm currently working on a written tutorial, but I cannot complete it without uploading the style first, since I would like to link the style in it. I plan on modifying the CSL file once the tutorial is online. 
Thank you very much for your consideration. 
All the best,
Benjamin PAUL (University of Geneva)

### CODE REVIEW

**Review by adam3smith — CHANGES_REQUESTED** [review]
Thanks! Some remaining change requests & questions. Most of the comments apply in multiple places throughout the style, not just where I flagged the issue.

**Comment by adam3smith** [comment]
@Benjamin-Paul -- just a reminder to please check on the questions and issues flagged above, thanks!

**Comment by Benjamin-Paul** [comment]
> @Benjamin-Paul -- just a reminder to please check on the questions and issues flagged above, thanks!

Hey @adam3smith, I actually did a few weeks ago, but not on this "branch" (I'm new to github and I don't understand it fully yet...). 

Since I actually changed a lot of the code following your advices, I uploaded it as a whole on a separate branch. Can you find it ? If not, I can try to change this branch, but I think it would be confusing... 

Sorry for my ignorance !

**Comment by Benjamin-Paul** [comment]
(The new branch is called "Benjamin-Paul-patch-2" and I asked for it to be "merged" with this one)

**Comment by rmzelle** [comment]
> Hey @adam3smith, I actually did a few weeks ago, but not on this "branch" (I'm new to github and I don't understand it fully yet...).
> 
> Since I actually changed a lot of the code following your advices, I uploaded it as a whole on a separate branch. Can you find it ? If not, I can try to change this branch, but I think it would be confusing...

@Benjamin-Paul, if you follow my instructions in my comment on your other pull request, this pull request should get updated with your original corrections automatically.

For the future, you can update existing pull requests by going to the "Files changed" tab, clicking the ellipsis button at the top-right of the file of interest, and selecting "Edit file" (and then committing any changes you make). You can also make changes directly in the origin branch used to create the pull request ("patch-2" in your forked repository, in this case).

If you look at https://github.com/Benjamin-Paul/styles/pull/1, you can see that you created a second pull request to merge changes from your "Benjamin-Paul-patch-1" branch into your "patch-2" branch. That's a perfectly valid approach too, but since it's a pull request within your forked repository we can't merge that one for you.

**Comment by Benjamin-Paul** [comment]
@rmzelle Thank you very much for your instructions ! I did what you suggested, I hope it worked ! Is there anything else I need to do for now ?

Thanks again to both of you, and sorry for the inconvenience - I shall now be on my way to go check out some GitHub tutorials ;-)

**Comment by rmzelle** [comment]
@adam3smith, good to merge from my side.

**Comment by adam3smith** [comment]
Great, thanks!

**Pull request merged**
