### PR TITLE
Update and rename journal-of-neurosurgery.csl to dependent/journal-of… (make AMA dependent)

### PR DESCRIPTION
**Pull request by POBrien333**
…-neurosurgery.csl

via https://forums.zotero.org/discussion/88712/journal-of-neurosurgery-style#latest

### CODE REVIEW

**Comment by POBrien333** [comment]
Not sure what the error is. Help welcome. :)

**Comment by adam3smith** [comment]
You're removing a style (or rather, turning it into a dependent style) on which a bunch of other styles either depend or point as template

**Comment by POBrien333** [comment]
Alright. I´ll check those then and see what I can do.

**Comment by POBrien333** [comment]
@adam3smith 
Thank you. This should be fine now. Those 3 journals are just JNS sister journals.

**Comment by rmzelle** [comment]
@POBrien333, thanks!

**Pull request merged**
