### PR TITLE
Create mimesis-edizioni.csl

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/67650/style-request-italian-unknown

Not ready.

### CODE REVIEW

**Comment by rmzelle** [comment]
Not 100% sure, but mimesis-edizioni.csl seems like a more accurate name than mimesis.csl. Also (hopefully) corrected the template link based on your first commit.

**Comment by adam3smith** [comment]
> mimesis-edizioni.csl seems like a more accurate name than mimesis.csl

+1

**Comment by rmzelle** [comment]
@POBrien333, ready?

**Comment by POBrien333** [comment]
Yes :)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
