### PR TITLE
Create chicago-17-fullnote-bibliography.csl

### PR DESCRIPTION
**Pull request by Elbar914**
CSL to accommodate specifications in 17th edition of Chicago Manual of Style.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks for these -- you don't happen to have a list of changes you implemented versus the 16th edition, do you? I'll look at a diff otherwise, but I figured I'd ask.

**Comment by Elbar914** [comment]
@adam3smith I don't have a list handy of exactly what was changed within the CSLs (changing variables, etc.) but the changes all had to do with the following updates to the style:

The changes I made to chicago-17-fullnote-bibliography had to do with: 
- Titles of websites that have a print counterpart should be in italics, while ones that are standalone resources should not.
- The use of "ibid" is no longer needed when repeating footnote citations. Instead, repeating the author's name and including the applicable page number if available is preferred.

For chicago-17-author-date:
- In an author-date reference list entry, the year may be repeated for sources that are also identified by month and day, such as journals.

**Comment by adam3smith** [comment]
Thanks! I'll spend some time on this over the weekend to review and see exactly how we want to organize the 16-->17 edition transition.
@rmzelle What do you want to do about transitioning all the Chicago styles to 17th edition? I'm not too happy with the thought of having all the different copies of CMoS for both editions, but unclear what else we could do. Overall the changes are fairly small, but there are some other ones (e.g. proper DOI format)

**Comment by Elbar914** [comment]
Great, thanks!

**Comment by rmzelle** [comment]
> What do you want to do about transitioning all the Chicago styles to 17th edition? I'm not too happy with the thought of having all the different copies of CMoS for both editions, but unclear what else we could do.

Looks like the 17th edition was released earlier this month (https://www.amazon.com/Chicago-Manual-Style-17th/dp/022628705X lists September 5, 2017 for the print edition), so we probably shouldn't wait to long to update the CSL styles.

I think we should update all variants in-place to the 17th edition, and maybe just create 16th edition styles for the most popular variants (https://github.com/zotero/bundled-styles has chicago-author-date.csl, chicago-fullnote-bibliography.csl, and chicago-note-bibliography.csl; somebody recently mentioned what Mendeley styles are included by default (maybe on the Zotero forums? Can't remember), but https://blogs.cranfield.ac.uk/is/cranfield-harvard-mendeley and https://github.com/citation-style-language/styles/issues/1720#issuecomment-261983934 suggests Mendeley ships chicago-author-date.csl and that chicago-fullnote-bibliography is quite popular, so I'd just do those three).

**Comment by adam3smith** [comment]
That sounds good -- I'll turn that into a pull request, hopefully over the weekend.

**Comment by adam3smith** [comment]
supserseded by https://github.com/citation-style-language/styles/pull/3021

**Pull request closed without merging**
