### PR TITLE
Create bfi-wien-mba-dt-note-german

### PR DESCRIPTION
**Pull request by stereokitchen**
Created a new CSL to accommodate the requirements from my University. Thank you.

### CODE REVIEW

**Comment by bwiernik** [comment]
Can you change the file name and style Title to spell out the words, at least the university name? Right now what style this is is very opaque. The current title can move to title-short.

**Comment by stereokitchen** [comment]
File has been updated as suggested. Thank you!

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

And can you make this pull request editable for us? There should be a checkbox near the bottom of the right-hand column on this page that looks like this:

image

**Comment by rmzelle** [comment]
Hi, we're closing this issue because we haven't heard from you in a while. Note that we can always reopen this issue if you get back to us.

**Pull request closed without merging**
