### PR TITLE
Update ieee.csl to incl. video directors | add standard type

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/113145/ieee-online-video-e-g-youtube#latest

I feel like we should include some other names as well. Any suggestions which?

-----
Also adds the "standard" type to style:
image

image
Requested here: https://forums.zotero.org/discussion/115455/zotero-not-compliant-with-the-ieee-style-guide/p1

### CODE REVIEW

**Comment by zepinglee** [comment]
I've collected all the sample entries of the IEEE manual into Zotero format (via <https://anystyle.io/>) and they may help testing CSL styles: <https://gist.github.com/zepinglee/f35d04cbbc240ad0de21de79818761cf>.

**Comment by bwiernik** [comment]
@POBrien333 Should we go ahead and merge this now and can add more in a future PR?

**Comment by POBrien333** [comment]
Yeah, I'd say so. Let's get that out to the users. :)

**Comment by POBrien333** [comment]
Is the type "preprint" not a valid item type (yet)?

**Comment by bwiernik** [comment]
Preprint is type "article"

**Pull request merged**
