### PR TITLE
Create estudios-de-asia-y-africa.csl

### PR DESCRIPTION
**Pull request by POBrien333**
Journal says it uses CMOS and then changes everything. Very funny.

Via https://forums.zotero.org/discussion/85049/add-p-or-pp-in-in-text-citation#latest

### CODE REVIEW

**Comment by rmzelle** [comment]
https://estudiosdeasiayafrica.colmex.mx/index.php/eaa/announcement

> Beginning in January 2021, Estudios de Asia y África shifts to Chicago (author-date style) referencing system.

@POBrien333, since this is such a recent change, are you sure that your version represents their new format instead of the old one? Maybe they'll switch to proper CMoS on January 31st :D.

**Comment by adam3smith** [comment]
I think Rintze may be right, check the most recent issue, e.g. https://estudiosdeasiayafrica.colmex.mx/index.php/eaa/article/view/2543/2600 -- that looks pretty much like Chicago Manual; certainly different from the style you have now.

**Comment by adam3smith** [comment]
@POBrien333 sorry about that -- I know that's super frustrating.

**Comment by POBrien333** [comment]
Ah, it's alright. Not the first time, not the last time. :)

**Pull request closed without merging**
