### PR TITLE
BES journals now all use (old-DOI format) APA

### PR DESCRIPTION
**Pull request by adam3smith**
See also https://github.com/citation-style-language/journals/commit/e089bb9ee97712ed6a2e1db4cf024c2e5e1c696b

### CODE REVIEW

**Comment by rmzelle** [comment]
(added a link to the matching "journals" repo commit in your opening post)

How did you find out this was the case? And are you sure the locale should be "en-US", not "en-GB"? Otherwise looks good to merge.

**Comment by adam3smith** [comment]
I got an error report from Mendeley about the BES style, then started looking at them in detail. en-US vs. GB doesn't make a difference with APA styles, but I figured since they use APA, en-US made sense.

**Comment by rmzelle** [comment]
Okay, thanks! Just trying to make sure we have a record.

**Comment by rmzelle** [comment]
Could you add the dependents for "Journal of Applied Ecology" and "Methods in Ecology and Evolution"? I think you just missed them (they generate correctly from the "journals" metadata for BES).

**Comment by rmzelle** [comment]
Just realized you did this in a repository branch I can commit to myself (duh), so easy to fix myself. Thanks!

**Pull request merged**
