### PR TITLE
Create cambridge-university-press-law-note.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/comment/298174/#Comment_298174

Also see https://github.com/citation-style-language/styles/pull/3254 for generic CUP Note style.

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, do you have a good understanding of where the guidelines for these two note styles are stored? In https://forums.zotero.org/discussion/comment/298174/#Comment_298174, the requestor links to https://authornet.cambridge.org/information/academic/downloads/General%20style%20guidelines.pdf, but I don't see a link to that file at https://authornet.cambridge.org/information/academic/guidelines_for_authors.asp.

In https://github.com/citation-style-language/styles/blob/master/cambridge-university-press-note.csl I included a documentation link to https://authornet.cambridge.org/information/academic/downloads/Style%20Guide.pdf, but I'm not a 100% sure that's the right file.

(looks like CUP needs to consolidate their style format documentation a bit)

**Comment by POBrien333** [comment]
@rmzelle 
yeah, I haven't figured that one out either. But the requestor seemed to know what he was talking about, so I trusted him in that regard.
He also reported back now that everything fits the style as necessary.

**Comment by adam3smith** [comment]
I think it makes sense to take this. I've added the one additional link as documentation. Thanks!

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
