### PR TITLE
Create citation-compass-apa-note-no.csl

### PR DESCRIPTION
**Pull request by haarbakke**
This is a Norwegian version of Citation Compass (Kildekompasset) - APA (note) where comma before & has been removed, changes made to lines 4, 5, and 6 adjust as appropriate.
The comma has been removed before & by changing delimiter-precedes-last="never" in lines 65, 70, 94, 98, and 102.
Also in line 1208 delimiter-precedes-last="never" has been added.

### CODE REVIEW

**Comment by adam3smith** [comment]
Can the other Citation Compass style then be set to default to English? And how about this one -- because there are two Norwegian locales, we can't set a language default?

**Comment by haarbakke** [comment]
We could probably choose Norsk bokmål which is used by the majority of Norwegian language users, but I should probably check the locales files that applies to styles and see if there are any differences. If not it doesn't matter which Norwegian locale is used. Can you give me a link to where I can find the necessary files?

**Review by haarbakke — COMMENTED** [review]
I have updated the default locale to nb-NO which is the locale that the majority of Norwegian Zotero users will use. Just for the record, default locale does not mean that it is not possible to change the locale to e.g. Norsk nynorsk or Danish?

Secondly, I am OK with setting a default locale to English for the original Citation Compass style if that is OK for all the others.

**Review by haarbakke — COMMENTED** [review]
Fixed an error committed in patch 2

**Comment by haarbakke** [comment]
Fixed an error in patch-2

**Comment by adam3smith** [comment]
> I have updated the default locale to nb-NO which is the locale that the majority of Norwegian Zotero users will use. Just for the record, default locale does not mean that it is not possible to change the locale to e.g. Norsk nynorsk or Danish?

It depends on the software, but in Zotero the default locale fixes the style to that language and can't be changed and I think that was our original vision, so if that doesn't work, we'd probably want to keep it language-neutral

**Comment by haarbakke** [comment]
OK, I will update the csl file to be language neutral and let the name be "Citation Compass (Kildekompasset) - APA (note) Norwegian" if that is OK.

**Comment by haarbakke** [comment]
@adam3smith thoughts on what to do next?

**Comment by bwiernik** [comment]
We would probably want to name this style Norsk APA-Manual (note) to follow the other style from Citation Compass?

**Comment by haarbakke** [comment]
That is OK for me. I made an attempt to rename earlier, but that attempt failed. Would you mind renaming the style or guide me how to do it?

**Pull request merged**
