### PR TITLE
Update global-change-biology.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/71486/global-change-biology

No guidelines available. Papers available here: https://onlinelibrary.wiley.com/toc/13652486/current

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks!

(I assume this can't be made a dependent of APA, as suggested by the OP?)

**Comment by POBrien333** [comment]
@rmzelle 
The OP in the thread only answered after me making the edit (and then I was sleeping). 
Want me to make it a dependent?

**Comment by rmzelle** [comment]
If you have a chance to confirm that the journal really uses APA, yes, please.

**Comment by POBrien333** [comment]
Confirmed that it's just APA: https://github.com/citation-style-language/styles/pull/3468

**Pull request merged**
