### PR TITLE
Astrophysical Journal Fix

### PR DESCRIPTION
**Pull request by adam3smith**
Putting one mistake in here on purpose to check on shelbot

### CODE REVIEW

**Comment by adam3smith** [comment]
Hmm -- apart from the hot mess I created. No shelbot in sight. leaving this up for @inukshuk

**Comment by adam3smith** [comment]
Never mind -- now he showed up. There should be another one after failed check though, right?

**Comment by inukshuk** [comment]
Yes, the PR responder worked (that one is triggered from GitHub), but the build responder did not (triggered from Travis), because it only accepts notifications signed by my Travis CI token. We need to use the token of whoever set up the styles repo on Travis. This is probably @rmzelle, right?

You can view your token on your profile page (described [here](http://docs.travis-ci.com/user/notifications/#Webhook-notification) at the bottom of the page); we need to set that token as an environment variable on Heroku. Can you set up a Heroku account (or tell me you existing one) so that I can give you access to the bot?

**Comment by rmzelle** [comment]
@adam3smith, can you commit to this PR once more?

**Comment by rmzelle** [comment]
Can you rebase this as well, by the way? The first three commits shouldn't be in this PR.

**Comment by adam3smith** [comment]
that doesn't seem to have worked (not rebasing bc I've already committed https://github.com/citation-style-language/styles/commit/07481d09ba0bb8afe6c276d723e0aa79677ee4fd ) only function of this now is testing.

**Comment by adam3smith** [comment]
hmm - yeah, rebased this successfully finally, but now we don't have a PR anymore. I'll try again with the next one now that my remote repo is in working order again.

**Comment by rmzelle** [comment]
(well, it says "Pushing new commits will allow the pull request to be re-opened.")

**Pull request closed without merging**
