### PR TITLE
sunway-college-johor-bahru-2015.csl

### PR DESCRIPTION
**Pull request by SunwayCollege**
Guide to Harvard Referencing by Sunway College Johor Bahru

### CODE REVIEW

**Comment by SunwayCollege** [comment]
Thank you

**Comment by adam3smith** [comment]
@rmzelle -- all good from my side, but I figured you may have thoughts about naming.

**Comment by rmzelle** [comment]
@SunwayCollege, thanks for contributing!

Are multiple versions of your style guide in use right now? We prefer to host only the most recent version, and leave out the "2015" from the style title and ID.

Does SCJB also have a style guide for a numeric style, or do you only use the Harvard-based author-date system?

**Comment by SunwayCollege** [comment]
Hi admin

"2015" is removed from style title and ID
SCJB uses Harvard- based author-date system.

Thank you

**Comment by rmzelle** [comment]
Thanks. Finally, do you care a lot about using "Harvard" to describe the style? At CSL we greatly prefer "author-date" (since Harvard styles don't have a real link to the real Harvard).

**Comment by SunwayCollege** [comment]
Hi

The college do emphasis on "author-date" system. However, students are not able to grasp the concept. Thus, the lecturers will use "harvard" referencing  term to guide the students.

**Comment by rmzelle** [comment]
Okay, thanks!

**Pull request merged**
