### PR TITLE
Create Harvard-Unisa-CAS.csl

### PR DESCRIPTION
**Pull request by jacolizem**
Harvard style referencing amended to correspond with official University of South Africa guidelines

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks @jacolizem 
1. Is there a copy of the guidlines for this style online somewhere? I found http://libguides.unisa.ac.za/CEMSHarvard but I assume CAS and CEMS Harvard are different?
2. Do you remember which style you started with to create this one?

**Comment by jacolizem** [comment]
Hi Sebastian.

Thank you for your comments. There are minor differences between CAS and
CEMS's Harvard, but nothing major. I also used the style guidelines from
Unisa's language services that is avaialble online for all Unisa staff (
https://staff.unisa.ac.za/static/intranet/Content/Resources/Documents/Unisa_reference_techniques_28March2013.pdf).
I used UCT's CSL as baseline and amended accordingly as there was not one
available for University of South Africa yet and being a South African
public academic institution I thought this to be the closest to the truth
to start with.

Kind regards,
@jacolizem

**Comment by jacolizem** [comment]
@adam3smith  They are very similar yes, and given that there isn't a CSL for University of South Africa yet, it does make sense to make it a general one for Unisa. CAS in our case refers to College of Accounting Sciences. Thanx!

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
