### PR TITLE
Create arvalia.csl

### PR DESCRIPTION
**Pull request by arvalia**
it-IT CSL style

### CODE REVIEW

**Comment by arvalia** [comment]
Hi! It's my first pull. Can you help me?
I created my CSL style "arvalia", but I don't see it on Zotero Repository:
https://www.zotero.org/styles
What was wrong?
TY for your kind help!

**Comment by rmzelle** [comment]
@arvalia, do you know if the http://www.arvalia.it/ website describes this citation format anywhere? Does the magazine accept open submissions, or is it invite-only?

**Comment by arvalia** [comment]
Hi @rmzelle,

[Arvalia.it](www.arvalia.it) website does not have a description page for the citation format: I will soon create it, I’m still making some adjustments…
Open submissions: at the moment only the magazine’s editors can do it, but I’m interested to engage readers. Does exist a Wordpress plugin or a Zotero online guide to do it?
Thank you,
Anthony

**Comment by arvalia** [comment]
TY **@rmzelle**,

I will go exactly in this direction: **open submissions** and **published style guide**.

I proposed Arvalia’s CSL to Zotero repository because [Zotpress](https://it.wordpress.org/plugins/zotpress/) plugin allows **only** existing CSLs.

Please, trust me admitting Arvalia CSL.
I will create a quality Italian CSL style, suitable for web magazines.
If style guide and open submissions will not online in a week you will delete this CSL.

TY 
Anthony

**Comment by adam3smith** [comment]
You can use custom styles in ZotPress:
Under "Options" click on the style under "Select a default style", then put in the whole URL of the style you want to use, e.g. 
https://raw.githubusercontent.com/arvalia/styles/74cc0298ce7ddcfd66c57091b576dd01eb7442da/arvalia.csl

here.  You can also do this individually for shortcodes as described here: https://raw.githubusercontent.com/arvalia/styles/74cc0298ce7ddcfd66c57091b576dd01eb7442da/arvalia.csl

I'm still not clear on whether this style is needed for anything other than ZotPress?

**Comment by arvalia** [comment]
Great!!!
@adam3smith , it works perfectly!
Really thank you!

**Comment by rmzelle** [comment]
> You can use custom styles in ZotPress

Oh, good to know. I checked the ZotPress forum on WordPress recently and didn't find any mention that this feature had been added.

@arvalia, does this cover your needs sufficiently, or would you still like this style to be added to the style repository? Otherwise I'll close this pull request.

Again, the primary role of this repository is to offer styles to individual authors for formatting references in their documents. @adam3smith and I still aren't clear whether this style would be a good fit for the repository. Will you ask outside contributors to submit their contributions via http://www.arvalia.it/scrivi-un-articolo/ with references formatted according to this style?

**Comment by adam3smith** [comment]
Closing as indicated above. Thanks everyone!

**Comment by arvalia** [comment]
TY

Bye

Anto

 

Da: Sebastian Karcher [mailto:notifications@github.com] 
Inviato: domenica 1 luglio 2018 19:34
A: citation-style-language/styles
Cc: arvalia; Mention
Oggetto: Re: [citation-style-language/styles] Create arvalia.csl (#3460)

 

Closed #3460 <https://github.com/citation-style-language/styles/pull/3460> .

**Pull request closed without merging**
