### PR TITLE
Create iso690-numeric-pl.csl

### PR DESCRIPTION
**Pull request by milekpl**
This is another standard style in Polish bibliography, available on CC license.

### CODE REVIEW

**Comment by rmzelle** [comment]
Coming back to this, @milekpl, where did you find this style? Is it currently available on a different website?

**Comment by milekpl** [comment]
Huh, it's on a different website. Sorry, I was flooded with work. I will email Krzysztof right away.

**Comment by cogosakrth** [comment]
Hi, I made that style by coping Polish locale file into style file because it had to work also in Mendeley. And as far as I know, this was the only way to do it for Zotero and Mendeley.

**Comment by rmzelle** [comment]
@cogosakrth, maybe back when you made this style, Zotero and Mendeley didn't yet have the Polish locale file?

Ideally the style should only redefine those terms that are different from the ones in the Polish locale file at https://github.com/citation-style-language/locales/blob/master/locales-pl-PL.xml.

**Comment by adam3smith** [comment]
(@rmzelle - no, this still doesn't work in Mendeley without the embedded locale file, as you'll recall from other conversations)

**Comment by rmzelle** [comment]
> (@rmzelle - no, this still doesn't work in Mendeley without the embedded locale file, as you'll recall from other conversations)

Even if the user changes the locale to Polish as per http://support.mendeley.com/customer/portal/articles/1367232-how-do-i-change-the-bibliography-s-language- ?

**Comment by adam3smith** [comment]
oh, I assume that works, but that's not a real solution, is it? If you want a style to "just work" rather than require elaborate instructions to everyone who installs it, you still (though hopefully not much longer) have to embed the locale.

**Comment by rmzelle** [comment]
Last I heard is that Mendely is finally, finally, looking at improving this in their software.

@cogosakrth, do you remember if you made any other changes to the style, other than changing the "default-locale" and pasting in the locale file?

**Comment by rmzelle** [comment]
Mendeley's next release should make it easier to select a locale. They also say "By default citations will use the language associated with the selected citation style", so it really shouldn't be necessary to include a complete locale file within the style. If it doesn't work, it should be reported as a bug to Mendeley.

See http://www.mendeley.com/release-notes/v1_13_4-dev1/

**Comment by milekpl** [comment]
@rmzelle: There is a problem here, as Mendeley >1.11 has no support for Mac Word 2008, and a lot of people use the outdated version now.

**Comment by rmzelle** [comment]
Uhm, sorry for letting this pull request linger. On second thought, I'm willing to accept this, but the title needs to be changed to just `<title>ISO-690 (numeric, Polish)</title>`. @milekpl can make the change in the current pull request by clicking the pencil icon at https://github.com/milekpl/styles/blob/patch-2/iso690-numeric-pl.csl

**Comment by rmzelle** [comment]
Thanks. Is there an online description on this format, so that we can add a "documentation" link? (point 10 at https://github.com/citation-style-language/styles/wiki/Style-Requirements )

**Comment by rmzelle** [comment]
Closing because of inactivity.

**Pull request closed without merging**
