### PR TITLE
Create jcom.csl

### PR DESCRIPTION
**Pull request by POBrien333**
Request via emails

### CODE REVIEW

**Comment by adam3smith** [comment]
(the rendering failure is a current issue with all automated tests, so ignore)

**Comment by bwiernik** [comment]
Should the style be named and titled "Journal of Science Communication"?

**Comment by adam3smith** [comment]
I'd go with "JCOM: Journal of Science Communication" which is how they appear in databases like DOAJ. Makes sense to have both full title and short title up front given how heavily they rely on the shore ttitle.

**Comment by POBrien333** [comment]
Thanks. Wasn't sure about the name

**Comment by adam3smith** [comment]
Thanks!

**Comment by adam3smith** [comment]
It's there now

**Comment by POBrien333** [comment]
cheers :)

**Pull request merged**
