### PR TITLE
Create sodertorns-hogskola-oxford.csl

### PR DESCRIPTION
**Pull request by SagaNy91**
CSL-file for a new style, Södertörns Högskola Oxford

### CODE REVIEW

**Comment by rmzelle** [comment]
@SagaNy91, thanks. Will this style only be used in Swedish or also in other languages (like e.g. English)? If it's just Swedish, we'll lock the style to that language so its automatically selected.

**Comment by SagaNy91** [comment]
@rmzelle Hi, I don't want to limit the style to only Swedish (even though it's mostly adapted to Swedish, and follows the rules of a referencing guide written in Swedish). It should work OK in other languages I hope, at least in English. By locking it, people will not be able to choose other languages at all. /Saga

**Comment by rmzelle** [comment]
@SagaNy91, great, thanks. We'll just accept it as is, then.

**Comment by SagaNy91** [comment]
Yes, great!
Thank you.
________________________________
Från: Rintze M. Zelle <notifications@github.com>
Skickat: den 2 februari 2021 05:43
Till: citation-style-language/styles <styles@noreply.github.com>
Kopia: SagaNy91 <saga_nylund@hotmail.com>; Mention <mention@noreply.github.com>
Ämne: Re: [citation-style-language/styles] Create sodertorns-hogskola-oxford.csl (#5234)


@SagaNy91<https://github.com/SagaNy91>, great, thanks. We'll just accept it as is, then.

**Pull request merged**
