### PR TITLE
Create ArcheoSciences citation style

### PR DESCRIPTION
**Pull request by nfrerebeau**
Create *ArchéoSciences : revue d'archéométrie* citation file.

### CODE REVIEW

**Comment by rmzelle** [comment]
@nfrerebeau, thanks. Did you start from an existing CSL style? If so, could you tell us which, so we can include a "template" link? (https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by nfrerebeau** [comment]
I started from *Archéologie médiévale (French)*, but it was not the most appropriate choice and I changed it significantly. Anyway, I added the template link.

**Comment by adam3smith** [comment]
@rmzelle good to merge from my end

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
