### PR TITLE
Create industrial-health.csl

### PR DESCRIPTION
**Pull request by Turius**
Create style csl for Industrial Health, published by the Japan Organization of occupational health and Safety - ISSN: 0019-8366 (Print Version), ISSN: 1880-8026 (Online Version). The style is based on AMA 11th brackets, but it is superscript and right parenthesis only in the text. The bibliography is represented by numbers followed by right parenthesis ")" and not period "."

### CODE REVIEW

**Comment by adam3smith** [comment]
Sorry for the late reply here @Turius -- I'm a bit confused by the bibliography here. I'm seeing
1) Ono-Ogasawara M, Furuse M, Matsumura Y, Yokota K (1992) Determination of diborane by adsorption sampling using modified
silica gel and the chromotropic acid-HPLC method. Ind Health **30**, 35–45.

in the style guide and also published articles. That seems quite different from AMA and what you have here?

**Comment by Turius** [comment]
Hi @adam3smith, thank you for reaching back to me. In the [author guidelines](https://www.jniosh.johas.go.jp/en/indu_hel/doc/instructions_authors.pdf), they write:  
```
References should be cited in the manuscript by superscript Arabic numerals in right parenthesis (e.g.,1), 2, 3) or 3–5)) and numbered in order of citation. As exemplified below, Journal references should show names of all authors cited, year of publication, title of article, name of journal, volume number, and pages. Journal abbreviations should follow Index Medicus. Book references should include names of authors or editors, year of publication, title, edition (if other than first), page(s), publisher, and place of publication. Electronic Source Materials should indicate title of materials/work, a uniform resource locator (URL), and date accessed. 
1) Ono-Ogasawara M, Furuse M, Matsumura Y, Yokota K (1992) Determination of diborane by adsorption sampling using modified silica gel and the chromotropic acid-HPLC method. Ind Health 30, 35–45. 
2) Mcllwain H, Bachelard HS (1971) Biochemistry and the central nervous system, 4th Ed., 171, Churchill Livingston, Edinburgh. 
3) Burrell R (1975) Immunology of occupational lung diseases. In: Occupational lung diseases, Morgan WKC and Seaton A (Eds.), 65–79, WB Saunders, Philadelphia. 
4) Japan Ministry of Health, Labour and Welfare. Final Report of Monthly Labour Survey March 2006. http://www.mhlw.go.jp/ english/database/db-l/18/1803fr/mk1803re.html. Accessed May 29, 2006
```

So I think that the current style reflects these instructions? If it helps, I also submitted a paper to Industrial Health before, and I applied this style. It passed the initial formatting check.

**Comment by adam3smith** [comment]
The references look quite different though, if you compare, e.g. a journal article from the instructions:

> ⁣1) Ono-Ogasawara M, Furuse M, Matsumura Y, Yokota K (1992) Determination of diborane by adsorption sampling using modified silica gel and the chromotropic acid-HPLC method. Ind Health 30, 35–45.

vs. what the current style produces:

> 4)vFenner M, Crosas M, Grethe JS, et al. A data citation roadmap for scholarly data repositories. Sci Data. 2019;6(1):28. doi:10.1038/s41597-019-0031-8

Note the position of the year, period/no period after journal abbreviation, comma vs. colon before page range, issue number vs. no issue number, no DOI vs. DOI and probably more

**Comment by adam3smith** [comment]
@Turius -- any thoughts on the above? I really do appreciate the contribution, but we can only accept the style if it actually matches the guidelines.

**Comment by Turius** [comment]
@adam3smith I think you are correct and the current csl file does not fully match the journal style. I will work more on this and submit a revised version in the future.

**Comment by adam3smith** [comment]
Closing for inactivity -- happy to re-open if you get back to working on this -- just post here.

**Pull request closed without merging**
