### PR TITLE
bulletin-of-faculty-of-pharmacy-cairo-university.csl

### PR DESCRIPTION
**Pull request by Sankar-GEO-ELS**
Style for an Elsevier nonstandard journal with slight changes to the Vancouver style

### CODE REVIEW

**Comment by adam3smith** [comment]
thanks!

**Comment by Sankar-GEO-ELS** [comment]
Hi Sebastian

I am working on a style and while parsing in ruby, I am getting the following error. Could you please help me to understand the error and steps I need to do to rectify this error?


Loading dependent styles...................................................
Loading independent styles..........

Progress: |
Progress: |===================================================================
  1) The CSL Style Repository does not contain any duplicate file names
     Failure/Error: expect(Independents.keys & Dependents.keys).to eq([])

       expected: []
            got: ["journal-of-chiropractic-medicine"]

       (compared using ==)
     # ./spec/repository_spec.rb:14:in `block (2 levels) in <top (required)>'


  2) The CSL Style Repository contains no duplicate ISSNs
     Failure/Error: expect(ISSN.select { |_, styles| styles.length > 1 }).to eq({})

       expected: {}
            got: {"1556-3707"=>["journal-of-chiropractic-medicine", "journal-of-chiropractic-medicine"]}

       (compared using ==)

       Diff:
       @@ -1 +1,2 @@
       +"1556-3707" => ["journal-of-chiropractic-medicine", "journal-of-chiropractic-medicine"]
     # ./spec/repository_spec.rb:18:in `block (2 levels) in <top (required)>'

Progress: |===================================================================
  3) The CSL Style Repository contains no duplicate style titles
     Failure/Error: expect(TITLES.select { |_, styles| styles.length > 1 }).to eq({})

       expected: {}
            got: {"journal of chiropractic medicine"=>["journal-of-chiropractic-medicine", "journal-of-chiropractic-medicine"]}

       (compared using ==)

       Diff:
       @@ -1 +1,2 @@
       +"journal of chiropractic medicine" => ["journal-of-chiropractic-medicine", "journal-of-chiropractic-medicine"]
     # ./spec/repository_spec.rb:22:in `block (2 levels) in <top (required)>'

Progress: |====================================================================|

Finished in 1 minute 32.48 seconds
125322 examples, 3 failures

Failed examples:

rspec ./spec/repository_spec.rb:13 # The CSL Style Repository does not contain any duplicate file names
rspec ./spec/repository_spec.rb:17 # The CSL Style Repository contains no duplicate ISSNs
rspec ./spec/repository_spec.rb:21 # The CSL Style Repository contains no duplicate style titles



Thanks
Sankar

**Comment by rmzelle** [comment]
It means that a style exists both as an independent and as a dependent style. In this case, we already have an independent style: https://github.com/citation-style-language/styles/blob/master/journal-of-chiropractic-medicine.csl

**Comment by adam3smith** [comment]
and as you can see, that style was added by Ramanathan, so I'd expect it to conform to your list of changes already.

**Comment by Sankar-GEO-ELS** [comment]
Thanks, this style is missing in our list. I should have searched the GitHub before start working. Anyway thanks for your help.

**Comment by Sankar-GEO-ELS** [comment]
Now I understood the error…expected {}….got {journal-of-chiropractic-medicine.csl }….so style exits in github already. Thanks

**Comment by rmzelle** [comment]
No problem! We have some plans to make the test reports more easy to understand.

Also, since we rarely have any comments on your submissions, maybe you could save up your styles and submit them all in a single pull request, e.g. once every two weeks or so? That should reduce the number of pull requests a bit.

**Comment by Sankar-GEO-ELS** [comment]
I think once in every two weeks is bit long, i think once in a week would be fine. I will do so then.

**Comment by rmzelle** [comment]
Sure!

**Pull request merged**
