### PR TITLE
Create concordia-theological-seminary-turabian.csl

### PR DESCRIPTION
**Pull request by petersractsfw**
I would like to add a style for use at Concordia Theological Seminary which is based off the Turabian 8th edition (full note) style, please.

Thank you!

### CODE REVIEW

**Comment by rmzelle** [comment]
@petersractsfw, thanks. Can you tell us how your CTSFW style format is documented? Is there an online style guide we can link to? We always try to document this so that it's possible to track down what guidelines each CSL style is based on. (see also https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link)

**Comment by petersractsfw** [comment]
@rmzelle Thank you for following up. I am one of the librarians at Concordia Theological Seminary, Fort Wayne, Indiana. Unfortunately, we do not have any specific style documentation. Our professors simply tell the students to use Turabian. Through my own experience and through working with the students, I've learned that they do not like "ibid," and want the short title in subsequent references no matter what. So I have modified the Turabian style to fit this. Part of why I am doing this is to work toward creating/adopting some official style documentation for our institution. Right now, I am putting pieces together and my next step will be to seek buy-in from the program directors. If the librarians has already done all the work, they will be most likely to accept it.

So is it possible to submit the style now so that our students can begin to use it and then link documentation after it has been officially adopted and posted?

Thanks for your help!

**Comment by rmzelle** [comment]
> Our professors simply tell the students to use Turabian. Through my own experience and through working with the students, I've learned that they do not like "ibid," and want the short title in subsequent references no matter what. So I have modified the Turabian style to fit this.

Do you think that will be the only change? If so, it might make more sense for us to create a "no Ibid." version of the "Turabian 8th edition (full note)" style. We can then later always make a so-called dependent CSL style that links to that version for CTSFW once you have some style documentation online.

**Comment by petersractsfw** [comment]
That's not a bad idea. I was also looking at the 9th edition of Turabian yesterday afternoon, and I noticed that their example of a shortened not for subsequent references is exactly what our professors are requiring. Is it possible to create a Turabian 9th edition (full note) style? Since the University of Chicago Press does not publish a change log for Turabian, you sometimes have to find these differences as you use it.

**Comment by rmzelle** [comment]
> I was also looking at the 9th edition of Turabian yesterday afternoon, and I noticed that their example of a shortened not for subsequent references is exactly what our professors are requiring. Is it possible to create a Turabian 9th edition (full note) style?

Yes, that would be even better. We have an open issue for making a Turabian 9th edition style (https://github.com/citation-style-language/styles/issues/3496), but we haven't had any takers yet. @POBrien333, would you have any interest in this?

**Comment by POBrien333** [comment]
I don't really like working on these big footnote styles and still working through all the requests. But I put it on the request list anyway.

**Comment by adam3smith** [comment]
I can take this one -- requires buying the stupid manual, too. One more for the collection... Will take a little time, though.

**Comment by adam3smith** [comment]
I think I'd be inclined to close this in favor of the Turabian 9 issue -- would that be OK?

**Comment by petersractsfw** [comment]
That works for me. Is it possible for me to subscribe to be notified when it's released, or should I just check periodically?

**Comment by adam3smith** [comment]
Yes, there's a "Subscribe" button at the bottom right of https://github.com/citation-style-language/styles/issues/3496 
Thanks!

**Pull request closed without merging**
