### PR TITLE
Springer update 2015 fix

### PR DESCRIPTION
**Pull request by zuphilip**
These modifications should make Travis happy again. Discussed in detail in the other thread.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks for looking into this. I'll probably not merge this, though, since the ISSN issues should be fixed in the metadata.

I added an extra tab to the spreadsheet with the files added/deleted. The only deleted styles currently are (these should be checked by hand and added to renamed-styles.json (pointing to their original parent)):
acta-theriologica.csl
aegean-review-of-the-law-of-the-sea-and-maritime-law.csl
bulletin-of-materials-science.csl
combination-products-in-therapy.csl
criminal-law-and-philosophy.csl
current-hepatitis-reports.csl
current-respiratory-care-reports.csl
current-translational-geriatrics-and-gerontology-reports.csl
european-journal-of-population-revue-europeenne-de-demographie.csl
giornale-italiano-di-health-technology-assessment.csl
indian-journal-of-virology.csl
information-retrieval.csl
international-journal-of-colorectal-disease.csl
international-journal-of-euro-mediterranean-studies.csl
international-journal-of-health-care-finance-and-economics.csl
international-journal-of-the-classical-tradition.csl
jahrbuch-fur-regionalwissenschaft.csl
journal-fur-betriebswirtschaft.csl
journal-of-astrophysics-and-astronomy.csl
journal-of-bioethical-inquiry.csl
journal-of-biorheology.csl
journal-of-chemical-sciences.csl
journal-of-earth-system-science.csl
journal-of-genetics.csl
journal-of-geometric-analysis.csl
journal-of-global-policy-and-governance.csl
journal-of-hepato-biliary-pancreatic-sciences.csl
journal-of-science-teacher-education.csl
modern-rheumatology.csl
naturwissenschaften.csl
nexus-network-journal.csl
pharmacoeconomics-german-research-articles.csl
pramana.csl
proceedings-mathematical-sciences.csl
sadhana.csl
sensing-and-imaging-an-international-journal.csl
technology-operation-management.csl
transition-studies-review.csl
wirtschaftsinformatik.csl

**Comment by rmzelle** [comment]
I'm checking these styles in the spreadsheet, by the way.

**Comment by zuphilip** [comment]
May I help in the spreadsheet? Or is some independent check preferable?

**Comment by rmzelle** [comment]
No, go ahead. Plenty to go around :)

**Pull request closed without merging**
