### PR TITLE
update bluebook-law-review.csl

### PR DESCRIPTION
**Pull request by POBrien333**
see https://forums.zotero.org/discussion/105567/bluebook-capitalisation-unreported-cases

### CODE REVIEW

**Comment by adam3smith** [comment]
I would check if you can add the institutions to reports here and if you want to work on unreported cases, do that in a different pull request. Might be worth checking in APA or Chicago Manual -- both of which follow Bluebook for case citations and have some case citation code nicely contained in separate macros, so might be possible to just copy over

**Comment by adam3smith** [comment]
OK, so not changing reports, let's do cases separately (again, if you want to to into that at all)

**Comment by adam3smith** [comment]
Thanks!

**Comment by POBrien333** [comment]
Ok, will see if I have the time and will for the other issues. Stuff I don't fully understand and is hard to decipher doesn't necessarily motivate me. Ha

**Pull request merged**
