### PR TITLE
Create rivista-italiana-di-paleontologia-e-stratigrafia.csl

### PR DESCRIPTION
**Pull request by mcranium**
Sorry I am not skilled in programming. Validation of the code didn't pass because of empty else elements. I just wanted the code to do nothing... Worked out in Zotero on Linux without problems.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- could you please add the ISSN and a documentation link for this style (see 9. and 10. here: https://github.com/citation-style-language/styles/wiki/Style-Requirements )

**Comment by mcranium** [comment]
The journal is published in English only. Sorry I am not sure where to put this information. Thank you so much for your help!

**Comment by adam3smith** [comment]
(good to merge from my end)

**Comment by rmzelle** [comment]
Here too :). Thanks both!

**Pull request merged**
