### PR TITLE
UNFCCC style update

### PR DESCRIPTION
**Pull request by mserifovic**
Period added after "(eds.)"
et al settings changed

### CODE REVIEW

**Comment by mserifovic** [comment]
Very minor changes made to style. Not able to interpret the auto check.

**Comment by adam3smith** [comment]
you didn't change the style, you added a new file without the .csl file extension.

**Comment by rmzelle** [comment]
@mserifovic, you can update the existing style from the repository by clicking the pencil icon at https://github.com/citation-style-language/styles/blob/master/united-nations-framework-convention-on-climate-change.csl. See also https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style for further instructions.

**Comment by mserifovic** [comment]
Great, thanks rmzelle. Pull request for the update created.

**Pull request closed without merging**
