### PR TITLE
Create ersam-histoires-et-sources-anciennes.csl

### PR DESCRIPTION
**Pull request by heaven988**
French CSL style for History and ancient litterature

### CODE REVIEW

**Comment by heaven988** [comment]
Hello,
Great, i passed the test !
Do i have just to wait to see this resquest integrate in the master branch ?
Thank you.

**Comment by rmzelle** [comment]
@heaven988, hi, sorry for the slow response.

Does ERSAM have a website? And is there a style guide (online or in print) that describes the ERSAM citation format?

**Comment by rmzelle** [comment]
@heaven988, see my question above. And ERSAM stands for "Équipe de Recherche Sources Antiques Multimédias", correct?

If we haven't heard back from you in a week, we'll close this pull request (but we can always reopen it if you reply).

**Comment by heaven988** [comment]
I am sorry i have completely forget this ask. I will get back to work on that in january, and made a page on my website to show what the style give.

**Comment by adam3smith** [comment]
@heaven988 we can re-open this if/when you get a chance to revisit.

**Pull request closed without merging**
