### PR TITLE
Create citation-compass-apa-note.csl

### PR DESCRIPTION
**Pull request by bwiernik**
https://forums.zotero.org/discussion/80599/request-new-style-apa-6th-for-footnotes

(Let's let the requester test it before merging.)

### CODE REVIEW

**Comment by bwiernik** [comment]
Okay, this should be good to go.

**Comment by rmzelle** [comment]
@bwiernik, do you know if this style would only be used in English, only in one of the Norwegian locales (Bokmål, Nynorsk), or a combination? Even if we leave off a default-locale, we should probably strip the in-style translations of any other languages (like Danish, German, Spanish, and Dutch).

**Comment by rmzelle** [comment]
And we could also name the style `<title>Citation Compass (Kildekompasset) - APA (note)</title>` (but leave the style ID as is), which we sometimes do in cases like these (see e.g. https://www.zotero.org/styles?q=id%3Aacta-universitatis-agriculturae-sueciae&dependent=0)

**Comment by bwiernik** [comment]
Okay, made those changes. Should I add the other Norwegian locale for `et al` (and also in APA styles, versus just having it in `nn` but not `by`)?

**Comment by rmzelle** [comment]
It's my understanding that "nb" is Norwegian Bokmål (see https://r12a.github.io/app-subtags/), which is already used in the APA styles. I'll put that back and merge the style.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
