### PR TITLE
Create universite-de-sherbrooke-departement-de-geomatique.csl

### PR DESCRIPTION
**Pull request by ArMoraer**
New style for Université de Sherbrooke - Département de géomatique appliquée

### CODE REVIEW

**Comment by ArMoraer** [comment]
Last commit passed the Travis CI checks

**Comment by rmzelle** [comment]
After looking at http://www.usherbrooke.ca/geomatique/fileadmin/sites/geomatique/espace-etudiant/guide-redaction2004.pdf, I was wondering whether the Département de géomatique is a subdepartment of Département de géographie et télédétection? Or do they just share the same citation format?

Secondly, it would be better to replace

```xml
    <category field="humanities"/>
    <category field="generic-base"/>
```

by

```xml
    <category field="geography"/>
```

(assuming that geomatics is a subtopic of geography; see also http://docs.citationstyles.org/en/stable/specification.html#appendix-i-categories)

**Comment by ArMoraer** [comment]
Hi rmzelle,
"Département de géographie et télédétection" is actually the old name of "Département de géomatique". However, your remarks about the category elements are relevant because I forgot to update them. Since Geomatics is a multidisciplinary field that belongs to Geography, Physics and Computer Science, I have set the following categories : 

```xml
<category field="geography"/>
<category field="physics"/>
<category field="engineering"/>
```

Don't hesitate to correct me if you feel these categories are wrong.

**Comment by rmzelle** [comment]
Thanks for clarifying, and thanks for contributing!

**Pull request merged**
