### PR TITLE
Create harvard-orient-institut-beirut.csl

### PR DESCRIPTION
**Pull request by rajeshvr**
OIBR csl style added

### CODE REVIEW

**Comment by rmzelle** [comment]
Hi. A few questions:

* Is there an online description of this citation format?
* Does the OIB use more than one citation format (e.g. a "numeric" and an "author-date" variant)? If it's just this format, we would typically remove the "Harvard" from the style title.
* Will this CSL style be used in more than one language?

**Comment by rmzelle** [comment]
Also, I noticed that this style was submitted twice by two different GitHub accounts (here and in #2279). We can deal with this submission in either issue, but one of them should be closed.

**Comment by rajeshvr** [comment]
I am closing this request as one of my colleagues also made a pull request of the same

**Comment by rmzelle** [comment]
Okay, thanks.

**Pull request closed without merging**
