### PR TITLE
Update peerj.csl

### PR DESCRIPTION
**Pull request by burnmeister**
inserted web pages and blog post entries such as 'available at' and 'accessed'

### CODE REVIEW

**Comment by rmzelle** [comment]
`et-al-min="10" et-al-use-first="10"` doesn't make sense. If you have 10 authors, you wouldn't show all 10 and "et al.". ("use-first" should always be less than "min")

Does PeerJ have an "et al." requirement?

**Comment by zuphilip** [comment]
The last reference in the latest article https://peerj.com/articles/cs-8/ is actually showing all 11 authors. However, in the HTML the last author is behind the " +1 more" link. My guess would be that we shouldn't use `et-al` in the references, i.e. this was correct before.

**Comment by burnmeister** [comment]
I also don't see any 'et al' requirements in the reference section guidelines ( https://peerj.com/about/author-instructions/#reference-section )

**Comment by zuphilip** [comment]
<blockquote>Each journal reference should be listed using this format: the full list of Authors with initials...</blockquote>
This sounds like they really want to have all authors and never an et-al.

**Comment by adam3smith** [comment]
OK, since there's now a consensus, could you remove the new et-al from the style? You can update your pull request by using the pencil (edit) button here:
https://github.com/burnmeister/styles/blob/patch-7/peerj.csl

Let us know when you're done, since we don't get notified on updated pull requests.

**Comment by burnmeister** [comment]
I have removed et-al-min="10" et-al-use-first="10"  and updated the pull request

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
