### PR TITLE
Update bursa-uludag-universitesi-saglik-bilimleri-enstitusu.csl

### PR DESCRIPTION
**Pull request by ozhansaglik**
We need to exclude (Turkish) from the title.

### CODE REVIEW

**Comment by adam3smith** [comment]
All CSL styles with a non-English decault locale have the language in parentheses in the repository. Why would you want to remove it?

**Comment by ozhansaglik** [comment]
Because our other styles do not include Turkish in parentheses. 

mendeley_desktop

**Comment by rmzelle** [comment]
@ozhansaglik, like @adam3smith says, we always include the language in the title for CSL styles fixed to a non-English language.

In your recent update of the "Bursa Uludağ Üniversitesi - Sağlık Bilimleri Enstitüsü" style (https://github.com/citation-style-language/styles/pull/3767), you added `default-locale="tr-TR"` to that style, which fixes the style to Turkish. As a result, we added the "(Turkish)" to the style title.

Was the addition of `default-locale="tr-TR"` an intentional change? When you first contributed the styles for Bursa Uludağ Üniversitesi, you indicated that the styles could also be used in English (https://github.com/citation-style-language/styles/pull/3715#issuecomment-427739365), in which case we wouldn't want to fix any of the styles to Turkish.

**Comment by ozhansaglik** [comment]
It is my fault sorry for the disturbance. I did not add "default-locale="tr-TR" intentionally, also I did not examine if there is a code like this.

Can you delete it or I have to delete it?

Sorry again.

Best

Özhan

**Comment by rmzelle** [comment]
I just reverted the change: https://github.com/citation-style-language/styles/commit/41cb8d2df5c582f008703c01abe9833b18684a6b

Should show up in Zotero/Mendeley within a day.

**Pull request closed without merging**
