### PR TITLE
Create purh-changer-d-epoque.csl

### PR DESCRIPTION
**Pull request by NMonteix**

### CODE REVIEW

**Comment by rmzelle** [comment]
Does this replace #1791?

**Comment by NMonteix** [comment]
Yes. A few changes in the structure of the file, though

**Comment by rmzelle** [comment]
Thanks. We never include the name of the publisher in the title and/or style ID for journal-styles, though, so this should just be "Changer d'époque (French)" and "changer-d-epoque.csl".

**Comment by NMonteix** [comment]
Title changed

**Comment by rmzelle** [comment]
Looks good to me. @adam3smith?

**Comment by rmzelle** [comment]
Thanks!

**Comment by rmzelle** [comment]
Also, any particular reason you didn't update the original pull request?

**Comment by rmzelle** [comment]
> NMonteix wants to merge 2 commits into citation-style-language:master from unknown repository

Ah, it looks like your original repository/branch didn't exist any more. I guess that's a good reason :)

**Comment by NMonteix** [comment]
To you!

**Comment by NMonteix** [comment]
Indeed...
Debasing remains quite a problem, but I'll find a way
:)

**Pull request merged**
