### PR TITLE
Create Médecine Intensive Réanimation.csl

### PR DESCRIPTION
**Pull request by Soniashine**

### CODE REVIEW

**Comment by rmzelle** [comment]
Hi @Soniashine, @POBrien333 ("@damnation" on the Zotero forums) already submitted his style for this journal at https://github.com/citation-style-language/styles/pull/2986, so we can probably take that instead.

**Comment by Soniashine** [comment]
Yes of course he gave it to me this morning but I don't know how to add it to zotero now?? thank you

**Comment by rmzelle** [comment]
@Soniashine, we'll get the style added to the Zotero Style Repository within the next few days, but you can already install the style by following the instructions at https://www.zotero.org/support/styles#installing_additional_styles (just right-click the style at https://raw.githubusercontent.com/POBrien333/styles/2e39340aead21e9ef4963f7c67988b0951631e13/medecine-intensive-reanimation.csl and save it to your computer first).

**Comment by rmzelle** [comment]
Added in #2986.

**Pull request closed without merging**
