### PR TITLE
Create harvard-university-of-exeter.csl

### PR DESCRIPTION
**Pull request by aricooperdavis**
This is a Harvard csl style guide for the University of Exeter. I am using the Geography department's documentation, and I have checked as many Journal Articles, Books, Websites, and Theses that I can, but have not yet looked at other publication types. I will update these as I go along.

### CODE REVIEW

**Comment by rmzelle** [comment]
@aricooperdavis, did you base this on an existing CSL style? If so, we'd like to have a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

**Comment by rmzelle** [comment]
Thanks! (note that I made a few minor changes, mostly to standardize the title and style ID)

**Comment by aricooperdavis** [comment]
Brilliant, Thanks rmzelle 👍 Any particular way for me to make improvements/updates?

**Comment by rmzelle** [comment]
> Any particular way for me to make improvements/updates?

See https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style. The main thing is to always start from the latest version in our repository.

**Pull request merged**
