### PR TITLE
creates the gigascience.csl file

### PR DESCRIPTION
**Pull request by azneto**
This is a style proposal for the Gigascience (https://academic.oup.com/gigascience).

### CODE REVIEW

**Comment by rmzelle** [comment]
@azneto, thanks. Can you tell us how this differ from our existing GigaScience style? (https://www.zotero.org/styles?q=id%3Agigascience)

**Comment by azneto** [comment]
> @azneto, thanks. Can you tell us how this differ from our existing GigaScience style? (https://www.zotero.org/styles?q=id%3Agigascience)

Currently, the GigaScience style available is just a redirect to Springer - Vancouver (https://csl.mendeley.com/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fgigascience) which is very different to the GigaScience guidelines (https://academic.oup.com/gigascience/pages/instructions_to_authors).

I took the Springer - Vancouver style and modified according to the GigaScience guidelines.

**Comment by azneto** [comment]
@rmzelle, I can't find the gigascience CSL file in the github repository, but the test keeps failing due to duplicate titles. I don't know how to fix it.

**Comment by rmzelle** [comment]
> I can't find the gigascience CSL file in the github repository

https://github.com/citation-style-language/styles/blob/master/dependent/gigascience.csl. It's a dependent style that use the format of https://github.com/citation-style-language/styles/blob/master/springer-vancouver-brackets.csl.

> the test keeps failing due to duplicate titles

That's because we already have a style for this journal.

**Comment by azneto** [comment]
@rmzelle Currently, the GigaScience style available is just a redirect to Springer - Vancouver (https://csl.mendeley.com/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fgigascience) which is very different to the GigaScience guidelines (https://academic.oup.com/gigascience/pages/instructions_to_authors).

I took the Springer - Vancouver style and modified according to the GigaScience guidelines.

Please let me know if I should go forth in fixing the .csl file to pass the test report.

**Comment by adam3smith** [comment]
@rmzelle the journal moved from BMC to OUP in 2017, so the change in style makes sense.

@azneto yes, please simply remove the /dependent/gigascience.csl file from your branch and the pull request should validate

**Comment by azneto** [comment]
@adam3smith, it's fixed now, thanks.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
