### PR TITLE
Create ucl-university-college-denmark-apa.csl

### PR DESCRIPTION
**Pull request by ckan9445**
UCL University College Denmark APA 7. edition. New documentation and some revisions made to suit Danish.

### CODE REVIEW

**Comment by rmzelle** [comment]
@ckan9445, could you update the style so it validates correctly? See https://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcitation-style-language%2Fstyles%2F26edac2bcb9468975c40ced322e1d9dae8ef57b1%2Fucl-university-college-apa.csl&version=1.0.1 for the current error:

Line 1785: Bad value “year-day-month” for attribute “date-parts” on element “date” from namespace “http://purl.org/net/xbiblio/csl”.

```xml
      <date form="text" date-parts="year-day-month" variable="issued"/>
```

(see also https://docs.citationstyles.org/en/1.0.1/specification.html#date)

**Comment by rmzelle** [comment]
I was also wondering you expect this style to be used with both Danish and English, or only with the former.

**Comment by ckan9445** [comment]
@rmzelle It's intended for Danish - not English. I have deleted the line about the date, but we have had problems about converting the date from the american standard of writing year-month-date (2020, August 17) to the European way of writing year-date-month (2020, 17. august).

**Comment by rmzelle** [comment]
> It's intended for Danish - not English.

Okay, I changed the style to always use Danish.

> I have deleted the line about the date, but we have had problems about converting the date from the american standard of writing year-month-date (2020, August 17) to the European way of writing year-date-month (2020, 17. august).

Can you give some example citations generated with this style that give the wrong format, and indicate what it should be?

**Comment by ckan9445** [comment]
**Newspaper article:** 

Andersen, M.-L. (2019, februar 20). Utilfredshed med folkeskolen: Forældre på lukningstruet skole planlægger hjemmeundervisning. Jyllands-Posten. https://jyllands-posten.dk/aarhus/norddjurs/ECE11198342/foraeldre-paa-lukningstruet-skole-planlaegger-hjemmeundervisning/ 

The date should be:

Andersen, M.-L. (2019, 20. februar). Utilfredshed med folkeskolen: Forældre på lukningstruet skole planlægger hjemmeundervisning. Jyllands-Posten. https://jyllands-posten.dk/aarhus/norddjurs/ECE11198342/foraeldre-paa-lukningstruet-skole-planlaegger-hjemmeundervisning/

**Blog-post:**
Hansen, R. S. (2019, april 6). Nutidens børn er fremtidens voksne. Vores virkelighed. http://voresvirkelighed.dk/?p=9504

Should be:

Hansen, R. S. (2019, 6. april). Nutidens børn er fremtidens voksne. Vores virkelighed. http://voresvirkelighed.dk/?p=9504

It should also include the retrieval date when citing an online dictionary/reference work that is continuously updated - but the APA 7th Zotero style doesn't include the date. But the retrieval date should be as this example:

Inklusion. (2010). I: Dansk Psykologisk-Pædagogisk Ordbog. Lokaliseret 20. august, fra https://www.ordbogen.com/da/search#/gyldendal-psych-dada/inklusion

**Comment by adam3smith** [comment]
I've fixed the bibliography date format for you. The accessed date for reference works I'd leave as is: The style prints an accessed date where an item _doesn't_ have an issued date. I think that's the right choice. If a work gets continuously updated, the issued date should reflect the time it was last updated

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
