### PR TITLE
Create oie-scientific-and-technical-review.csl

### PR DESCRIPTION
**Pull request by OIECitationStyle**
The output style for OIE Scientific and Technical Review was tested and validated by the editors. Now, we wish it can be easily avaible online

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks!

The style looks good, but we always try to avoid acronyms in style titles. How about:

* for file name/"self" link/style ID: "world-organisation-for-animal-health-scientific-and-technical-review" (+ ".csl" for the file name)
* for title:

```
<title>World Organisation for Animal Health - Scientific and Technical Review</title>
<title-short>OIE - Sci. Tech. Rev.</title-short>
```

**Comment by rmzelle** [comment]
See https://help.github.com/articles/renaming-a-file/ for instructions on how to change the file name.

**Comment by OIECitationStyle** [comment]
Many thanks (first time I post on GitHub, your help is appreciated)

**Comment by rmzelle** [comment]
Perfect, thanks!

**Pull request merged**
