### PR TITLE
Remove unused macros

### PR DESCRIPTION
**Pull request by fbennett**
Just a bit of tidying up. It looks like most of these were my doing from long ago.

### CODE REVIEW

**Comment by rmzelle** [comment]
That's odd. Our Travis tests are supposed to check for any unused macros.

There is also some white space problem in this PR (a few newly inserted blank lines).

**Comment by rmzelle** [comment]
Ah, apparently we are exempting the Chicago styles from those tests. I remember now.

https://github.com/citation-style-language/styles/blob/e7bf5fe64c40695cade64d24950cab7f55743cb2/spec/spec_helper.rb#L30

**Comment by rmzelle** [comment]
Let's merge these changes in #3528.

**Comment by rmzelle** [comment]
And obviously thanks!

**Comment by adam3smith** [comment]
We're exempting these because it makes it much easier for me to handle adjustments of CMoS styles across different versions, so let's please keep the unused macros in.

**Pull request closed without merging**
