### PR TITLE
Create nordic-pulp-and-paper-research-journal.csl

### PR DESCRIPTION
**Pull request by meaghany**

### CODE REVIEW

**Comment by rmzelle** [comment]
@meaghany, could you

* change the title to `<title>Nordic Pulp &amp; Paper Research Journal</title>`?
* add a "documentation" link to the Instructions to Authors webpage of the journal (http://www.npprj.se/html/main.asp?i=168&h=2&b=1&c=100)? See https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link
* if you based this on another style, could you add a "template" link? See https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link
* also please change `<issnl>0283-2631</issnl>` to `<issn>0283-2631</issn>`

Thanks.

**Comment by rmzelle** [comment]
Added in #2264.

**Comment by meaghany** [comment]
Hi Rintze,

Sorry I let this item drop - I am working on it again and will incorporate
all of your requests. Can it be reopened or should I repost?

Thanks,
Meaghan

**Comment by rmzelle** [comment]
@meaghany, per above, I went ahead and made the changes I previously requested, and added the style to our repository. So you're all set. (you can e.g. find the style now at https://www.zotero.org/styles?q=id%3Anordic-pulp-and-paper-research-journal)

**Comment by meaghany** [comment]
Thanks Rintze!

**Pull request closed without merging**
