### PR TITLE
Create univie-history-fullnote-bibliography.csl

### PR DESCRIPTION
**Pull request by ulkjasdf**
Created a new fullnote-bibliography with the style of the department of history at the university of vienna.
For exact information see:
http://ifg.univie.ac.at/fileadmin/user_upload/i_geschichte/Studium/Zitierregeln_IfG.pdf 
Completely new file...

### CODE REVIEW

**Comment by ulkjasdf** [comment]
Is it normal that i have to wait, or did i forget anything?

**Comment by adam3smith** [comment]
Sorry, yes, this typically should go much quicker but we're both a bit short on time so things are taking longer than we'd prefer. I should get to this shortly.

**Comment by rmzelle** [comment]
@ulkjasdf, sorry for the very long wait.

Before I accept this, could you tell me which languages this CSL style can be used with? Just German, or also English?

**Comment by ulkjasdf** [comment]
@rmzelle 
Wow, i waited for over one year and after that you did'nt even look at
the source code?
It's for english and german language (as you would see in the code after
5 seconds). 
actually i wanted to use this program (zotero) and script in university in many classes, but after waiting soo long - i advice students to take different program and don't waste their time with this program/or trying taking part.

**Comment by rmzelle** [comment]
@ulkjasdf, again my apologies for the long wait, and on behalf of @adam3smith for telling you in March that we would look at this soon. There are currently only two (volunteer) maintainers of this repository, and we get hundreds of these pull requests each year. We sometimes just don't have the time to address all of them in a timely manner next to our day jobs and family life. We're also trying to improve the way we keep track of open issues so we respond to them in a more timely manner.

Please also note that the Citation Style Language project and this style repository are independent of Zotero. Zotero does use our styles, but so do many other programs, like Mendeley and Papers.

For this submission, I didn't realize that "Completely new file..." meant you wrote the style from scratch. A lot of style contributors modify an existing style, so I just wanted to make sure the use of German and English terms was intentional. I did take a look at the style code.

(I can also recommend reading https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/, which gives you a good view of what things look like from our perspective)

**Comment by adam3smith** [comment]
(the style isn't written from scratch -- as it correctly indicates, it uses Chicago full note as a template. The question for which languages it was intended made total sense).

**Comment by rmzelle** [comment]
> the style isn't written from scratch -- as it correctly indicates, it uses Chicago full note as a template.

Yes, I just noticed that.

@ulkjasdf, I changed the title of the style to "Universität Wien - Institut für Geschichte", since the university is in Austria and the guidelines are in German. Let me know whether that's okay with you and I'll be happy to merge your style into the repository.

**Comment by rmzelle** [comment]
(added this style to the repository)

**Pull request merged**
