### PR TITLE
Update acta-philosophica.csl

### PR DESCRIPTION
**Pull request by fcofdezlab**
Added French and German customized locales. Corrected some formatting errors

### CODE REVIEW

**Comment by fcofdezlab** [comment]
My update request seems in a dead track. Is there something missing?

**Comment by rmzelle** [comment]
> Is there something missing?

Nope. All looks good, thanks. I missed this somehow.

(for next time, it's easier for us to keep track of things if you update your original pull request (in this case, #2029), instead of creating a new one)

**Comment by fcofdezlab** [comment]
My initial mistake (opening a new pull request instead of updating the old one) made me learn the lesson of how to update pull requests. Thank you!

**Comment by rmzelle** [comment]
> made me learn the lesson of how to update pull requests.

Great! (the instructions on how to update pull requests changed recently because GitHub changed the website a little; our latest version is at https://gist.github.com/rmzelle/a80e260ce6426b8b5a73c1eb74e7376f)

**Pull request merged**
