### PR TITLE
Create ipb-ppki-3.csl

### PR DESCRIPTION
**Pull request by auriza**

### CODE REVIEW

**Comment by rmzelle** [comment]
[PPKI_III.pdf](https://github.com/citation-style-language/styles/files/4163217/PPKI_III.pdf)

**Comment by rmzelle** [comment]
Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by auriza** [comment]
> Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

We use [visual editor](https://editor.citationstyles.org/visualEditor/) using the default template, based on [APA](http://www.zotero.org/styles/apa).

**Comment by rmzelle** [comment]
Thanks!

**Comment by auriza** [comment]
> Thanks!

You're welcome. Thank you very much for your assistance.

**Pull request merged**
