### PR TITLE
Create amsterdam-university-press-academic-ejt.csl

### PR DESCRIPTION
**Pull request by jd-s**
Modified Template to meet the requirements of European Journal of Theology (EJT), see http://www.paternosterperiodicals.co.uk/european-journal-of-theology.

### CODE REVIEW

**Comment by adam3smith** [comment]
So is this style different from the general AUP style? If so how? Is it documented somewhere?

**Comment by adam3smith** [comment]
Also, unless you disallowed this on purpose, could you enable edits on your pull request? See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

(If you did disable this on purpose that's fine, of course, but I'd be curious why)

**Comment by jd-s** [comment]
> So is this style different from the general AUP style? If so how? Is it documented somewhere?

The main difference is the "No use of p. or pp." and "In the footnotes, you only give author’s name and year of publication, followed by page number(s) as required." - quotes from the EJT Style Guide. 

I also stumbled upon disabled edits - but I cannot enable edits on this pull request. The option in your link is simply missing here... shall I open a new request?

**Comment by adam3smith** [comment]
Thanks & sorry for the delay!

**Pull request closed without merging**
