### PR TITLE
Create university-college-cork-harvard.csl

### PR DESCRIPTION
**Pull request by shawnday**
Created for use in citation management programmes by students and staff at University College Cork

### CODE REVIEW

**Comment by rmzelle** [comment]
Hi Shawn, thanks for submitting a style. Two questions:

* Is your Harvard citation format described anywhere online?
* Do you know which CSL citation style you started from? We always try to include a "template" link whenever possible (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

Thanks!

**Comment by shawnday** [comment]
Thanks very much for checking those out.
I will add those to the definition.
Best,
Shawn

~~ shawn.day@ucc.ie
~~ Lecturer in Digital Humanities
~~ College of Arts, Celtic Studies and Social Science
~~ University College Cork
~~ @iridium

On Sat, Jun 23, 2018 at 0:17, Rintze M. Zelle <notifications@github.com> wrote:

Hi Shawn, thanks for submitting a style. Two questions:

  *   Is your Harvard citation format described anywhere online?
  *   Do you know which CSL citation style you started from? We always try to include a "template" link whenever possible (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

Thanks!

**Comment by rmzelle** [comment]
@shawnday, if you can tell me which CSL style you started out from, and whether your style guide is available online, I can finalize the style myself too.

**Comment by shawnday** [comment]
Thanks Rintze and apologies for delay in coming back to you.

Our university library reference for online style guide uses: https://libweb.anglia.ac.uk/referencing/harvard.htm for Harvard and is the basis of what we use.

The CSL style from which this started was: harvard-anglia-ruskin-university.csl

Thanks very much for your assistance,
Shawn

~~ shawn.day@ucc.ie
~~ Lecturer in Digital Humanities
~~ College of Arts, Celtic Studies and Social Science
~~ University College Cork
~~ @iridium

On Sat, Jul 7, 2018 at 4:56, Rintze M. Zelle <notifications@github.com> wrote:

@shawnday<https://github.com/shawnday>, if you can tell me which CSL style you started out from, and whether your style guide is available online, I can finalize the style myself too.

**Comment by adam3smith** [comment]
But your style is different from the Anglia Ruskin style, right? Otherwise we could just link to the style directly rather than having extra code. And if it is different, are those differences described anywhere?

**Comment by shawnday** [comment]
Thanks Sebastian. Other than links to local resources and naming a local resource those are limited changes. Could you possibly point to example of changes describe elsewhere can document appropriately. Simply via read.me. Apologies for being obtuse. Thanks, Shawn


~~ day.shawn@gmail.com ~~ @iridium
On Tue, Jul 10, 2018 at 15:07, Sebastian Karcher <notifications@github.com> wrote:
But your style is different from the Anglia Ruskin style, right? Otherwise we could just link to the style directly rather than having extra code. And if it is different, are those differences described anywhere?

**Comment by adam3smith** [comment]
Sorry, I misread something; I thought you used Anglia Ruskin as documentation, but I see your own is already in the style, this is all good then.

**Comment by adam3smith** [comment]
Right, but where is your style documented? http://libguides.ucc.ie/DigitalArtsandHumanities is just a generic libguide. So where do you point students when you tell them how to reference? 

If you do use the same documentation as Anglia Ruskin, could you explain why you need a different style?

**Comment by rmzelle** [comment]
Just in case this isn't clear, @adam3smith is asking whether you had to make any format changes to the harvard-anglia-ruskin-university.csl style to adopt it for your university, or whether you just changed the name to "University College Cork".

If you use the same Harvard citation format as Anglia Ruskin University, we can create a much simpler CSL style for University College Cork that simply inherits its format from the Anglia Ruskin University CSL style. (that would look something like https://github.com/citation-style-language/styles/blob/master/dependent/nature-biotechnology.csl)

**Comment by shawnday** [comment]
Thanks, Rintze, That is exactly what we need to do. Sorry to have created this long thread when I should have been aware of the simpler inheritance. That is exactly it. Thanks, Shawn


~~ day.shawn@gmail.com ~~ @iridium
On Wed, Jul 11, 2018 at 4:59, Rintze M. Zelle <notifications@github.com> wrote:
Just in case this isn't clear, @adam3smith [https://github.com/adam3smith] is asking whether you had to make any format changes to the harvard-anglia-ruskin-university.csl style to adopt it for your university, or whether you just changed the name to "University College Cork".

If you use the same Harvard citation format as Anglia Ruskin University, we can create a much simpler CSL style for University College Cork that simply inherits its format from the Anglia Ruskin University CSL style. (that would look something like https://github.com/citation-style-language/styles/blob/master/dependent/nature-biotechnology.csl [https://github.com/citation-style-language/styles/blob/master/dependent/nature-biotechnology.csl] )

**Comment by rmzelle** [comment]
No worries. We can prepare this 'dependent' style for you.

I'm going to repeat @adam3smith's question, though: how do your students know what citation format to use? Is there any webpage (e.g. within http://libguides.ucc.ie/DigitalArtsandHumanities) or print material that tells the students to use the format used by Anglia Ruskin University? We always try to link to such documentation in our styles, so we can later trace down whether our citation formats are correct.

**Comment by shawnday** [comment]
Dear Rintze, Our instructions asking students to utilise Harvard Referencing as well as providing a style guide is available on our Digital Arts and Humanities website at: https://uccdh.com/referencing-styles-in-digital-arts-humanities/ It provides links to both the style guide (containing referencing instructions and a set of links as a downloadable PDF) and also links to our own Library’s website further making the connection to the use of Anglia Ruskin’s variant. I hope that this is the information that you link to. As always, Thanks for this, Shawn


~~ day.shawn@gmail.com ~~ @iridium
On Thu, Jul 12, 2018 at 17:42, Rintze M. Zelle <notifications@github.com> wrote:
No worries. We can prepare this 'dependent' style for you.

I'm going to repeat @adam3smith [https://github.com/adam3smith] 's question, though: how do your students know what citation format to use? Is there any webpage (e.g. within http://libguides.ucc.ie/DigitalArtsandHumanities [http://libguides.ucc.ie/DigitalArtsandHumanities] ) or print material that tells the students to use the format used by Anglia Ruskin University? We always try to link to such documentation in our styles, so we can later trace down whether our citation formats are correct.

**Comment by rmzelle** [comment]
@shawnday, perfect, that's just what we needed. I converted the style into a dependent one and put it into our style repository.

**Comment by shawnday** [comment]
@rmzelle @adam3smith Thanks again for all your help.

**Pull request merged**
