### PR TITLE
Create instituto-de-pesquisas-tecnologicas-ipt.csl

### PR DESCRIPTION
**Pull request by samuelbarsanelli**
Standard for citations and references used by the Institute for Technological Research of the State of Sao Paulo, Brazil – IPT (www.ipt.br/en), in accordance with the Brazilian Association of Technical Standards – ABNT NBR 6023: 2000.

### CODE REVIEW

**Comment by rmzelle** [comment]
@samuelbarsanelli, thanks for contributing!

Could you update your pull request by using the edit/pencil icon at https://github.com/samuelbarsanelli/styles/blob/patch-1/instituto-de-pesquisas-tecnologicas-ipt.csl, and make the following changes?:

- remove the "IPT" abbreviation from the title and style ID
- add the style language to the title (`(Portuguese - Brazil)`)
- add a "template" link to the CSL style you based this on one
- instead of the current "documentation" link, could you attach the file from your OneDrive to this issue?  (see https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) If your institution doesn't describe this citation format online, just use a link to the institution home page as "documentation" link.

https://github.com/citation-style-language/styles/wiki/Style-Requirements provides more guidance on each of these issues.

**Comment by samuelbarsanelli** [comment]
Hi Rintze Zelle,
Thanks for your comments. I'll update it next week, I'm out of the office right now.
About the template link, I started from zero actually, because I happened to find all other similar csl files way too heavy, with unnecessary macros. Is it a problem?
Thanks!
Samuel
Date: Sun, 15 Nov 2015 17:18:40 -0800

**Comment by rmzelle** [comment]
> About the template link, I started from zero actually, because I happened to find all other similar csl files way too heavy, with unnecessary macros. Is it a problem?

No, that's fine. We just ask because most styles are adaptations from other styles, and we like to keep track which styles were derived from each other. But if you started from scratch there is no need for a "template" link.

**Comment by samuelbarsanelli** [comment]
[IPT_CSL_Documentation.pdf](https://github.com/citation-style-language/styles/files/43847/IPT_CSL_Documentation.pdf)

**Comment by samuelbarsanelli** [comment]
@rmzelle, Travis test found some troubles on my request, but it happened to be the 'id' and 'self-link' from which I supressed the term 'ipt'.

**Comment by rmzelle** [comment]
Travis complains because the file name still needs updating (from "instituto-de-pesquisas-tecnologicas-ipt.csl" to "instituto-de-pesquisas-tecnologicas.csl"). See https://help.github.com/articles/renaming-a-file/ for instructions.

**Comment by rmzelle** [comment]
(and I see I didn't mention before that you had to do this, so sorry for that)

**Comment by samuelbarsanelli** [comment]
No problem at all @rmzelle. It's done! Hope it works good now...

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
