### PR TITLE
Create Citation-IsoGFX.cls

### PR DESCRIPTION
**Pull request by isogfx**
Hi Dear,
Changes in display of batch reference numbers and changes in the display of group referrals have been made.
[1]-[2]-[3]  --> [1-3]
[1],[4].[9] --> [1, 4, 9]
Thanks.
Have Good Time...

### CODE REVIEW

**Comment by rmzelle** [comment]
@isogfx, is this a personal preference? Our IEEE citation style follows the IEEE style guide, which specifies the format `as mentioned earlier [2], [4]–[7 ], [9];`. See page 5 at https://www.ieee.org/content/dam/ieee-org/ieee/web/org/conferences/style_references_manual.pdf.

**Comment by isogfx** [comment]
This Style working in Mendeley correctly!

**Comment by rmzelle** [comment]
@isogfx, don't worry about the test failures for now.

I would like to point out that we only accept citation styles into this repository if they're based on existing style guides for e.g. journals or institutions. If you modified the standard IEEE style according to personal preference, we won't accept your style. See also https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles. Can you clarify for us what kind of style this is?

**Comment by isogfx** [comment]
> 
> 
> @isogfx, don't worry about the test failures for now.
> 
> I would like to point out that we only accept citation styles into this repository if they're based on existing style guides for e.g. journals or institutions. If you modified the standard IEEE style according to personal preference, we won't accept your style. See also https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles. Can you clarify for us what kind of style this is?

This style runs at major universities in the Middle East of Iran and Saudi Arabia

**Comment by isogfx** [comment]
> 
> 
> worried There are some issues with your submission. Please check the [test report](https://travis-ci.org/citation-style-language/styles/builds/487679621) for details.

I provided this style to the engineering students of the universities, which they do not have to manually edit the reference numbers, in Mendley's software.

**Comment by rmzelle** [comment]
> In writing theses, this style is being implemented at major universities in the Middle East of Iran and Saudi Arabia.

Do you know if any of these universities have an online style guide that specifies this particular format?

**Pull request closed without merging**
