### PR TITLE
Create czech-journal-of-international-relations.csl

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/102914/style-request-czech-journal-of-international-relations#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
Year should be in parentheses -- notice the weird `(eds., 2009)` as per the author guidelines, which I think you can only do by splitting the parentheses between two elements in a way we usually don't like to.

Also, the publication the editor links to has `et-al-min="4" et-al-use-first="3"` in the bibliography.

**Comment by POBrien333** [comment]
Thanks for reviewing.
Is that weird parenthesis structure even possible? Not even with testing for `editor` and making it conditional.

**Comment by adam3smith** [comment]
So I was thinking along the lines of this
For the year:

```
<if variable="author">
<date variable ="issued" date-parts="year" form="numeric" prefix="(" suffix=")"/>
</if>
<else-if variable="editor">
<date variable ="issued" date-parts="year" form="numeric" suffix=")"/>
</else-if>
<else>
<date variable ="issued" date-parts="year" form="numeric" prefix="(" suffix=")"/>
</else>
```

and then for the author macro

```
    <names variable="author">
      <name delimiter=" &#8211; " delimiter-precedes-last="never" name-as-sort-order="all"/>
      <label form="short" prefix=" (" suffix=", "/>
```

(I'm OK if you don't want to deal with this, I'm more curious to see if we can actually get this right)

**Comment by POBrien333** [comment]
Sorry for keeping you wait. First was avoiding it and then had a surgery this week.
I think this actually works. Have a look :)

**Comment by adam3smith** [comment]
Excellent -- I hope things are well!

**Pull request merged**
