### PR TITLE
ISO formatted dates in Swedish Oxford citation style

### PR DESCRIPTION
**Pull request by Ambrosiani**
Changing date formatting to year-month-day with leading zeros.

### CODE REVIEW

**Comment by Ambrosiani** [comment]
ping @SagaNy91 – thoughts on this minor change?

**Review by SagaNy91 — COMMENTED** [review]
The changes in "Quoted" work well, the form is 2022-01-03. I didn't know about the "numeric-leading-zeros" form. However, for magazine articles/newspaper articles and the other types listed besides posts, it is supposed to look like this: 1/2 2022 (it is February 1 2022).  In these cases it should not include "0" before the day or the month. <- I know that it will probably not look good when referencing a blog post (or similar) in another language than Swedish. But since I don't want to lock the style to only Swedish, I think it is okay. I can update my pull request

**Comment by Ambrosiani** [comment]
ah ok, thx. Not an expert on Oxfort. Reverting "quoted" to the original. I added leading zeros to the Södertörn Harvard styles as well (although that should probably be another pull request)

**Comment by SagaNy91** [comment]
> ah ok, thx. Not an expert on Oxford. Reverting "quoted" to the original. I added leading zeros to the Södertörn Harvard styles as well (although that should probably be another pull request)

Thank you. I am not the author of the Harvard styles though, so I can't speak for them.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
