### PR TITLE
New CSL for Tesis Magister Sekolah Pascasarjana ITB

### PR DESCRIPTION
**Pull request by ceefour**
Based on guidelines in http://www.sps.itb.ac.id/in/pedoman-tesis-dan-disertasi/
Modified from APA 6th Edition

### CODE REVIEW

**Comment by rmzelle** [comment]
@ceefour, could you check https://github.com/citation-style-language/styles/wiki/Style-Requirements and update your style as necessary? In particular points 3 ("default-locale") and 8 ("template" link).

The file name and title also need to be adjusted. We try to avoid acronyms in titles, and the institution always goes first. So maybe "Institut Teknologi Bandung - Tesis Magister" and "institut-teknologi-bandung-tesis-magister.csl" (the style ID and "self" link would have to be changed as well to match the latter).

**Comment by ceefour** [comment]
Note to self: please also make the bibliography justified as per ITB master's requirements

**Comment by rmzelle** [comment]
Closing because of inactivity. @ceefour, if you get back to us we can just reopen this pull request.

**Comment by ceefour** [comment]
@rmzelle Please reopen, I've fixed it in the recent commit: https://github.com/ceefour/styles/commit/2c33389780bc34db9b32c8b5a5b1587eb9f9de48

**Comment by ceefour** [comment]
@adam3smith @rmzelle Thank you :) let me know if this is acceptable or there is more correction needed

**Comment by asetijadi** [comment]
Good job @ceefour :) :+1:

**Comment by adam3smith** [comment]
Looks good to me. Leaving to @rmzelle for final review&merge

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
