### PR TITLE
Create associacao-brasileira-de-normas-tecnicas-eceme.csl

### PR DESCRIPTION
**Pull request by trekcomet**
atende aos padrões estabelecido na ME-253 da Escola de Comando e Estado-Maior do Exército Brasileiro

### CODE REVIEW

**Comment by rmzelle** [comment]
@adam3smith, can you take this one? Validation fails because of a file name issue, although the style itself validates.

**Comment by trekcomet** [comment]
Dear Adam, because the end of the year, i didn't make a review my code.
Tomorow, i'll correct the failure.
Thx for the warning, merry christmas, or hannukah and happy new year
Haroldo
Em 23/12/2015 15:58, "Rintze M. Zelle" <notifications@github.com> escreveu:

**Comment by adam3smith** [comment]
No worries -- see the instructions above on how to update your pull request and let us know if you have any questions. Feliz Natal!

**Comment by rmzelle** [comment]
:christmas_tree: :santa: :snowman: :snowflake: 

@trekcomet, could you make the following changes?

* change the title to `<title>Associação Brasileira de Normas Técnicas - Escola de Comando e Estado-Maior do Exército (Portuguese - Brasil)</title>`
* change the style ID and "self" link to "associacao-brasileira-de-normas-tecnicas-eceme", and the style file name to "associacao-brasileira-de-normas-tecnicas-eceme.csl" (for instructions on renaming files, see https://help.github.com/articles/renaming-a-file/)

We'd also appreciate it if you could neatly indent the style with 2-spaces per level. You can use http://formatter.citationstyles.org/ to easily get a correctly indented file.

**Comment by trekcomet** [comment]
sorry everyone for my slowlyness.
All changes done and the file reformated into csl style formatter

**Comment by adam3smith** [comment]
Thank you and happy new year!

**Comment by trekcomet** [comment]
Adam thx and sorry again for the late. happy new year too

**Comment by rmzelle** [comment]
Thanks!

(I just changed "Brasil" in the title to "Brazil", since we use English country names: https://github.com/citation-style-language/styles/commit/3de81d53000ac03fcf62233990872485d819a7c7)

**Comment by rmzelle** [comment]
@trekcomet, I forgot to ask, but do you know if there is a copy online of the style guide? (I guess that would be the "ME 21-253" document?)

We try to have a "documentation" link for every style in our repository. A link to a catalog entry of the print version would help as well, if there is no online version.

**Pull request merged**
