### PR TITLE
Update and rename emerald-harvard.csl to emerald-harvard-2.csl

### PR DESCRIPTION
**Pull request by sgusmaob**
Italicized "et al." for inline citations.

### CODE REVIEW

**Comment by rmzelle** [comment]
> Italicized "et al." for inline citations.

Thanks. Is there a reason why you changed the file name of this style? Are there two versions in use? (one with italics, and one without)

If you're submitting a correction, we'd just update the existing style.

**Comment by sgusmaob** [comment]
I was not sure if the original file should be kept. However, Emerald publications are required to have the “et al.” italicized, so, I think only one file should be used.

 

Thank you.

**Comment by rmzelle** [comment]
Okay, thanks. Yes, they clearly require italicized "et al." now, so we should just update the existing style. Thanks!

**Comment by sgusmaob** [comment]
Is it this citation style already updated?

 

Thank you,

 

Sara

**Comment by rmzelle** [comment]
> Is it this citation style already updated?

@sgusmaob, yes, when a pull request is merged your contribution is accepted into the style repository.

**Pull request merged**
