### PR TITLE
Update isnad-dipnotlu.csl

### PR DESCRIPTION
**Pull request by osmndrmz**
Update book-with editor(s) and standart item types.

### CODE REVIEW

**Comment by bwiernik** [comment]
CSL 1.0.2 now has a proper `standard` type, so please use that instead

**Comment by bwiernik** [comment]
Hi @osmndrmz, as noted at https://github.com/citation-style-language/styles/pull/5910#issuecomment-1102371470, please do not include the workaround with `book`.

**Comment by adam3smith** [comment]
@bwiernik -- I'd be OK leaving the workaround in here given how poorly supported standard is in existing implementations. I've moved the test for the proper item type above it so it takes precedent. OK to merge after resolving conflicts?

**Comment by bwiernik** [comment]
Sure

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
