### PR TITLE
[DO NOT MERGE] Sheldon test

### PR DESCRIPTION
**Pull request by retorquere**
Get the new shel-gem, trigger a report.

### CODE REVIEW

**Comment by retorquere** [comment]
@adam3smith so this is better but still not what I would have expected.

**Comment by retorquere** [comment]
Strange... when I render this locally, I still get `[,]` as the in-text citations. This can't be right. @adam3smith?

**Comment by retorquere** [comment]
Is it possible that this style has no in-text citations? Is it a footnote style?

**Comment by adam3smith** [comment]
Ah, interesting -- it's a numeric style and `citation-number` is generated dynamically by citeprocs and that doesn't seem to work here. We could try to just add citation-number in the JSON hardcoded. Very few cases where this would matter for our purposes.

**Comment by retorquere** [comment]
*phew* I thought I had screwed something else up.

**Comment by retorquere** [comment]
Aw yeah.

**Pull request closed without merging**
