### PR TITLE
Create toxicological-sciences.csl

### PR DESCRIPTION
**Pull request by DataSciBurgoon**
CSL for the journal Toxicological Sciences.

### CODE REVIEW

**Comment by rmzelle** [comment]
Did you base this off another CSL style?

**Comment by DataSciBurgoon** [comment]
Yeah, bioinformatics.

**Comment by rmzelle** [comment]
Could you add a "template" link, then, as described at https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link ? Otherwise the style looks good.

**Comment by DataSciBurgoon** [comment]
Will do. Thanks!

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
