### PR TITLE
Animal Welfare

### PR DESCRIPTION
**Pull request by sjurdur**
Citation style adapted from Ecology,

One edit I didnt manage to do, was to change the label of editiors in plural to exclude the fullstop. Can I get help doing this, before it gets put up?

### CODE REVIEW

**Comment by rmzelle** [comment]
Please use the pencil (edit) icon at https://github.com/sjurdur/styles/blob/patch-1/animalwelfare.csl and make the following changes?:

* change the title to `<title>Animal Welfare</title>`
* change the style ID to `<id>http://www.zotero.org/styles/animal-welfare</id>` (same for the "self" link)
* change the style file name to "animal-welfare.csl" (see https://help.github.com/articles/renaming-a-file/ )
* change the "documentation" link to "http://www.ufaw.org.uk/instructions-authors.php"
* please remove me as author of the style
* since this style is for a UK journal, please change `default-locale="en-US"` to `default-locale="en-GB"`

**Comment by adam3smith** [comment]
I'll help out with the eds issue tomorrow

**Comment by rmzelle** [comment]
> One edit I didnt manage to do, was to change the label of editors in plural to exclude the fullstop

Try adding `strip-periods="true"` to any `<label/>` element found within an `<name/>` element. E.g. change `<label form="short" prefix=", " text-case="capitalize-first"/>` (L38) to `<label form="short" prefix=", " strip-periods="true" text-case="capitalize-first"/>`.

**Comment by adam3smith** [comment]
Nope, that'll also remove them from the singular. Only way is to redefine
the term

**Comment by rmzelle** [comment]
One of the examples is:

```
Meyer-Holzapfel M 1968 Abnormal behavior in zoo animals. In: Fox MW (ed) Abnormal Behavior in Animals pp 24-38. WB Saunders: Philadelphia, USA
```

so perhaps the period needs to be gone from both?

**Comment by sjurdur** [comment]
yes, apologies, I hadnt realised the there wasnt a fullstop in singular either. So I assume I can follow your suggestion above?

**Comment by rmzelle** [comment]
I also meant to link to https://github.com/citation-style-language/styles/wiki/Style-Requirements, but it seemed like you figured out most of the stuff.

The style just needs a "self" link. Use the pencil icon at https://github.com/sjurdur/styles/blob/patch-1/animal-welfare.csl, and add `<link href="http://www.zotero.org/styles/animal-welfare" rel="self"/>` above the "documentation" link.

**Comment by sjurdur** [comment]
ok, I have done this. Why do I reference to zotero when I made the changes in mendeley? Does this make any difference? Also when I try now to edit the citation style in Mendeleys editor, it doesnt allow me to access it. Is this because we are working on it in github or something??

**Comment by rmzelle** [comment]
`prefix=", "strip-periods="true"`

There has to be a space before "strip-periods". The "event" macro also needs to be deleted, since we don't allow unused macros.

> Why do I reference to zotero when I made the changes in mendeley?

It's just the result of the fact that the CSL styles repo started its life on Zotero's servers, a few years back. Eventually we'll use identifiers without the Zotero domain, but it's not a trivial change, so we're stuck with it for now.

**Comment by sjurdur** [comment]
i removed the " in front of strip periods on line 39, was that correct?

this is really interesting. Getting a flavour of programming

**Comment by sjurdur** [comment]
sorry for being daft, I changed it to what I think you meant.

**Comment by rmzelle** [comment]
Great. Some final touches: can you delete the line `<title-short>Animal Welfare </title-short>` (since it's the same as the title, it's redundant), and delete the lines

```
    <contributor>
      <name></name>
      <uri></uri>
    </contributor>
```
?

**Comment by sjurdur** [comment]
done

**Comment by sjurdur** [comment]
thanks very much for your help! I'll submit a few other small journal styles soon

**Comment by adam3smith** [comment]
Yes, that'll work then

**Comment by rmzelle** [comment]
Thanks! :trophy:

**Comment by sjurdur** [comment]
So in theory this should mean that when I look up animal welfare in "get more styles" in mendeley it should show up?

Not sure if it's a mendeley issue or with my computer, but i've not been able to access the citation style database this afternoon.

**Comment by rmzelle** [comment]
Mendeley pulls down our styles only once a day, so you might have to wait a little.

**Comment by zuphilip** [comment]
@sjurdur In the meantime, you can enter the URL directly in "Get more styles", which would be https://www.zotero.org/styles/animal-welfare

**Comment by sjurdur** [comment]
I check the citation style and particularly the book section format. (eds.) still has a full stop. Also I noticed something I had missed out, and that was that the number of book edition should not be in bold

**Comment by rmzelle** [comment]
You can make further edits by using the pencil icon at https://github.com/citation-style-language/styles/blob/master/animal-welfare.csl.

**Comment by sjurdur** [comment]
Do I simply erase the line of code that contains: <text macro="edition" font-weight="bold"/>

but also I mentioned that the supression of "." didnt apparently work. any suggestions to what I can do?

**Comment by rmzelle** [comment]
If you want the edition of the book not in bold, just remove ` font-weight="bold"`. And try changing `<label form="short" prefix=" (" suffix=")"/>` to `<label form="short" strip-periods="true" prefix=" (" suffix=")"/>` (on your own computer, if you can, before submitting the change).

**Comment by sjurdur** [comment]
tried, and failed. I have inserted the strip-period section into every label form line, and it still gives me (eds.)

**Comment by rmzelle** [comment]
With this item: https://www.zotero.org/groups/csl_styles_development/items/itemKey/RUBNRZRI, I get 

```
Reisman K 1974 Contrapuntal conversations in an Antiguan village. In Bauman R and Sherzer J (eds) Explorations in the Ethnography of Speaking pp. 110–124. Cambridge University Press, London ; New York
```

when I set "strip-periods" to "true" in the "container-contributors" macro:

```
  <macro name="container-contributors">
    <choose>
      <if type="chapter paper-conference" match="any">
        <text term="in" text-case="capitalize-first" font-style="normal" suffix=" "/>
        <names variable="editor translator" delimiter=", ">
          <name and="text" initialize-with="" name-as-sort-order="all" sort-separator=" "/>
          <label form="short" strip-periods="true" prefix=" (" suffix=")"/>
        </names>
      </if>
    </choose>
  </macro>
```

**Comment by sjurdur** [comment]
strange... I get:

Anderson A and Cosgrove P 2002 Northern Fulmar (Fulmar) Fulmarus glacialis. In Wernham C, Toms M, Marchant J, Clark J, Siriwardena G, and Baillie SR (eds.) The Migration Atlas pp. 117–119, 1st edition.. Christopher Helm Publishers Ltd, London

**Comment by rmzelle** [comment]
Can you try installing this version? https://gist.githubusercontent.com/rmzelle/7547fe78719fb0009ba2/raw/7a6d431317b257cc75b1b482726f3b557d1e67cd/animal-welfare-test.csl

**Comment by sjurdur** [comment]
that works! I assume there is an easy way of replacing what you have created with the one that is already there?

Also I apologise for this, but I noticed that I have forgotten to have a close look at the citation too. the et al should be in italics and there is no full stop after et al. 

Could you help me change this in the code, as I'm unable to change et al to italics in the mendeley editor?

**Comment by sjurdur** [comment]
argh! I'm sorry, but I can also see that when the reference is a book, the "1st edition" is in bold - it shouldn't be, Edition should be capitalised first letter, and no fullstop should be at the end.

**Comment by sjurdur** [comment]
should I redo all the formatting I can in mendeley citation style editor, then follow all these points above to adapt it appropriately? Is it then possible to remove the submitted edition?

**Comment by rmzelle** [comment]
Sorry, I meant to get back to you, but I've been a bit busy. Preferably you would always edit the current version from our repository. I think you should be able to copy and paste the contents of https://raw.githubusercontent.com/citation-style-language/styles/master/animal-welfare.csl into the Mendeley editor.

**Comment by sjurdur** [comment]
ok, so how do I re-submit and merge to the current uploaded code? 

I think I managed to make the changes but for some reason mendeley is unable to link to the server, so can confirm it on my own computer.

I have changed the et al to italics,

And I have changed a piece of code that the designate edition name as "bold" to "normal. Hope that works! 

http://csl.mendeley.com/styles/5873/animal-welfare

**Comment by rmzelle** [comment]
You should be able to create a new pull request by clicking the pencil (edit) icon at https://github.com/citation-style-language/styles/blob/master/animal-welfare.csl. You can then copy and paste in your new version.

**Pull request merged**
