### PR TITLE
Revert all Cell Journals to Cell style

### PR DESCRIPTION
**Pull request by adam3smith**
Note for later: Molecular Plant needs a separate style

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle -- pretty sure this is correct with article:
http://www.cell.com/ajhg/authors

**Comment by adam3smith** [comment]
@rmzelle -- I just wanted to get your OK before changing the AJHG title and ID before fixing this.

**Comment by rmzelle** [comment]
Yes. (so you'll delete american-journal-of-human-genetics.csl, right?)

Is Chemistry & Biology new?

**Comment by rmzelle** [comment]
> Is Chemistry & Biology new?

http://www.sciencedirect.com/science/journal/10745521:

Chemistry & Biology
Continued as Cell Chemical Biology;

**Comment by adam3smith** [comment]
OK, I'll investigate Cell Chemical Biology and add it as appropriate and remove C&B

**Comment by rmzelle** [comment]
(I just updated my comment above; our metadata needs updating here)

**Comment by rmzelle** [comment]
Otherwise this looks good to me. Will you prepare a PR to the journals repo as well? (or just commit directly)

**Comment by adam3smith** [comment]
oh had forgotten to actually make the PR on journals; the branch was already there: https://github.com/citation-style-language/journals/pull/13

**Comment by adam3smith** [comment]
thanks

**Pull request merged**
