### PR TITLE
Create fatigue-and-fracture-of-engineering-materials-and-structure.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/70715/style-request-fatigue-fracture-of-engineering-materials-structures#latest

Guidelines vs various papers. unclear what the style is...

### CODE REVIEW

**Comment by adam3smith** [comment]
yeah, as you note they publish in a completely different style, but let's go with this & see what happens I suppose? Sorry for letting this sit

**Comment by rmzelle** [comment]
(fatigue-and-fracture-of-engineering-materials-and-structure.csl should use "structures" (plural), will fix)

**Comment by rmzelle** [comment]
(fixed in https://github.com/citation-style-language/styles/commit/bcf94d2e3046647d5cc58229c44945b67ae6c090; didn't bother with renamed-styles.json since the style has been live for such a short time)

**Comment by rmzelle** [comment]
(also "medicine" as category? :P)

**Comment by POBrien333** [comment]
Thanks for fixing these issues! Much appreciated.

**Pull request merged**
