### PR TITLE
Create jurisprudence.csl

### PR DESCRIPTION
**Pull request by OTristanF**
Suitable for Jurisprudence – a journal published by Charles University, Faculty of Law.

### CODE REVIEW

**Comment by OTristanF** [comment]
Isn't the automatic "re-indent" commit (92e3331) wrong? It replaced `&gt;` with `>`.

**Comment by bwiernik** [comment]
@retorquere

**Comment by retorquere** [comment]
The re-indenter does more than re-indent, it also normalizes entities, it has always done this. It isn't necessary to write `&gt;` inside attribute values.

**Comment by bwiernik** [comment]
Thanks, I had thought that >< needed to be escaped

**Comment by retorquere** [comment]
Outside attribute values these do need to be escaped.

**Comment by OTristanF** [comment]
Should I change `&lt;` to `<` then?

**Comment by retorquere** [comment]
If you don't, the re-indenter will (but only in attribute values)

**Comment by OTristanF** [comment]
@retorquere, the re-indenter has changed just `&gt;` to `>`, without changing the corresponding `&lt;` to `<`. It is quite strange.

**Comment by retorquere** [comment]
@rmzelle, any idea? I haven't changed the re-indenter, so this will be long-standing behavior.

**Comment by bwiernik** [comment]
I don't see anywhere where `&gt;` is mentioned in the formatter library. So is that coming from the imported XML Parser?

**Comment by retorquere** [comment]
That's my guess, but that'd be pretty strange for a widely used domparser.

**Comment by rmzelle** [comment]
I just ran the original style submission through https://formatter.citationstyles.org/ (in Firefox), and it doesn't touch either `&gt;` or `&lt;`.

**Comment by retorquere** [comment]
Damn, that means it's an issue in the `xmldom` package. I'll see if I can create an isolated testcase and submit it there.

**Comment by bwiernik** [comment]
Personally, I think it's less confusing to leave the entities in both attributes and values, rather than changing them in the one place where they aren't needed

**Comment by retorquere** [comment]
It's not something I actively do. I have an isolated testcase for xmldom, it's in their serializer.

**Comment by rmzelle** [comment]
Maybe related to https://github.com/xmldom/xmldom/issues/339 ?

**Comment by retorquere** [comment]
Yeah, they're deeming it desirable behavior (https://github.com/xmldom/xmldom/issues/198). I'll see if this can be either worked around or made configurable.

**Comment by retorquere** [comment]
Blegh, it's not in a place where I can monkey-patch the problem away. But according to the reasoning in https://www.w3.org/TR/xml/#CleanAttrVals, they are right:

> Well-formedness constraint: No < in Attribute Values

**Comment by bwiernik** [comment]
Ah, so let's just let it be then? Or post hoc edit ">" back to "&gt;"?

**Comment by retorquere** [comment]
Not the latter, I'd say. Without a proper xml serializer we'd have to resort to regex hacks. I'd sooner patch the xml serializer before applying it.

**Comment by bwiernik** [comment]
@adam3smith thoughts?

**Comment by adam3smith** [comment]
I don't see any reason we shouldn't just leave > alone, yes.

**Pull request merged**
