### PR TITLE
Create DUT-Library-Harvard.csl

### PR DESCRIPTION
**Pull request by prash0929**
Good day. Our Subject Librarian at the Durban University of Technology Library have edited a citation style for Mendeley and would like this style to appear in the style repository at: https://csl.mendeley.com/about/ so that our users can use this style. The url for the style is: http://csl.mendeley.com/styles/643376651/DUT-Library-Harvard

### CODE REVIEW

**Comment by prash0929** [comment]
Good day Sebastian

Apologies for the late reply, I have been on examination leave.

The Post Grad Librarians at our University edited an existing style (University of South Africa) to suit the style requirements of our university.
The style they created is not described/documented anywhere.

Thank You

Regards
Prashanth

**Comment by adam3smith** [comment]
Thanks! But are the university style required available somewhere or could be uploaded here? We have a pretty firm policy against accepting styles without available guidelines that we can check against

**Comment by prash0929** [comment]
Hi Sebastian

I have attached a copy of our University's referencing style guide.
It is also available at our library website: https://library.dut.ac.za/wp-content/uploads/2017/08/Referencing-Guide.pdf

Thank you

Regards
Prashanth

**Comment by prash0929** [comment]
Good day Sebastian

Has there been any progress, regarding our citation style

Thank you

Regards
Prashanth


From: Prashanth Sivsaran
Sent: Thursday, 18 November 2021 09:28
To: citation-style-language/styles ***@***.***>; citation-style-language/styles ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [citation-style-language/styles] Create DUT-Library-Harvard.csl (PR #5694)

Hi Sebastian

I have attached a copy of our University's referencing style guide.
It is also available at our library website: https://library.dut.ac.za/wp-content/uploads/2017/08/Referencing-Guide.pdf

Thank you

Regards
Prashanth

**Comment by adam3smith** [comment]
Hi, I can probably get to this myself at some point, but your style currently fails the automated tests and would need to be fixed in order to be accepted

**Comment by prash0929** [comment]
Hi Sebastian

Our developer hepled fix the 3 errors yesterday. I ran it through the validator and it passes now - see attached.

Thank you

Regards
Prashanth

**Comment by adam3smith** [comment]
You'll want to update the pull request (email attachments don't get sent via GitHub at all)

**Comment by prash0929** [comment]
Thanks, will do

**Comment by adam3smith** [comment]
Superseded by #5762

**Pull request closed without merging**
