### PR TITLE
Create bulletin-archeologique-des-ecoles-francaises-a-l-etranger.csl

### PR DESCRIPTION
**Pull request by NMonteix**

### CODE REVIEW

**Comment by adam3smith** [comment]
So, is the only function of this to set the style to French? Why couldn't users just do this in the app?

**Comment by NMonteix** [comment]
No, it is a dependent style for a different review. Most users of this 
style would not look for the master-style

Le 11/11/2021 à 17:00, Sebastian Karcher a écrit :

**Comment by NMonteix** [comment]
Journal, not review...


Le 11/11/2021 à 17:00, Sebastian Karcher a écrit :

**Comment by adam3smith** [comment]
Ah sorry, misread

**Comment by NMonteix** [comment]
Thanks!

Le 11/11/2021 à 17:11, Sebastian Karcher a écrit :

**Pull request merged**
