### PR TITLE
Create handbook-of-clinical-neurology.csl

### PR DESCRIPTION
**Pull request by damnation333**
via https://forums.zotero.org/discussion/65028/style-request-clinical-handbook-of-neurology
Waiting for guidelines to be sent and clarifcation on et-al rules.
[HCN_Contributor_Instructions_EMSS .docx](https://github.com/citation-style-language/styles/files/1008518/HCN_Contributor_Instructions_EMSS.docx)

### CODE REVIEW

**Comment by adam3smith** [comment]
Let's also check on the title. While there is a Handbook of Clinical Neurology, the Zotero thread is the first thing that comes up searching for "Clinical Neurology Handbook". I couldn't find a guide for authors for the former, either.

**Comment by damnation333** [comment]
@adam3smith 
Been sent the documentation now, added that and changed the name accordingly.

**Comment by rmzelle** [comment]
Looks good to me, but I would add a second documentation link to the handbook's website (e.g. http://www.sciencedirect.com/science/journal/00729752 or https://www.elsevier.com/books/book-series/handbook-of-clinical-neurology)

@damnation333, did you ever figure out what website user nohxtk1 was referring to at https://forums.zotero.org/discussion/comment/273004/#Comment_273004? ("Here's are the instructions from the webpage")

Ideally we'd link to that.

**Comment by damnation333** [comment]
@rmzelle 
I doubt he/she meant Webpage. if you look at the .docx I attached in this PR you'll see the reference style is on page 3 as he/she talks about in the thread.

**Comment by rmzelle** [comment]
Okay, thanks. It might be worth asking to make sure these guidelines are really not publicly available.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
