### PR TITLE
Updated modern-language-association.csl

### LINKED ISSUE #3675: MLA Support for Motion Picture CSL Director Variable
Example MLA 8 Citation of Film (http://columbiacollege-ca.libguides.com/mla/videos):

The Usual Suspects. Directed by Bryan Singer. Performances by Kevin Spacey, Gabriel Byrne, Chazz Palminteri, Stephen Baldwin, and Benicio Del Toro. Polygram, 1995. 

CSL Output:   The Usual Suspects. Polygram, 1995.

Possible new code blocks:

```
<macro name="director">
    <names variable="author" prefix="Directed by "/>
  </macro>
```
```
          <group delimiter=" ">
            <text macro="author"/>
            <text macro="year-date" prefix="(" suffix=")"/>
            <group delimiter=" " suffix=",">
              <text macro="title"/>
              <text macro="director"/> 
              <text macro="translator" prefix="(" suffix=")"/>
            </group>
            <text macro="container-prefix"/>
            <group delimiter=", ">
              <text macro="editor"/>
              <text variable="container-title" font-style="italic"/>
              <text variable="collection-title"/>
              <text variable="genre"/>
              <text macro="edition"/>
              <text macro="publisher"/>
              <text macro="locators"/>
              <text macro="published-date"/>
              <text macro="pages"/>
            </group>
            <text macro="access"/>
          </group>
```

### PR DESCRIPTION
**Pull request by avimshah**
Add support for motion picture director CSL name-variable to MLA 8th edition style. Closes #3675.

Example Output: _Ready Player One_. Directed by Steven Spielberg, Warner Bros., 2018.

### CODE REVIEW

**Comment by rmzelle** [comment]
@adam3smith, do you mind checking this? (do you have a copy of the MLA styleguide?)

It might make more sense to fold the "director" code into the "other-contributors" macro, since that seems to be how MLA structures its citation at the highest level (see https://style.mla.org/works-cited-a-quick-guide/).

**Comment by rmzelle** [comment]
@adam3smith, haven't checked the style guide, but this is how I would add director support. Please merge if it looks okay.

**Comment by adam3smith** [comment]
Thanks -- I have the manual in the office, will check & merge or adjust on Tuesday

**Comment by avimshah** [comment]
@adam3smith Does it fit the manual specifications? I do not have a copy. If it is all good, I can go ahead and close #3675.

**Comment by adam3smith** [comment]
Really sorry this took so long. Part of this was the MLA's film citation rules are quite confusing -- directors etc. can _also_ be listed in the author position, but for generic citations, this is the right format.

**Comment by avimshah** [comment]
Yes, I believe if you want to emphasize a director or performer you place it in the author position. Thank you for checking the specifications in the MLA Handbook.

**Pull request merged**
