### PR TITLE
Update harvard-cardiff-university.csl

### PR DESCRIPTION
**Pull request by YoungZoe**
Disambiguation wasn't working correctly as it should use letters after the year rather than including more names.

### CODE REVIEW

**Comment by rmzelle** [comment]
@YoungZoe, thanks. Do you know if this is discussed in the style guide somewhere?

**Comment by YoungZoe** [comment]
Yes on the first page. Guide attached.

“If you are citing different publications written by the same author in the same year, label the first
one cited with the letter ‘a’ after the year and the second ‘b’ etc. e.g. (Smith 2015a), (Smith
2015b). You will need to do the same in your list of references.”

Zoe

Book a UG lunchtime drop-in       <http://www.bit.ly/bls-drop-in>               Book a staff/PG 1-2-1<https://outlook.office365.com/owa/bit.ly/bls-121s>
      www.bit.ly/bls-drop-in                          www.bit.ly/bls-121s<http://www.bit.ly/bls-121s>

Mrs Zoe Young BSc(Hons) MSc(ECON)

Subject Librarian, School of Healthcare Sciences, Optometry and Pharmacy
Health Library
University Library Service
Cardiff University
Cochrane Building
Heath Park
Cardiff
CF14 4YU
Tel: 029 22510196
Web: www.cardiff.ac.uk<http://www.cardiff.ac.uk/>
E-mail: YoungZ@cardiff.ac.uk<mailto:YoungZ@cardiff.ac.uk>

Registered charity: no. 1136855

Winner of THE Outstanding Library Team Award 2015

Proud to hold the Customer Service Excellence Standard®

The University welcomes correspondence in Welsh or English.


Mrs Zoe Young BSc(Hons) MSc(ECON)

Llyfrgellydd Pwnc, Ysgol Gwyddorau Gofal Iechyd, Optometreg a Fferylliaeth
Llyfrgell Iechyd
Gwasanaeth Llyfrgell y Brifysgol
Prifysgol Caerdydd
Adeilad Cochrane
Parc y Mynydd Bychan
Caerdydd
CF14 4YU
Ffôn: 029 22510196
Gwefan: www.caerdydd.ac.uk<http://www.caerdydd.ac.uk/>
E-bost: YoungZ@caerdydd.ac.uk<mailto:YoungZ@caerdydd.ac.uk>

Elusen gofrestredig: rhif 1136855

Enillydd 2015 Gwobr Tîm Llyfrgell Ragorol y THE

Rydym yn falch o fod wedi ennill safon Rhagoriaeth Mewn Gwasanaethau Cwsmeriaid ®

Mae'r Brifysgol yn croesawu gohebiaeth yn Gymraeg neu'n Saesneg.

**Comment by adam3smith** [comment]
right, but your changes don't affect citations by the same author(s). They're only relevant where 
1) different authors with the same last name are cited (`add-givenname`)
2) the first author is the same but not the whole set of authors (`add-names`)

The passage you cite is silent on this as far as I can tell.

**Comment by rmzelle** [comment]
@YoungZoe, thanks for clarifying. Would it be possible for you to attach the guide to a comment here? You need to use the GitHub website for that (via simple drag and drop), email attachments aren't saved.

**Comment by YoungZoe** [comment]
[libraryguide_Citing-and-Referencing-in-the-Cardiff-University-Harvard-Style (1).pdf](https://github.com/citation-style-language/styles/files/2373976/libraryguide_Citing-and-Referencing-in-the-Cardiff-University-Harvard-Style.1.pdf)

**Comment by adam3smith** [comment]
I'll note that the passage of the guide you quote is still entirely ambiguous/silent on how citations by different author groups with the same first author should be disambiguated, or how citations by authors with the same last name but different first names should be disambiguated. I understand, though, that you're in charge of the style guide, so  we'll take your word for it (but you may want to clarify this in future editions).

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
