### PR TITLE
Create fachhochschule-vorarlberg-author-date.csl

### PR DESCRIPTION
**Pull request by damnation333**
to continue https://github.com/citation-style-language/styles/pull/1933 (and https://github.com/citation-style-language/styles/pull/1953)

Slight cleanup (locales, use of variables than text and fix quotation mark issue and made a few simple changes to match guidelines.

### CODE REVIEW

**Comment by damnation333** [comment]
Travis says:

>        expected `[[31, "Did not expect element locale there"], [31, "Element style has extra content: locale"], [2, "Expecting element locale, got style"]].empty?` to return true, got false

What's the issue here? Are you not allowed to have two locales?

**Comment by rmzelle** [comment]
Let's first fix the CSL validation: http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fdamnation333%2Fstyles%2Fb62dbed0a50c22a515b12c4908442286249dc4d6%2Ffachhochschule-vorarlberg-author-date.csl&version=1.0.1

**Comment by rmzelle** [comment]
(sometimes the validation errors on Travis are a bit unclear; our Jing-based CSL validator is usually much better at pinpointing errors)

**Comment by rmzelle** [comment]
Do you know how this version (modified from the pull requests you mention above) relates to our existing https://github.com/citation-style-language/styles/blob/master/fachhochschule-vorarlberg.csl style? Is it an update?

(cc @adam3smith, @zuphilip)

**Comment by adam3smith** [comment]
yes this should udpated&replace the other style (see discussion in #1933 )

**Comment by rmzelle** [comment]
@damnation333, if you want, you could update this pull request to do so.

(First, you can edit the existing file at https://github.com/damnation333/styles/blob/patch-56/fachhochschule-vorarlberg.csl via the edit icon. Second, you can click the trash icon at https://github.com/damnation333/styles/blob/patch-56/fachhochschule-vorarlberg-author-date.csl)

**Comment by rmzelle** [comment]
Looks like we're continuing this in #2440.

**Pull request closed without merging**
