### PR TITLE
Create nh.csl

### PR DESCRIPTION
**Pull request by nilano**
Creation

### CODE REVIEW

**Comment by adam3smith** [comment]
sorry, we generally don't accept personal styles on the repository. What's your goal in submitting this?

**Comment by nilano** [comment]
Hy

I'd like to use it in the future for Ame Publishing 
(www.ame-editions.eu), but I'm testing this "personal style" with other 
people. So I thought to put it on the repository would be suitable.

**Comment by rmzelle** [comment]
These other people are all colleagues and/or people you know personally?

The main role of the repository is to distribute styles where the style author doesn't know the people using the style. In your case, it's probably better to distribute the style yourself. Éditions de l'Ame doesn't take open submissions, does it?

**Comment by nilano** [comment]
Ok, I do understand.
It will be people I know personnally. So I should not distribute the 
style on the repository.
But I have a problem with API:

    https://api.zotero.org/groups/xxxx/items/top?start=0&limit=25&format=atom&v=1&sort=accessDate&direction=desc&content=bib&*style=nh*

I cannot use the Ame Publishing style in the API feed if it is not on 
the Repository.
How should I do?

**Comment by adam3smith** [comment]
Zotero tells us the API should be able to use custom CSL styles very soon now and I've seen @fcheslack to some related work on that recently. Faolan -- do you have an ETA for us?

**Comment by nilano** [comment]
what is an ETA?

**Comment by adam3smith** [comment]
Estimated Time of Arrival

**Comment by adam3smith** [comment]
Btw, API requests with remotely hosted versions of styles are now possible simply by specifying the URL of the style as the style parameter of the API request, ie. so something like
https://api.zotero.org/groups/xxxx/items/top?format=bib&style=https://raw.githubusercontent.com/nilano/styles/patch-1/nh.csl
Closing this.

**Pull request closed without merging**
