### PR TITLE
APA uncertain date

### PR DESCRIPTION
**Pull request by bwiernik**
Add uncertain dates to APA and also format text-case on status variables

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! Just looked over this quickly, but it looks to me like there are two large repeated code blocks. The one on line 399-416 in standard APA and on line 715-733. They're identical for uncertain + regular date and then uncertain puts [ca. ] around them and regular dates uses (). Could we pack those two in macros to reduce complexity & duplication?

**Comment by bwiernik** [comment]
Okay. The lines you pointed out weren’t the same—they were for issued versus original-date. Pieces of the style use just year for both dates (the old issued-year macro) or conditionally all the parts (the old issues and original-date macros). I didn’t see a cleaner way to handle the combining circa with year and various placements of brackets versus parentheses needs than this.

**Comment by adam3smith** [comment]
See the issued macro in vanilla apa.csl and then the change in the bibliography. Does that make sense? If so, we could do the same for original date.

**Comment by adam3smith** [comment]
Perfect; exactly what I had in mind. 

Yes, this is enough complexity for one pull request, let's please put the other issues in a new one & thanks for working on that. 

Happy to follow your lead on the DOI/URL for books & chapters, although APA does indeed appear quite clear on omitting it: http://blog.apastyle.org/apastyle/2011/02/books-and-book-chapters-what-to-cite.html

**Comment by bwiernik** [comment]
Thanks. I think I'll change to follow the DOI/URL rule and see what copyeditors at non-APA journals do.

**Pull request merged**
