### PR TITLE
Update ieee-with-url.csl

### PR DESCRIPTION
**Pull request by POBrien333**
As discussed in #6511 

- copy ieee.csl
- replace access macro with the one from ieee-with-urls.csl

Let me know if I did this right. :)

### CODE REVIEW

**Comment by adam3smith** [comment]
The missing space before "Available" is an actual issue, not just in the preview (I think you can just add that to the macro)
A bit more tricky: journal articles without URL currently end in a comma.

**Comment by adam3smith** [comment]
That doesn't fix this one, though, does it?
> A bit more tricky: journal articles without URL currently end in a comma.

**Comment by POBrien333** [comment]
It came out fine. See the conditional in lines 300-307

**Comment by adam3smith** [comment]
Ah -- we've lost the DOI somewhere along the way. That should definitely still be part of access, and then the code works. (without the DOI in access, items with a DOI but no URL -- what I was testing with -- still end in a comma)

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
