### PR TITLE
Create wirtschaftsuniversitat-wien-ivm-interdisziplinares-institut-fu…

### PR DESCRIPTION
**Pull request by georgd**
…r-verhaltenswissenschaftlich-orientiertes-management.csl

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- I cleaned the code up and changed some things that didn't align with the styleguide. Please take a quick look to make sure I didn't introduce any errors

**Comment by georgd** [comment]
@adam3smith do you need more information from me?

**Comment by georgd** [comment]
ping @adam3smith – is something still missing?

**Comment by adam3smith** [comment]
My apologies -- this somehow got left behind. Thanks for repinging me.

Have a look at this subset of changes from my last commit. This will let you see what I changed:
https://github.com/citation-style-language/styles/pull/3388/commits/42bdfb9ca89c6ab4820c1e2447e3db7e2dc6dde2

**Comment by rmzelle** [comment]
(looks good to merge from my side)

**Comment by georgd** [comment]
@adam3smith I’m sorry for being to little precise here. I didn’t mean the actual issues in the current style file but rather the method for finding such places. Is it just the usual suspects or do you read the whole xml line by line?

**Comment by rmzelle** [comment]
Thanks!

(I'll leave it to @adam3smith to explain his magic)

**Comment by adam3smith** [comment]
@georgd -- it's somewhere in between the two: I manually scan the file for anything that looks unusual, where "unusual" is just based on experience looking at a lot of these. Obviously I still miss things all the time -- there are often many plausible options for a citation style and there's no way I'd have the time to go line-by-line comparing with the style guide -- but e.g. internal inconsistencies or things that would definitely look weird I always check on.

**Comment by georgd** [comment]
Great, thank you both!

**Pull request merged**
