### PR TITLE
Create Cladistics.csl

### PR DESCRIPTION
**Pull request by vidovics**
Cladistics journal reference style. The reference style is similar to Elsevier Harvard, with italicized et al. for in-text reference. The bibliography has no italics, there is a "." at the end of the author list and the date is out of brackets. There is a "." after the journal title.

### CODE REVIEW

**Comment by rmzelle** [comment]
Do you have a version of this style without all these extra line breaks? E.g.

```
    <link href="http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN
%291096-0031/homepage/ForAuthors.html" rel="documentation"/>
```

should be

```
    <link href="http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291096-0031/homepage/ForAuthors.html" rel="documentation"/>
```

**Comment by rmzelle** [comment]
Great, thanks.

Please take a look at https://github.com/citation-style-language/styles/wiki/Style-Requirements. In particular, the style file name should become "cladistics.csl" (lowercase; see also https://help.github.com/articles/renaming-a-file/ ). In addition, `<category field="generic-base"/>` should be deleted, and the "template" link should point to the CSL style you used as a starting point (if there is one, otherwise remove it). We also would like to see the eISSN included (`<eissn>1096-0031</eissn>`).

**Comment by rmzelle** [comment]
Perfect, thanks!

**Comment by vidovics** [comment]
Thanks for your help.

**Pull request merged**
