### PR TITLE
Update acta-universitatis-agriculturae-sueciae.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/98352/small-update-needed-for-style-acta-universitatis-agriculturae-sueciae#latest

### CODE REVIEW

**Comment by POBrien333** [comment]
Not sure this is actually working. hmm...

**Comment by bwiernik** [comment]
What do you mean?

**Comment by POBrien333** [comment]
It's not working as imagined. Can you test it out just to double check?

**Comment by bwiernik** [comment]
What is looking wrong?

**Comment by POBrien333** [comment]
I found the source of the problem.
I've implemented the type "software" which is a new type as of CSL1.0.2, but obviously, Zotero is still on 1.0.1 where "software" is mapped to just "book".

**Pull request merged**
