### PR TITLE
Create dionne.csl

### PR DESCRIPTION
**Pull request by LinoTremblay**
Hello,

I've upgraded and renamed the style "pour-reussir".

Lino

### CODE REVIEW

**Comment by LinoTremblay** [comment]
Hello, could you help me to fix what's wrong in my style please? I don't know what to do.

Thanks!

**Comment by bwiernik** [comment]
Please copy your style to http://validator.citationstyles.org/ and fix the errors it reports there

**Comment by LinoTremblay** [comment]
Ok, I've done that and it seems to be correct now.

**Comment by LinoTremblay** [comment]
I just did that, what's incorrect now?

**Comment by adam3smith** [comment]
Given the description of the style on the documentation page, shouldn't this replace the pour-reussir one rather then creating a new style? And in that case, do we need to change the stylename or could it remain Pour Reussir?

**Comment by LinoTremblay** [comment]
Hello,

               I think it could replace it, yes, but I’d ask the author of Pour réussir (Dany Thibault) before removing his style.

               Also, I’d prefer to keep the name Dionne, as people are using this (and not Pour réussir).

               Thanks for the follow up!


____________________________
Lino Tremblay
Librarian
Université du Québec à Chicoutimi (UQAC)
555, boul. de l'Université
Chicoutimi (Québec) G7H 2B1
418 545-5011, #2358
***@***.******@***.***>


[logo uqac]<http://www.uqac.ca/>

De : Sebastian Karcher ***@***.***>
Envoyé : 6 mai 2022 20:51
À : citation-style-language/styles ***@***.***>
Cc : Lino Tremblay ***@***.***>; Author ***@***.***>
Objet : Re: [citation-style-language/styles] Create dionne.csl (PR #6043)


Given the description of the style on the documentation page, shouldn't this replace the pour-reussir one rather then creating a new style? And in that case, do we need to change the stylename or could it remain Pour Reussir?

**Comment by bwiernik** [comment]
Please edit the existing Pour Reussir style instead of making a new one. You can do that in this pull request. 

Please don't change the style ID or filename. For the style title, use "Pour Réussir de Dionne 6ème édition (note, Français - Canada)"

**Comment by LinoTremblay** [comment]
Hello,

Could you please the me the status of my request please?

               Thanks!

               Lino


-------------------------------
Lino Tremblay
***@***.******@***.***>
-------------------------------

De : Lino Tremblay <>
Envoyé : 19 mai 2022 10:46
À : citation-style-language/styles ***@***.***>; citation-style-language/styles ***@***.***>
Cc : Author ***@***.***>
Objet : RE: [citation-style-language/styles] Create dionne.csl (PR #6043)

Hello and thanks for your reply,

I’ve changed the name because people are using Dionne for this style, not “Pour réussir”. See this website, which is the main site about this style: https://mondiapason.ca/fichiers/OutilBibliographique/#<https://mondiapason.ca/fichiers/OutilBibliographique/>

Aslo, as I’ve changed a lot of things in the style without working with the author and without knowing who’s using it, I’m not comfortable with replacing it like this.

Would it be possible to add my style instead of editing the old version please?

Thanks!

Lino


-------------------------------
Lino Tremblay
***@***.******@***.***>
-------------------------------

De : Brenton M. Wiernik ***@***.******@***.***>>
Envoyé : 19 mai 2022 10:39
À : citation-style-language/styles ***@***.******@***.***>>
Cc : Lino Tremblay ***@***.******@***.***>>; Author ***@***.******@***.***>>
Objet : Re: [citation-style-language/styles] Create dionne.csl (PR #6043)


Please edit the existing Pour Reussir style instead of making a new one. You can do that in this pull request.

Please don't change the style ID or filename. For the style title, use "Pour Réussir de Dionne 6ème édition (note, Français - Canada)"

**Comment by adam3smith** [comment]
I've replaced the pour-reussir style with this. The reason we're requiring links to documentation is so that we can have authoritative styles, not multiple competing copies -- there's aren't creative works, so there's no need to check with original authors.
The style title as it is now includes Dionne and I've also added that as the short-title, so it's easily findable using that label (clearly, though, not everyone is using "Dionne" for the style, since Dany created it as pour reussir). 
The filename/link/id stay the same for logistical reasons (implementations don't like us changing the ID), but are hidden from end-users.
This is OK to merge from my end, but please take a look and see if

**Comment by LinoTremblay** [comment]
Hello and thanks for the follow up Sebastian,

               Ok, let’s go like this. Is there something I need to do to see the updated style in the repository?

               Lino


-------------------------------
Lino Tremblay
***@***.******@***.***>
-------------------------------

De : Sebastian Karcher ***@***.***>
Envoyé : 5 juin 2022 21:33
À : citation-style-language/styles ***@***.***>
Cc : Lino Tremblay ***@***.***>; Author ***@***.***>
Objet : Re: [citation-style-language/styles] Create dionne.csl (PR #6043)


I've replaced the pour-reussir style with this. The reason we're requiring links to documentation is so that we can have authoritative styles, not multiple competing copies -- there's aren't creative works, so there's no need to check with original authors.
The style title as it is now includes Dionne and I've also added that as the short-title, so it's easily findable using that label (clearly, though, not everyone is using "Dionne" for the style, since Dany created it as pour reussir).
The filename/link/id stay the same for logistical reasons (implementations don't like us changing the ID), but are hidden from end-users.
This is OK to merge from my end, but please take a look and see if

**Comment by adam3smith** [comment]
This will become available on the Zotero repository shortly, and on the other CSL apps as soon as they pull in the update

**Pull request merged**
