### PR TITLE
Styles for NRC journals

### PR DESCRIPTION
**Pull request by libora**
styles for NRC Research Press Journals

### CODE REVIEW

**Comment by rmzelle** [comment]
@libora, did you create these all by hand? If you have a spreadsheet with the journal metadata, we prefer to generate these styles automatically. That makes it much easier to later find all the dependents and update them together.

**Comment by rmzelle** [comment]
And you should be able to upload more than one file at a time by using the "Upload files" button in the repository (which should lead you to https://github.com/citation-style-language/styles/upload/master ).

**Comment by libora** [comment]
@rmzelle  I created all by hand. I control manually guidance for authors of every NRC journals and when I found the same rules then I created new style directly in Github web editor (I do not upload anything). There are still 8 NRC journals which have different rules of references and have not created CSL style. Three of them (C. J. of Animal/Plant/Soil Science) have the common rules for references (http://www.aic.ca/journals/pdf/Instructions/Operations_Manual_Revised_2012.pdf) and I will compare them with rules for C.J. of Fisheries and Aquatic Science sometimes in this week. I will prepare a spreadsheet for all similar styles of NRC journals for automatic generation of styles.

**Comment by libora** [comment]
@rmzelle There is speadsheet with NRC journal data
https://docs.google.com/spreadsheets/d/1BoWy_CrJ9vbrUtWgWmOq6g300gO3Mufg6nnlJK_v-Hk/edit?usp=sharing

**Comment by rmzelle** [comment]
Great, thanks. I'll try to use the spreadsheet in the next few days to add the metadata to the "journals" repo and create the styles.

**Comment by libora** [comment]
@rmzelle Now are in spreadsheet only data for journals from this PR. Take me few days. Journals C. J. of Animal/Plant/Soil Science has different rules for references so I must prepare new independent style and after that, I will add this journals to the spreadsheet.

**Comment by libora** [comment]
@rmzelle do you create dependent styles from this pull request or from spreadsheet? In other words have I to close this pull request?

**Comment by adam3smith** [comment]
Thanks @libora -- yes, we'll want to add the dependent styles genereated from the spreadsheets in a separate commit. If you could make a new one just with CJES, that'd be great.

**Comment by libora** [comment]
OK

**Comment by libora** [comment]
This PR is replaced by https://github.com/citation-style-language/styles/pull/2082 and https://github.com/citation-style-language/journals/pull/11

**Pull request closed without merging**
