### PR TITLE
hochschule-bonn-rhein-sieg.csl

### PR DESCRIPTION
**Pull request by daryoush86**
This style provides the required citation styles for students from the University of Applied Sciences Bonn-Rhein-Sieg, Department of Business Economics

### CODE REVIEW

**Comment by POBrien333** [comment]
Hi,

1. Please add a "template" link to the style you based yours on in the style. 
2. Please add links to the documentation of the style.
3. Run the style through and copy back. This will get rid of some formatting issues. http://formatter.citationstyles.org/
4. For which languages is this style? Only German, only English, or both?

**Comment by daryoush86** [comment]
The style is only for german. I tried to fix most of the change requests. However, it seems two issues remain. 1) the file name seems not to meet the requirements and 2) the template link is not accepted, even though it points exactly to the refered style template.

Grateful for any help

**Comment by POBrien333** [comment]
You still need to do step 1 and 3. :)

**Comment by daryoush86** [comment]
Yes just finished with 1 and 3 :-). However, I still get that error for step 1. The template I used is located here: https://www.zotero.org/styles/deutsche-gesellschaft-fur-psychologie

However, the test tells me it is non-existent under this path

----------------------------------------------------------------
Absender:
Dr. Daryoush Daniel Vaziri
Fachbereich Wirtschaftswissenschaften
Bonn-Rhein-Sieg University of Applied Sciences
Grantham-Allee 20
53757 Sankt Augustin (Germany)
Tel.: +49 22 41 - 865 9654
http://www.h-brs.de<http://www.h-brs.de/>
mailto:daryoush.vaziri@h-brs.de

Leiter des Mittelstand 4.0 Kompetenzzentrums Usability
Region Nord
[cid:image002.jpg@01D43ECE.CE022860]
https://www.kompetenzzentrum-usability.digital/

Aktuelle Veranstaltungen
Nähere Informationen zu allen Veranstaltungen unter https://www.kompetenzzentrum-usability.digital/regionen/region-nord

September 2018

  *   Design Thinking Workshop zum Thema „E-Learning für den Mittelstand“ am 07.09.18.
  *   Design Thinking Workshop zum Thema „Mehrwerte digitaler Lebensmittelinformationen“ am 25.09.18.
  *   Virtueller Stammtisch zum Thema „UX im agilen Alltag“ am 27.09.18 um 16.30 Uhr.
November 2018

  *   Virtueller Stammtisch zum Thema „anwendungsfallbezogene Robotik mit Pepper“ am 13.11.18 um 16.30 Uhr.
  *   Workshop zum Thema „UX im agilen Alltag“ am 22.11.18
Dezember 2018

  *   Blended learning Kurs – UUX Management

Von: POBrien333 <notifications@github.com>
Gesendet: Dienstag, 28. August 2018 12:51
An: citation-style-language/styles <styles@noreply.github.com>
Cc: Vaziri, Daryoush <Daryoush.Vaziri@h-brs.de>; State change <state_change@noreply.github.com>
Betreff: Re: [citation-style-language/styles] hochschule-bonn-rhein-sieg.csl (#3661)


You still need to do step 1 and 3. :)

**Comment by daryoush86** [comment]
Yes just finished with 1 and 3 :-). However, I still get that error for step 1. The template I used is located here: https://www.zotero.org/styles/deutsche-gesellschaft-fur-psychologie

However, the test tells me it is non-existent under this path

**Comment by daryoush86** [comment]
Yes just finished with 1 and 3 :-). However, I still get that error for step 1. The template I used is located here: https://www.zotero.org/styles/deutsche-gesellschaft-fur-psychologie

However, the test tells me it is non-existent under this path

**Comment by daryoush86** [comment]
just tested and it seems to be alright now without the s in https. Thanks :-)

**Comment by rmzelle** [comment]
Danke!

@daryoush86, is there a webpage that links to https://www.h-brs.de/files/leitfaden_fuer_die_gestaltung_schriftlicher_arbeiten_2016_version_2.0.pdf? We try to avoid linking directly to PDFs (especially ones that have a date in the URL), since it can be hard for us to find the new link when the style guide is updated in the future.

**Comment by daryoush86** [comment]
Unfortunately there is no other link to the documentation. The file itself lies on the intranet and can’t be accessed from outside the university. But I could update the documentation link, whenever there is a new version. This does not happen so often. Maybe once every 2 years.

Best regards
Daryoush
----------------------------------------------------------------
Absender:
Dr. Daryoush Daniel Vaziri
Fachbereich Wirtschaftswissenschaften
Bonn-Rhein-Sieg University of Applied Sciences
Grantham-Allee 20
53757 Sankt Augustin (Germany)
Tel.: +49 22 41 - 865 9654
http://www.h-brs.de<http://www.h-brs.de/>
mailto:daryoush.vaziri@h-brs.de

Leiter des Mittelstand 4.0 Kompetenzzentrums Usability
Region Nord
[cid:image002.jpg@01D44516.2043FA70]
https://www.kompetenzzentrum-usability.digital/

Aktuelle Veranstaltungen
Nähere Informationen zu allen Veranstaltungen unter https://www.kompetenzzentrum-usability.digital/regionen/region-nord

September 2018

  *   Design Thinking Workshop zum Thema „E-Learning für den Mittelstand“ am 07.09.18.
  *   Design Thinking Workshop zum Thema „Mehrwerte digitaler Lebensmittelinformationen“ am 25.09.18.
  *   Virtueller Stammtisch zum Thema „UX im agilen Alltag“ am 27.09.18 um 16.30 Uhr.
November 2018

  *   Virtueller Stammtisch zum Thema „anwendungsfallbezogene Robotik mit Pepper“ am 13.11.18 um 16.30 Uhr.
  *   Workshop zum Thema „UX im agilen Alltag“ am 22.11.18
Dezember 2018

  *   Blended learning Kurs – UUX Management

Von: Rintze M. Zelle <notifications@github.com>
Gesendet: Mittwoch, 5. September 2018 05:46
An: citation-style-language/styles <styles@noreply.github.com>
Cc: Vaziri, Daryoush <Daryoush.Vaziri@h-brs.de>; Mention <mention@noreply.github.com>
Betreff: Re: [citation-style-language/styles] hochschule-bonn-rhein-sieg.csl (#3661)


Danke!

@daryoush86<https://github.com/daryoush86>, is there a webpage that links to https://www.h-brs.de/files/leitfaden_fuer_die_gestaltung_schriftlicher_arbeiten_2016_version_2.0.pdf? We try to avoid linking directly to PDFs (especially ones that have a date in the URL), since it can be hard for us to find the new link when the style guide is updated in the future.

**Comment by rmzelle** [comment]
@daryoush86, okay, in that case we'll just leave things as they are. Thanks again!

**Pull request merged**
