### PR TITLE
Create national-science-foundation-proposals.csl

### PR DESCRIPTION
**Pull request by pgugger**
NSF style that is a little simpler and cleaner than another existing one.

### CODE REVIEW

**Comment by rmzelle** [comment]
Would you mind giving some comparison examples between this and https://github.com/citation-style-language/styles/blob/master/national-science-foundation-grant-proposals.csl? I wonder if we shouldn't just update the latter. They're both for the same type of grant proposals, right?

(we're aware that space is of a particular premium in these proposals)

**Comment by pgugger** [comment]
Sure. They are fairly similar but mine is just a little cleaner looking, in
my opinion. They are both for the same NSF grant proposals. I think it
would be fine to update the other. I just wasn't sure how the style
submission worked (for example, if there were many similar competing
versions of styles that for styles that are not strictly defined). NSF
mandates that all the authors be given regardless of how many. and they
require the standard, title, journal, volume, pages. DOI or link is
optional but encouraged. Aside from that, the details of inline format and
bibliography format are open to interpretation and preference. Numerical
inline is commonly preferred for space reasons.

*Here is mine:*

1. Gugger PF, Liang CT, Sork VL, Hodgskiss P, Wright JW (2018) Applying
landscape genomic tools to forest management and restoration of Hawaiian
koa (Acacia koa) in a changing environment. *Evolutionary Applications*,
11(2):231–242. doi:10.1111/eva.12534 <https://doi.org/10.1111/eva.12534>

2. Pritchard JK, Stephens M, Donnelly P (2000) Inference of population
structure using multilocus genotype data. *Genetics*, 155(2):945–959.

3. Abrams MD (1998) The red maple paradox. *Bioscience*, 48:355–364.


*And here is the other one:*

1. Gugger, P. F., Liang, C. T., Sork, V. L., Hodgskiss, P., and Wright, J.
W. “*Applying Landscape Genomic Tools to Forest Management and Restoration
of Hawaiian Koa (Acacia Koa) in a Changing Environment*” *Evolutionary
Applications* 11, no. 2 (2018): 231–242. doi:10.1111/eva.12534
<https://doi.org/10.1111/eva.12534>

2. Pritchard, J. K., Stephens, M., and Donnelly, P. “*Inference of
Population Structure Using Multilocus Genotype Data*” *Genetics* 155, no. 2
(2000): 945–959.

3. Abrams, M. D. “*The Red Maple Paradox*” *Bioscience* 48, (1998):
355–364.

**Comment by rmzelle** [comment]
@adam3smith, looks like an improvement to me. Shall we just replace the old one?

**Comment by adam3smith** [comment]
Thanks. I changed the DOI/URL logic a bit so that it only prints one of them (and prints the DOI as a link).

**Pull request closed without merging**
