### PR TITLE
Create ABNT-Universidade-Federal-de-Pernambuco-CFCH.csl

### PR DESCRIPTION
**Pull request by cappellarius**
This is an updated style for the Centro de Filosofia e Ciências Humanas of the Universidade Federal de Pernambuco (UFPE). It follows the guidelines provided by its Central Library.

### CODE REVIEW

**Comment by rmzelle** [comment]
> It follows the guidelines provided by its Central Library.

Thanks for your submission. Are these guidelines available online? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

**Comment by cappellarius** [comment]
> > It follows the guidelines provided by its Central Library.
> 
> Thanks for your submission. Are these guidelines available online? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

Unfortunately I can't pinpoint exactly where I got them from, because the info in the site is always changing as they add/remove/update the guidelines. I started to work on this style in 2018, when I was accepted to the Master's program at this university.

Their website:
https://www.ufpe.br/sib/bdtd

The closest to the guidelines they now have:
https://www.ufpe.br/documents/39058/594591/Template+de+orienta%C3%A7%C3%A3o+para+elabora%C3%A7%C3%A3o+dos+elementos+pr%C3%A9-textuais+de+teses+e+disserta%C3%A7%C3%B5es+UFPE+-+Maio2019/25e27e4c-10e2-42ab-9067-2cc2916fe8ed

I hope some of this info helps.

**Comment by rmzelle** [comment]
Thanks! Did you base this on an existing CSL style (https://github.com/citation-style-language/styles/blob/6d7ca0a639709a9e4148011acd599b2922d3bf1d/associacao-brasileira-de-normas-tecnicas-ufrgs.csl perhaps)?

If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by cappellarius** [comment]
> Thanks! Did you base this on an existing CSL style (https://github.com/citation-style-language/styles/blob/6d7ca0a639709a9e4148011acd599b2922d3bf1d/associacao-brasileira-de-normas-tecnicas-ufrgs.csl perhaps)?
> 
> If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

I'm not sure. I looked on my backups to dig up what style I used as basis, but couldn't find it.  On previous version of mine one of the links pointed out to this style:
http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-ipea

This one is also stated as source on the one you pointed out. So I'm not sure if I used the one from UFRGS (Universidade Federal do Rio Grande do Sul) or the one from IPEA (Instituto de Pesquisa Econômica Aplicada). If I had to bet, I would choose the latter (the link above).

**Comment by cappellarius** [comment]
> Please check the [test report](https://travis-ci.org/citation-style-language/styles/builds/689015510) for details.

image

I validated it before uploading it here. No errors were found.

**Comment by rmzelle** [comment]
> I validated it before uploading it here. No errors were found.

There was an issue with an other style that reared its head here.

> So I'm not sure if I used the one from UFRGS (Universidade Federal do Rio Grande do Sul) or the one from IPEA (Instituto de Pesquisa Econômica Aplicada). If I had to bet, I would choose the latter (the link above).

The authors match those from the UFRGS style, so my bet is that that's what you used. We should be good here.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
