### PR TITLE
Update ocean-and-coastal-research.csl

### PR DESCRIPTION
**Pull request by azguth**
Fixing inline citation ordering
I hope it works

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! What is this change based on? I see both alphabetical and chronological sorting in articles in the recent issue. (I've reverted most of your other changes, which didn't seem right to me)

**Comment by azguth** [comment]
Thank you!
I wanted to do chronological order of the inline citations - but the file I was basing on had these two approaches.
Since i wasn't sure what i was doing, i decided to change the order of the sorting macros, instead of deleting the alphabetical order.
If your changes fixed this issue, for me - that's great! 
Thank you!

**Comment by adam3smith** [comment]
I think you're misunderstanding -- I'm asking why you think chronological order is correct for this journal. I see both in recent articles and no rule in the journal author guidelines.

**Comment by azguth** [comment]
Hi,

The inline citations are in chronological order. Copied from an article:
"(Monooch et al., 1983; Mussuti et al., 1998; Vaske-Junior and Lessa, 2004;
Rudershausen et al., 2010; Varghese et al., 2013; Choy et al., 2013;
Brewton et al., 2016; Menezes et al., 2019)."
"(Lusher et al., 2013; Besseling et al., 2015; Lusher et al., 2015; Lusher
et al., 2018; Ostle et al., 2019; Neto et al., 2020)"

The reference list is in alphabetical order.

And you are right, there are no explicit rules about inline citation order.
I'll add these rules in the Instructions for Authors in the near future.

Arthur Ziggiatti Güth

Laboratório de Ecologia e Evolução de Mar Profundo <http://lamp.io.usp.br/>
(Sala 133)
Instituto Oceanográfico
Universidade de São Paulo
Praça do Oceanográfico, 191
Cidade Universitária
São Paulo - SP
Brasil
CEP 05508-120

Fone: + 55 11 3091-6588 – FAX: 3091-6607
Celular: +55 11 99237 0255

**Comment by rmzelle** [comment]
@azguth, thanks!

**Pull request merged**
