### PR TITLE
Create journal-of-microscopy.csl

### PR DESCRIPTION
**Pull request by POBrien333**
closes https://github.com/citation-style-language/styles/issues/6988

Guidelines not in sync with actual papers.

### CODE REVIEW

**Comment by bwiernik** [comment]
@POBrien333 Missing a delimiter between publisher and publisher-place

**Comment by POBrien333** [comment]
I think that's an error of the generated examples in here.
Works fine and is set:
image

**Comment by adam3smith** [comment]
(reminder that citeproc-ruby handles delimiters that involve groups and conditionals incorrectly.   We should try to get that fixed, though Sylvester is unfortunately not developing anymore

**Comment by bwiernik** [comment]
@adam3smith @retorquere Sylvester pushed a fix to citeproc-ruby at RubyGems. Is there anything we need to do to update the repo to the latest version of the Gem?

**Comment by retorquere** [comment]
Sheldon still pulls in 2.0. Easy to fix but I'd have to set up Ruby again -- if someone has a working ruby env, changing the gemspec file and running bundle install will get the lockfile updated, then check the lot in -- this repo pulls sheldon from github at every run so there's no separate publishing step.

**Comment by bwiernik** [comment]
I think I have Ruby set up -- I'll check it out this weekend

**Pull request merged**
