### PR TITLE
Create uoz.csl

### PR DESCRIPTION
**Pull request by hamedheydari**
The University of Zabol has 15000 students, 110 majors and minors; Ph.D., M.D., M.A., B.A. and post-diploma programs, and 396 full-time faculty members.

### CODE REVIEW

**Comment by rmzelle** [comment]
Hi @hamedheydari. Is this citation format described anywhere, either online or in print? We always try to include a "documentation" link in the style that points to the official guide (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link)

**Comment by rmzelle** [comment]
Thanks, we'll take a look.

( @adam3smith, see https://translate.google.com/translate?hl=en&sl=fa&tl=en&u=http%3A%2F%2Fuoz.ac.ir%2F_DouranPortal%2FDocuments%2F%D8%AA%D9%86%D8%B8%DB%8C%D9%85%20%D9%85%D8%B7%D8%A7%D9%84%D8%A8%20%D9%BE%D8%A7%DB%8C%D8%A7%D9%86%20%D9%86%D8%A7%D9%85%D9%87_20101003_204948.doc )

**Comment by hamedheydari** [comment]
@rmzelle Hi. Google translator is not good enough in Persian. Let's do this the Easy Way. Check this out:
https://drive.google.com/file/d/0BwNDH0XEsW3VRjJoSGNyN3VMREU/view

**Comment by rmzelle** [comment]
Thanks. Two questions:

* So this style is for the entire university? It's not for a specific department, right?
* Did you write this style from scratch, or did you start from an existing CSL style. If the latter, we'd like to see a "template" link (https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

**Comment by hamedheydari** [comment]
Yes. This is for the entire university.
I started from "Cell" style. but almost everything is modified.
(https://www.zotero.org/styles/cell)

**Comment by rmzelle** [comment]
Okay, thanks. I just changed the style's file name (we try to avoid abbreviations in those).

**Pull request merged**
