### PR TITLE
Update frontiers-medical-journals.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/93077/no-date-in-the-frontiers-style-for-a-book-section#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
Is this actually WiP or ready for review?

**Comment by POBrien333** [comment]
I can't remember for the life of it, but looking at it I think this can be merged. :)

**Comment by adam3smith** [comment]
Book section looks quite different from guidelines now?


Sorenson, P. W., and Caprio, J. C. (1998). "Chemoreception," in The Physiology of Fishes, ed. D. H. Evans (Boca Raton, FL: CRC Press), 375-405.

**Comment by adam3smith** [comment]
Sorry, notnall that different. I think you are missing initialize-with for editors

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
