### PR TITLE
Minor ASM ch-ch-changes

### PR DESCRIPTION
**Pull request by aurimasv**
Based on MCB and JCM styles, but it looks like the style guide is copy-pasted for all ASM journals.

### CODE REVIEW

**Comment by rmzelle** [comment]
@dstillman, did something change about our S3 bucket we use for caching? Seem to be getting a 403.

**Comment by rmzelle** [comment]
Maybe it's just Travis/AWS being unhappy: http://www.traviscistatus.com/

**Comment by rmzelle** [comment]
For some reason the lines

```
$ export AWS_ACCESS_KEY_ID=[secure]
$ export AWS_SECRET_ACCESS_KEY=[secure]
```

are absent from this build, even if I restart it. Maybe Travis is (mistakenly) using an outdated .travis.yml (from @aurimasv's extremely outdated "master" branch)? Otherwise I have no clue what's failing.

**Comment by aurimasv** [comment]
You mean they're missing from the build log? I don't see them in https://travis-ci.org/citation-style-language/styles/builds/54208663 either though.

**Comment by aurimasv** [comment]
Doesn't look like secure variables should be working for most of the PRs  here anyway http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests

The bigger question, I guess, is why is the cache bundle not available from S3 in the first place (it is available for all the recent PRs I looked at). It may have something to do with Travis/AWS connection issues that you linked to above. Maybe try re-creating the cache bundle by creating a PR from this repo? Or, otherwise, might just need to re-trigger the build now that AWS seems to be back in business

**Comment by aurimasv** [comment]
Trying to re-trigger build...

**Comment by rmzelle** [comment]
But this used to work... I got nothing.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
