### PR TITLE
oecologia-australis.csl

### PR DESCRIPTION
**Pull request by gudryan**
It is a reviewed Mendeley style for Oecologia australis. Also, it is according to the new instructions for authors.
Gudryan J. Barônio in 20th July 2017.

### CODE REVIEW

**Comment by rmzelle** [comment]
@gudryan, let us know if you still want to submit this and need some help.

**Comment by gudryan** [comment]
@rmzelle, I had doubts about validation. I did not understand exactly whats are the problems with script. Although the validation not passed it is working better on Mendeley.

**Comment by rmzelle** [comment]
> I had doubts about validation. I did not understand exactly whats are the problems with script. Although the validation not passed it is working better on Mendeley.

There was one CSL validation error in the style you submitted: http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fgudryan%2Fstyles%2F938582a40a6e737a48b6f08f8c0a819cdf9f9b8b%2FOecologia_australis_July_2017.csl&version=1.0.1
(`<link href="https://goo.gl/2t3AeS"/>` needs to be `<link href="https://goo.gl/2t3AeS" rel="documentation"/>`), and there are some minor issues related to the style name, which doesn't follow our guidelines (https://github.com/citation-style-language/styles/wiki/Style-Requirements).

In general, though, you can easily update a pull request if there are some issues that need to be fixed (at least as long as you don't delete the "patch" branch, which you did here). If you still want to submit this, just create another pull request and we'll tell you what to fix.

**Comment by gudryan** [comment]
@rmzelle, could you help me?

There is a failure by csl-bot: 

1) oecologia-australis-july-2017: must validate against the CSL 1.0.1 schema
     Please check your style at http://validator.citationstyles.org/
     Failure/Error: expect(CSL.validate(path)).to be_empty
       expected `[[0, "598:1: FATAL: Extra content at the end of the document"]].empty?` to return true, got false
     Shared Example Group: "style" called from ./spec/styles_spec.rb:216
     # ./spec/styles_spec.rb:5:in `block (2 levels) in <top (required)>'

However, running the CSL validator it is all ok. What about it this error pointed by csl-bot?

Many thank you,
Gudryan

**Comment by rmzelle** [comment]
@gudryan, where can I find the author guidelines for this journal? http://www.oecologiaaustralis.org/ojs/index.php/oa/about/submissions points to https://drive.google.com/file/d/0Bzlp9Fz2x0N2aDU5XzJiMUtYeDA/view, which are guidelines from 2015, and https://revistas.ufrj.br/index.php/oa/about/submissions#authorGuidelines doesn't have any information.

**Comment by gudryan** [comment]
You can see the updated (for 2017) author's guidelines here: https://www.dropbox.com/s/azm8ycbkk229uce/Diretrizes%20OA%202017_12julho2017.pdf?dl=0

At moment, the roles were included only in the portuguese version of  https://revistas.ufrj.br/index.php/oa/about/submissions#authorGuidelines
However, I am including here the style in order to allow a better improvement of english version.
Is it what are you looking for?

**Comment by gudryan** [comment]
@rmzelle, sorry for had not include your Mark on last comment. Only for notification.

**Comment by rmzelle** [comment]
> You can see the updated (for 2017) author's guidelines here: https://www.dropbox.com/s/azm8ycbkk229uce/Diretrizes%20OA%202017_12julho2017.pdf?dl=0

Thanks. I edited the style and linked to that.

Do you know which CSL you started from? We also like to add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

**Comment by rmzelle** [comment]
Oh, and if you're more comfortable in Portuguese, just write in that language.

**Comment by gudryan** [comment]
I have started from this one:

http://csl.mendeley.com/styles/12134/OecologiaAustralis2015

For what is useful the zotero link which is automatically included on style? When I use this link it only drives me to "no found style web page".
I would like to include it in order to all user of Mendeley may use the style. Is it possible?

**Comment by rmzelle** [comment]
> I have started from this one:
> 
> http://csl.mendeley.com/styles/12134/OecologiaAustralis2015

Thanks. Looks like that one was based on our APA style, so I added a "template" link to that.

> For what is useful the zotero link which is automatically included on style? When I use this link it only drives me to "no found style web page".
> I would like to include it in order to all user of Mendeley may use the style. Is it possible?

You mean "http://www.zotero.org/styles/oecologia-australis"? Once we accept this style that link will work (after an hour or so).

**Comment by gudryan** [comment]
Thank you very much for this help!

**Comment by gudryan** [comment]
@rmzelle, do you now why I can not found the style when I search on http://editor.citationstyles.org/searchByName/ ?

As you said, the Zotero link is working, but I need that the users found the style when search at Mendeley app.

Thank you for attention!

**Comment by rmzelle** [comment]
> @rmzelle, do you now why I can not found the style when I search on http://editor.citationstyles.org/searchByName/ ?
> 
> As you said, the Zotero link is working, but I need that the users found the style when search at Mendeley app.

http://editor.citationstyles.org is under control, but updating styles there needs to be done by hand and is cumbersome, so it often takes weeks if not months between updates.

I'm not sure how often Mendeley updates their styles. Might be once every 24 hours, so you could check again tomorrow if it's available there. But we don't have any control over that.

**Comment by gudryan** [comment]
Ok, I understood.
Thank you very much for attention @rmzelle!

**Comment by gudryan** [comment]
Please @rmzelle, how could I update the style?
I can not edit this.

**Comment by rmzelle** [comment]
> Please @rmzelle, how could I update the style?
> I can not edit this.

If you wish to submit changes to the version we accepted, you can use the edit (pencil) icon at https://github.com/citation-style-language/styles/blob/master/oecologia-australis.csl. See also https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style

**Pull request merged**
