### PR TITLE
Add style: Elementa (author-date)

### PR DESCRIPTION
**Pull request by akokai**
For the journal [Elementa](http://www.elementascience.org/). Based on The Council of Science Editors style, Name-Year system: author-date in text, sorted in alphabetical order by author.
XML validated by validator.nu.

### CODE REVIEW

**Comment by akokai** [comment]
Thank you, I think I'm done with my final changes on this.

**Comment by rmzelle** [comment]
@akokai, thanks.

Could you make a few small changes? Please change the title to `<title>Elementa</title>`, and the file name to "elementa.csl" (and update the style ID and "self" link to match). Otherwise it looks good to merge.

**Comment by akokai** [comment]
@rmzelle Done. :)

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
