### PR TITLE
Added a style for Curr Top Med Chem

### PR DESCRIPTION
**Pull request by davidbajusz**
Possibly suitable for other journals of Bentham Science

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks. Can you add the print and electronic ISSNs?

Looking at http://benthamscience.com/journals/current-topics-in-medicinal-chemistry/, that would be:

```xml
<issn>1568-0266</issn>
<eissn>1873-5294</eissn>
```

You could also add `<category field="medicine"/>`.

**Comment by rmzelle** [comment]
And it looks like Bentham uses at least a few different citation formats. E.g. http://benthamscience.com/journals/current-alternative-energy/author-guidelines/#top mentions IEEE style, but http://benthamscience.com/journals/current-topics-in-medicinal-chemistry/author-guidelines/#top mentions ACS style.

**Comment by rmzelle** [comment]
Also, in general, we prefer pull requests not to have any merge commits. This is easier to accomplish if you don't make your changes directly to your "master" branch. Instead, you could keep your "master" branch synced up with our "master" branch, and then create a feature branch off of your "master" branch. That also allows you to (relatively) easily rebase your feature branch.

By far the easiest way is just to use the GitHub interface to create your pull request, though, since that will create a new fresh branch. See https://help.github.com/articles/creating-new-files/

**Comment by rmzelle** [comment]
And your style doesn't validate because it's missing a timestamp, like `<updated>2016-01-21T12:00:00+00:00</updated>`

**Comment by davidbajusz** [comment]
Thanks for the tips, I'll make sure to adhere to them in the future.

**Comment by rmzelle** [comment]
You currently have the "chemistry" field twice:

```
    <category field="chemistry"/>
    <category citation-format="numeric"/>
    <category field="chemistry"/>
```

And for this pull request, it's probably easiest to just create a new pull request by clicking the "New file" button at https://github.com/citation-style-language/styles and selecting the file from https://raw.githubusercontent.com/davidbajusz/styles/master/current-topics-in-medicinal-chemistry.csl.

You could then either reset your master branch as explained here (http://stackoverflow.com/questions/5916329/cleanup-git-master-branch-and-move-some-commit-to-new-branch) or just delete your cloned repository and fork it again, in case you want to make future contributions.

**Comment by adam3smith** [comment]
This looks good from the code side. @rmzelle -- I'll leave for you to merge.

**Comment by rmzelle** [comment]
Great, thanks for contributing! (added by hand to circumvent the extra merge commit in this pull request)

**Comment by davidbajusz** [comment]
Awesome, glad to have contributed.

**Pull request closed without merging**
