### PR TITLE
terrains-et-travaux.csl

### PR DESCRIPTION
**Pull request by nutelu**
Style for social sciences journal "terrains & travaux" (French). Description: http://tt.hypotheses.org/consignes-aux-contributeurs/mise-en-forme (see 3. Références bibliographiques)

### CODE REVIEW

**Comment by adam3smith** [comment]
There are a number of validation errors in the style. See http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fnutelu%2Fstyles%2Fpatch-1%2Fterrains-et-travaux.csl&version=1.0.1#source-code
and see if you can make sense of this--they should mostly be pretty clear. 

You also define a macro "number-of-pages" that you never call. Delete it.

**Comment by adam3smith** [comment]
You can update your pull request by using the pencil icon at the top here:
https://github.com/citation-style-language/styles/pull/1730/files

**Comment by rmzelle** [comment]
@nutelu, let us know if you need help with this.

**Comment by rmzelle** [comment]
@nutelu, your style doesn't validate yet against the CSL schema. See http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fnutelu%2Fstyles%2Fpatch-1%2Fterrains-et-travaux.csl&version=1.0.1.

You should be able to fix the style by changing

```xml
          <substitute>
            <names variable="editorial-director"/>
            <name and="text" name-as-sort-order="all" sort-separator=", " delimiter=", " delimiter-precedes-last="never" initialize-with="."/>
          <label form="short" prefix=" (" suffix=")" text-case="lowercase"/>
          </substitute>
```

into

```xml
          <substitute>
            <names variable="editorial-director"/>
          </substitute>
```

(the `<name/>` and `<label/>` elements here look rather redundant anyway)

**Comment by rmzelle** [comment]
Closing because of inactivity.

@nutelu, we can reopen this pull request if you get back to us.

**Pull request closed without merging**
