### PR TITLE
Create new Citation type

### PR DESCRIPTION
**Pull request by arya1406**
This Citation type for my Institution, State College of Meteorology Climatology and Geophysics. Thank you.

### CODE REVIEW

**Comment by adam3smith** [comment]
Is the citation style documented online somewhere or could you upload documentation here?

**Comment by arya1406** [comment]
I post it in my article, here is the link 
https://aruya.medium.com/cara-menambahkan-custom-citation-style-stmkg-pada-aplikasi-mendeley-2354b66217a2

**Comment by rmzelle** [comment]
> I posted in my article, here is the link
> https://aruya.medium.com/cara-menambahkan-custom-citation-style-stmkg-pada-aplikasi-mendeley-2354b66217a2

@arya1406, thanks. Can you also tell us where [STMKG](https://stmkg.ac.id/) publishes their citation guide? Do they have a publicly available online document?

**Comment by arya1406** [comment]
@

> > I posted in my article, here is the link
> > https://aruya.medium.com/cara-menambahkan-custom-citation-style-stmkg-pada-aplikasi-mendeley-2354b66217a2
> 
> @arya1406, thanks. Can you also tell us where [STMKG](https://stmkg.ac.id/) publishes their citation guide? Do they have a publicly available online document?

thanks @rmzelle ,
[STMKG](https://stmkg.ac.id/) does not post its citation types online, it only shares the format in pdf with its students. Because of that, I make this and post it, so every student can have it.

**Comment by rmzelle** [comment]
@arya1406, okay, I'll just link to the institute's webpage and your article, then. Thanks!

**Comment by arya1406** [comment]
> @arya1406, okay, I'll just link to the institute's webpage and your article, then. Thanks!

Thank you so much @adam3smith @rmzelle for helping me. Hope you always healthy

**Pull request merged**
