### PR TITLE
Create iso690-author-date-no-abstract-en.csl

### PR DESCRIPTION
**Pull request by paezm**
I change the style iso-690-author-date-en.csl. In this version, the abstract has been removed. And instead of "Accessed 9 November 2016"  I changed by "Viewed 9 November 2016".

### CODE REVIEW

**Comment by adam3smith** [comment]
What guide exactly is this based on? "ISO 690" is such a vague reference -- providing more general guidance than a specific citation format -- that I'd like to prevent the proliferation of styles. E.g., "Viewed" vs. "Accessed" certainly isn't something that the ISO standard specifies, is it?

**Comment by paezm** [comment]
ISO 690:2010. My library school wrote a guide about this style https://www.hesge.ch/heg/infotheque/citations-et-references-bibliographiques.

**Comment by adam3smith** [comment]
Great, thanks -- since this is only "based on" ISO 690:2010, I think we'll want to name this after the school rather than ISO 690. Looking briefly at the guide, I think it also makes sense to remove the note and archive macro and the block display?

**Comment by paezm** [comment]
Sorry but I'm not sure I understand. It's better if I change the name ? And I add the School library name?
Is it neccessary to remove the note and archive macro and the block display ? :)

**Comment by paezm** [comment]
It's better if we keep the name iso-690 because many schools use this standard. Et we have respected this standard. It's really specified "viewed" and not "accessed". How should I proceed to have the style validated? Sorry, this is the first time I'm correcting a style.. ;)

**Comment by rmzelle** [comment]
(I renamed the style to what we'd typically do in these cases. We could add back the "author-date" descriptor if your institution uses more than one type of ISO 690 style (like the "numeric" or "note" versions))

**Comment by paezm** [comment]
Thank you @rmzelle

**Comment by paezm** [comment]
@rmzelle Now, my style is submitted ? 
How to display my style on www.zotero.org/styles?

**Comment by paezm** [comment]
@adam3smith Hi ! How to display my style on www.zotero.org/styles?

**Comment by adam3smith** [comment]
Thanks!

**Comment by paezm** [comment]
Thank you!!! :D

**Pull request merged**
