### PR TITLE
Update american-institute-of-physics.csl

### PR DESCRIPTION
**Pull request by shinliang**

### CODE REVIEW

**Comment by adam3smith** [comment]
what are you basing this on? The original guide we link to is no longer available, but the sources I find do not print chapter titles, see e.g. 
http://physics.gac.edu/~huber/misc/aiprefs.htm
and 
http://guides.lib.monash.edu/content.php?pid=346637&sid=3118651

**Comment by shinliang** [comment]
Hi,

If you look at this:
http://authortoolkit.aip.org/JAP_Sample_MS.pdf
book chapters/sections are printed. Furthermore, without this added line,
the bibliography will turn out something like this for book chapters:
[Authors], *in* [Book Name], ....
which looks odd and as if something is missing before the "in".


Best regards,
Dr. Shin-Liang Chin
Thin Film Magnetism
Cavendish Laboratory
University of Cambridge

**Comment by adam3smith** [comment]
I don't see a book chapter example there, but I do see a chapter in conference proceeding (no. 4 on p. 12) and that is without title and exactly with the ", in" that you find odd:
R. K. Ahrenkiel, in Gallium Arsenide and Related Compounds 1993: Proceedings of the
20th International Symposium on Gallium Arsenide and Related Compounds, Freiburg, Germany, 29 August–2 September 1993, edited by H. S. Rupprecht and G. Weimann (Institute of Physics, London, 1994), pp. 685–690.

**Comment by shinliang** [comment]
Ok. I agree with you. 


Best regards,
Dr. Shin-liang Chin
Cavendish Laboratory
University of Cambridge

**Comment by adam3smith** [comment]
thanks!

**Pull request closed without merging**
