### PR TITLE
Create animal-migration

### PR DESCRIPTION
**Pull request by ecophilina**

### CODE REVIEW

**Comment by rmzelle** [comment]
@ecophilina, could you change the style's file name from "animal-migration" to "animal-migration.csl"? (see https://help.github.com/articles/renaming-a-file/ )

Also please include the journal's eISSN (`<eissn>2084-8838</eissn>`).

**Comment by rmzelle** [comment]
Great, thanks. Let us know when you're done editing this style.

I forgot to ask whether you could include a "template" link (assuming you based this CSL style on an existing one). See https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link

**Comment by ecophilina** [comment]
I think I've reached the limits of my skill with this (although I may still discover bugs and how to fix them) but I'd love to put this out for others to test and suggest improvements.

**Comment by rmzelle** [comment]
Okay, thanks! Future fixes are always welcome.

I made one small edit to italicize "et al.", which you said was required in the commit message of https://github.com/citation-style-language/styles/pull/2209/commits/06cc5383c6f22d08a3caa45310e25bb27f8bb022

**Pull request merged**
