### PR TITLE
Fixed comma setting for books

### PR DESCRIPTION
**Pull request by Braintelligence**
Example: If we specified a book with an edition, we had a prefixing comma with whitespace between the prepending element and the book. 

We may run into other problems involving strange design choices concerning prefixes of the original citation style, but this is an atomic fix for now. I will submit a PR anytime we encounter actual problems and fix them.

### CODE REVIEW

**Comment by adam3smith** [comment]
Something is off with the pull request. Could you redo this from an up to date fork of the repository?

**Comment by Braintelligence** [comment]
> 
> 
> Something is off with the pull request. Could you redo this from an up to date fork of the repository?

Sure, let me redo real quick.

**Comment by Braintelligence** [comment]
@adam3smith Is it better like this or should I destroy my repo and redo from scratch?

**Comment by adam3smith** [comment]
Yes, that works, thanks. 
(Btw., you should always make pull requests from feature branches so you have a clean copy of master you can go back to)

**Comment by adam3smith** [comment]
(I reopened since this looks good to me).

> It looks as if this line doesn't do anything in Zotero. I also don't understand the logic behind it. In my brain it should do something like <term=volume>.<variable=volume> which doesn't make any sense to me. That's why I investigated and realized it has no effect in Zotero at all. If you remove this line, Zotero still works.
Can someone please give me some insight to what could have been the intention behind this line? Sadly I didn't create the original CSL, but I'm tasked to fix bugs that we start to encounter now.

The line reference got lost here; which line are you referring to?

**Comment by Braintelligence** [comment]
Man, I have a really bad timing 😛, sorry for closing, I just was about to destroy my repo and fork again.

The line reference should be visible here: https://github.com/Braintelligence/styles/commit/4452beb5234952923f8b49169344efeff6ab7ea9

**Comment by adam3smith** [comment]
See my comment wrt. to the volume term. I don't think what you have here is right.

**Comment by adam3smith** [comment]
great, thanks

**Pull request merged**
