### PR TITLE
Update ens-de-lyon-centre-d-ingenierie-documentaire.csl

### PR DESCRIPTION
**Pull request by smarchand**
I made the changes you requested : for the extra-space and the group.
I hope it goes well know.
Let me know

### CODE REVIEW

**Comment by rmzelle** [comment]
Who requested these changes, and where? (can you give a link?)

**Comment by smarchand** [comment]
sure : it was this discussion :
https://github.com/citation-style-language/styles/pull/1658#discussion_r37675079.


Perhaps I made it wrong to make a new commit.

2015-09-17 17:30 GMT+02:00 Rintze M. Zelle <notifications@github.com>:

> Who requested these changes, and where? (can you give a link?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1691#issuecomment-141122890>
> .
>



-- 
Stéphane

**Comment by rmzelle** [comment]
Yes, it would be better to keep using the original pull request. Does #1658 already incorporate all the changes that are in this new pull request?

**Comment by smarchand** [comment]
Yes it does. I made a new change for the indentation. I made it there :
https://github.com/citation-style-language/styles/pull/1658 as you
requested.
Thanks you for all
stéphane

2015-09-18 11:28 GMT+02:00 Rintze M. Zelle <notifications@github.com>:

> Yes, it would be better to keep using the original pull request. Does
> #1658 <https://github.com/citation-style-language/styles/pull/1658>
> already incorporate all the changes that are in this new pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1691#issuecomment-141397231>
> .
>



-- 
Stéphane

**Comment by rmzelle** [comment]
Solved in #1658 (I think).

**Pull request closed without merging**
