### PR TITLE
Updated the Canadian-Journal-of-soil-science according to the recent updated journal instructions

### PR DESCRIPTION
**Pull request by sima15**
There have been recent changes in the reference section of the Canadian-Journal-of-soil-science which were not updated in its corresponding .csl file here. I did the updates.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks.

Could you update the "documentation" link in the style as well? It probably should point to http://www.nrcresearchpress.com/page/cjss/authors#21.

(and, as a very minor nitpick, we don't use trailing spaces at the end of XML elements, e.g. `<date-part name="year"/>` instead of `<date-part name="year" />`, but I can change that myself before we merge your changes)

**Comment by rmzelle** [comment]
Thanks!

**Comment by sima15** [comment]
I was trying to undo my forked branch commit since I remembered that I
needed to edit the original commit. What should I do now?

**Comment by rmzelle** [comment]
In general, it's easiest if you don't work in the "master" branch of your fork. Instead, just follow our instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md for adding and editing styles.

With our steps, you make the desired change in our official repository. GitHub automatically recognizes that you don't have the rights to make that change directly (since you don't have push access to our repo), and will store the change in a fresh branch (that is up-to-date with our "master" branch) in your own fork.

**Comment by sima15** [comment]
Alright, sure.

**Comment by rmzelle** [comment]
(and ignore the "There are some issues with your submission" comment I deleted. I just merged the pull request before our automated test system had the chance to test the pull request, which caused a harmless testing error)

**Comment by sima15** [comment]
I went to this link "
https://github.com/citation-style-language/styles/blob/master/canadian-journal-of-soil-science.csl"
to update the file online but it is the exact same thing that I want
because I have previously edited it. Can you try to merge again and see if
it works?


Thanks,
Sima

**Comment by rmzelle** [comment]
I don't really understand what you're trying to do. Maybe you can explain yourself a little more?

https://github.com/citation-style-language/styles/blob/master/canadian-journal-of-soil-science.csl is our current version, which includes the changed made through this accepted pull request. The previous version can be found at https://github.com/citation-style-language/styles/blob/eadecd80b911b0295ec5902b5412092ee45cb1aa/canadian-journal-of-soil-science.csl.

**Comment by sima15** [comment]
Oh, sorry, my confusion! I thought that your merge didn't go through and
you asked me for a second pull request! :D I guess we're good now! :)

**Comment by rmzelle** [comment]
> I thought that your merge didn't go through

No, that was just our automatic testing robot complaining. Just ignore him/her.

**Pull request merged**
