### PR TITLE
Create iranian-journal-of-basic-medical-sciences.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/69985/style-request-ijbms

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks!

**Comment by POBrien333** [comment]
Rintze is back!! Where did you hide? Hope you're doing well :)

**Comment by rmzelle** [comment]
Just been busy with other stuff (day job, one-year old, and just moved to a different state this past weekend). CSL has to take a backseat sometimes. It's also been nice to take a little break after being on style repository duty for 6+ years.

**Comment by POBrien333** [comment]
Ah, I see. I assumed something like that. :)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
