### PR TITLE
Update pnas.csl

### PR DESCRIPTION
**Pull request by POBrien333**
PNAS completely changed style. Please review. :)
Guidelines lack quite a bit of substance, so it's only really adapted for article-journal and chapter (and book extrapolated from that).
https://forums.zotero.org/discussion/78866/pnas-reference-update

### CODE REVIEW

**Comment by POBrien333** [comment]
Thanks for looking over it.

**Comment by rmzelle** [comment]
> PNAS completely changed style.

No template used?

**Comment by adam3smith** [comment]
> No template used?

Pretty sure this is based on the old style which didn't have a template in there.

**Comment by rmzelle** [comment]
Yeah, looks like it. Thanks both!

(timely, see e.g. https://twitter.com/SamPassmore_/status/1166989872944623623)

**Comment by POBrien333** [comment]
Template was just the old pnas.csl. :)

**Pull request merged**
