### PR TITLE
Create annual-review-of-linguistics

### PR DESCRIPTION
**Pull request by djvill**
Based on https://github.com/citation-style-language/styles/blob/master/annual-reviews-author-date.csl, with fixes for Ann Rev Linguistics. Validated 28 March 2022.

### CODE REVIEW

**Comment by bwiernik** [comment]
According to the documentation at https://www.annualreviews.org/pb-assets/ar-site/Migrated/AuthorHandbook-GREEN-1388351071000.pdf, Linguistics uses the same style all of the other Annual Reviews author-date journals. Can you describe what your style is intended to do?

**Comment by djvill** [comment]
This style updates the csl for the Annual Review of Linguistics per the more recent Feb 2020 revision, and in particular the style guide supplement on the last three pages of this doc: https://www.annualreviews.org/pb-assets/Authors%20Assets/AuthorHandbook-Linguistics-1582569109680.pdf

**Comment by bwiernik** [comment]
Thanks!

**Comment by bwiernik** [comment]
@djvill Were there other changes besides the linguistics-specific changes that should also be incorporated into the standard Annual Reviews (author-date) style? If so, can you open a pull request for that?

**Comment by djvill** [comment]
Can't remember--it's been a little while.

**Pull request merged**
