### PR TITLE
Update bibliothek-forschung-und-praxis.csl

### PR DESCRIPTION
**Pull request by jmiba**
Disambiguate no-date publications by one author

### CODE REVIEW

**Comment by adam3smith** [comment]
you really want the title there? I'd be more common to use a year suffix like "o. J.-a" in an author-date style (you'd have to set that explicitly, I believe)

**Comment by jmiba** [comment]
> you really want the title there? I'd be more common to use a year suffix like "o. J.-a" in an author-date style (you'd have to set that explicitly, I believe)

Actually, a disambiguated without-date-term would be preferable but I believe this is not possible. If you put a term here it will not be disambiguated in case there are several documents by the same author without dates.

**Comment by adam3smith** [comment]
Could you test this version? Should work

**Comment by jmiba** [comment]
Thanks, @adam3smith, this is perfect!

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
