### PR TITLE
Create up-fakulteta-za-vede-o-zdravju-apa-beta.csl

### PR DESCRIPTION
**Pull request by patrikpucerfvz**
Beta version 1 uploaded

### CODE REVIEW

**Comment by patrikpucerfvz** [comment]
Closed

**Comment by patrikpucerfvz** [comment]
UP FVZ beta version 1

**Comment by rmzelle** [comment]
@patrikpucerfvz, hi, sorry for the long wait.

So, this style is for the Faculty of Health Sciences at University of Primorska (http://www.fvz.upr.si/en), correct? Is the style guide for this citation format available online?

**Comment by patrikpucerfvz** [comment]
@rmzelle hello there!
Yes, that's correct, it is for the Faculty of Health Sciences at University of Primorska. We have a citation format available online (http://www.fvz.upr.si/sites/default/files/navodila_za_citiranje_in_navajanje_virov_up_fvz_2018.pdf), but it is in Slovenian language. Anyway, the examples are understandable in any language and we are using the Slovenian version of the APA 6th edition.

**Comment by rmzelle** [comment]
Thanks! Sorry this took so long.

Is there a university webpage that links to http://www.fvz.upr.si/sites/default/files/navodila_za_citiranje_in_navajanje_virov_up_fvz_2018.pdf? Since the PDF has a year in its name, the URL is likely to change rather soon, so maybe we can add a more stable URL as well?

**Pull request merged**
