### PR TITLE
Create evolutionary-bioinformatics.csl

### PR DESCRIPTION
**Pull request by damnation333**
via https://forums.zotero.org/discussion/56459/style-request-evolutionary-bioinformatics-libertas-academica-journal

### CODE REVIEW

**Comment by rmzelle** [comment]
It looks like all the SAGE journals listed at http://insights.sagepub.com/journal_homepage.php use AMA (didn't check if that's any different from SAGE Vancouver). http://insights.sagepub.com/author_resources.php?folder_id=135&sub_menu_id=137:

> Articles published in these journals use the AMA reference formatting style.  

I couldn't find a spreadsheet that lists these journals (which would make it a lot easier to generate CSL styles for them), and it's not totally clear to me what collection they belong to ("Insights"?). They e.g. aren't listed in the "SAGE Premier 2017 Title List" at https://us.sagepub.com/en-us/nam/title-lists.

**Comment by damnation333** [comment]
Sounds like we should write to them and ask them?

**Comment by adam3smith** [comment]
I've tried to write to Sage many times without any real success. I got a somewhat promising answer one, but that, too, dried up in spite of multiple follow-ups.

**Comment by rmzelle** [comment]
Thanks!

**Comment by rmzelle** [comment]
(looks like Travis CI created a ghost build? It wasn't me who triggered this)

**Pull request merged**
