### PR TITLE
Add "director" to "secondary-contributors" macro

### PR DESCRIPTION
**Pull request by nickbart1980**
For rendering the director element in, e.g., *Movie Title*. 2004. Directed by Mary Smith. Hollywood, CA: Bigshot Productions. 
See http://www.chicagomanualofstyle.org/qanda/data/faq/topics/Documentation/faq0020.html

### CODE REVIEW

**Comment by adam3smith** [comment]
the way citeproc-js interprets the specs for cs:names (rightly so, given the current wording):
http://docs.citationstyles.org/en/stable/specification.html#names
this would break the editortranslator functionality. 
Either add this as a separate element in a group, or we can think about revisiting this part of the specs; came up recently and @rmzelle suggested changing this: https://github.com/citation-style-language/styles/pull/1436#issuecomment-78958861 I said not worth it bc it's too rare, but I don't have any fundamental objections.

**Comment by nickbart1980** [comment]
I see – I added director as a separate element in a group now and committed the change – is this ok or do you need another pull request?

**Comment by adam3smith** [comment]
this is great, we're not super picky about minimizing the number of commits.

**Comment by nickbart1980** [comment]
Same problem in apa.csl, by the way: https://github.com/citation-style-language/styles/blob/master/apa.csl#L48 and #L58. Revising the specs might make sense after all.

**Pull request merged**
