### PR TITLE
Create american-school-of-classical-studies-at-athens.csl

### PR DESCRIPTION
**Pull request by wallrodt**
This is the first version of the ASCSA style for Hesperia.
There is a custom abbreviations.json file to accompany this style. That file allows the use of the AJA (American Journal of Archaeology) abbreviations for [Journals and Book Series](https://www.ajaonline.org/submissions/abbreviations) (but not for Standard Reference Works). I don't know how to add that to this style.

### CODE REVIEW

**Comment by rmzelle** [comment]
@wallrodt, thanks! A few questions:

* Did you base this on the Ecology CSL style, or another style? Ecology is mentioned in this style's template link, but it doesn't look like that's right.
* Style-specific abbreviation lists are a citeproc-js/Juris-M specific feature that isn't part of the official CSL specification, and we unfortunately currently don't support them.
* Is http://athina.ascsa.edu.gr/pdf/uploads/Guidelines10-13.pdf an intranet webpage? I'm trying to access it but it doesn't load for me.

**Comment by wallrodt** [comment]
Hello,

I hired someone to get the stylesheet started. I don’t know what template they started with.

The style-specific abbreviation is something that might be Zotero specific, which is my target audience. Many Classics related fields use the AJA abbreviations for bibliography, so this is a big part of the style.

Apologies for the bad URL. The American School was developing a new website while this stylesheet was being constructed. The new url is https://www.ascsa.edu.gr/uploads/media/Guidelines10-29-18.pdf
I have updated the csl.





On Jan 26, 2019, at 8:56 AM, Rintze M. Zelle <notifications@github.com<mailto:notifications@github.com>> wrote:


@wallrodt<https://github.com/wallrodt>, thanks! A few questions:

  *   Did you base this on the Ecology CSL style, or another style? Ecology is mentioned in this style's template link, but it doesn't look like that's right.
  *   Style-specific abbreviation lists are a citeproc-js/Juris-M specific feature that isn't part of the official CSL specification, and we unfortunately currently don't support them.
  *   Is http://athina.ascsa.edu.gr/pdf/uploads/Guidelines10-13.pdf an intranet webpage? I'm trying to access it but it doesn't load for me.

**Comment by rmzelle** [comment]
> The style-specific abbreviation is something that might be Zotero specific, which is my target audience. Many Classics related fields use the AJA abbreviations for bibliography, so this is a big part of the style.

Since we currently don't have a way to store and distribute custom abbreviation lists, you'll just have to provide your users with this file yourself for now. https://forums.zotero.org/discussion/comment/275237/#Comment_275237 suggests that Zotero users can use a custom abbreviations.json file by copying it into their Zotero data directory.

> I hired someone to get the stylesheet started. I don’t know what template they started with.

@POBrien333, was that you by any chance? You're currently mentioned in the style. If it's just carry-over from another style I'll remove your name here.

**Comment by POBrien333** [comment]
That was me.

**Comment by rmzelle** [comment]
@POBrien333, thanks for clarifying. It looks like we can make a dependent for Hesperia, right? https://www.jstor.org/journal/hesperia

**Comment by POBrien333** [comment]
Yes, let me check and submit a PR if.

**Comment by rmzelle** [comment]
@wallrodt, can you send us the abbreviations list?

You can either make a pull request at https://github.com/citation-style-language/abbreviations (file name doesn't really matter), or you can add the file here as an attachment to a GitHub comment. For the latter, note that email attachments don't work, and it looks like you'd have to give the JSON file a ".txt" extension (see https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by wallrodt** [comment]
[aja_abbreviations_json.txt](https://github.com/citation-style-language/styles/files/2832966/aja_abbreviations_json.txt)
This should be renamed abbreviations.json and placed in the top level of the user's Zotero folder.

**Comment by rmzelle** [comment]
> [aja_abbreviations_json.txt](https://github.com/citation-style-language/styles/files/2832966/aja_abbreviations_json.txt)
> This should be renamed abbreviations.json and placed in the top level of the user's Zotero folder.

Great, thanks. I uploaded this file at https://github.com/citation-style-language/abbreviations/blob/master/american-journal-of-archaeology/abbreviations.json. Clicking the "Raw" button gives you the actual file: https://raw.githubusercontent.com/citation-style-language/abbreviations/master/american-journal-of-archaeology/abbreviations.json

Can you also tell us where you found the list of AJA abbreviations?

**Pull request merged**
