### PR TITLE
Create Associação Brasileira de Normas Técnicas - Faculdade de Medicina ...

### PR DESCRIPTION
**Pull request by saufmvz**
...Veterinária e Zootecnia - USP (Portuguese - Brazil)

### CODE REVIEW

**Comment by rmzelle** [comment]
Can you start by visiting https://github.com/saufmvz/styles/blob/patch-3/Associa%C3%A7%C3%A3o%20Brasileira%20de%20Normas%20T%C3%A9cnicas%20-%20Faculdade%20de%20Medicina%20Veterin%C3%A1ria%20e%20Zootecnia%20-%20USP%20(Portuguese%20-%20Brazil)? Please click the pencil icon, and change the style's **file name** from "Associação Brasileira de Normas Técnicas - Faculdade de Medicina Veterinária e Zootecnia - USP (Portuguese - Brazil)" to "associacao-brasileira-de-normas-tecnicas-usp-fmvz.csl". Thanks.

See also https://help.github.com/articles/renaming-a-file/

**Comment by saufmvz** [comment]
Rintze, please disconsider number 1510. The file name was incorrect. Sorry. I thing the number # 1519 is ok now. Thank

**Comment by rmzelle** [comment]
You can still fix this pull request by changing the file name, by following my instructions above.

You were able to make a change, but you changed the style's title, not the file name.

**Comment by saufmvz** [comment]
Rintze I will try again. I'm librarian. Thank you again.

**Comment by saufmvz** [comment]
Rintze, do I think that the file name is correct now of #1510.

**Comment by rmzelle** [comment]
Great. There are just a few more things to change. Please use the pencil icon at https://github.com/saufmvz/styles/blob/patch-3/associacao-brasileira-de-normas-tecnicas-usp-fmvz.csl, and change:

* the title from "Associacao Brasileira de Normas Tecnicas - Faculdade de Medicina Veterinaria e Zootecnia - USP (Portuguese - Brazil)" to "Associação Brasileira de Normas Técnicas - Faculdade de Medicina Veterinária e Zootecnia - USP (Portuguese - Brazil)" (we want to keep the diacritics)
* `<id>http://csl.mendeley.com/styles/132518531/ABNT-FMVZ-USP-100</id>` to `<id>http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-usp-fmvz</id>`.
* `<link href="http://csl.mendeley.com/styles/132518531/ABNT-FMVZ-USP-100" rel="self"/>` to `<link href="http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-usp-fmvz" rel="self"/>` 
* please add a documentation link (see point 10 at https://github.com/citation-style-language/styles/wiki/Style-Requirements )
* `<category field="generic-base"/>` to `<category field="medicine"/>`

Finally, please change

```
   <author>
      <name>Alberto Massao Kawai</name>
      <email>alberto.kawai@gmail.com</email>
    </author>
    <contributor>
      <name>Alberto Kawai</name>
      <uri>http://www.mendeley.com/profiles/alberto-kawai/</uri>
    </contributor>
```

to

```
   <author>
      <name>Alberto Massao Kawai</name>
      <email>alberto.kawai@gmail.com</email>
      <uri>http://www.mendeley.com/profiles/alberto-kawai/</uri>
    </author>
```

**Comment by saufmvz** [comment]
Rintze,

please, which is the next step?

**Comment by rmzelle** [comment]
Is there a link you could give us that describes your citation format (i.e., what references should look like)?

**Comment by saufmvz** [comment]
Rintze, we have a link in portuguese language http://bibliotecafmvzusp.blogspot.com.br/ and http://www.fmvz.usp.br/biblioteca-www  (here you must click in veja + > left side Mendeley). Is there enought?  The  FMVZ style  is different because de citation must be in cronological order and the reference list above 4 authors must mencioned all of them. Thank you.

**Comment by rmzelle** [comment]
Can you add a second "documentation" link to http://www.fmvz.usp.br/biblioteca-www ?

**Comment by saufmvz** [comment]
Yes.

**Comment by rmzelle** [comment]
(you can use the same https://github.com/saufmvz/styles/blob/patch-3/associacao-brasileira-de-normas-tecnicas-usp-fmvz.csl link)

**Comment by saufmvz** [comment]
OK

**Comment by rmzelle** [comment]
(just change

```
    <link href="http://www3.fmvz.usp.br:8080/index.php/site/content/download/12588/50514/file/Estilo%20FMVZUSP%20Mendeley.pdf" rel="documentation"/>
```

to

```
    <link href="http://www3.fmvz.usp.br:8080/index.php/site/content/download/12588/50514/file/Estilo%20FMVZUSP%20Mendeley.pdf" rel="documentation"/>
    <link href="http://www.fmvz.usp.br/biblioteca-www" rel="documentation"/>
```
)

**Comment by saufmvz** [comment]
OK, Alberto Kawai is our collaborator (job friend) and he will made the alterations.

**Comment by saufmvz** [comment]
Rentze, I think that is ok now

**Comment by rmzelle** [comment]
Great, thanks!

**Comment by saufmvz** [comment]
Rintze its means that FMVZ style will be publicated together others styles? Its means that will be shared at the public repository ? Thanks

**Comment by saufmvz** [comment]
Thank you very much for your precious attention.

**Comment by rmzelle** [comment]
> Rintze its means that FMVZ style will be publicated together others styles? Its means that will be shared at the public repository ?

Yes, it's already available at https://www.zotero.org/styles?q=fmvz now (and within a day or two from within Mendeley as well).

**Comment by saufmvz** [comment]
Thanks, thanks, thanks. Finally!!!. I ´m so very happy!!

**Comment by rmzelle** [comment]
You're welcome!

**Comment by rmzelle** [comment]
@saufmvz, can you tell me what the et-al abbreviation rules should be for the references in the bibliography? The style currently uses `<bibliography et-al-min="0" et-al-use-first="1">`, which isn't correct. "et-al-min" specifies the minimum numbers of authors before et-al abbreviation kicks in, and "et-al-use-first" is the number of authors to show before "et al." in case of et-al abbreviation. A value of "0" for et-al-min doesn't make sense.

**Pull request merged**
