### PR TITLE
Change style to dependent style based on APA

### PR DESCRIPTION
**Pull request by libora**
Cititon style of yournal Ekonomie a management was changed to APA (see http://www.ekonomie-management.cz/en/detail-instructions-for-authors/)

### CODE REVIEW

**Comment by rmzelle** [comment]
Travis is unhappy because the dependent style isn't in the "dependent" subdirectory. You can move it yourself by clicking the edit icon at https://github.com/libora/styles/blob/patch-29/ekonomie-a-management.csl and following the instructions at https://github.com/blog/1436-moving-and-renaming-files-on-github

**Comment by libora** [comment]
Sorry I forgot it. Now it should be OK.

2015-05-13 19:46 GMT+02:00 Rintze M. Zelle <notifications@github.com>:

**Comment by rmzelle** [comment]
Thanks. But you didn't have to change the style ID and self link.

**Comment by libora** [comment]
Are you sure? I see this changes in my patch29 branch. Have I do anyhinkg?

<?xml version="1.0" encoding="utf-8"?><style xmlns="
http://purl.org/net/xbiblio/csl" version="1.0" default-locale="en-US">
<info> <title>Ekonomie a Management</title> <title-short>E+M</title-short>
<id>http://www.zotero.org/styles/dependent/ekonomie-a-management</id> <link
href="http://www.zotero.org/styles/dependent/ekonomie-a-management"
rel="self"/> <link href="http://www.zotero.org/styles/apa"
rel="independent-parent"/> <link href="
http://www.ekonomie-management.cz/en/detail-instructions-for-authors/"
rel="documentation"/>

2015-05-14 15:55 GMT+02:00 Rintze M. Zelle <notifications@github.com>:

**Comment by rmzelle** [comment]
You should revert those changes. The style IDs for dependent and independent styles are the same.

**Comment by libora** [comment]
Sorry, I am really silly. I use structure of pathway form github not from
zotero repozitory. I hope that now it is correct.

2015-05-14 18:48 GMT+02:00 Rintze M. Zelle <notifications@github.com>:

**Comment by rmzelle** [comment]
No problem!

Is it correct that the new style format if US English? The value of `default-locale` could be changed to the locale code for Czech, if you need a Czech version of APA.

**Comment by libora** [comment]
Journal change language of articles to English, articles in czech will not
accepted. So I change default locale.

2015-05-14 19:11 GMT+02:00 Rintze M. Zelle <notifications@github.com>:

**Comment by rmzelle** [comment]
Great, then we're all set! Thanks!

**Pull request merged**
