### PR TITLE
Medizinische Fakultät Mannheim - Numerisch

### PR DESCRIPTION
**Pull request by Director84**
Zitierstil für Dissertationen und Forschungsarbeiten an der medizinischen Fakultät Mannheim der Universität Heidelberg. Numerische Variante, basiert auf dem Stil des Journal of the American Society of Nephrology.
Ebenfalls zulässig ist der Zitierstil der Zeitschrift "Cell" (Autor-Jahr-Prinzip) und für Arbeiten in der Psychiatrie ist der APA-Style vorgeschrieben.

### CODE REVIEW

**Comment by Director84** [comment]
I don't see what the issue is, now that I deleted all files but the CSL itself.

**Comment by rmzelle** [comment]
Thanks! I made some minor changes to the style title and file name to align them better with the other styles in our repository. I attached the files you tried to upload in this comment. It's good to have them on hand, but we wouldn't add them to the repository itself.

(style per the "Richtlinien für die Abfassung der Dissertation" at https://www.umm.uni-heidelberg.de/fakultaet/promotion/promotion-dr-med/)

See also:
[documentation_medizinische-fakultat-mannheim.pdf](https://github.com/citation-style-language/styles/files/4038668/documentation_medizinische-fakultat-mannheim.pdf)
[drive-download-20200109T050131Z-001.zip](https://github.com/citation-style-language/styles/files/4038667/drive-download-20200109T050131Z-001.zip)

**Comment by Director84** [comment]
Thank you!

I will change the documentation PDF then to accommodate the new name and URL and send it to the faculty's library. Maybe they can put it up on the linked website, together with the repository link, next to the Endnote stuff.

I will also post the new file in a comment here.

I noticed the preview on the repository website does not render the non-breaking spaces, but displays their html-code instead. In LibreOffice the bibliography renders correctly though.
I don't know if that has to be fixed?

**Comment by Director84** [comment]
Here's the updated documentation and the other files in a zip.

[documentation_medizinische-fakultat-mannheim.pdf](https://github.com/citation-style-language/styles/files/4039255/documentation_medizinische-fakultat-mannheim.pdf)

[Aux-Files_medizinische-fakultät-mannheim.zip](https://github.com/citation-style-language/styles/files/4039254/Aux-Files_medizinische-fakultat-mannheim.zip)

**Comment by Director84** [comment]
Sorry, had to make another correction to the documentation.

[documentation_medizinische-fakultat-mannheim.pdf](https://github.com/citation-style-language/styles/files/4039296/documentation_medizinische-fakultat-mannheim.pdf)

**Pull request merged**
