### PR TITLE
Create politique-europeenne.csl

### PR DESCRIPTION
**Pull request by Lauriebeaudonnet**
Creation of a new style. It is used by the journal Politique Européenne (European studies academic journal in French and English)

### CODE REVIEW

**Review by Lauriebeaudonnet — COMMENTED** [review]
Hello, I have reviewed the changes, and I agree with them. I am not sure what I should do next?
Thank you
Laurie

**Comment by adam3smith** [comment]
(For future reference: journal is bilingual English & French

**Comment by adam3smith** [comment]
Sorry for the delay here!

**Comment by Lauriebeaudonnet** [comment]
Thank you very much :)

**Pull request merged**
