### PR TITLE
Create vancouver-brackets-noURL.csl

### PR DESCRIPTION
**Pull request by djibe89**
Vancouver citation styles with brackets for citations and URL references only for webpages

### CODE REVIEW

**Comment by djibe89** [comment]
Yes indeed.
In University of Lille 2 (France), academic professors don't like when there are http:// in the References.
But if you store URL to the article for future re-access to the article, you are in a dilemma. Store it or hide it from Bibliography.
My style allows to store URL of article, guideline and no Bibliography mess with http://.

**Comment by djibe89** [comment]
Yes for Zotero.
I understand, but many of the people in my University find it very helpful.

**Comment by rmzelle** [comment]
> In University of Lille 2 (France), academic professors don't like when there are http:// in the References.

Is this preference described in an official style guide from the university?

**Comment by djibe89** [comment]
No. Just Vancouver.
But Professors always tell us to stop having http and using brackets to cite.
You can delete if you want.
I dfon't wanna spoil your time

**Comment by adam3smith** [comment]
Thanks -- given that, I don't think we'll take this for the repository. However, as long as you don't change it in your github repository, your file will still be available, and you can pass on the link https://raw.githubusercontent.com/djibe89/styles/95c93325e3f7a2ea0b1f22186d12559cd438bf91/vancouver-brackets-nourl.csl to your colleagues.

We really do appreciate you submitting this, though.

**Pull request closed without merging**
