### PR TITLE
Update university-of-bradford-harvard.csl

### PR DESCRIPTION
**Pull request by dzacca**
Updated the style to correct the formatting of the titles in line with the guidelines from the University of Bradford.

### CODE REVIEW

**Comment by adam3smith** [comment]
I'm a bit confused about the rational for this change. In the Bradford brief guide to Harvard, I see e.g.

> Foreman, J. L. and Gubbins, E. J. (2015) Teachers see what ability scores cannot: predicting
student performance with challenging mathematics. _Journal of advanced academics_ 26(1), 5-23

i.e. the title not in italics, in line with what the current style is doing. What error exactly are you trying to fix?

**Comment by rmzelle** [comment]
@dzacca, as per @adam3smith request, could you give an example citation that demonstrates what the style currently does wrong?

**Comment by dzacca** [comment]
Hi @rmzelle , hi @adam3smith ,

the original style would produce the following:

(Atrill and McLaney 2017)
Atrill, P and McLaney, E 2017, Accounting and Finance for Non-Specialists with MyAccountingLab, 10th ed, Pearson Education Australia.

The title is not in italic and this does not comply with the University of Bradford's requirement.

The amended style produces the following:

(Atrill and McLaney 2017)
Atrill, P and McLaney, E 2017, _Accounting and Finance for Non-Specialists with MyAccountingLab_, 10th ed, Pearson Education Australia.

I actually just spotted a missing separator before the year so I'll have to submit a new patch

**Comment by rmzelle** [comment]
@dzacca, thanks for giving that example. While you're right that book titles should be italicized (per https://www.brad.ac.uk/library/find-out-about/referencing/referencing/referencing-books-and-book-chapters/), journal article titles shouldn't be (per https://www.brad.ac.uk/library/find-out-about/referencing/referencing/referencing-journal-articles/).

Your pull requests currently use italics for all titles, so that's not correct.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
