### PR TITLE
Vertical align fix

### PR DESCRIPTION
**Pull request by adam3smith**
using 
`perl -0777 -i -p -e 's/(layout.*)(>\n\s*)<text
variable=\"citation-number\" vertical-align=\"sup\"/$1 vertical-align=\"sup\"$2<text variable=\"citation-number\"/' ./*.csl`
then manually correcting for the too permissive regex.
(and no, I don't really know how to perl...)

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle -- I think this is ready, but leaving for you to merge for 2nd set of eyes.

**Comment by rmzelle** [comment]
You'd probably want to revert american-institute-of-aeronautics-and-astronautics.csl, american-institute-of-physics.csl, international-journal-of-sports-medicine.csl, pediatric-anesthesia.csl, and revista-virtual-de-quimica.csl. (all have changes in the bibliography)

**Comment by rmzelle** [comment]
And with my own jEdit find-regex of `^.*variable="citation-number".*vertical-align="sup"(.*\n)*.*</citation>` I found 47 styles with `vertical-align="sup"` following `variable="citation-number".` in the citation section (https://forums.zotero.org/discussion/comment/262999/#Comment_262999).

**Comment by rmzelle** [comment]
Thanks :)

**Comment by rmzelle** [comment]
(I'm surprised we didn't get more complaints about this, by the way, seeing how common this pattern was)

**Comment by adam3smith** [comment]
I think these were mostly 2nd tier Elsevier journals (the mistake was introduced by one of their folks who checked styles), so not exactly our most popular styles, but yes, I would have thought we'd get a few more reports, too.

**Comment by rmzelle** [comment]
I added a note in the QC wiki: https://github.com/citation-style-language/styles/wiki/Quality-Control/_compare/4d1191512d82508703987471ccb7c132a0f506e6...96ee92a5546cc17570922f99299a72aa6d6d38db

**Pull request merged**
