### PR TITLE
Create ancilla-juris.csl

### PR DESCRIPTION
**Pull request by gutp**
Style for the Open Access-Journal Ancilla Juris, http://www.anci.ch/
Styleguide: http://www.anci.ch/articles/AncillaIuris_StyleGuide.pdf

### CODE REVIEW

**Comment by adam3smith** [comment]
Did you start with an existing style when working on this? If so, which?

**Comment by gutp** [comment]
> 
> 
> Did you start with an existing style when working on this? If so, which?

I guess it was https://www.zotero.org/styles/juristische-zitierweise-schweizer

**Comment by adam3smith** [comment]
@rmzelle good to merge from my end

**Comment by gutp** [comment]
What do I have to do next?
Thanks.

**Comment by adam3smith** [comment]
@gutp nothing from your end
@rmzelle could you please check over the metadata & merge?

**Comment by rmzelle** [comment]
Thanks, and sorry for the long wait! (the journal name seems to be "Ancilla Iuris", not "Ancilla Juris")

(@adam3smith, I recently enabled Gmail labels for GitHub mentions, so my mentions don't get lost among all the other GitHub notification emails; see https://gist.github.com/ldez/bd6e6401ad0855e6c0de6da19a8c50b5#mentions)

**Comment by gutp** [comment]
> Thanks, and sorry for the long wait! (the journal name seems to be "Ancilla Iuris", not "Ancilla Juris")
> 
> (@adam3smith, I recently enabled Gmail labels for GitHub mentions, so my mentions don't get lost as easily among all the other GitHub notification emails; see https://gist.github.com/ldez/bd6e6401ad0855e6c0de6da19a8c50b5#mentions)

Thank you very much!

**Pull request merged**
