### PR TITLE
Create journal-of-international-peacekeeping.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/78795/style-request-journal-of-international-peacekeeping

### CODE REVIEW

**Comment by POBrien333** [comment]
A new edition of Patrick vs CMoS. I need your help, @rmzelle:
How do I remove the comma between title-note and container-contributors-note in without effing up the whole style?.
Before:
Isabela Mares, ‘Firms and the Welfare State: When, Why, and How Does Social Policy Matter to Employers?’, in Peter A. Hall and David Soskice (ed.), Varieties of Capitalism. The Institutional Foundations of Comparative Advantage (New York: Oxford University Press, 2001), pp. 184–213.
After:
Isabela Mares, ‘Firms and the Welfare State: When, Why, and How Does Social Policy Matter to Employers?’ in Peter A. Hall and David Soskice (ed.), Varieties of Capitalism. The Institutional Foundations of Comparative Advantage (New York: Oxford University Press, 2001), pp. 184–213.

**Comment by POBrien333** [comment]
@adam3smith Can you help me? :)

**Comment by adam3smith** [comment]
I'd have to look at the code & requirements in detail, but the basics are to add another group, i.e. take

```
 <group delimiter=", ">
   <group delimiter=", ">
     <text macro="contributors-note"/>
     <text macro="title-note"/>
     <text macro="issue-map-graphic"/>
   </group>
   <text macro="description-note"/>
   <text macro="container-contributors-note"/>
   <text macro="secondary-contributors-note"/>
   <text macro="container-title-note"/>
  </group>
```

Turn into something like


```
<group delimiter=", ">
  <group delimiter=" ">
    <group delimiter=", ">
       <text macro="contributors-note"/>
       <text macro="title-note"/>
       <text macro="issue-map-graphic"/>
     </group>
    <text macro="container-contributors-note"/>
  </group>
  <text macro="description-note"/>
  <text macro="secondary-contributors-note"/>
  <text macro="container-title-note"/>
</group>
```

**Comment by POBrien333** [comment]
Thanks @adam3smith ! :)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
