### PR TITLE
Create zeitschrift-fur-theologie-und-philosophie.csl

### PR DESCRIPTION
**Pull request by knorb**
A new style for a new journal (https://ztp.jesuiten.org/). The default locale is German since most papers will be in German. There is an option to switch to English for English submissions.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by knorb** [comment]
> Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

I used my own styles to build this new one, for example theologie-und-philosophie.csl. I will add this template link. The journal "Theologie und Philosophie", by the way, is merging with another journal to "Zeitschrift für Theologie und Philosophie." Shall we keep the style of the old journal in the repository?

**Comment by rmzelle** [comment]
> The journal "Theologie und Philosophie", by the way, is merging with another journal to "Zeitschrift für Theologie und Philosophie." Shall we keep the style of the old journal in the repository?

Is this mentioned somewhere on their website?

We generally only keep styles for active journals that accept submissions. If a journal is discontinued or merged we'd delete the style.

**Comment by knorb** [comment]
Sure, this is mentioned on the homepage of the new journal ztp.jesuiten.org, first sentence! This means you can delete the old style.

**Comment by rmzelle** [comment]
> Sure, this is mentioned on the homepage of the new journal ztp.jesuiten.org, first sentence! This means you can delete the old style.

Do you know if the old "Theologie und Philosophie" journal has already stopped accepting submissions? It looks like the new one will only start in January of next year?

> "Die Zeitschrift für Theologie und Philosophie (ZTP) führt ab Januar 2021 die beiden renommierten Fachzeitschriften Theologie und Philosophie (ThPh) und Zeitschrift für katholische Theologie (ZKTh) im Format eines Online-Fachjournals weiter."

**Comment by knorb** [comment]
OK, that's true. There is nothing said on the website of the old journal that they have already stopped accepting submissions (https://www.sankt-georgen.de/forschung/zeitschrift-theologie-und-philosophie/). Let's maybe still keep the old style.

**Comment by rmzelle** [comment]
> There is nothing said on the website of the old journal that they have already stopped accepting submissions (https://www.sankt-georgen.de/forschung/zeitschrift-theologie-und-philosophie/). Let's maybe still keep the old style.

Okay, in that case I can just merge this as-is. Thanks!

**Pull request merged**
