### PR TITLE
Create uoy-modern-language-association-8th-edition-1.csl

### PR DESCRIPTION
**Pull request by AVWoman**
University of York MLA 8th style

### CODE REVIEW

**Comment by adam3smith** [comment]
Please, before your issue any more pull requests, let's discuss this here.

**Comment by adam3smith** [comment]
Can I inquire why you do need custom styles if you're following the style manuals anyway? We do know that some universities have custom versions of such styles, but 5 such styles honestly seems excessive to me and I'm not sure we'd want to host them. Moreover, we very actively maintain the standard styles, but wouldn't touch your custom versions, so they wouldn't benefit from general improvements.

So could you briefly explain what your goal is with these styles and we can see how we can best meet your (and your students') needs.

CC @rmzelle

**Comment by AVWoman** [comment]
​Hi,



This is my first attempt at uploading these to github, so sorry if I’ve
spammed you with them!



I’m afraid we have 10 styles at York (departments are able to set their
own), and all 10 differ to some extent from the standard styles. We’ve
therefore put these versions together from the university’s interpretations
of the styles as given in our Integrity guide.



We have UoY versions of our styles for EndNote, and we’re wanting to mirror
this in CSL so that our students can easily use their departmental styles
in any reference manager. Ideally, therefore, we’d like our styles
available from the github collection, as importing custom styles isn’t
straightforward in some reference managers.



I’ll feed back your comments regarding the excessive number of custom
styles, and I appreciate any advice you can offer.



Many thanks,

Steph









*Stephanie Jesper*

Teaching & Learning



Information Services

Harry Fairhurst Building
University of York​

**Comment by adam3smith** [comment]
@rmzelle what's your view on this? I'm personally quite leery about accepting that many custom styles for a single university -- both because they clutter up the repository and because they create some level of expectation that we at a minimum fix them as issues arise. On the other hand, I'm glad to see universities working on this and down want to be unnecessarily obstructionist. @AVWoman which products are you looking at? Mendeley and Zotero, I assume, anything else?

**Comment by AVWoman** [comment]
Thanks Sebastian.
We specifically support Paperpile and Mendeley, but we're open to people
using anything, and encourage them to use whatever they prefer -- which is
why ideally we'd have the styles as findable as possible for our students.
Thanks for all your help,
Steph

**Comment by rmzelle** [comment]
> we have 10 styles at York (departments are able to set their own), and all 10 differ to some extent from the standard styles. We’ve therefore put these versions together from the university’s interpretations of the styles as given in our Integrity guide.

@AVWoman, do you have a list of names of these 10 styles? And is this Integrity guide available online? We always try to link to the style guide in the repository styles with a "documentation" link.

**Comment by AVWoman** [comment]
The styles are at https://drive.google.com/open?id=
0BzJhtoenpOu3dlMwSmV5RUduRFE and the Integrity guide is at
https://www.york.ac.uk/students/studying/develop-your-skills/study-skills/
study/integrity/referencing-styles/

We've got APA, Chicago, Harvard (x3), IEEE, MHRA, MLA, OSCOLA and Vancouver.
I don't know to what extent they differ from the official styles -- I
expect in some cases only slightly.

**Comment by rmzelle** [comment]
> The styles are at https://drive.google.com/open?id=0BzJhtoenpOu3dlMwSmV5RUduRFE and the Integrity guide is at https://www.york.ac.uk/students/studying/develop-your-skills/study-skills/study/integrity/referencing-styles/

Thanks! That's very helpful.

> We've got APA, Chicago, Harvard (x3), IEEE, MHRA, MLA, OSCOLA and Vancouver. I don't know to what extent they differ from the official styles -- I expect in some cases only slightly.

But you're certain that these UoY styles, in particular the APA, Chicago, IEEE, MHRA, MLA, and OSCOLA ones (which all have clearly defined official style guides), have differences from the official versions?

**Comment by AVWoman** [comment]
I just checked with the person who adapted the styles, and yes, each one
required some modification (whether our integrity pages are off-style by
accident, design, or just a failure to keep up, is hard to say!). The
Harvards required the most work, for obvious reasons.

Thanks,
Steph

**Comment by rmzelle** [comment]
Great, thanks.

@adam3smith, I'm fine with taking these, then. I touched up the current style a little in terms of naming. Good to go from my point of view. Will you merge?

**Comment by AVWoman** [comment]
Thanks. How would you like me to proceed then? Should I just add them as I
was doing, but follow those naming conventions?

**Comment by rmzelle** [comment]
> How would you like me to proceed then? Should I just add them as I was doing, but follow those naming conventions?

Let's wait with preparing any more pull requests until we hear back from my fellow maintainer @adam3smith, but yes, that would be the way to go. (you can also submit multiple styles in a single pull request, and I can explain how later)

**Comment by adam3smith** [comment]
Yes, that's fine, go ahead.

**Comment by rmzelle** [comment]
Okay, great. @AVWoman, if there is no particular hurry, I'll add your styles in the next few days (probably the weekend). I can probably create a pull request for the remaining 8 styles myself using the styles from your Google Drive, so no action is required on your part right now. I'll merge them after giving you a chance to review.

**Comment by AVWoman** [comment]
@rmzelle Cheers - that's much appreciated. Best wishes, Steph

**Comment by rmzelle** [comment]
APA variant added in #3056.

**Comment by rmzelle** [comment]
I created a pull request for the other 8 styles at https://github.com/citation-style-language/styles/pull/3073. I fixed all the styles to British English, and standardized the naming a bit.

@AVWoman, I had to correct the et-al settings for the Harvard Environment variant, which were incorrect CSL. For bibliographic entries with 11 or more authors, now the first 10 are shown followed by et al. Let me know if that's not correct.

@AVWoman, @adam3smith, can you give https://github.com/citation-style-language/styles/pull/3073 a quick look-over?

**Comment by AVWoman** [comment]
@rmzelle Thanks -- that's what it's supposed to do, so thanks for
correcting it!

**Comment by rmzelle** [comment]
@AVWoman, I merged the remaining styles. See https://www.zotero.org/styles?q=university-of-york

Please start from the latest repository copies whenever you make further updates. That makes it easier to accept changes.

**Comment by AVWoman** [comment]
​​@rmzelle Thanks for this - it's much appreciated. All the best, Steph.

**Pull request merged**
