### PR TITLE
Create wiley-was.csl

### PR DESCRIPTION
**Pull request by Kruszynski**
I modified Wiley-VHC and added a style (website) that was not included before.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks and sorry for the delay here. Could you explain more what this style is for specifically? I know what WAS is, but I don't see any reference formatting guidelines there.

**Comment by Kruszynski** [comment]
Hi, 
no worries. Thanks for your question. 
WAS Magazine is composed of commissioned articles only, thus we only send the guidelines to authors when we approach them. That is why there are no guidelines on the website. This might change soon when we finalize the reference style. Our intentions with this style are to simplify our authors' submissions and also use the style in the other 3 magazines within the hub (GIT Labor-Fachzeitschrift, Imaging & Microscopy, and Microscopy Analysis).
Although we are different from peer-review journals, I believe having this style ready will benefit not only the authors but also will speed up the editorial process.
I hope this answers your question. Please let me know if I can help you with anything else.

**Comment by Kruszynski** [comment]
Hi,
when can I expect this to be done? I wanted to give my manager an estimation. Thank you.

**Comment by adam3smith** [comment]
Sorry for the wait -- this is a bit of a borderline case, which is why things are taking unusually long. As per our[ criteria for inclusion](https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md), we don't necessarily host styles for publications with closed submission. Given the range of journals this would apply to, I'd be inclined to be flexible here, but we would really want a publicly accessible style guide: we can't host styles for which we are unable to assess error reports (i.e. compare output against guidelines).

**Comment by Kruszynski** [comment]
Hi, I'm not sure I understand your comment. This will be publicly available.
I am just waiting for this to be able to be used for us to publish the guidelines for authors online. 
Our magazines are published online without fees so you will be able to access errors. Does that answer your question?

**Comment by adam3smith** [comment]
> I am just waiting for this to be able to be used for us to publish the guidelines for authors online.

I don't quite understand why you need a CSL style hosted here in order to publish author guidelines? If you look at existing styles, virtually all of them have a link to the style guide where the publisher tells authors how to format references -- these logically predate the CSL style. You can't an automated citations style before the style itself exists ;)

**Comment by Kruszynski** [comment]
Hi, 
We have now added the author guidelines we send every author on our website as instructed https://analyticalscience.wiley.com/publication/was-magazine. Do you need anything else?

**Comment by adam3smith** [comment]
Thanks -- so metadata-wise this is good to merge now, but if you look at the automatic citation preview, the website looks off:

> [2] (2012). http://editor.citationstyles.org/searchByExample/.

What is this supposed to be? Just the URL?

**Comment by Kruszynski** [comment]
Hi, 
We often have people cite the website, so I just added the URL and year if they want to add that. Is that ok?

**Comment by adam3smith** [comment]
So, sorry, I thought I had merged this after the latest exchange.

**Comment by Kruszynski** [comment]
Dear all,
I need to request an edit to this style. Could you advise me on what to do?
1) I need to add "et al." in italics.
2) I need to add the DOI as a link to the article and not only plain text.
Thank you in advance.

Best
Cecilia

**Comment by bwiernik** [comment]
@Kruszynski I made those updates here https://github.com/citation-style-language/styles/pull/7050

**Pull request merged**
