### PR TITLE
Create reproduction-fertility-and-development.csl

### PR DESCRIPTION
**Pull request by okingfisher**
A new CSL for the journal Reproduction, Fertility and Development (http://www.publish.csiro.au/rd/AbouttheJournal). Based in the Journal of Biogeography CSL. Not sure about Communication references correctness.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- I'd actually suggest you go back and modify https://github.com/citation-style-language/styles/blob/master/international-journal-of-wildland-fire.csl instead to get this style. It's by the same publisher and almost correct already (only think I see that's wrong are the authors). There are a number of unorthodox choices (and some things that aren't quite right) and rather than fixing this all up in this version, you'll save time starting with a better template.

**Comment by okingfisher** [comment]
Redone from international-journal-of-wildland-fire.csl and resubmitted.

**Comment by okingfisher** [comment]
OK, looks right this time.

**Comment by okingfisher** [comment]
Looks right now...

**Comment by okingfisher** [comment]
OK, OK, now it seems right! some minor mistakes I overlooked...

**Comment by adam3smith** [comment]
Great, thanks!

**Pull request merged**
