### PR TITLE
Create oxford-university-press-note.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/73005/style-request-oxford-university-press-numbered-notes

### CODE REVIEW

**Comment by POBrien333** [comment]
yes. need to look into it more. Note style...

**Comment by POBrien333** [comment]
@adam3smith 
That should be it now. :)

**Comment by rmzelle** [comment]
@POBrien333, if this is OUP's only note style, I'd just call it "note" instead of "full note".

And is the absence of a "default-locale" on purpose? https://global.oup.com/academic/authors/author-guidelines/reference-styles/numbered-notes/?lang=en&cc=ch says "We give examples using US spelling and punctuation here.", so I assume they have British and US versions of this style?

(our existing OUP styles are fixed to either en-US or en-GB: https://www.zotero.org/styles?q=oxford%20university%20press )

**Comment by rmzelle** [comment]
> Locale: good spot. There are small differences. Access dates for example.

Where do you see these differences? Do they have a separate en-GB style guide?

**Comment by rmzelle** [comment]
@POBrien333, can you answer my question above?

**Comment by POBrien333** [comment]
Sorry.
Yes there are basically two guides that only differ in some punctuation regarding the access dates (see the Rambow examples in both guides).
UK: https://global.oup.com/academic/authors/author-guidelines/reference-styles/numbered-notes/?lang=en&cc=es
US (linked to at the bottom in the UK style guide): https://global.oup.com/academic/authors/author-guidelines/reference-styles/numbered-notes/?cc=es&lang=en&

**Comment by rmzelle** [comment]
> Yes there are basically two guides that only differ in some punctuation regarding the access dates (see the Rambow examples in both guides).

Any thoughts on what to do here?

If you can address the date localization in the locale sections of this independent style (with "en-US" and "en-GB" locale sections), we can fix this style to one of those two locales, and create a dependent style for the other.

**Comment by POBrien333** [comment]
@rmzelle 
Would it also be possible to not set a locale and then having the user choose in their document?

**Comment by rmzelle** [comment]
> Would it also be possible to not set a locale and then having the user choose in their document?

Sure, that works too. Do you know whether

> you can address the date localization in the locale sections of this independent style (with "en-US" and "en-GB" locale sections)

?

**Comment by POBrien333** [comment]
Yep. Will have a go at it. :)

**Comment by POBrien333** [comment]
@rmzelle 
Just checked. The style does everything correct already once the correct locale is chosen, so this should be ready to go as it is. :)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
