### PR TITLE
pull request for 5 style sheets

### PR DESCRIPTION
**Pull request by Sankar-GEO-ELS**
pull request for the following 5 style sheets
colombian-journal-of-anesthesiology.csl
radiography.csl
radiologic-clinics-of-north-america.csl
reports-of-practical-oncology-and-radiotherapy.csl
urological-science.csl

### CODE REVIEW

**Comment by rmzelle** [comment]
Looks great, thanks!

**Comment by Sankar-GEO-ELS** [comment]
Thanks. I have a question here "urological-science.csl" passed travis build, how to check other 4 pass travis build?

**Comment by rmzelle** [comment]
If you create a pull request that covers multiple commits, Travis CI will only check the most recent commit. https://github.com/Sankar-GEO-ELS/styles/commit/5af88ace64e8f2c13901face9d5d94e70529be36 contains all five styles, so they all passed the tests.

**Comment by Sankar-GEO-ELS** [comment]
OK. Thanks, I got it!

**Pull request merged**
