### PR TITLE
Create transboundary-and-emerging-diseases.csl

### PR DESCRIPTION
**Pull request by rhinotrope**
I created a style for the journal Transboundary and Emerging Diseases by modifying a similar style for a different journal.  It seems to be working properly except I haven't figured out how to properly create the website bibliography entry as shown in the author guidelines.  I am completely new to CSL and would appreciate a nudge in the right direction on how to add the URL.

### CODE REVIEW

**Comment by adam3smith** [comment]
@biosainik -- are you doing these approvals on purpose? I'm worried that's a bit confusing to other users.

@rmzelle -- we seemed to have dropped this one... I'll review tonight unless you get to it earlier.

**Comment by rmzelle** [comment]
> I haven't figured out how to properly create the website bibliography entry

@adam3smith, yes, I should have written something here, but I think I skipped it when I saw the remark above.

**Comment by biosainik** [comment]
@adam3smith @rmzelle  . I saw the style passed the tests but missed the comment above. Will see that this won't happen again. Will take more time and review. Sorry!

**Comment by rmzelle** [comment]
@biosainik, we appreciate your enthusiasm, but let's focus on your own pull requests first.

**Comment by damnation333** [comment]
here: https://github.com/citation-style-language/journals/pull/25

**Comment by rmzelle** [comment]
Added in #2447.

**Pull request closed without merging**
