### PR TITLE
Create associacao-brasileira-de-normas-tecnicas-ufrgs-alfab.csl

### PR DESCRIPTION
**Pull request by meiradarocha**
Brazilian ABNT rules as used by Universidade Federal do Rio Grande do Sul.

### CODE REVIEW

**Comment by rmzelle** [comment]
@meiradarocha, thanks for submitting!

We usually don't add descriptions like "alfabética" unless you're going to submit more than one style variant. Unless that's the case, could you:

* change the file name to "associacao-brasileira-de-normas-tecnicas-ufrgs.csl" (with ".csl" extension!)
* change the title to `<title>Associação Brasileira de Normas Técnicas - Universidade Federal do Rio Grande do Sul (Portuguese - Brazil)</title>`
* change the style ID and "self" link to "http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-ufrgs"

We also would like to have a "documentation" link. Do you have a link to the style guide for your university?

**Comment by rmzelle** [comment]
Thanks! Can you also change `<link href="https://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-ipea" rel="template"/>` to `<link href="http://www.zotero.org/styles/associacao-brasileira-de-normas-tecnicas-ipea" rel="template"/>` ("http" instead of "https")

**Comment by rmzelle** [comment]
Great, thanks!

**Comment by meiradarocha** [comment]
Thank you for your fast response. mr. rmzelle. 
I delete some unused macros, too.

**Pull request merged**
