### PR TITLE
Create college-of-naturopathic-medicine.csl

### PR DESCRIPTION
**Pull request by taffod**
created a new style to reflect this college's citation requirements

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks. I assume the reference guide isn't available online on the website of the college? Would it be possible to add a copy of the guide as an attachment to a GitHub comment here?

**Comment by taffod** [comment]
> Thanks. I assume the reference guide isn't available online on the website of the college? Would it be possible to add a copy of the guide as an attachment to a GitHub comment here?

No worries!  That's right the college doesn't publish the style guide - it's only to students that are logged in to their site, so I couldn't post a public link as a URL.  

I'll add it here as requested though.

Thank you.
[CNM Referencing Guide 2017-2018.pdf](https://github.com/citation-style-language/styles/files/2663061/CNM.Referencing.Guide.2017-2018.pdf)

**Comment by rmzelle** [comment]
Thanks!

**Comment by taffod** [comment]
I've amended the style to reflect some corrections in the et al numbers.  Here's the new version, not sure how best to upload and replace it sorry.  

[college-of-naturopathic-medicine 2019.txt](https://github.com/citation-style-language/styles/files/2718609/college-of-naturopathic-medicine.2019.txt)

**Comment by rmzelle** [comment]
> I've amended the style to reflect some corrections in the et al numbers. Here's the new version, not sure how best to upload and replace it sorry.

Thanks. I made the change: https://github.com/citation-style-language/styles/commit/14741acfff9d6b93d415d1a4abead54d3fd9ab37.

For future corrections, please follow our guidelines at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style.

**Pull request merged**
