### PR TITLE
Create international-body-psychotherapy-journal.csl (waiting for reply from editors)

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/comment/288471/#Comment_288471

apa.csl might not be the right version of APA. Let's see.

### CODE REVIEW

**Comment by rmzelle** [comment]
Are we certain we need an independent for this?

**Comment by POBrien333** [comment]
Yeah, as far as I understand he needs apa without DOI, but WITH issue.

**Comment by bwiernik** [comment]
I think we should contact the journal first. Given that the journal frequently includes DOIs in their papers, I would guess the poster is mistaken.

**Comment by POBrien333** [comment]
@bwiernik 
I have contacted them now. :)

**Comment by rmzelle** [comment]
@POBrien333, heard back yet?

**Comment by POBrien333** [comment]
No. I'm afraid no.

**Comment by POBrien333** [comment]
I'll close this for now. If I ever get an answer, we can reopen/merge.

**Pull request closed without merging**
