### PR TITLE
create oksident.csl

### PR DESCRIPTION
**Pull request by mtarakci**
Citation style for the Journal of Oksident. 

For citation examples, see
https://dergipark.org.tr/en/pub/oksident/page/14360

### CODE REVIEW

**Comment by mtarakci** [comment]
Sorry for the inconvenience. I haven't been here for a long time. I couldn't understand what went wrong.

**Comment by POBrien333** [comment]
You want the stylename, ID and self-link all to match.
From what I see it should be called oksident.csl or ...oksident for the two links.
Note also that you have the style in the "dependent" folder. You can move it out of there by hitting the backspace button while editing the filename.

**Comment by mtarakci** [comment]
Thank you @POBrien333 
I think I was able to make the changes you referred to. However, I could not transfer from the dependent folder. So, I have submitted a new file, but with no success. I apologize for submitting two different files.

**Comment by adam3smith** [comment]
superseded by #6380

**Pull request closed without merging**
