### PR TITLE
Add a citation style for the International Journal of Computer Supported Cooperative Work

### PR DESCRIPTION
**Pull request by kaitlyndoesresearch**
I've taken APA 7 and added the changes to contributor/author names; the labels for volume, issue, and page numbers; and no ampersands.
Specification is here: https://media.springer.com/full/springer-instructions-for-authors-assets/pdf/1649333_35755499_JCSCW%20Instructions%20for%20Authors%202022.pdf

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! What's wrong with the existing style for the journal though? https://www.zotero.org/styles?q=id%3Acomputer-supported-cooperative-work
that's pretty recent and looks in great shape to me.

**Comment by kaitlyndoesresearch** [comment]
The problem is that I didn't know it existed because it wasn't appearing in
the Mendeley CSL. Perhaps there is an importing issue for use in Mendeley
that isn't documented?

Thanks.

**Comment by adam3smith** [comment]
Oh, I'm *so* sorry you invested all the time. For some reason, Mendeley stopped updating their CSL styles almost 2 years ago. We have no idea what happened. You can ask them and encourage them to get in touch with us, but there's nothing we can do about this, unfortunately. 
Until it's fixed, I'd search on the Zotero repository and then install the style via URL from their or copy the code over.

**Comment by kaitlyndoesresearch** [comment]
Guess it's time to move to Zotero 😅

It's fine, I don't miss the time. I was on a time crunch, so it needed to
happen, and besides that, it was fun.

Thank you for clarifying.

**Pull request closed without merging**
