### PR TITLE
Added a style file for the IJSDIR

### PR DESCRIPTION
**Pull request by lorenzino**
Added a style file for the International Journal of Spatial Data Infrastructures Research (IJSDIR). More information here: http://ijsdir.jrc.ec.europa.eu/index.php/ijsdir/index

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks!

Could you:

* add the ISSN (`<issn>1725-0463</issn>`, see https://github.com/citation-style-language/styles/wiki/Style-Requirements#9---issn-and-eissn)
* add a default-locale (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#3---style-locale)
* it looks like you wrote this style from scratch, but if you did base it on another CSL style, please add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by lorenzino** [comment]
Thanks a lot for the support!
I've added the ISSN and the default-locale.
Regarding the source, I've made the csl from scracth.


Thanks again,
Cheers,
Lorenzino

**Comment by rmzelle** [comment]
Thanks!

And I forgot to ask, but could you run the style through our reformatter at http://formatter.citationstyles.org/? The indentation is currently a little inconsistent (sometimes 2 spaces per level, sometimes 3).

**Comment by rmzelle** [comment]
Perfect, thanks!

**Pull request merged**
