### PR TITLE
Chroniques efr

### PR DESCRIPTION
**Pull request by NMonteix**

### CODE REVIEW

**Comment by rmzelle** [comment]
@NMonteix, did you do this to get a non-breaking space? (for `prefix="§&#160;"`)

**Comment by rmzelle** [comment]
(if you're only concerned about the symbol, it's probably better to redefine `<term name="paragraph" form="symbol">` ; see https://github.com/citation-style-language/locales/blob/master/locales-en-US.xml#L196 )

**Comment by NMonteix** [comment]
Yes, in fact that was just about the symbol. Changes made. 
It seems that in French there is no proper symbol for sections, while § would be for paragraphs. Might need change in locales?

**Comment by rmzelle** [comment]
The French CSL locale file already uses § for paragraphs (see https://github.com/citation-style-language/locales/blob/master/locales-fr-FR.xml#L201), so there should be no need to redefine the term in the style.

**Comment by NMonteix** [comment]
Ok
Sorry, didn't check
Redefinition removed...

**Comment by NMonteix** [comment]
As for me, no more corrections needed

**Comment by adam3smith** [comment]
thanks!

**Comment by NMonteix** [comment]
To you!

**Pull request merged**
