### PR TITLE
Create the-korean-journal-of-mycology.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/92819/style-request-the-korean-journal-of-mycology#latest

Sample paper: http://www.kjmycology.or.kr/view/N0320490302.pdf

### CODE REVIEW

**Comment by adam3smith** [comment]
ah, too bad, that didn't work, I'll probably just put this into a new PR (or you can)

**Comment by retorquere** [comment]
For security reasons, sheldon refuses to run on PRs that attempt to change both the testing infra (the Gemfile in this case) and styles.

**Comment by retorquere** [comment]
Although we could make it so that if it's labeled safe to test Sheldon will allow mixed PRs.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
