### PR TITLE
Create johnson-matthey-technology-review.csl

### PR DESCRIPTION
**Pull request by coless82**
I hope someone can help perfect this style, we are not expert coders. 
The problems that we have are as follows:

Patents (Ref. 12 in the Mendeley example set)
Need to get the word <Patent> into italics and if possible, set up rules to specify if US, World, etc. and if Patent or Application, depending on the code. 

Patents (Ref. 12 in the example set)
Add assignees' details: inventor name(s), institution or company name

Examples:
H. Van Den Elzen, World Appl. 2011/129,992
also:
R. L. Pruett and J. A. Smith, Union Carbide Corporation, ‘Hydroformylation Process’, US Patent 3,527,809; 1970

Content types - report, thesis, book, chapter. (References 2, 3, 5, 8-11):
How to add the country to the publisher place? 

Reference 14: Webpage references
There is an extra space before the colon, we need to remove this extra space.

Dates with day and month - content types article-newspaper, webpage (References 7, 14)
We would like if possible a suffix on the day i.e. "st" for "1st, 21st," etc. and "nd" for "2nd, 22nd", etc and "rd" for "3rd, 23rd", "th" for "4th, 24th" etc. Is it possible?

Dates with day and month 
Also we would like a comma between the month and the year, if possible to do so, as:
15th April, 2015

Journal article (ref. 1)
“et al.” appears after 100 author names in journal article whereas we do not want to use "et al" at all, can it be removed?

### CODE REVIEW

**Comment by POBrien333** [comment]
Can you run your style through the formatter and then edit the PR here? currently it's all in one line. http://formatter.citationstyles.org/

**Comment by coless82** [comment]
Sorry about that. I thought I had done so. I was using IE - I just retried the formatter using Chrome and that seems to work better. How do I reupload the corrected file? 

Regards
Sara

**Comment by rmzelle** [comment]
The first comment you got on this pull request (https://github.com/citation-style-language/styles/pull/3319#issuecomment-364148882) describes how to update your submission.

**Comment by coless82** [comment]
Thanks I have done that now.

**Comment by coless82** [comment]
Hi, we'd like to start using the style for our authors in Mendeley, Zotero, etc. As this has now passed the tests is it ready? What do I need to do next? Thanks!

**Comment by coless82** [comment]
Hi, The style seems to be fixed, can anyone help me to get this approved? Does it need to be merged and who can help with this please? Many thanks.

**Comment by POBrien333** [comment]
@coless82 
Hi,
One of the 2 people who reviews the styles here is currently not as active.
@adam3smith might be able to help, but you can always just upload the .csl file onto your website and insert the link in your author guidelines, so your authors can access the style already.

**Comment by coless82** [comment]
Thanks @adam3smith and @POBrien333 . We have for now uploaded to our website as .txt file and added it to our Information for Authors. 

https://www.technology.matthey.com/for-authors/#references

**Comment by POBrien333** [comment]
@coless82 
I think it makes more sense to give the file as a .csl and not .txt. also you got all the + in each line.
You can literally use this link here: https://raw.githubusercontent.com/coless82/styles/9af13728ea04e913b95b4322aea98c8385b792da/johnson-matthey-technology-review.csl

**Comment by coless82** [comment]
Thanks @POBrien333 and @rmzelle for your help so far! We have updated the link on our website.

**Comment by rmzelle** [comment]
@coless82, sorry for letting this sit for so long. I just merged the style into the repository, and it should show up for Zotero and Mendeley users within the next 24 hours.

**Comment by coless82** [comment]
Thanks very much @rmzelle  and everyone who's helped us with this.

**Comment by POBrien333** [comment]
You can now also use this link to link to the latest style: https://www.zotero.org/styles?q=id%3Ajohnson-matthey-technology-review

**Pull request merged**
