### PR TITLE
Add dependents for hainan-medical-university-journal-publishing

### PR DESCRIPTION
**Pull request by damnation333**
See journals here: http://www.hnmujp.org/guide.html

As discussed here: https://forums.zotero.org/discussion/64839/asian-pacific-journal-of-tropical-disease-style-is-not-correct

I didn't add the Chinese version of JoHMU. Don't think that's alive.

Hope I did this right.
Do I always have to delete my own fork before making a new PR? Otherwise the fork is not up to date? I am asking, as all my files were 6 yrs old as that is when I had forked the first time. Thx

Also, why does it pull request for the "Create" and "Update" ones? Is that the way it's supposed to be?

### CODE REVIEW

**Comment by rmzelle** [comment]
> Hope I did this right.
> Do I always have to delete my own fork before making a new PR? Otherwise the fork is not up to date? I am asking, as all my files were 6 yrs old as that is when I had forked the first time. Thx

Well, it's usually not necessary to delete your fork (it's a good thing that you didn't have a lot of pull requests open, since I think deleting your fork makes it impossible to (easily) update any existing pull requests you created).

It looks like GitHub nowadays makes it possible to quickly create a pull request with multiple files in the first commit: https://github.com/blog/2105-upload-files-to-your-repositories. Alternatively, you can create a pull request like you normally do, by adding a single style to our repository, and then add the other files in separate followup commits.

You can also use git on your computer to update your master branch (GitHub for Windows/Mac makes that rather easy nowadays, I think), and then create a fresh branch off that updated master branch, and then create a pull request from that branch to our regular "master" branch. Generally it's better to avoid using the "master" branch in your fork directly for pull requests (like you did here), since that will make your "master" branch diverge from ours, which makes it harder to update later.

> Also, why does it pull request for the "Create" and "Update" ones? Is that the way it's supposed to be?

You get "Create" in the standard commit message if you add a file, and "Update" if you modify an existing file.

**Comment by rmzelle** [comment]
(and this PR is failing because 3 out of 5 dependents are not in the "dependent" subdirectory)

**Comment by damnation333** [comment]
>It looks like GitHub nowadays makes it possible to quickly create a pull request with multiple files in the first commit: https://github.com/blog/2105-upload-files-to-your-repositories. Alternatively, you can create a pull request like you normally do, by adding a single style to our repository, and then add the other files in separate followup commits.

thanks for clarifying. That seems slightly cumbersome, as I don't like to create files first and then upload them. I usually write/edit the stuff in the browser.
I don't see where I can add a followup commit to another file after starting a Pull Request. that sounds like what I'd like. Can you point me in the right direction? thanks.

**Comment by rmzelle** [comment]
> That seems slightly cumbersome, as I don't like to create files first and then upload them. I usually write/edit the stuff in the browser.

Yeah, it looks like GitHub's "Create new file" is limited to one file. You could ask them (https://github.com/contact) to make it possible to create multiple files that way, but most people probably just switch to a local git client at that point.

> I don't see where I can add a followup commit to another file after starting a Pull Request.

Well, for files already affected in the pull request, you can use the pencil icon at the top of the relevant file at https://github.com/citation-style-language/styles/pull/2582/files. To modify as-of-yet untouched files via the GitHub web interface, you need to navigate to the branch the pull request originates from (in this case, the "master" branch in your fork, since the top of this pull request says "damnation333  wants to merge 17 commits into citation-style-language:master from damnation333:master"), so that would be https://github.com/damnation333/styles/tree/master. Then make any additional changes there, and they will show up in the open pull request.

**Comment by rmzelle** [comment]
(I also forgot to mention that we could have generated these dependents via the "journals" repository; that might have been faster)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
