### PR TITLE
Update reproduction-in-domestic-animals.csl

### PR DESCRIPTION
**Pull request by okingfisher**
Corrections.

### CODE REVIEW

**Comment by adam3smith** [comment]
The guide for authors just says to use APA style -- any reason we shouldn't just link this directly to the existing APA style?

**Comment by okingfisher** [comment]
Sure, just found interesting to have a specific style for this journal.

**Comment by adam3smith** [comment]
We can still have a specific style and link it to APA http://docs.citationstyles.org/en/stable/specification.html#dependent-styles -- we'll do this, no need for you to figure out the details. Thanks for pointing out the error in the existing style!

**Comment by okingfisher** [comment]
Didn't know about that, good idea!

**Comment by adam3smith** [comment]
Closed via https://github.com/citation-style-language/styles/commit/4898c4047a40a6b9359233a44d5bbb1b6c756a6b

**Pull request closed without merging**
