### PR TITLE
Added bibliography tag to U-schylku citation

### PR DESCRIPTION
**Pull request by RomanZWang**
Intended to work with OSF.IO and for those that read information from bibliography tags in CSL files.

### CODE REVIEW

**Comment by rmzelle** [comment]
> Intended to work with OSF.IO and for those that read information from bibliography tags in CSL files.

Can you explain in a bit more detail what the link is between OSF and the journal U Schyłku Starożytności? The journal style doesn't include a bibliography, right? (it also looks like the journal might have been discontinued? Its last issue was in 2013)

**Comment by RomanZWang** [comment]
OSF.io is a web application that manages research projects. There is a citation widget that outputs a citation for project components given the citation style. The widget generates citation options in the dropdown for each citation file provided in citation-style-language, and formats the citation by reading from the information provided in the bibliography tags. 

I am not familiar too familiar with citations, bibliographies, and the polish language; so would you suggest changing the widget so it outputs something else for the citation format if it doesn't detect bibliography tags? Or remove the U Schyłku Starożytności csl file altogether, locally in OSF.IO?

**Comment by whit537** [comment]
I'm not sure this is the right approach to the OSF's problem (which is that *U Schyłku Starożytności* is not showing up as expected in the citation widget search box).

On the one hand, I find 23 out of 1,202 CSL files (2%) that seem not to have a bibliography:

```
$ ls *.csl | wc -l
    1202
$ grep -L '<bibliography' *.csl | wc -l
      23
$ grep -L '<bibliography' *.csl
art-history.csl
australian-historical-studies.csl
bluebook-inline.csl
bluebook-law-review.csl
bluebook2.csl
catholic-biblical-association.csl
early-medieval-europe.csl
ethics-book-reviews.csl
geopolitics.csl
history-and-theory.csl
iso690-note-cs.csl
journal-for-the-history-of-astronomy.csl
journal-of-applied-philosophy.csl
manchester-university-press.csl
medical-history.csl
oxford-art-journal.csl
past-and-present.csl
pisa-university-press.csl
studii-teologice.csl
the-historical-journal.csl
thomson-reuters-legal-tax-and-accounting-australia.csl
u-schylku-starozytnosci.csl
zeitschrift-fur-medienwissenschaft.csl
$
```

If the right approach with *U Schyłku Starożytności* is to add a bibliography element, then we should add bibliography elements for the other 22 as well.

On the other hand, however, it looks like Zotero.com/styles is handling *U Schyłku Starożytności* just fine. What do they know that OSF doesn't?

screen shot 2016-03-29 at 4 24 22 pm

**Comment by adam3smith** [comment]
No, I'd rather not "invent" a bibliography style where none exists. Zotero's preview just falls back to the citation where no bibliography exists. That'd seem to be an easy enough solution for OSF.io, no?

**Comment by rmzelle** [comment]
> On the one hand, I find 23 out of 1,202 CSL files (2%) that seem not to have a bibliography

It's not uncommon for note styles to not have a bibliography (in the "note" style format, the text contains footnotes or endnotes, with an optional bibliography at the end of the document/chapter listing the cited works again). (see http://docs.citationstyles.org/en/stable/primer.html#note-styles for a little bit more elaborate description)

**Comment by rmzelle** [comment]
(and yes, @adam3smith solution is good; alternative, you could remove all "note" styles from your collection)

**Comment by rmzelle** [comment]
So OSF.io uses CSL? :+1: (we try to keep track of all software products that use CSL on the http://citationstyles.org/ homepage)

**Comment by whit537** [comment]
> So OSF.io uses CSL?

@rmzelle Yes!

> (we try to keep track of all software products that use CSL on the http://citationstyles.org/ homepage)

Is the CSL homepage under https://github.com/citation-style-language/? It's not jumping out at me or I'd give you a PR. ;-)

**Comment by adam3smith** [comment]
no, our homepage is Wordpress, so no PRs there

**Comment by rmzelle** [comment]
No, just visit http://citationstyles.org/. The landing page has a few dozen software products on it that use CSL. We can add OSF if you'd like.

(ah, yes, I misunderstood the question; no, our website is not maintained on GitHub)

**Comment by whit537** [comment]
Okay, I'll leave that to you then. :-)

**Comment by whit537** [comment]
This can probably be closed. It sounds like we should take a different approach.

(P.S. I'm here as a code reviewer for OSF. :)

**Comment by rmzelle** [comment]
Okay. Thanks for stopping by :).

OSF is now listed at http://citationstyles.org/.

**Comment by whit537** [comment]
Thanks! Keep up the good work! :-)

**Pull request closed without merging**
