### PR TITLE
Create iso690-full-note-es.csl

### LINKED ISSUE #7059: Request for style ISO 690 FULL NOTE SPANISH
Hello, could you please create an style for ISO-690 in spansh full note, please?
Thank you very much in advance

### PR DESCRIPTION
**Pull request by POBrien333**
Closes #7059

### CODE REVIEW

**Comment by anamulopez** [comment]
Hello I have just checked the last file uploaded, i have issues with two types of documents.
First is the conference procceedings  which should be styled as the book chapters. 
Secondly is the generic type, which should be styled: Surname, Name (or first letter)+ name of work+ place+ date.
Could you fix it? please?
Thank you very much for your patience

**Comment by bwiernik** [comment]
@POBrien333 could you make the updates requested above ?

**Comment by POBrien333** [comment]
@anamulopez 
I've made some changes to fix the 2 issues. Can you check if it's all in order now?

**Comment by bwiernik** [comment]
merging for now

**Comment by anamulopez** [comment]
Hello! Thank you for all the changes. I was checking it and I found some issues.
Also I found a pdf of an Spanish university explaining how the iso 690:2024 works (newest version)
I took it everything in account and made a pdf linked in this message with all the modifications highlighted in red (both from the issues as well as the ones from the new version). I was wondering if you could please make them.
I was also wondering if we could get the cite style ready to cite also with ibid, idem and op.cit (it is also explained in the word file).
I am also uploading the presentation of the University of Sevilla explaining everything of the new version (may be useful)
in any case I am available to answer any doubts

Thank you very much again

[Modifications.pdf](https://github.com/user-attachments/files/17611185/Modifications.pdf)
[citas_y_referencias_eps_2024_1.pdf](https://github.com/user-attachments/files/17611189/citas_y_referencias_eps_2024_1.pdf)

**Pull request merged**
