### PR TITLE
Create hiob-ludolf-centre-for-ethiopian-studies-web.csl

### PR DESCRIPTION
**Pull request by eu-genia**
A version of the bibliographic style of the Hiob Ludolf Centre for Ethiopian Studies for web publications (with DOIs/URLs)

### CODE REVIEW

**Comment by rmzelle** [comment]
Is it necessary to have two style variants? Your instructions seem to suggest to always add URLs/DOIs if available: "Electronic publications should be cited like printed sources, accompanied by the permalink URL/DOI and the date of access." (http://www1.uni-hamburg.de/COMST/bulletin.html)

(having fewer style variants makes it easier to maintain the CSL style(s))

**Comment by eu-genia** [comment]
this was the result of the latest instruction from our department head  
who is also the editor in chief of all the publications.
the explanation is there are many journal articles which are ALSO  
online (or also many books, in particular older ones, which have been  
digitized and are accessible on googlebooks or archives.org), but  
these primarily in print should appear in our print journals without  
URL/DOI - these are reserved for exclusively electronic publications  
without analogue version - however in the bibliographies published  
online for our various projects the URLs and DOIs should be provided  
wherever they exist.
i understand that it will be difficult to maintain two parallel styles  
but do not see another solution to satisfy the request. do you?

Quoting "Rintze M. Zelle" <notifications@github.com>:

> Is it necessary to have two style variants? Your instructions seem  
> to suggest to always add URLs/DOIs if available: "Electronic  
> publications should be cited like printed sources, accompanied by  
> the permalink URL/DOI and the date of access."  
> (http://www1.uni-hamburg.de/COMST/bulletin.html)
>
> (having fewer style variants makes it easier to maintain the CSL style(s))
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/1988#issuecomment-203091038



-- 
Eugenia Sokolinski
Project Coordinator
Hiob Ludolf Centre for Ethiopian Studies
Asien Afrika Institut
Universit�t Hamburg
Alsterterrasse 1
20354 Hamburg

eugenia.sokolinski@uni-hamburg.de

http://www1.uni-hamburg.de/ethiostudies
http://www.traces.uni-hamburg.de

**Comment by rmzelle** [comment]
Okay, thanks for clarifying.

@adam3smith, any thoughts about the title? (would "Hiob Ludolf Centre for Ethiopian Studies (with URL/DOI)" and "http://www.zotero.org/styles/hiob-ludolf-centre-for-ethiopian-studies-with-url-doi" be better?)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
