### PR TITLE
Create Scientia-Iranica

### PR DESCRIPTION
**Pull request by smvazirizade**

### CODE REVIEW

**Comment by rmzelle** [comment]
@smvazirizade, thanks! There were several cases similar to `prefix=""" suffix="," "` in the style, which isn't valid XML, and which can be better handled with `quotes="true"`, so I made that change.

@adam3smith, since the style didn't validate we should probably briefly check the output against the style guide.

**Comment by adam3smith** [comment]
(style is not quite right; don't merge yet, I'll fix)

**Comment by rmzelle** [comment]
@adam3smith, good to merge now? Thanks already for the fixes.

**Comment by adam3smith** [comment]
Yes, sorry, got interrupted before getting to merge

**Pull request merged**
