### PR TITLE
Add csl for SDMI

### PR DESCRIPTION
**Pull request by SterArcher**

### CODE REVIEW

**Comment by SterArcher** [comment]
Could I please get help on this error, verifier worked fine.

**Comment by SterArcher** [comment]
Could I please get help on this error, verifier worked fine.

**Comment by adam3smith** [comment]
@SterArcher -- is this going to be a relevant style for more than this year's congress? If this will remain in use for subsequent years, we'd be happy to take it, but not sure that having a style for a single conference up on the repository makes sense.

**Comment by adam3smith** [comment]
@SterArcher see my question above

**Comment by SterArcher** [comment]
Sry for late reply @adam3smith , this congress happens every year. So the style will be relevant in the future also.

**Pull request merged**
