### PR TITLE
Update to harvard-cranfield-university.csl

### PR DESCRIPTION
**Pull request by ivyleavedtoadflax**
* Added support of Patent type using Genre field.

Sorry missed this in the last pull request. Thanks!

### CODE REVIEW

**Comment by adam3smith** [comment]
I'm actually not so keen on with using genre all over the place. The moment people use a different citation style, this is going to break things left and right.
What does the citation you're trying to generate here look like?

We may also ask you to change some of the things added in https://github.com/citation-style-language/styles/pull/1438 
I think in most cases, we have better variables for these things and I would like them to be treated uniformly across styles (cc @rmzelle )

**Comment by ivyleavedtoadflax** [comment]
Yes you're right, and it is a bit of a fudge. I've been writing this on behalf of the library, and their interest is solely in Mendeley, so I've been constrained by the Mendeley mappings.

This is what I have been trying to achieve (bold indicates text I have mapped to genre):

For blogs and wikis:
* Borger, J. (2010) ‘Afghanistan options are running out’, **[Blog]** *Julian Borger’s global security blog*. Available at: http://www.guardian.co.uk/world/julian-borger-global-security-blog/2010/sep/08/afghanistan-policy-uk (Accessed: 3 March 2015).
* Barefoot, A. (2012) ‘October National ARLG committee meeting notes’, **[Wiki]** ARLGSW PBworks. Available at: http://arlgsw.pbworks.com (Accessed: 4 December 2014).

For Kindle (or similar) books: 
* Dennis, H.L. (2012) *Secret breakers: the power of three* **[Kindle]**. London: Hodder Children’s Books. Available at: http://www.amazon.co.uk (Accessed: 10 February 2015).

The most tenuous one - conference proceedings:

* Wessel, J.T. and Meyer, B.L. (2010) ‘Assessing system software performance in complex system of systems environments’, *Military Communications Conference: MILCOM 2010*. **San Jose Convention Center, California, 31 Oct - 3 Nov**. Piscataway: Institute of Electrical and Electronic Engineers, pp. 2310–2315. Available at: http://ieeexplore.ieee.org/xpl/mosmostRecentIs.jsp?punumber=5673567 (Accessed: 1 January 2015).

If you could suggest alternatives, particularly to conferences which is the main issue I would be really grateful.

**Comment by ivyleavedtoadflax** [comment]
Also for patent:

* Hodge, C.D. (2008) *US 20080007021A1: Rear suspension assembly for a drag racing vehicle*. **US Patent**. Available at: http://www.google.com/patents/US7475894 (Accessed: 10 February 2015).

**Comment by adam3smith** [comment]
Thanks. I'll look at the Mendeley mappings and see what makes sense. I do recall that they're pretty stingy with some variable mappings.

**Comment by ivyleavedtoadflax** [comment]
Yes...I get the feeling it's not as easy as it should be! Thanks.

**Comment by adam3smith** [comment]
For Patent - could you then put the "number" in front of the title? People shouldn't be adding patent numbers in the title of their items (it's most commonly cited after the title along the lines on
* Hodge, C.D. (2008) Rear suspension assembly for a drag racing vehicle. US Patent  US20080007021A1. Available at: http://www.google.com/patents/US7475894 (Accessed: 10 February 2015).

For the other items--couldn't we go with Medium there? Mendeley offer that, too, and that seems like both a better fit and is also the direction we've been going with this e.g. in APA style.

**Comment by ivyleavedtoadflax** [comment]
I've made the changes you suggest in this latest commit. All is good for number in Patents (will speak to the library about your suggestion above). However, Mendeley doesn't seem to pick up the 'medium' field. If I export an entry with 'genre' from Mendeley as JSON I get:

{ "type": "thesis", "citation-label": "Tath10", "genre": "PhD thesis", "publisher": "Cranfield University", "title": "Confidence in United Kingdom defence logistics: rhetoric or reality?", "author": [{"family": "Tatham", "given": "P."}], "issued": { "raw" : "2010" }}

and this using 'medium'

{ "type": "thesis", "citation-label": "Tath10", "publisher": "Cranfield University", "title": "Confidence in United Kingdom defence logistics: rhetoric or reality?", "author": [{"family": "Tatham", "given": "P."}], "issued": { "raw" : "2010" }}

I've noticed before that [the mendeley mappings](http://support.mendeley.com/customer/portal/articles/364144-csl-type-mapping) are not always as reported - is this another instance?

**Comment by cpina** [comment]
@ivyleavedtoadflax : we should update the Mendeley mappings. Meanwhile you can use this style: http://pinux.info/files/cslDataExporter.csl and in Mendeley Desktop View menu -> Library as Citations. Besides the "language" field (missing in the cslDataExporter.csl) the rest is correct afaik.

**Comment by ivyleavedtoadflax** [comment]
@cpina - yes, thanks, that is what I used to export the above. Yes... an update to the mappings would be helpful...

**Comment by adam3smith** [comment]
OK, sorry about that. Go back to genre then. And we'll take this. If possible try to update this as Mendeley updates their field mappings.

**Comment by ivyleavedtoadflax** [comment]
Thanks, have rolled back to previous commit and rebased. I'll keep an eye on the mappings and update when things move on!

**Comment by adam3smith** [comment]
(btw. -- we've received an e-mail from a librarian at Cranfield about this style. We told them to be in touch with you, thought I'd mention it FYI.)

**Comment by ivyleavedtoadflax** [comment]
Ah yes thanks! Actually I suggested that they contact you, they are interested in developing a numbered style and I noticed on the CSL homepage that you would produce styles for a fee, which they are willing to pay. I'll would get around to it eventually, but you would certainly do a better job and could earn something from it.

**Comment by adam3smith** [comment]
Ah OK, thanks, we'll clarify that then.

**Pull request merged**
