### PR TITLE
Update geografie-sbornik-cgs.csl

### PR DESCRIPTION
**Pull request by libora**
Journal's guide for authors was updated (I do not know when), this commit response on changes in the guide.

### CODE REVIEW

**Comment by libora** [comment]
@rmzelle @adam3smith Hi guys, can you, please check this pull request. The students on the faculty, where this style is used for diploma thesis, are finishing theirs work. I think is better to download the style from official repository instead of the gist. Thanks.

**Comment by libora** [comment]
Who can merge the PR of styles?

**Comment by adam3smith** [comment]
sorry for the delay -- could you take a look & make sure everything is OK after my edits?

**Comment by libora** [comment]
@adam3smith Thank you, Sebastian, your changes are OK.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
