### PR TITLE
Update spec_helper.rb

### PR DESCRIPTION
**Pull request by NMonteix**
Added ISSN exception in preparation for Collection de l'Ecole française de Rome styles (note / full note)

### CODE REVIEW

**Comment by rmzelle** [comment]
You're trying to edit an out-of-date version of spec_helper.rb (in particular, the line we edited in your previous PR), so I can't merge this.

**Comment by NMonteix** [comment]
Ok
The place is fine but I need to update my fork?

**Comment by rmzelle** [comment]
I recommend visiting https://github.com/citation-style-language/styles, and then creating a new pull request by either using the "New file" button, or by editing https://github.com/citation-style-language/styles/blob/master/spec/spec_helper.rb. That way you always get a fresh branch.

**Comment by rmzelle** [comment]
(superseded by #1805)

**Pull request closed without merging**
