### PR TITLE
Create Facoltà-Teologica-dell'Italia-Settentrionale-Milano.csl

### PR DESCRIPTION
**Pull request by invern**
Stile di citazione secondo le norme della Facoltà Teologica dell'Italia Settentrionale (FTIS), sede di Milano

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! Some questions:
1. Do you remember which style you based this on originally?
2. We have a very strong preference for having documentation available for styles we publish on the repository. Is the guide for this style available online? If not, would you be able to post it here to a comment (note that you can't attach it to an e-mailed reply. You have to come to this page and drag&drop the file to a comment)
3. What is the purpose of the `(riviste non abbreviate)` in the title? Is there a version of this style _with_ abbreviated journals titles?

**Comment by invern** [comment]
Hallo,
1. I think the "Pontificia Università Salesiana" style as base and the "Pontifical Gregorian University" style for some features. 
2. the online guide is very dispersive, because it contains many other indications; moreover, it differs slightly from the style of the csl file, because the file in the website has not yet been updated, due the restyling of the website in progress. I post the updated file with bibliographic rules only:
[Norme_citazioni_bibliografiche_FTIS.pdf](https://github.com/citation-style-language/styles/files/3125373/Norme_citazioni_bibliografiche_FTIS.pdf)
3. Yes, there is a version of this style with abbreviated journals titles. Normally the titles of the journals are not shortened in the written students works, but there are some cases in which the titles can be abbreviated (in the theses and for the articles of the journal of the faculty). Because of the layout difference between abbreviated title and non-abbreviated title I was not able to put everything in one file (I'm not a computer technician, but a theology professor...). I started creating and uploading one file only.
Thanks!

**Comment by adam3smith** [comment]
@rmzelle if you could look at the title/filename with respect to 3.) above? Ready to merge otherwise.

**Comment by rmzelle** [comment]
The Italian translation of "unabbreviated journal titles" (and "abbreviated journal titles" for the other variant) would be better than "unabbreviated journals", which it looks "riviste non abbreviate" translates to. Otherwise looks fine.

**Comment by invern** [comment]
> The Italian translation of "unabbreviated journal titles" (and "abbreviated journal titles" for the other variant) would be better than "unabbreviated journals", which it looks "riviste non abbreviate" translates to. Otherwise looks fine.

ok, I've changed the Italian translation in "titoli di riviste non abbreviati"

**Comment by rmzelle** [comment]
@invern, thanks!

@adam3smith, will you do the honors?

**Comment by adam3smith** [comment]
Sorry for the delay in merging this.

**Comment by invern** [comment]
Thank you very much!

**Pull request merged**
