### PR TITLE
Create wolters-kluwer-nl.csl

### PR DESCRIPTION
**Pull request by aadverbunt**
This is a citation style developed to make citations in the style of the Dutch 'Wolters Kluwerbrede Schrijfwijze'. This is a company-dedicated style that resembles the 'Leidraad for Juridische auteurs' citation style. It is only a bit adjusted to produce the style that is used within Wolters Kluwer Netherlands.

### CODE REVIEW

**Comment by rmzelle** [comment]
@aadverbunt, thanks. Did you base this style on one of the documents listed here?: https://www.wolterskluwer.nl/auteur/voor-auteurs/auteursmiddelen-en-instructies

Can you tell us which one(s)?

(also, as a heads-up, we standardize the indenting of all our styles with https://formatter.citationstyles.org/, which will remove the empty lines and rearrange the XML comments a bit)

**Comment by rmzelle** [comment]
Oh, and does Wolters Kluwer have multiple style variants, or just one? If it's just one, we typically don't include a descriptor in the title like "(author-title-date-sorted)".

**Comment by aadverbunt** [comment]
> Oh, and does Wolters Kluwer have multiple style variants, or just one? If it's just one, we typically don't include a descriptor in the title like "(author-title-date-sorted)".

Hello, Thanks for your question. Wolters Kluwer NL uses 2 citation styles, for notes under the pages and for citations inside the full text.  I uploaded only the last one, since we use this the most.

**Comment by aadverbunt** [comment]
> @aadverbunt, thanks. Did you base this style on one of the documents listed here?: https://www.wolterskluwer.nl/auteur/voor-auteurs/auteursmiddelen-en-instructies
> 
> Can you tell us which one(s)?
> 
> (also, as a heads-up, we standardize the indenting of all our styles with https://formatter.citationstyles.org/, which will remove the empty lines and rearrange the XML comments a bit)

Hello, indeed it is the Leidraad for Juridische auteurs. We use this as a reference for our WKNL-style.

**Comment by rmzelle** [comment]
Bedankt!

**Pull request merged**
