### PR TITLE
Update associacao-brasileira-de-normas-tecnicas-ufrgs.csl

### PR DESCRIPTION
**Pull request by PriscilaSJUFRGS**
Update with some corrections and addition of document types.

### CODE REVIEW

**Comment by PriscilaSJUFRGS** [comment]
What needs to be corrected? I didn't understand.

**Comment by PriscilaSJUFRGS** [comment]
> 😟 There are some issues with your submission.
> 
> 1 test failed
> Please check the [test report](https://travis-ci.org/citation-style-language/styles/builds/732707228) for details.

What needs to be corrected? I didn't understand.

**Comment by rmzelle** [comment]
> What needs to be corrected? I didn't understand. Locale element seems to be at the right place.

Our CSL validator (https://validator.citationstyles.org/) gives more precise validation error messages. In this case the problem was a typo ("preffix" instead of "prefix"). See https://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcitation-style-language%2Fstyles%2F9aa3302f681e5860a985355291960794a4db07f2%2Fassociacao-brasileira-de-normas-tecnicas-ufrgs.csl&version=1.0.1.

Can you check if the latest version of the style (https://raw.githubusercontent.com/PriscilaSJUFRGS/styles/patch-6/associacao-brasileira-de-normas-tecnicas-ufrgs.csl) now gives the desired output?

**Comment by PriscilaSJUFRGS** [comment]
> > What needs to be corrected? I didn't understand. Locale element seems to be at the right place.
> 
> Our CSL validator (https://validator.citationstyles.org/) gives more precise validation error messages. In this case the problem was a typo ("preffix" instead of "prefix"). See https://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcitation-style-language%2Fstyles%2F9aa3302f681e5860a985355291960794a4db07f2%2Fassociacao-brasileira-de-normas-tecnicas-ufrgs.csl&version=1.0.1.
> 
Thanks! I used it but didn't see the intrusor >_<

> Can you check if the latest version of the style (https://raw.githubusercontent.com/PriscilaSJUFRGS/styles/patch-6/associacao-brasileira-de-normas-tecnicas-ufrgs.csl) now gives the desired output?

It's working perfectly!

**Comment by rmzelle** [comment]
Great. Two more comments:

* We recommend always using https://formatter.citationstyles.org/ to reformat a style before submitting it. That ensures it's indented and formatted consistently.
* I also put back the authors/contributors that were previously listed on the style. Unless this is a rewrite from scratch, we typically leave historic contributors on the style as a way to acknowledge their contributions to the style.

**Comment by PriscilaSJUFRGS** [comment]
> Great. Two more comments:
> 
> * We recommend always using https://formatter.citationstyles.org/ to reformat a style before submitting it. That ensures it's indented and formatted consistently.
Thanks! That will help a lot!

> * I also put back the authors/contributors that were previously listed on the style. Unless this is a rewrite from scratch, we typically leave historic contributors on the style as a way to acknowledge their contributions to the style.
I was trying to clean up a little bit, sorry!

Do I need to do something else?

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
