### PR TITLE
NIODA-Harvard.csl

### PR DESCRIPTION
**Pull request by sallymussared**
The National Institute of Organisation Dynamics Australia Ltd (NIODA) is an Australian Academic Institute and has a Harvard based Zotero citation style. 
Thank you

### CODE REVIEW

**Comment by POBrien333** [comment]
No caps. And filename and ID self link need to be the same.

**Comment by rmzelle** [comment]
> The National Institute of Organisation Dynamics Australia Ltd (NIODA) is an Australian Academic Institute and has a Harvard based Zotero citation style.

@sallymussared, thanks. Is your "National Institute of Organisation Dynamics Referencing Guide" available online? We always try to add a link to the style guide to each CSL style, so that people can verify whether the style is correct. See also https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link.

(and sorry for the picky @csl-bot)

**Comment by sallymussared** [comment]
Thank you.  Yes, it is available at:
https://www.nioda.org.au/wp-content/uploads/2019/07/NIODA-Referencing.pdf

Do you add the link or do I?
I look forward to hearing from you.
Kindest regards,
Sally

**Comment by rmzelle** [comment]
Thanks!

**Comment by sallymussared** [comment]
Thank you so much!
I am happy to delete whatever you suggest. 
Kindest regards,
Sally

**Comment by rmzelle** [comment]
> I am happy to delete whatever you suggest.

I made some minor changes (https://github.com/citation-style-language/styles/pull/4162/commits/dc952f8d44847ae2d2553fc4d17a148c2f91a315) so the style better follows our repository guidelines, and added the style to our repository. I don't think you have to delete anything at this point.

**Comment by sallymussared** [comment]
Hello,

You were so wonderfully helpful when we lodged our citation styles, I am
wondering if you might be able to help us again.

If a book is edited, we would like to have the Eds in brackets as shown
below:
Lubkin, I.M. & Larsen, P.D. (Eds.) (2013). Chronic illness: impact and
interventions, 8th edn. Jones & Bartlett
Learning: Burlington, MA.

I was thinking this should be in the section of the following in the csl,
but I am not sure how to make sure this is properly done:
<macro name="author">
    <names variable="author">
      <name name-as-sort-order="all" sort-separator=", "
initialize-with="." delimiter=", " delimiter-precedes-last="always"/>
      <label form="short" prefix=" (" suffix=")"
text-case="capitalize-first"/>
      <substitute>
        <names variable="editor"/>
        <names variable="translator"/>
        <text macro="title"/>
      </substitute>
    </names>
  </macro>

I hope this is not too much trouble and look forward to hearing from you.

Kindest regards,

Sally

Sally Mussared Board Secretary & Director of Administration NIODA
PO Box 287, Collins Street West, Melbourne VIC 8007
sally.mussared@nioda.org.au
www.nioda.org.au
+61 414 529 867

**Comment by POBrien333** [comment]
@sallymussared 
The style already prints out the following:
"Hancké, B., Rhodes, M., Thatcher, M. (Eds.) (2007). Beyond Varieties of Capitalism: Conflict, Contradiction, and Complementarities in the European Economy, Oxford University Press: Oxford and New York, NY."

**Pull request merged**
