### PR TITLE
Create comptes-rendus-author-date.csl

### PR DESCRIPTION
**Pull request by justinefabre**
Following a discussion with Adam Smith (https://github.com/citation-style-language/styles/pull/6626), I am creating two new independent styles : comptes-rendus-numeric and comptes-rendus-author-date. The other styles I already created can then be added as dependants from these.

### CODE REVIEW

**Comment by justinefabre** [comment]
Styles to be added as dependant from this one :
https://github.com/citation-style-language/styles/pull/6631
https://github.com/citation-style-language/styles/pull/6630
https://github.com/citation-style-language/styles/pull/6629

**Comment by adam3smith** [comment]
Same as for the other one: Do you have the guides available online somewhere? If so, could you add them as a link with `rel="documentation"` please?

**Comment by justinefabre** [comment]
Not for this one either, sorry again

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
