### PR TITLE
Create harvard-university-of-hull.csl

### PR DESCRIPTION
**Pull request by luistorrao**
Hello,

This is a first version of the University of Hull Harvard citation style.

Many Thanks

### CODE REVIEW

**Comment by rmzelle** [comment]
@luistorrao, looks great. The only things we need changed are:

* Presumably the style will only be used with British English, right? If so, please add `default-locale="en-GB"` to the `<style>` element, to fix the style to British English. See https://github.com/citation-style-language/styles/wiki/Style-Requirements#3---style-locale. This will likely fix the issue we discussed via email with the "available at" term as well, which currently is only defined for the "en-GB" locale, while Mendeley probably defaults to American English ("en-US"). Changing `<locale xml:lang="en-GB">` to `<locale>` should do the trick as well.
* Please add a "template" link to point to the CSL style you based this one on. See https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link.

**Comment by rmzelle** [comment]
@luistorrao, can you confirm that your style works like it should, now?

**Comment by luistorrao** [comment]
Dear @rmzelle please help me out with this:
- Should the style be already available on https://www.zotero.org/styles?q=hull and avalilabe in Mendeley the referencing tool I am using)? If not, should I just download the style from here and import it to Mendeley to test it? 
- After testing has been done by me and my uni's library staff, how does it get published and where will it be available?

Many Thanks

**Comment by adam3smith** [comment]
Once you're happy (and yes, just downloading from here is best), you let us know. We accept it here, then it becomes available on Zotero within an hour and in Mendeley within a day.

**Comment by luistorrao** [comment]
Dear @adam3smith. Great, I will then ask for the proofing/validation of the uni's library staff and let you know when all is OK. Many Thanks

**Comment by rmzelle** [comment]
(you can download the current version at https://raw.githubusercontent.com/luistorrao/styles/patch-1/harvard-university-of-hull.csl )

**Comment by luistorrao** [comment]
Dear @rmzelle thanks. I have just sent it for proofing/validation by the library staff. It might take some time and there might be necessary corrections in order to achieve a "perfect" 1st version. If corrections are necessary is it correct to use this conversation with you guys before editing? I suppose there will be few or no corrections, but anyways I wouldn't like to touch this code that has passed without prior advise. And I have a second question: when this first version is made public, if the official referencing rules that guide the file are changed/updated, will it be easy to create a 2nd edition to substitute the first? Or will the 2 versions coexist? I am thinking this particularly because of the advent of Massive Open Online Courses (MOOC) and the probable future update on official referencing rules in order to include this type of reference with a proper rule.

**Comment by adam3smith** [comment]
you can just make corrections here, no need to tell us. Just let us know when you're done.

And yes, it's very easy to update a style and we'd  encourage you to update this version rather than have 1st and 2nd edition both available (technically that's possible, but it's very rarely good idea. Only place we do that is for widely used style manuals like MLA, where old versions often continue to be used by select journals).

**Comment by luistorrao** [comment]
Dear @adam3smith Thank you for the clarification. I will then wait for the proofing/validation to complete and then let you know.

**Comment by rmzelle** [comment]
> I will then wait for the proofing/validation to complete and then let you know.

@luistorrao, I'm closing this pull request for now. Just post a comment here when this style has been approved, and we'll reopen it.

I'm just closing this because this pull request hasn't seen any activity in a while.

**Pull request closed without merging**
