### PR TITLE
Create ntu-library-harvard.csl

### PR DESCRIPTION
**Pull request by richard-cross-ntu**

### CODE REVIEW

**Comment by richard-cross-ntu** [comment]
Hi - is there a current estimated turnaround time for requests such as these? The CSL-bot indicates a human volunteer will be in touch "usually within a week".

**Comment by rmzelle** [comment]
> Hi - is there a current estimated turnaround time for requests such as these? The CSL-bot indicates a human volunteer will be in touch "usually within a week".

Yes, I meant to update that, since several weeks is more typical nowadays.

Regarding your submission, do you remember which style you started out from? We'd like to add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link). I also changed "NTU" to the full university name per our naming guidelines.

**Comment by richard-cross-ntu** [comment]
In answer to your question - the style I started out from was harvard-anglia-ruskin-university.csl

**Comment by rmzelle** [comment]
Great, thanks. Sorry for the long wait.

**Pull request merged**
