### PR TITLE
Update Elementa style

### PR DESCRIPTION
**Pull request by akokai**
Improve bibliography layout for Elementa.
- Fix weird layout artifact for reports.
- Add event fields for conference papers.

Apologies for the frequent PRs. I keep finding more things to fix as I write.

### CODE REVIEW

**Comment by akokai** [comment]
Canceling this because I realize there's a lot of work left to do on the legal citation style, which also extends into the CSE-author-date style that this was based on. I will submit new PRs for each style when I'm done.

**Comment by rmzelle** [comment]
Okay, thanks.

(does CSE need to support legal items? It's scope it more the natural sciences, no?)

**Comment by akokai** [comment]
Yeah, I might just leave CSE the way it is because I have a feeling I will not get it right, and more people probably use it. The CSE style guide is non-free, so I don't know for sure, but other sources say CSE should use Bluebook style for legal citations (like APA). Elementa definitely needs something like that because it's an interdisciplinary journal.

**Comment by rmzelle** [comment]
> Elementa definitely needs something like that because it's an interdisciplinary journal.

I don't see any legal types listed at https://home.elementascience.org/for-authors/style-guide/, though.

In general, CSL is somewhat limited in its support of legal materials, and we don't fully support the requirements of Bluebook. If you need extensive support for legal items, your best option is to use Juris-M (a fork of Zotero; https://juris-m.github.io/) in combination with its Juris-M styles (forked from CSL).

**Comment by akokai** [comment]
Thanks for the tips. Far from needing extensive legal citation support, I just want it not to output something nonsensical -- if anything, for my own use, but why not share it with the community. What I've done is copied the parts of APA that deal with legal citations. Will set up a new PR.

**Comment by rmzelle** [comment]
(replaced by #2160)

**Pull request closed without merging**
