### PR TITLE
Create RLMM.csl

### PR DESCRIPTION
**Pull request by osc4r8a**
wipe out the paper´s title. add issue

### CODE REVIEW

**Comment by rmzelle** [comment]
@osc4r8a, please update the original pull request instead of opening new ones.

Also please look at https://github.com/citation-style-language/styles/wiki/Style-Requirements to make sure your style is correctly submitted.

For starters, the file name should be "revista-latinoamericana-de-metalurgia-y-materiales.csl" (with matching style ID and "self" link), spelled out in full and in lowercase.

**Comment by rmzelle** [comment]
(it's fine to update this pull request, instead of the original #2165)

**Comment by damnation333** [comment]
Line #24 and #56 both can be deleted and the csl validates properly.

**Comment by rmzelle** [comment]
Closing because of inactivity. @osc4r8a, if you get back to us, we can reopen this pull request and complete the submission.

(@damnation333, careful with the "#...", it automatically creates links to issues)

**Comment by rmzelle** [comment]
(this style has been added in #2493)

**Pull request closed without merging**
