### PR TITLE
Create malaysian-orthopaedic-journal.csl

### PR DESCRIPTION
**Pull request by kbssrinivas**
Malaysian orthopaedic journal does not have a csl file.

### CODE REVIEW

**Comment by kbssrinivas** [comment]
How can I check if this csl file has been accepted? It has passed all the checks 11 days ago.
thanks,

**Comment by adam3smith** [comment]
Sorry, taking a bit longer to review currently -- you'll get a notification either when this is merged (i.e. accepted) or if we have any questions. I'll try to get to it asap.

**Comment by kbssrinivas** [comment]
Thats ok. Thank you for getting back.

**Comment by adam3smith** [comment]
@kbssrinivas Thanks -- looks good in general, but could you please confirm the change in sort order I made? You had the bibliography alphabetically, but as per the instructions (and recent articles I consulted) "Number references consecutively in the order in which they are first mentioned in the text" --was there any reason you had them alphabetical or was that an oversight?

**Comment by rmzelle** [comment]
(@adam3smith, no showstoppers here)

**Comment by kbssrinivas** [comment]
Thank you very much for the correction. It was an oversight. Numbering references should be in the order they appear in text. 

Regards,
Srinivas

**Comment by adam3smith** [comment]
Great, thanks!

**Pull request merged**
