### PR TITLE
Create uludag-universitesi-sosyal-bilimler-enstitusu-full-note-no-ibi…

### PR DESCRIPTION
**Pull request by mtarakci**
…d.csl

### CODE REVIEW

**Comment by rmzelle** [comment]
@mtarakci, before I merge this, will you be submitting any more variants, and if so, which ones?

**Comment by mtarakci** [comment]
@rmzelle,
This is the last one.
Is there any way or necessety to re-name the previous note style as "full note"?

**Comment by rmzelle** [comment]
> Is there any way or necessety to re-name the previous note style as "full note"?

Yes, I updated this pull request to include that change. Is https://github.com/citation-style-language/styles/pull/2951/files#diff-1b5ab0cbe6ed34c2599edfba93a07b79 what you want?

**Comment by mtarakci** [comment]
Thank you very much @rmzelle.
You have already done what I want.

**Comment by rmzelle** [comment]
Okay, thanks!

**Pull request merged**
