### PR TITLE
revista-brasileira-de-ciencia-do-solo.csl

### PR DESCRIPTION
**Pull request by FSHigashikawa**
This style was based on ABNT style.

### CODE REVIEW

**Comment by rmzelle** [comment]
@FSHigashikawa, thanks for submitting this style.

Could you please follow our submission guidelines at https://github.com/citation-style-language/styles/wiki/Style-Requirements and update your style accordingly? (please post a comment when you're done, since we don't get email updates for commits)

**Comment by FSHigashikawa** [comment]
Hi, 
Thank you very much for send me the submission guidelines.
I just updated the style...

**Comment by rmzelle** [comment]
@FSHigashikawa, thanks, but there are a few more things to change.

Our validator highlights two things (see http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2FFSHigashikawa%2Fstyles%2Fpatch-1%2FRevista%2520Brasileira%2520de%2520Ci%25C3%25AAncia%2520do%2520Solo.csl&version=1.0.1 ):

* `<link href="https://http://www.scielo.br/revistas/rbcs/iinstruc.htm"/>` should be `<link href="https://http://www.scielo.br/revistas/rbcs/iinstruc.htm" rel="documentation"/>`
* `<category field="soil science"/>`. You can only use the following "field" values: http://citationstyles.org/downloads/specification.html#appendix-i-categories. "science" and "biology" are probably suitable options. The style also shouldn't use the "generic-base" field, which we only use for styles that don't belong to any particular discipline.

In addition, the style file name should be "revista-brasileira-de-ciencia-do-solo.csl". The style ID should be "<id>http://www.zotero.org/styles/revista-brasileira-de-ciencia-do-solo</id>", the style needs a "self" link, and the "template" link should point to the ABNT style you started out with.

**Comment by FSHigashikawa** [comment]
Hi @rmzelle, thank you very much, but now I don't what I need to fix or change...

**Comment by rmzelle** [comment]
You still need to change the file name (see https://help.github.com/articles/renaming-a-file/). You also accidentally added "+" to several lines, which isn't correct. See https://github.com/FSHigashikawa/styles/blob/7950e606fa9d0afcad7df99b444853cd6dfc8139/Revista%20Brasileira%20de%20Ci%C3%AAncia%20do%20Solo.csl#L344

**Comment by rmzelle** [comment]
Great, almost there.

First, `<link href="https://http://www.scielo.br/revistas/rbcs/iinstruc.htm" rel="documentation"/>` should be `<link href="http://www.scielo.br/revistas/rbcs/iinstruc.htm" rel="documentation"/>` (remove the "https://").

Second, the style calls the "collection" macro twice, but this macro is not defined in the style. See http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2FFSHigashikawa%2Fstyles%2Feba95354aa3ffa02b4bd9ad233925963a179c522%2Frevista-brasileira-de-ciencia-do-solo.csl&version=1.0.1#source-code.

**Comment by FSHigashikawa** [comment]
Hi @rmzelle, what are the next steps ???

**Comment by rmzelle** [comment]
We're all set! Merged. (we don't get updates for commits, so unless you post a comment, it can take some time before we notice)

**Comment by FSHigashikawa** [comment]
Thank you very much!

**Comment by FSHigashikawa** [comment]
Hi @rmzelle, I detected an problem in this style... I don't know why, but not appear the name of authors and the name of the book in the references of books... Please, help me to fix it...

**Comment by rmzelle** [comment]
@FSHigashikawa, well, as you can see at https://github.com/citation-style-language/styles/pull/1395/files#diff-c3140f74a963bc244686f56b4b867776R342, the part of the style that describes the format of bibliographic entries for books doesn't include any calls to the "author" or "title" macros. Maybe you deleted them by accident?

**Comment by FSHigashikawa** [comment]
Hi @rmzelle, probably I deleted accidentally ... but I am not confident to fix it properly, I don't know the exact code... and the place to insert each code...
What can I do to fix it?

**Comment by FSHigashikawa** [comment]
Hi @rmzelle, maybe could I include this? But, where and how?
 <group>
<text macro="author" suffix=". "/>
<text macro="title" suffix=". "/>
<text macro="translator" suffix=". "/>
<text macro="edition" suffix=". "/>
<text macro="publisher" suffix=". "/>
<text macro="locators"/>
</group>

**Comment by FSHigashikawa** [comment]
<group>
<text macro="author" suffix=". "/>
<text macro="title" suffix=". "/>
<text macro="translator" suffix=". "/>
<text macro="edition" suffix=". "/>
<text macro="publisher" suffix=". "/>
<text macro="locators"/>
</group>

**Pull request merged**
