### PR TITLE
Create chinese-law-journals.csl

### PR DESCRIPTION
**Pull request by redleafnew**
More reference types needed to test the style, anyone could contact redleafnew@163.com.

### CODE REVIEW

**Review by redleafnew — COMMENTED** [review]
changed

**Comment by redleafnew** [comment]
I have changed the lines.

**Comment by adam3smith** [comment]
Don't worry about the test failure.

Could you say a bit more about this style? What is it based on? Which journals would use it? We typically would accept styles  specific to one journal rather than something as sweeping as "Chinese Law Journals"

@retorquere -- this looks like it might fail because of the rename within the pull request?

**Comment by redleafnew** [comment]
Many Chinese law journals and publishers apply this style, such China Legal Science, China Law Review (http://www.chinalawreview.com.cn), Peking University Law (http://journal.pkulaw.cn/NewIssue/Detail/160073), Journal of Comparative Law (https://bjfy.cbpt.cnki.net/WKC/WebPublication/index.aspx?mid=bjfy). https://www.weibo.com/ttarticle/p/show?id=2309404436112734027798 aslo lists some journal and publishers.

It is based on http://www.zotero.org/styles/china-national-standard-gb-t-7714-2015-note.

**Comment by redleafnew** [comment]
thanks @retorquere , and how to re-start the action on this PR?

**Comment by retorquere** [comment]
@redleafnew you can't, only a repo owner can.

**Comment by redleafnew** [comment]
Many thanks.

**Comment by rmzelle** [comment]
@adam3smith, I don't think we ever use transliteration in style titles (although a slugified transliterated title would probably make the most sense for the style ID).

I did find a section at https://weibo.com/ttarticle/p/show?id=2309404436112734027798 discussing the name of the style (search for "(6) The name of this citation style" after Google Translate).

@redleafnew, would 法学引注手册 be a good name for the style ("Law Citation Manual")? Or should we also mention the connected institution? It looks like this style is curated by the Law Journal Research Association of the Chinese Law Society?

**Comment by redleafnew** [comment]
I think Law Citation Manual could be better or Chinese Law Citation Manual . Need the Chinese translation 法学注引手册 add to the title of the csl?发自我的华为手机-------- 原始邮件 --------发件人： "Rintze M. Zelle" ***@***.***>日期： 2021年3月12日周五 12:38收件人： citation-style-language/styles ***@***.***>抄送： redleafnew ***@***.***>, Mention ***@***.***>主    题： Re: [citation-style-language/styles] Create chinese-law-journals.csl (#5314)

@adam3smith, I don't think we ever use transliteration in style titles (although a slugified transliterated title would probably make the most sense for the style ID).

I did find a section at https://weibo.com/ttarticle/p/show?id=2309404436112734027798 discussing the name of the style (search for "(6) The name of this citation style" after Google Translate).

@redleafnew, would 法学引注手册 be a good name for the style ("Law Citation Manual")? Or should we also mention the connected institution? It looks like this style is curated by the Law Journal Research Association of the Chinese Law Society?

**Comment by rmzelle** [comment]
We'd probably name the style either "Law Citation Manual (中文)" or "法学注引手册 (中文)", whatever you think makes the style easiest to find for its users.

**Comment by redleafnew** [comment]
Could we use the name 'Law Citation Manual (中法学注引手册, 中文)'？

**Comment by adam3smith** [comment]
Yes, I was going to say that I like the idea of having both translation and original available

**Comment by rmzelle** [comment]
@redleafnew, thanks!

**Comment by redleafnew** [comment]
@rmzelle Sorry, the Chinese name should be 法学注引手册, 中文 or 中国法学注引手册, 中文 instead of 中法学注引手册, 中文 in the bracket.

**Pull request merged**
