### PR TITLE
Create universitaet-hamburg_lateinamerikanistik_spanisch.csl

### PR DESCRIPTION
**Pull request by schaeffauer**
Style-Vorlage für die Lateinamerikanistik an der Universität Hamburg (Spanisch)

Diese Vorlage soll Studierenden der Universität Hamburg in den Fächern Romanistik und Lateinamerika-Studien (jeweils Spanisch) dazu dienen, Ihre Hausarbeiten mithilfe von Zotero anfertigen zu können.

### CODE REVIEW

**Comment by schaeffauer** [comment]
Ok, my fault! I changed the name of the file afterwards (because it is just the spanish version and there will be another one for portuguese) - I am going to correct that!.

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

And did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by rmzelle** [comment]
Also, if you'll be submitting styles for Spanish and Portuguese, do you know if the differences are minor enough so a single CSL style would be enough and rely on its automatic localization? If the only differences are translations that might work.

**Comment by POBrien333** [comment]
Pinging @schaeffauer regarding the outstanding questions. Happy to help.

**Comment by rmzelle** [comment]
Hi, we're closing this issue because we haven't heard from you in a long time. Note that we can always reopen this issue if you get back to us.

**Comment by schaeffauer** [comment]
Hi,

excuse me for having abandonned the issue for several weeks - please  
let it open, I am going to continue it in the second half of the  
current week and if everything is going well, I hope to conclude it in  
the next week.

Thank you very much for your patience!

With kind regards,
Markus

Zitat von "Rintze M. Zelle" <notifications@github.com>:

> Hi, we're closing this issue because we haven't heard from you in a  
> long time. Note that we can always reopen this issue if you get back  
> to us.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/4733#issuecomment-647408988


-- 
Prof. Dr. Markus Klaus Schäffauer

Romanische Philologie / Spanischsprachige
und portugiesischsprachige Literatur und Medien

Universität Hamburg
Institut für Romanistik
- Raum 11023 -
Überseering 35
D-22297 Hamburg

Tel:    ++49 (+40) 42838 4794
Fax:    ++49 (+40) 42838 6242

www.mkschaeffauer.de

**Pull request closed without merging**
