### PR TITLE
Create acta-scientiae-veterinariae.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/56735/style-request-acta-scientiae-veterinariae
Adapted for journal articles, books, chapter, reports, websites.

Examples here: http://www.ufrgs.br/actavet/45/045.htm

### CODE REVIEW

**Comment by rmzelle** [comment]
@damnation333, I noticed you didn't fix this to English. Did you find any indication that this journal publishes in Portuguese as well? E.g. all the titles at http://www.ufrgs.br/actavet/45/045.htm are English, and I could find no mention of "English" or "Portuguese" in the English instructions to authors.

**Comment by rmzelle** [comment]
@POBrien333, bump.

**Comment by rmzelle** [comment]
Thanks! (you've recently overtaken @ zuphilip in terms of commits! https://github.com/citation-style-language/styles/graphs/contributors)

**Comment by POBrien333** [comment]
haha :) nice one. Still way to go to catch up even with Charles or even you and Adam....

**Pull request merged**
