### PR TITLE
Create IEEE with DOI

### PR DESCRIPTION
**Pull request by csps-uam**
Add DOI information, if available, to IEEE citation style (in reference list, not inline).

### CODE REVIEW

**Comment by adam3smith** [comment]
what is this for? I don't see this in any of the IEEE style guides.

**Comment by csps-uam** [comment]
DOI allows quick reference finding an access.

**Comment by adam3smith** [comment]
I know why DOIs are useful in general and we do have styles that always print them (the Elsevier styles, APA, Chicago Manual for journal articles, etc.). Our [criteria for inclucion](https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles) are basically that a style is either used in a specific journal or published in a manual for wide use somewhere. I don't think that's the case here?

**Comment by rmzelle** [comment]
@adam3smith, see #1963 for more discussion.

**Comment by adam3smith** [comment]
Closing based on the discussion in #1963

**Pull request closed without merging**
