### PR TITLE
Update sciences-po-ecole-doctorale-note-french.csl

### PR DESCRIPTION
**Pull request by AnnaCouthuresIdrizi**

### CODE REVIEW

**Comment by AnnaCouthuresIdrizi** [comment]
I'm sorry, i think i'm lost with re-indent request. Could you please explain me how to proceed from this pull request ? Thank you, Anna

**Comment by adam3smith** [comment]
That's not a request; that's an automated change to standardize the appearance of the style code ([you can see what it does here](https://github.com/citation-style-language/styles/pull/6290/commits/cce459f10802ec49e828eaf78e3aa70465f07714)). Nothing for you to do.

**Comment by AnnaCouthuresIdrizi** [comment]
Dear Sebastian,
Thank you !
So I could close the pull request ?
Best,

*Anna Couthures-Idrizi*

bibliothécaire Humanités & admin Catalogue
Sciences Po Bibliothèque
Direction des Ressources et de l'Information Scientifique
27 rue Saint-Guillaume 75337 Paris cedex 07 France
T. +33 (0)1 45 49 50 43
Libguide Humanités <http:///>
<https://www.linkedin.com/edu/school?id=12454>


Le mer. 9 nov. 2022 à 13:53, Sebastian Karcher ***@***.***> a
écrit :

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
