### PR TITLE
Create publicatiewijzer.csl

### PR DESCRIPTION
**Pull request by RonaldVisser**
I've created this Dutch style for Archaeology and want to share it. Style as prescribed in Diepeveen-Jansen, M./J. Kaarsemaker, 2004: Publicatiewijzer voor de archeologie, Amsterdam (Themata 1).

### CODE REVIEW

**Comment by RonaldVisser** [comment]
Dear maintainers, can you help me with these errors? The style validates in the CSL validator, but I don't understand the  "self" link error and the et-al rules should be fine.

**Comment by POBrien333** [comment]
Have a look at this guide and also at other style. Your "info" section should look similar to other styles, then you have everything.
https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#csl-style-repository-requirements

In line 268 you specified `et-al-use-first="19"`, but no `et-al-min`. Add the latter and then it will validate. What et-al rules do you want in the style generally speaking?

**Comment by RonaldVisser** [comment]
Thanks! I'll try to submit again with the corrections. There should be no et al in the bibliography, so I'll remove the et-al-rules there.

**Comment by POBrien333** [comment]
We'd prefer if you just edited your PR here.
If you need any specific help let us know.

**Comment by RonaldVisser** [comment]
Sorry, I missed the option to edit the file. My mistake. I created a new pull request (#6319). I'll remove that one, and do the editing here.

**Comment by POBrien333** [comment]
Ah, you had created a new one already. You're fast. Great. thanks :)

Some of the others will review the style now, but please be patient as the backlog is a bit long at the moment. Thanks.

**Comment by adam3smith** [comment]
Thanks! Style looks good -- did you start with any existing style as a template (even if modified a good bit)? If so,  do you recall which?

**Comment by RonaldVisser** [comment]
I can not remember if I did. I might have, but I made this some time ago and decided to polish it and make it available. I normally document if I use something others have made, but I could not find much. However, I found an earlier version in my files. I think I might have used this one as inspiration: https://github.com/citation-style-language/styles/blob/master/journal-of-animal-physiology-and-animal-nutrition.csl

**Comment by adam3smith** [comment]
Thanks & sorry for the delay!

**Pull request merged**
