### PR TITLE
fix editor label for french apa.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/81829/eds-in-french

### CODE REVIEW

**Comment by POBrien333** [comment]
Closed. See thread on forum.

**Comment by POBrien333** [comment]
Reopened. See thread. 🤔

**Comment by bwiernik** [comment]
Looks good to me. Could you add it to the other APA variants? (Not apa-tr.csl or apa-fr-provost.csl obviously)

**Comment by POBrien333** [comment]
@bwiernik 
I changed all the APA 7 versions. None of the older versions.
Could you check this is all ok now?

**Comment by adam3smith** [comment]
@bwiernik -- I assume we should also update this for the 6th edition?

**Comment by bwiernik** [comment]
Yeah, and 5th while we are at it.

**Comment by adam3smith** [comment]
@POBrien333 do you mind? If this is inconvenient for you, I can also do the remaining ones in a separate PR.

**Comment by POBrien333** [comment]
All fine. I'll make two separate PRs for these :) (plenty of time....)

**Comment by bwiernik** [comment]
@POBrien333 Also apa-old-doi-prefix.csl and apa-no-doi-no-issue.csl please

**Comment by bwiernik** [comment]
Thanks! Looks good to me!

**Comment by adam3smith** [comment]
merci bien!

**Pull request merged**
