### PR TITLE
Create skripsi-sejarah-universitas-gadjah-mada.csl

### PR DESCRIPTION
**Pull request by asyrafi-m**
Based on Chicago Style Full with Footnote. Citation style suitable for Department of History, Faculty of Cultural Sciences, Universitas Gadjah Mada's Skripsi and/or Undergraduate Thesis. Including footnote citation ibid., op. cit., loc. cit., etc.

### CODE REVIEW

**Comment by adam3smith** [comment]
@asyrafi-m Are the requirements for this style documented somewhere you could link to?

**Comment by asyrafi-m** [comment]
> @asyrafi-m Are the requirements for this style documented somewhere you could link to?

Hi there, the requirements for this style is not documented online. I have to ask my friend in Indonesia for the print documentation.  Will that sufficient?

**Comment by asyrafi-m** [comment]
Oh, and the documentation is, unfortunately, fully in Indonesian / Bahasa Indonesia.

**Comment by adam3smith** [comment]
Documentation in Indonesian is fine, but we'd really like it online somewhere, if need be uploaded to this thread.

**Comment by asyrafi-m** [comment]
Dear @adam3smith here the best my friend could get from our department library. 
This is a manual for skripsi (undergraduate thesis) which this citation style aimed for.

https://drive.google.com/open?id=1_XIW5WLkr29zEQzmkSR8uc7b4xq8AzQT

**Comment by rmzelle** [comment]
@asyrafi-m, thanks! Do you know if this manual has an ISBN, or an entry in your online library catalog? That would help us track down the manual if there ever is a need. In addition, do you think you could attach those pictures as attachments here?

I also renamed the style a little, to "Universitas Gadjah Mada - Departemen Sejarah (Indonesian)". Does that look okay? We always put the university name first, and https://sejarah.fib.ugm.ac.id/beranda/ says "Departemen Sejarah" instead of "Jurusan Sejarah". We also typically don't include "thesis" or "skripsi" in style titles, since most university departments only have a single citation style.

**Comment by asyrafi-m** [comment]
> @asyrafi-m, thanks! Do you know if this manual has an ISBN, or an entry in your online library catalog? That would help us track down the manual if there ever is a need. In addition, do you think you could attach those pictures as attachments here?
> 
> I also renamed the style a little, to "Universitas Gadjah Mada - Departemen Sejarah (Indonesian)". Does that look okay? We always put the university name first, and https://sejarah.fib.ugm.ac.id/beranda/ says "Departemen Sejarah" instead of "Jurusan Sejarah". We also typically don't include "thesis" or "skripsi" in style titles, since most university departments only have a single citation style.

Hi there @rmzelle 
Yes, sure. I have no problem with the rename. I'm just following the guide directed from Zotero documentation page. I'm so sorry if it isn't following the general rule. 

Regarding the name of Jurusan Sejarah and Departemen Sejarah: You are correct. They are named Departemen Sejarah now. Recently, this year if I'm not mistaken, the faculty adopted new management for departments under it. This adoption includes changing the term "Jurusan" to "Departemen". So it is correct. This style is commonly used in Department of History, before and after the re-management.

Regarding the ISBN and entry, I am not quite sure we have it. Because it was published for student (thus the ISBN problem) in 2007 (we didn't really have good online catalog system back then). As far as I know, that was the last and latest manual available. This is the first attempt to bring the citation style on Zotero.

Hereby I attached the manual.
whatsapp image 2018-11-13 at 04 50 15
whatsapp image 2018-11-13 at 04 43 24
whatsapp image 2018-11-13 at 04 43 36
whatsapp image 2018-11-13 at 04 44 09
whatsapp image 2018-11-13 at 04 44 30
whatsapp image 2018-11-13 at 04 44 42
whatsapp image 2018-11-13 at 04 49 55
whatsapp image 2018-11-13 at 04 49 56 1
whatsapp image 2018-11-13 at 04 49 56
whatsapp image 2018-11-13 at 04 49 57


Thank you,

Kind Regards.
Asyrafi Muhammad

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
