### PR TITLE
uow-harvard.csl

### PR DESCRIPTION
**Pull request by diamanc**
University of Westminster - Harvard Citation Style Sheet

### CODE REVIEW

**Comment by adam3smith** [comment]
the style itself looks great, thanks. In line with our naming conventions, could you rename the style to 
Harvard - University of Westminster
and change id, filename, and self link to ```harvard-university-of-westminster``` (obviously with the .csl file extension for the filename the way you have it now)
you can update your pull request by clicking the edit(pencil) button here:
https://github.com/diamanc/styles/blob/patch-1/uow-harvard.csl
Let us know when you're done.

**Comment by rmzelle** [comment]
Also please consolidate

```
    <author>
      <name>Cristiano Diamanti</name>
    </author>
    <contributor>
      <name>Cristiano Diamanti</name>
      <uri>http://www.mendeley.com/profiles/cristiano-diamanti1/</uri>
    </contributor>
```

You can just move over the `uri` to the `author` element, and remove the `contributor` element.

**Comment by diamanc** [comment]
Thanks guys. Done it.

Cristiano

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
