### PR TITLE
Create bulletin-of-the-chemical-society-of-japan.csl

### PR DESCRIPTION
**Pull request by shojitakahashi**
This is a dependent style for the-chemical-society-of-japan.csl

### CODE REVIEW

**Comment by adam3smith** [comment]
The filename for this one should be bulletin-of-the-chemical-society-of-japan.csl -- but actually hold off on making that change: this will fail Travis tests until we've accepted your other pull request for the parent style. Once that's done, you renaming the file here will trigger another run of the tests which should then be fine.

**Comment by shojitakahashi** [comment]
Thanks.  I will wait.  I think the filename is already correct (bulletin-of-the-chemical-society-of-japan.csl).  Am I looking at a different thing?

**Comment by adam3smith** [comment]
You probably mean the id. the filename is this here and it's currently still set to the-chemical-society-of-japan.csl . But as I said, hold off on the fix, please

screenshot from 2015-12-10 10 28 19

**Comment by adam3smith** [comment]
thanks!

**Comment by rmzelle** [comment]
(in general, it's preferable to update the "documentation" link for dependent styles; for this style, it could be http://www.journal.csj.jp/bcsj/submission/manuscript-preparation#mp-raa )

**Pull request merged**
