### PR TITLE
New style for TU Dresden

### PR DESCRIPTION
**Pull request by jmiba**
Create
technische-universitat-dresden-betriebswirtschaftslehre-logistik-author-
date.csl

### CODE REVIEW

**Comment by rmzelle** [comment]
Will this style be used in German only?

**Comment by jmiba** [comment]
How it will be used I hardly can tell, yet I deliberately created it to be localizable to any language. However, I was not quite easy with some of the german terms, so I changed them. I expect some use of the style in English, at least. So it is not over the top to provide localization.

**Comment by rmzelle** [comment]
I'm asking because if the style is primarily used in German, it might make sense to fix it to that language (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#3---style-locale ).

**Comment by jmiba** [comment]
Yes, I know. But it is really meant to be used in different languages.

**Comment by rmzelle** [comment]
Okay, in that case the style is good to go.

**Comment by jmiba** [comment]
Thanks, very kind! And so fast!

**Comment by rmzelle** [comment]
We aim to please. :)

**Pull request merged**
