### PR TITLE
Create associacao-brasileira-de-normas-tecnicas-ibict-initials.csl

### PR DESCRIPTION
**Pull request by deivdy**
Estilo Instituto Brasileiro de Informação em Ciência e Tecnologia - ABNT (autoria abreviada) (Portuguese - Brazil)

### CODE REVIEW

**Comment by adam3smith** [comment]
sorry, just behind on this one.

**Comment by andreappel** [comment]
@adam3smith, could you please reopen this one? Also, it is related to #4202, which was also closed.

**Comment by rmzelle** [comment]
Thanks. Apologies for the long wait.

If IBICT has a webpage that describes its ABNT citation format variant, please let us know.

(see also #4202)

**Comment by andreappel** [comment]
Thank you very for the support, @rmzelle and @adam3smith!
Gonna prepare some documentation describing the updates and provide you as soon as it's uploaded.

**Pull request merged**
