### PR TITLE
Create arrbhousestyle.csl

### PR DESCRIPTION
**Pull request by ARRBlibrary**

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! What is ARRB and who would be using the style? We're generally reluctant to accept house styles, though will do so when they are for very large orgs or for publications open to outside submissions

**Comment by adam3smith** [comment]
@TonyARRB -- did you see my question about the styleguide? We have a very strong preference to have public style guides available so we can address any reported issues ourselves (and/or judge pull requests and submitted changes)

**Comment by TonyARRB** [comment]
> 
> 
> @TonyARRB -- did you see my question about the styleguide? We have a very strong preference to have public style guides available so we can address any reported issues ourselves (and/or judge pull requests and submitted changes)

Hi @adam3smith 

I'm sorry for the late reply. As it stands I'm trying to get the main website updated to include the ARRB Style Guide but that is a different department so sometimes these things take time.

As soon as I can put a definitive public facing link in I will add it to github. Will keep you posted.

Thanks

Tony

**Comment by adam3smith** [comment]
Great, thank you! If you're OK uploading it here as a file (you can just drag a file to a comment box) that'd be sufficient, certainly as an interim solution.

**Comment by adam3smith** [comment]
@TonyARRB any updates here?

**Comment by TonyARRB** [comment]
Hi @adam3smith.

Sorry this is taking a long time. Holidays and some other tasks have taken me a bit off this particular project. At this stage I don't believe the style sheet has been uploaded to an open facing page although I do understand that it will be shortly. I'll double check with them about that today.

[Referencing Guide.pdf](https://github.com/citation-style-language/styles/files/7999334/Referencing.Guide.pdf)

In the meantime, I've uploaded a copy of our referencing guide here. Hopefully this is helpful. Once I hear back from my colleague about where the web facing version will be I'll let you know.

Thanks

Tony

**Comment by TonyARRB** [comment]
Hi @adam3smith 

I added https://www.railknowledgebank.com/Presto/pl/NmQ5ZmY0YWQtNTc4NS00YzZiLTk3MTItNjEzYWQxZTgyMTRlLjcxNjg= as the document location for the following

<?xml version="1.0" encoding="utf-8"?>
<style xmlns="http://purl.org/net/xbiblio/csl" class="in-text" version="1.0" demote-non-dropping-particle="sort-only" default-locale="en-GB" page-range-format="minimal">
  <info>
    <title>Australian Road Research Board</title>
    <id>http://www.zotero.org/styles/australian-road-research-board</id>
    <link href="http://www.zotero.org/styles/australian-road-research-board" rel="self"/>
    <link href="http://www.zotero.org/styles/style-manual-australian-government" rel="template"/>
    <link href="https://www.railknowledgebank.com/Presto/pl/NmQ5ZmY0YWQtNTc4NS00YzZiLTk3MTItNjEzYWQxZTgyMTRlLjcxNjg=" rel="documentation"/>

I'm getting a lot of error messages now. Not sure what to do at this stage. Any advice would be helpful.

Thanks

Tony

**Comment by adam3smith** [comment]
Ignore the errors, they have nothing to do with your style

**Comment by TonyARRB** [comment]
Thankyou for that news @adam3smith. I think the style is done now. Please let me know if there is anything I missed.

**Comment by bwiernik** [comment]
Thanks!

**Pull request merged**
