### PR TITLE
Create university-college-lillebaelt-apa.csl

### PR DESCRIPTION
**Pull request by roaldfrosig**
APA variation for use by students at University College Lillebælt, Denmark

### CODE REVIEW

**Comment by adam3smith** [comment]
this is distinct from the regular APA style with some Danish terms switched out?

**Comment by roaldfrosig** [comment]
Yes, the main difference is how legislation and bills and bills are
rendered.

There's also some minor differences like underlining URLs.

On Tue, Mar 31, 2015 at 6:59 AM, Sebastian Karcher <notifications@github.com

**Comment by rmzelle** [comment]
Are there any more variants than the Vancouver and Harvard ones?

**Comment by roaldfrosig** [comment]
No. At University College Lillebælt the only reference styles allowed for
the students are Harvard, Vancouver and APA, so I won't be uploading more
styles.

I do hope that there will come some later corrections. The UCL variations
are in some cases inconsistent or unnecessary idiosyncratic, and I hope our
style requirements will be updated and bettered soon. But until then, all I
can do is to try to make Zotero consistent with the rules our students have
to follow.

**Comment by rmzelle** [comment]
The use of field categories is a bit inconsistent. For this style, we have:

```
    <category field="psychology"/>
    <category field="generic-base"/>
```

whereas the Harvard and Vancouver don't list any fields. Is that intentional? It would also be good to add a "template" link to the latter two, so we know which CSL style they're based on.

**Comment by roaldfrosig** [comment]
That's because I made the Harvard and Vancouver styles from scratch - I
found that it was easier than using an existing style.
The APA-style didn't need so much tinkering, and I have a better
understanding of csl now, so I used the APA 6th ed. as template, and
haven't changed the categories.

I can see that having <category field="generic-base"/> is plain wrong. Is
it ok if I just delete both 'category fields' from the APA style, and leave
it at that?

**Comment by rmzelle** [comment]
> I can see that having <category field="generic-base"/> is plain wrong. Is
it ok if I just delete both 'category fields' from the APA style, and leave
it at that?

Sure. For the full list, see
http://docs.citationstyles.org/en/stable/specification.html#appendix-i-categories

"generic-base" is actually acceptable for institution-wide CSL styles that are used for a wide range of disciplines. You can select all the styles with it at https://www.zotero.org/styles. So you can leave it in, too, but then you'd have to update the other two styles (and their dependents).

**Comment by rmzelle** [comment]
Thanks. Will you create English dependents for the APA and Harvard versions as well?

**Comment by roaldfrosig** [comment]
Thanks.
There are no plans to include english versions of the APA and Harvard
versions as of yet. But it might happen.

**Comment by rmzelle** [comment]
Okay. Thanks again for contributing!

**Pull request merged**
