### PR TITLE
Create german-kunstwissenschaft.csl

### PR DESCRIPTION
**Pull request by malte-frey**
I'm relativly new to this and needed to get some specification for german citing style, fitting to my needs. The code could probably be simplified.

### CODE REVIEW

**Comment by rmzelle** [comment]
@malte-frey, thanks. Is your style based on any style guide in particular? We generally only accept styles in the repository that are based on a documented citation format. See also https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link

**Comment by malte-frey** [comment]
Yes, it's wirtten according to the standards of The Academy of Fine Arts Münster, Germany. I put the documentation link in the file now, which leads to a PDF describing the standards.

**Comment by rmzelle** [comment]
Thanks! That'll do nicely. We'll just name the style after the Kunstakademie Münster, then.

And did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by malte-frey** [comment]
Yes, I did. I put in the link now. Is this ok?

**Comment by rmzelle** [comment]
Great, thanks!

**Comment by malte-frey** [comment]
Hey guys, would it be possible to change the name of the style to german kunstwissenschaft.csl again? Due to some specifics in the code I could not 100% write it like the template link would advise. Additionally, I wrote some things on which are no specific instructions in the guidelines. To be sure that there is no legal trouble I'd rather youd'd change the name. Thank you.

**Pull request merged**
