### PR TITLE
Create university-college-lillebaelt-vancouver-english.csl

### PR DESCRIPTION
**Pull request by roaldfrosig**
English version of university-college-lillebaelt-vancouver, I have made it as a dependent style as suggested by Rintze: https://forums.zotero.org/discussion/47839/supporting-two-languages/#Item_2

### CODE REVIEW

**Comment by rmzelle** [comment]
Dependent styles need to be placed in the "dependent" subdirectory. I also prefer the file name "university-college-lillebaelt-vancouver-en.csl" (we usually just use the short-hand language code), with the style ID to match. Also add a "self" link, please.

You should be able to make all these changes by updating this pull request. Let us know if you need instructions.

**Comment by zuphilip** [comment]
(@rmzelle A CSL style is still valid without the self link, why?)

**Comment by rmzelle** [comment]
@zuphilip, the CSL specification doesn't require any links, except for "independent-parent" for dependent styles. It's also not really crucial for dependent styles, except for auto-updating.

We do have a stricter version of the CSL schema for the repository (https://github.com/citation-style-language/schema/blob/master/csl-repository.rnc), but it only works if the `<info/>` section is sorted correctly due to some limitations in RELAX NG. It's probably too much to ask from people submitting styles to validate against that. I run it manually once in a while.

**Comment by rmzelle** [comment]
@roaldfrosig, will you set the other style to German once I merge this? ("de-DE")

**Comment by roaldfrosig** [comment]
Thanks for the help rmzelle - I really appreciate it.
But I'm a bit confused about your last request: The independent style is already set to "da-DK", why should I change that to german?

**Comment by rmzelle** [comment]
Uhm, never mind, then :). There is another pull request for a style that is also multilingual, and I was mixing things up.

**Comment by rmzelle** [comment]
Looks good, thanks!

**Comment by roaldfrosig** [comment]
Thanks!

**Pull request merged**
