### PR TITLE
Acta Neuropathologica update

### PR DESCRIPTION
**Pull request by libora**
https://forums.zotero.org/discussion/69330/andern-eines-zitationsstils
- add new Springer basic numeric et-al alphabetical
- change parent style for Acta Neuropathologica journal to new Springer style

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle I think this is likely the right approach. Please merge if you agree.

**Comment by rmzelle** [comment]
Do we really need this? I see that http://www.springer.com/medicine/pathology/journal/401 says "(Up to six authors, all authors should be listed. If there are more than six, list only the first six, followed by et al.)", but further down it reads "Ideally, the names of all authors should be provided, but the usage of “et al” in long author lists will also be accepted". Wouldn't it be simpler to just stick to the second rule and leave things as they are?

(if we take this, we'd also have to put the style on the skip list of the Springer metadata in the "journals" repo)

**Comment by libora** [comment]
From my point of view as an editor of a scholarly journal, use "et al." in the submissions is not welcome. I can easily change it in the editorial process.

**Comment by adam3smith** [comment]
good call @rmzelle -- especially since the journal also doesn't appear to be using et al. (or at least not consistently) in publication, I think it makes sense to keep the number of styles limited.

**Pull request closed without merging**
