### PR TITLE
Create haffner-style-manual.csl

### PR DESCRIPTION
**Pull request by Pavelus19**
This is a style file for my style manual P. Haffner, A Style Manual for Essays and Theses: https://www.amazon.com/Style-Manual-Essays-Theses-Haffner/dp/0852447434

### CODE REVIEW

**Comment by Pavelus19** [comment]
Would you be able to correct the error for me please, as I'm not quite sure how to do it? :)

**Comment by adam3smith** [comment]
@Pavelus19 did you start with an existing style as a template for this CSL?

**Comment by Pavelus19** [comment]
Thanks very much I'm not sure what I have to do next? :)

**Review by bwiernik — CHANGES_REQUESTED** [review]
A few minor changes

**Comment by Pavelus19** [comment]
Thanks very much to adam3smith and bwiernik for the suggestions and changes!
Most grateful!

**Comment by Pavelus19** [comment]
What's the next step?

**Comment by adam3smith** [comment]
You haven't actually implemented the changes requested by bwiernik above. We'll merge this once you do

**Comment by adam3smith** [comment]
No, you're misunderstanding -- bwiernik suggested changes for you to make (by editing the style as described [in the first automated comment above](https://github.com/citation-style-language/styles/pull/6054#issuecomment-1121087435))

**Comment by bwiernik** [comment]
Hi @Pavelus19, you didn't actually make any changes to the files in your last edit? All of the 3 issues I mentioned are still there. Please change those suffixes to groups with delimiters. Thanks!

**Comment by Pavelus19** [comment]
Hi bwiernik, I'm very happy to make the changes but am unsure how to do this.
Is anyone able to help?
Thanks

**Comment by adam3smith** [comment]
I've made these changes for you, see
https://github.com/citation-style-language/styles/pull/6054/commits/adf3b31851b899a906a5485e875b6b018754c5bf for future reference about what we were referring to

**Comment by Pavelus19** [comment]
Hi adam3smith,
Very many thanks for making these changes for me and for merging.
    I'm really most grateful to you.
    Thanks for showing me how to do it for next time!
    Best,
Paul

**Pull request merged**
