### PR TITLE
Create freie-hochschule-stuttgart.csl

### PR DESCRIPTION
**Pull request by atec21**
Style for academic papers of the Freie Hochschule Stuttgart

### CODE REVIEW

**Comment by rmzelle** [comment]
@atec21, thanks for your submission. Do you know if the style guide for this style is available online?

**Comment by rmzelle** [comment]
@atec21, did you see my question above?

**Comment by atec21** [comment]
> @atec21, did you see my question above?

Yes, already answered via email, but seemed to be a bad idea. ;-) ... The high school doesn't provide their citation guidelines online.

Kind regards,
Erik

**Comment by rmzelle** [comment]
@atec21, thanks!

**Pull request merged**
