### PR TITLE
Add reviewed-title to american-chemical-society-* and reviews-of-modern-physics-with-titles

### PR DESCRIPTION
**Pull request by serpodrick**
Hi

This pull request adds reviewed-title to the american-chemical-society-* and reviews-of-modern-physics-with-titles styles.

Both style guides are entirely silent about about these kinds of publications.

(As an aside, the review and review-book types are confusing. I haven't figured out what review-book is supposed to mean!)

### CODE REVIEW

**Comment by adam3smith** [comment]
Not sure about this -- as it is, this would seem to add confusion if anything: It may look like the review title is part of the title or (in absence of a title) actually the title of the work. How are you envisioning this being used?

**Comment by adam3smith** [comment]
(Travis fails because you're misspelling delimiter, btw.)

**Comment by serpodrick** [comment]
I'm trying to add the reviewed-title after the title like council-of-science-editors does. The CSE style uses the type (review or review-book) to decide whether or not to display reviewed. I was trying to avoid that since if reviewed-title has a value, it's a review. (<ost of the things I'm trying to create citations for are actually journal articles.)  Adding it to the title macro was easier than adding a review macro.

If following the model in council-of-science-editors would be accepted, I can submit a new pull request. (I only use american-chemical-society-with-titles version of ACS and forgot to test the others, sorry!)

**Comment by adam3smith** [comment]
What I'm wondering isn't how the style is going to tell this is a review (that makes sense) but how the reader would be able to tell from a citation that it is.

**Comment by serpodrick** [comment]
I agree. I'll use a non-CSL solution for what I'm trying to accomplish.

**Pull request closed without merging**
