### PR TITLE
Create BFCN.csl

### PR DESCRIPTION
**Pull request by pgiraudoux**
This file corresponds to the style requirements of Bourgogne Franche-Comté Nature

### CODE REVIEW

**Comment by pgiraudoux** [comment]
OK. I forgot to quote the thread lines 8-10;  I have edited the code accordingly, and now it went through the CSL validator.

**Comment by pgiraudoux** [comment]
I have changed the file name BFCN.csl to lowercase bfcn.csl

**Comment by pgiraudoux** [comment]
BFCN changed to bfcn where appropriate

**Comment by rmzelle** [comment]
@pgiraudoux, thanks. Is there a webpage that describes the style requirements? And does the journal have outside contributors that need to submit their manuscripts formatted according to the journal's style requirements?

**Comment by pgiraudoux** [comment]
Not at this stage. We are just processing an author instruction webpage, but this will not be ready before some weeks. Of course contributors are already strongly encouraged to use csl style for their MS submission, and will be more formally invited to do so when the page is ready. For the moment, the documentation link points to the journal website.
Kind regards,

**Comment by rmzelle** [comment]
> We are just processing an author instruction webpage, but this will not be ready before some weeks.

Great. Could you report back here when that page is live?

**Comment by rmzelle** [comment]
Thanks!

**Comment by pgiraudoux** [comment]
> Great. Could you report back here when that page is live?

Yes, of course, I will also modify the link "document" in the csl file accordingly to point to the page "instructions to authors" and commit the modif. Thanks for your concern. Best.

**Pull request merged**
