### PR TITLE
Create KatiGel Diplomarbeit ÖNORM

### PR DESCRIPTION
**Pull request by gschachinger**
Please upload to Zotero public citation styles so that all students are able to use this style for their diploma thesis

### CODE REVIEW

**Comment by adam3smith** [comment]
Thank you. My question from one of the other pull requests for documentation of the citation format remains relevant though: We are reluctant to accept styles with no available documentation since that means they cannot be checked or maintained beyond the original creator. If the style isn't available online, is there a document you could upload here?

**Comment by rmzelle** [comment]
(supersedes #3924, #3925, #3926, #3927, and #3928; @gschachinger, for the future, please note that you can update pull requests per the instructions above. There is generally no need to create new pull requests if the first one gives an error for our automated tests)

**Comment by rmzelle** [comment]
@gschachinger, I just noticed that we already have a "TGM Wien Diplomarbeit" style in the repository that was contributed by you several years ago. See https://github.com/citation-style-language/styles/blob/master/tgm-wien-diplom.csl. Is the style you're submitting now meant to replace our current version, or are they two different citation styles?

(@adam3smith, you actually added this way back in 2011: https://github.com/citation-style-language/styles/commit/837a7936d9f8ae10114b3e329bcde2eebfa2b630#diff-8495915906ba1fa0d34d04e95e36189c )

**Comment by gschachinger** [comment]
Sorry, wenn forgot. Be so kind and put it on your website.
but i don't know what is missing because of the fact that i'm the head of the department my opinion that must be enough for you to put it on your side.
it's not disappoint in contact me you can see my name on the website of the tgm www.tgm.ac.at. Angehört of the department for mechanical engineering.

(Sent with Mobility.)




On Tue, Apr 2, 2019 at 8:04 AM +0200, "stale[bot]" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #3929<https://github.com/citation-style-language/styles/pull/3929>.

**Comment by adam3smith** [comment]
The two remaining questions are this from me:

> Thank you. My question from one of the other pull requests for documentation of the citation format remains relevant though: We are reluctant to accept styles with no available documentation since that means they cannot be checked or maintained beyond the original creator. If the style isn't available online, is there a document you could upload here?


We don't have any doubt that this style is authorized, but we still would much prefer to have some sort of public documentation. If someone reports a problem with the style, for example, we don't want to have to rely on being able to contact you to clarify.

And this from Rintze:

> I just noticed that we already have a "TGM Wien Diplomarbeit" style in the repository that was contributed by you several years ago. See https://github.com/citation-style-language/styles/blob/master/tgm-wien-diplom.csl. Is the style you're submitting now meant to replace our current version, or are they two different citation styles?

Obviously we don't want to unnecessarily host duplicate or quasi-duplicate styles.

**Comment by gschachinger** [comment]
Hello,

I now send you a documentation for the style as an attachment.
Also you will find the style itself with some correction of the title so that the now 2 relevant styles for the TGM are better visible. We need both styles available because of 2 different types of diploma thesis at our institute. The attached documentation is also available on internal TGM servers.


Freundliche Grüße / Best Regards

AV ING-PEAD IGIP ING DIPL.-ING
Gabriele Schachinger

tgm | Abteilungsvorständin für MASCHINENBAU - Anlagentechnik, Fahrzeugtechnik, Industriedesign, New Technologies and Smart Mechanics
University of Applied Sciences | Studiengangsleitung MASCHINENBAU - Mechatronik, Gebäudetechnik, Fertigungstechnik
Geschäftsführerin der Mechanical and Mechatronical Engineering Association - MEA | Verein zur Förderung des Maschinenbaus am tgm
Generalsekretärin der Internationalen Gesellschaft für Ingenieurpädagogik | NMC-Austria, IMC-Member
Vizepräsidentin EMC –  European Federation of National Engineering Associations | Vertreterin Österreichs

Wexstraße 19 - 23
1200 Wien

Mail:   gabriele.schachinger@tgm.ac.at<mailto:gabriele.schachinger@tgm.ac.at>
Tel:      +43 1 33126 260
Mobil:  +43 664 80 126 260




Von: Sebastian Karcher <notifications@github.com>
Gesendet: Mittwoch, 3. April 2019 04:15
An: citation-style-language/styles <styles@noreply.github.com>
Cc: Schachinger Gabriele <gschachinger@tgm.ac.at>; Mention <mention@noreply.github.com>
Betreff: Re: [citation-style-language/styles] Create KatiGel Diplomarbeit ÖNORM (#3929)


The two remaining questions are this from me:

Thank you. My question from one of the other pull requests for documentation of the citation format remains relevant though: We are reluctant to accept styles with no available documentation since that means they cannot be checked or maintained beyond the original creator. If the style isn't available online, is there a document you could upload here?

We don't have any doubt that this style is authorized, but we still would much prefer to have some sort of public documentation. If someone reports a problem with the style, for example, we don't want to have to rely on being able to contact you to clarify.

And this from Rintze:

I just noticed that we already have a "TGM Wien Diplomarbeit" style in the repository that was contributed by you several years ago. See https://github.com/citation-style-language/styles/blob/master/tgm-wien-diplom.csl. Is the style you're submitting now meant to replace our current version, or are they two different citation styles?

Obviously we don't want to unnecessarily host duplicate or quasi-duplicate styles.

**Comment by adam3smith** [comment]
Great thanks -- unfortunately attachments sent by email don't upload here. You'd have to go to https://github.com/citation-style-language/styles/pull/3929 , log in, and then upload them (simply by dragging the file(s) to the comment window.

**Comment by gschachinger** [comment]
[doc-zitiervorlage-tgm-wien-diplom-oenorm.pdf](https://github.com/citation-style-language/styles/files/3050703/doc-zitiervorlage-tgm-wien-diplom-oenorm.pdf)
[tgm-wien-diplom-oenorm.zip](https://github.com/citation-style-language/styles/files/3050704/tgm-wien-diplom-oenorm.zip)

According to your mail adam3smith, here again the attachments. The new title of the style is:
**TGM Wien Diplomarbeit ÖNORM (German)**
Please be so kind and change the name of the style which is included in the zip csl File
I hope now everything is OK with the new, second style.

**Comment by gschachinger** [comment]
So finaly there should be online 2 styles:
TGM Wien Diplomarbeit ÖNORM (German) => the "second" TGM style
TGM Wien Diplomarbeit (German) => the "first" TGM style

**Pull request merged**
