### PR TITLE
Change format to "numeric" for radiopaedia.csl

### PR DESCRIPTION
**Pull request by zuphilip**
This is an online resource and therefore (foot-)notes does not
make much sense, also it is a super-scripted number in the text.

HT @adam3smith which noted this "outliner" for medicine styles

### CODE REVIEW

**Comment by zuphilip** [comment]
Here are some example urls:
* https://radiopaedia.org/articles/alzheimer-disease-1
* https://radiopaedia.org/articles/creutzfeldt-jakob-disease

**Comment by adam3smith** [comment]
we also need to convert this into a numeric style in the citation section though, right?

**Comment by zuphilip** [comment]
Yes, you are right. Moreover, the style seems to have changed in various other aspects which I tried to fix quickly...

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
