### PR TITLE
Create dilektekin.csl

### PR DESCRIPTION
**Pull request by dilektekin**

### CODE REVIEW

**Comment by adam3smith** [comment]
Could you say what the goal/nature of this style is? Currently this links to the MCP style which we already have and appears to be your own custom version of that? We don't include custom styles in the repository -- see https://github.com/citation-style-language/styles/blob/master/README.md#criteria-for-inclusion for details.

**Comment by dilektekin** [comment]
> Could you say what the goal/nature of this style is? Currently this links to the MCP style which we already have and appears to be your own custom version of that? We don't include custom styles in the repository -- see https://github.com/citation-style-language/styles/blob/master/README.md#criteria-for-inclusion for details.

Hi, im writin my thesis and couldnt find the exact style i want. So i edit one of them (which was in accordance %85) and want to make public. Sorry if i did sth wrong.

**Comment by adam3smith** [comment]
Great, thanks -- are those specific thesis guidelines for a university/department? If so, which, and could you link to them? We'd want to publish them under a title that other users could find.

**Comment by dilektekin** [comment]
> 
Thank you so much.
Yes, it's for "Saglik Bilimleri Universitesi" 
The institute's link is 
https://sbe.sbu.edu.tr/

**Comment by adam3smith** [comment]
Sorry for the delay -- we do have that style already though, so this is a duplicate. If something is wrong with the existing style, we'd want an error report or a PR against that. https://www.zotero.org/styles?q=id%3Asaglik-bilimleri-universitesi

**Pull request closed without merging**
