### PR TITLE
Create pontifical-gregorian-university-de.csl

### PR DESCRIPTION
**Pull request by PUG-IS**
This is the German version of the Pontifical Gregorian University style. Shortly I'll add other languages (French,Spanish,English)

### CODE REVIEW

**Comment by rmzelle** [comment]
Do you know if it would be possible to cover most of these languages with a single independent style?

(for a similar situation, see https://www.zotero.org/styles?q=pontificia%20salesiana, where the English, French, Spanish, and Portuguese versions share the same style)

(for a description of independent and dependent styles, see http://docs.citationstyles.org/en/stable/primer.html#independent-and-dependent-styles)

**Comment by PUG-IS** [comment]
Thanks @rmzelle ,
I think that i can do a dependent style for French and Spanish, the only change is about the translation of some "terms" elements (e.g. "editor").
The German style uses different kind of suffix and prefix than the others one, and i don't know if it is possible to use a dependent style.
The English style and the Italian style (already published) are equal, so probably I’ll just have to rename the title.
Is it the correct way?

**Comment by rmzelle** [comment]
> I think that i can do a dependent style for French and Spanish, the only change is about the translation of some "terms" elements (e.g. "editor").

Yes, in that case a dependent style is definitely possible.

> The German style uses different kind of suffix and prefix than the others one, and i don't know if it is possible to use a dependent style.

Can you give an example? (the only thing close that is localizable are quote marks)

> The English style and the Italian style (already published) are equal, so probably I’ll just have to rename the title.

For an example of a dependent and independent style, see https://github.com/citation-style-language/styles/blob/master/dependent/universita-pontificia-salesiana-fr.csl and https://github.com/citation-style-language/styles/blob/master/universita-pontificia-salesiana.csl. The former relies on the latter, but provides an (overriding) "default-locale" value.

Since the repository already has the Italian version as an independent style, you can make an English dependent style that points to the Italian style. Use `default-locale="en-US"` for US English or "en-GB" for British English.

**Comment by PUG-IS** [comment]
> I think that i can do a dependent style for French and Spanish, the only change is about the translation of some "terms" elements (e.g. "editor").

> Yes, in that case a dependent style is definitely possible.

Perfect...I'll do it.

>Can you give an example? (the only thing close that is localizable are quote marks)

Sure.
Italian,Spanish and French style:
`<text variable="title" form="short" quotes="false" prefix="«" suffix="»"/>`
German style:
`<text variable="title" form="short" quotes="false" prefix="„" suffix="“"/>`

Thanks.

**Comment by adam3smith** [comment]
Perfect. If you use `quotes="true"` that will work for all of those languages exactly as you want it. I.e.
`<text variable="title" form="short" quotes="true"/>`

**Comment by PUG-IS** [comment]
Ok...I'm editing the main style ( Italian ) to fix some problems and then i will create dependent styles for the other languages.

**Comment by PUG-IS** [comment]
Ok...I'm editing the main style ( Italian ) to fix some problems and then i will create dependent styles for the other languages.

**Pull request closed without merging**
