### PR TITLE
Create journal-for-veterinary-medicine-biotechnology-and-biosafety.csl

### PR DESCRIPTION
**Pull request by DmytroVovk**
This is a citation style for the Journal for Veterinary Medicine, Biotechnology and Biosafety.
Our website: http://jvmbbs.kharkov.ua

### CODE REVIEW

**Comment by rmzelle** [comment]
@DmytroVovk, thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by DmytroVovk** [comment]
@rmzelle, thank you! Three days ago I agreed with all your edits and added a "template" link.

**Comment by adam3smith** [comment]
@rmzelle looks good to me, leaving for you to merge.

**Comment by rmzelle** [comment]
Thanks!

**Comment by DmytroVovk** [comment]
@rmzelle @adam3smith Thanks!

**Pull request merged**
