### PR TITLE
Create harvard-cite-them-right-all-authors.csl

### PR DESCRIPTION
**Pull request by r-patterson**
I've created a general style that is almost identical to Cite Them Right 10th edition Harvard. The only thing that is different is that sources with 4 or more authors in the reference list give all author instead of the first author followed by et al. I've called the style 'Cite Them Right 10th edition - Harvard (all authors in reference list)'. The Cite Them Right Online guide gives the following guidance:

Example: book with four or more authors

In-text citation:
This was proved by Young et al. (2015, pp. 21–23) ...

Reference list:
Young, H.D. et al. (2015) Sears and Zemansky's university physics. San Francisco, CA: Addison-Wesley.

Or, if your institution requires referencing of all named authors:

Young, H.D., Freedman, R.A., Sandin, T.R. and Ford, A.L. (2015) Sears and Zemansky's university physics. San Francisco, CA: Addison-Wesley.

### CODE REVIEW

**Comment by POBrien333** [comment]
See https://forums.zotero.org/discussion/80135/style-request-based-on-cite-them-right-10th-edition-but-listing-all-authors-in-the-reference-list#latest

**Comment by r-patterson** [comment]
Hi.  No-one has been in touch about this request.  Is there something else that I'm meant to have done? Thanks.  Ruth

**Comment by adam3smith** [comment]
No sorry, it was just Thanksgiving here and we're a little behind, but this
looks good in general.

**Comment by rmzelle** [comment]
Thanks! (and thanks for your patience; this repository is maintained by two volunteers, so we often can't offer quick feedback)

**Comment by r-patterson** [comment]
Thank you!  This is very much appreciated.  Happy to wait - I just wasn't sure whether I had done it right!

**Pull request merged**
