### PR TITLE
Create misc.csl

### PR DESCRIPTION
**Pull request by MelaniePerron**

### CODE REVIEW

**Comment by rmzelle** [comment]
@MelaniePerron, what does "MISC" stand for? And how is this style related to the existing McGill CSL styles? (https://www.zotero.org/styles?q=mcgill)

**Comment by MelaniePerron** [comment]
MISC is the acronym for a research project held by one of our law faculties. MISC stand for « Modes d’intervention en situation de conflits ».

We had to modify the existing McGill style to have full notes for subsequent references instead of « supra » or « ibid. ».

[http://www.bibl.ulaval.ca/images/bibli_logo_170_80.png]

Mélanie Perron

Bibliothécaire-conseil en droit


Bibliothèque de l’Université Laval

Pavillon Jean-Charles-Bonenfant

2345, allée des Bibliothèques, local 2376

Québec (Québec) G1V 0A6

Téléphone : 418 656-2131, poste 7978

Télécopieur : 418 656-7699

melanie.perron@bibl.ulaval.ca<mailto:melanie.perron@bibl.ulaval.ca>

bibl.ulaval.ca<http://www.bibl.ulaval.ca/>

[http://www.bibl.ulaval.ca/images/logo-facebook-20.png]<https://www.facebook.com/bibliotheque.ulaval/>




_____________________________________________________

Avis relatif à la confidentialité / Notice of Confidentiality<http://www.rec.ulaval.ca/lce/securite/confidentialite.htm>



De : Rintze M. Zelle [mailto:notifications@github.com]
Envoyé : 5 décembre 2017 20:55
À : citation-style-language/styles <styles@noreply.github.com>
Cc : Mélanie Perron <melanie.perron@bibl.ulaval.ca>; Mention <mention@noreply.github.com>
Objet : Re: [citation-style-language/styles] Create misc.csl (#3172)


@MelaniePerron<https://github.com/melanieperron>, what does "MISC" stand for? And how is this style related to the existing McGill CSL styles? (https://www.zotero.org/styles?q=mcgill)

**Comment by adam3smith** [comment]
We generally accept styles that we expect to be used by a large-ish group of people. What's the target group for this? If we're just talking about one research group, could it make sense to distribute the style locally?

**Comment by MelaniePerron** [comment]
The style is for one research group. It could be distributed locally, but the research project is about giving access to legal information. This philosophy also extends to the methodological aspects of the research. We wanted to make it available for anyone who might need it.

**Comment by rmzelle** [comment]
> The style is for one research group. It could be distributed locally, but the research project is about giving access to legal information. This philosophy also extends to the methodological aspects of the research. We wanted to make it available for anyone who might need it.

The repository is primarily for styles where the style author doesn't know the users of their style. The main examples of such styles are those for general style guides (APA, Chicago, McGill) and for journals. Our repository styles are distributed to hundreds of thousands of users, so we generally exclude styles with a small known audience to keep the repository size in check.

Like @adam3smith, I'm afraid this doesn't appear to be a good fit for us. I think we would only accept this if, a) there is a webpage where MISC describes this citation format, and b) the research project seeks outside contributions for which the authors need to use this citation format. If it's only for internal use, we wouldn't take it.

**Comment by adam3smith** [comment]
That said, I do really appreciate the spirit of openness of your project and I think you should absolutely make your style available publicly, e.g. via your website or even your own code repository.

**Pull request closed without merging**
