### PR TITLE
Create international-renewable-energy-agency.csl

### PR DESCRIPTION
**Pull request by sobinw**

### CODE REVIEW

**Review by sobinw — COMMENTED** [review]
reviewed

**Comment by sobinw** [comment]
thank you

**Comment by adam3smith** [comment]
Thanks! Is this any different than the IEA style? https://www.zotero.org/styles?q=id%3Ainternational-energy-agency-organisation-for-economic-co-operation-and-development

**Comment by sobinw** [comment]
Dear Sebastian,

Yes, we have made many changes to this style.

Thanks & regards,
Sobin

**Comment by adam3smith** [comment]
Thanks -- so is the style guide available somewhere? We generally dislike accepting styles without a published style guide, as we can't check on any error reports

**Comment by adam3smith** [comment]
@sobinw see my question above we do really need a published style guide in order to be able to take this style.

**Comment by adam3smith** [comment]
Closing for inactivity -- happy to re-open if you get back to us on the questions above, just post here

**Pull request closed without merging**
