### PR TITLE
Update nature.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/98158/referencing-preprint-in-nature-format

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! Since this is one of the first ones where we explicitly code preprint, I wanted to get this just right so we can use the code as a template -- see updated version.

**Comment by POBrien333** [comment]
Great. I'll add this adjustment for the other nature style(s) when I get a chance.

**Comment by POBrien333** [comment]
Pleaser check if I did everything 100% correct. Thanks :)

**Comment by adam3smith** [comment]
Yes, looks great, thanks! (FWIW, this will look weird if preprints have neither URL nor DOI, but I think we can ignore that possibility)

**Pull request merged**
