### PR TITLE
Extended the hdm style for my bachelor thesis.

### PR DESCRIPTION
**Pull request by ieservices**
Extended this citation style for our univercity.

### CODE REVIEW

**Comment by rmzelle** [comment]
Can you correct the style so that it is valid CSL? See http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Fieservices%2Fstyles%2Fmaster%2Fstuttgart-media-university.csl&version=1.0.1

**Comment by ieservices** [comment]
Hi Rintze,

I'll see what I can do - I did that 1,5 years ago -but just thought of 
publishing it ;)

BR Martin
Am 01.04.2015 um 22:12 schrieb Rintze M. Zelle:

**Comment by rmzelle** [comment]
I'm surprised this even worked for you :).

The biggest issue seems to be that you define a lot of new terms, which isn't (currently) allowed, but there are a bunch of other errors. Let us know if you need help.

The style also has been receiving various corrections over the years (https://github.com/citation-style-language/styles/commits/master/stuttgart-media-university.csl), so if you're dedicated to this, it would be better to start out from the version in our repository.

**Comment by ieservices** [comment]
Well, back then I didn't even know that there is a csl validator - but I 
needed those term in my Zotero -

And about your style - I guess I started from it - and extended it...

So What shall we do about the not-yet supported terms, such as:

speech, source, thesis, title, websitecall, year? - and what about the 
<if> and <else> tags?

Thanks for the help!

Am 01.04.2015 um 22:47 schrieb Rintze M. Zelle:

**Comment by rmzelle** [comment]
> And about your style - I guess I started from it - and extended it...

Right. But if you forked the style 1.5 years ago, your version will be missing the maintenance we did on it since the fork.

> What shall we do about the not-yet supported terms

You can print verbatim text with `<text value="..."/>`. Text defined this way doesn't localize, but if your style is fixed to German that doesn't really matter.

> what about the <if> and <else> tags?

They need to be children of a `<choose/>` element. See http://docs.citationstyles.org/en/stable/specification.html#choose

**Comment by rmzelle** [comment]
I'm closing this pull request for now because of inactivity. If you wish to fix up your pull request in the future, just post a comment and we can reopen this.

**Pull request closed without merging**
