### PR TITLE
Create normes-presentation-sc-hum-cegep-drummond.csl

### PR DESCRIPTION
**Pull request by cegepdrummond**

### CODE REVIEW

**Comment by cegepdrummond** [comment]
Can I please get some help understanding the errors? Thanks.

**Comment by adam3smith** [comment]
the errors are all due to the fact that you´ve placed the file in the subfolder "dependent," which is only for styles that are nothing but links to an already existing style.
I don't have time to check for other problems and @rmzelle will likely want you to rename the style somewhat, but that's the problem you're getting from Travis.

**Comment by rmzelle** [comment]
https://github.com/blog/1436-moving-and-renaming-files-on-github shows how you can move the style out of the "dependent" folder.

The style title should probably be something like "Cégep de Drummondville - sciences humaines (French-Canada)" (if this is the only style in use at this institution, the "- sciences humaines" can be left out). The file name should then be "cegep-de-drummondville-sciences-humaines.csl" (or "cegep-de-drummondville.csl"), and match up with the style ID and "self" link.

See also https://github.com/citation-style-language/styles/wiki/Style-Requirements

**Comment by rmzelle** [comment]
To edit/move the style, use the pencil (edit) icon at https://github.com/cegepdrummond/styles/blob/patch-1/dependent/normes-presentation-sc-hum-cegep-drummond.csl.

**Comment by rmzelle** [comment]
Let us know if you need any help with this.

**Comment by rmzelle** [comment]
I'm closing this pull request for now because of inactivity. If you wish to fix up your pull request in the future, just post a comment and we can reopen this.

**Pull request closed without merging**
