### PR TITLE
Update taxon.csl to fix author disambiguation

### PR DESCRIPTION
**Pull request by damnation333**
see https://github.com/citation-style-language/styles/issues/2509
Fix author disambiguation

### CODE REVIEW

**Comment by adam3smith** [comment]
did you check over this otherwise? -- I just had a quick glance at a recent article (there's a free one in the Dec. 2016 issue) and it looks nothing like this style.

**Comment by damnation333** [comment]
Nothing like it is a bit is maybe a bit harsh, but I've found some mistakes just now. (open paper: http://www.ingentaconnect.com/contentone/iapt/tax/2016/00000065/00000005/art00007)
I made this style not too long ago and I was contacted by the editor people, so they must be generally happy with it apart from the disambiguation stuff. (I did spot some issues though with title italication).

**Comment by adam3smith** [comment]
no, you're right. I actually overlooked some things in the code, it looks much better than I thought it did -- I just saw the code taken from APA and the style being quite un-APAish, but see a lot of the key things are actually right. The et al. for the bibliography isn't, though. I don't think they do et al. there at all. See the Wang et al. article with 11 authors in the bibliography of the article you link to.

**Comment by damnation333** [comment]
Thanks for pointing that out. I've fixed that!

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
