### PR TITLE
Create stanovnistvo.csl

### PR DESCRIPTION
**Pull request by gljk**
Adding the style for Serbian demography journal called Stanovništvo.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! Please
- Check on the formatting of page numbers of in-text citations (the style says (Lutz 2014: 530), you currently produce (Luty 2014, pp. 530)
- Check on et al settings: the style says et al for four or more authors in text, you're doing three or more. Also, check when they want et al. in the bibliography -- you currently have it for 8 or more authors.

**Comment by gljk** [comment]
@adam3smith Thank you for the corrections. I have fixed it.

**Comment by gljk** [comment]
@adam3smith Are there any more actions expected on my part before merging? I have just went through the documentation again and it seems everything is in order.

**Comment by adam3smith** [comment]
Thanks!

**Comment by gljk** [comment]
Thank you!

**Pull request merged**
