### PR TITLE
Create United States International Trade Commission.csl

### PR DESCRIPTION
**Pull request by USITC-Zotero**
Hello, we're reaching out to create a dedicated CSL file for the United States International Trade Commission. Please feel free to contact us at Zotero_WG@usitc.gov if you have any questions or suggested edits. Thank you!

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! A couple of initial questions:
1. How is this style going to be used (e.g., by all USITC personnel, by outside authors, etc.)
2. Is there a public style guide you could link to?
3. Did you base this style on an existing citation style? If so, which?

**Comment by adam3smith** [comment]
(ignore the failing test for now)

**Comment by USITC-Zotero** [comment]
Hi Adam,

1. This style is public-facing, but I imagine most users will be at the agency.
2. Please give me a few moments to check with our editor team. I know we have a style guide, but I'm not sure if it is hosted publicly.
3. We based our existing citation style on the 17th edition of the Chicago Manual of Style.

Cheers!

**Comment by USITC-Zotero** [comment]
Following up on the earlier comment, the USITC's style is not posted online publicly. We may need to add a link at a later point.

**Comment by adam3smith** [comment]
Would you be able to upload a copy here (you can just drag a file to a comment window)? We are fairly insistent for public CSL styles to refer to public style guidelines, so that they can be corrected (if need be).

**Comment by USITC-Zotero** [comment]
Okay, I will verify that the internal guidance can be shared publicly. If it cannot, we may need to delay a few days.

**Comment by USITC-Zotero** [comment]
Hi Sebastian, our editor recommended citing to the [Chicago Manual of Style's guide](https://www.chicagomanualofstyle.org/tools_citationguide.html). Again, our agency's style is a small modification to the Chicago style.

**Comment by adam3smith** [comment]
Great thanks -- is there a list of the major differences, which would also help me review this?

**Comment by USITC-Zotero** [comment]
Our editor says a list of major differences won't be available until July. I'll work to see if I can get their approval to send the example list of citations that way you have some examples to compare with the file's outputs.

So you're aware, we currently use the file internally for our work products and staff research, Errors or needed fixes are infrequent with none requested in the last 10 weeks. Major changes that I can remember programming are listed below. Please note that it's been 7 months since we started, so please forgive me for not remembering more. 

- We use abbreviated names in footnotes for government agencies or intergovernmental organizations.  
- To accomplish the above, we repurposed the extra field. allow authors can enter abbreviated agency or institution names under the extra field and it will replace the author field (we needed a creative solution)
- Consecutive, duplicate citations will not be automatically shortened
- all titles in footnotes are in the short title format by default with title case. If none short title is provided, the long title field will be used instead.
- We created a few logical conditions to handle certain odd situations. For example, websites entered without an author will be populated with the website title in footnotes.

**Comment by rmzelle** [comment]
@USITC-Zotero, I assume this style can have a fixed localization of US English? Or will you be using it in other languages as well? (I just made this change but we can easily roll it back)

@adam3smith, other than missing documentation and template links the metadata looks fine to me.

**Comment by USITC-Zotero** [comment]
@rmzelle Yes, the style will use US English.

**Comment by USITC-Zotero** [comment]
> C

**Comment by USITC-Zotero** [comment]
Hey, I opted to close / reopen the pull request for the moment. It appears some of the outputs need correcting. Let me send a copy of the results to our editor for a "final review."

**Comment by adam3smith** [comment]
OK, just let us know when this is ready for final review

**Comment by USITC-Zotero** [comment]
The document should be ready for final review, but we have one persistent error. We're missing a space between the author field and the webpage's title.

> Citation Style Editor,“CSL Search by Example,” 2012

**Comment by rmzelle** [comment]
> The document should be ready for final review, but we have one persistent error showing up in checks. We're missing a space between the author field and the webpage's title in the website example's footnote.
> 
> > Citation Style Editor,“CSL Search by Example,” 2012

Where are you seeing this problem (i.e., with what software)? If I test the style with Zotero, I get:

> Individual Citations
> Citation Style Editor, “CSL Search by Example,” 2012.
> Bibliography
> Citation Style Editor. “CSL Search by Example,” 2012. http://editor.citationstyles.org/searchByExample/.

**Comment by USITC-Zotero** [comment]
The error occurred in the bot's output (see image below). Given that we're unable to reproduce the error, it may just be an isolated issue.

{2FDA0405-11A6-41E2-808A-438B516D75BB} png

**Comment by USITC-Zotero** [comment]
@rmzelle @adam3smith hey, so what's the status on this pull request? After some additional testing with the CSL file, I am unable to reproduce the bot's error mentioned above.

**Comment by adam3smith** [comment]
Yeah, this just needs a final look from one of us. Nothing we need from
your end.
Thanks!

**Comment by rmzelle** [comment]
@adam3smith, things looked fine for me in Zotero, so I assume this is a bug in the CSL rendering here?

**Comment by rmzelle** [comment]
@USITC-Zotero, thanks, and sorry for the wait.

**Comment by USITC-Zotero** [comment]
@rmzelle @adam3smith Awesome, thank you both for your patience!

**Pull request merged**
