### PR TITLE
change s. d. to s.d. in french style for INBO reports (issue #2)

### LINKED ISSUE #2: settle on new base uri for styles, update ids accordingly
Right now, styles have a base uri of `http://zotero.org/styles`. We need to change that to a more generic like `http://citationstyles.org/styles/`. 

A separate question is whether we want to serve files directly from github, either using the github base uri, or some sort of indirection (cnames, or whatever).

### PR DESCRIPTION
**Pull request by ElsLommelen**
This PR intends to solve issue #2.
fixes #2

### CODE REVIEW

**Comment by florisvdh** [comment]
Note that a few more commits are to come before this PR is actually ready. (Best turn this PR to draft)

**Comment by adam3smith** [comment]
Let us know when this is ready for review

**Comment by florisvdh** [comment]
This PR is ready! My apologies for the delay.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
