### PR TITLE
Update harvard-university-of-technology-sydney.csl

### PR DESCRIPTION
**Pull request by MeijunHuang**
Hi

University of Technology Sydney - Harvard has been changed since 2017 for Mendeley users . Hope it will also keep up-to-date for other users from Gitbub.com. The newest version of University of Technology Sydney - Harvard can be downloaded from the following link.

https://csl.mendeley.com/styles/17238301/harvard-university-of-technology-Sydney-2

Regards
Meijun Huang
University of Technology Sydney

### CODE REVIEW

**Comment by MeijunHuang** [comment]
Thanks for your response.

There some problems when I copy and paste the codes into the edit window, the lines all go to the left. I don’t know how to do it properly. Could you help to copy and paste it from the following link.

https://csl.mendeley.com/styles/17238301/harvard-university-of-technology-Sydney-2

Regards
Meijun

**Comment by rmzelle** [comment]
@MeijunHuang, thanks. There were two small issues. `<text suffix=">" variable="URL" prefix="<"/>` had to be changed to `<text suffix="&gt;" variable="URL" prefix="&lt;"/>` to be valid XML, and we don't allow the use of forced sentence case for titles, since it's so error prone.

**Comment by MeijunHuang** [comment]
Thanks

please go ahead to do the changes.

Meijun

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MeijunHuang** [comment]
Hi there

I notice the double quotation marks are used in the samples, but actually they are single quotation marks. Could you please the double quotation marks to single?

Thanks
Meijun

**Comment by rmzelle** [comment]
> I notice the double quotation marks are used in the samples, but actually they are single quotation marks. Could you please the double quotation marks to single?

Can you give an example of a formatted reference of how the current CSL style and the desired format differ?

**Comment by rmzelle** [comment]
(answered in #4229)

**Pull request merged**
