### PR TITLE
Create biologia

### PR DESCRIPTION
**Pull request by matejovo**
http://www.degruyter.com/view/j/biolog new style for Biologia (ISSN:1336-9563)

### CODE REVIEW

**Comment by adam3smith** [comment]
you'll need to add a .csl file extension to the filename (though not the id/link). Without that, most tests won't even run properly.

**Comment by adam3smith** [comment]
wait, what's going on here? Why did you close and delete?

**Comment by rmzelle** [comment]
@adam3smith, continued in #1924?

**Comment by matejovo** [comment]
My firs contribution to github, I am confused. So If I wanted rename file to .csl extension, It was not possible. Then I create new and also I rename branch to better orientation. 
It is going in https://github.com/citation-style-language/styles/pull/1924

**Comment by rmzelle** [comment]
For the future, https://help.github.com/articles/renaming-a-file/ has instructions on how to change the file name.

**Comment by rmzelle** [comment]
(it's usually preferable to correct your initial pull request instead of creating new ones)

**Pull request closed without merging**
