### PR TITLE
Add eva-berlin-numeric.csl to repository

### PR DESCRIPTION
**Pull request by thtbln**

### CODE REVIEW

**Comment by adam3smith** [comment]
OK, so it looks like the conference submission deadline passed, so I don't think this makes sense anymore, I'm afraid. As I said on the Zotero forums, it'd have been OK to ping us here, especially given the deadline -- I was also confused by the multiple pull requests with changing names. Next time please follow the instructions above and update your initial pull request.

**Comment by thtbln** [comment]
Sorry @adam3smith, this was my first pull request (and I've learned a lot). The conference is every year, so it would be useful to have the style available for the 26th conference in 2019.

**Comment by adam3smith** [comment]
and the citation guidelines stay about the same? And is the conference in Berlin every year or would it make sense to remove the location?

**Comment by rmzelle** [comment]
> And is the conference in Berlin every year or would it make sense to remove the location?

Looks like it's always in Berlin: https://www.eva-berlin.de/en/eva_archiv-2/eva-berlin-archive/ says "Since 1994 the Berlin EVA Conference has annually been taking place ..."

**Comment by rmzelle** [comment]
@thtbln, some questions: are the citation style guidelines available online? And do they specify multiple citation formats, or just this numeric one?

**Comment by rmzelle** [comment]
@adam3smith, please merge this if this looks good to you.

**Pull request merged**
