### PR TITLE
Create expert-reviews-in-molecular-medicine.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/92687/expert-reviews-in-molecular-medicine#latest

The in-text "Ref." or "Refs" cannot be done with CSL, correct?

They want "....blal (Ref. 1) said that was confirmed by everyone else (Refs 2-5)."

### CODE REVIEW

**Comment by adam3smith** [comment]
> The in-text "Ref." or "Refs" cannot be done with CSL, correct?

We could add "Ref." to the layout prefix, but we can't make the singular/plural distinction, so I think better to leave that for the user to add as prefix or so. Not ideal, but...

**Comment by adam3smith** [comment]
Looking at the author guidelines, I do wonder whether we shouldn't use square brackets as explicitly requested there? Always hard to say when those are wrong & when journals change this in typeset. I'd be somewhat inclined to go with the latter assumption here?

**Comment by POBrien333** [comment]
It's a 50/50 chance. I mean, if editors request it out hopefully a user reports it and we can just change it.

**Comment by bwiernik** [comment]
@POBrien333 Let’s go with the brackets as per the style guidelines

**Comment by bwiernik** [comment]
Thanks!

**Pull request merged**
