### PR TITLE
journal-of-forensic-and-legal-medicine.csl

### PR DESCRIPTION
**Pull request by Sankar-GEO-ELS**
Style for Elsevier nonstandard journal with slight changes to the Vancouver style

### CODE REVIEW

**Comment by Sankar-GEO-ELS** [comment]
Please help me to understand about the failure and please tell me about the next step to be taken to pass this pull request. Thanks

**Comment by cpina** [comment]
Style file names should end in .csl . Otherwise they are not parsed as a style and considered a "extra file".

**Comment by Sankar-GEO-ELS** [comment]
Thanks Carls

**Comment by adam3smith** [comment]
great, thanks!

**Pull request merged**
