### PR TITLE
Update aerosol-science-and-technology.csl

### PR DESCRIPTION
**Pull request by damnation333**
Fixes made as requested here: https://forums.zotero.org/discussion/comment/272932/#Comment_272932

Something odd is happening on the CSL editor. 
Campbell, J.L. and Pedersen, O.K. (2007). The varieties of capitalism and hybrid success. Comp. Polit. Stud., 
40(3):307–332.
Borges, J.L. (1999). Selected non-fictions. Viking, New 
York.
There is a new line for some citations. Any clue why?

### CODE REVIEW

**Comment by adam3smith** [comment]
We've come across that newline problem in the editor before. I believe @zuphilip helped fix it at the time -- which browser is this on?

**Comment by adam3smith** [comment]
Thanks!

**Comment by damnation333** [comment]
I'm editing in Chrome (although I use FF for all my browsing).
As long as I know it's just a bug, I don't mind.

**Comment by adam3smith** [comment]
yeah, definitely nothing to do with the style(s), so nothing to worry about for you.

**Comment by zuphilip** [comment]
The fix was for firefox only, because it worked okay with Chrome, but maybe they changed something now. See here for the issue: https://github.com/citation-style-language/csl-editor/issues/161

**Pull request merged**
