### PR TITLE
Create springer-vancouver-french-citation-label-and-page-locators.csl

### PR DESCRIPTION
**Pull request by favabien**
Inspired from [Springer Vancouver](http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fspringer-vancouver) and [DIN 1505-2 (alphanumeric, German)](https://www.zotero.org/styles/din-1505-2-alphanumeric) styles.
Translated in French. Use label based citations with page locators.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- is that style documented somewhere and/or used by some specific organization? 
(Context: https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles )

**Comment by favabien** [comment]
Hello,
I use it for my Bachelor Thesis. This style folllows the rules that my
University gave me. There's no documentation beside the one from the style
I'm inspired of
<http://www.springer.com/cda/content/document/cda_downloaddocument/Key_Style_Points_1.0.pdf>
.

2016-09-06 2:39 GMT+02:00 Sebastian Karcher <notifications@github.com>:

**Comment by adam3smith** [comment]
While we really appreciate the submission, I don't think we'll take this then -- styles that are only used by small groups of people and aren't documented publicly are not a good fit for the repository. 

Sorry about that, again thanks for your submission and for your understanding.

**Comment by favabien** [comment]
Ok, I understand. I just wanted to add a style which is a "label" style to
the repo, because there's only one there
<https://www.zotero.org/styles?format=label>!
Thanks for making this style repo anyway...

2016-09-06 22:15 GMT+02:00 Sebastian Karcher <notifications@github.com>:

**Pull request closed without merging**
