### PR TITLE
Associacao-Brasileira-de-Normas-Tecnicas-FMVZ-USP.csl 

### PR DESCRIPTION
**Pull request by saufmvz**
...usp.csl

- Inline: 
: citation: chronological order
: et-al: above 4 authors, mention all authors

- Bibliography: 
: chapter: added page number after year; (eds.) was changed to (ed.)
: thesis: added year after title; added page number after year;
: paper-conference: added proceeding issue; added publication year and locator-publisher; added issue year and publication year;

### CODE REVIEW

**Comment by adam3smith** [comment]
There's a couple of problems here, but let's start with what you actually want to do:
With this, you're actually replacing the existing ABNT style with a different style. We're certainly not going to accept that, but I suspect it's also not what you're actually trying to do.

**Comment by AlbertoKawai** [comment]
I'm helping to write this style... in reality, we are trying to adapt to requested style from FMVZ-USP, a college from University of São Paulo - Brazil... it will be a new style, we don't want to replace the existing style.

**Comment by rmzelle** [comment]
See https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md for instructions on how to submit a new style.

**Comment by saufmvz** [comment]
Dear sirs, we were submitted another style (#1). Please, disregard 1503. Thank you.

**Comment by rmzelle** [comment]
Are you trying to submit https://github.com/saufmvz/fmvz-usp/commit/9ccfdf2fae011f32e6acd4b49023c3f96ad230e7 ?

**Comment by AlbertoKawai** [comment]
Yes! We had verified the code in the indicated scripts before that too.

**Comment by saufmvz** [comment]
Yes, please.  If all are correct, we want to submit. Thank you.

**Comment by rmzelle** [comment]
Can you visit https://github.com/citation-style-language/styles, and then click the "+" icon, and then add your new style?
(at the right here: 
image )

The first two lines of the style at https://github.com/saufmvz/fmvz-usp/commit/9ccfdf2fae011f32e6acd4b49023c3f96ad230e7 should also be removed.

**Comment by saufmvz** [comment]
Yes, thanks

**Comment by rmzelle** [comment]
Continued in #1510.

**Pull request closed without merging**
