### PR TITLE
Update durban-university-of-technology-harvard.csl

### PR DESCRIPTION
**Pull request by seancarte**

### CODE REVIEW

**Review by adam3smith — COMMENTED** [review]
Sorry for the long wait here -- a couple of questions inline

**Comment by adam3smith** [comment]
@seancarte  please see comments above

**Comment by seancarte** [comment]
Hi Sebastian

Sorry, I'm still hoping to get a response from the librarians who asked me
to upload the style.

Sean

**Comment by adam3smith** [comment]
Hi @seancarte any update here? -- I'd like to merge or (at least until you have an answer) close this to keep some semblance of order in the pull request queue

**Comment by seancarte** [comment]
I'm really sorry about this, Sebastian, I've had no response from the
librarians. Please close this and I'll start again when the librarians
figure out what it is they want.

Sean

**Comment by adam3smith** [comment]
Thanks and no worries -- you can just post here and I can re-open. No need to start from scratch.

**Pull request closed without merging**
