### PR TITLE
SpringerProtocols2017

### PR DESCRIPTION
**Pull request by GermainRousselet**
Springer Protocols style version 2017

### CODE REVIEW

**Comment by GermainRousselet** [comment]
Hi,
I'm very new here, but I am editing a book of protocols for Springer, and I need to have a style publicly available for authors working with Mendeley. I know the style is working with me. How will it go on from now?

**Comment by rmzelle** [comment]
I rewrote your corrections a little, but thanks for submitting them!

**Comment by GermainRousselet** [comment]
Thank you!
How can people have access to the style?

**Comment by rmzelle** [comment]
The updated version is live in the Zotero Style Repository (https://www.zotero.org/styles?q=id%3Aspringerprotocols). Mendeley should have the updated version available by now as well.

**Pull request merged**
