### PR TITLE
Create begell-apa.csl

### PR DESCRIPTION
**Pull request by SergeyOST**
new 'Begell-APA' style for the Begell House Inc, a scholarly publisher https://www.begellhouse.com/

### CODE REVIEW

**Comment by adam3smith** [comment]
Is a description of this style, or how it differs from regular APA, available online?

**Comment by SergeyOST** [comment]
> Is a description of this style, or how it differs from regular APA, available online?

These are the styles for the Begell House Inc.
Where can I add description for them?

**Comment by adam3smith** [comment]
Ideally the description would be available online. If not, you can paste or upload it here.

**Comment by SergeyOST** [comment]
Ok, 
We prepared a spreadsheet of our active journals with the data you requested. The file is available here - https://www.begellhouse.com/files/Journals4CSL.xls

May be this is what you need?

**Comment by adam3smith** [comment]
That's indeed very helpful, but what we'd want to know is: How do these styles differ from the regular APA, Chicago, and Vancouver? 
Or put differently, what would you tell an author who doesn't use a reference manager in terms of formatting their references.

**Comment by SergeyOST** [comment]
I need to ask my colleague from Begell. I'll let you know tomorrow.
Thanks.

**Comment by adam3smith** [comment]
Thanks! (I also just saw your correspondence with my colleague @rmzelle which provides additional context)

**Comment by SergeyOST** [comment]
Does you mean Authors instructions?
For example, http://dl.begellhouse.com/forauthors/journals/6a7c7e10642258cc.html (Begell Chicago)
http://dl.begellhouse.com/forauthors/journals/00551c876cc2f027.html (Begell APA)
http://dl.begellhouse.com/forauthors/journals/4b27cbfc562e21b8.html (Begell Vancouver)

**Comment by rmzelle** [comment]
@SergeyOST, hi again.

Can you tell us which existing CSL styles you based these three on, so we can add "template" links (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link). And can you confirm that you modified the citation format of each? (if you e.g. need standard APA, we can link any journal styles directly to that without creating a Begell House APA variant).

I'm also a little confused by the Vancouver version. The CSL style here isn't actually Vancouver (which always is a numeric style instead of an author-date format), while the link you gave us (http://dl.begellhouse.com/forauthors/journals/4b27cbfc562e21b8.html) clearly says "Cite references in the text in numerical order using superscript numerals, placed close-up (no space) after punctuation."

**Comment by SergeyOST** [comment]
@rmzelle , hi :)
Thank you for your corrections.

I have used standard APA 7th editition style [http://www.zotero.org/styles/apa](http://www.zotero.org/styles/apa) for our 'Begell House APA' and Chicago 17th edition (note and author-date)  [http://www.zotero.org/styles/chicago-note-bibliography](http://www.zotero.org/styles/chicago-note-bibliography) and [http://www.zotero.org/styles/chicago-author-date](http://www.zotero.org/styles/chicago-author-date) for Begell House Chicago.

I confirm that I have modified the citation format of each BH APA and BH Chicago.

As for Vancouver style, it is my mistake. It is should be a numeric style. I do not modified the standard style, only renamed it.
You can delete our BH Vancouver style and use the standard Vancouver [http://www.zotero.org/styles/vancouver](http://www.zotero.org/styles/vancouver) for our journals.

Thanks.

**Comment by rmzelle** [comment]
Thanks! I just added the dependent CSL styles for the 50 journals as well.

**Comment by SergeyOST** [comment]
Thank you for your work.

**Pull request merged**
