### PR TITLE
Update arts-university-bournemouth.csl

### PR DESCRIPTION
**Pull request by Dbelk**
Have tried to incorporate all of the changes suggested in last pull request.
Sorry if this isn't the way it's supposed to be done but i couldn't see how to edit my latest attempt.

Duncan

(RZ: continuation of #2894 and #2895)

### CODE REVIEW

**Comment by rmzelle** [comment]
@Dbelk, before I accept this, have you actually tested your modified versions?

**Comment by Dbelk** [comment]
Hi Rintze,

No, we have not tested the modified version because we only know how to test an accepted version.
The modified version is based on our testing of our currently accepted version though.
How do we test a version we can’t use from the Zotero style library?

Duncan


Duncan Belk
Digital Services Librarian
+441202363394
dbelk@aub.ac.uk
aub.ac.uk

​The contents of this communication are confidential and intended solely for the use of the named recipient(s). If you have received this email in error please delete it and do not disseminate, distribute, copy or alter it. Any views or opinions expressed are those of the author and do not necessarily represent those of Arts University Bournemouth.

Although  Arts University Bournemouth has taken reasonable precautions to ensure no viruses are present in this email, the University cannot accept responsibility for any loss or damage arising from the use of this email or attachments.

**Comment by bwiernik** [comment]
You can download the .csl file from GitHub at this link:
https://github.com/Dbelk/styles/raw/c02ac6169c46067b1dcd099c67f8c132782fff2a/arts-university-bournemouth.csl

Then install this into Zotero and see if it formats things as you would like.

**Comment by rmzelle** [comment]
Yes, if you're using Zotero you should be able to install the downloaded style via the Preferences window, per https://www.zotero.org/support/preferences/styles.

**Comment by Dbelk** [comment]
Hi Rintze,

We have been testing for the last couple of days and have learned quite a lot, as well as hopefully created a style that will work.
I will create a pull request for it now.

Duncan


Duncan Belk
Digital Services Librarian
+441202363394
dbelk@aub.ac.uk
aub.ac.uk

​The contents of this communication are confidential and intended solely for the use of the named recipient(s). If you have received this email in error please delete it and do not disseminate, distribute, copy or alter it. Any views or opinions expressed are those of the author and do not necessarily represent those of Arts University Bournemouth.

Although  Arts University Bournemouth has taken reasonable precautions to ensure no viruses are present in this email, the University cannot accept responsibility for any loss or damage arising from the use of this email or attachments.

**Comment by bwiernik** [comment]
This pull request is still open--you can just continue to make commits to the current pull request branch, rather than opening a new one.

**Comment by POBrien333** [comment]
Can this be closed now?

**Comment by rmzelle** [comment]
Yes. Thanks all!

**Pull request closed without merging**
