### PR TITLE
Create journal-applied-clinical-medical-physics.csl

### PR DESCRIPTION
**Pull request by stefanopeca**
Hi, I needed Mendeley to format my biblio for this journal, so here it is.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks!

**Comment by stefanopeca** [comment]
Hi, thanks for your help, I'm new to GitHub

I realized I made a mistake - I did not cite the name of the initial
developer of this code (I modified it, did not write from scratch). His
name is Sebastian Karcher.  Could his name be added? I tried editing but I
get that I need to be on a branch (?) to do so...

thanks!!

**Comment by adam3smith** [comment]
(no, that's fine as long as the template link is in the style, which is the case; thanks!)

**Comment by stefanopeca** [comment]
Whait... that;s you?? Now I'm confused, haha!!

On Mon, Oct 17, 2016 at 9:46 AM, Sebastian Karcher <notifications@github.com

**Comment by rmzelle** [comment]
(yes, "adam3smith" is Sebastian's user name on GitHub; see https://github.com/adam3smith)

**Pull request merged**
