### PR TITLE
Update mis-quarterly.csl

### PR DESCRIPTION
**Pull request by bwiernik**
https://forums.zotero.org/discussion/67116/style-error-mis-quarterly

And general clean-up.

Inquired with the journal about whether they want DOI in or not.
Waiting for response.

### CODE REVIEW

**Comment by bwiernik** [comment]
Fixes some other issues with the style than https://github.com/citation-style-language/styles/commit/a8e923509dbb8279fcf1c1d1a1dfaed2f797e04b

**Comment by rmzelle** [comment]
@adam3smith, FYI. (also, Sheldon seems down for this particular PR)

**Comment by adam3smith** [comment]
sorry, I'll merge the changes in once @bwiernik hears back from the journal and we know what to do with the DOI.

**Comment by bwiernik** [comment]
Heard from Journal. They would like the DOI in this format.

**Comment by rmzelle** [comment]
Thanks! (I just resolved the merge conflict by keeping @bwiernik's version, which had the delimiter @adam3smith fixed in the old version already correct)

**Pull request merged**
