### PR TITLE
Update marine-ecology-progress-series.csl

### PR DESCRIPTION
**Pull request by sgorgopa**
Format was not correct (the style that MEPS is dependant to is not very similar to the desired end result, also really out of date), made a new MEPS style using Addiction-Biology as a template.
Changed capitalization of titles, changed the format for the webpage access date (lowercase, added parentheses). Updated the ISSN and the link for author instructions.

### CODE REVIEW

**Comment by sgorgopa** [comment]
The checks appear to have failed because the MEPS style already exists? (issn duplicate)... also because the code probably is written as a standalone style, not dependent like the old version?  Please advise how to move forward. Thank you

**Comment by sgorgopa** [comment]
Should i submit this as a new independent style and have the old (dependent) one removed?

**Comment by rmzelle** [comment]
Don't worry about the checks for now. It's easy for us to fix.

Do you remember which guidelines you based your style on? It looks like all Inter-Research Science Center journals still use the same citation format (see https://www.int-res.com/journals/guidelines-for-authors/manuscript-formatting-requirements-and-preparation-tips/), so if that's the case we just would update that parent style (https://github.com/citation-style-language/styles/blob/master/inter-research-science-center.csl).

**Comment by sgorgopa** [comment]
Okay. 

The guidelines you linked to are correct. So that sounds right, for the parent style to be updated so all Inter-Research Science Center journals would use the updated formatting. Thanks!

**Comment by rmzelle** [comment]
> So that sounds right, for the parent style to be updated so all Inter-Research Science Center journals would use the updated formatting.

Done in https://github.com/citation-style-language/styles/pull/3941, using your style. Thanks!

**Pull request closed without merging**
