### PR TITLE
Create applied-clay-science-chronologically.csl

### PR DESCRIPTION
**Pull request by matejovo**
1.Citation format:
-References in the text should be reported by increasing chronological 
order

Citations in the text may be made parenthetically groups of references should be listed first chronologically, then alphabetically for the same year.

### CODE REVIEW

**Comment by adam3smith** [comment]
you're creating a bit of chaos here ;). Please hold off on pull requests for now and explain what exactly it is you're trying to do. Am I understanding you that the current style for applied clay sciences is incorrect and you're just trying to fix it by ordering in-text citations chronologically?

**Comment by rmzelle** [comment]
@POBrien333, do you mind taking a look?

The current CSL style (https://github.com/citation-style-language/styles/blob/master/dependent/applied-clay-science.csl) is a dependent of Elsevier Harvard (https://github.com/citation-style-language/styles/blob/master/elsevier-harvard.csl), which (presumably correctly) doesn't sort citations primarily by year. Per above, the journal instructions at https://www.elsevier.com/journals/applied-clay-science/01691317/guide-for-authors say:

> Citations in the text should be given in chronological order.

and

> Citations in the text may be made parenthetically groups of references should be listed first chronologically, then alphabetically for the same year.
> - Examples of papers in a text: 
> (Bergaya et al., 1999; Allan and Jones, 1999, 2000a, 2000b; Allan, 2015) and (Tunney and Detellier, 1996; Letaief and Detellier, 2007; Tonlé et al., 2007, 2009; de Faria et al., 2009, 2010, 2011; Yang et > al., 2012; Matusik and W?cis?o, 2014)

**Comment by POBrien333** [comment]
I can confirm. The style was not correct and the suggested style by matejovo fixes the issue.
Checked in guidelines and papers.

**Comment by rmzelle** [comment]
Great, thanks both.

Corresponding exemption in journals repo at https://github.com/citation-style-language/journals/commit/c6664440cc996d69bc639c5a9ba3a3005b7d21ce.

**Pull request merged**
