### PR TITLE
Update hawaii-international-conference-on-system-sciences-proceedings…

### PR DESCRIPTION
**Pull request by danielbmiller**
….csl

Added a space to the citation number delimiter

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks. Can you provide a new "documentation" link that points to the style guide? Our old link is dead.

**Comment by danielbmiller** [comment]
There does seem to be a bit of a disconnect in their documentation.  Contacted one of the mini-track chairs for this years conference and he was not able to locate them.  There is supposed to be a link to the format specifications on http://hicss.hawaii.edu/tracks-and-minitracks/authors/.  It appears it may have been a casualty of their recent site redesign.

**Comment by rmzelle** [comment]
But you're confident about your proposed change?

**Comment by danielbmiller** [comment]
The change was proposed in response to feedback received from my advisor on a paper.  It also brings the number citations in line with papers accepted to HICCS 49 such as:
https://www.computer.org/csdl/proceedings/hicss/2016/5670/00/5670a104.pdf see pg. 104
https://www.computer.org/csdl/proceedings/hicss/2016/5670/00/5670a094.pdf see pg. 97
https://www.computer.org/csdl/proceedings/hicss/2016/5670/00/5670a066.pdf see pg. 68

**Comment by rmzelle** [comment]
Okay, thanks. I added the link to "http://hicss.hawaii.edu/tracks-and-minitracks/authors/". Hopefully they will add a link to the "Initial Format Specifications" there. I did find a link to them in Google Cache (http://webcache.googleusercontent.com/search?q=cache:O9hgoU2fOlgJ:www.hicss.org/author-instructions%23!+&cd=1&hl=en&ct=clnk&gl=us for HICSS-50, which points to http://shidler.hawaii.edu/sites/shidler.hawaii.edu/files/users/tung.bui/hicss/hicss-formatspec-initialmanuscript.doc), but that doesn't describe the citation number delimiter, so we'll just assume that's what they want based on your example papers.

**Comment by danielbmiller** [comment]
Sounds reasonable to me.

Thanks.

**Pull request merged**
