### PR TITLE
Create Ergonomics (journal)

### PR DESCRIPTION
**Pull request by Chris210**
This is a version of Chicago (16th) used for the journal Ergonomics.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- there are  a couple of issues with this still, but could you maybe start by clarifying the nature of this? Ergonomics uses a style that's based on Chicago, but not quite the same, and this is the correct, adjusted version? Do I have that right?

**Comment by Chris210** [comment]
Good afternoon

Although I have been using Mendeley for many years, I am still not very familiar with how to submit the reference system to the database.

Yes, Ergonomics uses a modified version of Chicago 16, which is what this style is.


Regards

Dr Chris Parker
Lecturer in CAD – Design & Fashion Business Subject
PASS Staff Coordinator

Please note I am ‘working to contract’ as part of the UCU  industrial action  in support of fair pay in higher education. This may mean it takes longer for me to respond to emails. You can find out more about the dispute here:https://www.ucu.org.uk/fair-deal-for-HE<https://list.mercury.ucu.org.uk/t/4033/174252/1682/3/?ad5a924d=dWN1LW1lbWJlcnMuX2FsbC1mdWxsLWhlLW1lbWJlcnMtam5jaGVz&560a3889=VUNVIHN0cmlrZSBhY3Rpb246IDI0ICYgMjUgTWF5IDIwMTY%3d&469547c0=TlcwODE%3d&x=1fe7477c>

School of Materials | Faculty of Engineering & Physical Sciences | The University of Manchester
Room C59b, Sackville Street Building | Entrance off Granby Row | Manchester | M13 9PL
Tel: +44 (0)161 306 3007 | E-mail:

Emails will be replied to within five working days
Open Office Hours: Tuesday & Thursday 2pm – 3pm

Twitter<https://twitter.com/UserGenDesign> / Google Scholar<http://scholar.google.co.uk/citations?user=oQbSNL8AAAAJ&hl=en>

**Comment by adam3smith** [comment]
OK great. Did you see https://github.com/citation-style-language/styles/wiki/Style-Requirements ? Could you fix everything pertaining to 4-10 (filename, id, documentation&template link, ISSN).
Also, instead of `generic-base`, please find a somewhat more specific category from this list http://docs.citationstyles.org/en/stable/specification.html#appendix-i-categories (engineering?).
Finally, I'd recommend just adding yourself as the author and removing all other contributors/authors. They're credited via the template link. 

Let us know if you have any questions.

**Comment by rmzelle** [comment]
@Chris210, @adam3smith, it looks like we might already have this format as https://www.zotero.org/styles?q=taylor-and-francis-chicago-author-date (in which case we can create a simple "dependent" style for "Ergonomics" that links to this)

See http://www.tandfonline.com/action/authorSubmission?journalCode=terg20&page=instructions#mp_style and http://www.tandf.co.uk/journals/authors/style/reference/tf_ChicagoAD.pdf

**Comment by Chris210** [comment]
Yes, that sounds exactly right. Please go ahead with this.


Regards

Dr Chris Parker
Lecturer in CAD – Design & Fashion Business Subject
PASS Staff Coordinator

Please note I am ‘working to contract’ as part of the UCU  industrial action  in support of fair pay in higher education. This may mean it takes longer for me to respond to emails. You can find out more about the dispute here:https://www.ucu.org.uk/fair-deal-for-HE<https://list.mercury.ucu.org.uk/t/4033/174252/1682/3/?ad5a924d=dWN1LW1lbWJlcnMuX2FsbC1mdWxsLWhlLW1lbWJlcnMtam5jaGVz&560a3889=VUNVIHN0cmlrZSBhY3Rpb246IDI0ICYgMjUgTWF5IDIwMTY%3d&469547c0=TlcwODE%3d&x=1fe7477c>

School of Materials | Faculty of Engineering & Physical Sciences | The University of Manchester
Room C59b, Sackville Street Building | Entrance off Granby Row | Manchester | M13 9PL
Tel: +44 (0)161 306 3007 | E-mail:

Emails will be replied to within five working days
Open Office Hours: Tuesday & Thursday 2pm – 3pm

Twitter<https://twitter.com/UserGenDesign> / Google Scholar<http://scholar.google.co.uk/citations?user=oQbSNL8AAAAJ&hl=en>

**Comment by rmzelle** [comment]
@adam3smith, do you know the status of https://github.com/citation-style-language/journals/tree/master/taylor-and-francis? It's out of sync with the CSL styles repo.

(I was contemplating using _extra.tab, but maybe it's easier to make this dependent by hand)

**Comment by adam3smith** [comment]
The idea was that we wanted more up to date data, but I haven't been able to get that, through multiple attempts. I'd just do it by hand.

**Comment by rmzelle** [comment]
Is the t&f set in the "journals" repo out-of-date, or more up-to-date than the "styles" repo, though? I get changes to 199 styles when I run the script on it.

**Comment by adam3smith** [comment]
more up to date than in the styles repo, but not without some problems that
need cleaning up first (I think I have notes to that extent). I'll try to
work on that in the next 2 weeks?

On Mon, Jun 20, 2016 at 11:18 PM, Rintze M. Zelle <notifications@github.com>
wrote:

> Is the t&f set in the "journals" repo out-of-date, or more up-to-date than
> the "styles" repo, though? I get changes to 199 styles when I run the
> script on it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/citation-style-language/styles/pull/2104#issuecomment-227330228>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAH32hNIrhkCtPwlvwLd-jfx-aJRiy-_ks5qN1f2gaJpZM4I1HsL>
> .
>



-- 
Sebastian Karcher, PhD
www.sebastiankarcher.com

**Comment by rmzelle** [comment]
No rush, but it would be appreciated. (a readme detailing where the current data has come from would help too, especially now that I've made it hard to see the history :P)

**Comment by rmzelle** [comment]
Added a dependent style for Ergonomics (by hand): https://github.com/citation-style-language/styles/pull/2120

**Pull request closed without merging**
