### PR TITLE
Create united-nations-development-programme-icca-legal-review.csl

### LINKED ISSUE #4541: CSL- United Nations Development Programme ICCA Legal Review
Hi,

I am not a coder at all and tried to follow the guide but I have unfortunately been quite unsuccessful.

Can you make or apply this changes to the existing Style Manager Australian Government (note:

**__chapter in a book, the year should come after the Author's name, 
and **the quotes to the title should be removed__**** 

[Suggested Referencing Style.docx](https://github.com/citation-style-language/styles/files/4134082/Suggested.Referencing.Style.docx)
Anyone able to help? 
I have attached the requirements in the word document. 

Thank you!

### PR DESCRIPTION
**Pull request by POBrien333**
closes #4541

### CODE REVIEW

**Comment by rgm111** [comment]
Thank you so much!!!

**Comment by rmzelle** [comment]
@rgm111, if you wish to test this style you can download it from https://raw.githubusercontent.com/POBrien333/styles/patch-654/united-nations-development-programme-icca-legal-review.csl.

**Comment by POBrien333** [comment]
@rgm111 
Is the style working for you without problems or is there any amendments needed?

**Comment by rgm111** [comment]
I confirm again that the style is working for me and no amendments are needed. Thank you very much!

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
