### PR TITLE
Fix for missing comma in last group, removal of DOI

### PR DESCRIPTION
**Pull request by Braintelligence**
Hello everyone!
We realized that we had a missing comma in the last group, so we ended up with wrongly styled citations. Also we realized that we don't want DOI in our citation, so we removed it for now.

I hope everything is fine, the CSL was validated properly before the PR.

### CODE REVIEW

**Comment by Braintelligence** [comment]
Oh, I forgot to change the updated date. 🐱

**Comment by adam3smith** [comment]
I've adjusted how the comma is handled for robustness (with your code, you could have ended up with citations ending on a comma). I wish you would reconsider the DOI -- they're really useful...

**Comment by Braintelligence** [comment]
Currently there are no plans to show the doi in citation. We do save it in Zotero, however.

**Comment by adam3smith** [comment]
too bad... thanks for the style update.

**Pull request merged**
