### PR TITLE
Create duale-hochschule-baden-wurttemberg-department-of-international…

### PR DESCRIPTION
**Pull request by POBrien333**
…-business.csl

via emails, client on commission.

@adam3smith , I'd be grateful if you could prioritise the review of this style in order to allow the client to link to the public style and make it available for their students. I'd highly appreciate it. :)

### CODE REVIEW

**Comment by adam3smith** [comment]
Have they reviewed & approved?

**Comment by POBrien333** [comment]
Yes. Just did the last round of review and fixes this morning.

**Comment by adam3smith** [comment]
Looks great, thanks!

**Comment by POBrien333** [comment]
Awesome. You're the best

**Pull request merged**
