### PR TITLE
Create mongolian-bibliography-standard

### PR DESCRIPTION
**Pull request by munkhmagnai**

### CODE REVIEW

**Comment by munkhmagnai** [comment]
I did not understand this error at all. now what am I going to do?

**Comment by adam3smith** [comment]
Is this style documented somewhere online?

**Comment by POBrien333** [comment]
I assume this is to go with this Forum thread: https://forums.zotero.org/discussion/71500/need-help-in-submitting-mongolian-bibliography-style-standard

**Comment by adam3smith** [comment]
Closing because of inactivity: @munkhmagnai -- we'd love to have this (or generally a Mongolian) style, so I'm happy to re-open this, but we do need some indication on which document(s) the style is actually based on, ideally in the form of a link.

**Comment by rmzelle** [comment]
@munkhmagnai, I also left a note at https://forums.zotero.org/discussion/71500/need-help-in-submitting-mongolian-bibliography-style-standard, but translating https://github.com/citation-style-language/locales/blob/master/locales-mn-MN.xml would be a great step to improve Mongolian support in CSL. For some reason we already have a CSL locale file for Mongolian but it doesn't look like it was ever translated from English.

**Pull request closed without merging**
