### PR TITLE
Create AfriCHI

### PR DESCRIPTION
**Pull request by andrew-from-pretoria**
File name now without digits

### CODE REVIEW

**Comment by adam3smith** [comment]
This only passes because it doesn't have a file extension. Please don't create new pull requests if you run into trouble. Everything you'd need to do to fix one can be done by updating a single pull request. Pick one to work with, close all the others, and then stay with that. Ask for help if you need it and we're happy to assist.

**Comment by andrew-from-pretoria** [comment]
Thanks Adam, apologies for messing up. I'm new to this.

**Comment by andrew-from-pretoria** [comment]
How do I now add the file extension?

**Comment by adam3smith** [comment]
See https://help.github.com/articles/renaming-a-file/
Please note my comments from the other thread -- i.e. the filename (and id/self link) must be all lowercase letters. You can have 2016 in the filename/id/link (africhi-2016), and should do so if it's also in the style's title. I'm not sure if that makes sense, but typically, for conferences that change citationstyles, it does.

**Comment by andrew-from-pretoria** [comment]
Thanks Adam. I'll check out the link. The reason I'm changing the file name to exclude all digits is because the checker's error messages seemed to indicate that I can only use lower/uppercase letters in some of the fields inside the file. But I could be mistaken since I haven't read all the documentation on how to format the file contents. I was hoping this would be a quick thing to do...I wanted to share the style sheet with others since this conference is using a style that (I think) is uncommon - but again, I could be mistake. Kind regards

**Comment by andrew-from-pretoria** [comment]
Thanks for this free service, much appreciated! You people are doing excellent work!

**Comment by andrew-from-pretoria** [comment]
going home now...

**Comment by adam3smith** [comment]
digits are definitely allowed, see e.g. https://github.com/citation-style-language/styles/blob/master/modern-language-association-8th-edition.csl

**Comment by adam3smith** [comment]
it needs to be all lowercased: `africhi.csl` (same without the extension for id and link)

**Comment by andrew-from-pretoria** [comment]
Dear Sebastian

Thank you so much for your assistance.

Kind regards
Andrew


>>> On 20/07/2016 at 19:22, in message
<citation-style-language/styles/pull/2152/c234018698@github.com>, Sebastian
Karcher <notifications@github.com> wrote:
- it needs to be all lowercased: `africhi.csl` (same without the extension for 
- id and link)
- 
- ---
- You are receiving this because you authored the thread.
- Reply to this email directly or view it on GitHub:
- https://github.com/citation-style-language/styles/pull/2152#issuecomment-234 
- 018698

**Comment by rmzelle** [comment]
@andrew-from-pretoria, you're also submitting your style to the wrong branch in our repository in this pull request, so I'll close this (we don't really use or maintain the "1.0" branch anymore).

**Comment by rmzelle** [comment]
Continued in #2151.

**Pull request closed without merging**
