### PR TITLE
Create universite-du-quebec-a-montreal-guide-des-memoires-et-theses.csl

### PR DESCRIPTION
**Pull request by jjrondeau**
Ce style est conforme aux nouvelles normes décrites dans le Guide de présentation des mémoires et thèses de l'Université du Québec à Montréal publié en septembre 2017.

### CODE REVIEW

**Comment by adam3smith** [comment]
What is the relationship of this style to the existing UQAM style? Should it replace that or are they used in parallel (https://www.zotero.org/styles?q=id%3Auniversite-du-quebec-a-montreal )

**Comment by jjrondeau** [comment]
Hi,

Ideally, we would like to replace the existing one by our new version that is far more complete and that is working in Zotero AND Mendeley. Last February 6th, I wrote to Patrick O’Brien who published the existing UQAM style without notice to ask him to change the name of his style to avoid any confusion for our students but I got no response.

Our version is the official UQAM style developped by the UQAM Library Services. It is compliant with the new UQAM guidelines for the submission of dissertations and theses that were published in September 2017.
The existing «O’Brien» UQAM style is based on a previous partial version that was developped by our library staff (Olga Skliar) and that was not yet ready to be archived in your repository.


I also have a question. Do you still have access to an older version of the UQAM style (Bouthat) that was in the repository a year ago and that was deleted at about the same time the existing UQAM style was published? I would be grateful if I could obtain a copy of this version.

Thank you,
Jean-Jacques
_____________________________________________
Jean-Jacques Rondeau
Librarian
Biochemistry, chemistry, biological sciences, kinesiology and physical education
Science library, Université du Québec à Montréal
(514) 987-3000, poste 3247
http://www.bibliotheques.uqam.ca/sciences




De : Sebastian Karcher [mailto:notifications@github.com]
Envoyé : 17 février 2018 14:51
À : citation-style-language/styles
Cc : Rondeau, Jean-Jacques; Author
Objet : Re: [citation-style-language/styles] Create universite-du-quebec-a-montreal-guide-des-memoires-et-theses.csl (#3321)


What is the relationship of this style to the existing UQAM style? Should it replace that or are they used in parallel (https://www.zotero.org/styles?q=id%3Auniversite-du-quebec-a-montreal )

**Comment by jjrondeau** [comment]
Rondeau, Jean-Jacques souhaite rappeler le message « [citation-style-language/styles] Create universite-du-quebec-a-montreal-guide-des-memoires-et-theses.csl (#3321) ».

**Comment by jjrondeau** [comment]
Hi,
Just as a follow up, do you need further informations to proceed my request?
Many thanks.

**Comment by adam3smith** [comment]
Sorry, things have been busy -- if you mean this to replace the existing style, you should submit it as a pull request modifying the existing style as described here: https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md

As for the old style -- nothing gets deleted here, but it'd take some digging through the history for me to find this -- what do you need it for? You can also cycle through old commits here on the site to track it down.

**Comment by rmzelle** [comment]
Superseded by https://github.com/citation-style-language/styles/pull/3383.

@jjrondeau, if you're still looking for the older version of the UQAM style (Bouthat), that would probably be this version: https://raw.githubusercontent.com/citation-style-language/styles/929692740c06108efba284eab38e565bee87754f/universite-du-quebec-a-montreal.csl

(for the full history of the UQAM style, see https://github.com/citation-style-language/styles/commits/master/universite-du-quebec-a-montreal.csl)

**Pull request closed without merging**
