### PR TITLE
Create art-libraries-society-of-north-america-arlisna-reviews.csl

### PR DESCRIPTION
**Pull request by m406m947**
Initial submission of the Art Libraries Society of North America (ARLIS/NA) Reviews (ISSN 2374-4723) citation style.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! I'm trying to understand how this style would get used. Just for the citation of the reviewed work at the top of the review?

**Comment by m406m947** [comment]
Yes, the guidelines will be updated soon.  Also, on the ARLIS/NA reviews site we keep a full bibliography of all books received from publishers for potential review each year. Librarians use these bibliographies for collection development, which is why the title appears before the author. Please let me know if you have any other questions.
Thank you,
Megan

--
Megan Macken
Assistant Department Head, Digital Resources and Discovery Services
She/Her/Hers, Assistant Professor, University Libraries
405.744.9773 • ***@***.*** • library.okstate.edu
________________________________

**Comment by adam3smith** [comment]
Thanks Megan! So, I'm still wondering if the style makes sense for the repository, i.e. if many people (relatively speaking) need access. Can you very briefly walk me through who you imagine would use it.
(See the criteria for inclusion in the repository readme for reference)

**Comment by m406m947** [comment]
ARLIS/NA Reviews is a bi-monthly publication for a international professional organization of over 1000 members<https://www.arlisna.org/history>. There  are 72 different review authors and 2 editors per year who would need to access the style. Each reviewer formats a single citation for their review. Reviews are indexed by Ebsco. Prior to 2006 Reviews appeared in Art Documentation, published by the University of Chicago Press.

<https://www.arlisna.org/history>
________________________________

**Comment by adam3smith** [comment]
Ok, thanks!

**Pull request merged**
