### PR TITLE
Update and rename sciences-po-ecole-doctorale-note-french.csl to scie…

### PR DESCRIPTION
**Pull request by AnnaCouthuresIdrizi**
…nces-po-ecole-recherche-note-french.csl

### CODE REVIEW

**Comment by AnnaCouthuresIdrizi** [comment]
Hello,
Now that the rename action has been approved, how to pull request to modify something in the renamed csl file ?
Best regards,
Anna

**Comment by AnnaCouthuresIdrizi** [comment]
Dear Brenton,
I'm OK with that, but I forgot how to do it.. Could you explain me how to
modify the file inside of the previous pull request ?
If not, could i cancel this pull request and start again from the
beginning, modifying only the style title ?
Many thanks in advance for your help,
Anna

*Anna Couthures-Idrizi*

bibliothécaire Humanités & admin Catalogue
Sciences Po Bibliothèque
Direction des Ressources et de l'Information Scientifique
27 rue Saint-Guillaume 75337 Paris cedex 07 France
T. +33 (0)1 45 49 50 43
Libguide Humanités <http:///>
<https://www.linkedin.com/edu/school?id=12454>

**Comment by bwiernik** [comment]
Go to your copy of the repository online https://github.com/AnnaCouthuresIdrizi/styles

Click the branch dropdown menu in the upper left corner (will probably say master) and choose patch-13 (you can see the name of the branch for the PR at the top of this PR screen where it shows which branch is being merged into the CSL repo).

Then go to the file you've edited and edit it again. 

Let me know if you have any questions!

**Comment by bwiernik** [comment]
Thank you!

**Pull request merged**
