### PR TITLE
Create IPB PPKI 3 style

### PR DESCRIPTION
**Pull request by auriza**

### CODE REVIEW

**Comment by rmzelle** [comment]
@auriza, you don't need to create a new pull request if some of the automatic tests fail. You can just update one of the existing pull requests (#4546, #4547, or this one) per the instructions above.

**Comment by auriza** [comment]
I'm sorry, the edit icon (pencil) is not seen anywhere.

**Comment by rmzelle** [comment]
> I'm sorry, the edit icon (pencil) is not seen anywhere.

Ah, sorry. Once in a while GitHub makes small changes to its web interface. I've updated our instructions now (you can see the new instructions at e.g. https://github.com/citation-style-language/styles/pull/4551#issuecomment-582294545; the pencil icon has been replaced by an option in the ellipsis menu).

**Comment by auriza** [comment]
> I've updated our instructions now (you can see the new instructions at e.g. [#4551 (comment)](https://github.com/citation-style-language/styles/pull/4551#issuecomment-582294545); the pencil icon has been replaced by an option in the ellipsis menu).

Thank you very much. I hope that will benefit other newcomers also.

**Pull request closed without merging**
