### PR TITLE
Update clinical-physiology-and-functional-imaging.csl

### PR DESCRIPTION
**Pull request by libora**
https://forums.zotero.org/discussion/comment/314347/#Comment_314347

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, since you submitted this style less than a month ago, could you review these changes?

**Comment by POBrien333** [comment]
Will do when back from holidays.
Thanks Libor for putting in the fix.

**Comment by POBrien333** [comment]
The fixes are correct.
One more:
Line 36: group suffix needs to be a . and not a ;

**Comment by rmzelle** [comment]
Thanks both!

**Pull request merged**
