### PR TITLE
Update bursa-uludag-universitesi-sosyal-bilimler-enstitusu-metinici-a…

### PR DESCRIPTION
**Pull request by ozhansaglik**
…tif.csl

### CODE REVIEW

**Comment by adam3smith** [comment]
I don't think this works -- by moving the year into the publisher macro, it won't be included in any item types that don't print the publisher macro, including thesis, speech, and the various article types.

**Comment by ozhansaglik** [comment]
Hi Adam,

Thank you for your thoughts. We need to place date after the publisher for books and before the range of pages for articles in journals. How can we manage these?

Best wishes

Özhan

**Comment by adam3smith** [comment]
Could you put a couple of sample citations here, including, ideally, one that includes an original date of publication? (Don't worry about italics etc. this is just about the order of elements)

**Comment by ozhansaglik** [comment]
BORGES Jorge Luis, Selected Non-Fictions, ed. Eliot Weinberger; trans. Esther Allen, Suzanne Jill Levine, Eliot Weinberger, New York: Viking, 1999.

CAMPBELL John L., Ove K. PEDERSEN, “The Varieties of Capitalism and Hybrid Success,” Comparative Political Studies, vol. 40, no. 3, 2007, pp. 307–32.

**Comment by adam3smith** [comment]
Thanks -- I'll look at that and see what'd work.

**Comment by adam3smith** [comment]
Given https://forums.zotero.org/discussion/77029/location-of-the-date#latest I'm also wondering: Is this a correction to this style, or a customization requested by one of your users?

**Comment by ozhansaglik** [comment]
Hi Stephen, it is a correction but we realized this by the request of our user. 

https://www.uludag.edu.tr/dosyalar/sosyalbilimler/formlar/SBE%20TEZ%20YAZ.%20KIL.2018%20logoluENSOON.pdf You can see the examples in the page 16.

**Comment by ozhansaglik** [comment]
Dear Stephen,

Do you have a chance to review our issue?

**Comment by adam3smith** [comment]
@ozhansaglik sorry for the long wait -- May was travel month. Could you test that this works for you as desired?

**Comment by ozhansaglik** [comment]
Hi Stephen,

No apologies needed. I am sorry to can not reply you in time as you now the holiday of Eid.

It is working now as we requested, thank you so much.

**Comment by rmzelle** [comment]
Thanks!

**Comment by mtarakci** [comment]
This style is not used anymore. 
It would be better to delete it to avoid confusion.
Current citation styles in the Institute are APA, Chicago Manual and Isnad.
See page 5 of thesis manual: 
https://uludag.edu.tr/dosyalar/sosyalbilimler/2020%20KLAS%C3%96R/Tez%20Yazim%20Kilavuzu%2015.03.2021%20g%C3%BCncelleme/tez_yazim_kilavuzu_16052022_1_2_son.docx

**Pull request merged**
