### PR TITLE
Update APA styles for "event" macro

### PR DESCRIPTION
**Pull request by POBrien333**
fixes https://forums.zotero.org/discussion/comment/414271/#Comment_414271

I went through[ this list](https://github.com/citation-style-language/styles/pull/6161/files) and adapted all the styles that didn't have this conditional correct.

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks!

**Comment by Arundathi1** [comment]
Hello 

Hi, I was retrieving an appointment with this style but it doesn't appear correctly:

Formal education and elite sports in Argentine adolescents
Laino, Fernando Alberto ; Tunon, Ianina; Castro, Hernan ; Perez Rodriguez, Martin
Physical Education and Science, 2019, Vol.21 (3), p.e089-e089
 

It retrieves it like this:

Laíño, Tuñon, I., Castro, H., & Pérez Rodríguez, M. (2019). Formal education and elite sport in Argentine adolescents. Physical Education and Science, 21(3), e089–e089. https://doi.org/10.24215/23142561e089

The first and second authors do not recover the initials of their names.

Please if you could check.

Thanks.

**Comment by Arundathi1** [comment]
Hello

Hi, I was retrieving an appointment with this style (Apa 7) but it doesn't appear correctly:

Formal education and elite sports in Argentine adolescents
Laino, Fernando Alberto ; Tunon, Ianina; Castro, Hernan ; Perez Rodriguez, Martin
Physical Education and Science, 2019, Vol.21 (3), p.e089-e089

It retrieves it like this:

Laíño, Tuñon, I., Castro, H., & Pérez Rodríguez, M. (2019). Formal education and elite sport in Argentine adolescents. Physical Education and Science, 21(3), e089–e089. https://doi.org/10.24215/23142561e089

The first author do not recover the initials of their names.

Please if you could check.

Thanks.

**Comment by bwiernik** [comment]
This is from an Ex Libris catalog, yes?

The catalog is using a very outdated version of the citeproc-js citation processor. Whoever maintains the catalog needs to upgrade Ex Libris to a newer version that uses a current version of citeproc-js.

**Comment by Arundathi1** [comment]
Thank you very much for the reply. An additional question, how do I find out who is in charge of the citeproc-js catalog?

**Comment by bwiernik** [comment]
I maintain citeproc-js, but the thing that needs to be fixed is the version of Ex Libris. Contact whoever maintains the library catalog system

**Pull request merged**
