### PR TITLE
Update ferdinand-porsche-fern-fachhochschule.csl

### PR DESCRIPTION
**Pull request by christoph425**
Substantial changes to our Ferdinand Porsche Fernfachhochschule Style.

### CODE REVIEW

**Comment by adam3smith** [comment]
OK to change the style title, but let's leave the id as is, i.e. `ferdinand-porsche-fern-fachhochschule`. Are the new guidelines available online somewhere?

**Comment by christoph425** [comment]
Yes of course the ID is fine.
The Guidelines will be published on our website as soon as the new style is approved. (we can also publish it on GitHub as we did with the old guideline).
Attached you find the new Guidelines (do we need an English version as well?).

Von: Sebastian Karcher <notifications@github.com>
Gesendet: Dienstag, 20. Oktober 2020 14:32
An: citation-style-language/styles <styles@noreply.github.com>
Cc: JUNGBAUER Christoph <christoph.jungbauer@fernfh.ac.at>; Author <author@noreply.github.com>
Betreff: Re: [citation-style-language/styles] Update ferdinand-porsche-fern-fachhochschule.csl (#5073)


OK to change the style title, but let's leave the id as is, i.e. ferdinand-porsche-fern-fachhochschule. Are the new guidelines available online somewhere?

**Comment by adam3smith** [comment]
Yes, if you could put the new guidelines here, that'd be great. For the link, you could also use the URL where they will appear on your site if you know that already

**Comment by rmzelle** [comment]
> Attached you find the new Guidelines (do we need an English version as well?).

@christoph425, per @adam3smith, could you either attach the guidelines to a GitHub comment (you have to use the GitHub website to do this, as attachments to email replies don't work), or point us to the location on your website where these guidelines will be found?

**Comment by christoph425** [comment]
> > Attached you find the new Guidelines (do we need an English version as well?).
> 
> @christoph425, per @adam3smith, could you either attach the guidelines to a GitHub comment (you have to use the GitHub website to do this, as attachments to email replies don't work), or point us to the location on your website where these guidelines will be found?

The guideline is now linked to:
https://github.com/christoph425/ffh_csl_styles/blob/main/Richtlinien_wissenschaftliche_Arbeiten_WP.pdf

**Comment by adam3smith** [comment]
Thank you both!

**Pull request merged**
