### PR TITLE
Create jurnal-sains-farmasi-dan-klinis.csl

### PR DESCRIPTION
**Pull request by yoriyuliandra**
Hello. This is the first time submission/request to store the csl of our journal. Thanks

### CODE REVIEW

**Comment by yoriyuliandra** [comment]
> 😟 There are some issues with your submission.
> 
> 1 test failed
> The CSL Style Repository may not contain extra files (make sure styles have a ".csl" extension)
> 
> ```
> expected: []
>      got: ["/home/travis/build/citation-style-language/styles/dependent/jurnal-sains-farmasi-dan-klinis.cls"]
> 
> (compared using ==)
> ```
> 
> Please check the [test report](https://travis-ci.org/citation-style-language/styles/builds/626155823) for details.

**Comment by adam3smith** [comment]
Thanks! Just to clarify -- the style differs from the various Vancouver styles we already offer?

**Comment by yoriyuliandra** [comment]
> Thanks! Just to clarify -- the style differs from the various Vancouver styles we already offer?
> And it looks like this is based on an existing style -- was that just vancouver.csl or something else?

Hi, yes it's basically taken from Vancouver. But I modified a couple of things to suit our journal guidelines. So, this is something different. Thanks

**Comment by adam3smith** [comment]
Great, thanks!

**Comment by yoriyuliandra** [comment]
> [4]. Fenner M, Crosas M, Grethe JS, Kennedy D, Hermjakob H, Rocca-Serra P, et al. A data citation roadmap for scholarly data repositories. Scientific Data. 2019;6(1):28. https://doi.org/10.1038/s41597-019-0031-8

Looks good. But I was hoping the journal title in the citation number 4 to be abbreviated (Sci Data instead of Scientific Data). So, it would be: 

[4]. Fenner M, Crosas M, Grethe JS, Kennedy D, Hermjakob H, Rocca-Serra P, et al. A data citation roadmap for scholarly data repositories. Sci Data. 2019;6(1):28. https://doi.org/10.1038/s41597-019-0031-8

**Comment by adam3smith** [comment]
Yeah, the style does that, the abbreviation is just not in the metadata used for the test.

**Comment by yoriyuliandra** [comment]
Cool. Thanks

**Pull request merged**
