### PR TITLE
Update the-british-journal-of-psychiatry.csl

### PR DESCRIPTION
**Pull request by ludiafit**
-not bold volume
- period (.) after the journal name
- insert publisher place

### CODE REVIEW

**Comment by rmzelle** [comment]
What were you trying to do? This pull request currently renames the "The British Journal of Psychiatry" CSL style to "Makara Journal of Health Research", which can't be correct.

To submit a new style, see the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3a-submitting-a-new-style.

**Comment by makarask** [comment]
I apologize for any mistake..  I don't know what mistake i have made..This is the first time i use Git Hub and I am just trying to change an existing style, namely The British Journal of Psychiatry.. i have followed the instruction here: https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style

Do yo have any recommendation what should i do?  and please let me know what mistake that i made

Thank you,
Thank you,

**Comment by rmzelle** [comment]
Well, you can see the changes you were proposing at https://github.com/citation-style-language/styles/pull/2204/files. If you want to make corrections to the existing "The British Journal of Psychiatry", the style's title, ID, "self" link, ISSNs, etc., shouldn't change.

**Comment by ludiafit** [comment]
Thank you.. i will learn first..

**Pull request closed without merging**
