### PR TITLE
Switch from dx.doi.org to doi.org per official Crossref guidelines

### PR DESCRIPTION
**Pull request by rmzelle**
See https://github.com/citation-style-language/styles/issues/2197 for
discussion

### CODE REVIEW

**Comment by rmzelle** [comment]
@adam3smith, if you have time, feel free to give it a quick lookover. It's all a find-replace from "dx.doi.org" to "doi.org", with the exception of water-alternatives.csl.

**Comment by rmzelle** [comment]
Qui tacet consentire videtur!

**Comment by adam3smith** [comment]
I only taceted for 13 hs ;), but this looks good, thanks!

**Comment by rmzelle** [comment]
Yeah, I know, but it's a rather straightforward change and you said you were busy anyway.

**Pull request merged**
