### PR TITLE
Create FIPS-Publikationsdatenbank

### PR DESCRIPTION
**Pull request by franklin66**
Dieser Stil wird für Einträge in die Publikationsdatenbank der FH Vorarlberg genutzt.

### CODE REVIEW

**Comment by rmzelle** [comment]
Is the purpose of this style different from https://github.com/citation-style-language/styles/blob/master/fachhochschule-vorarlberg.csl ?

**Comment by franklin66** [comment]
Hi Rintze,

> Is the purpose of this style different....
> 

Yes, definitely. The style "fachhochschule-vorarlberg" is the style that students use to write their publications etc. The style "FIPS-Publikationsdatenbank" is used by our new publication database system to generate automated lists etc. Our publication database has to be maintained by all the lecturers and also uses the zotero-api to do its work. But as I am not the programmer of this system my knowledge about it is limited. If you have further technical questions concerning the system please contact Claudia Heitz via ch@fhv.at

However, we really need these two styles to be separated, not only for technical reasons. They are quite similar now, but they might evolve into different directions.


Kind Regards,
Frank

P.S.: We are also planning to develop a footnote-version of the "fachhochschule-vorarlberg"-style but this might take some time.


- - - -
Dipl.-Päd. Mag. (FH) Frank Weber
 Rectorate - Learning Support 

University of Applied Sciences Vorarlberg
 Hochschulstraße 1
6850 Dornbirn, Austria
GmbH, FN 165415h, LG Feldkirch

Phone: +43 (0) 5572 792 1009
Fax: +43 (0) 5572 792 9506

Email: frank.weber@fhv.at
 Web: www.fhv.at/learningsupport
Blog: http://learningsupport.at
Twitter: http://twitter.com/xifrank
XING: https://xing.com/profile/Frank_Weber23

**Comment by rmzelle** [comment]
> The style "FIPS-Publikationsdatenbank" is used by our new publication database system to generate automated lists etc.

What CSL-supporting software are you using?

Since our styles are pushed out to hundreds of thousands of users, we're always a hesitant to accept styles with a very limited audience (in your case, an audience of one: the database system), so it would be better to self-host it (although some CSL software only support styles that are hosted in our repository).

**Comment by adam3smith** [comment]
The ability to use styles hosted somewhere other than on our repo is really something that Zotero needs to add to their API (and they've said they will). @fcheslack do you have any sense of an ETA for that?

**Comment by adam3smith** [comment]
@rmzelle as per the comment:
> Our publication database has to be maintained by all the lecturers and also uses the zotero-api to do its work.

**Comment by franklin66** [comment]
>>What CSL-supporting software are you using?
Frankly, I don't know. But I do know that we need this style to be online in the repository for technical reasons. I'll inform the programmer about this conversation, hoping that she'll have the answers...

**Comment by rmzelle** [comment]
@franklin66, I missed that you wrote that you're using the Zotero API. That's the part that should support styles not hosted in our repository.

**Comment by claudia-heitz** [comment]
Our publications are stored in a Zotero online library and we use the Zotero Web Api (https://www.zotero.org/support/dev/web_api/v2/start) to generate the bibliography. The API requires a style located in the Zotero Style Repository (style on https://www.zotero.org/styles) and therefore we need the fips-style to be uploaded. Or is there a way to use a style located somewhere else?

**Comment by rmzelle** [comment]
@claudia-heitz, currently the Zotero API only works with styles in our repo. By the way, are you in a hurry, or will it be a while before your system goes live?

@fcheslack, I'd be open to some temporary solution, such as maintaining a second repository for this type of styles, if that would things easier for you. But we'd still very much like to see support in the Zotero API for styles hosted at arbitrary locations. We've already had to turn down several styles that were submitted with the sole purpose of being used with the Zotero API, which is a pity.

**Comment by claudia-heitz** [comment]
Our system is already online - at the moment we use another style. So, it would be great to have our fips-style in the repository soon :-)

**Comment by rmzelle** [comment]
@dstillman, any ETA on adding support for custom style URIs in the Zotero API?

**Comment by fcheslack** [comment]
Sorry I missed this, I had notifications off for some reason. Other repository shouldn't be necessary. I'll try to get something done in the next couple weeks. I was putting off some other work on it until node 0.12 anyway.

**Comment by rmzelle** [comment]
Awesome.

@claudia-heitz, @franklin66, if you can manage with your current style for the next few weeks, I rather not accept this style.

**Comment by adam3smith** [comment]
we'll leave the ticket open as a reminder.

**Comment by rmzelle** [comment]
@fcheslack, will you open a ticket at (presumably) https://github.com/zotero/citeproc-node?

**Comment by fcheslack** [comment]
https://github.com/zotero/citeproc-node/issues/18

**Comment by franklin66** [comment]
@rmzelle , sorry I missed a part of this conversation. It would be great to have a solution in a couple of weeks!

**Comment by rmzelle** [comment]
This now works: https://api.zotero.org/users/475425/items/X42A7DEE?format=bib&style=https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

**Pull request closed without merging**
