### PR TITLE
Update manchester

### PR DESCRIPTION
**Pull request by icornelius**
rename `manchester-university-press.csl` to distinguish author-date and note-bib variants of this citation style. 
Rebuild the note-bib style from a new template to improve accuracy of the output.
Create the author-date style using note-bib as template.

### CODE REVIEW

**Comment by icornelius** [comment]
The file that I update and rename is referenced as template by another csl file in the repo. The name-change removes ambiguity between note-and-bibliography and author-date variants of Manchester University Press style. I'm not sure what to do about the error. Help, please?

**Comment by adam3smith** [comment]
This looks good. I am seeing initials, not full names, for authors in the style guide though -- any reason you're using full names?

**Comment by icornelius** [comment]
I wondered about that. The style guide gives initials, as you note, but does not stipulate usage. The single reference I find is in section 5.4.2 (first bullet point), stating that in the bibliography "surname should precede first name or initials". I have checked three MUP books published in 2020: two use author forenames, one initials. I suppose we could ask an editor at MUP. Let me see if I can get a response.

**Comment by icornelius** [comment]
Confirming that the style should initialize given names.

**Comment by adam3smith** [comment]
@rmzelle good to go from my end, but want to make sure you're OK with the IDs & titles.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
