### PR TITLE
Create ulua-revista-de-historia-sociedad-y-cultura.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/89581/style-request-ulua-revista-de-historia-sociedad-y-cultura#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
@POBrien333 -- I didn't find anything on the et-al rules: but I did see an item with for authors listed in the bibliography, so I bumped the numbers higher. Did you see any rule or pattern about this?

I also turned et al italic in text as I saw that (Ibarra et al. 2014 here: https://ulua.uv.mx/index.php/ulua/article/view/2685/4547 )

**Comment by rmzelle** [comment]
(looks good to me otherwise)

**Comment by adam3smith** [comment]
Thanks!

**Comment by POBrien333** [comment]
Thank you for making those amendments.

**Pull request merged**
