### PR TITLE
Thieme dependents

### PR DESCRIPTION
**Pull request by rmzelle**
Via https://github.com/citation-style-language/journals/pull/39

### CODE REVIEW

**Comment by rmzelle** [comment]
(I just realized I didn't set up redirects in renamed-styles.json for the independent styles we're deleting that have different names in their dependent form; we could also change the metadata to keep the journal titles and style IDs the same)

**Comment by adam3smith** [comment]
I did a quick check and the International Journal of Sports Medicine publishes in English with English abbreviations (i.e. ed instead of Hrsg.) and Röfo uses et al for >  authors, as does DMW. If we're in a rush here, I'd leave these independent and check back with @juliarojahn

**Comment by rmzelle** [comment]
Sure. I can put them on the skip list for now and update the PR in the styles repo.

**Comment by rmzelle** [comment]
> I'd leave these independent

@adam3smith, I updated both the "journals" and "styles" PRs to do just that. Should be good to merge.

**Comment by juliarojahn** [comment]
Please include the Journal DMW in the style - it should use the same style, and the colleagues would be very happy to be included!

The journals with english citations (International Journal of Sports Medicine, RöFo etc.) I can tackle afterwards.
Thanks,
Julia

**Comment by adam3smith** [comment]
OK, we'll fix this so it includes DMW and then merge it over the weekend. Sorry for the delay

**Comment by rmzelle** [comment]
Hmz, looks like I should have done DMW instead of the European Journal of Ultrasound.

**Comment by rmzelle** [comment]
> OK, we'll fix this so it includes DMW and then merge it over the weekend.

@adam3smith, just made this change. Feel free to merge (and the journals PR mentioned at the top of this PR as well).

**Comment by adam3smith** [comment]
great, thanks!

**Pull request merged**
