### PR TITLE
Create beilstein-open-access-journals.csl

### PR DESCRIPTION
**Pull request by Beilstein**
This is the citation style for the Beilstein Open Access Journals

https://www.beilstein-institut.de/en/journals

The style is based on the citation style "american-chemical-society.csl" with minor formatting changes regarding the in-text citations.

### CODE REVIEW

**Comment by adam3smith** [comment]
Let us know if you need help with the build issues.
Also, do you have a spreadsheet of all journals, ideally with ISSN, this style applies to?

**Comment by adam3smith** [comment]
@Beilstein did you see my question above? Any chance we can get a spreadsheet with the journals this applies to?

**Comment by Beilstein** [comment]
@adam3smith Sorry we answered your email but got the address wrong. Here's the spreadsheet with our two journals:
Beilstein Journal of Organic Chemistry - ISSN 1860-5397
Beilstein Journal of Nanotechnology - ISSN 2190-4286

[beilstein-journals.xlsx](https://github.com/citation-style-language/styles/files/4312754/beilstein-journals.xlsx)

**Comment by rmzelle** [comment]
@Beilstein, thanks!

Since there are only two journals I just created CSL styles for both instead of having a general Beilstein CSL style as well.

**Pull request merged**
