### PR TITLE
Gaya UKM

### PR DESCRIPTION
**Pull request by fareedsairi**
A modified citation style for Gaya UKM from Modern Humanities Research Association 3rd edition (Rintze Zelle).
-Term such as editor, composer, months, translator and etc was translated to Bahasa Melayu to suit Universiti Kebangsaan Malaysia citation style known as Gaya UKM
-Most citation style for journal articles, books, chapter in books, website was changed according to Gaya UKM
-Citation for legal case, art and social science reference may not be formated yet according to Gaya UKM
-For Gaya UKM in English, you can just remove the 'term' in local to remove translation using visual editor

### CODE REVIEW

**Comment by rmzelle** [comment]
@fareedsairi, thanks. Is this style based on the "Panduan Penulisan Thesis Gaya UKM / UKM Thesis Writing Guideline" style guide at http://www.ukm.my/pusatsiswazah/templat-gayaukm/ ?

And can you explain what "Gaya" stands for? ("BM" stands for Malay/Bahasa Melayu, I assume)

**Comment by fareedsairi** [comment]
Hello @rmzelle, "Gaya UKM" can be translated to UKM style (Universiti Kebangsaan Malaysia Style). The style provided by  http://www.ukm.my/pusatsiswazah/templat-gayaukm/ is still inaccurate. Thus, I'm trying to improve and add the style into the repository so that others can help edit and make the style complete. We had some test run and most of it was acceptable. The only problem is I'm noob at this coding and github things. So I may had made mistakes somewhere.

**Comment by fareedsairi** [comment]
and yes, BM is Bahasa Melayu

**Comment by rmzelle** [comment]
Ah, so "Gaya" just means "style"?

So this citation style will be used both in English and Malay? It's possible to use a single CSL style in multiple languages by removing the `default-locale="en-US"`, and specifying the desired language when you use the style. (CSL styles rely on CSL locale files for standard translations, but it looks like we don't have such a CSL locale file for Malay yet: see https://github.com/citation-style-language/locales and http://docs.citationstyles.org/en/stable/translating-locale-files.html. Creating one would make it easier to write Malay CSL styles.)

**Comment by fareedsairi** [comment]
Yap. I think the closes would be in Indonesian language (id) that I can find in locales. I may be able to make a new local for bahasa but I'm not sure how can I integrate it into the codes. I'm still a beginner in this and had made the style using visual editor instead writing it from scratch. So, does the submitted citation style is acceptable to be listed in Mendeley? I will try to improve as best as I can

**Comment by rmzelle** [comment]
> So, does the submitted citation style is acceptable to be listed in Mendeley?

I made some changes, including to the style title. Let me know if the style title looks acceptable to you and I can merge this.

If you're interested in creating a Malay CSL locale, you can follow the instructions at http://docs.citationstyles.org/en/stable/translating-locale-files.html (it looks like the locale code for Standard Malay is "zsm", so you would create locales-zsm.xml). But this is optional and not required for us to accept this style.

**Comment by fareedsairi** [comment]
Dear @rmzelle, I'm good with the changes. I will need sometime to validate the style or any new changes in the future. If there is, i will directly add to github. For the Malay CSL, I will need some time. for now, I'm ok for the merge. Thanks a alot :)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
