### PR TITLE
Create UFR-Etudes_Psychanalytiques

### PR DESCRIPTION
**Pull request by hsdjhs**
Fichier de style semblable au Tapuscrit de l'EHESS mais avec la possibilité de mettre la date de 1ere publication dans les notes et le nom des traducteurs des oeuvres en français (très utile pour les oeuvres de Freud notamment, ainsi que celles de Lacan et Foucault).

### CODE REVIEW

**Comment by rmzelle** [comment]
@hsdjhs, my apologies for not reviewing this style until now.

Does the "Études Psychanalytiques" department have a style guide that describes this citation format? Is it available online?

**Comment by rmzelle** [comment]
@hsdjhs, could you answer my question above?

**Comment by hsdjhs** [comment]
Hello Rintze,

Sorry for my late reply and happy new year! There was a style guide on the
website of my department when I wrote the Zotero style (
http://www.ep.univ-paris-diderot.fr/lmd/doctorat/) but both the website and
the responsible of the Doctoral School have recently changed, so nothing is
available on Internet for now. I sent an email to the responsible of the
Doctoral School as soon as I received your email to know if she could put
the style guide again on the website but as she is on holiday, I have not
received any news from her... I will keep you in touch as soon as she get
back to me (but this can take a while as she is generally overwhelmed...).

All the best,

Adrien

Le sam. 5 janv. 2019 à 20:56, Rintze M. Zelle <notifications@github.com> a
écrit :

**Comment by rmzelle** [comment]
@hsdjhs, great, thanks. If you still have a copy of the style guide, and you're allowed to put it online, you can also just add it here as an attachment. It would be better to have a link on the university website, though.

I renamed the style to fit with our guidelines.

**Comment by hsdjhs** [comment]
Hello Rintze!

Thank your for your email. I will wait for the updated style guide before
sending it to you. For the renaming of the zotero style, as "etudes
psychanalytiques" is not anymore an ufr but a department, is it possible to
name it universite-paris-diderot-departement-detudes-psychanalytiques ?

All the best,

Adrien

**Comment by rmzelle** [comment]
> I will wait for the updated style guide before sending it to you. For the renaming of the zotero style, as "etudes psychanalytiques" is not anymore an ufr but a department, is it possible to name it universite-paris-diderot-departement-detudes-psychanalytiques ?

Thanks for the correction. I'll make that change when the style guide becomes available.

**Comment by hsdjhs** [comment]
Hello Rintze,

Finally, the "department d'études psychanalytiques" based himself on the
guidelines of the university (
https://bibliotheque.univ-paris-diderot.fr/article/th%C3%A8ses-doctorants),
which links to
https://bibliotheque.univ-paris-diderot.fr/sites/default/files/fichiers/guide_doct_ministere_education.pdf
for the bibliographics norms. The "department d'études psychanalytiques"
asks us aditionnaly to put the first date of publication, which I added on
the "extra" field on Zotero.

Sorry for this delayed answer,

All the best,

Adrien Cascarino

Le jeu. 10 janv. 2019 à 21:21, Rintze M. Zelle <notifications@github.com> a
écrit :

**Comment by rmzelle** [comment]
Thanks! So the style is primarily based on the style guide "Guide pour la rédaction et la présentation des thèses à l'usage des doctorants" by the Ministère de l’Education nationale and the Ministère de la recherche? If so, it might be better to name the style after this guide, especially since it looks like it's also used by other French universities and departments (see e.g. https://www.google.com/search?client=firefox-b-1-d&q=GUIDE+POUR+LA+R%C3%89DACTION+ET+LA+PR%C3%89SENTATION+DES+TH%C3%88SESA+L%E2%80%99USAGE+DES+DOCTORANTS)

> The "department d'études psychanalytiques" asks us aditionnaly to put the first date of publication, which I added on the "extra" field on Zotero.

@hsdjhs, is there already a university website that uses "department d'études psychanalytiques"? I still see "UFR" at http://www.ep.univ-paris-diderot.fr/.

@adam3smith, I guess it would be better to use "original-date" than extra for this?

**Comment by hsdjhs** [comment]
Hello Rintze,

You are right, it may be better to rename the style after this guide. Maybe
"Guide pour la rédaction et la présentation des thèses à l'usage des
doctorants français", if it is not too long ?

For the "département d'études psychanalytiques", it is mentioned in the
webiste of Universit Paris Diderot (
https://universite.univ-paris-diderot.fr/structures/ufr-institut-humanites-sciences-et-societes-ihss)
: if was an UFR and now it is a department under the UFR IHSS.

I was not able to find the field "original-date" in Zotero (I have version
5.0.60) : do you where it is ? Because if it already exists, it would
indeed be much easier :).

Le ven. 15 févr. 2019 à 04:46, Rintze M. Zelle <notifications@github.com> a
écrit :

**Comment by rmzelle** [comment]
>  You are right, it may be better to rename the style after this guide. Maybe "Guide pour la rédaction et la présentation des thèses à l'usage des doctorants français", if it is not too long ? For the "département d'études psychanalytiques", it is mentioned in the webiste of Universit Paris Diderot ( https://universite.univ-paris-diderot.fr/structures/ufr-institut-humanites-sciences-et-societes-ihss) : if was an UFR and now it is a department under the UFR IHSS.

Yes, we would probably name the style "Guide pour la rédaction et la présentation des thèses à l'usage des doctorants (French)", then (we always put the language of non-English fixed-locale styles in the style title in English). Would that suffice by itself, or would you still want a so-called dependent CSL style named "Université Paris Diderot - département d’Études Psychanalytiques (French)" that links to the former one?

> I was not able to find the field "original-date" in Zotero (I have version 5.0.60) : do you where it is ? Because if it already exists, it would indeed be much easier :).

There is (currently) not a dedicated field for "original-date" in Zotero, but it's possible to use a special syntax in the Extra field, e.g. `Original Date: 1886-04-01`. That's much preferred over just using the entire contents of Extra. See https://www.zotero.org/support/kb/item_types_and_fields#citeable_fields_not_included_in_zotero for details.

**Comment by hsdjhs** [comment]
> You are right, it may be better to rename the style after this guide.
> Maybe "Guide pour la rédaction et la présentation des thèses à l'usage des
> doctorants français", if it is not too long ? For the "département d'études
> psychanalytiques", it is mentioned in the webiste of Universit Paris
> Diderot (
> https://universite.univ-paris-diderot.fr/structures/ufr-institut-humanites-sciences-et-societes-ihss)
> : if was an UFR and now it is a department under the UFR IHSS.
>
> Yes, we would probably name the style "Guide pour la rédaction et la
> présentation des thèses à l'usage des doctorants (French)", then (we always
> put the language of non-English fixed-locale styles in the style title in
> English). Would that suffice by itself, or would you still want a so-called
> dependent CSL style named "Université Paris Diderot - département d’Études
> Psychanalytiques (French)" that links to the former one?
>
- Hello Rintze, I think it would be great to have also a dependant CSL
style named "Université Paris Diderot - département d’Études
Psychanalytiques (French)", it will help the PhD students of my department
to find it (they may not look for the general style...).


> I was not able to find the field "original-date" in Zotero (I have version
> 5.0.60) : do you where it is ? Because if it already exists, it would
> indeed be much easier :).
>
> There is (currently) not a dedicated field for "original-date" in Zotero,
> but it's possible to use a special syntax in the Extra field, e.g. Original
> Date: 1886-04-01. That's much preferred over just using the entire
> contents of Extra. See
> https://www.zotero.org/support/kb/item_types_and_fields#citeable_fields_not_included_in_zotero
> for details.
>

- Ok. I am not very familiar with coding directly in CSL, I mostly used the
visual editor (http://editor.citationstyles.org/visualEditor/)... That's
why I used the whole extra field instead of only a part. Also, generally,
only the year of original date is needed.

**Comment by rmzelle** [comment]
Thanks! I added "Université Paris Diderot - Département d'études psychanalytiques (French)" and "Guide pour la rédaction et la présentation des thèses à l'usage des doctorants (French)" styles.

**Comment by hsdjhs** [comment]
Thank you very much !

Le lun. 18 févr. 2019 à 18:23, Rintze M. Zelle <notifications@github.com> a
écrit :

**Pull request merged**
