### PR TITLE
Create geochemical-perspectives-letters.csl

### PR DESCRIPTION
**Pull request by xeones**
Citation style for Geochemical Perspectives Letters based on Information for Authors document; probably applicable to Geochemical Perspectives also.

### CODE REVIEW

**Comment by rmzelle** [comment]
Great, thanks.

If you can confirm that Geochemical Perspectives uses the same citation format, we can create a simple "dependent" CSL style for it that points to this one. (similar to https://github.com/citation-style-language/styles/blob/master/dependent/nature-biotechnology.csl)

**Comment by updownleft** [comment]
@rmzelle: according to the guide for authors (http://www.geochemicalperspectivesletters.org/information-for-authors), the citation requirements for Geochemical Perspectives (ISSN 2223-7755 | e-ISSN 2224-2759) appear to be the same as for Geochemical Perspectives Letters.

**Comment by rmzelle** [comment]
@updownleft, I noticed some slight differences between the two style guides, but that may be unintentional. E.g.:

> Strunk Jr., W., White, E.B. (1979) The Elements of Style. Third Edition, Macmillan, New York, 100 pp.
http://www.geochemicalperspectives.org/guide-for-authors

> Strunk Jr., W., White, E.B. (1979) The Elements of Style. Third Edition, Macmillan, New York.
http://www.geochemicalperspectivesletters.org/information-for-authors#References

It's probably fine to assume they use the same style. Could either one of you prepare a dependent CSL style for it?

**Comment by updownleft** [comment]
@rmzelle, yes, can do.

**Pull request merged**
