### PR TITLE
Update united-states-international-trade-commission.csl

### PR DESCRIPTION
**Pull request by USITC-Zotero**
Hello,

When possible could you please review and approve the updated style file? We resolved the following list of issues.

1) News article section titles appeared in Footnotes
2) Abstract information sometimes blocked short-titles
3) Added legal citation information

Thank you,
USITC Zotero team

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks!

**Comment by USITC-Zotero** [comment]
@bwiernik Hi Brenton, apologies but it doesn't appear the merge was successful. How can we resolve the issue?

image

**Comment by adam3smith** [comment]
The merge was successful. Zotero has an automated process to update their repository from ours that appears broken/stuck. @dstillman could you check on this?

**Comment by dstillman** [comment]
It was the GitHub git:// → https:// change. Fixed now. Thanks for letting us know.

**Comment by USITC-Zotero** [comment]
@dstillman @adam3smith @bwiernik Hi all, I was able to verify that the merge was successful. Thank you for investigating the matter!

image

**Pull request merged**
