### PR TITLE
Create jmr.csl

### PR DESCRIPTION
**Pull request by svishwan**

### CODE REVIEW

**Comment by adam3smith** [comment]
let us know if you need help.

**Comment by svishwan** [comment]
Thank you so much, I will.

Please pardon my typos,
with best regards,
Suresh Vishwanath

**Comment by rmzelle** [comment]
You can update this pull request via the edit/pencil icon at https://github.com/svishwan/styles/blob/patch-1/jmr.csl.

Our automated tests fail because the style currently doesn't use the "citation-locator" macro, and we require that styles don't contain any unused macros. Please also look at our https://github.com/citation-style-language/styles/wiki/Style-Requirements, in particular the style naming (I currently don't know what JMR stands for).

**Comment by adam3smith** [comment]
most commonly, JMR refers to the Journal of Materials Research, which we just added in https://github.com/citation-style-language/styles/pull/2141 so closing this. If that's not it @svishwan please comment here and we can reopen the pull request.

**Pull request closed without merging**
