### PR TITLE
Updates Elsevier dependent styles.

### PR DESCRIPTION
**Pull request by cpina**
Updates Elsevier styles, keeping the _skip.txt that was previously used.
I'll update the elsevier/_journals.tab if this works.
Having problems running rake locally, I'll give it one attempt to see if it works or I'll fix it properly later on if I need to debug problems.

### CODE REVIEW

**Comment by adam3smith** [comment]
This is great, thanks!

**Comment by adam3smith** [comment]
@cpina could you still update _journals.tab, please?

**Comment by cpina** [comment]
Yes, I can, I'll find some time next week(s)

**Comment by POBrien333** [comment]
Hey @cpina 
Just checking in if this was completed as I still have it on my log for citation style requests (https://docs.google.com/spreadsheets/d/1zc3Sl4JU7Ltu0Q55-OB0QYCJbYiguVXwpc_BzBLLZcA/edit#gid=128551622)

**Pull request merged**
