### PR TITLE
Coventry - bibliography order

### PR DESCRIPTION
**Pull request by tipichris**
Tweak order for bibliography

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- the commit message had two other issues mentioned (disambiguation/full names). I didn't check, but I assume those were already added in an earlier PR.

**Comment by tipichris** [comment]
Yes. Sorry, Git confuses me! Perhaps I should have started with rebase upstream/master instead of merge upstream/master?
It looks like  438b0e5 and f3c11be in my branch somehow became 9c1d9a4 in master, so they got pushed again

**Comment by adam3smith** [comment]
If you do `git pull upstream master` (which is the same as `git fetch` followed by `git merge`) before adding any changes to the repository that really should work. I'm guessing there was an automerge that made it to the pull request. 
What I think may be going on is that you keep working from the same branch. The standard procedure would be to have a separate branch for every PR and then delete it once the PR gets merged.

**Comment by rmzelle** [comment]
> The standard procedure would be to have a separate branch for every PR and then delete it once the PR gets merged.

@tipichris, especially if you plan to commit a pull request for just a single style, it's usually just as easy to just have GitHub take care of things. If you follow our instructions on updating existing styles at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style, and edit the version in our official repository, GitHub will automatically recognize that you don't have the rights to commit directly, and create a new up-to-date branch in your fork. That way you don't ever have to bother to keep the "master" branch in your fork up-to-date.

**Comment by rmzelle** [comment]
@adam3smith, it doesn't really matter here, but I wonder if maybe GitHub's new rebase option would have worked here: https://github.com/blog/2243-rebase-and-merge-pull-requests

**Comment by adam3smith** [comment]
Great that that's possible -- but my understanding would be that makes not difference at all here (since the end result is a single commit either way), but could help us in situations where previously merging wasn't possible?

**Comment by rmzelle** [comment]
@adam3smith, yeah, I'm not really sure when you'd want to rebase on GitHub.

**Pull request merged**
