### PR TITLE
Update bursa-uludag-universitesi-saglik-bilimleri-enstitusu.csl

### PR DESCRIPTION
**Pull request by ozhansaglik**
Bursa Uludag University Health Sciences Institute has changed the citation style so in this pull request these changes are reflected.

### CODE REVIEW

**Comment by adam3smith** [comment]
Something went wrong here: your second commit reverted all the changes of your first one, so there's not actually anything to merge.

**Comment by ozhansaglik** [comment]
Hi Adam sorry, I have just checked the file and edit it. Best wishes.

**Comment by ozhansaglik** [comment]
Hi folks, do you have a time merge this pull request? 
Best wishes
Özhan

**Comment by adam3smith** [comment]
Sorry, there's still no meaningful change in the style (you can see the diff under "Files changed" above

**Comment by ozhansaglik** [comment]
Hi Stephen, sorry. I checked 2 times now and attached the new version.
[Codes.txt](https://github.com/citation-style-language/styles/files/5348103/Codes.txt)

**Comment by ozhansaglik** [comment]
Hi Stephen, how does it look now?
[Codes.txt](https://github.com/citation-style-language/styles/files/5348141/Codes.txt)

**Comment by adam3smith** [comment]
(There's no Stephen here...)
I didn't look in detail, but this looks like you just copied APA 6 -- are there any meaningful differences to the existing style?

**Comment by ozhansaglik** [comment]
Sorry Sebastian.

The Institute changed a bit from APA 6. Here is an example.
[Saglik_Bilimleri_Deneme.docx](https://github.com/citation-style-language/styles/files/5349067/Saglik_Bilimleri_Deneme.docx)

**Comment by ozhansaglik** [comment]
Dear Adam, I hope you are fine. Did you review the issue? We should update our citation style.

**Comment by rmzelle** [comment]
> Dear Adam, I hope you are fine. Did you review the issue? We should update our citation style.

I just merged this pull request. @adam3smith is right that if you're using standard 6th edition APA, it would be better to turn this citation style into a dependent of https://github.com/citation-style-language/styles/blob/master/apa-6th-edition.csl (for an example of an dependent CSL style, see https://github.com/citation-style-language/styles/blob/master/dependent/nature-biotechnology.csl).

**Comment by ozhansaglik** [comment]
Dear Rintze,

Thank you for your contribution.

**Pull request merged**
