### PR TITLE
Create mui-vancouver.csl

### PR DESCRIPTION
**Pull request by ueen**
based on Vancouver with modifications based on the guidelines for the University of Medicine Innsbruck

https://www.i-med.ac.at/studium/docs/Richtlinie-zur-Erstellung-einer-Diplomarbeit-und-Masterarbeit_19-12-2018.pdf

### CODE REVIEW

**Comment by ueen** [comment]
thier seems to be an issue with the date somehow, in zoterro this is how it looks (and should) thier should be dots

[zuletzt aufgerufen am 27.4.2019]

Bildschirmfoto 2023-03-29 um 21 06 37

**Comment by ueen** [comment]
Sooo sorry for all the commits, i have some trouble with different date renderings inside zotero and the github bot examples, the but misses the dots `[zuletzt aufgerufen am 27042019]`

this is how it looks in zotero

Bildschirmfoto 2023-03-29 um 21 24 20

**Comment by adam3smith** [comment]
Sorry, you can ignore that. The processor used by the preview bot doesn't understand `delimiter` set on cs:date (which is new in CSL 1.0.2)

**Comment by ueen** [comment]
> Sorry, you can ignore that. The processor used by the preview bot doesn't understand `delimiter` set on cs:date (which is new in CSL 1.0.2)

ahh i see, i fiddled around for about an hour to get it right - then this should be ready for merging from my side :)

**Comment by ueen** [comment]
Ok sorry for that, now everything should be ready to merch, thanks so much in advance!

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
