### PR TITLE
Update mohr-siebeck-recht.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/90740/mohr-siebeck-style-trennung-der-zitate#latest

### CODE REVIEW

**Comment by rmzelle** [comment]
This change seems rather poorly supported. The old mohr.de domain seems to be dead, but I found some possible author guidelines at https://www.mohrsiebeck.com/service/fuer-autoren. Could you take a look if this is documented anywhere?

**Comment by POBrien333** [comment]
I had looked through those documents already, but another user added their voice to this on the forum thread now.

**Comment by rmzelle** [comment]
> I had looked through those documents already

Did you identify one of that could be a good replacement for "http://www.mohr.de/fileadmin/user_upload/Hinweise_Autoren_PDF/Merkblaetter/merkjura2006.pdf"?

**Comment by POBrien333** [comment]
Let me get in touch with them.

**Comment by adam3smith** [comment]
I say we just take this based on the comments in the tread.

**Pull request merged**
