### PR TITLE
[Don't Merge] Testing new bots

### PR DESCRIPTION
**Pull request by adam3smith**

### CODE REVIEW

**Comment by adam3smith** [comment]
@retorquere not quite there yet -- see above, somehow Sheldon is failing to load

**Comment by retorquere** [comment]
I'd need to see the heroku log to see whether something gets delivered. Another thing that would be useful is if Sheldon-gem can be ran with the --verbose flag.

**Comment by retorquere** [comment]
I can open my own PR to test the client side. But someone would either have to copy out the heroku logs to here or I'd need to have temporary access to Sheldon.

Another option is that I set up a heroku-18 stack and that I transfer it when I have it working, but someone would have to set secret vars to get it to work. I also don't know if I can migrate to the existing name.

**Comment by adam3smith** [comment]
Happy to give you access. What email do you use?

**Comment by retorquere** [comment]
It may not be required, see the new PR (sloppiness on my part, really sorry) -- but otherwise, emiliano.heyns@iris-advies.com

**Comment by adam3smith** [comment]
added you for good measure. Feel free to also update the stack

**Pull request closed without merging**
