### PR TITLE
Create AFTE CSE.csl

### PR DESCRIPTION
**Pull request by PavelGiv**

### CODE REVIEW

**Comment by rmzelle** [comment]
@PavelGiv, thanks! https://afte.org/afte-journal/information-for-authors says:

> The AFTE Journal follows Scientific Style and Format: The Council of Science Editors (CSE) Manual for Authors, Editors, and Publishers, 8th Ed.

Did https://www.zotero.org/styles?q=id%3Acouncil-of-science-editors not give the right output?

**Comment by PavelGiv** [comment]
Hello!
The original CSE style uses different methods of inline citation. So, I
couldn't use dependent styles and had  to modifiy the citation section.

Sincerely yours,
Pavel

пн, 26 апр. 2021 г., 06:44 Rintze M. Zelle ***@***.***>:

**Comment by PavelGiv** [comment]
Hello!
The original CSE style uses different methods of citation formatting in the
text. So, I couldn't use dependent styles and had  to modify the citation
section.

Sincerely yours,
Pavel

пн, 26 апр. 2021 г. в 06:44, Rintze M. Zelle ***@***.***>:

**Comment by adam3smith** [comment]
@rmzelle we could take this as AFTE Journal or as CSE brackets, any preferences?
(I confirmed the journal specifically asks for numbers in brackets in regular text; CSE is typically with superscript numbers)

**Comment by PavelGiv** [comment]
Hi!
Would it be possible to have the style-name including "AFTE Journal"?
Something like "AFTE Journal based on CSE"

Pavel

вс, 16 мая 2021 г. в 22:02, Sebastian Karcher ***@***.***>:

**Comment by PavelGiv** [comment]
Hi!
@rmzelle <https://github.com/rmzelle> , @adam42smith
<https://github.com/adam3smith>
I would like to know if any decision on my pull request for
afte-journal-cse.csl  has been made?

Sincerely yours,
Pavel

пн, 17 мая 2021 г. в 20:25, Pavel Giverts ***@***.***>:

**Comment by adam3smith** [comment]
@rmzelle see my naming question above? (Obviously we'd add an AFTE dependent style if we go with the CSE option)

**Comment by rmzelle** [comment]
@adam3smith, @PavelGiv, sorry, didn't see this before. Let's go with a CSE variant as independent and AFTE style as dependent.

**Comment by PavelGiv** [comment]
@rmzelle <https://github.com/rmzelle>, @adam3smith
<https://github.com/adam3smith>.
Thank you for making the decision!
What is the best way to proceed? Will you make changes in my pull request
to convert it to the independent CSE variant? Or will I make these changes?
Or will it be better to close this request and make a new one for the CSE
variant?

After the CSE variant is accepted I'll make a pull request to
dependent AFTE style.

Best regards,
Pavel


чт, 1 июл. 2021 г. в 06:13, Rintze M. Zelle, PhD ***@***.***>:

**Comment by adam3smith** [comment]
Superseded by https://github.com/citation-style-language/styles/commit/f73d62f05be8d237e9bd12cdb8a5a6ed1c8b56d5

**Comment by adam3smith** [comment]
Thanks! The style is now available.

**Pull request closed without merging**
