### PR TITLE
vilnius-gediminas-technical-university.csl

### PR DESCRIPTION
**Pull request by VGTUPress**

### CODE REVIEW

**Comment by rmzelle** [comment]
Is this citation format described online or in print? We always like to be able to point to some kind of documentation.

**Comment by VGTUPress** [comment]
Do you mean some written rules about citation is needed? XML file is not
enough?

2015-06-18 17:27 GMT+03:00 Rintze M. Zelle <notifications@github.com>:

> Is this citation format described online or in print? We always like to be
> able to point to some kind of documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1587#issuecomment-113172572>
> .
>



-- 
*Pagarbiai,*
*Roberta Poderytė*

**Comment by adam3smith** [comment]
right, we much prefer to have written documentation (which can be in Lithuanian), e.g. in case someone reports an error with the style.

**Comment by VGTUPress** [comment]
Here it is, please check, if it is suitable for you.

2015-06-19 8:56 GMT+03:00 Sebastian Karcher <notifications@github.com>:

> right, we much prefer to have written documentation (which can be in
> Lithuanian), e.g. in case someone reports an error with the style.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1587#issuecomment-113383810>
> .
>



-- 
*Pagarbiai,*
*Roberta Poderytė*

**Comment by adam3smith** [comment]
sorry, if you meant to post a link, that didn't make it.

**Comment by VGTUPress** [comment]
I've attached a PDF, but if it was unsuccessful, maybe you could download
here: http://we.tl/v6FyOGEqyV

2015-06-19 9:38 GMT+03:00 Sebastian Karcher <notifications@github.com>:

> sorry, if you meant to post a link, that didn't make it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1587#issuecomment-113394985>
> .
>



-- 
*Pagarbiai,*
*Roberta Poderytė*

**Comment by adam3smith** [comment]
OK, looks like this is also available at http://www.lvalia.lt/files/pdf/literaturos_sarasas_lt.pdf
We'll take a closer look -- we'll need some small adjustments -- but this is very helpful, thanks.

**Comment by VGTUPress** [comment]
Thank you very much. Looking forward for your answer!

2015-06-19 9:53 GMT+03:00 Sebastian Karcher <notifications@github.com>:

> OK, looks like this is also available at
> http://www.lvalia.lt/files/pdf/literaturos_sarasas_lt.pdf
> We'll take a closer look -- we'll need some small adjustments -- but this
> is very helpful, thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1587#issuecomment-113398694>
> .
>



-- 
*Pagarbiai,*
*Roberta Poderytė*

**Comment by rmzelle** [comment]
I found at copy at http://leidykla.vgtu.lt/lt/autoriams/rankraio-rengimas/kai-kurios-raymo-taisykls/literatros-saraas.html too.

@VGTUPress, do you happen to know who wrote this citation style guide? It doesn't seem like it was written by somebody from VGTU.

**Comment by VGTUPress** [comment]
http://leidykla.vgtu.lt/lt/autoriams/rankraio-rengimas/kai-kurios-raymo-taisykls/literatros-saraas.html
is an official VGTU Press site. You also found
http://www.lvalia.lt/files/pdf/literaturos_sarasas_lt.pdf site because
there are people in this association from VGTU and they have rights to use
it. The one I have sent you with WeTransfer is from our computer. So
everything is all right. How many time it will take to make the citation
style work? Thank you for your notes.

2015-06-19 16:59 GMT+03:00 Rintze M. Zelle <notifications@github.com>:

> I found at copy at
> http://leidykla.vgtu.lt/lt/autoriams/rankraio-rengimas/kai-kurios-raymo-taisykls/literatros-saraas.html
> too.
>
> @VGTUPress <https://github.com/VGTUPress>, do you happen to know who
> wrote this citation style guide? It doesn't seem like it was written by
> somebody from VGTU.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1587#issuecomment-113523613>
> .
>



-- 
*Pagarbiai,*
*Roberta Poderytė*

**Comment by rmzelle** [comment]
Okay, thanks. I'm just checking to make sure we give the style the proper name. So it looks like we indeed should name it after VGTU.

> How many time it will take to make the citation style work?

We should be able to help you get the style into proper shape for submission in the next few days. See also https://github.com/citation-style-language/styles/wiki/Style-Requirements. To start:

* Roberta Poderytė is currently listed twice, once as contributor and once as author. It's better if she is listed only as author.
* Will this style be used in Lithuanian, English, or both languages? If the style is for a single language, the `default-locale` attribute needs to be set to either Lithuanian or English. The answer to this question also determines whether we want to use "Vilnius Gediminas Technical University" or "Vilniaus Gedimino technikos universitetas" as the style title.
* The "documentation" link needs to be updated, probably to "http://leidykla.vgtu.lt/lt/autoriams/rankraio-rengimas/kai-kurios-raymo-taisykls/literatros-saraas.html".

**Comment by VGTUPress** [comment]
- About the author - I agree with you. Can the contributor field be
   deleted?
   - We will use it in Lithuanian, because using URL's we set prefix
   "Available online" in Lithuanian ("Prieiga per internetą"). However, we
   think that we should still use "Vilnius Gediminas Technical University" as
   style title, because Mendeley's citation style database, support center and
   other information is in English, so we want to fit in the context. Do you
   think it is fine to do this?
   - Yes, it is the right link.

Will you correct it by yourself or should I re-upload my style with the
changes? We are very glad to communicate with such an attentive support and
we are very thankful for your interest.

2015-06-22 13:22 GMT+03:00 Rintze M. Zelle <notifications@github.com>:

> Okay, thanks. I'm just checking to make sure we give the style the proper
> name. So it looks like we indeed should name it after VGTU.
>
> How many time it will take to make the citation style work?
>
> We should be able to help you get the style into proper shape for
> submission in the next few days. See also
> https://github.com/citation-style-language/styles/wiki/Style-Requirements.
> To start:
>
>    - Roberta Poderytė is currently listed twice, once as contributor and
>    once as author. It's better if she is listed only as author.
>    - Will this style be used in Lithuanian, English, or both languages?
>    If the style is for a single language, the default-locale attribute
>    needs to be set to either Lithuanian or English. The answer to this
>    question also determines whether we want to use "Vilnius Gediminas
>    Technical University" or "Vilniaus Gedimino technikos universitetas" as the
>    style title.
>    - The "documentation" link needs to be updated, probably to "
>    http://leidykla.vgtu.lt/lt/autoriams/rankraio-rengimas/kai-kurios-raymo-taisykls/literatros-saraas.html
>    ".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1587#issuecomment-114059231>
> .
>



-- 
*Pagarbiai,*
*Roberta Poderytė*

**Comment by rmzelle** [comment]
The English VGTU name is fine.

It is easiest for us if you update this pull request yourself. You can do this by using the edit/pencil icon at https://github.com/VGTUPress/styles/blob/patch-2/vgtu-references.csl.

Please make the following changes (per https://github.com/citation-style-language/styles/wiki/Style-Requirements):

* change the style title to `<title>Vilnius Gediminas Technical University (Lithuanian)</title>`
* change the short title to `<title-short>VGTU</title-short>`
* add the "default-locale" attribute on the root `<style/>` element and set it to "lt-LT" (locale code for Lithuanian)
* change the file name to "vilnius-gediminas-technical-university.csl" (see also https://help.github.com/articles/renaming-a-file/). Update the style's ID and "self" link to match.
* update the documentation link
* remove Roberta Poderytė as contributor

**Comment by VGTUPress** [comment]
I have made these changes, Travis CI approved it. Are there some more
things to correct?

2015-06-22 14:18 GMT+03:00 Rintze M. Zelle <notifications@github.com>:

> The English VGTU name is fine.
>
> It is easiest for us if you update this pull request yourself. You can do
> this by using the edit/pencil icon at
> https://github.com/VGTUPress/styles/blob/patch-2/vgtu-references.csl.
>
> Please make the following changes (per
> https://github.com/citation-style-language/styles/wiki/Style-Requirements
> ):
>
>    - change the style title to <title>Vilnius Gediminas Technical
>    University (Lithuanian)</title>
>    - change the short title to <title-short>VGTU</title-short>
>    - add the "default-locale" attribute on the root <style/> element and
>    set it to "lt-LT" (locale code for Lithuanian)
>    - change the file name to "vilnius-gediminas-technical-university.csl"
>    (see also https://help.github.com/articles/renaming-a-file/). Update
>    the style's ID and "self" link to match.
>    - update the documentation link
>    - remove Roberta Poderytė as contributor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1587#issuecomment-114071047>
> .
>



-- 
*Pagarbiai,*
*Roberta Poderytė*

**Comment by rmzelle** [comment]
Great, thanks for contributing!

**Pull request merged**
