### PR TITLE
merge to master

### PR DESCRIPTION
**Pull request by gundestrup**

### CODE REVIEW

**Comment by gundestrup** [comment]
merge to master

**Comment by rmzelle** [comment]
@gundestrup, it's a bit unclear what you're trying to do here.

Our recommended workflow for making contributions is described at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style. Typically you wouldn't make changes in the "master" branch of your own fork of this repository.

**Comment by gundestrup** [comment]
I am trying to merge my master back to the original master. (closing my
fork)
I am aware of the work flow, but please bear in mind that my fork was
created back I 2012....

As you can see the end result is no change to the master

ons. 30. dec. 2020 05.09 skrev Rintze M. Zelle <notifications@github.com>:

**Comment by adam3smith** [comment]
I think there may still be a misunderstanding -- you don't need to merge your fork back to upstream unless there are any meaningful changes (and then those should typically come from a recent and clean feature branch). You also don't need to close it in any way -- if you do indeed want to get rid of a fork, you just delete the repo.

If you're trying to align your fork's master with the upstream master you'll want to locally rebase, i.e. some version of 

```
git rebase upstream/master
``` 

as described e.g. here: https://thoughtbot.com/blog/keeping-a-github-fork-updated 
Might require resolving some conflicts and force pushing locally.

**Pull request closed without merging**
