### PR TITLE
Update friedrich-schiller-university-jena-faculty-of-medicine.csl

### PR DESCRIPTION
**Pull request by POBrien333**
Used this one as a template style for another one I did the other day. This was my 2nd ever CSL style and god was this one bad. Glad I came across it and fix a whole lot of issues. :)

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks!

**Comment by rmzelle** [comment]
@POBrien333, I just noticed you changed the default-locale to German; apart from adding this language to the style title, we might also want to rename the entire style from English to German.

**Comment by rmzelle** [comment]
(I'd be happy to make this change if you agree)

**Comment by POBrien333** [comment]
thanks for spotting that. I've made the PR: #3565 :)

**Pull request merged**
