### PR TITLE
Update revue-archeologique.csl

### PR DESCRIPTION
**Pull request by NMonteix**
Final dot in citation removed
Double comma in ibid-with-locator removed

### CODE REVIEW

**Comment by adam3smith** [comment]
we do generally set periods at the end of citations unless you're saying the period wouldn't be required in a single footnote.

**Comment by NMonteix** [comment]
Some authors told me it was problematic when they wrote after the citation.

**Comment by adam3smith** [comment]
Sorry, we're not going to introduce that level of inconsistency between citation styles. This works fine when using prefix/suffix, which is what's recommended to add text after the citation.
Without the period, a simple task like converting an in-text to a footnote citation doesn't work properly anymore (and it breaks compatibility with other foonote styles that include the period).

**Comment by NMonteix** [comment]
@adam3smith 
Period reinstated

**Comment by adam3smith** [comment]
Great, thanks!

**Comment by NMonteix** [comment]
To you!

Le 21/11/2017 à 18:40, Sebastian Karcher a écrit :

**Pull request merged**
