### PR TITLE
Create IITM_thesis_zotero_style.csl

### PR DESCRIPTION
**Pull request by sawsiba**
This style file is modified from my earlier edited JASA style file to march the style of IIT Madras Ph.D. thesis.

### CODE REVIEW

**Comment by sawsiba** [comment]
This style file is modified from my earlier edited JASA style file to march the style of IIT Madras Ph.D. thesis.

**Comment by rmzelle** [comment]
Is this citation format described online or in print? We always like to be able to point to some kind of documentation.

**Comment by sawsiba** [comment]
There is a pdf file showing the standard citation style for our institute. I have modified the JASA csl file to match that.

The link to that PDF:
https://mat.iitm.ac.in/usefullink/thesis_format.pdf

The csl file does not generate the Sl.No. as shown in that template. The Sl.No. can be added be setting the paragraph format in the word processor. At least that is what I am doing and its is working well.

**Comment by rmzelle** [comment]
> The csl file does not generate the Sl.No. as shown in that template. The Sl.No. can be added be setting the paragraph format in the word processor. At least that is what I am doing and it is working well. 

I think you're misunderstanding the style guide. "<S.No.>." is a placeholder for the citation-number. See page 6 of the PDF, which says "References. Use only Arabic numerals. Serial numbering".

**Comment by sawsiba** [comment]
Hi,
Thanks for your comment.

I think I am not misunderstanding the template. There is another template specifically for LATEX users, which clarifies the style as in that old template.

However, I have just noticed that there is one format mismatch in the attached csl file. It is not making the journal name italic. I shall change it.

Link for the more recent template for LATEX : "https://mat.iitm.ac.in/usefullink.html"
"Latex template for IITM PhD thesis and synopsis   [tar.gz file][zip file].(Updated 29 October, 2012)"
The pdf file is there inside the zip or tar.gz file.

A few example for that pdf page 16.
1. Lamport, L., LATEX: A document preparation system. Addision-Wesley, 1986.
2. Ramachandran, P., MayaVi: A free tool for CFD data visualization. In 4th An-
nual CFD Symposium. Aeronautical Society of India, 2001. Software available at:
http://mayavi.sf.net.
3. Ramachandran, P. (2004). L A  TEX class for dissertations submitted to IIT-M. Ph.D.
thesis, Department of Aerospace Engineering, IIT-Madras, Chennai – 600036.
4. Ramachandran, P., S. C. Rajan, and M. Ramakrishna (2003). A fast, two-
dimensional panel method. SIAM Journal on Scientific Computing, 24(6), 1864–1878.
5. van Rossum, G. et al. (1991–). The Python programming language. URL http:
//www.python.org/.

Please correct me if you still think I am misunderstanding the template. By the way, I am preparing my thesis in openoffice with zotero.

Thanks.

**Comment by rmzelle** [comment]
> Please correct me if you still think I am misunderstanding the template.

No, I thought you were changing the paragraph style to print "S.No. Lamport, L., LATEX: A document preparation system. Addision-Wesley, 1986.", but I understand now that you're not doing that.

Still, this is something that you should code in the style. See the Nature style to see how (https://www.zotero.org/styles/nature?source=1). You need to print the "citation-number" CSL variable, and use `second-field-align="flush"` to indent the rest of the reference. Relevant excerpt:

```
  <bibliography et-al-min="6" et-al-use-first="1" second-field-align="flush" entry-spacing="0" line-spacing="2">
    <layout>
      <text variable="citation-number" suffix="."/>
      <group delimiter=" ">
        <text macro="author" suffix="."/>
```

To update this pull request, you can use the edit/pencil icon at https://github.com/sawsiba/styles/blob/patch-1/IITM_thesis_zotero_style.csl.

**Comment by rmzelle** [comment]
@sawsiba, let us know if you need help with this.

**Comment by rmzelle** [comment]
Closing because of inactivity.

**Pull request closed without merging**
