### PR TITLE
Update instituto-brasileiro-de-informacao-em-ciencia-e-tecnologia-abn…

### PR DESCRIPTION
**Pull request by andreappel**
…t.csl

Incorporating #4493 updates and for consistency with #4508

### CODE REVIEW

**Comment by rmzelle** [comment]
@andreappel, did you uncheck "Allow edits from maintainers" for this pull request, and if so, could you change this back? I need to make a very minor tweak before I can merge this.

See https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by rmzelle** [comment]
Or is this pull request superseded by #4516?

**Comment by andreappel** [comment]
> @andreappel, did you uncheck "Allow edits from maintainers" for this pull request, and if so, could you change this back? I need to make a very minor tweak before I can merge this.

Probably by accident, sorry. Just reverted it.

> Or is this pull request superseded by #4516?

They are slightly different. #4511 is the version for shortened/initialized first names, and #4516 displays full names.

**Comment by rmzelle** [comment]
> They are slightly different. #4511 is the version for shortened/initialized first names, and #4516 displays full names.

That doesn't seem to be the case. They're both for instituto-brasileiro-de-informacao-em-ciencia-e-tecnologia-abnt.csl (the full name variant). Feel free to create a new pull request for instituto-brasileiro-de-informacao-em-ciencia-e-tecnologia-abnt-initials.csl

**Comment by andreappel** [comment]
@rmzelle I didn't notice that. But both (abbreviated and full names) seem to be up to date now. Thank you!

**Pull request merged**
