### PR TITLE
Creation of two Collection de l'Ecole française de Rome styles

### PR DESCRIPTION
**Pull request by NMonteix**

### CODE REVIEW

**Comment by rmzelle** [comment]
(ideally we wouldn't have the "Merge pull request #6 from citation-style-language/master" commit included in this PR)

**Comment by NMonteix** [comment]
(I would admit I don't understand why this is sticky... Anyway, I can 
start over using the Master branch for the spec and then a normal PR for 
the styles)

**Comment by adam3smith** [comment]
as you do so, remember file extensions on your file (which are the problem that has Travis fail here).

**Comment by rmzelle** [comment]
> I would admit I don't understand why this is sticky

I'm not sure what you mean with "sticky", but your fork basically had a parallel history. Git allows us to merge such parallel branches, but it's cleaner to merge branches that just contain the desired changes. You can achieve this by "rebasing" your repository (this replaces your history with ours), and re-adding your files. It's simpler to just creating a new pull request via the GitHub interface from our repo, though. You then end up with a new branch (e.g. "patch-1") in your repo that is up to date with ours.

**Comment by NMonteix** [comment]
I guess I missed something in rebasing my repo, even if I thought the 
changes in the main (not mine) repo had been merged to mine.
Yes, indeed, for next time, I will use the new PR button...
Thanks

**Comment by rmzelle** [comment]
> even if I thought the
changes in the main (not mine) repo had been merged to mine.

When you rebase, you're not merging. What I'm requesting is to avoid any merges.

**Comment by NMonteix** [comment]
I thought rebasing was possible merging the main repo into mine (using 
mine as base the main as head).
So easiest way to use the new file button and then create a branch for 
merging?

**Comment by rmzelle** [comment]
If you're interested, see e.g. https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview.

If you merge "the main repo into mine", you get the following:

image

If we then accept your pull request, our repository commit history will contain the fork, and any further commits would start from the "merge commit".

It's cleaner to rebase, which moves the branching point to the most recent commit of the master branch, so you end up with:

image

If we then accept your pull request, we have a clean linear history.

> So easiest way to use the new file button and then create a branch for
merging?

Yes.

**Comment by NMonteix** [comment]
Thanks for the explanations. I'll try to catch the whole thing (and then 
will use the easiest way...)

**Comment by rmzelle** [comment]
In many git clients it's not exactly trivial to rebase, and git is also not very easy to understand for newcomers, so yeah, I'm a big fan of the easiest way :).

**Comment by rmzelle** [comment]
(superseded by #1805)

**Pull request closed without merging**
