### PR TITLE
Create Nehet style

### PR DESCRIPTION
**Pull request by NMonteix**

### CODE REVIEW

**Comment by rmzelle** [comment]
You have two "access" macros.

**Comment by NMonteix** [comment]
Ok
Didn't quite understand
Changed
Thanks

**Comment by rmzelle** [comment]
Now you added extra indenting (too much) :)

(you should be able to quickly reindent the style with http://formatter.citationstyles.org/ )

**Comment by NMonteix** [comment]
Indeed

**Comment by NMonteix** [comment]
I have been starting using Github desktop. To rebase, I guess it gets more than syncing between master branches?

**Comment by adam3smith** [comment]
looks good to me. I'll merge tonight or go ahead @rmzelle

**Comment by adam3smith** [comment]
thanks!

**Comment by NMonteix** [comment]
To you!

**Comment by rmzelle** [comment]
Looks like the title should be "NeHet" instead of "Nehet", no? (see http://sfe-egyptologie.fr/index.php/fr/publications/revue-nehet )

**Comment by rmzelle** [comment]
> I have been starting using Github desktop. To rebase, I guess it gets more than syncing between master branches?

I'm not really sure what your question is here.

**Comment by NMonteix** [comment]
It depends though... NeHet on the title, NeHeT as a name for the PDF 
file, Nehet inside the review itself [See 
http://sfe-egyptologie.fr/NEHET3/02-NeHeT%203-Sommaire-Avant-Propos-p.I-VI.pdf 
(p. 3)].
I will contact them and change the title according to their answer

**Comment by NMonteix** [comment]
Question solved crawling in the Github tutorials
I should not have undue PR or rebasing problems now, using the command line

**Comment by rmzelle** [comment]
> I should not have undue PR or rebasing problems now, using the command line

Yes, I haven't found a Git UI client yet that makes it straightforward to rebase, so the command line usually works just as well.

**Comment by NMonteix** [comment]
Title is NeHeT in fact (they might have a problem with the typography of 
their title page...)
File changed and committed

**Comment by rmzelle** [comment]
Okay, thanks for checking!

**Pull request merged**
