### PR TITLE
Added a style for Deutsche Lebensmittel-Rundschau (DLR)

### PR DESCRIPTION
**Pull request by Mailaender**
It was created with http://editor.citationstyles.org taking articles in the journal for reference.

### CODE REVIEW

**Comment by rmzelle** [comment]
Does DLR take open submissions? Is there a guide for authors online that describes the citation format?

(the CSL repository is primarily for journals with open submissions, see https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles)

**Comment by Mailaender** [comment]
Improved the style a bit further. The self description is in German only: http://www.dlr-online.de/mediadaten.html I would classify it as a very local, but open submission and peer-reviewed journal.

**Comment by adam3smith** [comment]
very local is fine and I see it's peer reviewed, but I don't see any way to submit (and thus also no instructions for contributors)? How would one go about submitting to this? (I'm asking both because we do want to make sure putting this in the general repository makes sense and because we really do like to have documentation we and others can refer to if there are any doubts in the future).

**Comment by Mailaender** [comment]
I believe the journal has no guidelines and everyone just uses what he likes so indeed you may be right: this is probably not suitable for inclusion.

**Pull request closed without merging**
