### PR TITLE
journal-of-hearing-science-2022.csl

### PR DESCRIPTION
**Pull request by JHSifps**
Minor style changes

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks. Are you sure that's correct? Now there isn't any punctuation between a book title and the publisher? What is the problem you're trying to fix?

**Comment by JHSifps** [comment]
Dear Brenton,

I try to update a JHS Zotero style to our instruction for authors on the JHS website. I followed the Editing CSL Styles Guide. However, I am not IT worker and have no experience with such an issue, as you can see.  I wanted to withdraw full-stops from journals abbreviated name: Curr Biol

There are many other things to change, and perhaps it would be better to create a new style for JHS. What is your opinion?

With regards
Aleksandra

Journal of Hearing Science
Managing Editor

**Comment by adam3smith** [comment]
Thanks -- I reworked this to actually reflect the style in the author guidelines

**Comment by JHSifps** [comment]
Thank you very much! I wonder if I could ask you to do some changes in the future? We are now in the process of changing our website and the guidelines for authors will change too.
With regards
Aleksandra

**Comment by adam3smith** [comment]
> Thank you very much! I wonder if I could ask you to do some changes in the future? We are now in the process of changing our website and the guidelines for authors will change too.

You can request changes via the Zotero forums, though no guarantees how fast that'll be (anywhere from 2 weeks to 2 months is typical). 
If you need something quicker, either paying for it or doing it yourself (ideally with clean code) typically gets this in faster.

**Pull request merged**
