### PR TITLE
Update north-pacific-anadromous-fish-commission-bulletin.csl

### PR DESCRIPTION
**Pull request by Br-Johnson**
Change title to sentence case

### CODE REVIEW

**Comment by adam3smith** [comment]
I may have asked this before, but why use capitalize-first? The standard way to implement sentence case is to remove the `text-case` attribute entirely (as the style had it for most titles before).

**Comment by Br-Johnson** [comment]
Hi @adam3smith I've removed the text-case attribute all together now so I'm hoping that resolves this and can be merged

**Comment by Br-Johnson** [comment]
Thanks for the linting! Is this good to be merged now @adam3smith?

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
