### PR TITLE
Create angelaki.csl

### LINKED ISSUE #1171: Angelaki: Journal of the Theoretical Humanities
This is a Taylor & Francis journal, which is not in the list from the publisher but uses a standard style. = For the future add-list:

https://forums.zotero.org/discussion/12652/style-request-modern-language-association-note-with-bibliography/#Item_0

### PR DESCRIPTION
**Pull request by zuphilip**
Fixes #1171

### CODE REVIEW

**Comment by zuphilip** [comment]
I haven't added the subtitle `Journal of the Theoretical Humanities` because the title `Angelika` doesn't look ambiguous for me. Or do you prefer to add the subtitle as well?

**Comment by rmzelle** [comment]
Thanks. And yes, I try to avoid including subtitles at all cost :).

**Comment by zuphilip** [comment]
Okay. I couldn't find anything about subtitle in the https://github.com/citation-style-language/styles/wiki/Style-Requirements

**Comment by rmzelle** [comment]
I rather keep Style Requirements as compact as possible. This doesn't come up very often.

**Pull request merged**
