### PR TITLE
Update style-manual-australian-government.csl

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/95329/style-error-style-manual-australian-government-author-date#latest

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks! 

Looks like Line 162 has an extraneous prefix still. And shouldn't there be some sort of punctuation between the editor and container title?

**Comment by adam3smith** [comment]
image

So no punctuation after editor(s) it looks like

**Comment by POBrien333** [comment]
thanks for spotting that, Brenton. I've removed that prefix.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
