### PR TITLE
Update ausonius-editions.csl

### PR DESCRIPTION
**Pull request by jgravier001**
This pull request aims to correct some aspect of the style, mainly fot contributions and online references, in collaboration with the Ausonius Editions (UMR Ausonis - Université Bordeaux Montaigne)

### CODE REVIEW

**Comment by adam3smith** [comment]
Citations without author appearing as just the year (2012) in the auto-generated citation must be wrong, no? Either the anonymous should be there, or the author should be replaced by a short title.

**Comment by jgravier001** [comment]
Hello and thank you for your answer.
Indeed, by updating the csl style, I forgot to reintroduce the else case "Anonymous". Then, your suggestion of short title for some specific refences makes sense : I also implemented if to the file. It seems now it works correctly.
Best regards

**Comment by adam3smith** [comment]
Thanks!

**Comment by jgravier001** [comment]
Thank you for your fast review and for the merge.

**Pull request merged**
