### PR TITLE
Create van-yuzuncu-yil-universitesi-fen-bilimleri-enstitusu.csl

### PR DESCRIPTION
**Pull request by YYU-FBE**
Van Yüzüncü Yıl Üniversitesi Fen Bilimleri Enstitüsü Tez Yazım Stili - apa6 Tr https://csl.mendeley.com/styles/578584211/VanYYUFBE-apa6-tr-4

### CODE REVIEW

**Comment by adam3smith** [comment]
Sorry for the delay here -- could you clarify what this style is based on? If it's just a link to the existing APA-TR style, we'd add it as a dependent style. If it follows different rules, we'd want a link to the documentation

**Comment by YYU-FBE** [comment]
Hi, 
Please accept my apoligize for late response.
It is not only a link to existing APA-TR style. We changed some details according to our institute writing rules (off the record i already give up asking "why", you know these organizations). But i don't know what you mean "the documentation". Please can you give an example or definition?

PS: We will also apply the English version for our foreign students and for our institute journal.

**Comment by adam3smith** [comment]
@YYU-FBE : sorry, I missed your response here -- by "documentation" I mean what you would point students who don't use a reference manager to for formatting reference. In other word, the document that describes this citation style

**Comment by YYU-FBE** [comment]
Thansk for your response.

Here are the links in both Turkish and English. Section I.14 and I.15 are related to citations. II.7 is about how to use csl (Mendeley).

Turkish: https://www.yyu.edu.tr/images/files/Tez_Yazim_Kurallari(1).pdf 

English : https://www.yyu.edu.tr/images/files/Thesis_Writing_Rules(1).pdf

**Comment by adam3smith** [comment]
Great, thanks!

**Pull request merged**
