### PR TITLE
show issue numbers in springer basic author-date style

### PR DESCRIPTION
**Pull request by fgnievinski**
forked springer-basic-author-date-no-et-al.csl

### CODE REVIEW

**Comment by adam3smith** [comment]
Is this for a specific journal or other requirement?

**Comment by fgnievinski** [comment]
Yes, it's for Springer's "GPS Solutions" journal:
https://www.springer.com/journal/10291/submission-guidelines#Instructions%20for%20Authors_References
GPS Solutions has its own CSL file, which simply inherits 
Springer basic author-year:
https://github.com/citation-style-language/styles/blob/master/dependent/gps-solutions.csl
I didn't update that CSL file directly because I thought 
that showing issue numbers might be helpful in general.

**Comment by fgnievinski** [comment]
just pinging to avoid being automatically closed for no further activity.

**Comment by adam3smith** [comment]
Sorry for the long wait. So I've confirmed that GPS journal consistently does use issue numbers. I'd want to double-check that some of the journals of the springer-basic-author-date-no-et-al.csl style _do_ use issue numbers next and then either merge this or replace the original style

**Comment by adam3smith** [comment]
@rmzelle -- currently I'm not seeing any other journal that uses this style, but given the number of Springer journals, there's a good chance there is. Two options:
1. Take this style and redirect the gps-solutions independent style
2. Make this style just for gps-solutions and delete the dependent

I don't have a strong opinion either way.

**Comment by rmzelle** [comment]
>     1. Take this style and redirect the gps-solutions dependent style

Let's go with this one (having many Springer independent variants isn't super problematic as I assume nobody looks for them, unlike APA/CMoS).

@fgnievinski, thanks!

**Pull request merged**
