### PR TITLE
Update cultural-geographies.csl

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/72439/problems-with-cultural-geographies-humane-style

### CODE REVIEW

**Comment by POBrien333** [comment]
Any clue what's going on here?

**Comment by adam3smith** [comment]
Citation format needs to correspond to class -- let's see if this restarts Travis (which had also stalled)

**Comment by POBrien333** [comment]
thank you. :)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
