### PR TITLE
Add APA numeric and update BioEssays

### PR DESCRIPTION
**Pull request by bwiernik**
https://forums.zotero.org/discussion/85312/style-request-updating-bioessays#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
@bwiernik do you want to add the styles on the exception list for unused macros?

**Comment by bwiernik** [comment]
Actually, yeah, I'll do that instead.

**Comment by adam3smith** [comment]
I think that should be `apa-numeric-superscript` in line with Vancouver, no?
(1) numeric
[2] numeric-brackets
<sup>1</sup> numeric-superscript
<sup>[1]</sup> numeric-superscript-brackets

**Comment by bwiernik** [comment]
Got it okay.

**Comment by adam3smith** [comment]
I hope the two journals are OK with this -- I've seen the provisional guidelines from the Biotechnology journals and they're a not-very-precise adaptation of APA 6th... let's hope they're actually OK with correct APA 7

**Comment by adam3smith** [comment]
Thanks!

**Comment by bwiernik** [comment]
BioEssays indicated that APA 7 was fine, and Biotechnology Journal said they were the same as BioEssays, so I’m thinking they aren’t too concerned about the details.

**Pull request merged**
