### PR TITLE
ikc.csl

### PR DESCRIPTION
**Pull request by omerfarukgorucu**
İzmir Katip Çelebi Üniversitesi Sosyal Bilimler Enstitüsü

### CODE REVIEW

**Comment by adam3smith** [comment]
Why did you take out the diacritics and change it to lowercase? That doesn't make sense to me. Please ask questions if things aren't clear, we're happy to help, but don't just change things around randomly.

**Comment by omerfarukgorucu** [comment]
adam3smith, i'm sorry. You wasted your time because of my fault. I'm new at this stuff. I was not sure whether some Turkish characters would be accepted. On the other hand i'm trying to figure out Github system. I need your help to save our csl style to citationstyles.org. What's the next step to make this possible?

**Comment by omerfarukgorucu** [comment]
@rmzelle, #3783 and #3784 actually use same style. These are multiples. So we can use #3784 as just "Sosyal Bilimler Enstitüsü" and remove the other one. 

We based our style on "Chicago Manual of Style 17th edition (full note)" http://www.zotero.org/styles/chicago-fullnote-bibliography

**Comment by rmzelle** [comment]
Thanks!

And to answer your earlier questions and remarks, special characters are allowed in style titles. They just need to be removed from the file name and style ID. And the easiest way to submit styles is by following our instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md.

**Pull request merged**
