### PR TITLE
Create earthquake-spectra

### PR DESCRIPTION
**Pull request by bbbear2002**
CSL style for journal Earthquake Spectra

### CODE REVIEW

**Comment by bbbear2002** [comment]
Please someone help me look into it.

**Comment by rmzelle** [comment]
@bbbear2002, thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by bbbear2002** [comment]
@rmzelle Sorry i can't remember, maybe it is based on CSL style of American Society of Civil Engineers

**Comment by rmzelle** [comment]
> @rmzelle Sorry i can't remember, maybe it is based on CSL style of American Society of Civil Engineers

No, I don't think so. It looks like it should be one of these: https://github.com/citation-style-language/styles/search?utf8=%E2%9C%93&q=Humphrey&type=

Anyway, if you don't remember it's fine to leave the style as is.

**Comment by rmzelle** [comment]
(I think it was probably Journal of Studies on Alcohol and Drugs)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
