### PR TITLE
Update ecole-de-technologie-superieure-apa.csl

### PR DESCRIPTION
**Pull request by Bibref**
Update to the style to include the Software document type now available in Zotero. Removal of the previous "hack" to give an output that looks like softwares to simply include the new type software.

### CODE REVIEW

**Comment by adam3smith** [comment]
The way you're doing this doesn't work: you're actually removing italics from books and other item types that need them -- the hack is in the next line (testing for 'version' to determine that something is software.) You'll want to move that entire `if` section into a new `else-if type="software"`

**Comment by Bibref** [comment]
> The way you're doing this doesn't work: you're actually removing italics from books and other item types that need them -- the hack is in the next line (testing for 'version' to determine that something is software.) You'll want to move that entire `if` section into a new `else-if type="software"`

Thank you for the comment. I adjusted the commit to reflect your comment and tested it out successfully.

**Review by Bibref — COMMENTED** [review]
**This change should answer adam3smith comment on the pull request.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
