### PR TITLE
Create australian-archaeology.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/78728/style-request-australian-archaeological-association

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, https://www.tandfonline.com/action/authorSubmission?journalCode=raaa20&page=instructions#refs suggests the journal uses "Taylor&Francis Reference Style V Harvard B" (which we don't have yet: https://www.zotero.org/styles?q=taylor).

**Comment by rmzelle** [comment]
(if you could take a quick look to see if this Taylor and Francis style guide describes the same format as the documentation link you've been using, it would be better to create Taylor and Francis independent style and a dependent for this journal. Thanks!)

**Comment by POBrien333** [comment]
Good find, but...
- The Taylor Harvard V we have is actually the B version (see that the documentation link is https://www.tandf.co.uk//journals/authors/style/reference/tf_V.pdf, which is the same actually given for the AA journal
- The T&F Harvard V B is different to the style I created based on the guidelines on the AA website and actual publications.

**Comment by rmzelle** [comment]
Thanks!

**Comment by POBrien333** [comment]
Anthropology! I was wondering what the best category would be!

**Comment by rmzelle** [comment]
In this case I went to the Zotero Style Repository, searched for "archaeology", and checked what the most frequently used tag was for the matching styles.

**Comment by adam3smith** [comment]
This is somewhat unique to the US, but "anthropology" here has three branches -- cultural anthropology (which is what we mostly think of under anthro), biological anthropology, and archaeology. They're all very different from each other, which makes of interesting/odd seminars.

**Pull request merged**
