### PR TITLE
Create journal-of-the-japan-medical-library-association.csl

### PR DESCRIPTION
**Pull request by hellboy84**
I create the citation style for Journal of the Japan Medical Library Association.

### CODE REVIEW

**Comment by rmzelle** [comment]
Do you expect people to use this CSL style primarily for English citations, or for Japanese ones?

**Comment by hellboy84** [comment]
Thank you for your comment, I expect people to use this style primarily for Japanese citations.

**Comment by rmzelle** [comment]
In that case, would it make sense to use the Japanese name ("Igaku Toshokan", or even "医学図書館") instead of "Journal of the Japan Medical Library Association" for style's title?

The style should probably also be set to Japanese (point 3 of https://github.com/citation-style-language/styles/wiki/Style-Requirements ). (the locale code for Japanese is "ja-JP")

**Comment by hellboy84** [comment]
That's my mistake! I revised codes according to your proposal.
I have changed language code and title and Style ID, so file name has changed also. Would this be correct?

**Comment by rmzelle** [comment]
Great.

Can you also delete

```
  <locale xml:lang="fr">
    <date form="text" delimiter=" ">
      <date-part name="day"/>
      <date-part name="month" form="short" strip-periods="true"/>
      <date-part name="year"/>
    </date>
    <terms>
      <term name="retrieved">disponible</term>
      <term name="from">sur</term>
    </terms>
  </locale>
  <locale xml:lang="de">
    <terms>
      <term name="retrieved">verfügbar</term>
      <term name="from">unter</term>
    </terms>
  </locale>
```

? That's for French and German localization, which isn't relevant for this style (the section for English might come in handy in the future, so you can leave that).

**Comment by hellboy84** [comment]
Thanks a lot!
I deleted French and German section.

**Comment by rmzelle** [comment]
Perfect, thanks!

**Comment by hellboy84** [comment]
I appreciate your help!

**Comment by rmzelle** [comment]
You're welcome! Thanks for contributing!

**Pull request merged**
