### PR TITLE
add DOI preprint to american-society-for-microbiology.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/83976/change-style-for-journal-of-microbiology-and-biology-education-and-american-microbiology-society

Looks like some ASM journals are adding the DOI now.
Option 1:
Accept this PR and just have it added for all the journals and see if somebody moans about it.
Option 2:
Make two separate styles, one with and one without the DOI.

Let me know what you think and I prepare it.

### CODE REVIEW

**Comment by adam3smith** [comment]
Hmmm: https://mmbr.asm.org/sites/default/files/additional-assets/MMBR-ITA.pdf

>  Note  that  DOIs  are  notneeded for most references. ASM copy editors will automat-ically  insert  DOIs  on  all  references  in  the  CrossRef  andPubMed  databases  during  copyediting. 

I didn't check if that's the same for all journals, but would guess it is?

**Comment by POBrien333** [comment]
Oh, didn't check that file. Thanks for spotting that.
Maybe then let's just leave it as is, no?

MCB for example has the same guidelines file: https://mcb.asm.org/sites/default/files/additional-assets/MCB-ITA.pdf

**Comment by adam3smith** [comment]
We could ask if they're getting told to include DOIs by the journals/editors, in which case I'm always happy to add them, but otherweise I wouldn't be inclined to.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
