### PR TITLE
Create associacao-brasileira-de-normas-tecnicas-ufrgs-footnote-ibid.csl

### PR DESCRIPTION
**Pull request by barbara-vianna**
Using the Brazilian ABNT citation and bibliography style created by the SBUFRGS, created the option to insert the citations as footnotes, using samples from Chicago Style.

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle This actually looks fine to me. Can you check the metadata to see if you have any concerns?

**Comment by rmzelle** [comment]
@adam3smith, feel free to merge.

**Comment by adam3smith** [comment]
@barbara-vianna -- this is ready to merge, but we also just merged an updated version of the style you based this on (I think) in #4460 -- could you please check whether you want to update this style based on those changes before we merge?

**Comment by barbara-vianna** [comment]
I would like to update it first, but I won't be able to do it until
february. The style still has some issues.

**Comment by adam3smith** [comment]
Great, thanks -- we've disabled the automatic closing of pull requests, so this will just stay open. Let us know if you need any help, otherwise we'll check back late February

**Comment by rmzelle** [comment]
@barbara-vianna, are you still planning to update this style?

**Comment by barbara-vianna** [comment]
Yes, but god knows when. This is a side project for me, and right now my
plate is overflowing. Go ahead and publish it as is, if that is the next
step needed. The format is funcional, and the errors it contains are minor.

**Comment by rmzelle** [comment]
@barbara-vianna, okay, thanks. We'll just merge the style as-is, then. If you later wish to make any further changes, please start from the copy we have in our repository (see https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style for instructions).

**Pull request merged**
