### PR TITLE
Create chicago-author-date-feup.csl

### PR DESCRIPTION
**Pull request by serbernardo**
Variation of the Chicago author-date style 17th edition. 
Authors in reference lists are shown in a abreviated form
Webpages always show access date with or wihtout edition date inserted
Style to be used in Faculty of Engineering - University of Porto

### CODE REVIEW

**Comment by serbernardo** [comment]
I would really aprecciate some help to have this style up and running...
Can anyone please help?

**Comment by cpina** [comment]
Hi @serbernardo 

You've reached to me by email but I thought that adding it here might help a bit more...

I'm just going to try to "translate" from computer errors to human errors. I haven't done any CSL related things for long time now! Actually it brings back good memories seeing the errors :-)

> worried There are some issues with your submission.
> 3 tests failed
> 
> chicago-author-date-FEUP: must have a conventional file name
> 
> ```
> expected "chicago-author-date-FEUP.csl" to match /^[a-z\d]+(-[a-z\d]+)*\.csl$/
> Diff:
> @@ -1,2 +1,2 @@
> -/^[a-z\d]+(-[a-z\d]+)*\.csl$/
> +"chicago-author-date-FEUP.csl"
> ```

It's saying in a friendly way for regular expression readers or non-friendly way for non-regular expression readers:
The file name need to start with lower case letters or numbers and then have optionally groups of "-" and lower case letters/numbers.

In your case I think that if you rename it to "chicago-author-date-feup" it would work.


> 
> chicago-author-date-FEUP: may not have any unused macros
> 
> ```
> expected: []
>      got: ["editor", "translator"]
> 
> (compared using ==)
> ```

It says that no unused macros should be present  but "editor" and "translator" are not used. I'm not sure if you intended to not used them, if this is the case deleting them might fix the problem:
```
  <macro name="editor"> 
    <names variable="editor"> 
      <name name-as-sort-order="first" and="text" sort-separator=", " delimiter=", " delimiter-precedes-last="always"/> 
      <label form="short" prefix=", "/> 
    </names> 
  </macro> 
  <macro name="translator"> 
    <names variable="translator"> 
      <name name-as-sort-order="first" and="text" sort-separator=", " delimiter=", " delimiter-precedes-last="always"/> 
      <label form="short" prefix=", "/> 
    </names> 
  </macro>
```


> chicago-author-date-FEUP
> chicago-author-date-FEUP: style ID must be of the form "http://www.zotero.org/styles/" + style file name (without ".csl" extension, e.g. "http://www.zotero.org/styles/apa")
> 
> ```
> expected: "http://www.zotero.org/styles/chicago-author-date-FEUP"
>      got: "http://www.zotero.org/styles/chicago-author-date-feup"
> 
> (compared using ==)
> ```

the filename is -FEUP and the style id -feup. They should have the same spelling (the style Id without the .csl)

While looking at this I had a look at the file. I think that the contributors of the original style are usually left in the new style. I'm sure that Rintze or Sebastian can explain the convention for this cases.

**Comment by bwiernik** [comment]
You can just re-open the pull request. One other change you will want to make is to rename the file and style ID and title to follow the format I used for the Faculty of Psychology and Education Sciences, Porto style:
-	Just put the university and faculty name in the file name, chicago-author-date isn’t necessary unless the faculty has multiple different styles that it allows
o	If it does have multiple styles, put those at the end, e.g.: universidade-do-porto-faculdade-de-psicologia-e-de-ciencias-da-educacao-apa.csl vs universidade-do-porto-faculdade-de-psicologia-e-de-ciencias-da-educacao-numeric.csl
o	Spell out the whole words, don’t use abbreviations
-	Title the style with the University name, then the faculty name, then the type of style if needed, separated by hyphens
o	E.g., Universidade do Porto - Faculdade de Psicologia e de Ciências da Educação – APA

**Comment by serbernardo** [comment]
Hi @bwiernik , Well I made a stupid action because I have deleted the repository :( 

"It says below  the repository that submitted this pull request has beeen deleted"
What can I do now? 

Thanks for the suggestion, In our faculty we use others styles like IEEE and NP405 (a portuguese versions of iso 690). The chicago author date is the most used by far.

Keeping in mind your suggestions I think it would be ok like this:
Title: Universidade do Porto - Faculdade de Engenharia – Chicago
ID: universidade-do-porto-faculdade-de-engenharia-chicago.csl

**Comment by bwiernik** [comment]
It looks like you deleted your fork of the style repository. Just open a new pull request in that case. Those ID/title are fine.

**Comment by serbernardo** [comment]
thanks a lot for your help @bwiernik and @cpina. I will open a new pull request. 
All the best for you both.

**Pull request closed without merging**
