### PR TITLE
Create virican-textrevisions.csl

### PR DESCRIPTION
**Pull request by delgui**
This is a Vancouver Author-date style with new features to facilitate checking references during text revisions.Not intended for final documents.

### CODE REVIEW

**Comment by rmzelle** [comment]
@delgui, thanks. Who would be using this style? The authors, or the editors?

**Comment by delgui** [comment]
Hello, @rmzelle!

Both styles are mostly for the authors. 

> @delgui, thanks. Who would be using this style? The authors, or the editors?

**Comment by adam3smith** [comment]
I still don't quite understand what this is for, sorry. If I'm understand the ViriCan website correctly, this is a working group with <10 member -- if that's right, I think hosting the style(s) locally, as you already do, is the better approach. It gives you more flexibility, and since this is for internal use, you really don't need to make the style easy to find for a worldwide audience, which is the main draw of having it on the repository.

I may be misunderstanding, though.

**Comment by delgui** [comment]
Hello, @adam3smith adam3smith!

These styles are being used by our research group for some time now. However, people that do not belong to our group commented that they were very useful for them also. That's why I decided to share these styles with the Zotero Community worldwide. I provided 2 styles here:

virican-textrevisions.csl
This is intended to check citations during editions. Useful to find out which work is being cited without going to the end of the document. Also, the bibliography includes URLs (DOI, PMID, and PMCID, if available in the database) to go to the published paper online, if necessary.

virican-abnt-doi.csl
Is intended for final documents that requires the Brazilian ABNT style. There are many ABNT styles in Zotero repository, and they all are obsolete because the were prepared with outdated version of the ABNT rules. Our style has some updates considering the last ABNT rule (issued on Oct, 2018) and some improvements. 

I hope this address your questions. Still, if you think they are not suitable for the repository, I will understand. Anyway, they are available at our website, as you know.

deo

**Comment by adam3smith** [comment]
So, I think the reference checking style we won't take -- that's indeed better suited for your homepage. 

But I'd be very interested in getting an updated/improved ABNT version.
If you're following standard ABNT rules without any local customization, I think it may just make sense to replace the existing associacao-brasileira-de-normas-tecnicas.csl, which hasn't been updated since 2016

**Comment by delgui** [comment]
Ok, @adam3smith. Our ABNT style does not have local customization.  It can be used to replace the associacao-brasileira-de-normas-tecnicas.csl, as you indicated.

However, please note that there are many versions of the ABNT rules in the repository. By the way, I provided ours because none of them were really appropriate. See below.

16 styles found:

    Associação Brasileira de Normas Técnicas (note, Portuguese - Brazil)(2018-05-22 00:59:23)
    Associação Brasileira de Normas Técnicas (Portuguese - Brazil)(2016-02-26 17:39:47)
    Escola de Comando e Estado-Maior do Exército - ABNT (Portuguese - Brazil)(2018-05-22 00:59:23)
    Escola de Comando e Estado-Maior do Exército - Instituto Meira Mattos - ABNT (Portuguese - Brazil)(2018-06-25 03:31:13)
    Instituto de Pesquisa Econômica Aplicada - ABNT (Portuguese - Brazil)(2017-06-27 03:09:32)
    Universidade de São Paulo - Faculdade de Medicina Veterinária e Zootecnia - ABNT (Portuguese - Brazil)(2018-10-23 04:18:21)
    Universidade Estadual Paulista - Campus de Dracena - ABNT (autoria abreviada) (Portuguese - Brazil)(2018-06-17 16:03:44)
    Universidade Federal de Minas Gerais - Faculdade de Ciências Econômicas - ABNT (autoria abreviada) (Portuguese - Brazil)(2018-05-22 00:59:23)
    Universidade Federal de Minas Gerais - Faculdade de Ciências Econômicas - ABNT (autoria completa) (Portuguese - Brazil)(2018-05-22 00:59:23)
    Universidade Federal de Sergipe - ABNT (Portuguese - Brazil)(2017-06-27 03:09:32)
    Universidade Federal do Espírito Santo - ABNT (autoria abreviada) (Portuguese - Brazil)(2018-07-03 02:59:21)
    Universidade Federal do Espírito Santo - ABNT (autoria completa) (Portuguese - Brazil)(2018-07-03 02:59:21)
    Universidade Federal do Estado do Rio de Janeiro - Educação Infantil e Políticas Públicas - ABNT (Portuguese - Brazil)(2018-03-28 23:10:24)
    Universidade Federal do Paraná - ABNT (Portuguese - Brazil)(2017-06-27 03:09:32)
    Universidade Federal do Rio Grande do Sul - SBUFRGS - ABNT (autoria abreviada) (Portuguese - Brazil)(2017-11-08 01:36:37)
    Universidade Federal do Rio Grande do Sul - SBUFRGS - ABNT (autoria completa) (Portuguese - Brazil)(2017-11-08 01:36:37)

**Comment by adam3smith** [comment]
Right, I'm talking about the 2nd one. The other ones are created for ABNT as used at specific universities. I understand it's not uncommon to have some variation since the ABNT guidelines leave some room for interpretation.

**Pull request closed without merging**
