### PR TITLE
Create antafr.csl

### PR DESCRIPTION
**Pull request by samarkar**
New style for _Antiquités africaines_ Journal.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks! Same questions as for https://github.com/citation-style-language/styles/pull/4775:

Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

And does this journal only publish in French?

**Comment by samarkar** [comment]
Thank you very much for those corrections. I based myself on another style I created for a journal published in the team where I worked before, more oriented on art history: invisu.csl.
But I have changed a lot of things for the needs of the archaeological journals I am in charge of now, in particular by changing the style from "note" to "author-date". So I don't think it's useful to mention the InVisu style, which is very different.
Antonio

**Comment by samarkar** [comment]
I forgot: the journal publishes articles in several languages (French, English, Italian, Spanish, German...).

**Comment by rmzelle** [comment]
> So I don't think it's useful to mention the InVisu style, which is very different.

Thanks. I'd still like to include that as a template link, since we can use these links for a bunch of different things (such as attribution and maintenance of style families).

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
