### PR TITLE
Always print publisher in APA 6th edition

### PR DESCRIPTION
**Pull request by bwiernik**
Even though the manual says otherwise, I've found that journals (including APA) generally ask for publisher and place when working with APA 6.

Also backport some other features from APA 7.

### CODE REVIEW

**Comment by bwiernik** [comment]
@rmzelle can this be merged?

**Comment by adam3smith** [comment]
The preview shows the no-issue-no-doi style duplicating publisher and location. Could you make sure that's a citeproc-ruby issue and doesn't show up in citeproc-js?

**Comment by bwiernik** [comment]
Fixed that thanks. Wasn't in the habit of checking the the output changed checks.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
