### PR TITLE
Create waterbirds.csl

### PR DESCRIPTION
**Pull request by damnation333**
Per https://forums.zotero.org/discussion/62872/style-request-waterbirds
It says they follow CSE (I only saw after making the style). doesn't perfectly look like CSE anyway.
Free articles: http://www.bioone.org/toc/cowa/38/4

### CODE REVIEW

**Comment by rmzelle** [comment]
(@damnation333, unrelated question: I assume you're currently using http://formatter.citationstyles.org/ before submitting your styles? If so, could you stop doing that for a while for styles you edit with the Visual Editor? I'm trying to see if there is anything else we can fix directly in the Visual Editor)

**Comment by damnation333** [comment]
(@rmzelle
i use the formatter probably in 30% of the styles when I actually do lots of manual edits and copy paste kind of things and I can't be bothered to fix it manually. I won't use it for a while. :)

**Comment by rmzelle** [comment]
(I'm mostly curious to what extent the Visual Editor mixes up the order of the "rel" and "href" attributes on links)

**Comment by rmzelle** [comment]
(please keep using it for styles with lots of manual editing; I'm just want to keep an eye on styles coming straight out of the Visual Editor)

**Comment by rmzelle** [comment]
Thanks!

**Comment by rmzelle** [comment]
:duck:

**Pull request merged**
