### PR TITLE
bursa-uludag-universitesi-egitim-bilimleri-enstitusu.csl

### PR DESCRIPTION
**Pull request by ozhansaglik**
Citation styles for "Bursa Uludag University Egitim Bilimleri Enstitusu"

### CODE REVIEW

**Comment by rmzelle** [comment]
@ozhansaglik, thanks for submitting these styles. Do I understand correctly that these are styles for the

Institute of Natural Sciences
Institute of Health Sciences
Institute of Social Sciences
Institute of Educational Sciences

at Uludağ University? What does "Metinici Atif" mean (#3720)?

And are the citation style guides of the institutes available online? We always try to link to them if possible.

**Comment by ozhansaglik** [comment]
Hello Ritze,

Thanks for your concern. Yes, you understand correctly but we do not have Institute of Natural Sciences, we have Institute of Sciences.

"Metinici Atif" means inline citations. The style of Social Sciences includes footnote citation, "metinici Atif" is for the users who would like to adopt inline citations.

I did add citation guideline links to XML except Educational Sciences. I did notice and add the link #3715.

Here are the links for the citation guidelines:

Institute of Sciences (Fen Bilimleri) = http://www.uludag.edu.tr/dosyalar/fenbilimleri/fen%20bilimleri/FBE_Tez_Yazim_Kurallari_YENI.pdf

Institute of Health Sciences (Saglik Bilimleri) = https://www.uludag.edu.tr/dosyalar/saglikbilimleri/duyuruimages/2018%20Duyurular/SA%C4%9ELIK%20B%C4%B0L%C4%B0MLER%C4%B0%20ENST%C4%B0T%C3%9CS%C3%9C%20TEZ%20YAZIM%20KLAVUZU%202016-BURSA-edited.pdf

Institute of Social Sciences (Sosyal Bilimler) = http://www.uludag.edu.tr/dosyalar/sosyalbilimler/2017%20Duyrular/SBE%20TEZ%20YAZ.%20KIL.(22%20Kas%C4%B1m%202017).pdf

Institute of Educational Sciences (Egitim Bilimleri) = http://www.uludag.edu.tr/dosyalar/egitimbilimleri/tez_yazim_kurallari_Mart_2016_D%C3%BCzeltme.pdf

Thanks for your concern.

**Comment by ozhansaglik** [comment]
@rmzelle Hello Ritze,

We would like our citation styles to be shown as "Bursa Uludağ Üniversitesi Eğitim Bilimleri Enstitüsü". To do this, we did the title as mention above in the Citation Editor. Can you confirm us?

**Comment by rmzelle** [comment]
> We would like our citation styles to be shown as "Bursa Uludağ Üniversitesi Eğitim Bilimleri Enstitüsü". To do this, we did the title as mention above in the Citation Editor. Can you confirm us?

I just updated the style here to use "Bursa Uludağ Üniversitesi - Eğitim Bilimleri Enstitüsü" as the title instead of "Bursa Uludag Universitesi Egitim Bilimleri Enstitusu" (we also always put a hyphen between the name of the institute and the department for these kind of style).

And thanks for getting back to me. I have two more questions:

* Will these styles only be used in Turkish, or also in other languages such as English?
* We'd also like to know which CSL styles you based these ones on. Some of you styles have a "template" link (see e.g. https://github.com/citation-style-language/styles/pull/3717/files#diff-1498ffd39e3439bb9cebcaa05993d1f5R8), but not all of them.

**Comment by ozhansaglik** [comment]
Thank you for your reply. We are pleased with your contribution.

These styles can be used in English, but is there anything we have to do using in other languages?

I have just added the template to other citation styles do not exist the template link.

**Comment by rmzelle** [comment]
> These styles can be used in English, but is there anything we have to do using in other languages?

Thanks. I was asking because CSL styles can be fixed to a single language, but it looks like you wouldn't want that here, then.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
