### PR TITLE
Create american-journal-of-primatology.csl

### PR DESCRIPTION
**Pull request by damnation333**
via https://forums.zotero.org/discussion/63979/style-error-american-journal-of-primatology
I did not review this due to lack of access to the journal. If somebody could check that would be great. Thanks :)

### CODE REVIEW

**Comment by damnation333** [comment]
ah dammit. I should have just edited the independent file. Sorry.
Can somebody now tell me how I add a commit to the here PR to also delete the americaan-journal-of-primatology independent style?

**Comment by rmzelle** [comment]
> I did not review this due to lack of access to the journal. If somebody could check that would be great. Thanks :)

You should be able to access http://onlinelibrary.wiley.com/doi/10.1002/ajp.v79.1/issuetoc (via "Get Sample Copy" in the side bar of http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1098-2345).

> Can somebody now tell me how I add a commit to the PR here to also delete the american-journal-of-primatology independent style?

Go to the branch from which your pull request originates (https://github.com/damnation333/styles/tree/patch-1), look up the style you want to change (https://github.com/damnation333/styles/blob/patch-1/american-journal-of-primatology.csl), and click the trash icon at the top of the file.

**Comment by damnation333** [comment]
Thanks Rintze.
That ain't APA at all, although that's what they say in the guidelines or show in their examples.
The actual papers follow this: [Campbell & Pedersen, 2007] and Campbell JL, Pedersen OK. 2007. The varieties of capitalism and hybrid success. Comparative Political Studies 40:307–332. (florida-entomologist is a great match). I'll work on that in the next days.

**Comment by rmzelle** [comment]
> That ain't APA at all, although that's what they say in the guidelines or show in their examples.

(the sample issue is from January 2017, so it's probably still current)

**Comment by damnation333** [comment]
can be closed. the independent style on the repo, made by adamsmith, is correct. Just Wiley's guidelines are competely different and wrong.

**Comment by adam3smith** [comment]
See my comment on the Zotero thread. I'm pretty sure they changed this

**Comment by adam3smith** [comment]
http://onlinelibrary.wiley.com/doi/10.1002/ajp.22595/epdf
is open access and follows the new format

**Comment by adam3smith** [comment]
@damnation333 trying to follow this -- is the dependent or the independent style correct? Obviously if we can do this via the dependent, that'd be nice.

**Comment by damnation333** [comment]
@adam3smith
The independent style code in here is the right one to go with. It needs its own independent style and is not an APA dependent as initially thought. Thanks

**Comment by adam3smith** [comment]
I haven't looked at this in detail, but wouldn't it be easier to just copy over APA style and change the couple of things that are different?

**Comment by damnation333** [comment]
i think we've gone full circle on this now. Just made it a dependent of APA.

**Pull request merged**
