### PR TITLE
Elsevier 2016 07 25

### PR DESCRIPTION
**Pull request by cpina**

### CODE REVIEW

**Comment by rmzelle** [comment]
See https://github.com/citation-style-language/journals/pull/12 for related PR in "journals" repo.

@cpina, are you aware of any outstanding issues with these PRs, or should they be good to merge once we give them a quick look-over?

**Comment by cpina** [comment]
@rmzelle : should be good to merge

**Comment by rmzelle** [comment]
@adam3smith, I gave both this and the "journals" PR a look-over, and didn't see anything wrong. Will you do the honors?

**Comment by cpina** [comment]
ping :-)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
