### PR TITLE
Create Harvard - Cardiff University DPR Group.csl

### PR DESCRIPTION
**Pull request by V-UK**
Harvard variant for DPR Group

### CODE REVIEW

**Comment by rmzelle** [comment]
@V-UK, hi. What does "DPR" stand for? Is there an online description of your style variant?

**Comment by V-UK** [comment]
Hi rmzelle. It's a variant of Cardiff University Harvard style used in a particular research group within the university (DPR Group)

**Comment by rmzelle** [comment]
Does "DPR" stand for anything? Does the group have its own website?

**Comment by V-UK** [comment]
http://www.cardiff.ac.uk/people/view/81258-ramji-dipak

I can rename it if needed

**Comment by rmzelle** [comment]
Hi. I'm sorry, but we usually don't accept styles into the repository for groups as small as a single research group. See also https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles

**Pull request closed without merging**
