### PR TITLE
Create apa-6th-edition-no-ampersand.csl

### PR DESCRIPTION
**Pull request by bwiernik**
Gotten several requests from authors writing in Spanish for APA 6 without ampersand.

Would we want to just switch the locale for Spanish to use "y" for `and="symbol"`?

### CODE REVIEW

**Comment by adam3smith** [comment]
> Would we want to just switch the locale for Spanish to use "y" for and="symbol"?

Doing this from memory, but I don't think and="symbol" can be localized? I think that should be on the list for CSL 1.0.2 (or wherever that discussion ended up ;).

If I'm wrong, I'd be happy to see this localized, yes, I've gotten the same complaint about APA in Spanish a number of times; I think that's why we created the original option.

**Comment by bwiernik** [comment]
Ah, yes, forgot about that. Once `and="symbol"` is localizable, we can change the locales and move the no-ampersand versions to dependent styles I think.

**Comment by rmzelle** [comment]
So would we want to turn this style into a Spanish one, then?

**Comment by adam3smith** [comment]
> So would we want to turn this style into a Spanish one, then?

I don't think so, no. It's just a particular common scenario for not wanting the &

**Comment by bwiernik** [comment]
Can this be merged?

**Pull request merged**
