### PR TITLE
Update united-states-international-trade-commission.csl

### PR DESCRIPTION
**Pull request by USITC-Zotero**
Additional changes to legal citations. Fixed some missing short author name ("Extra" field). Resolved blog titles.

### CODE REVIEW

**Comment by USITC-Zotero** [comment]
Hi @adam3smith, sorry for being a nuisance, but what's the status of this pull request?

**Comment by adam3smith** [comment]
Sorry, vacations, starting to get through backlog asap

**Comment by adam3smith** [comment]
@USITC-Zotero I'm ready to merge this now, but I noticed the mention of `hearing` in the commit message: Note that as of Zotero 6.0.10 (released July 18th), hearing from Zotero is now mapped to the `hearing` CSL type, which you're not using in the style. Does this affect what you want to do here?

**Comment by USITC-Zotero** [comment]
@adam3smith Thank you for flagging this issue! Our agency is using an older version of Zotero that handles `hearing` as `bill` item types (see CSL code below). The code will be updated shortly to adjust for `hearing` item types.

**Comment by adam3smith** [comment]
Great, thanks -- I've merged here and you can update for the new mappings from Zotero (see https://aurimasv.github.io/z2csl/typeMap.xml for the current map) once you're ready

**Comment by USITC-Zotero** [comment]
@adam3smith excellent, thank you for sharing the new mappings link. Cheers!

**Pull request merged**
