### PR TITLE
OSCOLA.csl: Add publiser info to generic secondary sources (CSL type "article").

### PR DESCRIPTION
**Pull request by StianOby**
An attempt to fix this issue: https://forums.zotero.org/discussion/comment/359163/#Comment_359163

PS: I am not intimately familiar with the code for the OSCOLA CSL style. Thus my technique for fixing the issue may not be optimal. Please double-check my work before committing to master.

### CODE REVIEW

**Comment by StianOby** [comment]
(I suspect that this has slipped through the cracks, therefore tagging @adam3smith – sorry if I'm mistaken.)

**Comment by adam3smith** [comment]
Sorry for the delay here. We actually want `document` for generic going forward. `article` will be used for preprints as of CSL 1.2

**Comment by StianOby** [comment]
Thanks for pointing out this CSL 1.2 issue! AFAIK there are no real differences between generic documents and preprinst (working papers) in OSCOLA. Thus I attempted to fix the CSL 1.2 issue by just adding the "document" item type as well. I hope this is OK.

**Comment by StianOby** [comment]
PS: why is this suddenly not validating? Validator is complaining about a "premature EOF [End Of File] at line 168". But I haven't touched that line...

**Comment by adam3smith** [comment]
Sorry, I jumped the gun there -- document isn't available in 1.0.1

**Pull request merged**
