### PR TITLE
 Remove "DOI"

### PR DESCRIPTION
**Pull request by todoricMDPI**
Hi,

MDPI plan to remove DOI from citation after 20 December 2018. It's ok for us (MDPI team) that we remove this field few days before this date.

Kind regards,
Darko Todoric

### CODE REVIEW

**Comment by rmzelle** [comment]
> MDPI plan to remove DOI from citation after 20 December 2018. It's ok for us (MDPI team) that we remove this field few days before this date.

We can merge this a bit closer to that date. Just comment here to remind us if we forget.

I noticed that you're submitting this style from the "master" branch of your fork. In general, it's easier to follow our instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style, which automatically generates a new branch in your fork based on the most recent version of the style in our repository. That eliminates the need to keep your own "master" branch up to date.

And it's your decision of course, but the trend is to include DOIs in citations (which is widely considered best practice), not to remove them.

**Comment by rmzelle** [comment]
Thanks!

**Comment by RyanJMcCarty** [comment]
MDPI either did not remove DOI's or changed their policy. DOIs should be included as per their online information: https://www.mdpi.com/authors/references .
Can the "remove DOI" change be reverted?

**Comment by rmzelle** [comment]
@todoricMDPI, can you let us know whether MDPI went ahead with removing DOIs?

As @RyanJMcCarty just pointed out, https://www.mdpi.com/authors/references (and the linked to "full MDPI Reference List and Citations Style Guide" at https://res.mdpi.com/data/mdpi_references_guide_v5.pdf (Version 5, 4 September 2018), all still include DOIs.

**Comment by nelsoncardenas** [comment]
@rmzelle this problem is a few years old. Based on the activity of my repo, I think people still need an improvement in the `csl` file. This is the repo I created due to my lack of experience at that time. I have an average of 1 unique visitor per day.

https://github.com/nelsoncardenas/MDPI-Alternative-Style-for-Zotero-Mendeley

**Pull request merged**
