### PR TITLE
Create iranian-journal-of-pharmaceutical-research.csl

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/69984/style-request-ijpr

### CODE REVIEW

**Comment by POBrien333** [comment]
Heya @rmzelle and @adam3smith . Could you review this one? There is another style in the pipeline that I want to base on this one once it's been reviewed. Cheers :)

**Comment by adam3smith** [comment]
Sorry for the delay. I still have some concern about how online articles are displayed. The guidelines have
Morse SS. Factors in the Emergence of Infectious Diseases. Emerg. Infect. Dis. [serial online] 1995 Jan-Mar [cited 1996 Jun 5], 1: [24 screens]. Available from: URL: http://www.cdc.gov/ncidod/EID/eid.htm.

and I don't think the current style is getting that quite right yet. I fixed some things a week ago, but I don't think it's quite there yet. If you can take another look, that'd be great; otherwise I'll try to get to it asap.

**Comment by rmzelle** [comment]
(style metadata looks good)

**Comment by POBrien333** [comment]
Adam, 
That online article example is such a weird one. 1 is the issue, and 24 the volume. What's the "screens" meant to mean? also "available from: URL:..." Very odd.

**Comment by rmzelle** [comment]
> Adam,
> That online article example is such a weird one. 1 is the issue, and 24 the volume. What's the "screens" meant to mean? also "available from: URL:..." Very odd.

It's this article: https://dx.doi.org/10.3201/eid0101.950102. It says "Volume 1, Number 1". My guess is that "24 screens" is the number of paper pages if you print out the online article (which is not very useful or reproducible information, but that's the only thing that I can come up with).

> Btw. Why is the notifications on GitHub gone?

@POBrien333, they work for me. You're not getting any? Or are you missing a particular type of notifications?

**Comment by POBrien333** [comment]
Hmm. The whole little notification blob on the top right beside my profile has been gone for weeks now. Just played around with some settings. I've just assumed it was something with GitHub (or my browser, but the same in all of them, so it must be the settings if it works for you).

**Comment by POBrien333** [comment]
Notifications are back now. Had to activate them all... I wonder why they were shut off in the first place.
thanks :)

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
