### PR TITLE
Create harvard-xi-an-jiaotong-liverpool-univeisity.csl

### PR DESCRIPTION
**Pull request by ous50**

### CODE REVIEW

**Comment by ous50** [comment]
But that's how my university spell.... If I remove that apostrophe, the pronunciation is completely different :(

**Comment by adam3smith** [comment]
Thanks & sorry for the delay.
This style doesn't seem to match the linked style guide very closely yet. Just had a cursory look but:
- Et al shouldn't be used for 3 authors in text
- Et al should be in italics
- Et al should be used in the bibliography
- Year in bibliography should be in parentheses
- Quotation marks instead of italics for the title of a book chapter
- (eds.) should be in parentheses

There's likely more -- could you fix this up to match the style guide a bit more closely, please?

**Comment by adam3smith** [comment]
@ous50 -- please see my question above

**Comment by ous50** [comment]
> @ous50 -- please see my question above

Sorry for the late reply. I was so busy these days and did not notice your opinion. I am looking documentations to modify it.

**Comment by adam3smith** [comment]
Thanks!

**Comment by ous50** [comment]
thanks for your correction :)

**Pull request merged**
