### PR TITLE
Create nations-and-nationalism.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/77386/style-request-nations-and-nationalism-journal
(low-quality template style...)

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks!

**Comment by POBrien333** [comment]
Thank you.

@adam3smith and @rmzelle:
Is there something up with the sync between GitHub and zotero.org/styles?
I was wondering about that the other day already as the style hadn't shown up.

**Comment by rmzelle** [comment]
> Is there something up with the sync between GitHub and zotero.org/styles?
> I was wondering about that the other day already as the style hadn't shown up.

@dstillman, can you take a look?

**Comment by dstillman** [comment]
Sorry about that. Something in our pipeline conflicted with the Sheldon changes. Fixed now, and styles page updated.

**Comment by POBrien333** [comment]
cheers, @dstillman.

**Pull request merged**
