### PR TITLE
Create aims-press.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/78479/format-for-aims-public-health
Keeping this a generic style and will make the dependents for all the journals subsequently.
(very low-quality guidelines and open to interpretation...)

### CODE REVIEW

**Comment by adam3smith** [comment]
Great, thanks. I do have the journal list scraped from their site.

**Comment by POBrien333** [comment]
Great. Send it over. :)

**Comment by adam3smith** [comment]
https://github.com/citation-style-language/journals/tree/master/aims

still needs fields &category and a template

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
