### PR TITLE
Create kerala-journal-of-ophthalmology.csl

### PR DESCRIPTION
**Pull request by DrJohnDavis**
Kerala Journal of Ophthalmology citation style.

### CODE REVIEW

**Comment by DrJohnDavis** [comment]
Changed https to http as there was an error

**Comment by DrJohnDavis** [comment]
Is there a rendering failure ?

**Comment by adam3smith** [comment]
I don't think dependent styles render automated citations -- since you're not actually making any changes to a style, that's not really important, either.

**Comment by DrJohnDavis** [comment]
Thank you.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
