### PR TITLE
Elsevier 2015 01 05

### PR DESCRIPTION
**Pull request by cpina**
Updates dependent Elsevier styles up to 2015-01-05. (replaces #1312)

### CODE REVIEW

**Comment by rmzelle** [comment]
Great, that's much cleaner. I'll review this soon, and I assume @adam3smith will take a look as well.

**Comment by rmzelle** [comment]
renamed-styles.json doesn't validate (http://jsonlint.com/) due to two misplaced commas. Otherwise this looks good to me. The metadata matches https://github.com/citation-style-language/utilities/commit/4a88b38e8a150eacf5c8f3c8ff20384ca2a4776d ?

**Comment by cpina** [comment]
Hi - I've fixed renamed-styles.json and yes, the metadata matches citation-styles-language/utilities.

**Comment by rmzelle** [comment]
@adam3smith, can I leave this for you to merge?

**Comment by adam3smith** [comment]
yes, will look tonight.

**Comment by adam3smith** [comment]
Thanks, looks great!

**Comment by rmzelle** [comment]
Awesomesauce!

**Pull request merged**
