### PR TITLE
Create mbts-fullnote-bibliography.csl

### PR DESCRIPTION
**Pull request by gq9000**
Hello, I have created a new style for use at Midwestern Baptist Theological Seminary (https://www.mbts.edu/). It is based on Chicago. Thank you!

### CODE REVIEW

**Comment by adam3smith** [comment]
The style guide you link to is for blogs and doesn't say anything about references -- is the citation style described somewhere you could link to? How is it different from Chicago Manual?

**Comment by gq9000** [comment]
Hello,
thanks for your message. You're right, that's the wrong link. I just
checked and it looks like this style guide is not posted online. I just
have the PDF from the school. It's very similar to Chicago but there's some
minor differences for several types such as journal articles, encyclopedia
and dictionary entries, etc. Mostly punctuation and placement of some
locators. If you like, I can send you the PDF.

Sincerely,
J Brown

**Comment by adam3smith** [comment]
Could you upload the PDF here so we have some point of reference? It's not ideal to have a style up where we can't access documentation in case someone reports issues.

**Comment by gq9000** [comment]
Okay, I uploaded the file here:
https://github.com/gq9000/styles/blob/master/The-Midwestern-Style-Manual-Second-Edition-Revised-110718.pdf

Thanks.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
