### PR TITLE
Anabases

### PR DESCRIPTION
**Pull request by NMonteix**

### CODE REVIEW

**Comment by rmzelle** [comment]
@NMonteix, can you resubmit this style by following the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3a-submitting-a-new-style?

If you follow those steps, you should automatically get a new branch in your fork that is up-to-date with our master branch. It should be simpler for you, and it avoids having merge commits in the pull request as you have now.

**Comment by adam3smith** [comment]
@rmzelle -- given the ease of squashing, why do the merge commits matter?

**Comment by rmzelle** [comment]
@adam3smith, ah, right, so we're probably okay with this. @NMonteix, following our instructions for future pull requests should still make things easier for you.

**Comment by NMonteix** [comment]
@rmzelle I thought I did... But I might have been doing it from my fork... Sorry for that

**Comment by rmzelle** [comment]
Ah, right, your pull request was from your "Anabases" branch. Still, there isn't really a need to include any merge commits.

Thanks!

**Comment by NMonteix** [comment]
I wish I could understand how not to include those when creating a PR from my fork. They're like sticky...
Thanks to you!

**Comment by rmzelle** [comment]
> I wish I could understand how not to include those when creating a PR from my fork. They're like sticky...

Yes, you can't easily exclude them. In general, it's easiest to always start in our repository and edit/add the style there. That will always give you an up to date branch in your fork.

**Pull request merged**
