### PR TITLE
Create bppb.csl

### PR DESCRIPTION
**Pull request by harukin-bppb**
CSL for Biophysics and Physicobiology

### CODE REVIEW

**Comment by adam3smith** [comment]
@harukin-bppb please don't touch this for now. You are generating a bunch of confusing notifications

**Comment by harukin-bppb** [comment]
OK. I understand.
Haruki Nakamura

----- Original Message -----
> From: Sebastian Karcher ***@***.***>
> To: citation-style-language/styles ***@***.***>
> Cc: harukin-bppb ***@***.***>,Mention ***@***.***>
> Date: 2021-05-17 07:53:59
> Subject: Re: [citation-style-language/styles] Create bppb.csl (#5452)
> 
> @harukin-bppb please don't touch this for now. You are generating a bunch of confusing notifications
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/5452#issuecomment-841889240
> 

================================================
Haruki Nakamura, Doctor of Science
e-mail: ***@***.***

**Comment by rmzelle** [comment]
@harukin-bppb, thanks! It looks like you based this CSL style on that for Nature (nature.csl)? Please confirm whether this is the case, so we can add a "template" link (see https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#8---template-link).

**Comment by harukin-bppb** [comment]
Dear Rintze M. Zelle,

> @harukin-bppb, thanks! It looks like you based this CSL style on that for Nature (nature.csl)? 

I became an Editor-in-Chief of BPPB about a year ago, and historically, I hear that our citation style was decided several years ago. I do not know the correct history how it was decided.

When we have recently tried to make our CSL, we find that the BPPB style is similar to Nature. Therefore, we have referred the style of Nature to construct bppb.csl.

> Please confirm whether this is the case, so we can add a "template" link (see https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#8---template-link).

So, actually "this is the case."
Please add a "template" link.

We would greatly appreciate your kind support.
When bppb.csl is finally fixed, please let us know.

Thank you in advance,

With the best regards,
Haruki Nakamura
Editor-in-Chief of Biophysics and Physicobiology (BPPB)

----- Original Message -----
> From: Rintze M. Zelle ***@***.***>
> To: citation-style-language/styles ***@***.***>
> Cc: harukin-bppb ***@***.***>,Mention ***@***.***>
> Date: 2021-05-19 12:45:55
> Subject: Re: [citation-style-language/styles] Create bppb.csl (#5452)
> 
> @harukin-bppb, thanks! It looks like you based this CSL style on that for Nature (nature.csl)? Please confirm whether this is the case, so we can add a "template" link (see https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#8---template-link).
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/5452#issuecomment-843723435
> 

================================================
Haruki Nakamura, Doctor of Science
Editor-in-Chief of Biophysics and Physicobiology (BPPB)
e-mail: ***@***.***

**Comment by rmzelle** [comment]
@harukin-bppb, thanks! I added the style to the repository. For future contributions, please only create a single pull request per style (if the initial submission needs corrections, those can be made in the initial pull request).

**Comment by harukin-bppb** [comment]
Dear Rintze M. Zelle,

Thank you very much for your kind support to finalize and add our CSL to your repository.
I confirm that "biophysics-and-physicobiology.csl" appears in the list of "citation-style-language/styles", and that the CSL correctly works on my own PC.

By the way, I have another question.
When I try to access
"http://www.zotero.org/styles/biophysics-and-physicobiology",
I have only a reply: "Style not found", and cannot obtain the CSL file.

Does it mean that we have to wait for a while until "biophysics-and-physicobiology.csl" is registered at Zotero?
Or, should I make some other inquiry to Zotero, so that http://www.zotero.org/styles/biophysics-and-physicobiology becomes active?

Thank you in advance.
With the best regards,
Haruki Nakamura
Editor-in-Chief of Biophysics and Physicobiology (BPPB)


----- Original Message -----
> From: Rintze M. Zelle ***@***.***>
> To: citation-style-language/styles ***@***.***>
> Cc: harukin-bppb ***@***.***>,Mention ***@***.***>
> Date: 2021-05-20 12:26:55
> Subject: Re: [citation-style-language/styles] Create bppb.csl (#5452)
> 
> @harukin-bppb, thanks! I added the style to the repository. For future contributions, please only create a single pull request per style (if the initial submission needs corrections, those can be made in the initial pull request).
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/5452#issuecomment-844656791
> 

================================================
Haruki Nakamura, Doctor of Science
Editor-in-Chief of Biophysics and Physicobiology
e-mail: ***@***.***

**Comment by adam3smith** [comment]
The Zotero repository just takes some time to update. The style is available there now.

**Comment by harukin-bppb** [comment]
Dear Sebastian Karcher,

I now confirm our CSL on the Zotero repository.
Thanks a lot.

With the best regards,
Haruki Nakamura
Editor-in-Chief of Biophysics and Physicobiology (BPPB)

----- Original Message -----
> From: Sebastian Karcher ***@***.***>
> To: citation-style-language/styles ***@***.***>
> Cc: harukin-bppb ***@***.***>,Mention ***@***.***>
> Date: 2021-05-20 21:40:29
> Subject: Re: [citation-style-language/styles] Create bppb.csl (#5452)
> 
> The Zotero repository just takes some time to update. The style is available there now.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/citation-style-language/styles/pull/5452#issuecomment-845073625
> 

================================================
Haruki Nakamura, Doctor of Science
Editor-in-Chief of Biophysics and Physicobiology
e-mail: ***@***.***

**Pull request merged**
