### PR TITLE
Update environmental-microbiology.csl

### PR DESCRIPTION
**Pull request by clauspelikan**
EM line line citation should use italic "et al." (http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291462-2920/homepage/ForAuthors.html)

Thanks!

### CODE REVIEW

**Comment by and3k** [comment]
@clauspelikan, it actually should be 

```
<contributor>
  <name>Connor Skennerton</name>
</contributor>
<contributor>
  <name>Claus Pelikan</name>
</contributor>
```

not

```
<contributor>
  <name>Connor Skennerton</name>
  <name>Claus Pelikan</name>
</contributor>
```
 
;)

**Comment by adam3smith** [comment]
you can update your pull request by using the pencil icon here (the actual change in the style content is good as is). https://github.com/clauspelikan/styles/blob/patch-1/environmental-microbiology.csl
Let us know when you're done.

Thanks @and3k for helping out.

**Comment by and3k** [comment]
It’s fixed :)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
