### PR TITLE
Create gost-r-7-0-5-2008-numeric-alphabetical-inevo.csl

### PR DESCRIPTION
**Pull request by AlexanderSavenkov**
Adding new style for InEvo series of articles.

### CODE REVIEW

**Review by AlexanderSavenkov — COMMENTED** [review]
removed duplicate macro

**Comment by AlexanderSavenkov** [comment]
removed duplicate macro

**Review by AlexanderSavenkov — COMMENTED** [review]
removed unused macro

**Comment by rmzelle** [comment]
@AlexanderSavenkov, thanks. Could you point us to the website of this journal and its instructions to authors?

**Comment by AlexanderSavenkov** [comment]
Hello Rintze,

There’s no specific journal for this style, I’m just trying to update the gost-r-7-0-5-2008-numeric-alphabetica style with default Russian language and a number of improvements.

Let me know if I’m doing it the wrong way, please – I’m new to the styles system.

Regards,
Alexander

**Comment by rmzelle** [comment]
@AlexanderSavenkov, if you're trying to improve the existing style, please follow the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style and change the original style (https://github.com/citation-style-language/styles/blob/master/gost-r-7-0-5-2008-numeric-alphabetical.csl). Thanks!

**Comment by adam3smith** [comment]
Closing this for inactivity. We remain very interested in improvements to the main GOST style, so please do submit them as described above if you get a chance

**Pull request closed without merging**
