### PR TITLE
Update institut-francais-darcheologie-orientale-arab-studies.csl

### PR DESCRIPTION
**Pull request by NicolasSouchon**
Major citation style update related to 2022 publishing guidelines update

### CODE REVIEW

**Comment by NicolasSouchon** [comment]
@bwiernik I didn't know I could do that, thanks for the advice!

On the other hand, using the API with this style and the three others updated yesterday, I found that my queries results were using the old version of this style and not the current one (it has happened before: https://forums.zotero.org/discussion/85063)

**Comment by NicolasSouchon** [comment]
The versions on Zotero.org/styles are the new ones (2022-04-13) and the old ones are no longer in the list. Everything works perfectly when adding the styles to Zotero, only the API displays a result corresponding to the old version ([here](https://api.zotero.org/groups/2470397/items?tag=TNS_Masson-Berghoff2021&format=bib&style=institut-francais-darcheologie-orientale-etudes-arabes), the mention OLA 300 should not appear anymore)

**Comment by bwiernik** [comment]
@dstillman Whats the update schedule for the API vs the style repository?

**Comment by NicolasSouchon** [comment]
The problem was solved by @dstillman. For details regarding this issue, see [this comment](https://forums.zotero.org/discussion/comment/406783/#Comment_406783) on the Zotero forum. @bwiernik, thank you for your help

**Pull request merged**
