### PR TITLE
Create scientific-review-engineering-and-environmental-sciences.csl

### PR DESCRIPTION
**Pull request by libora**
SREaES style is based on "APA no ampersand" with this changes:
1. "et al." from three authors
2. italicise with "." (without space between italicised letters)
The guide for authors only states "use APA style", but the comparison of published articles with outputs from APA style leads to changes of APA style described above.  Unfortunately, available papers on web pages of journal do not use the same format for volume and issue; so the style template for SREaES does not change this. I also did not change prefix "https://doi.org/" for DOI, though the published articles used to prefix "doi:".

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks!

**Comment by rmzelle** [comment]
@libora, this journal is bilingual, right? I saw some Polish and English articles.

**Comment by libora** [comment]
@rmzelle yes

**Comment by rmzelle** [comment]
@libora, okay, thanks. I added an (XML) comment to that effect: https://github.com/citation-style-language/styles/commit/1be95ff8698bb6f2d6857e638f86f4917d9e47d9

**Comment by libora** [comment]
Similar comments can be added to a lot of journals from East Europe
For example, journals Vodohospodářské technicko-ekonomické informace (vodohospodarske-technicko-ekonomicke-informace.csl for Czech and Slovak language and vodohospodarske-technicko-ekonomicke-informace-en.csl for English) and Podzemná voda (podzemna-voda.csl) published in Czech, Slovak and English language.

**Comment by rmzelle** [comment]
> vodohospodarske-technicko-ekonomicke-informace.csl for Czech and Slovak language

That CSL style is currently fixed to Czech, though (see https://github.com/citation-style-language/styles/blob/master/vodohospodarske-technicko-ekonomicke-informace.csl). If this CSL style can also be used in Slovak, we should probably delete its `default-locale`.

> podzemna-voda.csl) publish in Czech, Slovak and English language.

Similarly, this one is fixed to Slovak currently (https://github.com/citation-style-language/styles/blob/master/podzemna-voda.csl).

**Pull request merged**
