### PR TITLE
Update renewable-agriculture-and-food-systems.csl

### PR DESCRIPTION
**Pull request by vidotto**
- now the last author is shown as the first ones (e.g. "Wainer, K., Genty, D., Blamart, D., Bar-Matthews, M., Quinif, Y., and Plagnes, V. 2013..."
-  added issue of a journal volume in brackets

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! What are these changes based on? Looking at https://www.cambridge.org/core/journals/renewable-agriculture-and-food-systems/information/instructions-contributors
I *am* seeing the authors as you have them, but I'm not seeing issue numbers for journals nor a space between "p." and the page range for chapters

**Comment by vidotto** [comment]
Yes, you are right. In the examples reported in the instructions for contributors the issue for journals is not reported, as well as page range (chapters) and space after "p."
Nevertheless, I found these changes in several recent paper published in the journal...Unfortunately, it is quite common that there are differences between the instructions for contributors and what it is actually published. Usually I prefer to be more adherent to the format adopted in recent papers of a journal, even though I do not know what should be the correct way to proceed. Other journals offer examples of references in their instructions but specify aldo that authors should in any case take as "official" format what is published in recent papers. 
We can also ask the journal to update the instructions (I never did that, but we can try).

Inviato da iPhone

**Comment by adam3smith** [comment]
> Nevertheless, I found these changes in several recent paper published in the journal...Unfortunately, it is quite common that there are differences between the instructions for contributors and what it is actually published. Usually I prefer to be more adherent to the format adopted in recent papers of a journal

Yes, we know all about that trust me ;) -- and we also generally prefer what's published to the instructions, so will take this as is, thank you for clarifying.

**Comment by rmzelle** [comment]
> I found these changes in several recent paper published in the journal

Could you give us a link to one or two recent papers that show these changes?

**Comment by rmzelle** [comment]
Also, thanks!

**Comment by vidotto** [comment]
There are some inconsistencies among papers, indeed, but these involve mainly the indication of issue of journals (sometimes present, sometimes not, even within the same paper).

Here some recent papers (open access)
https://www.cambridge.org/core/services/aop-cambridge-core/content/view/5D62EAE3BDC8067192D6E10AD791FFEE/S1742170517000291a.pdf/trouble_with_temporary_impacts_and_pitfalls_of_a_meanwhile_community_garden_in_wythenshawe_south_manchester.pdf

In the following there is no issue of journals:
https://www.cambridge.org/core/services/aop-cambridge-core/content/view/DCEC123D3B678CF7B1B22B770F3A46AB/S174217051700031Xa.pdf/propelled_abrasive_grit_applications_for_weed_management_in_transitional_corn_grain_production.pdf

https://www.cambridge.org/core/services/aop-cambridge-core/content/view/732DAC57E92E1C9EFC5A451F7EAF454A/S1742170517000096a.pdf/trouble_with_cover_crops_farmers_experiences_with_overcoming_barriers_to_adoption.pdf

Again, no issue of journals here (except one case):
https://www.cambridge.org/core/services/aop-cambridge-core/content/view/B3A73D494DC9D7615E85350A6D15FB8C/S1742170516000120a.pdf/establishment_of_apple_orchards_as_temperate_forest_garden_systems_and_their_impact_on_indigenous_bacterial_and_fungal_population_abundance_in_southern_ontario_canada.pdf

**Comment by rmzelle** [comment]
Great, thanks again!

**Pull request merged**
