### PR TITLE
UTM Thesis

### PR DESCRIPTION
**Pull request by mahdimak2000**

### CODE REVIEW

**Comment by rmzelle** [comment]
Does the Universiti Teknologi Malaysia have a webpage with a description of this citation format?

**Comment by mahdimak2000** [comment]
Hello and goody day
yes, UTM has thesis manual which can be download from UTM website through the link below. at page 21-22 of the 2015 manual you can see the citation style. 
http://www.sps.utm.my/sps/?option=com_content&task=view&id=279&Itemid=

thanks alot
 


     On Friday, October 9, 2015 10:40 AM, Rintze M. Zelle <notifications@github.com> wrote:
   

 Does the Universiti Teknologi Malaysia have a webpage with a description of this citation format?—

**Comment by rmzelle** [comment]
Thanks. That URL seems to be truncated, though (there should be something after "Itemid="). http://www.sps.utm.my/ also doesn't load for me, while I can visit http://utm.my/ just fine.

To accept this style, it needs to abide to all the rules in
https://github.com/citation-style-language/styles/wiki/Style-Requirements. The file also needs to be renamed from "UTM Thesis" to something like "harvard-universiti-teknologi-malaysia.csl".

**Comment by rmzelle** [comment]
@mahdimak2000, I went ahead and made the required changes in #2342, and accepted the style. A belated thanks!

**Pull request closed without merging**
