### PR TITLE
Create china-national-standard-gb-t-7714-2015-numeric.csl

### PR DESCRIPTION
**Pull request by buffalo-d**
"GB/T 7714-2015" is a national standard/guidelines of China for bibliographic references and citations to information resources. It is widely used in academic journals and papers in China mainland . It is drafted with reference to the international standard ISO 690:2010(E) and its previous version is "GB/T 7714-2005".

### CODE REVIEW

**Comment by buffalo-d** [comment]
Hi, everyone. 
This is my first submission. There is a unused macro in this csl. 
Can anyone tell me how to fix it?

**Comment by fredericky123** [comment]
请问有“编者-年”的版本吗？该版本能否实现根据语言自动插入“et al.”或“等”？

**Comment by fredericky123** [comment]
另外，该版本还未正式发布是吗？在官方收录库看不到呢

**Comment by buffalo-d** [comment]
> 请问有“编者-年”的版本吗？该版本能否实现根据语言自动插入“et al.”或“等”？

我没有做“编者-年”的版本，据我所知国内期刊或学位论文几乎没有用“编者-年”的。如果要求的人多可以考虑做一个。

csl 不是编程语言，能不能实现多语言切换要看软件采用啥处理核心。目前 zotero 用的是不支持多语言的内核，所以不能实现根据语言自动插入“et al.”或“等”。

**Comment by buffalo-d** [comment]
> 另外，该版本还未正式发布是吗？在官方收录库看不到呢

还没审核通过，也不知道啥时候会审核。可以自己下载，然后手动添加到 zotero 样式库里面使用。

**Comment by fredericky123** [comment]
> > @fredericky123  另外，该版本还未正式发布是吗？在官方收录库看不到呢
> 
> 还没审核通过，也不知道啥时候会审核。可以自己下载，然后手动添加到 zotero 样式库里面使用。

好的，辛苦了，感谢付出！

**Comment by adam3smith** [comment]
A little hard for me to review because the styleguide is in Chinese, but the parts I was able to check look good -- thanks!

**Comment by adam3smith** [comment]
@rmzelle We have three older versions of this standard online, named "Chinese Std GB/T 7714-2005"
I think "Chinese National Standard" makes more sense, but don't have particularly strong views except that they should probably all be called the same. Views?

**Comment by buffalo-d** [comment]
> @rmzelle We have three older versions of this standard online, named "Chinese Std GB/T 7714-2005"
> I think "Chinese National Standard" makes more sense, but don't have particularly strong views except that they should probably all be called the same. Views?

Hi, @adam3smith . Since the 1980s, the Standardization Administration of China has made three standards about bibliographic references, in chronological order: GB/T 7714-87, GB/T 7714-2005 and GB/T 7714-2015. And it was clearly stated that the latter should replace the previous one.

In addition, the Chinese meaning of "GB" in the standard number "GB/T 7714" is "national standard", and the letter "T" means "recommended/non-mandatory standard". So I believe it's okay to call them all "national standard", and it might be more accurate to call them "national recommended standard"

**Comment by buffalo-d** [comment]
> This issue hasn't seen any activity in the past 30 days. It will be automatically closed if no further activity occurs in the next two weeks.

Hi @adam3smith, does this mean that my submission has been rejected ?

**Comment by fredericky123** [comment]
为啥被reject了，还等着收入正式目录呢 醉了

**Comment by buffalo-d** [comment]
> 为啥被reject了，还等着收入正式目录呢 醉了

@fredericky123，俺发现机器人把这个提交标记成 waiting，还以为到期不被收录就关闭了... 没想到留言之后 waiting 标签就取消了。按说格式应该没问题，只是不知道还要多久才收录。

**Comment by rmzelle** [comment]
Sorry for not chiming in sooner. I think I'd prefer "China National Standard GB/T 7714-2015 (numeric, Chinese)" (and "china-national-standard-gb-t-7714-2015-numeric.csl" as file name).

We currently have styles name like "Chinese Std GB/T 7714-1987 (numeric, Chinese)" (https://www.zotero.org/styles?q=7714), which means that people searching for "China" won't find the styles. And we should spell out "National Standard" instead of using the abbreviated "Std". Adding "recommended" would make the style titles rather long. For the file name, there isn't a reason to include the locale, especially since we currently only have (simplified) Chinese versions. @adam3smith, will you make the change if you agree (also for the titles of the existing styles)?

**Comment by buffalo-d** [comment]
em~

**Comment by fredericky123** [comment]
when the submission will be accepted?

**Comment by buffalo-d** [comment]
@adam3smith , @rmzelle. Is there any problem with this submission? could we solve it?

**Comment by rmzelle** [comment]
Thanks! Apologies for the very long wait. (@adam3smith, I haven't updated the file names of the older styles, as Dan prefers style IDs to remain as static as possible)

**Comment by jiewuza** [comment]
@buffalo-d 我也碰到“et al.”或“等”这个问题。你说`目前 zotero 用的是不支持多语言的内核`，我想再问一下，你知道有其他东西可以解决这个问题吗？

**Comment by buffalo-d** [comment]
> @buffalo-d 我也碰到“et al.”或“等”这个问题。你说`目前 zotero 用的是不支持多语言的内核`，我想再问一下，你知道有其他东西可以解决这个问题吗？
> 
> 另外，我搜到#4484
> 然后我看了apa.csl，它里面好多locale的判断

文档编辑完成之后，在word里面查找英文文献列表中的‘等‘，全部替换成’et al.‘ 。用利用通配符，也还算是方便的：

查找：(\[[0-9]{1,}\]^t*[a-zA-Z], )等.
替换：\1 et at.

实际上，上面的查找替换规则不是唯一的。我写过一个可以完成上面的查找替换操作的word 宏，发给过几个网友，他们在知呼上好像都写了教程。如果你不熟悉通配符，在网上搜一下用宏也可以。

**Comment by buffalo-d** [comment]
> @buffalo-d 我也碰到“et al.”或“等”这个问题。你说`目前 zotero 用的是不支持多语言的内核`，我想再问一下，你知道有其他东西可以解决这个问题吗？
> 
> 另外，我搜到#4484
> 然后我看了apa.csl，它里面好多locale的判断

#4484 的 locale 不是判断，只是指定不同的本地关键字。并不能同时使用荷兰语的 'e.a.' 和英语的'et al'。

**Comment by buffalo-d** [comment]
文档编辑完成之后，在word里面查找英文文献列表中的‘等‘替换成’et al.‘ 用利用通配符，也还算是方便的。我写过一个word 宏，发给过几个人，他们在知呼上好像都写了教程。如果你不熟悉通配符，在网上搜一下也就有了。

Sent from Mail for Windows 10

**Comment by fredericky123** [comment]
@buffalo-d 大神 能否编辑一个编者-年的2015版本，现在zotero自带的那个2005编者-年有错误，进行参考文献格式转换时总是出现错误，非常感谢！

**Comment by buffalo-d** [comment]
> @buffalo-d 大神 能否编辑一个编者-年的2015版本，现在zotero自带的那个2005编者-年有错误，进行参考文献格式转换时总是出现错误，非常感谢！
@fredericky123  好的。但是，最近比较忙，3月份以后我编辑一个编者-年的。
另，我只是普通网民，不是大神。哈哈～

**Comment by fredericky123** [comment]
哈哈 好的 期待~

**Comment by buffalo-d** [comment]
> 请问有“编者-年”的版本吗？该版本能否实现根据语言自动插入“et al.”或“等”？

@fredericky123 , https://github.com/citation-style-language/styles/pull/4611

**Comment by fredericky123** [comment]
Wow, thanks so much!

**Comment by guanhao-g** [comment]
您好！非常感谢您的工作。但是现在在numeric的注释中，如果加入页码，则页码会显示在方括号内：
图片
而根据7714-2015的规则，页码应显示在方括号后，不带“p”：
图片
不知是否可以处理这一问题？感谢！

**Comment by buffalo-d** [comment]
> 您好！非常感谢您的工作。但是现在在numeric的注释中，如果加入页码，则页码会显示在方括号内：
> 图片
> 而根据7714-2015的规则，页码应显示在方括号后，不带“p”：
> 图片
> 不知是否可以处理这一问题？感谢！

编写这个cls文件的时候，对问题我特别研究过，我的结论是目前应该没法通过 cls 解决。但是采用类似于 "et al" 问题的解决方式，定稿后在Word里面利用通配符替换，所以写成了你截图中的样子，目的就是方便写正则。

**Comment by guanhao-g** [comment]
好的，十分感谢！ On 09/22/2020 11:23, Buffalo_D wrote: 您好！非常感谢您的工作。但是现在在numeric的注释中，如果加入页码，则页码会显示在方括号内： 而根据7714-2015的规则，页码应显示在方括号后，不带“p”： 不知是否可以处理这一问题？感谢！ 编写这个cls文件的时候，对问题我特别研究过，我的结论是目前应该没法通过 cls 解决。但是采用类似于 "et al" 问题的解决方式，定稿后在Word里面利用通配符替换，所以写成了你截图中的样子，目的就是方便写正则。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
