### PR TITLE
Create elsevier-american-chemical-society.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/101854/citation-style-request-acs-numbered-style-style-9#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
Do you recall if there was any reason you didn't make this superscript?

**Comment by POBrien333** [comment]
The example they give in that .pdf is non-superscript:
`Example: ...preparing N-(p-nitroaryl)amides (2).`
{Source, page 10)[https://booksite.elsevier.com/9780081019375/content/Elsevier%20Standard%20Reference%20Styles.pdf]

**Comment by adam3smith** [comment]
Right, that confused me too. Let's leave it as this one for now. If we do need the other ones, they'd get the -superscript and -author-date qualifiers

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
