### PR TITLE
Clara-revue-style-fr.csl

### PR DESCRIPTION
**Pull request by clararevue**
Citation style for the scientific journal Clara: Recherche/Architecture

### CODE REVIEW

**Comment by rmzelle** [comment]
Could you change the file name to "clara-recherche-architecture.csl", the title to "CLARA Recherche/Architecture (French)", and update the style ID and "self" link to match the file name ("http://www.zotero.org/styles/clara-recherche-architecture")? Also please delete the line `<category field="generic-base"/>`.

Is the style format described online anywhere? The website refers to the "Directives aux auteurs" in one or two places with the link http://clararevue.ulb.be/OJS/index.php/CLARA/about/submissions#authorGuidelines, but that webpage doesn't seem to contain any author guidelines.

**Comment by rmzelle** [comment]
Merci!

**Comment by clararevue** [comment]
What do I do next to make the style available?

**Comment by clararevue** [comment]
Dear @rmzelle merci à toi! the style is not yet available from the zotero site. Do you know what is missing or what step is still required?

**Comment by rmzelle** [comment]
It's online now in the Zotero Style Repository. Sometimes it takes a while.

**Pull request merged**
