### PR TITLE
Create jsbm.csl

### PR DESCRIPTION
**Pull request by spaetz**
Based on apa, no ampersand.
Description of style here:
https://onlinelibrary.wiley.com/page/journal/1540627x/homepage/forauthors.html

### CODE REVIEW

**Comment by adam3smith** [comment]
I'm not sure APA is a good style to start from actually. Seeing lots of differences with the author guidelines. See e.g. the format for book chapters & compare to the Mares sample generated above:

Kaslow, Florence W., and S. Kaslow (1992). 'The Family that Works Together: Special Problems of 
Family Businesses,' in Work, Families, and Organizations. Ed. S. Zedeck. San Francisco, Calif.: Jossey Bass, 312-361.

Almost every element (author names, quotation marks, title case, location and formatting of editor, location and formatting of page number...) is different.

**Comment by spaetz** [comment]
> 
> 
> I'm not sure APA is a good style to start from actually. Seeing lots of differences with the author guidelines. See e.g. the format for book chapters & compare to the Mares sample generated above:
> 
> Kaslow, Florence W., and S. Kaslow (1992). 'The Family that Works Together: Special Problems of
> Family Businesses,' in Work, Families, and Organizations. Ed. S. Zedeck. San Francisco, Calif.: Jossey Bass, 312-361.
> 
> Almost every element (author names, quotation marks, title case, location and formatting of editor, location and formatting of page number...) is different.

Mmmh, I had checked predominantly journal articles and books. It is true that book chapters seem to be weird. The APA-no-ampersand style seemed to get as close as it could. In that case, this goes over my head, I am sorry to say.

**Comment by rmzelle** [comment]
Thanks!

**Comment by spaetz** [comment]
Thanks for merging. I take that as an encouragement to further improve the style 😃.

**Pull request merged**
