### PR TITLE
Switch Chicago Manual to 17th ed.

### PR DESCRIPTION
**Pull request by adam3smith**
General approach: Move over all styles to 17th edition, keep the three
most popular (not, full note, author-date) available for 16th
edition. Delete "no ibid" styles and move them to new default format via
rename.json. Add new styles as exceptions to unused macros in automated tests.

Changes
- Default to "just author" short form instead of ibid. Keep ibid styles
around.
- Switch DOI to new format
- Better styling for webpages and blogs
- Use guidelines for maps & artwork, including where not formally
published
- Author-date: add year to dates for newspapers & magazines
- Author-date: remove space between volume:pages
- Some other small fixes

Oxford Studies in Ancient Philosophy: adjust template

### CODE REVIEW

**Comment by rmzelle** [comment]
(I'll take a look soon)

**Comment by rmzelle** [comment]
So, since Git is confused by some of the deletions/additions, just to keep track of things myself, we currently have:

> Chicago Manual of Style 16th edition (author-date, Basque)
Chicago Manual of Style 16th edition (author-date, French)
Chicago Manual of Style 16th edition (author-date, German)
Chicago Manual of Style 16th edition (author-date)
Chicago Manual of Style 16th edition (figures and illustrations)
Chicago Manual of Style 16th edition (full note, French)
Chicago Manual of Style 16th edition (full note, no Ibid.)
Chicago Manual of Style 16th edition (full note)
Chicago Manual of Style 16th edition (library list)
Chicago Manual of Style 16th edition (note, annotated bibliography)
Chicago Manual of Style 16th edition (note, no Ibid.)
Chicago Manual of Style 16th edition (note)

as well as

> Taylor & Francis - Chicago F
Taylor & Francis - Chicago Manual of Style (author-date)
Taylor & Francis - Chicago Manual of Style (note)

All independents. Following our discussion at https://github.com/citation-style-language/styles/pull/2962#issuecomment-331029230, this PR now:

* gives new "16th-edition" style IDs to the three most popular CMoS styles
  * Chicago Manual of Style 16th edition (author-date)
  * Chicago Manual of Style 16th edition (full note)
  * Chicago Manual of Style 16th edition (note)
* updates the following 16th ed. styles to 17th ed. (same style ID)
  * Chicago Manual of Style 16th edition (note, annotated bibliography)
  * Chicago Manual of Style 16th edition (author-date)
  * Chicago Manual of Style 16th edition (full note)
  * Chicago Manual of Style 16th edition (note)
  * Chicago Manual of Style 16th edition (library list)
* deletes the following "no Ibid." styles, since 17th ed. doesn't ever use "Ibid."
  * Chicago Manual of Style 16th edition (full note, no Ibid.)
  * Chicago Manual of Style 16th edition (note, no Ibid.)
* redirects users of the old 16th ed. "no Ibid." styles to their regular 17th ed. equivalents
* adds "Ibid." styles for 17th ed.
  * Chicago Manual of Style 17th edition (full note with ibid)
  * Chicago Manual of Style 17th edition (note with ibid)
* redirects "Oxford Studies in Ancient Philosophy" from "no-ibid" (16th ed.) to regular 17th style

Notes:
* "ibid" should be spelled "Ibid." in style titles (2x)
* Can we also upgrade "Chicago Manual of Style 16th edition (figures and illustrations)"?
* You're not touching the localized versions, which is fine.
* I assume T&F is on their own schedule?

**Comment by rmzelle** [comment]
So, if you could change
 
* Chicago Manual of Style 17th edition (full note with ibid)
* Chicago Manual of Style 17th edition (note with ibid)

to

* Chicago Manual of Style 17th edition (full note, with Ibid.)
* Chicago Manual of Style 17th edition (note, with Ibid.)

with comma and other punctuation, this looks good to merge. Do you also want to check the timestamps? Some styles still have one from 2012.

**Comment by rmzelle** [comment]
https://www.zotero.org/styles?q=id%3Asodertorns-hogskola-harvard-ibid should also be renamed "Ibid.", but we fix that up in https://github.com/citation-style-language/styles/pull/3020.

**Comment by rmzelle** [comment]
@adam3smith, please do the honors!

(if it's easy to check, could you see if chicago-figures.csl stays the same for the 17th edition?)

**Comment by adam3smith** [comment]
I can check on the figures style -- it's a completely different style, so haven't checked. Same for the localized versions -- they're closer to the codebase, but still quite distinct and I'm not sure what updating would entail. And yes, I'd assume T&F will change at a later date, will try to keep an eye out.

**Comment by rmzelle** [comment]
> I can check on the figures style -- it's a completely different style, so haven't checked.

Yes, I figured maybe you knew whether CMoS 17th keeps the same instructions for formatting figures, in which case we can just change the title to "17th". If it's not trivial to figure out, just leave it.

**Comment by rmzelle** [comment]
Also, thanks a lot!

**Comment by stakats** [comment]
Thanks for this! Found one small issue: page numbers are always required now that ibid is discouraged ([CMS 14.34](http://www.chicagomanualofstyle.org/book/ed17/part3/ch14/psec034.html)). So even when a citation immediately repeats with the same page number, e.g. "Zelle, 18", the next citation should also say "Zelle, 18". The current implementation omits the page number.

**Comment by rmzelle** [comment]
@adam3smith, if you have a chance to confirm this, can you create an issue (or directly fix it)?

**Pull request merged**
