### PR TITLE
Create ephemerides-theologicae-lovanienses.csl

### PR DESCRIPTION
**Pull request by carljohanberglund**

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by adam3smith** [comment]
@carljohanberglund The style looks good, but we're waiting on input for you on whether you used a different style as a template for this

**Comment by carljohanberglund** [comment]
I wrote this one from scratch.

**Comment by adam3smith** [comment]
Thanks -- did you close this on purpose?

**Comment by carljohanberglund** [comment]
No...

Vänliga hälsningar
Carl Johan Berglund

**Comment by adam3smith** [comment]
Great, thanks!

**Pull request merged**
