### PR TITLE
Create FLOSS4INGO

### PR DESCRIPTION
**Pull request by vmalep**
Style created for a project in the framework of a Master Degree in Spain

### CODE REVIEW

**Comment by rmzelle** [comment]
> I am know copiing the document on a wiki website (http://www.floss4ingo.xyz) and I would like to use the same style, but for this, it must be available from zotero database.

Which software are you using that requires this?

Since the styles from our repository are offered to hundreds of thousands of users, we're very hesitant to accept styles for individuals or individual projects.

**Comment by vmalep** [comment]
Dear Rintze,
    
    Thanks for your reply. The website is done with TikiWiki and it has
    the feature to create a footnote with the Zotero reference according
    to the style specified in the parameter, but this style must be
    available from your website.
    
    In any case, I decided to proceed differently (with a small tag
    defined as an hyperlink to the Zotero page directly).
    
    Thanks for your support and have a good continuation!
    Pierre
    
    On 04/01/15 14:11, Rintze M. Zelle
      wrote:
    
    
      
        I am know copiing the document on a wiki website (http://www.floss4ingo.xyz)
          and I would like to use the same style, but for this, it must
          be available from zotero database.
      
      Which software are you using that requires this?
      Since the styles from our repository are offered to hundreds of
        thousands of users, we're very hesitant to accept styles for
        individuals or individual projects.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by rmzelle** [comment]
Does TikiWiki support Zotero referencing by itself, or were you planning to use some TikiWiki plugin?

**Comment by rmzelle** [comment]
Closing this as we're unlikely to accept this style.

**Pull request closed without merging**
