### PR TITLE
Create Royal Society of Chemistry bold journal title

### PR DESCRIPTION
**Pull request by TobiasVoepel**
This is the RSC style which has added bold journal titles

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- before you try to fix the automated tests, could you specify what this is for? I don't think RSC prints journal titles in bold, does it?

**Comment by TobiasVoepel** [comment]
Hello Seabstian,

our university (Ruhr University Bochum) uses zotero to create automated 
bibliographical records for research groups.
We would like to have a style that has bold journal titles for better 
readability.

Best

Tobias



Am 08-07-2019 16:14, schrieb Sebastian Karcher:

**Comment by adam3smith** [comment]
OK, makes sense. I'm trying to figure out if this is a good fit to host on the repository or if it would make sense for you to just host locally. Who would be using/downloading this style? Members of a particular working group? Department? The whole university? Students or just researchers? Or are these generated using an API/online service. 

In general, the fewer people a style is aimed at, the less suitable for centralized hosting here it is.

**Comment by TobiasVoepel** [comment]
Hi,
the style would be used implemented in the bibliographical system of the 
university and can be accessed by an API provided by the bibliographical 
team of university.
Basically everyone who has a webpage at Ruhr University has access to 
this.

Best

Tobias


Am 08-07-2019 16:37, schrieb Sebastian Karcher:

**Comment by adam3smith** [comment]
OK -- we [generally don't host styles for usage in APIs](https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles). The styles here are made available to end-users via Zotero, Mendeley, etc. and there is no reason to have this style included in that list. Any reason you couldn't just host this internally? An API shouldn't care where the style is hosted.

**Comment by TobiasVoepel** [comment]
Danke!
Ich werde diese Möglichkeit mit der Hochschulbibliographie besprechen.

Gruß

Tobias Vöpel


Am 08-07-2019 16:46, schrieb Sebastian Karcher:

**Comment by vjosenhans** [comment]
Dear Sebastian,
thanks for your information about the duplicate ticket. We use the zotero style library for the campus so that our scientists can automatically integrate publication lists on their websites via our bibliography. of course we update the zotero library again and again and we really wanted to avoid hosting our own styles.  From your answer, I conclude that we have to do it now, right?
Many greeting, Veronika

**Comment by adam3smith** [comment]
@vjosenhans apologies for the late reply -- summer travel...
I'd be inclined to say that yes, we'd prefer you to host your own style. Could you explain why that would be a problem? There may be options you're not aware of or I may still be misunderstanding (writing in German is fine, too, btw.)

**Pull request closed without merging**
