### PR TITLE
Create uludag-sbe-author-date.csl

### PR DESCRIPTION
**Pull request by mtarakci**
For Institute of Social Sciences of Uludag University. Author-date style.

### CODE REVIEW

**Comment by rmzelle** [comment]
@mtarakci, I renamed the style title and ID a little to better match the rest of our styles. Do you know which existing Chicago CSL style you started from? We'd like to link to that style with a "template" link (https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link).

**Comment by rmzelle** [comment]
(otherwise this looks good to go)

**Comment by rmzelle** [comment]
(replaces #2941)

And @mtarakci, it's usually not necessary to create new pull requests for the same style if you need to make changes.

We also have been receiving Travis CI email notifications for all your commits, which we never see for our other contributors. Did you log in at https://travis-ci.org/ by any chance? Could you turn off Travis CI for your fork of the style repository at https://travis-ci.org/profile/mtarakci? Thanks!

**Comment by mtarakci** [comment]
@rmzelle 
This version started with Chicago Manual of Style (author-date).

**Comment by rmzelle** [comment]
@adam3smith, good to go from my side.

**Comment by rmzelle** [comment]
Thanks! Sorry for the long wait to get anything accepted.

**Pull request merged**
