### PR TITLE
Create american-medical-association-no-url-alphabetical.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/99783/style-update-request-american-journal-of-sport-medicine#latest

### CODE REVIEW

**Comment by adam3smith** [comment]
Hmm -- shouldn't the title for the AMA style be "no DOI", which is the more significant difference?

**Comment by POBrien333** [comment]
I'll let you decide on what's best

**Comment by adam3smith** [comment]
didn't realize we already have a no URL version, so let's stay with that label even if it's awkward.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
