### PR TITLE
Patch 4

### PR DESCRIPTION
**Pull request by libora**
Update one style and add new style

### CODE REVIEW

**Comment by adam3smith** [comment]
@rmzelle -- are you OK with the filename here? Then I'd add it to the ISSN exception list. (context [here](https://forums.zotero.org/discussion/56868/set-up-delimiterprecedeslast-for-different-locale/#Comment_248370), we need separate styles because of non-localizable differences.

**Comment by rmzelle** [comment]
I'm fine with the filename, but the titles of the Czech and English version should be aligned. Could we use "Vodohospodářské technicko-ekonomické informace (Czech)" and "Vodohospodářské technicko-ekonomické informace (English)"?

(if there is only one style format per journal, we usually don't include descriptors like "numeric, brackets" in the title)

I already added the ISSN exception (and restarted the Travis build): https://github.com/citation-style-language/styles/commit/e39144c2561f8925ae02295ae50a8ca5b1ea4674

**Comment by libora** [comment]
Could we use "Vodohospodářské technicko-ekonomické informace (English)"? - of course yes, I will change, take me a moment

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
