### PR TITLE
polimdosains-politeknik-negeri-manado.csl

### PR DESCRIPTION
**Pull request by anritsupolii**
General style for POLIMDOSAINS Journals

### CODE REVIEW

**Comment by rmzelle** [comment]
@anritsupolii, thanks for submitting this style.

http://p3m.polimdo.ac.id/jurnal/ says (translated): "POLIMDOSAINS is an online publishing system based on the Open Journal System that is managed by the Center for Research and Community Service (P3M), Manado State Polytechnic"

We have CSL styles in our repository named after publishers, but none named after publishing systems. Would "Politeknik Negeri Manado - Pusat Penelitian dan Pengabdian Kepada Masyarakat" be an acceptable name for this style? That would fit better with how we do things here.

And we might not even need an overarching CSL style for POLIMDOSAINS/P3M, as we could also just create CSL styles for the three journals listed at http://p3m.polimdo.ac.id/jurnal/.

**Comment by anritsupolii** [comment]
Thanks for commented.
"Politeknik Negeri Manado - Pusat Penelitian dan Pengabdian Kepada Masyarakat" that's a good acceptable name but maybe for consideration that Pusat Penelitian dan Pengabdian Kepada Masyarakat (abbreviated as P3M) up to now has a Journals System [http://p3m.polimdo.ac.id/jurnal/](http://p3m.polimdo.ac.id/jurnal/) and Research Systems [http://p3m.polimdo.ac.id/sim/](http://p3m.polimdo.ac.id/sim/). 
This style is specifically to the P3M journals system, so it would be good to added prefix "Jurnal" and the style name become "Politeknik Negeri Manado - Jurnal Pusat Penelitian dan Pengabdian Kepada Masyarakat".
Regards.

**Comment by anritsupolii** [comment]
> We have CSL styles in our repository named after publishers, but none named after publishing systems. Would "Politeknik Negeri Manado - Pusat Penelitian dan Pengabdian Kepada Masyarakat" be an acceptable name for this style? That would fit better with how we do things here.

@rmzelle thanks for your comments.

I have changed the style to named after publishers. It would be better and suitable for us to use the style name "Politeknik Negeri Manado - Jurnal Pusat Penelitian dan Pengabdian Kepada Masyarakat" 

change notes:
- named after publishers
- Added "Jurnal" prefix

**Comment by rmzelle** [comment]
@anritsupolii, great, thanks.

Can you also look over the dependent styles I added for your three journals?

**Comment by anritsupolii** [comment]
> @anritsupolii, great, thanks.
> 
> Can you also look over the dependent styles I added for your three journals?

@rmzelle, great help, 

Thank you for the goodness of adding dependent styles. It looks very good and I appreciate your help.
Regards.

**Comment by anritsupolii** [comment]
> 
> 
> 😃 Your submission passed all our automated tests.
> 
> Below are some sample citations generated based on your proposed changes:
> politeknik-negeri-manado-jurnal-p3m.csl (new)
> dependent/jurnal-elektrik.csl (rendering failure)
> dependent/jurnal-masina-nipake.csl (rendering failure)
> dependent/jurnal-teknologi-infrastruktur-berkelanjutan.csl (rendering failure)

@rmzelle 
csl-bot says "rendering failure", is this okay?

**Comment by rmzelle** [comment]
Thanks!

> csl-bot says "rendering failure", is this okay?

Yeah, that's fine. It just doesn't always work for "dependent" styles. As long as the tests pass we're good.

**Pull request merged**
