### PR TITLE
Update ecosystems.csl

### PR DESCRIPTION
**Pull request by jasonjensen**
Correctly use abbreviated journal titles

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks!

**Comment by rmzelle** [comment]
@adam3smith, I just checked this, and the instructions use full titles:

> Use the following formats for Literature Cited style:
Journal Article
Elser JJ, Goldman CR . 1991. Zooplankton effects on phytoplankton in lakes of contrasting trophic status. Limnology and Oceanography 36: 64-90.
Journal Article in press
Cottingham KL, Knight SE. 1998. Effects of grazer size on the response of mesotrophic lakes to experimental enrichment. Water Science and Technology, in press.

whereas the published articles seem to use the short forms (see e.g. http://link.springer.com/article/10.1007/s10021-016-9998-6/fulltext.html). What do we do in these cases?

**Comment by rmzelle** [comment]
@jasonjensen, did you notice the discrepancy yourself, or did an editor ask you to use abbreviated journal titles for a manuscript?

**Comment by adam3smith** [comment]
I always trust the published artices over journal guidelines (unless those specify the difference), so this is great, thanks!

**Comment by jasonjensen** [comment]
Thanks, I work at paperpile and a user requested it. I checked one of the latest articles on their site before sending the pull request.
Best,Jason

Get Outlook for iOS




On Thu, Jun 16, 2016 at 12:24 AM -0400, "Sebastian Karcher" <notifications@github.com> wrote:












I always trust the published artices over journal guidelines (unless those specify the difference), so this is great, thanks!

**Pull request merged**
