### PR TITLE
Modify heredity.csl for journal Freshwater Crayfish

### PR DESCRIPTION
**Pull request by FetznerJ**
A new style based on heredity.csl for use by the journal Freshwater Crayfish.

### CODE REVIEW

**Comment by rmzelle** [comment]
@FetznerJ, thanks, but you're currently replacing the Heredity style with your style, and your version has all the code on a single line.

Could you follow the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3a-submitting-a-new-style to submit your style (in a new pull request), and first run it through http://formatter.citationstyles.org/ so that it is properly indented?

Thanks!

**Comment by rmzelle** [comment]
Replaced by #2880.

Thanks!

**Comment by FetznerJ** [comment]
Hi Rintze,

Thanks for the info. I have run the style though the formatter, but when I cut and paste it into the “Edit New File” box in IE11, it flashes on the screen as formatted properly for a second, but then changes to a single line. Seems to be an issue with the submission form (??).

Humm.  I just tired FireFox and it seems to keep the formatting.  I will try submitting it that way.

Cheers,
Jim

**Comment by adam3smith** [comment]
no need to do anything anymore, we added the style already.

**Comment by FetznerJ** [comment]
Ok.  Many thanks!  Appreciate it.

Cheers,
Jim

**Comment by rmzelle** [comment]
> I have run the style though the formatter, but when I cut and paste it into the “Edit New File” box in IE11, it flashes on the screen as formatted properly for a second, but then changes to a single line. Seems to be an issue with the submission form (??).

I just tried using http://formatter.citationstyles.org/ with IE11 on Windows 7, and it works for me. But older versions of IE can be a bit temperamental.

But as @adam3smith said, and sorry if this was unclear, one of our volunteers took your style and resubmitted it with some tweaks, and we accepted that submission, so you're all set.

**Comment by FetznerJ** [comment]
Many thanks!

Cheers,
Jim

**Pull request closed without merging**
