### PR TITLE
Create journal-of-neolithic-archaeology.csl

### PR DESCRIPTION
**Pull request by MartinHinz**
Added style for the Journal of Neolithic Archaeology (http://www.j-n-a.org), based on the DAI style

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks!

**Comment by rmzelle** [comment]
@MartinHinz, sorry for the long wait for reviewing this, by the way.

I see that this journal publishes both in German and English. I was curious whether you tested the CSL style with both languages. The style also still contains some translations for Spanish, Italian, and French that we can probably delete.

**Comment by MartinHinz** [comment]
@rmzelle , thank you for your feedback, and the detailed look to the journal! Actually, the journal articles from now on usually should be in english, but there might be some occasions when we accept german, or even articles in other languages. So I might check the translations, thank you for pointing this out. Will update the style soon if necessary.

**Comment by rmzelle** [comment]
> Actually, the journal articles from now on usually should be in english, but there might be some occasions when we accept german, or even articles in other languages.

Okay, thanks. I added a note in the style that the journal publishes in multiple languages, so that it's clear in the future that the style shouldn't have a fixed "default-locale": https://github.com/citation-style-language/styles/commit/c7d187b8fa39b2367b247813040073457c7cfb25

**Pull request merged**
