### PR TITLE
Create epidemiology-psychiatric-sciences.csl

### PR DESCRIPTION
**Pull request by POBrien333**
https://forums.zotero.org/discussion/103711/style-request-epidemiology-psychiatric-sciences#latest

Guidelines: https://www.cambridge.org/core/journals/epidemiology-and-psychiatric-sciences/information/author-instructions/preparing-your-materials
Paper: https://www.cambridge.org/core/services/aop-cambridge-core/content/view/C271ECD9AB7C2B441029FDBD54D3AD8E/S2045796022000798a.pdf/div-class-title-childhood-adversities-and-risk-of-posttraumatic-stress-disorder-and-major-depression-following-a-motor-vehicle-collision-in-adulthood-div.pdf

Style is all over the place, so this was a minimal-effort style.

### CODE REVIEW

**Comment by bwiernik** [comment]
@POBrien333 Could you add a delimiter between publisher and place?

**Comment by POBrien333** [comment]
That already worked. E.g.: 
Hancké B, Rhodes M and Thatcher M (Eds) (2007) Beyond varieties of capitalism: Conflict, contradiction, and complementarities in the European economy. Oxford University Press, Oxford and New York, NY

**Comment by bwiernik** [comment]
Oh, this is a case of citeproc-ruby handling choose within groups weirdly. My bad

**Comment by bwiernik** [comment]
@adam3smith @retorquere Who is the current maintainer of citeproc-ruby?

**Comment by adam3smith** [comment]
It's still Sylvester afaik

**Pull request merged**
