### PR TITLE
Create revista-da-sociedade-brasileira-de-medicina-tropical.csl

### PR DESCRIPTION
**Pull request by emmanuelbrasil**
http://www.scielo.br/revistas/rsbmt/iinstruc.htm

References: References should be numbered consecutively as they appear in the text. List all authors when there are up to six. For seven or more authors, list the first six, followed by “et al.” Type the reference list on a separate page at the end of the manuscript, using double spacing.

Numbered references to personal communications, unpublished data, or manuscripts either “in preparation” or “submitted for publication” should not be listed among the references. If essential, such material can be incorporated at the appropriate place in the text in accordance with the following examples: (AB Figueiredo: Personal Communication, 1980); (CD Dias, EF Oliveira: Unpublished Data). In-text citations should be indicated using the appropriate reference numbers as superscripts to the corresponding word, using parentheses and no commas (e.g. World(1) (2) (3); Life(30) (42) (44) (45) (46) (47) (48) (49) (50).)

The references at the end of the manuscript should follow the system used in the uniform requirements for manuscripts submitted to biomedical journals (for more information, please see: http://www.nlm.nih.gov/citingmedicine).

The titles of any journals referenced should be abbreviated according to the style used in the Index Medicus (for more information, please see: http://www.ncbi.nlm.nih.gov/sites/entrez?db=journals&TabCmd=Limits).

The following are sample references:

    1. Articles citation in general: Authors, Article title (original language), Periodical name, year, Issue/Volume, articles pages.
    Russell FD, Coppell AL, Davenport AP. In vitro enzymatic processing of radiolabelled big ET-1 in human kidney as a food ingredient. Biochem Pharmacol 1998; 55:697-701.

    2. Book chapter: Authors' book chapter, Chapter title, Editors, Book name, Edititon, City, Publisher, Year and chapter pages.
    Porter RJ, Meldrum BS. Antiepileptic drugs. In: Katzung BG, editor. Basic and clinical pharmacology. 6th ed. Norwalk (CN): Appeleton and Lange; 1995. p. 361-380.

    3.Book: Book authors, Book name, edition, City, Editor and Year.
    Blenkinsopp A, Paxton P. Symptoms in the pharmacy: a guide to the management of common illness. 3rd ed. Oxford: Blackwell Science; 1998.

    4. Dissertation/Thesis: Author, Title, Book Type (Dissertation or Thesis), Place of Publication, Publisher, Date, Total number of pages.
    Cosendey MAE. Análise da implantação do programa farmácia básica: um estudo multicêntrico em cinco estados do Brasil. [Doctor´s Thesis]. [Rio de Janeiro]: Escola Nacional de Saúde Pública. Fundação Oswaldo Cruz; 2000. 358 p.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks. Could you add a ".csl" extension to the file name? ("revista-da-sociedade-brasileira-de-medicina-tropical.csl" instead of "revista-da-sociedade-brasileira-de-medicina-tropical")

See https://github.com/blog/1436-moving-and-renaming-files-on-github

**Comment by rmzelle** [comment]
@emmanuelbrasil, could you make a few more changes:

* the style currently doesn't validate: http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2Femmanuelbrasil%2Fstyles%2Fpatch-1%2Frevista-da-sociedade-brasileira-de-medicina-tropical.csl&version=1.0.1  
  Can you delete the `<substitute/>` on line 42?
* Can you delete the `edition_chapter` macro? It's not used.

**Comment by emmanuelbrasil** [comment]
Lets see if it goes this time. Tried to make as requested.

**Comment by rmzelle** [comment]
Thanks.

In your new version you have `<macro name="access"/>`, and empty macros are not allowed. If you don't need it, just delete the macro itself and the calls to the macro.

**Comment by emmanuelbrasil** [comment]
I wanted to be helpful but I give up. Im upset with this task and I don't want to spend more time in doing something that I really don't understand. rmzelle... if would like to take over this style, it's fine for me. Regards.

**Comment by rmzelle** [comment]
@emmanuelbrasil, it's a bit late, but I fixed the remaining issue and committed the style manually. Thanks for contributing.

**Pull request closed without merging**
