### PR TITLE
Create universidade-do-porto-faculdade-de-engenharia-chicago.csl

### PR DESCRIPTION
**Pull request by serbernardo**
Variation of the Chicago author-date style 17th edition.
Authors in reference lists are shown in a abreviated form
Webpages always show access date with or wihtout edition date inserted

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

**Comment by serbernardo** [comment]
>  Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

@Hi @rmzelle thanks for your feedback. I have included the link for the documentation that you have suggested. 

 <link href="http://www.zotero.org/styles/universidade-do-porto-faculdade-de-engenharia-chicago" rel="self"/>

Can you please tell me, if are you that will close the pull request after your validation, or if its me? I'm not quite sure. Thanks :)

**Comment by rmzelle** [comment]
@serbernardo, thanks. One more question before we can accept this into the repository: will this CSL style be used in both Portuguese and English, or just one of those two languages?

**Comment by serbernardo** [comment]
> @serbernardo, thanks. One more question before we can accept this into the repository: will this CSL style be used in both Portuguese and English, or just one of those two languages?

Hi @rmzelle, this CSL style will be used in both languages English and Portuguese. Thanks :)

**Comment by rmzelle** [comment]
Great, obrigado!

**Comment by serbernardo** [comment]
Hi @rmzelle.
I would like your help if you could help me. I was reviewing once more the style bibliography output and something has escaped my reviews.

In webpages titles in our styles is missing the quotes "".
And we would like to have has the default Chicago Style with quotes like this.

So in our code Inside of <macro name="title"> and then in <else-if type="legal_case interview patent webpage>
it is missing quotes="true" in text variable.  


Can you please advise how I can change the code:

 <else-if type="legal_case interview patent webpage" match="any">
        <text variable="title"/>

With the correct one:

<else-if type="legal_case interview patent webpage" match="any">
        <text variable="title" quotes="true"/>

I would really appreciate your help.
Thanks :)

**Pull request merged**
