### PR TITLE
Create revista-cuicuilco

### PR DESCRIPTION
**Pull request by natch-nacht**
Create a dependent CSL file for Revista Cuicuilco of Escuela Nacional de Antropología e Historia in Mexico City.

### CODE REVIEW

**Comment by adam3smith** [comment]
Perfecto. Muchas gracias Juan.

**Comment by natch-nacht** [comment]
Al contrario, gracias a ti Sebastian

--
Enviado desde mi iMac

**Comment by rmzelle** [comment]
@adam3smith, you're a little too quick :).

I made some minor changes at https://github.com/citation-style-language/styles/commit/733c8330df27af1c77686a75c5fcd5cbdfd78864

@natch-nacht, thanks for contributing!

**Comment by natch-nacht** [comment]
Thanks to you, really!

--
Enviado desde mi iMac

**Pull request merged**
