### PR TITLE
Create Speculum style

### PR DESCRIPTION
**Pull request by adunning**
Style for Speculum: <http://www.journals.uchicago.edu/journals/spc/style-sheet>.

### CODE REVIEW

**Comment by adunning** [comment]
I seem to have broken the test bot, as it is complaining about macros that I have removed.

**Comment by rmzelle** [comment]
@adunning, since this is a University of Chicago Press journal (at least per 2016: http://www.journals.uchicago.edu/journals/spc/about), and since http://www.journals.uchicago.edu/journals/spc/style-sheet says "For usage issues not found in Speculum, authors should consult the 16th edition of The Chicago Manual of Style (Chicago, 2010)", did you check whether this style is the same as either the "note" or "full note" Chicago 16th edition CSL styles we have (https://www.zotero.org/styles?q=16th)?

If so, we can just create a "dependent" style for this journal.

**Comment by adunning** [comment]
Not the same; see the style guide.

**Comment by rmzelle** [comment]
Okay, thanks! It looks like there was a temporary problem with the test bot infrastructure (Travis CI) that resolved itself.

**Comment by adunning** [comment]
Thank you!

**Pull request merged**
