### PR TITLE
Create apa-uoc-style

### PR DESCRIPTION
**Pull request by cespinoa**
The UOC (Universitat Oberta de Catalunya) citation style propose write whole name, without abbreviations. It's a way to make visible the womans in researchs.

### CODE REVIEW

**Comment by bwiernik** [comment]
Thanks! Is there a particular reason you based the style on APA 6th edition instead of APA 7th edition introduced in 2018?

**Comment by cespinoa** [comment]
> Thanks! Is there a particular reason you based the style on APA 6th edition instead of APA 7th edition introduced in 2018?

I need the author's name to be seen in full, not abbreviated.
It's a suggestion from my university to show women's names.
I already use this style locally, but I want my colleagues to use it.

**Comment by bwiernik** [comment]
I understand the change you are making with the style, but could you explain why you used the old version APA 6th edition instead of 7th edition?

**Comment by cespinoa** [comment]
Ooops. That was a mistake. It's updated. Thank

**Comment by adam3smith** [comment]
Is full first names the only change to APA 7
@bwiernik I'd consider creating an APA version for this that we can point to. Organization Studies is the same thing

**Comment by bwiernik** [comment]
Yeah, that's what I was thinking

**Comment by bwiernik** [comment]
@cespinoa Thanks! I included a version of this style in https://github.com/citation-style-language/styles/pull/5812.

It is titled `universitat-oberta-de-catalunya-apa.csl` (Universitat Oberta de Catalunya - APA) to be consistent with the repository style guidelines.

**Pull request closed without merging**
