### PR TITLE
New style for University of Lausanne

### PR DESCRIPTION
**Pull request by nchachereau**
This style is developed mainly for the history department of the University of Lausanne, Switzerland. It is based on another style (infoclio), and adapted to fit the citation style that has been used for years in teaching and students' papers in the department. 

More information is available on our separate Github repository (French): https://github.com/LausanneCitationStyle/Lausanne, where we also write the [documentation](https://github.com/LausanneCitationStyle/Lausanne/blob/master/documentation/StyleDescription.md) intended for the department's website.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks. https://github.com/LausanneCitationStyle/Lausanne/blob/master/README.md says:

> Ce style bibliographique, adapté aux pratiques des départements d'histoire des universités suisses, a été développé pour les besoins de la section d'histoire de l'Université de Lausanne sur la base d'un style développé pour Infoclio.

Apart from your own documentation, is there any other official documentation that describes this citation format as used by the history departments of Swiss universities?

**Comment by rmzelle** [comment]
I also noticed that you made a derivative of the Zotero logo for your style: https://raw.githubusercontent.com/LausanneCitationStyle/Lausanne/master/images/LausanneCitationStyle.png at https://github.com/LausanneCitationStyle/Lausanne/blob/master/README.md

You can ask the Zotero developers and/or Corporation for Digital Scholarship, but I'm pretty sure they will say your logo will violate their trademark/copyright, so you should probably use something else. (cc @dstillman, @stakats )

**Comment by dstillman** [comment]
Yes, @nchachereau, I'm afraid we'll need you to remove that. The Zotero logo [can be used to promote Zotero](https://www.zotero.org/support/brand), but use of our trademarks [is otherwise reserved](https://www.zotero.org/support/terms/trademark), and we can't allow a derivative version of the logo.

(Note, too, that CSL styles aren't specific to Zotero, so while we're very happy to have you promote using it with Zotero, it could in theory be used with other CSL-supporting tools as well.)

**Comment by grandjeanmartin** [comment]
Many thanks @rmzelle and @dstillman for your precious comments.

The icon was just an illustrative fan art that we gladly remove, no intention to use it as a mark. ;)
In any case, the Github documentation will be greatly enriched once the style has been accepted (and supplemented by more official documentation on the university website, this icon wasn't supposed to be transferred there).

With regard to additional documentation asked by @rmzelle, the style is derived from the [infoclio style](https://www.infoclio.ch/fr/style-de-citation-infoclioch-instructions-pour-zotero). 
Unfortunately, the official documentation of the University of Lausanne was taken offline during this renewal process. But you can have a look at the guides proposed at the University of Fribourg ([this document](http://www.unifr.ch/theo/assets/files/SA2015/Guide.methodologie.2015.pdf), from p.22).

Best,
Martin (and @nchachereau)
[hey @stakats, funny to see you appear on this thread]

**Comment by rmzelle** [comment]
> Unfortunately, the official documentation of the University of Lausanne was taken offline during this renewal process. But you can have a look at the guides proposed at the University of Fribourg ([this document](http://www.unifr.ch/theo/assets/files/SA2015/Guide.methodologie.2015.pdf), from p.22).

We always try to make sure each style is based on, and named after, a single authoritative source. If you represent the history department at the University of Lausanne, we'll probably want to rename the style title to "Université de Lausanne - Section d'histoire (French)" (we also specify the style language for non-English styles), and change the filename/style ID to "universite-de-lausanne-section-dhistoire". Let me know if that's the correct scope for this style.

For now it will suffice to keep the current "documentation" link to https://github.com/LausanneCitationStyle/Lausanne, but it would be great if you could ping us here once the official documentation on the university website becomes available again.

You can make this change yourself and update the current pull request by following the instructions above at https://github.com/citation-style-language/styles/pull/3796#issuecomment-441259820, or I can make these changes for you.

**Comment by rmzelle** [comment]
Perfect, thanks!

**Pull request merged**
