### PR TITLE
Update vietnam-ministry-of-education-and-training-vi.csl

### PR DESCRIPTION
**Pull request by Tungphamfsh**
Major update to fix various problems with citing web page, thesis and book
Use new citation style to match the requirements of Ministry of education and training

### CODE REVIEW

**Comment by rmzelle** [comment]
See http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2FTungphamfsh%2Fstyles%2Fpatch-10%2Fvietnam-ministry-of-education-and-training-vi.csl&version=1.0.1#source-code

**Comment by Tungphamfsh** [comment]
Thank you, I was looking for the error for 30 minutes. I did not know about the validator tool before

**Comment by rmzelle** [comment]
Yes, sorry. The Travis CI schema validation errors usually aren't very descriptive. @inukshuk, any chance this could be improved? E.g. https://travis-ci.org/citation-style-language/styles/builds/61760294 says:

```
expected: []
            got: [[25, "Did not expect element macro there"], [25, "Element style has extra content: macro"], [2, "Expecting element locale, got style"]]
```

whereas the validation report http://validator.citationstyles.org/?url=https%3A%2F%2Fraw.githubusercontent.com%2FTungphamfsh%2Fstyles%2Fpatch-10%2Fvietnam-ministry-of-education-and-training-vi.csl&version=1.0.1#source-code correctly identifies the issue:

```
Line 63: Element “date” from namespace “http://purl.org/net/xbiblio/csl” is missing required attribute “variable”.
```

**Comment by rmzelle** [comment]
Also, @Tungphamfsh, if you have `et-al-min="3" et-al-use-first="3"` set on `<style/>`, you can remove these same attributes from `<citation/>` and `<bibliography/>`.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
