### PR TITLE
Create UWE-Bristol-Harvard-2021.csl

### PR DESCRIPTION
**Pull request by Delane00**
Hello - following feedback and testing illuminating a number of issues with University of the West of England (UWE) Bristol's Harvard format, I have made use of the University of Worcester's style with some minor amendments to correct those issues.

Hopefully this version will be acceptable.

### CODE REVIEW

**Comment by Delane00** [comment]
Hello - I have managed to update the errors in my file, but I'm afraid I don't know what to do about the final one. Could someone advise or help? Many thanks

> UWE-Bristol-Harvard-2021: must have a conventional file name
> 
> expected "UWE-Bristol-Harvard-2021.csl" to match /^[a-z\d]+(-[a-z\d]+)*\.csl$/
> Diff:
> @@ -1 +1 @@
> -/^[a-z\d]+(-[a-z\d]+)*\.csl$/
> +"UWE-Bristol-Harvard-2021.csl"

**Comment by rmzelle** [comment]
@Delane00, don't worry about that error for now. Do I understand correctly that this version should replace our existing UWE style?: https://www.zotero.org/styles?q=id%3Aharvard-university-of-the-west-of-england

**Comment by Delane00** [comment]
> @Delane00, don't worry about that error for now. Do I understand correctly that this version should replace our existing UWE style?: https://www.zotero.org/styles?q=id%3Aharvard-university-of-the-west-of-england

@rmzelle , Yes please, that would be great.

**Comment by rmzelle** [comment]
@Delane00, thanks! I updated the existing style with your submission.

**Comment by Delane00** [comment]
Many thanks, @rmzelle

**Pull request merged**
