### PR TITLE
Create biotechnology-journal.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/84873/style-request-biotechnology-journal#latest

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, I'm not sure I should merge this.

@bwiernik already set up a dependent style for this journal (pointing to an APA variant) last November (https://github.com/citation-style-language/styles/pull/5089#issuecomment-720339525), which is more recent than the request referenced above, and presumably they haven't changed citation format since.

**Comment by bwiernik** [comment]
Yeah, the early view articles seem to have switched to the APA 7 variant used by BioEssays https://onlinelibrary.wiley.com/doi/epdf/10.1002/biot.202000350

**Comment by POBrien333** [comment]
thanks for checking. It was an older request on the Citation Style Requests list (https://docs.google.com/spreadsheets/d/1zc3Sl4JU7Ltu0Q55-OB0QYCJbYiguVXwpc_BzBLLZcA/edit#gid=128551622).

That's the problem if it doesn't get marked I just assume it hasn't been done.

**Comment by bwiernik** [comment]
Sorry about that. I didn't realize this journal was on the list.

**Pull request closed without merging**
