### PR TITLE
Update uludag-universitesi-sosyal-bilimler-enstitusu-full-note.csl

### PR DESCRIPTION
**Pull request by mtarakci**
So sorry for such a quick and near update.

### CODE REVIEW

**Comment by mtarakci** [comment]
Dear rmzelle,
Tomorrow, we have introductory meeting for zotero styles of uludag university at university campus.
Is it possible for you to merge the recent updates today?

**Comment by rmzelle** [comment]
I'll take a look now. (sorry for the long wait; we get a lot of pull request and both volunteers who deal with them are rather busy nowadays)

**Comment by rmzelle** [comment]
Thanks!

**Comment by mtarakci** [comment]
Thank you very much @rmzelle. I am very grateful.

**Comment by mtarakci** [comment]
Dear @rmzelle, 
In accordance with Chicago Manual of Style 17th Edition, I want to change this full note style in a way that it does not use Ibid. And, I will add full note-with Ibid version.  So full note with no-ibid version should be deleted. 
Is this OK for you?

**Comment by rmzelle** [comment]
So you would like to see

Uludağ Üniversitesi - Sosyal Bilimler Enstitüsü (full note, no Ibid., Turkish)
Uludağ Üniversitesi - Sosyal Bilimler Enstitüsü (full note, Turkish)

renamed to

Uludağ Üniversitesi - Sosyal Bilimler Enstitüsü (full note, no Ibid., Turkish)
Uludağ Üniversitesi - Sosyal Bilimler Enstitüsü (full note, Turkish)

to

Uludağ Üniversitesi - Sosyal Bilimler Enstitüsü (full note, Turkish)
Uludağ Üniversitesi - Sosyal Bilimler Enstitüsü (full note, with Ibid., Turkish)

Correct? If so, I can just rename both styles myself.

**Comment by mtarakci** [comment]
There are also very minor changes. Then let me update the styles firstly.

**Pull request merged**
