### PR TITLE
Scientific Reports style format update

### PR DESCRIPTION
**Pull request by austin-curnutt**
The journal reference format has changed since the previous style was uploaded in 2014. I created this based on a Nature style to fit the current requirements.

### CODE REVIEW

**Comment by adam3smith** [comment]
How does this differ from one of the regular Nature styles (don't worry about the Travis failure for now)

**Comment by austin-curnutt** [comment]
It's for Scientific Reports, which is a Nature journal. I used the nature style as the template, but it's for Scientific Reports to match the current formatting guidelines (see the documents in the info section).

Austin Curnutt

________________________________

**Comment by adam3smith** [comment]
Right, I know what Scientific Reports is; I'm wondering how this is different from regular Nature style. The current CSL style for Scientific Reports just links to that and I think that's still the right approach given

> Scientific Reports uses standard Nature referencing style. 

If there are problems with the Nature style (which is totally possible) we can fix those there.

**Comment by austin-curnutt** [comment]
The PDF file with guidance for references describes a different format than what is currently available from the Scientific Reports style in the repository. The guidance there asks for bracketed references and the DOI in the bibliography, which the current style does not have.

Austin Curnutt

________________________________

**Comment by adam3smith** [comment]
It doesn't ask for DOIs, no -- those are only for online only journals and datasets (note the Schott et al. example in both PDF and HTML instructions which as no DOI).

The square brackets are weird -- let me see if we can get some guidance from Springer Nature on that -- it's odd that journals with the same style in print would want something different in for submission (Scientific Reports uses superscripts for references in print).

**Comment by austin-curnutt** [comment]
I see that now about the DOI. I noticed that point about the brackets when reading some of their other papers, but made the edit for ours to comply with that guidance in the revision document.

I’m working on submitting a paper now, so thank you for pointing that out about the DOI requirement.

**Comment by adam3smith** [comment]
If you're submitting anyway, would you mind asking the managing editor about square brackets vs. superscript? If they're fine with superscript, we could leave this linked to Nature style; if they really want brackets, we need a separate style (i.e. yours) which is of course possible, but much less convenient.

**Comment by austin-curnutt** [comment]
Definitely. We should be submitting tonight or tomorrow so I’ll have the submitting author include that question.

**Comment by rmzelle** [comment]
@austin-curnutt, did you ever hear back?

**Comment by austin-curnutt** [comment]
Hello,

I’m checking with the corresponding author to see how they accepted the paper formatting. I’ll let you know when I hear back.

**Comment by austin-curnutt** [comment]
I just saw the proof for the paper. The in-line citations for Scientific Reports were done as superscripts and the references were done using numbers in the format: “1.”

**Comment by adam3smith** [comment]
Didn't realized this actually got answered fully -- thanks for getting back to us & good to know we can leave things as they are

**Pull request closed without merging**
