### PR TITLE
Create ecohealth.csl

### PR DESCRIPTION
**Pull request by soflito**
CSL for EcoHealth Journal

### CODE REVIEW

**Comment by adam3smith** [comment]
could you explain what you're trying to do? This is a little confusing -- you're adding a style that you're saying is for ecohealth, but that is actually (as per the style) for The Holoscene. You're also adding it in the wrong place (i.e. the dependent folder).

**Comment by soflito** [comment]
Hi Sebastian,

I'm so sorry for the mess! It was just a trial because I want to add a
style for EcoHealth, but I'm still editing and learning how to do all this.
I tried to undo what I did and didn't know how to. I'm very sorry for
wasting your time as well.

I will get some help next time when I have the style ready.

My apologies again,

Sofia

On Fri, Mar 27, 2015 at 9:58 AM, Sebastian Karcher <notifications@github.com
> wrote:

> could you explain what you're trying to do? This is a little confusing --
> you're adding a style that you're saying is for ecohealth, but that is
> actually (as per the style) for The Holoscene. You're also adding it in the
> wrong place (i.e. the dependent folder).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1482#issuecomment-86964636>
> .
>



-- 
Sofía Rodríguez B.
University of Texas at Austin
1 University Station, CO930
Integrative Biology
Austin, TX 78712
Tel (512) 475-6164

**Comment by adam3smith** [comment]
No worries. I'll close this then. Start a new pull request when you're ready.

**Comment by rmzelle** [comment]
@soflito, and when you're ready to resubmit, make sure to check the requirements in https://github.com/citation-style-language/styles/wiki/Style-Requirements

**Pull request closed without merging**
