### PR TITLE
filename change for naming consistency

### PR DESCRIPTION
**Pull request by grolimur**
`haute-ecole-de-gestion-de-geneve-iso-690-en.csl` replaced by `haute-ecole-de-gestion-de-geneve-iso-690-en.csl` (for consistency with the newly submitted `haute-ecole-de-gestion-de-geneve-iso-690-fr.csl`)

### CODE REVIEW

**Comment by rmzelle** [comment]
It's better to leave the style ID and file name as is, as changing style IDs can cause problems for downstream products. Would you like us to accept the other changes in the pull request?

**Comment by grolimur** [comment]
Ok, I understand the problems that may occur.
Yes, I would like you to accept all the other changes.

**Comment by grolimur** [comment]
@rmzelle According to @adam3smith's proposal (#5201), I would like to add 2 little changes.
Should I wait for the above changes to be merged before submitting them?

**Comment by adam3smith** [comment]
you can make changes additional changes to this and related file in your master branch and they'll automatically update this PR here. That'd be the best option.

**Comment by grolimur** [comment]
@adam3smith Should I do some additional change to have the updated style merged? Students of my university will have to start using it from February on.

**Comment by adam3smith** [comment]
Thanks, sorry for the delay merging.

**Comment by grolimur** [comment]
No worries. Thanks

**Pull request merged**
