### PR TITLE
Modification bibliography for book

### PR DESCRIPTION
**Pull request by Bibref**
The citation style didn't match the school style for books. A punctuation problem was solved by adding a `<choose>` and creating two different options.

### CODE REVIEW

**Comment by rmzelle** [comment]
Is there a specific reason why you closed this pull request? It looks identical to #1406.

**Comment by Bibref** [comment]
It is exactly the same. it was mistakenly closed...

**Comment by rmzelle** [comment]
Okay. Just know that you can always reopen the pull request (as long as the original branch still exists).

**Comment by Bibref** [comment]
Thanks for the advice!

**Pull request closed without merging**
