### PR TITLE
Update freshwater-biology.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/75767/style-edit-request-freshwater-biology-add-doi
add Doi. checked in publication .pdf.

### CODE REVIEW

**Comment by POBrien333** [comment]
Not getting why this wouldn't validate?
I also didn't touch the template line, but it appears in green as if I added it?

**Comment by adam3smith** [comment]
Somehow you must have been on an older fork/branch. The template was removed about a month ago when the style linked to got turned into a dependent https://github.com/citation-style-language/styles/pull/3393/files

**Comment by adam3smith** [comment]
Thanks!

**Comment by POBrien333** [comment]
hmm.
I usually just go into the repo here on github and get the very latest code and copy it over to the editor.
This time, for whatever reason, I went onto the zotero repository and did the Ctrl+U trick to get the code.

**Pull request merged**
