### PR TITLE
Create arcadia-science.csl 

### PR DESCRIPTION
**Pull request by mertcelebi**
New [Arcadia Science](https://www.arcadiascience.com/) CSL style that's a simplified version of the [eLife](https://github.com/citation-style-language/styles/blob/master/elife.csl) CSL style.

### CODE REVIEW

**Comment by adam3smith** [comment]
Could you say more about what this style will be used for and how? Also, are the requirements documented online somewhere?

**Comment by adam3smith** [comment]
Thanks! We generally try to avoid having citation styles just for API integrations since the styles are made available for 100,000s of users via the various software integrations. PubPub wouldn't be able to use a custom-hosted style?

**Comment by mertcelebi** [comment]
Hi @adam3smith thanks for getting back to me so quickly. That's a great question. I'll ask PubPub and get back to you. I'll also check-in with our team about potential future use cases that I may not be able to anticipate right now. Based on PubPub's response + our team's potential use cases, perhaps we can punt on this PR until a future date. I'll keep you posted. Thank you for your patience :)

**Comment by adam3smith** [comment]
Thanks, happy to leave this open until you hear back -- if there's no technical way to make this happen otherwise, we can revisit, the goal of course is for this repo to be as useful as possible, but we also do try to keep it manageable.

**Comment by adam3smith** [comment]
@mertcelebi any update on this? Otherwise I'd be inclined to close the issue for now and re-open once you have any thoughts on how you want to proceed.

**Comment by mertcelebi** [comment]
Hi @adam3smith apologies for this! I thought I responded, but it seems like this slipped through the cracks. 

I talked to PubPub and our internal publishing team about this. We'd love to move forward with the inclusion of the `arcadia-science.csl` to the repository, since this is part of our broader publishing experiment and we'd love to encourage a wider adoption of this style by others. You can read more about our publishing experiment [here](https://research.arcadiascience.com/pub/perspective-publishing-round-one/release/2).

**Comment by adam3smith** [comment]
Thanks @mertcelebi -- we'll accept this. I can't edit your pull request (there should be an option to the right to allow maintainers edit access) so could you either enable that or make the following two changes to the info section:
1. Add a link to the elife style (on zotero.org/styles, not on github) with rel="template"
2. Add a link to the description of your style you posted in your last comment, i.e. https://research.arcadiascience.com/pub/perspective-publishing-round-one/release/2 with rel="documentation.

**Comment by mertcelebi** [comment]
@adam3smith addressed! Let me know if I didn't do it correctly. Thank you :)

**Pull request merged**
