### PR TITLE
Update science-and-technology-for-the-built-environment.csl.

### PR DESCRIPTION
**Pull request by mitchpaulus**
Fix subsequent inline citation problem.
Fix author name ordering.

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks. I assume you based this on published articles? The instructions to authors only say:

> All authors are listed in a Reference list entry (no “et al.”).

but don't say anything about the use of "et al." in in-text citations.

**Comment by rmzelle** [comment]
I was able to confirm the `et-al-min="3" et-al-use-first="1"` setting for in-text citations in http://www.tandfonline.com/doi/pdf/10.1080/23744731.2016.1208538, by the way. But according to the instructions, the style shouldn't use "et al." at all in the bibliography, so we'll have to change that as well.

**Comment by rmzelle** [comment]
@mitchpaulus, I'll merge this once you give the go-ahead.

**Comment by adam3smith** [comment]
(I was just looking over this, too; I think it's good to go)

**Comment by mitchpaulus** [comment]
Thank you all for your help! Obviously, the journal does not have a fully specified format, and I did my best to reverse engineer out what they prefer. 

You can go ahead and merge in.

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
