### PR TITLE
Update padagogische-hochschule-vorarlberg.csl

### PR DESCRIPTION
**Pull request by peboeck**
next try - thank you for your help!

### CODE REVIEW

**Comment by rmzelle** [comment]
Did you try my suggestion from #1473? You seemed to have used the "publisher" macro as I wrote it, but you didn't use

```
      <group delimiter=" "/>
        <group delimiter=". "/>
          <text macro="publisher"/>
          <text macro="editor"/>
        </group>
        <text macro="published-date"/>
      </group>
```

**Comment by rmzelle** [comment]
It's also much easier for us to keep track of things if you update your existing pull request, instead of creating a new one each time you wish to submit a change.

E.g. you can update this pull request by using the pencil icon at https://github.com/peboeck/styles/blob/patch-11/padagogische-hochschule-vorarlberg.csl

**Comment by rmzelle** [comment]
And the point of

```
      <group delimiter=" "/>
        <group delimiter=". "/>
          <text macro="publisher"/>
          <text macro="editor"/>
        </group>
        <text macro="published-date"/>
      </group>
```

is to use ". " between the output of the "publisher" and "editor" macros, and " " between the output of those two macros and the "published-date" macro.

**Comment by peboeck** [comment]
it works that way, I requested.

**Comment by rmzelle** [comment]
> it works that way, I requested.

I'll just merge this, then. (also, if you're not totally comfortable writing in English, German is perfectly fine too)

**Pull request merged**
