### PR TITLE
Modification to national-institute-of-technology-karnataka.csl

### PR DESCRIPTION
**Pull request by biosainik**
The hanging indent in bibliography is set **false.** The line spacing is set to **1.5** and
[national-institute-of-technology-karnataka.txt](https://github.com/citation-style-language/styles/files/1068831/national-institute-of-technology-karnataka.txt)

 data stamp changed.

### CODE REVIEW

**Comment by biosainik** [comment]
@rmzelle Here is a request for you, to review my style.

Thanks.

**Comment by biosainik** [comment]
@adam3smith Could you please review my changes in this style.

**Comment by rmzelle** [comment]
Thanks!

**Comment by biosainik** [comment]
Thanks @rmzelle !

**Pull request merged**
