### PR TITLE
[Don't Merge] Fix the web page citation

### PR DESCRIPTION
**Pull request by SuperDomek**

### CODE REVIEW

**Comment by SuperDomek** [comment]
Sorry, I introduced a mistake into the style. I'm gonna fix it. Please can you put this pull request on hold in the meantime?

**Comment by adam3smith** [comment]
Sure -- let us know when this is ready for review

**Comment by SuperDomek** [comment]
It's ready to merge. Thank you!

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
