### PR TITLE
Victoria University Harvard style uploaded and renamed

### PR DESCRIPTION
**Pull request by SunwayCollege**
Applied changes as recommended 
- Change file name
- change self link

### CODE REVIEW

**Comment by rmzelle** [comment]
Is this the same as #1915?

**Comment by SunwayCollege** [comment]
Yes. It is similar to #1915 but with the recommended changes as applied to 2645c04

**Comment by rmzelle** [comment]
I accepted your style from #1915. Thanks for contributing!

Sorry for letting that pull request sit for a few days. I hadn't seen you had updated it. (in general, it's almost always better to stay in your original pull request; next time, feel free to leave a comment if you think you've been forgotten)

**Comment by SunwayCollege** [comment]
Noted. Thank you for the advice.

**Pull request closed without merging**
