### PR TITLE
Update systematic-and-applied-microbiology.csl

### PR DESCRIPTION
**Pull request by Sankar-GEO-ELS**
added a new Sort node under ‘Bibliography’ header specifying 'author'

### CODE REVIEW

**Comment by adam3smith** [comment]
thanks. I'd suggest using ```<key macro="author"/>``` though: that way, e.g. edited books will be included in the regular alphabetic sorting. Please just update this pull request by editing the file in your patch-5 branch. No need to start a new one. Let us know if you need more detailed instructions.

**Comment by Sankar-GEO-ELS** [comment]
Thanks. I have just updated this pull request in the patch-5 branch with <key macro="author"/>.

**Comment by adam3smith** [comment]
thanks!

**Comment by Sankar-GEO-ELS** [comment]
Sebastian, Thanks for your help on this. Sankar

**Pull request merged**
