### PR TITLE
technische-universitat-dresden-finanzwirtschaft-und-finanzdienstleistungen-author-date

### PR DESCRIPTION
**Pull request by jmiba**
Yet another style of the chair Finanzwirtschaft at TU Dresden

### CODE REVIEW

**Comment by rmzelle** [comment]
Do you have some example references that show how this style differs from #1761? They both print the short title in the in-text citation, but this one doesn't print it again in the bibliography?

**Comment by jmiba** [comment]
@rmzelle, this is a mistake. The short title should not be printed in the inline citation. I will change that.

**Comment by rmzelle** [comment]
Okay, looks good now.

**Comment by adam3smith** [comment]
thanks!

**Pull request merged**
