### PR TITLE
Create university-college-lillebaelt-vancouver.csl

### PR DESCRIPTION
**Pull request by roaldfrosig**
Variation of the Vancouver reference style, for use by students at University College Lillebælt (Denmark)

### CODE REVIEW

**Comment by zuphilip** [comment]
(continuation of https://forums.zotero.org/discussion/45623/adding-a-new-style-to-the-repository/)

Okay, now we are fine for the next steps. The maintainer of the repo will have a look at your styles and give you some sort of feedback, maybe ask you to change some stuff. If the styles will be accepted then they will outomatically appear in the official repo.

**Comment by rmzelle** [comment]
@roaldfrosig, can you set both styles to `default-locale="da-DK"`, please? We also would like to see a "template" link (see point 6 at https://github.com/citation-style-language/styles/wiki/Style-Requirements ).

**Comment by roaldfrosig** [comment]
I have now set both styles to default-locale="da-DK", and have added a page-range-format to the Harvard style.
I actually wrote the two styles from scratch, as I found it very confusing to adjust an existing style.

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
