### PR TITLE
Create materials-express.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/80461/style-request-materials-express-harvard-referencing

Style does not follow guidelines. It's certainly a numeric style (and not an author-date style). Formatting in various papers checked, but it's all over the place.
https://scholar.google.es/scholar?hl=en&as_sdt=0%2C5&q=%22Materials+Express%22+-optical+2019&btnG=

### CODE REVIEW

**Comment by rmzelle** [comment]
> Style does not follow guidelines. It's certainly a numeric style (and not an author-date style). Formatting in various papers checked, but it's all over the place.

So what did you base this CSL style on?

**Comment by adam3smith** [comment]
I'm actually seeing that the most recent papers I could find, those accepted/published after June this year, _do_ follow the styleguide, i.e. citation number in square brackets and author. **year**. title
e.g.
https://www.ingentaconnect.com/contentone/asp/me/2019/00000009/00000006/art00013?crawler=true&mimetype=application/pdf
https://www.ingentaconnect.com/contentone/asp/me/2019/00000009/00000006/art00005?crawler=true&mimetype=application/pdf

**Comment by POBrien333** [comment]
Hmm. I based the style on some articles from 2018, if I can remember it exactly.
I'll look into it again.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
