### PR TITLE
Create mercator-institut-fur-sprachforderung-und-deutsch-als-zweitspr…

### PR DESCRIPTION
**Pull request by ltwente**
…ache.csl

### CODE REVIEW

**Comment by adam3smith** [comment]
Could you describe briefly the target audience for this style, i.e. who would be using it?
Looking whether this style meets https://github.com/citation-style-language/styles/wiki/Criteria-for-Accepting-Styles

**Comment by rmzelle** [comment]
And if possible, please provide a direct link to the style guide on which you based this citation style.

**Comment by adam3smith** [comment]
Thanks for updating the style @ltwente -- do please see my and Rintze's questions above, though. Feel free to respond in German if that's easier for you.

**Comment by ltwente** [comment]
Sorry for not responding instantly. I noticed some little things I would like to change before merging. I will revise the style today.

Regarding the target audience: We frequently publish articles and other texts involving authors from outside our Institute. Also, we sponsor a multitude of projects at other universities and then report the results and their publications. It would be much easier if we could point 'outside' authors to the style on zoterobib (that tool is awesome) so the references we receive are already formatted even if people are not using zotero as a software.

As for the style guide: the style follows the Waxmann Style that has been written for Citavi and thus is not available for free. I will post a link to the style guide via a public link on sciebo if that is ok.

**Comment by adam3smith** [comment]
That's good enough for me re: target audience, thanks for clarifying. 
Sciebo link for the style guide is perfectly fine.

Please let us know when you're done with any revisions you still like to make.

**Comment by ltwente** [comment]
I am done for now!

**Comment by ltwente** [comment]
Sorry, I am new to GitHub

**Comment by rmzelle** [comment]
Great, thanks!

And would it be okay to attach a copy of that style guide to a GitHub comment here? Just in case the Sciebo link will become unavailable in the future. (if you want to give this a try yourself, you can just do it via drag and drop)

**Comment by ltwente** [comment]
[StyleGuide for the Mercator-Institute for Literacy and Language Education in Cologne (German).docx](https://github.com/citation-style-language/styles/files/2542281/StyleGuide.for.the.Mercator-Institute.for.Literacy.and.Language.Education.in.Cologne.German.docx)

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
