### PR TITLE
Update austrian-legal.csl

### PR DESCRIPTION
**Pull request by zuphilip**
Improve the interpunctation and simplify some code, cf https://forums.zotero.org/discussion/50736/fehler-bei-zitierstil-moor-siebeck/#Item_6

### CODE REVIEW

**Comment by rmzelle** [comment]
Should we try to keep the XML comments? @adam3smith?

(@zuphilip, unfortunately the CSL editor strips XML comments from styles)

**Comment by zuphilip** [comment]
I manually added some XML comments before submitting. However, the other comments are (at least for me) mostly unnecessary.

**Comment by adam3smith** [comment]
I'm OK taking these out. Agree with @zuphilip we should be judging this case-by-case.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
