### PR TITLE
Create iran-manual-style

### PR DESCRIPTION
**Pull request by sinasabbagh**
Modified version of Chicago date-author style, edition 16

* Modified quotations and delimiters to match Persian writing style.
* Also changed months names, although I don't think this matters in Chicago style.
* The title of this csl is set to Iran Manual Style, to match the name that is used by Irandoc. Please note that they have an official permission from Chicago Universiry Press to do this.

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- A couple of questions:
- The name "Iran Manual Style" sounds weird in English. The original in Farsi is  شیوه‌نامه ایران  ?  
How would "Iran Manual of Style - شیوه‌نامه ایران  (فارسی)" work as a title?
And is there just the author-date version of this, or are there footnotes versions as well?

**Comment by adam3smith** [comment]
@ sinasabbagh Please see my questions above -- would be great to get this merged!

**Comment by sinasabbagh** [comment]
I'm terribly sorry for the delay. This was lost in my inbox.
To answer your question:

-  yes the original title is شیوه‌نامه ایران
- Actually you're right about the title "Iran Manual of Style" is correct and is used in English description of the manual.

**Comment by sinasabbagh** [comment]
I've updated the title. I don't see why it needs فارسی in the title. We can add it though, if saying explicitly that it is in Persian is necessary.

**Comment by adam3smith** [comment]
@rmzelle -- this is gtg from my end -- see what you want to do about adding (or not) the language to the style.

**Comment by rmzelle** [comment]
> I've updated the title. I don't see why it needs فارسی in the title. We can add it though, if saying explicitly that it is in Persian is necessary.

We always add the language to the titles of CSL styles that are locked to non-English languages. Two big advantages are that people can then quickly identify styles created for their specific language, and that users are informed what locale a citation style will render in. For consistency we'd like to add it here as well.

**Comment by rmzelle** [comment]
@sinasabbagh, thanks!

**Pull request merged**
