### PR TITLE
Quotes nccr-mediality

### PR DESCRIPTION
**Pull request by cnotz**
Adapted quotes to requirements of citation standard.

### CODE REVIEW

**Comment by rmzelle** [comment]
@cnotz, there can only be one `<terms/>` element per `<locale/>` element, so:

```
   <terms>
      <term name="open-quote">»</term>
      <term name="close-quote">«</term>
      <term name="open-inner-quote">›</term>
      <term name="close-inner-quote">‹</term>
    </terms>
    <terms>
      <term name="accessed">gesehen am</term>
```

should be

```
   <terms>
      <term name="open-quote">»</term>
      <term name="close-quote">«</term>
      <term name="open-inner-quote">›</term>
      <term name="close-inner-quote">‹</term>
      <term name="accessed">gesehen am</term>
```

**Comment by cnotz** [comment]
Thank you for your help. I changed and recommited.

**Comment by rmzelle** [comment]
Thanks!

**Comment by cnotz** [comment]
Thanks to you!

**Pull request merged**
