### PR TITLE
Update the-open-university-numeric-superscript.csl

### PR DESCRIPTION
**Pull request by kellyfk**
without quotes

### CODE REVIEW

**Comment by rmzelle** [comment]
@kellyfk, you somehow ended up creating this pull request from the "springer-update-2" branch in your fork to the same fork in our repository, which isn't correct. You should instead propose the change to the version of this style in the default "master" branch, which you can find it at https://github.com/citation-style-language/styles/blob/master/the-open-university-numeric-superscript.csl.

Before you create another pull request, though, is this change meant as a correction? Can you give a link to the style guide you are following?

**Comment by kellyfk** [comment]
My change is not meant as a correction, just a tweak for the use of myself and my research team. Do I need to create a new style? Since it was largely based on an existing style, with one minor change, I thought this was the best way to go.

 

Kelly

 

From: Kelly Kajumulo [mailto:kellyfk@uw.edu] 
Sent: Thursday, February 09, 2017 4:56 PM
To: 'citation-style-language/styles' <reply@reply.github.com>; 'citation-style-language/styles' <styles@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [citation-style-language/styles] Update the-open-university-numeric-superscript.csl (#2491)

 

Thanks for the help. I am new to this. The update changed the title and added my name as a contributor. I’m completely unsure of what the protocols are for this but I would like to use the-open-university-numeric-superscript style with one minor change. They currently put quotes around the title of the article and I would like to remove those quotes. (I did that by changing true to false).

 

This is the original link

https://github.com/citation-style-language/styles/blob/69cd543a65403f7a62339794703d3e7137187c77/the-open-university-numeric-superscript.csl

 

 

Should I go in and request a new update using the master branch?

 

Kelly

**Comment by kellyfk** [comment]
Thanks for the help. I am new to this. The update changed the title and added my name as a contributor. I’m completely unsure of what the protocols are for this but I would like to use the-open-university-numeric-superscript style with one minor change. They currently put quotes around the title of the article and I would like to remove those quotes. (I did that by changing true to false).

 

This is the original link

https://github.com/citation-style-language/styles/blob/69cd543a65403f7a62339794703d3e7137187c77/the-open-university-numeric-superscript.csl

 

 

Should I go in and request a new update using the master branch?

 

Kelly

**Comment by rmzelle** [comment]
If this is for personal use, there is no need to submit the change to this central repository. We try to avoid having multiple variants of the same style (especially if they deviate from the official style guide), but you should be able to just install your customized version on your own computer.

**Comment by kellyfk** [comment]
Ok, thanks. I couldn’t figure out how to do that. All of zotero’s instructions seem to indicate that I need to add it to the repository. I’ll go back to zotero and see if I can figure it out.

**Comment by rmzelle** [comment]
> All of zotero’s instructions seem to indicate that I need to add it to the repository.

No, that's not the case. Can you tell us which instructions you were looking at?

I'd like to point you to https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step#change_the_style_title_and_id and https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step#install_your_edited_style_with_zotero, for instructions on how to change the style title and ID (so that Zotero doesn't replace your custom version when we update the original) and on how to install your custom style.

**Comment by kellyfk** [comment]
Thank you, that was very helpful.


Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Pull request closed without merging**
