### PR TITLE
Update royal-society-of-chemistry.csl

### PR DESCRIPTION
**Pull request by damnation333**
via https://forums.zotero.org/discussion/65534/style-request-photochemical-photobiological-sciences-with-titles
Needs to be checked if all the RSC actually have adapted this new style including the title for journal articles.

### CODE REVIEW

**Comment by adam3smith** [comment]
From that thread it appears that is *not* the case so we need to turn this into an independent style, right?

**Comment by damnation333** [comment]
@adam3smith I think it might be worth to give the RSC a shout directly and find out what's going on from the horse's mouth. I can do that unless somebody else already had been in touch with them in the past?

**Comment by adam3smith** [comment]
please do. I don't think we have a direct contact there from the past. Feel free to invoke CSL ("I work with the Citation Style Language (CSL) project" or something along those line).

**Comment by damnation333** [comment]
Great, that's sent. Let's see what they say (and when). :)

**Comment by adam3smith** [comment]
@damnation333 I take it you never heard back? I'd suggest just going with a new indpendent style then as
royal-society-of-chemistry-with-title and changing the data in the journals repo to redirect Physical Chemistry Chemical Physics and Photochemical & Photobiological Sciences to that.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
