### PR TITLE
Create thesis-archaeology.csl

### PR DESCRIPTION
**Pull request by saraperga-3**
Adapted  style APA

### CODE REVIEW

**Comment by saraperga-3** [comment]
Hola
 Gracias por vuestra ayuda. No tengo claro que paso dar para solucionar los ultimos problemas. del #2275.
He validado el archivo actualizado en CSL Validator y he copiado el codigo en el archivo.

**Comment by saraperga-3** [comment]
Hola de nuevo,
He vuelto a validar el archivo en CSL Validator pero en versión 1. y me ha dado dos errores que he rectificado en Line 6 y Line 19. Los he rectificado. Espero haberlo realizado correctamente.  Un saludo

**Comment by adam3smith** [comment]
antes de todo lo demas: para que sirve el estilo? Una revista? El estilo de tesis para un departamento (cual)? Algo diferente?

**Comment by saraperga-3** [comment]
Hola
El estilo es para mi proyecto de tesis doctoral en la Universidad de
Alicante (España).

**Comment by rmzelle** [comment]
@saraperga-3, is there a webpage or printed style guide that describes your style format? We always try to find a URL that documents the CSL style (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link), and I would like it if we could use something more specific than https://www.ua.es/.

(feel free to respond in Spanish)

**Comment by rmzelle** [comment]
@saraperga-3, did you model this style after https://biblioteca.ua.es/en/you-study-and-learn/elaboration-and-management-of-bibliographic-citations/citation-and-bibliographic-reference.html (and more specifically, https://rua.ua.es/dspace/bitstream/10045/34027/1/Estilo_APA_doctorado.pdf)?

**Comment by POBrien333** [comment]
@rmzelle 
Just looking into this one.
The University of Alicante specifies to use a whole bunch of standard styles (ISO 690, APA, CSE, MLA, Vancouver, Chicago, "Harvard") and have style guides for all of those.
Checking the APA one they outline with the actual APA style I don't find any differences.
I therefore think the style made by the user here actually doesn't need to be on the repository. Also due to the inactivity we could close this, no?

**Comment by rmzelle** [comment]
@POBrien333, thanks for checking!

**Pull request closed without merging**
