### PR TITLE
Create IME-USP.csl

### PR DESCRIPTION
**Pull request by igorsteinmacher**
Style in accordance with the norms of Institute of Mathematics and Statistics (Computer Science) theses and dissertations.

### CODE REVIEW

**Comment by rmzelle** [comment]
Can you change the title to `<title>Universidade de São Paulo - Instituto de Matemática e Estatística</title>`? You can add an abbreviated title as `<title-short>USP-IME</title-short>`. Please also indicate which CSL style you based this on (see point 6 at https://github.com/citation-style-language/styles/wiki/Style-Requirements ).

Can you furthermore change the file name to "universidade-de-sao-paulo-instituto-de-matematica-e-estatística.csl", and update the style ID and "self" link accordingly? Thanks!

**Comment by rmzelle** [comment]
You can update your style by using the edit (pencil) icon at https://github.com/igorsteinmacher/styles/blob/patch-1/IME-USP.csl.

**Comment by adam3smith** [comment]
That should be universidade-de-sao-paulo-instituto-de-matematica-e-estatistica , no accent on the i for filename, id, and self link

**Comment by rmzelle** [comment]
Thanks. Two more things:

* Can you replace the `<rights/>` line with `<rights license="http://creativecommons.org/licenses/by-sa/3.0/">This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 License</rights>`?
* Can you remove the unused macros "edition", "event", "issued", "locators", and "publisher"?

Since you renamed the style, you can now edit it at https://github.com/igorsteinmacher/styles/blob/patch-1/universidade-de-sao-paulo-instituto-de-matematica-e-estatistica.csl

**Comment by igorsteinmacher** [comment]
I think now it is good to go. No issues from Travis

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
