### PR TITLE
Update united-nations-conference-on-trade-and-development.csl

### PR DESCRIPTION
**Pull request by MirUnctad**
Updated united-nations-conference-on-trade-and-development.csl

### CODE REVIEW

**Comment by adam3smith** [comment]
Do you work for UNCTAD? We have little ways to verify PRs for this style. Also, is the style manual online by now so that we could check on issues ourselves?

**Comment by MirUnctad** [comment]
Dear Sebastian,
Thank you for your email.

Yes, I work for UNCTAD.

And I think there is a manual.
I work with IT, my work email is ***@***.***, and I received a request to update the file from a colleague. I do not know all the details.

Please let me know how we can help, I will ask tomorrow morning to the colleague.

Thank you and best regards,
Mirco




________________________________

**Comment by adam3smith** [comment]
Great thanks -- if there is a style manual we could link to in the style, that'd be great, so please let me know what you find out, otherwise I'll merge this as is some time this coming week

**Comment by MirUnctad** [comment]
Good morning, I have added the link to the style manual; my colleagues will replace it at the same URL when the new version is ready. Could you please merge?

**Comment by adam3smith** [comment]
Thanks! (link and id are URIs, not URLs, hence the http)

**Pull request merged**
