### PR TITLE
Create necmettin-erbakan-universitesi-fen-ve-muhendislik-bilimleri-de…

### PR DESCRIPTION
**Pull request by muyaner**
…rgisi.csl

This style file was designated for "Necmettin Erbakan University Journal of Science and Engineering".
We are expected that this newly founded journal will be pubishen in Turkish Great Open Acces Journal platform, DergiPark.
We also hope that all authors who submit new manuscripts to this journal will use proposed template.
Dr. Mesut UYANER,
Editor
For correspondance: muyaner@erbakan.edu.tr, muyaner@yahoo.com

### CODE REVIEW

**Comment by rmzelle** [comment]
@muyaner, thanks! Is there already a website for this journal? We would like to be able to link to the "Instruction to authors" section that describes the citation format of the journal. (see also https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link)

**Comment by rmzelle** [comment]
Great, thanks!

Does this journal already have an print and/or online ISSN?

**Comment by muyaner** [comment]
Dear Rintze M. Zelle,

We have started to publish our journal just on-line.
In Turkey, the procedure to get e-ISSN a little bit different.
The ISSN Turkey, asks for us to publish at least one issue.
So we will apply to take e-ISSN approximately 3 months later.

As soon as getting e- ISSN, we will update our csl file.

Sincerely yours,

​​Mesut UYANER, Prof. Dr.

Necmettin Erbakan Üniversitesi
Fen Bilimleri Enstitüsü Müdür Yardımcısı
Adres: Selver Mahallesi Eski Meram Caddesi No:211 Meram/KONYA 
Telefon: 0 332 3212017- 3243182 

Havacılık ve Uzay Bilimleri Fakültesi
Uçak Mühendisliği Bölüm Başkanı
Adres: Kürden Mahallesi, Yeni Meram Cd. No:262, 42090 Meram/Konya, 
Telefon: 0332 325 1147

NEÜ Fen ve Mühendislik Bilimleri Dergisi Editörü
http://dergipark.gov.tr/neufmbd

muyaner@erbakan.edu.tr
 

    On Wednesday, January 9, 2019, 4:36:47 AM GMT+3, Rintze M. Zelle <notifications@github.com> wrote:  
 
 
Great, thanks!

Does this journal already have an print and/or online ISSN?

**Comment by rmzelle** [comment]
Okay, great. Once the journal is assign an e-ISSN, you can just mention it here, or update the style yourself by following our instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style. The style for this journal is at https://github.com/citation-style-language/styles/blob/master/necmettin-erbakan-universitesi-fen-ve-muhendislik-bilimleri-dergisi.csl.

**Pull request merged**
