### PR TITLE
Create vancouver-virican.csl

### PR DESCRIPTION
**Pull request by Shrlck-X**
This is an updated Vancouver-like Style that might be considered useful to the community. It has few minor adjustments over the original Vancouver Style and it includes DOI, PMID, and PMCID, if available. 

Example Citations
[1–3]
[4–6]
[7,8]

Example Bibliography
[1] Elgui de Oliveira D, Müller-Coan BG, Pagano JS. Viral Carcinogenesis Beyond Malignant Transformation: EBV in the Progression of Human Cancers. Trends Microbiol. 2016; 24:649–64. DOI:10/f8xn4d | PMID: 27068530; PMCID: PMC5489061.
[2] Müller-Coan BG, Caetano BFR, Pagano JS, Elgui de Oliveira D. Cancer Progression Goes Viral: The Role of Oncoviruses in Aggressiveness of Malignancies. Trends Cancer. 2018; 4:485–98. DOI:10/gdvtn2 | PMID: 29937047.
[3] Caetano BFR, Jorge BAS, Müller-Coan BG, Elgui de Oliveira D. Epstein-Barr virus microRNAs in the pathogenesis of human cancers. Cancer Lett. 2021; 499:14–23. DOI:10/ghmqwp | PMID: 33248209.
[4] Mares I. Firms and the welfare state: When, why, and how does social policy matter to employers? In: Hall PA, Soskice D, editors. Varieties of capitalism. The institutional foundations of comparative advantage, New York: Oxford University Press, 2001, p. 184–213
[5] Ahlquist JS, Breunig C. Country clustering in comparative political economy. Cologne: Max-Planck Institute for the Study of Societies, 2009
[6] Isaacson W. Steve Jobs. New York, NY: Simon & Schuster, 2011
[7] CSL search by example. Citation Style Editor. 2012. http://editor.citationstyles.org/searchByExample/ (Accessed: 15/Dec/2012)
[8] Hawking S. Properties of expanding universes. Doctoral thesis. University of Cambridge. DOI:10.17863/CAM.11283

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! As a general rule, we don't take custom styles based on individual preferences for the repository: the number of styles would be limitless. You're obviously free to share this on your github/homepage, but we don't think it's helpful to make it available via the centralized repository.

I am understanding correctly that this is based on your research group's preferences, right?

**Comment by Shrlck-X** [comment]
Dear Sebastian, thank you for your reply.

It is not based only on our preferences, It is an updated version of the
Vancouver Styles available in the repository (listed below). Even the
newest ones do not include DOI, PMID or PMCID.

- African Online Scientific Information Systems - Vancouver
<https://www.zotero.org/styles/african-online-scientific-information-systems-vancouver>(2021-03-19
22:33:38)
- Bibliothèque universitaire de médecine - Vancouver (Français)
<https://www.zotero.org/styles/bibliotheque-universitaire-de-medecine-vancouver>(2021-02-12
04:50:30)
- Cardiff University - Vancouver
<https://www.zotero.org/styles/cardiff-university-vancouver>(2018-02-08
05:26:22)
- Elsevier - Vancouver
<https://www.zotero.org/styles/elsevier-vancouver>(2019-10-15
15:13:52)
- Elsevier - Vancouver (author-date)
<https://www.zotero.org/styles/elsevier-vancouver-author-date>(2019-10-15
15:13:32)
- Imperial College London - Vancouver
<https://www.zotero.org/styles/vancouver-imperial-college-london>(2017-03-12
20:34:54)
- Nature Publishing Group - Vancouver
<https://www.zotero.org/styles/nature-publishing-group-vancouver>(2017-05-18
15:23:08)
- SAGE - Vancouver <https://www.zotero.org/styles/sage-vancouver>(2018-05-13
20:38:51)
- SAGE - Vancouver (brackets)
<https://www.zotero.org/styles/sage-vancouver-brackets>(2018-05-13 20:38:51)
- Springer - Vancouver
<https://www.zotero.org/styles/springer-vancouver>(2019-10-01
00:21:45)
- Springer - Vancouver (author-date)
<https://www.zotero.org/styles/springer-vancouver-author-date>(2017-05-18
15:23:08)
- Springer - Vancouver (brackets)
<https://www.zotero.org/styles/springer-vancouver-brackets>(2018-01-30
15:31:26)
- UCL University College - Vancouver (English)
<https://www.zotero.org/styles/ucl-university-college-vancouver>(2020-10-01
22:47:43)
- University of York - Vancouver
<https://www.zotero.org/styles/university-of-york-vancouver>(2017-12-07
04:15:37)
- Vancouver <https://www.zotero.org/styles/vancouver>(2016-06-19 21:20:29)
- Vancouver (author-date)
<https://www.zotero.org/styles/vancouver-author-date>(2016-06-19 21:20:29)
- Vancouver (brackets, no "et al.")
<https://www.zotero.org/styles/vancouver-brackets-no-et-al>(2016-06-19
21:20:29)
- Vancouver (brackets, only year in date, no issue numbers)
<https://www.zotero.org/styles/vancouver-brackets-only-year-no-issue>(2015-10-27
18:47:03)
- Vancouver (brackets)
<https://www.zotero.org/styles/vancouver-brackets>(2016-06-19
21:20:29)
- Vancouver (Français - Canada)
<https://www.zotero.org/styles/vancouver-fr-ca>(2021-02-12 04:50:30)
- Vancouver (superscript, brackets, only year in date)
<https://www.zotero.org/styles/vancouver-superscript-brackets-only-year>(2015-10-27
18:47:03)
- Vancouver (superscript, only year in date, no issue numbers)
<https://www.zotero.org/styles/vancouver-superscript-only-year>(2017-05-31
02:53:21)
- Vancouver (superscript)
<https://www.zotero.org/styles/vancouver-superscript>(2016-06-19 21:20:29)

As people are often requesting us this style, I believed it would be better
to share with the community in the repository.


Best regards,

deo


<http://www.fmb.unesp.br/>


*Prof. Dr. Deilson Elgui de Oliveira, Ph.D.*Professor Associado -
Departamento de Patologia
UNESP, Faculdade de Medicina de Botucatu
Av. Prof. Mário Rubens G. Montenegro, s/n
CEP 18618-687 - Botucatu, SP, Brasil
Tel.: +55 (14) 3880-1573 |  FAX: (14) 3815-2348
[image: ORCID iD icon] <https://orcid.org/0000-0001-5562-9648>
orcid.org/0000-0001-5562-9648

ℹ️

ATENÇÃO: Por favor, acrescente URGENTE ao assunto das mensagens de alta
prioridade
ATTENTION: Please, add URGENT to the subject of high-priority messages.




Em qua., 12 de mai. de 2021 às 12:45, Sebastian Karcher <
***@***.***> escreveu:

**Comment by adam3smith** [comment]
What published style guide is it based on?

**Comment by Shrlck-X** [comment]
It is bases no the ICMJE Recommendations
<https://en.m.wikipedia.org/wiki/ICMJE_Recommendations> (Uniform
Requirements for Manuscripts)
http://icmje.org/about-icmje/faqs/icmje-recommendations/

Em qua., 12 de mai. de 2021 12:58, Sebastian Karcher <
***@***.***> escreveu:

**Comment by adam3smith** [comment]
Hmm, I don't think so. The ICMJE are from 1979, so they don't include either of those. The _Citing Medicine_ implementation, which we follow for the standard Vancouver style, has both PM(C)ID and DOI as part of an _optional_ note and only one example of each among the ~100 examples for journal article citations. We have variants that use PMID/PMCID (https://www.zotero.org/styles?q=id%3Anational-library-of-medicine-grant-proposals ) and DOI (e.g. the Elsevier Vancouver one), and I'm not saying there's anything wrong with it, but we'd want to base this on some published guide.
For example, | doesn't appear in any sample citation in _Citing Medicine_; where they do use the DOI, it has a lowercase `doi:` prefix (and that should probably be https://doi.org/ instead) etc.

**Comment by Shrlck-X** [comment]
> Hmm, I don't think so. The ICMJE are from 1979, so they don't include either of those. 

I probably misunderstood your question. The so-called "Vancouver guidelines" is essentially based on ICMJE, and that's why I mentioned it.

>The _Citing Medicine_ implementation, which we follow for the standard Vancouver style, has both PM(C)ID and DOI as part of an _optional_ note and only one example of each among the ~100 examples for journal article citations. We have variants that use PMID/PMCID (https://www.zotero.org/styles?q=id%3Anational-library-of-medicine-grant-proposals ) and DOI (e.g. the Elsevier Vancouver one), and I'm not saying there's anything wrong with it, but we'd want to base this on some published guide.
> For example, | doesn't appear in any sample citation in _Citing Medicine_; where they do use the DOI, it has a lowercase `doi:` prefix (and that should probably be https://doi.org/ instead) etc.

I did not find a _Citing Medicine_ style, and I would be thankful if you indicate it in the repositorty. If you are referring to the NLM style at http://www.zotero.org/styles/national-library-of-medicine, it outdated and do not include DOI or PMID. Also, I am not sure if users looking for an updated Vancouver-based format style will find it easily in the repository.

For sure there are other styles that include PM(C)ID and DOI, and I did not research extensively the repository to found out what are those that are more or less compatible with the Vancouver format. I am just concerned with many students looking to a style similar to this one that we are proposing and do not find it. I frequently share it with my student and I wonder how many other people would benefit of it.

You can compare the NLM style and this one we are proposing in the images below.

**[NLM (grant proposals with PMCID/PMID)](https://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fnational-library-of-medicine-grant-proposals)**
image

**Vancouver-Virican**

image

**Comment by adam3smith** [comment]
From the Wikipedia page you link to:
> The citation style recommended by the ICMJE Recommendations, which is also known as the Vancouver system, is the style used by the United States National Library of Medicine (NLM), codified in Citing Medicine.

So our Vancouver styles follows _Citing Medicine_. We don't have a separate style called Citing Medicine because people don't tend to look for it under that name. We added the NLM one because people do look for it under that label (but it's just a link).

I don't really have an opinion about what constitutes an "outdated" citation style (arguably all of them are...), but my point is 
that, as a matter of both policy and practicality, we restrict styles on the repositories to those which explicitly follow published guidance from some entity that expects a large number of people to cite that way -- a publisher, a journal, a university, or a grant-giving organization.

That doesn't seem to be the case for this style. I don't doubt that it's useful for some people, but given the nature of the repository, we need to be able to tell, without the input of the original creator, whether a style is correct or not based on error reports. Without published guidance, that's not possible and we can't take this.

As I say above, we have absolutely no objections to you self-hosting & distributing this -- several of us have our own repos of styles we distribute separately for this reason. When distributed via github, styles install directly into Zotero and can be easily installed in Mendeley via the Raw link..

**Pull request closed without merging**
