### PR TITLE
Create geological-magazine

### PR DESCRIPTION
**Pull request by ms609**

### CODE REVIEW

**Comment by rmzelle** [comment]
@ms609, I'm closing this pull request for now because of inactivity. (if you get back to us we can re-open it)

**Comment by ms609** [comment]
Sorry, I missed the comments.  If you re-open the request I will make the suggested changes.

- Martin

**Comment by adam3smith** [comment]
thanks. You're good to go. Let us know if you have any questions.

**Comment by ms609** [comment]
Looks like someone else has beaten me to it and created geological-magazine.csl.  Marking request as closed.

**Pull request closed without merging**
