### PR TITLE
Fixed wrong page-range-format

### PR DESCRIPTION
**Pull request by luciomarinelli**

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks.

Could you create a new pull request, though, by following the instructions for "submitting changes to an existing style" described at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md? (in short, use the edit icon at https://github.com/citation-style-language/styles/blob/master/journal-of-science-and-medicine-in-sport.csl)

It's better to always make your changes to the latest version of a style in the CSL styles repository. This pull request includes a commit we already accepted in #2014, and we don't want that.

**Comment by adam3smith** [comment]
ugh, sorry, just merged the other one.

**Comment by adam3smith** [comment]
or did I merge the right one?

**Comment by rmzelle** [comment]
Okay, looks like we're all set, then.

(@luciomarinelli, my remarks still hold for any future changes you're like to submit for this style)

**Pull request closed without merging**
