### PR TITLE
Change The Condor to dependent style from The Auk

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by zuphilip** [comment]
Hm.. I don't understand what problem Travis has found. Any help?

**Comment by adam3smith** [comment]
the style for rhodora used Condor as a template -- now the template link is dead. I'd just add Keith Larson as a contributor there and delete the template link.

**Comment by zuphilip** [comment]
Thank you. I did what you suggested and Travis is happy again.

**Comment by adam3smith** [comment]
thanks!

**Pull request merged**
