### PR TITLE
Create smithsonian-institution-scholarly-press-note.csl

### PR DESCRIPTION
**Pull request by POBrien333**
closes https://github.com/citation-style-language/styles/issues/2867

### CODE REVIEW

**Comment by rmzelle** [comment]
(you can just leave a note at the top of the PR, instead of putting the status in the PR title)

**Comment by rmzelle** [comment]
(also, once this is ready, please leave a new comment so I get notified)

**Comment by rmzelle** [comment]
(why did you close this?)

**Comment by POBrien333** [comment]
I don't want to work on this one. I've referenced to this here though: https://github.com/citation-style-language/styles/issues/2867, so somebody else can pick it up.

**Comment by POBrien333** [comment]
Reopened and finished the work. I want to close that Issue: https://github.com/citation-style-language/styles/issues/2867

**Comment by POBrien333** [comment]
I'm an idiot. I made the botany style again.... Anyway, this is the adapted note style. Pretty much Chicago.

**Comment by POBrien333** [comment]
@rmzelle 
This one is ready.

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
