### PR TITLE
Erzincan Binali Yildirim University-Institute of Social Sciences

### PR DESCRIPTION
**Pull request by ahmedsaidyalcinkaya**

### CODE REVIEW

**Comment by ahmedsaidyalcinkaya** [comment]
Erzincan Binali Yildirim University

**Comment by adam3smith** [comment]
A couple of small change request. Just to make sure: this is meaningfully different from both the existing Chicago style and the other Turkish Chicago-type styles?

**Review by adam3smith — CHANGES_REQUESTED** [review]
Sorry -- @ahmedsaidyalcinkaya Somehow the actual change requests didn't get published. See above

**Comment by adam3smith** [comment]
I'm closing this for inactivity for now, but we're happy to re-open if you come back to work on this. Just leave a comment here.

**Pull request closed without merging**
