### PR TITLE
Create pensoft-journals.csl

### PR DESCRIPTION
**Pull request by teodorgeorgiev**
Adding a new style: pensoft-journals.csl

### CODE REVIEW

**Comment by POBrien333** [comment]
Thanks for making this style.
We recently had somebody ask for a style for a Pensoft journal, Neobiota, on the forums: https://forums.zotero.org/discussion/84512/style-request-neobiota-pensoft#latest

Is this Pensoft style a generic style used by a whole bunch of journals incl. Neobiota?

**Comment by teodorgeorgiev** [comment]
Thanks a lot for accepting this style! Yes, it is a generic style, and it is used by many of Pensoft's journals incl. Neobiota

**Comment by adam3smith** [comment]
@teodorgeorgiev thanks! Two quick questions:
1. For the citation of edited volumes, "Hancké B, Rhodes M, Thatcher M eds." looks odd to me; I'd expect "Thatcher M, Eds." or "Thatcher M (Eds)." -- this isn't covered in the style guide and presumably fairly rare, but could you get any guidance on this?
2. Re:
> Yes, it is a generic style, and it is used by many of Pensoft's journals incl. Neobiota

Would it be possible to get us a list of all journals (including their ISSN[s]) using this style so that we can add them as dependent styles and make the style easily findable for authors?

**Comment by teodorgeorgiev** [comment]
1. Sorry, my mistake ... it should be "Thatcher M (Ed.)" or "Hancké B, Rhodes M, Thatcher M (Eds)" [no dot after the closing bracket] if the editors are more than one... 
2. I will send you a complete list of our journals using this style later today

**Comment by teodorgeorgiev** [comment]
@adam3smith here is a list of all journals using pensoft-journals.csl 

In order to avoid confusion for the authors and to maintain the reference style coherent for all our journals, is it possible to take out the [zookeys.csl](https://github.com/citation-style-language/styles/blob/7c1df3e21abcee8e722dfc772ecae24c79661d0a/zookeys.csl), once the journals below are associate with pensoft-journals.csl?

Journal   Title | eISSN | ISSN | website
-- | -- | -- | --
African Invertebrates | 2305-2562 | 1681-5556 | https://africaninvertebrates.pensoft.net/
Nature Conservation | 1314-3301 | 1314-6947 | https://natureconservation.pensoft.net/
Comparative Cytogenetics | 1993-078X | 1993-0771 | https://compcytogen.pensoft.net/
Nota Lepidopterologica | 2367-5365 | 0342-7536 | https://nl.pensoft.net/
Metabarcoding and Metagenomics | 2534-9708 |   | https://mbmg.pensoft.net/
Pharmacia | 2603-557X | 0428-0296 | https://pharmacia.pensoft.net/
Arctic Environmental Research | 2658-7173 | 2541-8416 | https://aer.pensoft.net/
Neotropical Biology and Conservation | 2236-3777 |   | https://neotropical.pensoft.net/
Journal of Orthoptera Research | 1937-2426 | 1082-6467 | https://jor.pensoft.net/
MycoKeys | 1314-4049 | 1314-4057 | https://mycokeys.pensoft.net/
Italian Botanist | 2531-4033 |   | https://italianbotanist.pensoft.net/
Plant Sociology | 2704-6192 | 2280-1855 | https://plantsociology.arphahub.com/
Alpine Entomology | 2535-0889 |   | https://alpineentomology.pensoft.net/
Research Results in Pharmacology | 2658-381X |   | https://rrpharmacology.pensoft.net/
Herpetozoa | 2682-955X | 1013-4425 | https://herpetozoa.pensoft.net/
Acta Biologica Sibirica | 2412-1908 |   | https://abs.pensoft.net/
Check List | 1809-127X |   | https://checklist.pensoft.net/
BioRisk | 1313-2652 | 1313-2644 | https://biorisk.pensoft.net/
Travaux du Muséum National d’Histoire   Naturelle “Grigore Antipa” | 2247-0735 | 1223-2254 | https://travaux.pensoft.net/
Evolutionary Systematics | 2535-0730 |   | https://evolsyst.pensoft.net/
Subterranean Biology | 1314-2615 | 1768-1448 | https://subtbiol.pensoft.net/
PhytoKeys | 1314-2003 | 1314-2011 | https://phytokeys.pensoft.net/
Journal of Hymenoptera Research | 1314-2607 | 1070-9428 | https://jhr.pensoft.net/
Rethinking Ecology | 2534-9260 |   | https://rethinkingecology.pensoft.net/
NeoBiota | 1314-2488 | 1619-0033 | https://neobiota.pensoft.net/
Zoosystematics and Evolution | 1860-0743 | 1435-1935 | https://zse.pensoft.net/
ZooKeys | 1313-2970 | 1313-2989 | https://zookeys.pensoft.net/
Nuclear Energy and Technology | 2452-3038 |   | https://nucet.pensoft.net/
Deutsche Entomologische Zeitschrift | 1860-1324 | 1435-1951 | https://dez.pensoft.net/

**Comment by POBrien333** [comment]
Perfect that you have one style for all your journals and thanks for providing the list.
I will make the necessary PR to have all the styles created automatically. That will then also overwrite the zookeys.csl file.

**Comment by teodorgeorgiev** [comment]
@adam3smith 
Now I see the Pensoft Journals style in the Zotero interface, however, when I select it I get the following error: 
      "Received error from Zotero server: An error occurred."
This is from the console:
     "Request URL: https://api.zotero.org/users/2373123/items?format=bib&itemKey=P59GCP4B&locale=en-US&style=pensoft-journals
     Status Code: 500 Internal Server Error"

**Comment by adam3smith** [comment]
That'd be a Zotero error, but where exactly are you getting that? It looks fine to me.

**Comment by teodorgeorgiev** [comment]
I get this when I try to format a reference using the style

**Comment by adam3smith** [comment]
@dstillman  @tnajdek the Zotero web library seems to use an up-to-date list of CSL styles but the API isn't updated as regularly, leading to the error reported above for new styles. Would be good to synchronize the two.

@teodorgeorgiev thanks -- that's an issue for the Zotero web library only. It's not how most Zotero users, let alone CSL users, will use the style. Installing it in the Zotero desktop software and citing there works fine (and the web library will work eventually). In any case, not a problem with the style or something we at CSL can do anything about.

**Comment by dstillman** [comment]
Fixed — sorry about that. The Zotero API should now reflect new and updated styles within a few minutes of their being committed.

**Comment by teodorgeorgiev** [comment]
@adam3smith @dstillman thank you both for your help and prompt reaction!

**Comment by rmzelle** [comment]
Journal styles have been added. Thanks!

**Pull request merged**
