### PR TITLE
Create Comparative Population Studies

### PR DESCRIPTION
**Pull request by bwiernik**

### CODE REVIEW

**Comment by rmzelle** [comment]
@bwiernik, in general, I recommend against committing to your own "master" branch. It's much easier to either ignore it completely, and just rely on the fresh branches GitHub creates in your fork off of our repository when you create a new pull request via our repository, or just keep it up to date by pulling upstream commits, and creating new branches off of your own up-to-date "master" branch.

**Comment by bwiernik** [comment]
Yup. Sorry to make a mess of the repo.

**Comment by rmzelle** [comment]
Well, you can only create a mess in your own fork, so I don't really care :). Just giving a tip to make your own life easier.

**Comment by rmzelle** [comment]
(replaced by #2430)

**Pull request closed without merging**
