### PR TITLE
Create mind-and-language.csl

### PR DESCRIPTION
**Pull request by damnation333**
Per https://forums.zotero.org/discussion/64130/style-request-mind-language

### CODE REVIEW

**Comment by rmzelle** [comment]
@adam3smith, looks good to me. See http://onlinelibrary.wiley.com/doi/10.1111/mila.2016.31.issue-1/issuetoc for example papers.

**Comment by bwiernik** [comment]
It looks like citation layout should have parentheses affixes. All of the in-text citations and most of the footnote citations have parentheses around them. Across different papers I've looked at for this journal, it seems fairly common to have citations in footnotes that do not have parentheses if the footnote is one clause of the form "For additional information, see Strause 2003; Engel, 2006". But citations with parentheses are so much more common that it would be a huge pain for authors, I suspect, to have to type them themselves.

**Comment by rmzelle** [comment]
@damnation333, @bwiernik was clearly more eagle-eyed than me. Can you make his proposed change?

**Comment by rmzelle** [comment]
Thanks both!

**Pull request merged**
