### PR TITLE
Create critical-reviews-in-food-science-and-nutrition.csl

### PR DESCRIPTION
**Pull request by redleafnew**
Critical Reviews in Food Science and Nutrition

### CODE REVIEW

**Review by redleafnew — COMMENTED** [review]
delete unused macros

**Review by redleafnew — COMMENTED** [review]
delete text-case="title"

**Review by redleafnew — COMMENTED** [review]
text-case="sentence"

**Comment by redleafnew** [comment]
what should I do to be merged for this style?

**Comment by POBrien333** [comment]
This has been solved here already: https://github.com/citation-style-language/journals/pull/135

**Comment by adam3smith** [comment]
we still need to figure out merging the T&F pull, but closing here

**Pull request closed without merging**
