### PR TITLE
Create ZHAW Roger Müller.csl

### PR DESCRIPTION
**Pull request by literaturverwaltungZHAW**
This style is based on Roger Müller, ZitierGuide Leitfaden zum fachgerechten Zitieren in rechtswissenschaftlichen Arbeiten, 4. Auflage, Zürich 2016 (ISBN 978-3-7255-7583-1).

### CODE REVIEW

**Comment by rmzelle** [comment]
Thanks, and sorry for the wait.

I renamed the style after the ZitierGuide itself. If the ZHAW Zurich University of Applied Sciences uses only this style, we can add a so-called "dependent" CSL style titled "Zürcher Hochschule für Angewandte Wissenschaften" that uses the same citation format.

**Comment by literaturverwaltungZHAW** [comment]
Hi,
Thank you for your work.
No, the ZHAW uses a lot of different styles. So there can’t be a style titled Zürcher Hochschule für Angewandte Wissenschaften.
It is good at it is 😊
Kind regards
Carina

Von: Rintze M. Zelle <notifications@github.com>
Gesendet: Sonntag, 15. September 2019 22:59
An: citation-style-language/styles <styles@noreply.github.com>
Cc: ZHAW Literaturverwaltung <literaturverwaltung@zhaw.ch>; Author <author@noreply.github.com>
Betreff: Re: [citation-style-language/styles] Create ZHAW Roger Müller.csl (#4242)


Thanks, and sorry for the wait.

I renamed the style after the ZitierGuide itself. If the ZHAW Zurich University of Applied Sciences uses only this style, we can add a so-called "dependent" CSL style titled "Zürcher Hochschule für Angewandte Wissenschaften" that uses the same citation format.

**Comment by rmzelle** [comment]
Something like "Zürcher Hochschule für Angewandte Wissenschaften - ZitierGuide (Roger Müller)" would be an option as well, but if you don't mind pointing your users to the "ZitierGuide: Leitfaden zum fachgerechten Zitieren in rechtswissenschaftlichen Arbeiten (Roger Müller)" style itself, that's even better.

**Comment by literaturverwaltungZHAW** [comment]
"Zürcher Hochschule für Angewandte Wissenschaften - ZitierGuide (Roger Müller)" is a good solution. Thank you for suggesting! So it is easier to find for our students.

**Comment by literaturverwaltungZHAW** [comment]
We have a list for the citation styles of our different schools: [https://www.zhaw.ch/de/hochschulbibliothek/schreiben-publizieren/#c98258]
You find the ZitierGuide under _School of Management and Law_ - _Rechtswissenschaftliche Arbeiten_.

**Comment by rmzelle** [comment]
Great, thanks. How about "Zürcher Hochschule für Angewandte Wissenschaften - Rechtswissenschaft (Roger Müller)", or do you prefer "Zürcher Hochschule für Angewandte Wissenschaften - ZitierGuide (Roger Müller)"?

**Comment by literaturverwaltungZHAW** [comment]
Sorry for the delay - We would prefer the second option: "Zürcher Hochschule für Angewandte Wissenschaften - ZitierGuide (Roger Müller)". Thank you for your support!

**Comment by rmzelle** [comment]
> We would prefer the second option: "Zürcher Hochschule für Angewandte Wissenschaften - ZitierGuide (Roger Müller)". Thank you for your support!

Added: https://github.com/citation-style-language/styles/pull/4311

Thanks!

**Pull request merged**
