### PR TITLE
WCAG compliant AGLC (subsequent references)

### PR DESCRIPTION
**Pull request by shreeyaahrc**
Removes Ibid for subsequent references to ensure this version is WCAG compliant.

### CODE REVIEW

**Comment by adam3smith** [comment]
Could you say a bit more about the context of this? CSL formats citation style according to existing style guides, so if there is a problem with using ibid for accessibility wouldn't the place to address this be the style guide, not an attempt to automate whatever it prescribes? (And AGLC just published a fourth edition, so this may have changed anyway?)

**Comment by rmzelle** [comment]
@shreeyaahrc, yes, like @adam3smith said, we always do our best to have our citation styles match the official style guide requirements. Please let us know whether you're proposing this change because of some official guidance, by AGLC or another party, or whether this is a personal preference.

**Comment by shreeyaahrc** [comment]
Thanks Adam, Rintze

So, here's the background. AGLC4 still abides by the same ibid rules as AGLC3. However, the Australian government's accessibility requirements mandate that ibid (and see note x above) cannot be used for accessibility reasons. I am working on helping a government agency use Zotero for their referencing needs, and we are trying to figure out how best to massage the AGLC style for Zotero to make this work. One work around that we have looked at is to create an in house style that is available on the agency's servers for download, but given this is a government requirement, there will be other government agencies who will have to comply. In light of that, I was wondering whether it was possible to have it available through the Central repository as AGLC WiCAG compliant.

Thanks

Shreeya
________________________________

**Comment by rmzelle** [comment]
> the Australian government's accessibility requirements mandate that ibid (and see note x above) cannot be used for accessibility reasons.

Thanks for getting back to us. Can you point us to those government requirements, in particular the section that discusses the use of "ibid."? And do those requirements specifically mention AGLC, or are they more general?

**Comment by adam3smith** [comment]
(If we do this -- and it sounds like there may be a good case to -- I'd feel better if we just describe what the style doesn't do, i.e. no ibid, no supra. WCAG compliance, of course, is massively complex and I don't think we should suggest that using a given citation style will actually do more that a tiny, tiny bit towards compliance.)

**Comment by rmzelle** [comment]
Hi @shreeyaahrc, we're closing this issue because we haven't heard from you in a while. Note that we can always reopen this issue if you get back to us.

**Pull request closed without merging**
