### PR TITLE
Create revue-internationale-durbanisme.csl

### PR DESCRIPTION
**Pull request by everdeil**
some details updated

### CODE REVIEW

**Comment by POBrien333** [comment]
via https://forums.zotero.org/discussion/comment/401947#Comment_401947

**Comment by POBrien333** [comment]
Do you remember the style you based this on?
One of the requirements is to acknowledge the work of the template style creator.
See: https://github.com/citation-style-language/styles/blob/master/STYLE_REQUIREMENTS.md#csl-style-repository-requirements

Also, since the style has a default-locale set, please include (francais) in the title of your style. See for example: https://www.zotero.org/styles?q=id%3Aassociation-de-science-regionale-de-langue-francaise

**Comment by adam3smith** [comment]
Thanks; in addition to the two thing POBrien333 mentions, could you link to the instructions for authors?

**Comment by adam3smith** [comment]
@everdeil let us know if you need any help with this

**Comment by everdeil** [comment]
Hello
I have submitted it there
https://github.com/everdeil/styles/commit/b129e6b2e3a3ed3fab4852e3e3d4239dae3c134c
I hope it meets the requirements.
Best
Eric

**Comment by bwiernik** [comment]
Please edit the file in this pull request

**Comment by everdeil** [comment]
Thanks. I did it.
The answer is it is again failed but I don't understand where is the issue.
Can you please help
Best
Eric
Finished in 1 minute 22.68 seconds (files took 48.83 seconds to load)
170957 examples, 1 failure

Failed examples:

rspec ./spec/repository_spec.rb:25 # The CSL Style Repository may not
contain extra files (make sure styles have a ".csl" extension)
/opt/hostedtoolcache/Ruby/3.0.2/x64/bin/ruby
-I/home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.10.1/lib:/home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.10.3/lib
/home/runner/work/styles/styles/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.10.1/exe/rspec
--pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --require spec_helper.rb
--format Fuubar --color --format json --out spec/sheldon/ci.json failed
Error: Process completed with exit code 1.

**Comment by POBrien333** [comment]
Currently, you're making new PRs, instead of just editing this one. I know it can be confusing. To edit the current PR, see this screenshot:
image

**Comment by everdeil** [comment]
Frankly, it's not obvious when you're not used to the site.
If I am on page Create revue-internationale-durbanisme.csl #5974 I don't know how to edit it again.
So I have edited it as a new pull: github.com/citation-style-language/styles/pull/6037/files
Can it be checked from there?

**Comment by POBrien333** [comment]
I provided you with a screenshot, marked where you need to click. I think you're looking at our replies only in your emails? If you come to the website, you will have a better overview.

**Comment by adam3smith** [comment]
Thanks!

**Comment by POBrien333** [comment]
The style has been fixed for you, reviewed and merged to the repository back in June. You don't need to do anything else. 
https://www.zotero.org/styles?q=revue-internationale-durbanisme

**Pull request merged**
