### PR TITLE
Updated style for Informal Logic

### PR DESCRIPTION
**Pull request by waleedmebane**
Detailed list of changes is in the commit message for the file (informal-logic.csl).

### CODE REVIEW

**Comment by rmzelle** [comment]
@waleedmebane, thanks. Could you resubmit this version by following the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style

That will ensure you're always working from the most recent version in the repository and avoid the type of merge conflict I'm seeing here.

**Comment by rmzelle** [comment]
(I went ahead and merged this myself in https://github.com/citation-style-language/styles/pull/4831)

**Comment by waleedmebane** [comment]
@rmzelle Thanks. I read your advice but just hadn't gotten back to it, yet.  I'll do that next time.

**Comment by rmzelle** [comment]
Sounds good!

**Pull request closed without merging**
