### PR TITLE
Add dependent style for Geology Intermountain West

### PR DESCRIPTION
**Pull request by inkenbrandt**
Follows the Utah Geological Survey Style

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks! This needs to go into the /dependent subfolder. Instructions for moving files on github are here: https://help.github.com/articles/moving-a-file-to-a-new-location/

**Comment by rmzelle** [comment]
The style file name also needs to be updated to include the "of the" of the journal title.

**Comment by adam3smith** [comment]
Great, thanks!

**Comment by rmzelle** [comment]
@adam3smith, can you strip the XML comment? That might cause issues.

**Comment by adam3smith** [comment]
done

On Mon, Jan 11, 2016 at 10:05 AM, Rintze M. Zelle <notifications@github.com>
wrote:

> @adam3smith <https://github.com/adam3smith>, can you strip the XML
> comment? That might cause issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/citation-style-language/styles/pull/1858#issuecomment-170597698>
> .
>



-- 
Sebastian Karcher, PhD
www.sebastiankarcher.com

**Comment by rmzelle** [comment]
Thanks!

**Pull request merged**
