### PR TITLE
Create droit-belge-centre-de-droit-prive-ulb.csl

### PR DESCRIPTION
**Pull request by rafjaf**
Citation style which can be used in French for Belgian law references

### CODE REVIEW

**Comment by rmzelle** [comment]
@rafjaf, thanks. Is this style specific to the Centre de droit privé – Université Libre de Bruxelles (https://unifam.ulb.ac.be/), or does it follow the Guide des Citations, références et abréviations juridiques (6ème édition) you linked to? If the latter, we would typically name the style after the style guide, instead of after the university department.

**Comment by rafjaf** [comment]
Thank you for your swift reply!
It is mostly based on the Guide des citations, but with some minor local 
variations, hence the name of the style.
However, if you think it preferable to name the style after the Guide, fine 
by me.
Best regards,
Rafaël Jafferali
Le 15 novembre 2020 18:16:58 "Rintze M. Zelle" <notifications@github.com> a 
écrit :

**Comment by rmzelle** [comment]
> It is mostly based on the Guide des citations, but with some minor local variations, hence the name of the style.

Are those local variations described in a citation manual somewhere? We always to try link the CSL style to the document describing the desired format.

**Comment by rafjaf** [comment]
Thank you for your comments. Pursuant to them, I have made a new commit in which (i) I changed the name to make a direct reference to the Guide des citations and (ii) added a link to a short manual describing the differences with the Guide. I hope this meets your comments. Best regards, Rafaël Jafferali

**Comment by rmzelle** [comment]
[Guide des citation, références et abréviations juridiques CSL.docx](https://github.com/citation-style-language/styles/files/5551152/Guide.des.citation.references.et.abreviations.juridiques.CSL.docx)

**Comment by rmzelle** [comment]
Great, thanks!

**Pull request merged**
