### PR TITLE
Update harvard-stellenbosch-university.csl

### PR DESCRIPTION
**Pull request by Yusufras**
hanging-indent="true"

### CODE REVIEW

**Comment by Yusufras** [comment]
made a change to bibliography

hanging-indent="true"

**Comment by rmzelle** [comment]
Thanks!

**Comment by Yusufras** [comment]
Can you check my changes. Nothing seemes to happen? I made changes to 3 styles?

**Comment by rmzelle** [comment]
What changes?

You only have one open pull request (https://github.com/citation-style-language/styles/pulls/Yusufras) at https://github.com/citation-style-language/styles/pull/2234, which I haven't merged yet because I made a comment to which you haven't yet responded (https://github.com/citation-style-language/styles/pull/2234#discussion_r87641203).

(the same pull request also has changes for harvard-stellenbosch-university.csl (https://github.com/citation-style-language/styles/pull/2234/files#diff-6d7b03e05501fd967882bb5a8d81c9cf), but we already merged those in in another pull request (https://github.com/citation-style-language/styles/pull/2295/files)).

**Comment by Yusufras** [comment]
Sorry for the delays. I made the change know as requested. 

I saw the pull request for Harvard-Stellenbosch-University, but when i test it in a document it is still the same. I need the bibliography to be indent, and it seems that it was not updated by Mendeley?

**Comment by rmzelle** [comment]
> it seems that it was not updated by Mendeley?

Yes. My copy of Mendeley Desktop also still shows an older version from May 12th. I've reported the problem to somebody who works at Mendeley, but you could contact them yourself as well.

**Comment by rmzelle** [comment]
@Yusufras, I just checked Mendeley Desktop, and it now shows the latest version of the Stellenbosch style, so it looks like their updating problem has recently been fixed.

**Pull request merged**
