### PR TITLE
Update instituto-brasileiro-de-informacao-em-ciencia-e-tecnologia-abn…

### PR DESCRIPTION
**Pull request by diegojmacedo**
…t.csl

Algumas melhorias conforme a norma NBR 6023:2018.

### CODE REVIEW

**Comment by rmzelle** [comment]
@deivdy, @andreappel, would you like to review these changes before I accept them?

**Comment by andreappel** [comment]
Yes, @rmzelle. I would review and also replicate the changes to the abbreviated branch/ version by this weekend.

**Comment by andreappel** [comment]
@rmzelle I've just finished reviewing the update. Also took the opportunity to improve overall code and to create the documentation. Not sure if I followed the correct procedure to submit the reviewed file.

**Comment by rmzelle** [comment]
@diegojmacedo, @andreappel, thanks both.

**Comment by andreappel** [comment]
Thank you @rmzelle. Could you also please update https://github.com/citation-style-language/styles/blob/master/instituto-brasileiro-de-informacao-em-ciencia-e-tecnologia-abnt.csl? I will create an update/pull request with the changes that @diegojmacedo and I have made.

**Pull request closed without merging**
