### PR TITLE
Update bluebook-law-review.csl

### PR DESCRIPTION
**Pull request by fettingderek**
Fixed else clause in source macro.

### CODE REVIEW

**Comment by mattluce** [comment]
Can this be merged?

**Comment by fettingderek** [comment]
Can this be merged please?

**Comment by adam3smith** [comment]
Sorry this took so long. 
I agree with the switch to italics, but I'm not sure moving volume to the back is right. My understanding of BB citations for books (which presumably is the most important category in `else` is that they should begin with the volume?

**Comment by fettingderek** [comment]
Hello,
I've updated the style to display volume ahead of authors for books (instead of in the source macro), and to make book titles small caps.

**Comment by adam3smith** [comment]
Great, thanks!

**Pull request merged**
