### PR TITLE
Create uludag-universitesi-sosyal-bilimler-enstitusu (full note).csl

### PR DESCRIPTION
**Pull request by mtarakci**

### CODE REVIEW

**Comment by bwiernik** [comment]
Is there a reason you keep opening and closing pull requests? If you need to make additional changes to the style, you can just make new commits to your GitHub branch, and they will be reflected automatically in the pull request. No need to close it and re-open.

**Comment by mtarakci** [comment]
@bwiernik , 
Csl bot was saying that there was a problem in the title of the project (or of the style). Assuming that it might be project title, I changed the names. Later, I learned that it's a problem that the title of my style and zotero id was not compatible. 

I feel sorry for disturbing you and interrupting your routine.

**Comment by bwiernik** [comment]
Not a problem, it's just easier for the CSL folks to track pull requests if all of the relevant changes happen in one request.

**Comment by mtarakci** [comment]
I am finished with the project. This is for Social Sciences Institute of Uludag University (Bursa, TURKEY). MA and Phd Theses could be written within Zotero or Mendeley through this project. 
Institute's guide for authors can be found at: http://www.uludag.edu.tr/dosyalar/sosyalbilimler/2016%20Duyurular/SBE%20TEZ%20YAZ.%20KIL.(YEN%C4%B0)%2023.09.2016%20(1).pdf

With my best wishes. 

And thank you very much for the gorgeous programs such as Zotero/Mendeley, Csl Editor and this web site.

**Comment by mtarakci** [comment]
I edited the style from the beginning.

**Comment by mtarakci** [comment]
@bwiernik 
This is final. I did my best. Any idea or improving is welcome.

**Comment by mtarakci** [comment]
Sorry. This style is on of those that cause the conversion problem. 
I suspect that I deleted a part of a macro which inserts the doi number. 
I am working on it to solve the problem.

**Comment by rmzelle** [comment]
> I am working on it to solve the problem.

If I understand correctly, you want to make some additional changes to this style. Try to fix it in this pull request. I'll make a few changes myself to the style title and ID. And do you know which existing Chicago CSL style you started from? We'd like to link to that style with a "template" link (https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link). 

(this pull request replaces #2912, #2911, #2910, #2909; see also #2734)

**Comment by mtarakci** [comment]
@rmzelle 
Thank you very much. This style started with Chicago Manual of Style (full note). 
Now it seems to work properly. May be your changes comes in useful.

**Comment by mtarakci** [comment]
OK. I added variable for number of volumes at some necessary places. 
That's fine for me now.

**Comment by rmzelle** [comment]
@adam3smith, good to go from my side.

**Comment by rmzelle** [comment]
Thanks! (you can create new pull requests if you need to make any further edits. See https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style)

**Pull request merged**
