### PR TITLE
Create cryptogamie, bryologie

### PR DESCRIPTION
**Pull request by Zoosystema**

### CODE REVIEW

**Comment by adam3smith** [comment]
Thanks -- it looks like all of these styles are identical, is that right? If so, what's the publisher they're from? Is there a styleguide? And did you start with any style as a template?

**Comment by Zoosystema** [comment]
Thanks for your help !
Indeed they are the Csl for all the journals of the Muséum national d'Histoire naturelle, in Paris. 
All journals have the same format. I am a desk editor, and an author helped me to create this style but I do not know from which style he starts. I can ask him…

**Comment by adam3smith** [comment]
Perfect. Would you be able to get us the following information:
1. A link to the guide where this citation style is described
2. If at all possible, the style the author started from (so yes, please do ask)
3. An .xlsx (Excel) file with the following columns: Name of Journal, ISSN, eISSN that contains all your journals? We'll use that to automatically create style copies that are easier to maintain as the separate styles you've submitted.

Do let me know if you have any questions (and do feel free to write in French if that's at all easier for you)

**Comment by Zoosystema** [comment]
Ok, I'll do this as soon as possible.

**Comment by Zoosystema** [comment]
[MNHN_journals.xlsx](https://github.com/citation-style-language/styles/files/3740032/MNHN_journals.xlsx)

Here is the table you asked me. I also added columns for the category field and for the links to the authors guideline which are different for each journal.

Finallly the author anwered that he didn't use any stylesheet, he created it directly.
Tell me if you need other informations.

**Comment by adam3smith** [comment]
That's perfect, thank you! We'll take it from here.

**Comment by Zoosystema** [comment]
Great, Thank you for your help.

**Comment by POBrien333** [comment]
I've created the automatic styles based on that .xlsx.
Let me know if this is all good.

**Comment by Zoosystema** [comment]
Thanks. I have two questions:
• is it normal that the journal Cryptogamie, Bryologie is missing in the table? Otherwise all if fine.
• why there is this link in the template?  <link href="http://www.zotero.org/styles/american-chemical-society" rel="independent-parent"/>

**Comment by POBrien333** [comment]
With this PR here it will add an independent style for Cryptogamie, Bryologie.
The other PR I made, #83, will then automatically create the other styles for the missing MNHN journals, hence it is missing in that list.

**Comment by Zoosystema** [comment]
So ok, thanks for the explanation

**Comment by Zoosystema** [comment]
An why is there a link toward american chemical society in the template ?

**Comment by POBrien333** [comment]
Check it here, I linked the wrong PR.
https://github.com/citation-style-language/journals/pull/83/files

No need to worry. It'll get reviewed and checked.

**Comment by Zoosystema** [comment]
ok, it looks fine for me.
Thanks.

**Comment by Zoosystema** [comment]
Dear POBrien333, before the discussion closes, can you give me news of the style? Is it deposited, should I do something? Thanks for your help.

**Comment by POBrien333** [comment]
@adam3smith and @rmzelle, the main curators of the repository, will be able to answer the question.
(and no, it's not deposited)

**Comment by rmzelle** [comment]
@Zoosystema, I (finally) added the styles to our repository. Apologies for the long wait.

**Comment by Zoosystema** [comment]
Thank you @rmzelle !

**Comment by Zoosystema** [comment]
Hi @POBrien333 and @rmzelle We are going to welcome in our publications a new journal which leaves the private publisher Elsevier to pass in Open access with us. 
Name of Journal : Comptes rendus Palevol
ISSN: 1631-0683
We would therefore like to create the style sheet linked to the CSL Muséum national d'Histoire naturelle.
and delete the old style sheet linked to Elsevier  <title>Comptes rendus - Palevol</title>
Please tell me how I should proceed.

**Comment by POBrien333** [comment]
Thanks @Zoosystema 

I have made the necessary Pull Requests to add it to the MNHN sjournals and remove it from Elsevier.
Over to Rintze.

**Pull request merged**
