### PR TITLE
MLA: Add container-author to other-contributors

### PR DESCRIPTION
**Pull request by bwiernik**
From https://forums.zotero.org/discussion/comment/333958/#Comment_333958

How should we address the logic for L140?

### CODE REVIEW

**Comment by bwiernik** [comment]
@adam3smith  Any changes you wanted here?

**Comment by bwiernik** [comment]
@adam3smith Any changes you wanted here? How should we address the logic for L140?

**Comment by adam3smith** [comment]
Sorry this is taking so long

**Comment by adam3smith** [comment]
sorry this took forever. See if this makes sense to you, please.

**Comment by bwiernik** [comment]
That looks good to me

**Comment by adam3smith** [comment]
Thanks!

**Pull request merged**
