### PR TITLE
add new T&F dependent styles and style updates

### PR DESCRIPTION
**Pull request by adam3smith**

### CODE REVIEW

**Comment by rmzelle** [comment]
Just seeing that we still have to deal with this, and that you already did some detective work in https://github.com/citation-style-language/utilities/commit/2b53ca8deba7e63373aec3bca5265619daae280f#commitcomment-8236657

**Comment by rmzelle** [comment]
@adam3smith, did you mean to close this?

**Comment by adam3smith** [comment]
no. Side effect of fighting with rebase. sigh. I'll have to redo this, but I might as well request an up to date list from T&F and work off of that.

**Comment by rmzelle** [comment]
(I often make a backup branch when I'm about to do a tricky rebase)

**Comment by adam3smith** [comment]
yeah, problem here (and also cause for the initial messy commit) was that I usually never commit to master on a fork, so rebasing master is never an issue. It didn't even occur to me that I had unmerged commits on master until you pointed out this was closed/deleted.

**Pull request closed without merging**
