### PR TITLE
Fix extra space between citation number and author in pnas.csl

### PR DESCRIPTION
**Pull request by simonster**

### CODE REVIEW

**Comment by adam3smith** [comment]
thanks!

**Comment by adam3smith** [comment]
@rmzelle @zuphilip -- we may have more of these and they mess with the left-alignment of the citations that have more than 1 line. We should take a closer look.

**Comment by zuphilip** [comment]
Okay, I searched for the same pattern
```
<macro name="author">\s*\r\n\s*<names variable="author"[^>]*prefix=" "
```
and corrected the resulting other case. Do you think there are still more such cases? If yes, any ideas how to search for them in an easy way?

**Comment by adam3smith** [comment]
I think the other scenario would be if the prefix is set on the author macro itself.
```pcregrep -Ml '<text variable=\"citation-number\"[^\/]*\/>\n\s*<text macro="author"[^\/]*prefix' *.csl |xargs grep -l 'second-field-align'```

gives me this list, which merits a closer look. Feel free to have a go at it, I'm currently mainly trying to wrangle the massive Wiley submission in shape.

acta-anaesthesiologica-taiwanica.csl
advanced-engineering-materials.csl
advanced-materials.csl
advances-in-complex-systems.csl
african-journal-of-emergency-medicine.csl
alexandria-journal-of-medicine.csl
american-physics-society.csl
american-society-of-mechanical-engineers.csl
angewandte-chemie.csl
archives-of-oral-biology.csl
australasian-emergency-nursing-journal.csl
biochimica-et-biophysica-acta.csl
biology-of-reproduction.csl
biomed-research-international.csl
chinese-journal-of-aeronautics.csl
drug-testing-and-analysis.csl
elsevier-vancouver.csl
elsevier-without-titles.csl
elsevier-with-titles-alphabetical.csl
elsevier-with-titles.csl
engineering-in-life-sciences.csl
flavour-and-fragrance-journal.csl
free-radical-research.csl
human-pathology.csl
international-journal-of-gynecology-and-obstetrics.csl
international-journal-of-osteopathic-medicine.csl
journal-francais-dophtalmologie.csl
journal-of-adolescent-health.csl
journal-of-basic-microbiology.csl
journal-of-cellular-and-molecular-medicine.csl
journal-of-integrated-omics.csl
journal-of-separation-science.csl
metallurgical-and-materials-transactions.csl
new-solutions.csl
proteomics.csl
small.csl
transactions-of-the-materials-research-society-of-japan.csl

**Comment by rmzelle** [comment]
@adam3smith, there is Wiley data?

@simonster, does this mean that you're going to submit your monkey business to PNAS? If so, good luck!

**Comment by adam3smith** [comment]
no, sorry. Taylor and Francis. Both blue logos...

**Comment by rmzelle** [comment]
:monkey:

**Pull request merged**
