### PR TITLE
Create the-sociological-review.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/86762/style-request-the-sociological-review#latest

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, if this is APA style, are you sure the localization should be "en-GB"?

**Comment by rmzelle** [comment]
@bwiernik, do you know if the latest APA CSL style behaves well with "en-GB" as locale? (we have a UK journal here that says it's using APA style, so I'm wondering if we should keep it with "en-US" or could have the dependent style override the locale to "en-GB")

cc @adam3smith

**Comment by adam3smith** [comment]
The terms are all defined using lang="en" and the style doesn't use quotes, so the only thing that will change is the date format:
It's "February 13, 2021" in en-US and "13 February 2021" in en-GB. If the styleguide doesn't specify the date format and only says APA, I'd assume the US format is correct and use en-US

**Comment by bwiernik** [comment]
Some item types like magazines give the bibliography date as (2020, September 4)--not sure if it's worth bothering with a new style just to modify that.

**Comment by rmzelle** [comment]
Thanks all!

**Pull request merged**
