### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by yrg23**
Karabuk University csl file

### CODE REVIEW

**Comment by yrg23** [comment]
sorry i am newbie. so what now?

**Comment by adam3smith** [comment]
> sorry i am newbie. so what now?

Like the automated message says:

> One of our human volunteers will try to get in touch soon (usually within a week).

**Comment by rmzelle** [comment]
Thanks for your submission. Is there an online style guide available for this style? Per https://github.com/citation-style-language/styles/wiki/Style-Requirements#10---documentation-link, we typically require each CSL style to include a link to the format it describes.

**Comment by rmzelle** [comment]
Thanks! Did you base this on an existing CSL style? If so, we'd like to know which one, so we can add a "template" link (see https://github.com/citation-style-language/styles/wiki/Style-Requirements#8---template-link)

**Comment by rmzelle** [comment]
And is this style used throughout the university or only at the faculty of Natural and Applied Sciences (FEN BİLİMLERİ ENSTİTÜSÜ)?

**Comment by yrg23** [comment]
i have carried out your demands. Thanks...

**Comment by rmzelle** [comment]
Thanks!

Note that we made a few changes to your style. If you wish to make future changes to this style, please follow our instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style.

**Pull request merged**
