### PR TITLE
Update netherlands-journal-of-geosciences-geologie-en-mijnbouw.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/91633/style-request-netherlands-journal-of-geosciences-geologie-en-mijnbouw#latest

### CODE REVIEW

**Comment by POBrien333** [comment]
@bwiernik 
I fixed the style as per the above thread, but get the number-of-pages duplicated like such:
`Isaacson, W., 2011. Steve Jobs (630 pp.). Simon & Schuster (New York, NY): 630 pp.`

Do you have an idea how to tackle this issue?

**Comment by bwiernik** [comment]
You have `<text macro="locators"/>` on line 812, but `locators` is also called as part of the condition at line 527 in the `description` macro:

```
        <else-if type="book interview manuscript motion_picture musical_score pamphlet post-weblog speech webpage" match="any">
          <group delimiter="; ">
            <text macro="locators"/>
            <text macro="secondary-contributors"/>
          </group>
        </else-if>
```

Either remove `locators` from there or add a new condition without it for the offending types.

**Comment by POBrien333** [comment]
yup :)

**Comment by bwiernik** [comment]
Thanks!

**Pull request merged**
