### PR TITLE
New style vancouver-bium-fr

### PR DESCRIPTION
**Pull request by alerac**
* Added a custom Vancouver style for the
  Lausanne (CH) University Library of Medicine

### CODE REVIEW

**Comment by alerac** [comment]
Hello,

Do you think there is a chance that our vancouver style for the students of the faculty of Biology and Medicine at the Lausanne University (UNIL) would be accepted into the Zotero repository ?

The CSL style did pass all the automated checks last week but I was wondering if maybe I had to make other corrections. Or if you consider this style would not be eligible ?

Many thanks for all your work.

Alex

**Comment by adam3smith** [comment]
Apologies for the long wait -- will look asap

**Comment by alerac** [comment]
> Apologies for the long wait -- will look asap
No problems. Thank you!

**Comment by adam3smith** [comment]
@rmzelle could you check metadata & merge please? Not sure about naming here.

**Comment by rmzelle** [comment]
Thanks! (@alerac, I changed the title and file name a little to be more in line with the rest of our styles)

**Comment by alerac** [comment]
> Thanks! (@alerac, I changed the title and file name a little to be more in line with the rest of our styles)

Many thanks to you @rmzelle! Ok no problems!

@adam3smith Many thanks also for the clean-up and reformat referenced [here](https://github.com/citation-style-language/styles/pull/3952/commits/9848130d2895304696d65e80d2ca82b56f60089a)

I will just close my fork and propose an update with a new pull request soon. Because in the corrections you made (line 517 removed) the `<text variable="note" suffix=" "/>` should be present. I managed to have the webpage date (if any) in the Extra field in addition to the website date.

if the line `<text variable="note" suffix=" "/>` is not present the reference is then not correct. Below an image showing this. Reference 1 is not correct. Reference 2 and 3 are correct.

Many thanks again for your time and all your good work!!

examples

**Comment by rmzelle** [comment]
> I will just close my fork and propose an update with a new pull request soon.

Note that it's generally not necessary to close/delete a fork on GitHub. You can just follow the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style for updating your style.

> Because in the corrections you made (line 517 removed) the `<text variable="note" suffix=" "/>` should be present. I managed to have the webpage date (if any) in the Extra field in addition to the website date.

@adam3smith, do we have a better variable for this? Maybe use the "container" date variable for the website with the expanded syntax, and "issued" for the webpage? (http://docs.citationstyles.org/en/1.0.1/specification.html#date-variables and https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra)

**Comment by adam3smith** [comment]
Yes, I guess that makes sense, although I still don't quite understand the distinction between a webpage and a website date. What is a website date? Surely it can't be the date a website was first published (because -- who cares?). But if not that, I really have no idea.

**Comment by alerac** [comment]
Hi,
Sorry for the late answer and thank you for all the valuable information.

> Yes, I guess that makes sense, although I still don't quite understand the distinction between a webpage and a website date. What is a website date? Surely it can't be the date a website was first published (because -- who cares?). But if not that, I really have no idea.

@adam3smith I totally agree with you, the website date does not really make sense. In our guide we tried to follow as much as possible the recommendations from the [National Library of Medicine](https://www.nlm.nih.gov/bsd/uniform_requirements.html#electronic), example 39. Part of a homepage/Web site. They mention the Website Copyright date along with the Publisher place and publisher metadata. We saw also in other library guides the mention of the web page date, so we tried to mix all the information because we thought that it was important. Finally in our guide we propose a more simplified reference.

> Note that it's generally not necessary to close/delete a fork on GitHub. You can just follow the instructions at https://github.com/citation-style-language/styles/blob/master/CONTRIBUTING.md#3b-submitting-changes-to-an-existing-style for updating your style.

@rmzelle Thanks, I'll do that the next time :-)

> do we have a better variable for this? Maybe use the "container" date variable for the website with the expanded syntax, and "issued" for the webpage? (http://docs.citationstyles.org/en/1.0.1/specification.html#date-variables and https://www.zotero.org/support/kb/item_types_and_fields#citing_fields_from_extra)

@rmzelle And thanks again for these two links. I was not aware of this usage of the "Extra" field for missing fields. This will probably help me a lot in the future.

**Pull request merged**
