### PR TITLE
Create cambridge-university-press-note.csl

### PR DESCRIPTION
**Pull request by POBrien333**
via https://forums.zotero.org/discussion/69540/style-request-cambridge-university-press-short-title-system-law

### CODE REVIEW

**Comment by rmzelle** [comment]
@POBrien333, this is just for the field of law, right? Maybe we should rename the style to `<title>Cambridge University Press - Law (note)</title>`.

And since https://authornet.cambridge.org/information/academic/guidelines_for_authors.asp links to many different documents, a second "documentation" link to https://authornet.cambridge.org/information/academic/downloads/Additional%20style%20guidelines%20for%20Law.pdf would be useful (if that's the only file you used).

**Comment by POBrien333** [comment]
I am not sure that this is only for law. the style is generic and has an extra .pdf for law specific style questions.

**Comment by rmzelle** [comment]
Thanks!

**Comment by POBrien333** [comment]
Turns out we'll need two styles. One generic note style and one for law specifically. there is a few small differences.

**Pull request merged**
